### ISSUE TITLE
Push query string into destination URL

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#1123]
This is a **COPY** of **Issue 1123: [Push query string into destination URL](http://code.google.com/p/yourls/issues/detail?id=1123)**, filed on Google Code before the project was [moved on Github](https://github.com/ozh/google-issues-to-github).
- Submitted on 2012-06-17T22:48:44.000Z by [llon...@gmail.com](http://code.google.com/u/112449842653656422751/)
- Status: Done

Please **review** the original issue and especially its comments. **Comments here on closed issues will be ignored**. Thanks.
## Original description

```
Hello,

I am planning to use yourls 1.5 as url shortener.

I need the query string on the Short URL to be pushed into the Redirect URL in the form:

ShortURL: http://sho.rt/XXXX?a=1&amp;b=2
RedirectURL:  http://www.my-large-url.is/test/?a=1&amp;b=2

What is the plugin best practice in order to get this functionality? Which filters or actions should I use to get better results?

Thanks,
```

**Comment by plmwebdev** [comment]
How do I pass the query string as well?

**Comment by ozh** [comment]
See plugin list

**Comment by plmwebdev** [comment]
Thanks!
