### ISSUE TITLE
change admin directory

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#1137]
This is a **COPY** of **Issue 1137: [change admin directory](http://code.google.com/p/yourls/issues/detail?id=1137)**, filed on Google Code before the project was [moved on Github](https://github.com/ozh/google-issues-to-github).
- Submitted on 2012-07-03T06:11:48.000Z by [Stevebl...@gmail.com](http://code.google.com/u/118343940187153665856/)
- Status: Duplicate

Please **review** the original issue and especially its comments. **Comments here on closed issues will be ignored**. Thanks.
## Original description

```
Hi,

Would be a nice to be able change the admin folder to something else.
Is a super simple fix:

Add in config.php:
define( 'YOURLS_ADMIN_FOLDER', 'minad' );

Change in functions.php
line: 1626
$admin = YOURLS_SITE . '/'.YOURLS_ADMIN_FOLDER.'/' . $page;

Best regards,
```

**Comment by Akila3** [comment]
is this still valid for v1.8.2?
I can't find the "$admin = YOURLS_SITE . '/'.YOURLS_ADMIN_FOLDER.'/' . $page;" in the functions.php file
