### ISSUE TITLE
Admin User management 

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#1225]
This is a **COPY** of **Issue 1225: [Admin User management ](http://code.google.com/p/yourls/issues/detail?id=1225)**, filed on Google Code before the project was [moved on Github](https://github.com/ozh/google-issues-to-github).
- Submitted on 2012-11-05T20:05:34.000Z by [pelister...@gmail.com](http://code.google.com/u/110272335112732145717/)
- Status: Invalid

Please **review** the original issue and especially its comments. **Comments here on closed issues will be ignored**. Thanks.
## Original description

```
User management by admin in case of muti user setup.
Ability to delete, add, count users from Admin interface.

Regards
pelister
```

**Comment by LeoColomb** [comment]
Ref: #1255
