### ISSUE TITLE
Simplify 'YOURLS_URL_CONVERT'

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#1284]
This is a **COPY** of **Issue 1284: [Simplify 'YOURLS_URL_CONVERT'](http://code.google.com/p/yourls/issues/detail?id=1284)**, filed on Google Code before the project was [moved on Github](https://github.com/ozh/google-issues-to-github).
- Submitted on 2013-01-22T07:52:03.000Z by [joseph.k...@gmail.com](http://code.google.com/u/103157080646358609357/)
- Status: 

Please **review** the original issue and especially its comments. **Comments here on closed issues will be ignored**. Thanks.
## Original description

```
If you put a number into the 'YOURLS_URL_CONVERT' setting that isn't 36 or 62, which can be pretty easy to do, considering the similarity of the numbers to 32 and 64, you can get some pretty strange behaviour. For example, if you try to add a url using the admin interface, the loading gif will just stay on the button forever, and not report any error.

I would suggest either implementing an error reporting if the number provided for the setting isn't 36 or 62, or simply changing it to a true/false type setting.

Thanks!
```

**Comment by FreedomFighterSparrow** [comment]
Shouldn't this be closed? yourls_get_shorturl_charset() seems to check for 62 and 64, else it defaults to 36. Therefore, wrong numbers are simply ignored.

**Comment by ozh** [comment]
You're right, the problem isn't about wrong values anymore. I think we've left this issue open because it would make much more sense to have a human readable setting instead of an arbitrary geek number.
