### ISSUE TITLE
Add sqlite support

### ISSUE THREAD

**Issue by ghost** [YOURLS/YOURLS#1337]
Hi there

I just discovered this project and thought that mysql is quite overkill for such just storing short links.

**Comment by Efreak** [comment]
Yes, it really is... I'm running my webserver on an ODroid-C1, and would prefer not to be running a database server 24/7 (php is bad enough).

**Comment by ozh** [comment]
For the record: SQLite support is but left to plugin territory.

You can easily [bypass the core DB file](https://github.com/YOURLS/YOURLS/blob/master/includes/load-yourls.php#L147:L153) and implement your own layer (probably very easily at the moment since we're still using the ezSQL lib which has sqlite support)

**Comment by Efreak** [comment]
Oh, cool. It's been ages since I did much of anything with php, but I'll take a look if I get a chance.

**Comment by farvadotnet** [comment]
I've managed to get SQLite working, somewhat. Some required SQL features aren't supported, which means plugins (can't activate them, although you can of course manually include them) and statistics are broken. Rewriting the SQL queries to be more db-agnostic or adding another code path for SQLite would fix this, but I'm not really familiar enough with SQL to do this yet. As it currently stands, it works well enough for my needs. If anyone's interested, [here's the repo](https://github.com/farvadotnet/yourls-sqlite).

**Comment by ozh** [comment]
@farvadotnet interesting!! Can't this be packaged as a full plugin instead of having to overwrite core files? If anything is missing in core to make this possible, feel free to discuss more hooks/filters/whatever is needed

**Comment by farvadotnet** [comment]
Well I could put the includes in the plugin folder, but there's still the matter of the actual SQL queries. They have to be modified to work on SQLite...I started on functions-install.php just to get it going, but I'm really outside my element here. Obviously some restructuring would be in order.

**Comment by ozh** [comment]
The option I thought would work would be to [load your DB layer](https://github.com/YOURLS/YOURLS/blob/master/includes/load-yourls.php#L147:L153) instead of all YOURLS DB files (which would be here the ezsql core file + ezsqlite) and then you have full control over queries ?

**Comment by farvadotnet** [comment]
I do that already (see [db.php](https://github.com/farvadotnet/yourls-sqlite/blob/master/user/db.php)), but that's not where the queries are; they are in the functions-*.php files in includes.

**Comment by ozh** [comment]
You're still loading core files. The idea of a custom DB layer would be to completely ignore DB core files. This way, you have full control over the methods and what they do.

**Comment by farvadotnet** [comment]
I don't see how, since the queries aren't even in the "DB core files" (the only one I'm loading, BTW, is ez_sql_pdo.php). And I could put the ez_sql_pdo_sqlite-*.php files somewhere else (except that I disagree with the judgement that a db layer can be reasonably done in a plugin without redesigning a lot of functions to explicitly support this). Unless you're suggesting implementing a translation layer for the queries, which would be (IMHO) positively insane.

**Comment by ozh** [comment]
I made something that seems to work and that doesn't require modifying core files. You'll need to update YOURLS to current master for this, I've added a [way to bypass the SQL tables creation](https://github.com/YOURLS/YOURLS/commit/fc583182659626d6cc42a1b2137a288f02367fa6) to allow SQLite tables creation instead.

See https://github.com/ozh/yourls-sqlite

**Comment by ozh** [comment]
(Ping @eric-schleicher @Efreak in case they're still interested)

**Comment by farvadotnet** [comment]
That takes care of functions-install but there's still a load of others that need to be dealt with, unfortunately.

**Comment by farvadotnet** [comment]
Nice. There's some problems with statistics, but I've got it figured out. I'll put together a report and a patch.

**Comment by Flameborn** [comment]
For anyone interested, I am maintaining an 1.7.10-compatible version at https://github.com/Flameborn/yourls-sqlite

It would be nice if this, or possibly an improved version could find its way into the official package, despite its limitations.

**Comment by ozh** [comment]
I think it's neat! Could you make a PR on https://github.com/YOURLS/awesome-yourls to list it?

**Comment by Flameborn** [comment]
Thank you. I've created one via https://github.com/YOURLS/awesome-yourls/pull/75

**Comment by eugenio412** [comment]
I've created a ready to use docker container with this SQlite patch, to avoid RAM usage, on the base of reanimus and @Flameborn work.

https://github.com/eugenio412/docker-yourls-sqlite

enjoy
