### ISSUE TITLE
Instructions to host YOURLS on Heroku

### ISSUE THREAD

**Issue by harley** [YOURLS/YOURLS#1345]
I just put YOURLS on Heroku (a cloud PaaS) successfully. Just checking if there is any interest in adding some sample files in the code or including this HowTo in the README or on a Wiki page. Googling around helped me deal with putting php on Heroku, but nothing directly related to YOURLS and its specific gotchas. So I thought writing it out may help those who are interested.

A rough list of steps:
- Modify `user/config.php` to pull credentials and sensitive info from Heroku's config vars. This is a good practice (separate admin user and db credentials from config.php), so maybe we can even add a `user/config-heroku-sample.php` so people can just rename when setting up
- Use one of the MySQL addons on Heroku (code handling the connection is reflected in `config-heroku-sample.php`)
- Add a dummy, empty `index.php` to the project root folder so Heroku recognizes this as a PHP app
- Add a `.htaccess` file to the project root folder (and push to heroku) because adding `.htaccess` dynamically from the web UI doesn't work for Heroku

**Comment by mikeatlas** [comment]
Still no merge, but I also want to add that creating a `Procfile` with contents `web: vendor/bin/heroku-php-apache2` removes deploy warnings about the default web process selection when using the empty Composer configuration.

Also, for me, same thing with ephemeral file system, password not needed to be hashed, instead it looks like:
```php
 // they're located in ENV vars on heroku, no need to hash them.
define( 'YOURLS_NO_HASH_PASSWORD', true ); 
$yourls_pass = getenv('YOURLS_PASS');
$yourls_site = getenv('YOURLS_SITE');
$yourls_user_passwords = array($yourls_admin => $yourls_pass);
```

**Comment by Tom-Fox1** [comment]
I don't personally know how but it would be cool to have one of those "Deploy to Heroku" buttons on the readme - https://devcenter.heroku.com/articles/heroku-button.

**Comment by LeoColomb** [comment]
To cover Heroku usage (and other similar services like Zeit Now) Docker images are available for YOURLS. See https://store.docker.com/images/yourls
