### ISSUE TITLE
Short URL not redirecting to long URL in Yourls 1.6

### ISSUE THREAD

**Issue by mickael78** [YOURLS/YOURLS#1350]
Hi, here I face a situation with the new 1.6 version of Yourls I don't know how to fix it (never happened with previous 1.5.1 version):
- for some short URLs the application redirects the user to the long URLs (correct), while
- for some short URLs the application redirects the user to the domain homepage instead of the long URL (incorrect).
  I suspect it's about special characters but, as I said, I don't know how to fix it so please help.

Here are the examples:

Correct behavior
Short URL: http://cauta-reduceri.com.ro/oferte/fructe-cactusi
Long URL: http://stiati.ca/fructele-anumitor-cactusi-sunt-comestibile/

Wrong behavior 1
- Short URL: http://cauta-reduceri.com.ro/oferte/test-wrong1
- Long URL: http://event.2parale.ro/events/click?ad_type=quicklink&aff_code=38bd2bac4&unique=08ac3033a&redirect_to=http%25253A%25252F%25252Fwww.sevensins.ro%25252Fcostume-sexy%25252Fobsessive%25252Fpolice-dress%25252F
- Expected destination: http://www.sevensins.ro/costume-sexy/obsessive/police-dress/
- But it loads the homepage of: http://www.sevensins.ro/

Wrong behaviour 2
- Short URL: http://cauta-reduceri.com.ro/oferte/test-wrong2
- Long URL: http://event.2parale.ro/events/click?ad_type=quicklink&aff_code=38bd2bac4&unique=91698cac4&redirect_to=http%25253A%25252F%25252Fwww.clickshop.ro%25252Ftablete-accesorii%25252Ftablete%25252Facer-iconia-b1-wifi-17-78cm-7-dualcore-8gb-gps-bt4-0-android-4-1%25252F
- Expected destination: http://www.clickshop.ro/tablete-accesorii/tablete/acer-iconia-b1-wifi-17-78cm-7-dualcore-8gb-gps-bt4-0-android-4-1/
- But it loads the homepage of http://www.clickshop.ro/

I use Yourls with Chromium browser under Ubuntu OS but I guess this is not the cause.

Please help.

Thanks.

**Comment by SoorajV1995** [comment]
use this on mysql database
`grant all privileges on database. * to serverAdmin@yourdomain identified by 'database_password'`
