### ISSUE TITLE
Yourls 1.6 Breaks QR Plugin

### ISSUE THREAD

**Issue by seandrickson** [YOURLS/YOURLS#1366]
The issue I'm having is that when you enable the QR plugin, it redirects to the home directory (when adding `.qr` to the URL).

I'm trying to figure out exactly why, but I can't wrap my head around it. My best guess might be MIME type errors or htaccess issues, but for some reason, the QR code plugin that you wrote, no longer works with the latest version.

I have confirmed that this is not a server configuration issue as this is happening on my local MAMP install, my server install (that I upgraded to 1.6) and on a few other people's installs.

I would appreciate any help. Thanks.

**Comment by jangrewe** [comment]
Just in case anybody is looking for the corresponding nginx rewrite config, i came up with this one:

```
location ~ ^/([0-9A-Za-z]+)\.qr/?$ {
        rewrite ^/(.+?)\.qr$ http://chart.apis.google.com/chart?cht=qr&chs=250x250&chl=http://$server_name/$1 last;
    }
```

**Comment by ibegyourpardon** [comment]
> Just in case anybody is looking for the corresponding nginx rewrite config, i came up with this one:
> 
> ```
> location ~ ^/([0-9A-Za-z]+)\.qr/?$ {
>         rewrite ^/(.+?)\.qr$ http://chart.apis.google.com/chart?cht=qr&chs=250x250&chl=http://$server_name/$1 last;
>     }
> ```

thanks.

nginx is the best.
