### ISSUE TITLE
Incorrect DB config, or could not connect to DB

### ISSUE THREAD

**Issue by mosfetti** [YOURLS/YOURLS#1408]
I'm sure I config it right, but still can't access.
I had the error "can't create table bla bla bla" then fixed, but I was getting "mysql version is too old bla bla bla" and then uploading the updated master version I get this error.

![schermata 2013-05-31 a 15 25 17](https://f.cloud.github.com/assets/4580135/590971/dc79aa74-c9f5-11e2-86fe-027fb521f2f1.png)

Edit: I tought it was a permission error, tryed to chmod 777 the admin dir but it won't access to the install page (sort of timeout)

EDIT2: Updated by erasing all the directory, all the databases, all the users databases, then reuploaded and recreated all. And this is what I get.

![schermata 2013-05-31 a 16 12 45](https://f.cloud.github.com/assets/4580135/591189/6b044a14-c9fc-11e2-954d-7925140d13b7.png)

**Comment by siminm** [comment]
Had the same issue, ended up needing to create the *database* manually. The error is too generic to be helpful

**Comment by ozh** [comment]
@siminm : http://yourls.org/#Install -> "Create a new database"

**Comment by siminm** [comment]
Maybe a terminology collision here, but I had to create the actual database `YOURLS_DB_NAME` within my MySQL database. The yourls user could create the table within the DB, but it wouldn't create the original database even though it had enough permissions. Simply specifying the variables needed for the configuration wasn't enough to get things working

**Comment by ozh** [comment]
Yes. You had to create a database. As explained in the readme. Not sure how things can be stated in a clearer way.

**Comment by siminm** [comment]
The text says "Create a new database (see Configuration – *you can also use an existing one*)" which makes me think that you don't *have* to use an existing one. The link to Configuration only explains the variables needed, does not explain what needs to be pre-existing.

The error that's discussed in this thread says "Incorrect DB config, or could not connect to DB" even though the DB config and the connection to the DB are correct. The only thing that was wrong is that the database within the DB did not exist.

**Comment by ozh** [comment]
"Create a new database (see Configuration – you can also use an existing one)" seems quite clear to me: either you **create** a DB, or you use an **existing** one. Seriously I don't know how to make this clearer but I'll be happy to use a clearer sentence.

**Comment by chrislange** [comment]
I'm very sure this has now been resolved many years later, however, I had the same issue today and found that forcing my config.php file to use mysql worked.

`define( 'YOURLS_DB_DRIVER', 'mysqli' );`

**Comment by kichuku** [comment]
@chrislange Thanks a LOT. I was searching everywhere on why my install wasn't working. I was pretty damn sure that the config.php file was right. Then adding the line that you have suggested made it work.

I added this line
> define( 'YOURLS_DB_DRIVER', 'mysqli' );

**Comment by transonly** [comment]
I had the same problem and it's a complete mystery to me how this was caused.
I addes the portnumber to localhost in the config file what resolved it.

define( 'YOURLS_DB_HOST', 'localhost:3306' );

**Comment by Petaflop** [comment]
Had the same problem after running Yourls 1.5.1 for two years and not changing anything. Solution: My webspace provider changed the host address of my database and I had to change my database password to a more complicated one (in my account at my provider's website). And after updating these two things in my config.php it worked again. I also upgraded to 1.7.1, but I don't know if that also helped.

@ozh Thanks a lot for Yourls, I use it on my little personal shortener baby http://15.re and it works like a charm. But please: you seem to think that everybody here except you is an idiot. After reading all these comments here I think you really have to work on your communication.

**Comment by ozh** [comment]
:)

**Comment by lanavas** [comment]
I had the same error but please left the same as the sample file

/** MySQL hostname.
 ** If using a non standard port, specify it like 'hostname:port', eg. 'localhost:9999' or '127.0.0.1:666' */
define( 'YOURLS_DB_HOST', 'localhost' );

do not change 'localhost'

Luis

**Comment by robloxspoof** [comment]
I am having the exact problem. I actually copy and pasted the user, pass, dbname, host, and port into another test php file... and no errors. Getting the same error as OP on the admin page

**Comment by robloxspoof** [comment]
Figured it out! Silly me. Just install php7.0-gd and php7.0-mysql! This should be mentioned

**Comment by ozh** [comment]
GD isn't needed. MySQL is indeed needed, as stated everywhere in the readme and the wiki.

**Comment by dhmontgomery** [comment]
My `yourls` installation has been working properly for 10 months, but in the past week or so it suddenly started through this error with no changes to the server on my part.

**Comment by LeoColomb** [comment]
> no changes to the server on my part

And no changes to the server on the host part? If you are ***sure*** no changes have been done on any part, you have to find what's wrong with your database.

**Comment by dhmontgomery** [comment]
That's what I'm looking into now. I'm hosting this on an EC2 instance, and hadn't logged into it since i set it up.

**Comment by dhmontgomery** [comment]
I have hosted my `yourls` install on an AWS EC2 instance for the past 10 months with no instance. At some point in the past week, it stopped working and started throwing the `Incorrect DB config, or could not connect to DB` error. 

Apparently some programs had stopped running on my server. I was able to fix this by `ssh`ing in and running: `sudo service httpd start`  and `sudo service mysqld start`. I'm not sure which did it but after running those (from the LAMP server setup instructions) `yourls` once again worked.

**Comment by dgw** [comment]
Might be worth looking into making sure that crashed services are restarted (how to do that depends on your init system). What probably happened is mysqld got an error and crashed, and the initd isn't configured to respawn dead services.

**Comment by zaghost** [comment]
make sure your mysql user has the appropriate privileges to use the database and create tables.

**Comment by zaghost** [comment]
for more detail, modify config.php, change 
define( 'YOURLS_DEBUG', false);
to
define( 'YOURLS_DEBUG', **true** );

**Comment by tobyw7** [comment]
For anyone that comes across this, I had the same problem. Created a new db user and assigned permissions over the db. Working again!

**Comment by charlie-nguyen-goldenowl** [comment]
hi there
I have just change 
```define( 'YOURLS_DB_HOST', 'localhost' );```
to
```define( 'YOURLS_DB_HOST', '127.0.0.1' );```
and it works!

**Comment by uglyeoin** [comment]
I had to install the "nd_pdo_mysql" PHP module then it worked.

**Comment by tbfpartner** [comment]
if someone stumbles upon this way later, with the same error but obviously a complete different problem: mariadb 11.x was the problem for me --> https://mariadb.org/post-mortem-php-and-mariadb-docker-issue/
worked fine with mariadb 10.x
