### ISSUE TITLE
how to create an index page

### ISSUE THREAD

**Issue by ebukaezeh** [YOURLS/YOURLS#1460]
i have been trying to create an index page, for example if i type http://domain.com it will redirect to http://domain.com/index.php (where i will add the homepage details), i don't know how to go about it, because there is already a .htaccess file from yourls installation,

so when i visit my site url http://domain.com, i got this page

[[[
.quarantine/
 .tmb/
 CHANGELOG.md
 CONTRIBUTING.md
 LICENSE.md
 README.md
 YOURLS-master.zip
 YOURLS-master/
 _file-manager/
 admin/
 css/
 dest/
 images/
 includes/
 js/
 pages/
 readme.html
 sample-public-api.txt
 sample-public-front-page.php
 sample-remote-api-call.txt
 sample-robots.txt
 user/
 yourls-api.php
 yourls-go.php
 yourls-infos.php
 yourls-loader.php 
]]]

please help with this thanks.

**Comment by timtam564** [comment]
> @ebukaezeh This:
> 
> ```
> # BEGIN YOURLS
> <IfModule mod_rewrite.c>
> RewriteEngine On
> RewriteBase /
> RewriteCond %{REQUEST_FILENAME} !-f
> RewriteCond %{REQUEST_FILENAME} !-d
> RewriteRule ^.*$ /yourls-loader.php [L]
> </IfModule>
> # END YOURLS
> # BEGIN INDEX-FIX
> Options -Indexes
> DirectoryIndex index.php index.html
> # END INDEX-FIX
> ```
> Note this only allow you to show index.php (if the file exist) when you type ``[http://domain.com`](http://domain.com%60) :-)

This is not working for me, it shows 403
