### ISSUE TITLE
Update doc for userpassword before 1.7 final

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#1485]
Current master for Version 1.7 generates a notice if YOURLS cannot write the config file:

> Could not auto-encrypt passwords. Error was: "cannot write file". [Get help](http://yourls.org/userpassword).
> [Click here](//) to dismiss this message for one week.

Make sure that this wiki page is updated accordingly when 1.7 ships

**Comment by tantweiler** [comment]
Why was this issue being closed? What was the solution? I have exactly the same issue.

**Comment by ozh** [comment]
This issue was a reminder to update https://github.com/YOURLS/YOURLS/wiki/Username-Passwords#faq where you will probably find a solution to your problem
