### ISSUE TITLE
Return Alternative Stats View Through API

### ISSUE THREAD

**Issue by adamdehaven** [YOURLS/YOURLS#1525]
I'm currently building an iOS app for YOURLS and would like to plot clicks on a timeline [graph] over time. I see the functionality available in the source code (i.e. on my YOURLS installation) but I'd like access to this data (im some form) through the API in order to build out functionality. Also, deleting a link by use of the API would be great (especially for an app).

Providing stats associated with dates, as well as the referrers, would give YOURLS users a whole new way of reporting data based on link clicks. I'm sure there are other stats/info people would like to pull out... feel free to comment.

**Comment by Smith454** [comment]
@LeoColomb & @ozh Has this issue been resolved? Can one now get all the information illustrated at http://yourls.org/cookie+ via API? 

@adamdehaven Did you ever find a way around this issue?
