### ISSUE TITLE
[Feature Request] Ability to create subdomains instead

### ISSUE THREAD

**Issue by j8d** [YOURLS/YOURLS#1527]
I'm trying to come up with a way to automatically create short urls as subdomains. i.e something.in.cm rather than in.cm/something. This seems like it should be pretty straightforward. Any advice?

**Comment by ahgray** [comment]
j8d or ozh has anything ever developed from this? I have a domain that I would love to your subdomain shortening for. If nothing turn key exists definietly willing to do my own configuration if I could get pointed in the right direction.
