### ISSUE TITLE
Location of API Responses

### ISSUE THREAD

**Issue by claytondaley** [YOURLS/YOURLS#1538]
I want to write an API plugin that takes a URL and attempts to select a human readable sURL keyword for that URL.  Obviously, it would be simplest to use core functions like `yourls_add_new_link()`.  However, `yourls_add_new_link()` returns a response array which is kinda awkward to parse in a plugin.  In fact, `functions.php` has several functions returning response arrays.
- My reaction is that response arrays should only be constructed inside `functions-api,php`.  If a plugin wants a response array, it can always include `functions-api.php`.
- I assume response arrays were used because some functions (e.g. `yourls_add_new_link()`) need to return several error messages ("no or malformed url" vs. "can't shorten a shorturl" vs. "keyword already exists", etc.).
- I suggest (over time) replacing response arrays in `functions.php` with try/throw/catch logic.  Core functions can throw several different exceptions as a means of (eventually) generating different response codes.

Obviously, I _can_ parse response arrays in my plugin if this isn't a desirable direction for YOURLS.  However, I would rather spend time upgrading `functions.php` (and the related code in `functions-api.php`) if my general proposal is acceptable.

If we go this route, I'd also like some guidance on backwards-compatibility:
- Should I upgrade the YOURLS core functions (possibly breaking plugins that make calls to them) or extract the try/throw/catch logic into new functions?
- If we move the (now exception-generating) logic into new functions, I'd like some guidance on the naming scheme.
- Finally, some of the filters currently run on response arrays.  Seems like we either change their parameters (backward incompatible) or note that their scope is reduced to API calls (better if we could rename them but that would defeat the purpose).  How do you want to handle situations like this?

**Comment by ozh** [comment]
API and return responses have evolved over the years, I think this issue is outdated. Closing -- anyone feel free as usual to re-open if I'm missing something.
