### ISSUE TITLE
Documentation for 1.7 : proxy support

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#1566]
See https://github.com/YOURLS/YOURLS/wiki/Proxy-Support

**Comment by xsoft** [comment]
Thanks?

Btw, please disable or remove plugin "HTTP-Proxy". or other people like me will search why this plugin is not working. https://code.google.com/archive/p/yourls-http-proxy/

note:
`function yourls_get_remote_content( $url,  $maxlen = 4096, $timeout = 5 ) {
	yourls_deprecated_function( __FUNCTION__, '1.7', 'yourls_http_get_body' );
	return yourls_http_get_body( $url );
}`

**Comment by ozh** [comment]
?

Also: ??
