### ISSUE TITLE
[Question/Feature] Capital Letters

### ISSUE THREAD

**Issue by Slind14** [YOURLS/YOURLS#1588]
Hey,

I just noticed if you enter capital letters into the "Custom short URL" field they get removed. So I thought ok lets do everything lowercase and link the shorturl with some uppercrase letters that it looks cleaner. But somehow this doesn´t work.
1. Is it possible to ignore case sensitive ?
2. Would it be possible to allow uppercase letters in a short url ?

**Comment by JoshFialkoff** [comment]
Hi,
Is there an update on allowing mixed-case urls, with both upper and lowercase characters?

**Comment by leduyquang753** [comment]
Definitely. Simply change the config to use base 62 (0-9; a-z; A-Z):

define('YOURLS_URL_CONVERT', 62);

However, changing this will probably make other short URLs created before break.

**Comment by JoshFialkoff** [comment]
Thanks @leduyquang753! I did that in /user/config.php, but it did not help with the fjmp.us/Case-Study/.
What else do you recommend?
<img width="700" alt="config php - cpanel file manager v3 2018-11-29 10-05-49" src="https://user-images.githubusercontent.com/3923170/49230765-62b27b00-f3be-11e8-8430-24809b5230c6.png">

**Comment by JoshFialkoff** [comment]
Sorry... I had put it at the end, rather than updating the existing setting. Here's a screenshot of the corrected file.
<img width="699" alt="config php - cpanel file manager v3 2018-11-29 10-07-02" src="https://user-images.githubusercontent.com/3923170/49230841-9b525480-f3be-11e8-9733-fd50c719d595.png">
I tested it on https://fjmp.us/Case-Study, but that url redirects to https://fjmp.us/ rather than redirecting to the correct url (https://forwardjump.com/about/josh-fialkoff/case-study/).

**Comment by leduyquang753** [comment]
It's the 77th line. Change 36 to 62.

**Comment by JoshFialkoff** [comment]
Thanks! I realized that and made that change, but it hasn’t affected
fjmp.us/Case-Study.

**Comment by leduyquang753** [comment]
Please check the URL list again because the links are probably changed.

**Comment by JoshFialkoff** [comment]
Thank you so much for your quick replies, @leduyquang753! Here's a video showing that the links have updated but the url does not redirect correctly: http://take.ms/5P3mcV.

**Comment by leduyquang753** [comment]
I didn't have time and bandwidth to watch a video, sorry. But maybe the problem was the hyphen in the link. You can try creating a different URL using 0-9; a-z and A-Z only, e.g. CaseStudy and report back to me it it works.

**Comment by LeoColomb** [comment]
@JoshFialkoff Please clear you browser cache, or test with a fresh private session.

**Comment by leduyquang753** [comment]
Firstly, did CaseStudy work?

Secondly, you can create a directory Case-Study in your web folder and make an index.html with a meta to automatically redirect it.
Or, you can try clearing your browser cache to see if the old way works.

**Comment by JoshFialkoff** [comment]
OK. Thanks. I tried both of those methods, but they did not work.
Thanks again for all of your help!
Hopefully I can find a way to fix this.
