### ISSUE TITLE
Bootstrap adaptation issues

### ISSUE THREAD

**Issue by LeoColomb** [YOURLS/YOURLS#1621]
- [x] Responsive  

https://github.com/YOURLS/YOURLS/pull/1383#issuecomment-31287060 :
- [x] Alerts
- [ ] Search form
- [x] Powered by YOURLS

**Comment by omidfi** [comment]
Does it mean that in version 2.0 the admin panel will be responsive?

**Comment by LeoColomb** [comment]
@omidfi Yes! :smile:
