### ISSUE TITLE
Add X-YOURLS header

### ISSUE THREAD

**Issue by LeoColomb** [YOURLS/YOURLS#1648]
Following an @ozh proposal, it could be really cool to add these headers:
- `X-YOURLS` for every pages (?)
- `X-YOURLS(-API)` when it's a API call.

**Comment by ozh** [comment]
Custom headers shouldn't be named "X-Something", just "Something" ([RFC](https://tools.ietf.org/html/rfc6648))

**Comment by LeoColomb** [comment]
Actually no worth at all anymore
