### ISSUE TITLE
URL Encoding gets decoded before saving to db.

### ISSUE THREAD

**Issue by Arujei** [YOURLS/YOURLS#1651]
When shorting this URL:
/Page.jsp?tI=ND6AWbgS5U4ky08ndJoxQg%253D%253D&uI=sA2%252BUi1VNUjpVsdS0GJGtw%253D%253D

it gets saved as:
/Page.jsp?tI=ND6AWbgS5U4ky08ndJoxQg==&uI=sA2+Ui1VNUjpVsdS0GJGtw==

Looks the URL encoding gets decoded.

**Comment by davidolrik** [comment]
> Similarly if someone enters http://example.com/hello world%20yay, the end result should be http://example.com/hello%20world%20yay and not double-encoding the second %20.

I disagree here, if I enter a url with the characters %20 in it I expect it to be encoded as %2520 - you can't mix entering stuff to be encoded, and stuff that shouldn't be encoded.

In your example above you *should* double encode the second %20, as you can't have a url both be unencoded and encoded at the same time.

**Comment by SirLouen** [comment]
davidolrik, I disagree with you. Why just never encoding and suggest manual encodings by users (or a tool to help encoding, but no pre-suppose encodings when not needed that fool the whole system?
Or maybe a tick button in line ("Encode URL?") 
From what I've seen the issue goes beyond to other functionalities (like editing updating information in the admin panel)
https://github.com/YOURLS/YOURLS/issues/1973
For example when I change the Title, the not-coded url fallsback to an encoded url (breaking the functionality that the fix from ozh provided)

**Comment by davidolrik** [comment]
@SirLouen I agree, that no encoding at all is a better choice - but if you choose to encode, you should encode all of the string and not try to guess whether or not some part of the string is already encoded.

**Comment by SirLouen** [comment]
Exactly trying to guess the proper string, is the problem because then you have to implement a lot of rules and plugins to adapt to infinite possible combinations.
Now I'm looking how to solve this issue in different parts of the code, because it only works for me during the creation with the plugin mentioned here.

**Comment by ozh** [comment]
The solution is not "never encode" nor "never decode". It depends on the context in which URL are added to the DB: shortening using API, shortening using bookmarklets, shortening using manual input, or editing in the admin interface.

**Comment by davidolrik** [comment]
The solution is to always do the same everywhere, and I'm leaning towards never encode.

**Comment by Ben-Mack** [comment]
@ozh Can you put `Don't encode/decode` to the plugin list? It's take me hours to found this solution.
( Another vote for no encoding at all, as I can see that's what goo.gl bit.ly do )

Thank you for develop this great url shortener!

**Comment by LeoColomb** [comment]
@Ben-Mack Thanks for your feedback!
Would you aim to create a PR on [awesome-yourls](https://github.com/YOURLS/awesome-yourls) to add the plugin? 💯

**Comment by kristianserrano** [comment]
I don't know if this is the same issue or not, but when I try to shorten a permalink generated by [Trumba](https://www.trumba.com/), it encodes any % as %25 in the URL.
For example,
http://web.library.emory.edu/news-events/upcoming-classes.html?trumbaEmbed=view%3Devent%26eventid%3D128996992
gets rewritten as this:
http://web.library.emory.edu/news-events/upcoming-classes.html?trumbaEmbed=view%253Devent%2526eventid%253D128996992

Any suggestions on how to work around or fix this?

**Comment by e-anima** [comment]
The Plugin in from ozh is so great. As i had a lot of parameterized urls that uner no cirumstances are allowed to be changed in any way, thsi is the solution.

**Comment by ozh** [comment]
Closing: 2691 and associated PR will supersede
