### ISSUE TITLE
Icon next to "Short URL" label on stats page broken

### ISSUE THREAD

**Issue by fallingrock** [YOURLS/YOURLS#1656]
The icon next to the "Short URL" label on the stats page shows as a broken image.

The generated HTML shows an empty IMG src.

![screenshot00267](https://f.cloud.github.com/assets/4029821/2438576/59ad7b1a-adf3-11e3-93c5-e0b7d1aca192.png)

The bug appears to be in the yourls_favicon function in functions.php.  If the $favicon variable isn't null, it just returns the value ... ignoring the $echo parameter.

**Comment by seventhsite** [comment]
Also in 2.0 something wrong may be in https://github.com/YOURLS/YOURLS/blob/2.0/yourls-infos.php:255
I have double favicon image url in short link on statistics page.

```
<td>Short URL</td>
<td>
<img src="http://site.com/assets/img/favicon.icohttp://site.com/assets/img/favicon.ico">
</td>
```

### Technical details

* YOURLS version: 2.0
* PHP version: 7.0.7

**Comment by ozh** [comment]
@seventhsite thanks for spotting!

**Comment by seventhsite** [comment]
I don't want to start new issue for a little error, I post here, if you don't mind.
In 2.0 on refferers tab of stats page link to "details" don't work. It's lines 487-488 in https://github.com/YOURLS/YOURLS/blob/2.0/yourls-infos.php. 
Maybe wrong ID's, or empty href='', or spoiler need <div>... Don't know now.
