### ISSUE TITLE
Problems when using bookmark on secure sites.

### ISSUE THREAD

**Issue by dervondenbergen** [YOURLS/YOURLS#1662]
When I'm trying to short an url from a site which uses https, it isn't working because the my yourls installation is served via http.

This is the error log, I get on https://gist.github.com:

```
[blocked] The page at 'https://gist.github.com/dervondenbergen/a600dd5dcb1895633f17' was loaded over HTTPS, but ran insecure content from 'http://s.demont.is/admin/index.php?up=https%3A&us=%2F%2F&ur=gist.github.com%2Fdervondenbergen%2Fa600dd5dcb1895633f17&t=testing.md&k=gist&jsonp=yourls': this content should also be loaded over HTTPS.
```

It is also not possible to make a XMLHttpRequest to the url, because there is no Access-Control-Allow-Origin header.

So it is only possible to save a https:// url via the admin interface.

**Comment by dylanh724** [comment]
I've reproduced this - Access-Control-Allow-Origin

**Comment by johnyradio** [comment]
easy fix: the Custom Shorten tool works with no problem on secure sites.
