### ISSUE TITLE
"URL already exists" should be more helpful

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#1676]
When you shorten a URL that already exists, the error message should also tell you its short URL, so you don't have to search for it

**Comment by atnbueno** [comment]
How about adding just ```. " ($shorturl)"```?

**Comment by adigitalife** [comment]
I actually created a plugin for this a long time ago on Google Code.  I've now added here on Github for reference: https://github.com/adigitalife/yourls-change-error-messages

**Comment by master3395** [comment]
I belive @adigitalife 's plugin should be a thing. As you don't know what line, the url is on.
