### ISSUE TITLE
YOURLS strips encoded linefeed and carriage return from URLs

### ISSUE THREAD

**Issue by ip2k** [YOURLS/YOURLS#1694]
In this block in includes/functions-formatting.php (lines 486-491):

```
        $url = preg_replace( '|[^a-z0-9-~+_.?#=!&;,/:%@$\|*\'()\\x80-\\xff]|i', '', $url );
        // Previous regexp in YOURLS was '|[^a-z0-9-~+_.?\[\]\^#=!&;,/:%@$\|*`\'<>"()\\x80-\\xff\{\}]|i'
        // TODO: check if that was it too destructive
        $strip = array( '%0d', '%0a', '%0D', '%0A' );
        $url = yourls_deep_replace( $strip, $url );
        $url = str_replace( ';//', '://', $url );
```
it looks like we're purposely stripping %0D and %0A (and their lower-case versions).

In some cases, these are useful to have in a URL. One such use-case I ran into was copying and pasting links to/from an application that encodes a SQL-like query into the URL to be shared around. With YOURLS currently, it strips the newlines, and if the user doesn't remember to include spaces, the query no longer works. If they do include spaces as well as newlines, the query still doesn't hold the same formatting. Commenting out the "$strip = " and the next line solves this problem for me (possible with a plugin? Probably...).

I looked for RFCs specifying if the URL should / should not contain CR / LF, but couldn't find anything solid. Is there a reason that these are stripped?

EDIT: I'm aware of https://www.acunetix.com/websitesecurity/crlf-injection/ but don't really understand if it's necessary to deep-replace the URLs like this due to CRLF injection.

Thanks!

**Comment by ozh** [comment]
(*In case someone is still following this issue... :-P*)

Yeah, this is to prevent CRLF injection. The use case described here (SQL thingies shared by URLs) is too specific and better fixed with a custom plugin
