### ISSUE TITLE
Apostrophe Encoding Issues with bookmarklets

### ISSUE THREAD

**Issue by ardichoke** [YOURLS/YOURLS#1698]
When sharing a shortened link via the link stats page (or from the page the shorten bookmarklet takes you to), if the title has an apostrophe in it, the resulting tweet will replace the apostrophe with `&#039;`. This happens to me in multiple versions of Firefox, including the most recent,  though I have not tested other browsers. I have noticed that if you click the "share" button on the main YOURLS admin page, and share to twitter from there, this issue does not happen. Additionally, if you're on the link admin page, and you edit the quick share text, any apostraphes you type in will work as expected and not be replaced.

**Comment by ozh** [comment]
Fixed somewhere along the road, not sure when...
