### ISSUE TITLE
Add Specific Code to Header of Redirect page at url Creation

### ISSUE THREAD

**Issue by morphers82** [YOURLS/YOURLS#1702]
I am trying to figure out how I can add the ability to add code specifically to the html head of the redirect page that is specific to the individual shortened urls.
What I specifically want to do is to add a retargeting pixel code from facebook to the redirect page. This code will be different for each shortened url, so I would want to be able to add it when creating/editing an individual shortened url.
Is there a way to do this now?

**Comment by DrTuttle** [comment]
This is such an important feature... literally the only reason I'm using yourls.  
I'm trying to write a plugin to do the same thing... I would appreciate some help with this.  

I'm having a hard time believing no one has done this... does anyone have an example?
