### ISSUE TITLE
Add Official Support for Nginx

### ISSUE THREAD

**Issue by ZacharyDuBois** [YOURLS/YOURLS#1715]
Nginx is becoming a very widely used httpd lately. YOURLS should have some official support for the httpd so it can be used on more platforms. All you need to do is make a config for us Nginx users in the wiki :P

**Comment by member0123** [comment]
I have wordpress installed on domain.com  , and yourls installed on domain.com/url
wordpress is working well but when I try to open yourls links, I get the 404 not found error of wordpress. 
this is my default nginx.conf http://p.ngx.cc/14
can you edit it for me please .

**Comment by snoow** [comment]
Hey guys,
Moved my host from apache to nginx and after using the default config, and trying a million other things I am still having a few lingering issues:

URL stats results in a 403 error
heading to the root URL where yourls is hosted, results in nginx serving the /admin/index.php file rather then executing it.

Any tips appreciated...
Thanks

**Comment by dk253** [comment]
I'm not sure if this helps this conversation.  But I was pulling my hair out about this.  I diligently went through all of your potential fixes with no luck.  Because I am cheap I am running yourls on the same machine as wordpress multisite.  

I'm really not sure what the interaction was but when I renamed the admin folder from 'admin' to 'booger' and then the url references in the php files, it all started to work.  There was something about the word 'admin' that (I believe) wpmu was screwing with.

**Comment by ZacharyDuBois** [comment]
Here is my newer config. I should've updated this here awhile ago.

```nginx
server {
  listen 80;
  listen [::]:80;

  server_name domain.tld;

  return 301 https://domain.tld $request_uri;
}
server {
  listen 443 ssl spdy;
  listen [::]:443 ssl spdy;

  root /srv/http/site/public;
  index index.php index.html index.htm;

  server_name domain.tld;

  add_header Strict-Transport-Security "max-age=31536000; preload";
  add_header Alternate-Protocol 443:npn-spdy/3,443:npn-spdy/2;
  add_header X-Frame-Options DENY;
  add_header X-Content-Type-Options nosniff;

  spdy_headers_comp 6;
  ssl on;
  ssl_certificate /etc/nginx/ssl/ssl.crt;
  ssl_certificate_key /etc/nginx/ssl/ssl.key;
  ssl_stapling on;
  ssl_stapling_verify on;
  ssl_trusted_certificate /etc/nginx/ssl/trustchain.crt;

  location ~ /\. {
    deny all;
  }
  
  location /user {
    # Note: Remove this if you have plugins that load images or JS (Like random background images).
    deny all;
  }

  location / {
    try_files $uri $uri/ /yourls-loader.php;
  }

  # Pass PHP files to FPM.
  location ~* \.php(?:$|/) {
    fastcgi_split_path_info ^(.+\.php)(/.+)$;
    fastcgi_pass unix:/var/run/php5-fpm.sock;
    fastcgi_index index.php;
    fastcgi_buffers 8 16k;
    fastcgi_buffer_size 32k;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param PATH_INFO $fastcgi_path_info;
    fastcgi_param HTTPS on;
  }

  location ~*.(jpg|jpeg|png|gif|ico|css|js)$ {
    expires 30d;
  }
}
```

**Comment by toleabivol** [comment]
Hello , 

in order to make yourls work with plugin "Redirect with GET paramaeters" on nGinx you need to keep the query args : 

    try_files $uri $uri/ /yourls-loader.php?$query_string;

**Comment by skeith** [comment]
Hi guys, I need help

I am using this nginx config but I kept getting 403

```
server {

  # Listen IPv4 & v6
  listen 80;
  listen [::]:80;

  # Server names
  server_name s.yukirin.xyz;

  # Root directory (NEEDS CONFIGURATION)
  root /home/yourls;
  index index.php index.html

  # Rewrites
  location / {

    # Try files, then folders, then yourls-loader.php
    # --- The most important line ---
    try_files $uri $uri/ /yourls-loader.php;

    # PHP engine
    location ~ \.php$ {
      try_files      $uri =404;
      fastcgi_pass   unix:/var/run/php7-fpm.sock; # Can be different
      fastcgi_index  index.php;
      fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
      include        fastcgi_params;
    }
  }
}
```

**Comment by skeith** [comment]
I fixed my error 403 with this config

```
server {
    listen      80;
    server_name example.xyz;
    root        /home/yourls;

    access_log /home/yourls/logs/access.log;
    error_log /home/yourls/logs/error.log;

    index index.php;

    location / {
        try_files $uri $uri/ /yourls-loader.php;
        expires 14d;
        add_header Cache-Control 'public';
    }

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_intercept_errors off;
        fastcgi_buffer_size 16k;
        fastcgi_buffers 4 16k;
    }
}
```

**Comment by cloudymous** [comment]
Hello. I follow this instruction https://github.com/YOURLS/YOURLS/wiki/Nginx-configuration

But it's instead downloading the yourls.php than opening my generated link.

What's wrong with my config?
`server {
	listen 80;
	listen [::]:80;	

	listen 443 ssl http2 default_server;
	listen [::]:443 ssl http2 default_server;

	root $MYDOCROOT;

	index index.php index.html index.htm index.nginx-debian.html;

	server_name $SERVERNAME;
	
	include snippets/$SSLCONF.conf;
	include snippets/SSLPARAMS.conf;

	location / {
		try_files $uri $uri/ /yourls-loader.php =404;
	}	

	location ~ \.php$ {
		include 	snippets/fastcgi-php.conf;
		fastcgi_pass 	unix:/run/php/php7.0-fpm.sock;
		fastcgi_param	SCRIPT_FILENAME $document_root$fastcgi_script_name;
		include		fastcgi_params;
		
	}
	
	location ~ /\.ht {
		deny all;
	}
	
	location ~ /.well-known {
		allow all;
	}
}`
Btw, what's default permission for all files and folder in YOURLS?

I used 755 for folder and 640 for files.

**Comment by skeith** [comment]
@cloudymous 
yours `fastcgi_pass unix:/run/php/php7.0-fpm.sock;`
should be `fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;`

**Comment by cloudymous** [comment]
@skeith I have change that and still download .php files when i try to visit generated link.

I also follow your configuration up there but still download the .php file.

**Comment by lilmike** [comment]
Hi all,
I'm using the config from the wiki, with the exception of try_files $uri $uri/ /yourls-loader.php index.php?$args /index.php?$args;
However, when I go to mysite/<page here> it tries to download it as a file. I tried /pages/page.php, but that said I was accessing an unallowed area and I was redirected back to the homepage.
Any thoughts?
-Michael.

**Comment by lilmike** [comment]
With more digging, it's turned out it's downloading the yourls-loader.php. So somehow try_files isn't telling nginx it's a php file. Very odd.

**Comment by lilmike** [comment]
For some reason putting the index.php?$args /index.php?$args before /yourls-loader.php fixed it.
-Michael.

**Comment by lilmike** [comment]
Hi again,
I was trying to get rid of the clunky ifs I had to put in to get both a public homepage and the redirects to work, and I thought that I must've just made a stupid mistake with the original configuration, as it seems like /yourls-loader.php would return 404 or similar if it didn't find the url, and would then pass to the next php file. However, it still tries to download the /yourls-loader.php. Any thoughts?
-Michael.

**Comment by dakanji** [comment]
The configuration given here: https://github.com/YOURLS/YOURLS/wiki/Nginx-configuration as modified for proxying PHP to Apache does not work.

```
server {

  # Listen IPv4 & v6
  listen 80;
  listen [::]:80;

  # Optional SSL stuff
  listen              443              ssl;
  listen              [::]:443         ssl;
  ssl_certificate     example.com.crt;
  ssl_certificate_key example.com.key;
  
  # Server names
  server_name example.com www.example.com;

  # Root directory (NEEDS CONFIGURATION)
  root /path/to/files;

  # Rewrites
  location / {

    # Try files, then folders, then yourls-loader.php
    # --- The most important line ---
    try_files $uri $uri/ /yourls-loader.php;

    # PHP engine
    location ~ \.php$ {
      try_files      $uri =404;
      proxy_pass   https://example.com:8080; # Can be different
      include        proxy_params;
    }
  }
}
```

To make is work for such, I changed this

```
    # Try files, then folders, then yourls-loader.php
    # --- The most important line ---
    try_files $uri $uri/ /yourls-loader.php;

```

to 

```
    # Try files, then folders, then yourls-loader.php
    # --- The most important line ---
    try_files $uri $uri/ /yourls-loader.php$request_uri;

```

Then in includes/functions.php, I changed function yourls_get_request as so:

`	return yourls_apply_filter( 'get_request', $request );
`


to

```
	/*  HACK for Nginx Proxying PHP to Apache: 
	 *  Defaults on project site assume PHP-FPM fastcgi
	 *  Therefore configs given do not work
	 *
	 *  This hack here removes "yourls-loader.php" from url if it exists
	 *  Can coexist with PHP-FPM fastcgi setup
	 *
	 *  In Nginx conf, use:
	 *      "try_files $uri $uri/ /yourls-loader.php$request_uri;"
	 *      Instead of
	 *      "try_files $uri $uri/ /yourls-loader.php;"
	 */ 
	if( preg_match( "@yourls-loader\.php\/@", $request ) ) {
		$request = str_replace( "yourls-loader.php/", "", $request );
	}
	
	return yourls_apply_filter( 'get_request', $request );

```

**Comment by tofuSCHNITZEL** [comment]
I had to use
`if (!-e $request_filename){
	rewrite ^(.+)$ /yourls-loader.php?q=$1 last;
}`

instead of `try_files $uri $uri/ /yourls-loader.php;`

to make https://github.com/joshp23/YOURLS-IQRCodes work

**Comment by dakanji** [comment]
@tofuSCHNITZEL. The try_files directive is preferred over `!-e $request_filename`. See https://www.nginx.com/resources/wiki/start/topics/tutorials/config_pitfalls/#check-if-file-exists

See the note in my earlier comment suggesting `try_files $uri $uri/ /yourls-loader.php$request_uri;`. That needs an accompanying edit in `includes/functions.php`. For your case, you could consider `try_files $uri $uri/ /yourls-loader.php?p=$request_uri;`

**Comment by tofuSCHNITZEL** [comment]
@dakanji unfortunately even with your suggested functions.php edit none of the try_files directives work for me

**Comment by dakanji** [comment]
@tofuSCHNITZEL The edit to functions.php goes specifically and only with the implementation of try_files that I had

Since `if (!-e $request_filename){ rewrite ^(.+)$ /yourls-loader.php?q=$1 last; }` works for you, then **DO NOT** edit functions.php and use:

`try_files $uri $uri/ /yourls-loader.php?q=$request_uri;`
or
`try_files $uri $uri/ /yourls-loader.php?q=$uri;` 

That is, make no changes apart from swapping the `if (!-e $request_filename)...` line with one or the other of the try_files lines in this message.

**Comment by tofuSCHNITZEL** [comment]
I tried all of the different combinations. but none except the "if" works for me... I guess it has something to do with the plesk panel generated nginx directives....

**Comment by PopVeKind** [comment]
Just a question...

**Has anyone considered using the EasyEngine settings as a roadmap?**  At least for Ubuntu and Debian. The server settings for YOURLS and WordPress are nearly identical.    A lot of people have put their time and effort into making that easy and workable.

> _EasyEngine (ee) is a Python tool to easily manage your WordPress websites with Nginx, supported on Ubuntu and Debian Linux Distributions._

I'm getting ready to set up my first Nginx + https YOURLS MultiSite with WordPress MultiSite (EasyEngine) sharing the document root **#2335** and am looking at Nginx server settings.

**Comment by angelcosta** [comment]
@PopVeKind Did you get it working? I am struggling right now with the conf. I can't get it to redirect.

**Comment by PopVeKind** [comment]
@angelcosta - I currently have everything (except https) working on a shared hosting Apache.  I currently have no access to Nginx (expecting a Linode within a week).  Before I retired I used EasyEngine to build Nginx WordPress sites (Single and MultiSites), which I considered solid production sites.

## Helpful Tips
1. Get answers to the questions asked at https://github.com/PopVeKind/YOURLS/issues/3
2. Remove all Plugins until you have the basic site working.

Help Offered
As part of my research into Best Practices, I am willing to help you get your conf. working.
1. Navigate to https://github.com/PopVeKind/YOURLS/tree/multisite
2. Open a new issye for your conf. file.
3. Answer the questions asked at https://github.com/PopVeKind/YOURLS/issues/3

**Comment by skeith** [comment]
For people who need HTTPS configuration on nginx, here is my config

```
server {
    listen      80;
    listen      443 ssl;
    server_name YOURDOMAINHERE;
    root        /home/YOURLSPATH;

    access_log /home/YOURLSPATH/logs/access.log;
    error_log /home/YOURLSPATH/logs/error.log;


    index index.php;

    location / {
        try_files $uri $uri/ /yourls-loader.php;
        expires 14d;
        add_header Cache-Control 'public';
    }

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_intercept_errors off;
        fastcgi_buffer_size 16k;
        fastcgi_buffers 4 16k;
        fastcgi_param HTTPS on;
    }
}
```

**Comment by angelcosta** [comment]
For any of you out there using EasyEngine, I managed to get it working by editing /etc/nginx/commmon/php.conf
there I added only 
`    location / {
        try_files $uri $uri/ /yourls-loader.php;
        expires 14d;
        add_header Cache-Control 'public';
    }`

**Comment by PopVeKind** [comment]
@skeith - Thank You, that was a shove in the right direction.

## Here's my ultimate goal.
1. Anything coming in for redirection should work.
Accept Both `IP4` and `IP6`
Accept Both `HTTP` and `HTTPS`
Accept Both `www.` and `no-www.`
2. Something for `/admin/`
Accept Both `IP4` and `IP6`
Accept Only `HTTPS`
Accept Only `no-www.`

The idea is to lock down the admin server, and speed up the redirection server (no multiple redirects)..
`cu.te/abc` may be **_typed_** as `www.cu.te/abc` and different browsers may default to `https` or `http`

**Comment by PopVeKind** [comment]
@angelcosta - Thanks for the specific info on the EasyEngine conf.
## EasyEngine
A couple friends (acquaintances) in the EE camp are interested in the prototype YOURLS Plugins (described in the #2335 Patch):
- **YOURLS MultiSite Plugin** (one install to manage several domains)
- **WordPress Plus YOURLS Plugin** (working together without conflict, addressed in the document root directory - no subdirectory for either!)

If EE added support for these, it would be a nice boost for the YOURLS community.

**Comment by LeoColomb** [comment]
Thanks everyone for your your contributions! 🎉 🙏 
I've made a full review of the nginx configuration for YOURLS based on your suggestions, and updated the [respective documentation](https://github.com/YOURLS/YOURLS/wiki/Nginx-configuration). It's tested and approved on last versions of pieces of software involved.
Please take a look and let me know what are your thoughts! Thanks again! 👍
