### ISSUE TITLE
Aplication out of ar

### ISSUE THREAD

**Issue by joaocaetano** [YOURLS/YOURLS#1719]
I instaled Yourls today but the admin was redirecting to http://www.salesforce.com/platform/overview/?d=70130000000liBh

The aplication is out of ar?

**Comment by kamijoutouma** [comment]
MOST ANNOYING THING ever but okay 
why was this like super hard to find ...

**Comment by shoeper** [comment]
This isn't super hard to find. This won't occur if one just reads how to install yourls.
If you DO NOT want to inform yourself about softwar DO NOT install it.

**Comment by kamijoutouma** [comment]
I actually read the wiki and it didn't have any info about this.

Also I usually don't waste my time with closed issues. Because more then half the time it's either fixed issues or people tryna steal shit.
