### ISSUE TITLE
can't install yoursl

### ISSUE THREAD

**Issue by vyskoczilova** [YOURLS/YOURLS#1754]
Hi,

I'm not able to install yoursl and don't know why - I've created a MYSQL database for it. Changed config.php, clicked on install in admin page and I've got these errors:

Error creating table 'yourls_url'.
Error creating table 'yourls_options'.
Error creating table 'yourls_log'.
Error creating YOURLS tables.
File .htaccess successfully created/updated.

But in my MYSQL tables were actually created and they are not empty. If I enter again http://url.kybernaut.cz/admin/ it waits for loggin, but if I fill the name and pwd nothing happens.

What's wrong? Thanks for advices.
Best regards
Karolina Vyskocilova

**Comment by zaghost** [comment]
for more detail, modify config.php, change
define( 'YOURLS_DEBUG', false);
to
define( 'YOURLS_DEBUG', true );
