### ISSUE TITLE
Setup Categories to sort Short-URLS

### ISSUE THREAD

**Issue by wci-aw** [YOURLS/YOURLS#1763]
Hi may I missed something, but cannot find a solution in how to categorize shorten links to enable a sort option. e.g. of Domains or special created folders and sub-folders where links could be implemented and sorted. 

Is there anything out there in how to categorize and sort shorten Link-Urls? Would be great to get an App for this or advice in how to setup this.

Alex (not a developer or coding specialist...)

**Comment by WillianBR** [comment]
There is any kind of NameSpace support in YOURLS?    I have the CLASH problem!
