### ISSUE TITLE
Sorry - cannot get past endless spinning icon when adding URL (secure or otherwise)

### ISSUE THREAD

**Issue by justkristin** [YOURLS/YOURLS#1766]
I am running YOURLS 1.7 on:
   Ubuntu 12.04.3.LTS
   Apache 2.2.22
   PHP 5.3.10
   MySQL 5.5.38
Curl is installed.
mod_security is not installed. (https://github.com/YOURLS/YOURLS/wiki/Endless-Spinning-Icon)
mod_rewrite is installed and enabled.
.htaccess looks like this:
   # BEGIN YOURLS
   <IfModule mod_rewrite.c>
   RewriteEngine On
   RewriteBase / 
   RewriteCond %{REQUEST_FILENAME} !-f
   RewriteCond %{REQUEST_FILENAME} !-d
   RewriteRule ^.*$ /yourls-loader.php [L]
   </IfModule>
   # END YOURLS
Nothing else is installed in that doc root; The install has its own subdomain:
   sd.gozoo.org (aliases: gozoo.org, www.gozoo.org)
Apache is configured with AllowOverride ALL
All files in the directory are owned by apacheuser
The only errors in the apache error log are "Directory index forbidden by Options directive"
[Caveat]
Had to change the line mentioned in https://github.com/YOURLS/YOURLS/issues/1652
to get login to work:
setcookie('yourls_username', yourls_salt( $user ), $time );
I tried adding the lines mentioned here (not by line number, but by relative location to lines in example):
http://www.davewooding.com/yourls-not-working/
but no luck.
Can anyone tell me what else I may have pooched? Sorry to be a bother, but I am a bear of very little brain.

**Comment by olexandrbig** [comment]
justkristin commented on 23 Sep 2014

i have the same problem, did anybody find how to fix this

**Comment by olexandrbig** [comment]
fixed when i have worked in url without www. in start, so problem is in .htaccess

**Comment by LeoColomb** [comment]
> so problem is in .htaccess

Do you have details?
