### ISSUE TITLE
Investigate CORS related problems

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#1767]
As mentionned in #1766 : 
- suggest use of .htaccess CORS trick? see http://dev.nuclearrooster.com/2011/01/03/cors-with-apache-mod_headers-and-htaccess/
- add to PHP headers? http://enable-cors.org/server_php.html

But first:
- investigate why it would fail with some hosts?
- any side effects adding this to everyone?

**Comment by niketdesai** [comment]
Hello ozh!

I'm encountering this issue (w/ DreamHost) and the .htaccess trick didn't seem to be fruitful for me. With regards to the PHP headers would I add that to the admin scripts only? 

If I can sort out how to get past this issue I'll at least provide an explanation for a workaround until it's decided whether this needs to be globally addressed in YOURLs itself.

Thanks
/nnd

**Comment by ozh** [comment]
See #2094
