### ISSUE TITLE
Short URLs and Facebook

### ISSUE THREAD

**Issue by YOzaz** [YOURLS/YOURLS#1773]
Hey guys,
Not 100% sure, but it looks like Facebook has changed the way links sharing works from last Saturday morning. Now if you'll try to post shortened link to your wall or a page - Facebook will reveal final URL and will use it instead. So no clicks will be counted in Yourls service...
I'm still not sure does Facebook just follows to the last URL 301 redirect, or takes it from meta data.
Any ideas how to "fix" this?

**Comment by joshp23** [comment]
I realize this is closed for some time, but it may be helpful to know that if you use the [Hide Referrer](https://github.com/Sire/yourls-hide-referrer) plugin, Facebook sticks with the short url, but like ozh mentions, there is no thumbnail.
