### ISSUE TITLE
URLs with ' cannot be edited & saved

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#1801]
Examples: https://www.google.com/search?q=it's+cool or https://www.google.com/search?q=it%27s+nice

The problem is known, I'm just filing an issue to hopefully avoid new issues on the matter.
## Why it fails:

`yourls_edit_link()` escapes $url and compares it with the old URL associated with the submitted keyword. But escape of `it's cool` becomes `it\'s cool` and thus the function thinks we try to submit a different URL keeping the same keyword, and then returns an error because that keyword is already in use.
## Resolution:

Short term resolution would be obviously to replace `$url = yourls_escape( $url )` with `$sql_url = yourls_escape( $url )` and use `$sql_url` in all SQL statements. But: there are a gazillion queries with the same problem.

A much better longer term resolution is to eventually have the proper prepare functions we've been needed for years -- see [Roadmap](https://github.com/YOURLS/YOURLS/wiki/Road-Map). Deferred to 1.8

**Comment by Kiroteryn** [comment]
I have this issue as well. What's odd is that.. It worked fine for a couple months and only today did this start happening. I have about 3 pages of links.

**Comment by dylanh724** [comment]
Closed == fixed? 🤨

**Comment by ozh** [comment]
Closed == (fixed && was a duplicate)

Of course: if you're experiencing something related that doesn't seem right, please file a new issue with all details
