### ISSUE TITLE
Custom date/time format string for i18n?

### ISSUE THREAD

**Issue by chtaube** [YOURLS/YOURLS#1802]
Without [hacking core](https://github.com/YOURLS/YOURLS/wiki/Dont-Hack-Core), there seem to be no proper way to change the output of date/time string when using localization.

Example: `yourls_date_i18n( "F j, Y @ g:i a", …`  ([source](https://github.com/YOURLS/YOURLS/blob/4ce79cad7f5bd2382ed0d807fd12cacf72b67e8f/yourls-infos.php#L341)) returns _Oktober 31, 2014 @ 1:37 pm_ while in Germany we would write this as _31. Oktober 2014, 13:37 Uhr_.

**Comment by ozh** [comment]
This should be covered with https://github.com/YOURLS/timezones
