### ISSUE TITLE
yourls_get_favicon_url() is dead

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#1803]
http://www.google.com/s2/u/0/favicons?domain=example.com has gone missing. Find replacement ASAP.

**Comment by plttn** [comment]
Unfortunately, it looks like to me that if you're logged into a google account, the call to s2/ still points to s2/u/0.

**Comment by ozh** [comment]
Not for me

**Comment by ElliotFriend** [comment]
Logged into a Google Apps account, s2/u/0/ redirects to: plus.google.com/_/favicon?domain=example.com. s2 proceeds as expected. In both cases, I get the same favicon.

**Comment by LeoColomb** [comment]
I second @ElliotFriend.

**Comment by plttn** [comment]
Weird, s2 is erroring for me. I'll try rolling my install up to HEAD and
seeing if that resolves it.

**Comment by plttn** [comment]
For what it's worth, updating to HEAD seemed to have fixed it.
