### ISSUE TITLE
"This domain is blacklisted" - Error Message

### ISSUE THREAD

**Issue by guimadrum** [YOURLS/YOURLS#1811]
I'm trying to shorten a simple url like i always did, but now i get this message in a pink tab at the top. "This domain is blacklisted" 

And nothing happens. That is it.  

I have also noticed that a shortened link that was a huge hit for me, (like 40k hits)  had the the clicks reset to zero.

The previously shortened links works. 
### Technical details
- YOURLS version: 1.7
- PHP version: native 5.4
- all my websites are hosted at Godaddy

Anyone faced this same trouble? 
What should i do? 
(i'm a simple user, be patient)

**Comment by sarfraazcodes** [comment]
antispam plugin cause this

**Comment by drbeco** [comment]
Hi ozh. Thanks for the solution. My case, `dropbox` was blocked.

Please if you could, add a small reference in the error message. Something like : "This domain is blocked by antispam plugin".

Thanks for your hard work.
