### ISSUE TITLE
Where is the function to prefix every url?

### ISSUE THREAD

**Issue by AsaadQ** [YOURLS/YOURLS#1830]
i am looking for function which will allow me to prefix every shortened url with another url:

http://www.mysite.com&go=http://sh.rt/sdfsfdg

Where can i find the main funtion which handles all the url requests so i can work with this?

thanks!

**Comment by AsaadQ** [comment]
Basically i want to do something like this, the current code, is it ok or does it need tuning?

https://github.com/mattytemple/YOURLS-Plugin--Skimlinks

**Comment by ozh** [comment]
I don't understand what you need. Look at existing plugins, find what is most similar to your needs and modify its code to make it work the way you want.
