### ISSUE TITLE
Title % Breaks Editing

### ISSUE THREAD

**Issue by AskKim** [YOURLS/YOURLS#1831]
When adding a URL that has a page title containing a % (percentage symbol), the link is correctly made and works, but is not editable. 

You can click on the editing button, and the buttons grey out at the time that the editing drop-down (drop-in?) would appear, but the editing box never appears. 

After some testing, I submitted this to my webhost, as I had used their autoinstaller, and they did further testing and have decided it's likely a bug. 

Their reply is pasted below the ---- line. 

Kim 
---------------------------------------------------------------------------
Dear Kimberly,

Thank you for provided details and your patience.

According to our technical team, this issue appears to be a script flaw - it hangs in case if the title of the URL being shortened contains "%" symbol , like in '100% Satisfaction Guaranteed - Buy Now!' , as submitted by you.

We have created a new shortened link, titled 'Full Satisfaction Guaranteed - Buy Now!' - and it does work as expected. 

We would suggest contacting script developer on this matter.

Should you have any questions please do not hesitate to contact us again.

Regards,
Alexey Ko.
Namecheap Hosting Customer Support

**Comment by ozh** [comment]
Fixed in current master. You can safely update (or of course wait for 1.7.1, no ETA)

**Comment by AskKim** [comment]
Thanks :)
