### ISSUE TITLE
Destination URL doesn't get updated when editing links

### ISSUE THREAD

**Issue by tstrickland415** [YOURLS/YOURLS#1832]
### Reproducible Bug Summary 

1. Shorten any link
2. Visit the shortened link (it should work as intended)
3. Now go back to the Admin section and Edit the Long URL, and Save. You will get the green Successfully Saved message, and the save is reflected in the Admin Dashboard and MySQL database.
4. Now visit the same shortened link. It will still direct to the Old URL and not the Updated URL, even though in the Admin dashboard the Updated URL is saved in there

Upon further investigation, I noticed the Edit feature only works if the link has never been clicked or visited yet.

### Reproducible Bug Summary

1. Shorten any link
2. Do NOT click on it
3. Edit the link's destination URL, and Save
4. Now, click on the shortened URL. It will point to the new URL
5. Once the shortened URL has been clicked or visited, the destination URL can no longer be edited

I'm no expert, but I suspect there may be some sort of caching problems going on because when I clear my cache then I can edit the link successfully (but only before I click it). If I clicked the link, then I have to clear my cache again before I can successfully edit the link. If I clear my cache, then visit the link, I can no longer edit the link.

### Technical details

* YOURLS version: 1.7
* PHP version: 5.4.31
* MySQL version: 5.5.36
* Server OS: Linux cPanel
* Browser Version: Chrome & Firefox, latest

* Any other useful information depending on context (server version, mysql version, browser version, OS version...)

**Comment by dgw** [comment]
This is normal behavior for 301 ("Permanent") redirects. Response code 301 indicates a redirect that is not expected to change, and may be cached for an appropriate length of time by user agents (browsers, etc.).

If you need to be able to update your short links quickly for users who may have already visited them, use a plugin like 302-Instead ([Plugin List](https://github.com/YOURLS/YOURLS/wiki/Plugin-List#0-9)) to send 302 ("Temporary") redirects instead.
