### ISSUE TITLE
White Boxes Obsure Links on Firefox

### ISSUE THREAD

**Issue by Kolano** [YOURLS/YOURLS#1833]
The Flash embed used by this is not invisible on Windows Firefox 36.0 (and likely other revisions). This causes all zClip related links and buttons to be obscured by white boxes.

Here is a screenshot of the issue on my machine...
![links obscured](https://cloud.githubusercontent.com/assets/6509657/5864115/28882996-a24d-11e4-9905-2ce138d23abb.png)

**Comment by LeoColomb** [comment]
Hey @Kolano !
What is the ***specific*** relation with YOURLS?
It's seemed to be a zClip bug (i.e. in general), isn't it?

**Comment by Kolano** [comment]
Oops, sorry, got linked here through a series of links from the an old Google Code page for zClip, didn't realize this wasn't the zClip github.

**Comment by LeoColomb** [comment]
Right! Thanks :smile_cat:
