### ISSUE TITLE
Is new recaptcha (i am not a robot tick) compatible with ∞²?

### ISSUE THREAD

**Issue by xenu-cf** [YOURLS/YOURLS#1834]
Is [new recaptcha](http://recaptcha.com) (i am not a robot verification via tick) compatible with ∞² (Infinity Squared)? 

if not, how do i add support for it?

**Comment by dgw** [comment]
This is the issue tracker for YOURLS, a self-hosted URL shortener. Are you sure you're asking in the place you intended to come?

**Comment by ColtonDRG** [comment]
Sorta. You have to rewrite the bit of the code that handles Captcha, which is not immediately easy. You can see an example of new recaptcha working with a moddified version of infinity squared at http://itti.cf/ (If it's not down. Having some trouble with my webhost at the moment.)

I can post an example of how to get this working, but as I said, I'm having some problems with my webhost at the moment, so I can't do it right now.

One last thing. This probably wasn't the right place to ask. It's not really a bug, it's a question and it has more to do with Infinity Squared than YOURLS

**Comment by xenu-cf** [comment]
ok how do i do that

**Comment by LeoColomb** [comment]
@xenu-cf You seem to want help for infinity-squared.
Please see the right repo https://github.com/tomslominski/infinity-squared and ask @tomslominski.
Thanks! :smile:
