### ISSUE TITLE
how do i add a shortlink counter to front page

### ISSUE THREAD

**Issue by xenu-cf** [YOURLS/YOURLS#1835]
how do i add a shortlink counter to front page ([No. of short URLs created] short links have been created and [No. of total clicks on short URLs] clicks on [site])

e.g.

200 short links have been created and 3,000 clicks on xenu's url shortener.

**Comment by vaughany** [comment]
It already does, at least on 1.7.1.  When I log in to our installation, it says "Overall, tracking 286 links, 3,416 clicks, and counting!" on the front page.  You could change the wording quite simply by editing admin/index.php line 277.

**Comment by ozh** [comment]
I think the question was more about displaying on a public interface.
```php
list( $total_urls, $total_clicks ) = array_values( yourls_get_db_stats() );
echo $total_urls;
```

NB: as explained in the sample interface and the readme files, customizing a public interface is left as a user's exercise, depending on their needs.

**Comment by LeoColomb** [comment]
@koulaxizis You only need to add @ozh [suggestion](https://github.com/YOURLS/YOURLS/issues/1835#issuecomment-71465308) just above.
