### ISSUE TITLE
Is links been checked with Google safe browsing api?

### ISSUE THREAD

**Issue by Mn9or** [YOURLS/YOURLS#1836]
Hello,

At the beginig I would like to thank you all for this great simple script. I have a question, is the links has been checked with Google safe browsing api?. It is a very important and safe thing to add to the script if not.

Best regards,
Mansour

**Comment by Decicus** [comment]
[There's a plugin for that](https://github.com/YOURLS/google-safe-browsing) as well as you need to use an API key, which is still limited to a 10,000 queries per day.
