### ISSUE TITLE
IBM DB2 Compatability

### ISSUE THREAD

**Issue by JordonGreene** [YOURLS/YOURLS#1838]
Hello,

My company currently uses yourls to shorten URLs, however our new system is based on the IBM AS400 using DB2 for our database. I have not been able to find anything regarding using yourls with DB2 and my attempts to integrate it have been unsuccessful with my limited knowledge.

Is DB2 supported at all with yourls or planned to be supported?

**Comment by ozh** [comment]
DB2 support is not planned.
It could be implemented as a plugin since you can declare a [custom DB layer](https://github.com/YOURLS/YOURLS/blob/master/includes/load-yourls.php#L147:L153) but that's it.

**Comment by JordonGreene** [comment]
Thank you for the quick reply. Is there anywhere that a quick list of required functions for the database operations exists?

**Comment by ozh** [comment]
You'll want to look into `includes/ezSQL/ez_sql_core.php` and `ez_sql_mysql.php`

**Comment by JordonGreene** [comment]
Thanks!
