### ISSUE TITLE
Truncate yourls database

### ISSUE THREAD

**Issue by lingstar** [YOURLS/YOURLS#1840]
I just upgraded my yourls version and have 830K+ records in my logfile.  Plus, I have about 4K URLs that haven't been clicked on for at least 90 days.

How can I clean out my database?

Thanks!

**Comment by ozh** [comment]
First of all, having a million records in mysql isn't a problem, the db engine can totally handle that. Unless you have a specific reason to do so, just forget about it.

If you want to truncate logs, the easiest way would be to use phpmyadmin and simply delete those you don't want, eg filter by date or ip or whatever you like (table:yourls_log)

To delete short urls, the same applies, and there's also a mass delete plugin available.
