### ISSUE TITLE
Adding url to 1.7.1 and deleting record not working

### ISSUE THREAD

**Issue by goldsteinmedia** [YOURLS/YOURLS#1842]
Hi,

I just installed YOURLS v. 1.7.1 to GetMSL.co/admin. I can't add a URL or delete one. What am I doing wrong?

**Comment by ColtonDRG** [comment]
Does your SQL account have write access?

**Comment by goldsteinmedia** [comment]
it should. how do i check that?

**Comment by goldsteinmedia** [comment]
SQL has write access. now what

**Comment by LeoColomb** [comment]
Please follow [Contributing Guidelines](https://github.com/YOURLS/YOURLS/blob/master/CONTRIBUTING.md) to allow us help you.
Notably, please give your system info.
