### ISSUE TITLE
Can't install correctly or login

### ISSUE THREAD

**Issue by mageguild** [YOURLS/YOURLS#1844]
I am trying to setup this application but when I follow the steps but during the install process, I get the following errors.  

Error creating table 'yourls_url'.
Error creating table 'yourls_options'.
Error creating table 'yourls_log'.
Error creating YOURLS tables.

Apart from the YOURLS table, the other tables have actually been created.  
When I return to /admin/ it prompts me to login but I don't know what the logs are.  

Can someone provide some assistance with this on how to get it working?

**Comment by LeoColomb** [comment]
> I am trying to setup this application

I don't think you have followed a kind of setup guide!...

Please refer to the configuration setup: https://yourls.org/#Install then https://yourls.org/#Config
