### ISSUE TITLE
Some custom URLs get short URL some not

### ISSUE THREAD

**Issue by semaf** [YOURLS/YOURLS#1845]
Some of my Pages gives a correct shorten URL back but some of the will not. Even they are shorten at Yourls. I can see it at the Admin Panel.

This is the debug of a Page with shorten URL

    {"status":"fail","code":"error:url","url":{"keyword":"09266","url":"http:\/\/domain.com\/LilyPad-Arduino-328-Main-Board","title":"LilyPad Arduino 328 Main Board","date":"2015-02-12 00:35:39","ip":"xxx.xxx.xxx","clicks":"0"},"message":"http:\/\/domain.com\/LilyPad-Arduino-328-Main-Board already exists in database","title":"LilyPad Arduino 328 Main Board","shorturl":"http:\/\/doma.in\/09266","statusCode":200,"qrcimg":"http:\/\/doma.in\/user\/plugins\/inline-qrcode\/images\/qrccf6f0d99893974288d48676d9cdbd51a.png","qrimage":"

This is the debug of another Page without the URL on Page but available at Admin

    {"status":"fail","code":"error:keyword","message":"Short URL 00027 already exists in database or is reserved","statusCode":200,"qrcimg":"http:\/\/doma.in\/user\/plugins\/inline-qrcode\/images\/qrcd41d8cd98f00b204e9800998ecf8427e.png","qrimage":"

This is my PHP Code

    function shortyourls(){
    global $smarty;

    // Inputs
    $shorturl   =   'http://' . $_SERVER['HTTP_HOST']  . $_SERVER['REQUEST_URI'];
    $signature  =   "123456789";
    $siteurl    =   "http://doma.in";
    $format     =   "json";
    $Artikel    =   $smarty->get_template_vars('Artikel');
    $title      =   http_build_query(array('title' => $Artikel->cName));
    $keyword    =   preg_replace("/[^0-9,.]/", "", ($Artikel->cArtNr));

    // Phases url
    $short = file_get_contents($siteurl.'/yourls-api.php?signature='.$signature.'&action=shorturl&url='.$shorturl.'&format='.$format.'&keyword='.$keyword.'&'.$title);

    $url=json_decode($short,TRUE);
    $output = $url['shorturl'];
    echo $output;
}

Any idea what is wrong?

**Comment by LeoColomb** [comment]
> `"message":"http:\/\/domain.com\/LilyPad-Arduino-328-Main-Board already exists in database"`
> `"message":"Short URL 00027 already exists in database or is reserved"`

These messages are quite clear, isn't it?
Deal with `YOURLS_UNIQUE_URLS` config variable as explained in https://yourls.org/#Config, should help you.
