### ISSUE TITLE
Unique URLS not working in admin area or via API

### ISSUE THREAD

**Issue by bertrandsoulier** [YOURLS/YOURLS#1848]
I set up a private link shortener with Yourls 1.7

I only publish links via admin area and api (Tweetot and dlvr.it)
In config.php I have define( 'YOURLS_UNIQUE_URLS', true );

Via admin area Yourls still generate multiple short url for the same long url. A set up a public test page. When i'm logged as admin Yourls generate a new short url each time I submit a the same long url. If I logout, I get the message "already in database" when I submit the url.

Is it a bug or normal ? Is this possible to really have unique urls working in each case ?

Thanks

**Comment by ozh** [comment]
I can't reproduce this.

**Comment by MrBodira** [comment]
I have exactly the same issue. 99% of the url's made by an API call with the signature to authenticate, action: shorturl and format: json. My feeling is that something goes wrong with the interpretation of the true / false value of YOURLS_UNIQUE_URLS somewhere further in the application. I also research it myself but up to now I have not been able to put my finger on it.

**Comment by LeoColomb** [comment]
@MrBodira Thanks your feedback. 
Could you precise your versions (YOURLS, PHP, …)?

**Comment by MrBodira** [comment]
Hi Leo, requested information:
Yourls: 1.7.0
PHP: 5.4
MySql: 5.5.41
