### ISSUE TITLE
shortened url not working

### ISSUE THREAD

**Issue by trtlator** [YOURLS/YOURLS#1849]
I have installed yourls in a sub folder and access it fine but when I tell it to create a shortened url it pulls  in the closest permalink available. So for example: http://domain.com/testtestpage and shorten to http://domain.com/test it will show another page called testers or something similar to the example. The site is on wordpress I have also installed the yourls plugin and verified that the api is working. Is this because the install directory is domain.com/yourls and the shorten url is domain.com/yourls/test and the site isnt bringing in this info. How can I correct this so that it works better?

**Comment by ozh** [comment]
By reading the readme, probably.
