### ISSUE TITLE
404 on Shortened link Click

### ISSUE THREAD

**Issue by EbearPlays** [YOURLS/YOURLS#1851]
So I installed correctly and everything. Great.

However, I went and read everything about mod_enable and all the apache and .htaccess settings, all of which I've confirmed to be correct, and it still sends me a 404.

Until I get the plugin with more complex links, here's the one I'm trying to use: http://ebear.us/r/1

Also, I'm using the latest master.zip.

If there's any reason this is happening or any way you can help me fix it, please let me know. Thanks!

**Comment by ozh** [comment]
Are you positive the .htaccess is correct, eg like https://github.com/YOURLS/YOURLS/wiki/.htaccess (see subdirectory)

**Comment by EbearPlays** [comment]
Nearly positive, I checked multiple times. I'll check one last, but chances are there's no errors. And I'm sure of that.

**Comment by ozh** [comment]
Double check the htaccess. Check server logs. Double check mod_rewrite is enabled. Honestly, dunno. There *is* something misconfigured on your end, but it could be numerous things.

**Comment by EbearPlays** [comment]
My .htaccess file is [here](http://pastie.org/9985736).

The root directory or whatever it asks for in config is http://ebear.us/r

I double, even triple checked the configurations and if mod_rewrite was enabled, and it is.

Is there anything else besides those on my end that could be causing the issues?

**Comment by ozh** [comment]
That's not a .htaccess file, that's a config file (with mysql password and everything: bad idea to share that publicly)

**Comment by EbearPlays** [comment]
@ozh welp time to change the password :P 

Thank god it was a random one.

http://pastie.org/9985772

Well, there's the .htaccess.

I'm not even going to get into the facepalms I just did.

**Comment by ozh** [comment]
The most probable reason for this would that mod_rewrite is not enabled (which you can check with a `phpinfo()`). Other than this, I have no idea. Server error logs might tell more.

**Comment by EbearPlays** [comment]
I checked via phpinfo(), it's listed as enabled. I checked every possible Error Log (Apache, MySQL, and normal System), I restarted the server. Do you think a fresh YOURLS install would help? Since I've tried everything as far as configuration goes, and it hasn't helped anything.

**Comment by ozh** [comment]
Reinstalling YOURLS won't help: this is a server config error, YOURLS has nothing to do with it.
AFAIK the docroo is not the problem, if there was a problem with this the server would simply not serve pages at all.

Honestly, don't know.

**Comment by EbearPlays** [comment]
Yeah @ozh since this is a completely fresh server, it makes no sense.
