### ISSUE TITLE
Install in subdirectory?

### ISSUE THREAD

**Issue by sirtet** [YOURLS/YOURLS#1852]
I used git to get the files, what created a subdir YOURLS/
`git clone https://github.com/YOURLS/YOURLS.git`
I thought, ok, maybe a good idea to have a clean root...
But then i found no way to configure so that the shortening still works without the subdir.

Do i have to install in root?

**Comment by LeoColomb** [comment]
> Do i have to install in root?

No. You may see the documentation, and [config wiki](https://github.com/YOURLS/YOURLS/wiki/.htaccess#case-yourls-installed-in-subdirectory).

**Comment by sirtet** [comment]
Ah well, i menat can i install in a subdir and still use shorts like if it was installed in the root.
On 2nd thought, i guess it MUST be impossible, as the requests could never reach YOURLS.
UNLESS, the .htaccess in root would redirect all requests to the subdir. But then the whole idea would not make sense anymore, i guess...

**Comment by LeoColomb** [comment]
Yes you can, but you have to change your "root" `.htaccess`.
It's such a mix of the two documented examples of configuration:
* Your "base" is the root
* Your rewrite push to the directory

```apache
# BEGIN YOURLS
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^.*$ /YOURLS/yourls-loader.php [L]
</IfModule>
# END YOURLS
```

**Comment by LeoColomb** [comment]
Be careful, your admin is still located at `example.com/YOURLS/admin/`.

**Comment by sirtet** [comment]
Thanks.
In the meantime, is saw there's also a plugin which seems to help with this:
https://github.com/ggwarpig/Yourls-Swap-Short-Url
