### ISSUE TITLE
30 Minute Delay

### ISSUE THREAD

**Issue by montemorgan** [YOURLS/YOURLS#1853]
I noticed that when a use my Yourls with an RSS feed the new shortened links within the RSS feed take about 30-35 minutes before they link correctly.  Any reason for the delay?  Is there a way to fix this problem?

**Comment by ozh** [comment]
I don't undestand the question.

**Comment by montemorgan** [comment]
I built a Yourl shortener to shorten the links I was using to tweet on
Twitter.  When the tweet shows up on Twitter with the shortened link I get
an error message saying that the link is harmful.  After 30 minutes when
you click on the link you no longer get the message.  Also, not every link
has this problem.



On Thu, Feb 26, 2015 at 3:22 PM, ྅༻ Ǭɀħ ༄༆ཉ <notifications@github.com>
wrote:

> I don't undestand the question.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/YOURLS/YOURLS/issues/1853#issuecomment-76262203>.
>



-- 
Monte Morgan
montemorgan@gmail.com
917-687-6683

<http://www.cash2sit.com/rdr.php?id=7733&sid=1>

**Comment by ozh** [comment]
I don't think this is related at all with YOURLS. It's either related to your short domain, or the link you're shortening. YOURLS itself has nothing to do with this.
