### ISSUE TITLE
Plugin broken: Google Analytics Link Tagging

### ISSUE THREAD

**Issue by sirtet** [YOURLS/YOURLS#1856]
Sorry for the crossposting, i know this is que is not meant for plugins, but i still dare to post here, delete if i'm unappropriate.

The plugin __Google Analytics Link Tagging__ seems broken since YOURLS 1.7 (or earlyer?)
https://github.com/katzwebservices/google-analytics-for-yourls/issues/6
AND a bit abandoned.
So i thought it's maybe ok to try attract some attention from 'outside'.

This plugin seems quite handy for people who use YOURLS for cross-media tracking. It allows to easily add tags to your url like
> http://www.my-long-url.com/?utm_source=MySource&utm_medium=Banner&utm_campaign=MyCampaign

So, maybe someone familiar with plugins could quite quickly spot the problem?
My own coding skills would take me days to get into it.

**Comment by ozh** [comment]
Did you check the other plugins? There are a few others about Google Analytics. I pinged the plugin author to be notified if we should remove this plugin from the "official" list

**Comment by sirtet** [comment]
Thanks. No, i did not _try_ the others, but from their description they clearly are no replacement. 
They allow to add the analytics js code to track yourls-usage.
Whereas _Google Analytics Link Tagging_ adds some input fields to facilitate adding url-parameters like _utm_source=somevalue_ to the long URL's
