### ISSUE TITLE
Not able to Run

### ISSUE THREAD

**Issue by sagarhani** [YOURLS/YOURLS#1857]
![screenshot from 2015-03-04 20 54 59](https://cloud.githubusercontent.com/assets/6933389/6486568/da1e4044-c2b1-11e4-82e9-fe7e3d4b75bf.png)

Why I am getting this error?
I have followed the steps mentioned in http://yourls.org/#Install

**Comment by ColtonDRG** [comment]
I'm guessing your MySQL account has the wrong permissions. I usually just
give the accounts full permissions to avoid any issues.

**Comment by chtaube** [comment]
Your database server denies access. Check your database username/password and double check the permissions set on the database server.

Your database server seems to be on another system than your webserver, so you apparently cannot simply grant permission to "sagar@localhost" here. Double check this, too.

**Comment by LeoColomb** [comment]
As @ColtonDRG and @chtaube said (thanks guys!), you should check your database identifiers in your YOURLS configuration. :mag:
See https://yourls.org/#Config
