### ISSUE TITLE
Prefix-n-Shorten fails in Chrome because address bar hides http://

### ISSUE THREAD

**Issue by ryanmr** [YOURLS/YOURLS#1863]
(First time issue writer, advanced apologies for doing it wrong.)

In Chrome, the address bar hides the `http://` part of a url, unless it is `https://` in which case Chrome leaves it alone. When using the prefix-n-shorten, since Chrome hides the `http://` on most pages, the shortening will fail.

*Expected behavior*: the shortened url shown on the admin panel after using the prefix-n-shorten shortcut of YOURLS.
*Actual behavior*: the landing page of my YOURLS installation.

*Steps to reproduce*:
1. Open Chrome
2. Go to non-https page
3. Prefix the URL on said page in the address with the yourls installation path
4. Fails to produce the shortened url

*Example*:
* myyourls.com/theverge.com/blah/blah | fails
* myyourls.com/http://theverge.com/blah/blah | works

Other information:
* PHP 5.5.9
* MYSQL 14.14
* Ubuntu 14.04
* YOURLS 1.7

I love using the prefix-n-shorten feature, and while this is annoying, I end up just typing the `http://` by hand. Even if there is no way to fix this, I figured it might helpful to document somewhere.

**Comment by ozh** [comment]
This is a browser issue, nothing YOURLS can fix (how to know if http://sho.rt/omg.com is a short URL or a shortening attempt?)

In Firefox: `about:config` then set `browser.urlbar.trimURLs` to `false`

In Chrome, there's probably something similar. Not a user, I don't know, but Google will probably be your friend :)
