### ISSUE TITLE
Add a comments field

### ISSUE THREAD

**Issue by sirtet** [YOURLS/YOURLS#1866]
Add a comment field to each created url.

What for?
I use YOURLS for cross-media campaigns, so the short url's are put on print media like flyers or brochures.
To be able to track these paper sources as "referral" for a visitor of the (long) url, you need to keep track of which short url is used where.
This is where an additional field for notes would help to keep the overview in YOURLS

I think of something like this for the list of URL's:

![yourls-notes](https://cloud.githubusercontent.com/assets/3509308/6626243/812ea6d2-c8f5-11e4-8cb6-22df080c1a14.jpg)

**Comment by ozh** [comment]
That's left to plugin territory (there are several issues about this)

**Comment by sirtet** [comment]
I'm still interested in doing this.
Maybe someone with good knowledge of YOURLS's code has hints how to approach that? Where to start looking?
For adding another field to the DB, _track-custom-keywords_
https://github.com/timcrockford/track-custom-keywords
might help me. But about adding a col. to the list of short-url's, as outlined in my screenshot, i'm not sure where i'd start...

**Comment by slimmingcapsule** [comment]
Semoga sukses :
http://obatamandel.utamakansehat.com/
http://obatflekparuparu.utamakansehat.com/
http://obatgondok.utamakansehat.com/
http://obatgulabasah.utamakansehat.com/

**Comment by psteinweber** [comment]
+1 - I'd be really interested in that as well and would love to have something like the OP suggested. Couldn't find any other place to leave this feedback/feature request - hope it's somewhat constructive here. Cheers.
