### ISSUE TITLE
Add option to hide IP-column in URL-list if YOURLS is in private mode.

### ISSUE THREAD

**Issue by sirtet** [YOURLS/YOURLS#1867]
I think the column with the IP of the shortlink-creator is meant to have an idea who created a link.
But if url's can only be added by logged in users, this is not a that important info, at least not in the overview.
So it would be nice to have an option to hide that col. vor a better overview in the spirit of _less is more_...

PS:
Same could be said about the clicks-col for people not interested in stats within yourls (what would not apply to me).

**Comment by ozh** [comment]
This is left, once again, for plugin territory. Different users will have differents needs (multiple users, public instances, etc...)
