### ISSUE TITLE
How to add custom 404

### ISSUE THREAD

**Issue by sirtet** [YOURLS/YOURLS#1869]
I think there's no core way to have a 404 page for non-existing shortlinks.

This is how i did it, maybe this helps someone else, maybe i should do this differently:

I installed the  __fallback-url__ plugin
http://diegopeinador.blogspot.fr/2013/04/fallback-url-simple-plugin-for-yourls.html
which allows to redirect to another page if there's no match with a shortlink.
Then i configured it to redirect to a page called 404.php where i output something like

> sorry, link __X__ does not exist

to get __X__, the request-uri, into my 404 page, i modified the plugin to send along the REQUEST_URI as get parameter.

```
 14 yourls_add_action( 'redirect_keyword_not_found', 'dp_fallback_url' );
 15 function dp_fallback_url() {
 16         // Get value from database
 17         $fallback_url = yourls_get_option( 'fallback_url' );
 18         $fallback_url.= '?url=' . $_SERVER['REQUEST_URI']; // send the request-uri to the 404-page
 19         yourls_redirect( $fallback_url, 302 ); //Use a temporal redirect in case there is a valid keyword in the future
 20 }
 ```

One issue i see, i should actually not do a redirect to the 404 page, but directly deliver that, with 404 status code...

**Comment by ozh** [comment]
It's easy as pie:

```php
<?php
/*
Plugin Name: 404 if no short URL
Plugin URI: 
Description: 
Version: 1.0
Author: Ozh
Author URI: http://ozh.org/
*/

yourls_add_action( 'redirect_keyword_not_found', 'my404' );

function my404( $data ) {
    $shorturl = $data[0];
    yourls_status_header( 404 );
    echo "Short URL <strong>$shorturl</strong> not found!";
    die();
}
```

**Comment by sirtet** [comment]
Great, thanks! I would put this into a proper plugin, if wanted.

One problem though:
**redirect_keyword_not_found** fires only if a **keyword** was not found, but there are other cases of 404, that still lead to the normal forwarding to the standard index file, eg.  requests like **some/dir** or **some&specialchar**
Is there a way to catch those too?

**Comment by ColtonDRG** [comment]
If it doesn't catch those it's easy to fix. Just have the plugin report a
404 to the client using the header, then include("404.php"). That will
report 404 on nonexistent short links, then add ErrorDocument 404 404.php
to the .htaccess and instruct users to put their 404 page in 404.php.

**Comment by sirtet** [comment]
Well, there's no 404 in the first place, that's the problem.
What typically would be 404's YOURLS redirects with 302 to the index page.

The code above gives us 404's for simple strings life foo
if i request foo/bar, it's not caught.

Maybe i misunerstand something?

PS: i tuned ozh's function a bit, to have an easily editable 404-page:
```
function my404( $data ) {
    $placeholder = '<request-url>';
    $shorturl = $_SERVER['HTTP_HOST'] . '/' . $data[0];
    $errorpage = file_get_contents('/home/toronetc/public_html/domain-ksv-li/user/plugins/custom-404/404.html');
    $errorpage = str_replace( $placeholder, $shorturl, $errorpage);
    yourls_status_header( 404 );
    echo $errorpage;
    die();
}
```

**Comment by ColtonDRG** [comment]
Yes, that is why you should add `ErrorDocument 404 404.php` to your
.htaccess file.

**Comment by ozh** [comment]
Still trivial to handle non existent directories or anything, with action `'loader_failed'`:

```php
yourls_add_action( 'redirect_keyword_not_found', 'my404' );
yourls_add_action( 'loader_failed', 'my404' );

function my404( $data ) {
    $shorturl = $data[0];
    yourls_status_header( 404 );
    echo "Short URL $shorturl not found!";
    die();
}
```

**Comment by sirtet** [comment]
@ColtonDRG, i tried your approach without any success, and i am not surprised, because there's never a 404 raised, but a 302 (YOURLS does that).

@ozh, thanks, works perfectly. I'll see if i can put that into a plugin sometime.

**Comment by ColtonDRG** [comment]
Alright. I didn't realize that YOURLS handled those like that, but @ozh's
method does work. I would still recommend throwing a 404 header with your
plugin, then php include 404.php, because then we can just  toss our 404
page in that file and turn on the plugin, plus we can very easily edit the
file at any time. It will also be totally inline with Google Webmaster
Tools' best practices for 404 handling. Tell me when you release your
plugin, because I will probably put it to use, or fork it for my uses.

@ColtonDRG <https://github.com/ColtonDRG>, i tried your approach without
any success, and i am not surprised, because there's never a 404 raised,
but a 302 (YOURLS does that).

@ozh <https://github.com/ozh>, thanks, works perfectly. I'll see if i can
put that into a plugin sometime.

—
Reply to this email directly or view it on GitHub
<https://github.com/YOURLS/YOURLS/issues/1869#issuecomment-81177732>.

**Comment by sirtet** [comment]
My plugin looks like below.
It does all what you want i think. Throws a 404, and i have an easily editable 404 file, but without php, to separate the output from php code.

The string _{{request-url}}_ can be placed in that 404.html, where i want the request-uri.


```<?php
/*
Plugin Name: 404 if no short URL
Plugin URI:
Description:
Version: 1.0
Author: Ozh
Author URI: http://ozh.org/
*/

// redirect if the shortlink ( shortlink = text only, no special chars) does not exist
yourls_add_action( 'redirect_keyword_not_found', 'my404' );
// redirect if supbages or pages with special-chars were requested
yourls_add_action( 'loader_failed', 'my404' );

function my404( $data ) {
    $placeholder = '{{request-url}}';
    $shorturl = $_SERVER['HTTP_HOST'] . '/' . $data[0];
    $errorpage = file_get_contents('user/plugins/custom-404/404.html');
    $errorpage = str_replace( $placeholder, $shorturl, $errorpage);
    yourls_status_header( 404 );
    echo $errorpage;
    die();
}
```

**Comment by ColtonDRG** [comment]
I don't understand why you don't want to just use PHP to include the file. Why not have the ability to include some PHP code in your 404 page? You should also change the plugin and author information to yours. ;)

**Comment by sirtet** [comment]
The idea is, that if no php is run, you can not do something possibly dangerous.
And people who know a little html, but no php, can savely edit the file.
Or even use whatever html editor.

What would you possibly want to do in php?
I just wanted to be able to print the requested url.
Check out my shortener http://ksv.li/
And try some random text to get a 404...

Will see when i get time to create a full plugin. i'd put it on github.

**Comment by jmilldr** [comment]
Hi, 

I wonder, how can I redirect visitor to link using plugin code below (Instead of page in same directory)?

<?php
/*
Plugin Name: 404 if no short URL
Plugin URI:
Description:
Version: 1.0
Author: Ozh
Author URI: http://ozh.org/
*/

// redirect if the shortlink ( shortlink = text only, no special chars) does not exist
yourls_add_action( 'redirect_keyword_not_found', 'my404' );
// redirect if supbages or pages with special-chars were requested
yourls_add_action( 'loader_failed', 'my404' );

function my404( $data ) {
    $placeholder = '{{request-url}}';
    $shorturl = $_SERVER['HTTP_HOST'] . '/' . $data[0];
    $errorpage = file_get_contents('user/plugins/custom-404/404.html');
    $errorpage = str_replace( $placeholder, $shorturl, $errorpage);
    yourls_status_header( 404 );
    echo $errorpage;
    die();
}

**Comment by LeoColomb** [comment]
@jmilldr I'm not sure to understand well your question, but you may refer to the usage of `yourls_redirect()` function.

```php
function my404( $data ) {
    yourls_redirect( [YOUR LINK], 404 );
    die();
}
```
