### ISSUE TITLE
admin page REDIRECTS TO BS

### ISSUE THREAD

**Issue by kamijoutouma** [YOURLS/YOURLS#1870]
http://www.salesforce.com/platform/overview/?d=70130000000liBh ..... seriously JUST NO

**Comment by ozh** [comment]
How embarrassing, isn't it.

**Comment by kamijoutouma** [comment]
Http://site.com should be changed to 
Http://you_are_an_idiot_for_leaving_this_in_config.com just saying @ozh I didn't see anything about this in the wiki and I usually don't look at closed issues

**Comment by kamijoutouma** [comment]
If I hadn't known any better I would have thought someone hacked my server configuration and rewrote my nginx .....

Oh yeah for laughs enjoy this page 
http://toaru-music.tv/dittoit/ @ozh

**Comment by kamijoutouma** [comment]
Also the search usually only yields open issues unless they changed it. 
And I normally only assume that closed issues are either fixed issues or dumb issues like someone trying to compromise your project and take claim for your work.
