### ISSUE TITLE
Sequential or random?

### ISSUE THREAD

**Issue by freimanas** [YOURLS/YOURLS#1871]
I have read that there is a feature:
Sequential or custom URL keyword

But how do I get the random one to work? when I use admin or API I get /1 /2 /3
how can I get something random like: /1kY48s

Just cant find anywhere in the config nor API documentation how to enable that...

any help?

**Comment by chtaube** [comment]
The random keyword feature is implemented as a plugin:

https://github.com/YOURLS/random-keywords

Just install and activate the plugin and you are done.

**Comment by LeoColomb** [comment]
Perfect answer, @chtaube! Thanks :rocket:

**Comment by freimanas** [comment]
thanks guys works like a charm!
