### ISSUE TITLE
Possible bug? Api and admin page refuses any Capital letters for keyword when shortening

### ISSUE THREAD

**Issue by kamijoutouma** [YOURLS/YOURLS#1872]
I find this rather annoying because as with almoust any url shortener links are case sensitive. Looking at bit.ly and goo.gl we can see that i am not lying.

I did a bit of googleing and found some request https://github.com/YOURLS/YOURLS/issues/999
that literally made me laugh for a bit and then made me think (now why on earth would you make the possibilities of shortened urls so limited by removing case sensitivity

I seriously hope this hasn't become a thing

also if the keyword is in ALL CAPS

the shorturl becomes a zero since there are no lowercase letters (weird)

"DGFHGHSAGHJDSGHJ -> 0" (wtf)

if there were lowercase letters

like

"LoKE2" 

only "o2" would be accepted

"LoKE2 -> o2" (again wtf)

both the api and the admin page do this 

If this is a bug then i would be happy if it gets fixed

if its not a bug then can someone point me to a plugin as i found none during my search

@ozh

**Comment by ozh** [comment]
There are several issues about this. This has even its own topic in the readme FAQ.

**Comment by chtaube** [comment]
Take a look at `user/config.php`:

    /** URL shortening method: 36 or 62 */
    define( 'YOURLS_URL_CONVERT', 36 );
    /*
     * 36: generates all lowercase keywords (ie: 13jkm)
     * 62: generates mixed case keywords (ie: 13jKm or 13JKm)
     * Stick to one setting. It's best not to change after you've started creating links.
     */
