### ISSUE TITLE
Make random-keywords a core plugin

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#1877]
Why isn't this bundled?

**Comment by ozh** [comment]
(this would require a renaming of the functions and a check for previous version activated)

**Comment by Preovaleo** [comment]
+1

**Comment by Preovaleo** [comment]
we could add it as a submodule 
git submodule add -f https://github.com/YOURLS/random-keywords.git user/plugins/random-keywords

**Comment by dgw** [comment]
Gonna self-assign this. Been too long since I did anything in PHP (mostly Python, Lua, and JS these days).

**Comment by dgw** [comment]
Closing this, as #2367 was merged a while ago and the standalone plugin repo was archived.
