### ISSUE TITLE
Public interface instructions unclear

### ISSUE THREAD

**Issue by sison2466** [YOURLS/YOURLS#1879]
I am sorry if this seems stupid.  I have search, google, and trial and errored how to get a public interface working properly.

I have the standard install ( 'YOURLS_PRIVATE', true )which works fine.  

I wanted to see if I could make a standard interface.

1) Unzipped infinity squared files into the root
2) Renamed the config-sample file in the Public folder that came with infinity squared to config.php
https://github.com/tomslominski/infinity-squared
3) I was not sure how to follow the instruction below, so I renamed the file config.php and left it in the root.
"A sample public interface is provided, named sample-public-front-page.txt. Rename it as a .php file and customize it to suit your needs."

I tried to access the interface by typing both mydomain.com/config.php (which should be the file in step 3)

and mydomain.com/public/config.php (which should be the file in step 2)

All bring up a "Forbidden You don't have permission to access / on this server" error.  

Permissions are set on the folder as 755.

What am I doing wrong?

**Comment by ozh** [comment]
With YOURLS out of the box : install, rename sample-public-front-page.txt to public.php, done, you have your public interface available at http://yourdomain/public.php

With infinity-squared, don't know.
