### ISSUE TITLE
Cannot set background to transparency on stats

### ISSUE THREAD

**Issue by xenu-cf** [YOURLS/YOURLS#1880]
Hi! I cannot set the background of the line and pie graphs to transparent, even if I edit `functions-infos.php`! No matter what I do, it stays white!

how do I set it?

**Comment by ozh** [comment]
Don't know if that's possible with the current graph library we're using, [Google Charts](https://developers.google.com/chart/). Check there.

**Comment by xenu-cf** [comment]
Found something https://developers.google.com/chart/image/docs/chart_params (find background fills).

Where would I set that parameter though?
