### ISSUE TITLE
Not being able to log in

### ISSUE THREAD

**Issue by Redstonegenie7** [YOURLS/YOURLS#1884]
When i login to the admin page it won't let me login and just keeps redirecting here is my .htaccess file its in a subdomain as you can see something.com/bitly/

# BEGIN YOURLS
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /bitly/
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^.*$ /bitly/yourls-loader.php [L]
</IfModule>
# END YOURLS

**Comment by Redstonegenie7** [comment]
Please help and do not close it

**Comment by Redstonegenie7** [comment]
Never mind finally fixed it just re-installed it

**Comment by ozh** [comment]
Two issues, same subject, unreadable formatting, zero added value to anyone, and a PEBKAC conclusion. I already love you.

**Comment by Redstonegenie7** [comment]
U are really evil and being a D**k head

**Comment by ozh** [comment]
Just doing precisely [as advertised](https://github.com/YOURLS/YOURLS/blob/master/CONTRIBUTING.md) (that's the yellow link to **Guidelines** that shows when you open a new issue but you didn't bother to read), ie "Please take a moment to review this document, or see your issue closed with harsh comments".
