### ISSUE TITLE
Remove all common functions from `class-mysql.php`

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#1888]
When you create a custom DB layer, [SQLite support](https://github.com/ozh/yourls-sqlite) for instance, you should not have to [duplicate or rewrite core functions](https://github.com/ozh/yourls-sqlite), it should just consist in writing functions hooked into filters

**Comment by NILIHK** [comment]
This. 

I'm currently looking to write in postgresql support into yourls as our current platform is closing down and the one we're moving to had less than perfect mysql support, there is a mention within one of the files about drop in db support but there is no further mention of this in documentation or example files which would help people like myself who don't want to have to go through and read every line (ok no every but a lot) of the program to re-write the database layer.

**Comment by ozh** [comment]
Deprecated issue since DB layer change
