### ISSUE TITLE
Stats Page Graph Not Using Time Zone Offset

### ISSUE THREAD

**Issue by just-mike** [YOURLS/YOURLS#1893]
This is related to Issue 544: [Stats page graph time not using time zone offset] (https://code.google.com/p/yourls/issues/detail?id=544)

Issue 544 was closed on Aug 16, 2012 even though issue was only partially resolved.

Times displayed on stats page (graph's x-axis and informational section referring to link creation time) are GMT, however, GMT +/- offset is used on Admin page for link creation time.

### Proposed Solutions 
1. Use GMT +/- offset on stats graph
or
2. Make note on stats graph that times are GMT.

### This is a bug because...
Inconsistent use of time zone offset specifically specified in configs is confusing.

* YOURLS version: 1.7

**Comment by ozh** [comment]
Did you try with current master? There have been a number of small fixes here and there regarding timezones and time offsets

**Comment by just-mike** [comment]
I made a mistake. I am using 1.7.1. 

I have two instances, both pulled from master at date of install. First was installed 3/22, second 4/20. Both exhibit the behavior.

**Comment by ozh** [comment]
Pull request welcome!

**Comment by just-mike** [comment]
lol. Any pull request from me will be for solution #2. It will take some time as am new to git updates

**Comment by ozh** [comment]
Closing, #2048 should resolve this
