### ISSUE TITLE
No Way for YOURLS Users to Communicate With Each Other

### ISSUE THREAD

**Issue by just-mike** [YOURLS/YOURLS#1895]
Why doesn't YOURLS have a forum?

This is prompted by my desire to apply filter/actions on a per-link basis. I checked the available plugins and there are non that work on a per-link basis. I normally check the forums to see what others have tried. I searched the issues, but my query isn't an issue.

**Comment by ozh** [comment]
[because](http://blog.yourls.org/2012/06/forums/) :-)

Issues can be also a neat way to communicate : ask a clear question, get an answer from me or someone else, and this can be searched & found by others.

**Comment by just-mike** [comment]
Damn. The blog. I missed that.
