### ISSUE TITLE
Public Interface - No output

### ISSUE THREAD

**Issue by moloe00** [YOURLS/YOURLS#1896]
I've made a public interface on https://brw.li/.
Everything works but when I enter a long link to shorten, there is not output.
Using YOURLS 1.7.
What's wrong?
Sincerly,
Moritz

**Comment by ozh** [comment]
From the included `sample-public-front-page.txt` : 
```
 * This is an example file for a public interface and a bookmarklet. It
 * is provided so you can build from it and customize to suit your needs.
 * It's not really part of the project. Don't submit feature requests 
 * about this file. It's _your_ job to make it what you need it to be :)
```

Looks like you edited this file to customize it (which is the right thing to do) but you deleted parts you want that outputs the short URL. Other than this your install is [functional](https://brw.li/melodeath) it seems.

Again, your job :)

**Comment by moloe00** [comment]
Ok, thank you for your quick support!
