### ISSUE TITLE
'Random Keywords' Plugin activation fails with none specific error.

### ISSUE THREAD

**Issue by Spereicle** [YOURLS/YOURLS#1897]
This is a bug because: 'Random Keywords' Plugin activation fails with none specific error.

Clicking "Activate" results in Error page with "Plugin generated unexpected output. Error was: "
 -- That's it, nothing more specific.

Debug Shows:
DB driver: pdo
SELECT `option_name`, `option_value` FROM `tiny_options` WHERE 1=1
Check for new version: no

Bug Recreation:
Install random-keywords per directions
  -Create /user/plugins/random-keywords
  -Install files from https://github.com/YOURLS/random-keywords

Within Yourls interface: Manage Plugins
Plugin show up with "(no info)" in all fields and the following errors:
Notice: Undefined index: Plugin Name in /home/big_pond/big-pond.org/tiny/includes/functions-plugins.php on line 571
Notice: Undefined index: Plugin Name in /home/big_pond/big-pond.org/tiny/includes/functions-plugins.php on line 572 (Repeated a total of 5 times)

Resolved by Adding the following to the top of the plugin.php file:
<?php
/*
Plugin Name: Random Keywords
Plugin URI: http://yourls.org/
Description: Allow Random Keywords in short URLs (like <tt>http://sho.rt/alkJJA</tt>)
Version: 1.0
Author: Ozh&LC
Author URI: http://ozh.org/
*/
?>

Now listings are correct in Manage Plugins.

Clicking "Activate" results in Error page with "Plugin generated unexpected output. Error was: "

Can Not install plugin.

This issue may be happening across all user added plugins.

Default plugins (Allow Hyphens in Short URLs, etc) DO function properly
New install of 1.7 Yourls release
New MySQL Database
PHP Version 5.6.5
MySQL Version: 5.1.56-log

**Comment by LeoColomb** [comment]
Well, I see you are at version `1.0`.
[The current is `1.1`](https://github.com/YOURLS/random-keywords/blob/ff83532bd9534d8a9947664b89dfce3235dea567/plugin.php#L6)

Are you up to date?

**Comment by Spereicle** [comment]
Thank you! -- that lead me to the solution.

I right clicked on the file pluggin.php and downloaded the html, makes much more sense now that I downloaded the actual code... And works.

**Comment by LeoColomb** [comment]
@Spereicle :smile_cat:

**Comment by ozh** [comment]
This raises anyway the issue that, if I understand correctly, you can activate a file that's not a plugin at all
