### ISSUE TITLE
More validation of plugin files

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#1898]
You can activate a file that's not a plugin at all, see #1897
- this file appears with `(no info)` as name, author, version and description: I think at least a name should be mandatory
- `(no info)` as plugin name and plugin author are absurdly linked to `http://sho.rt/admin/(no%20info)`
- is there any way to check that the file is at least some PHP ?

**Comment by dgw** [comment]
What about checking that the file contains `<?php`? Not foolproof, certainly, but better than no check at all. HTML should fail that test because `<` needs to be escaped.

**Comment by vaughany** [comment]
Could you require that plugin authors provide author name, plugin name, plugin version and plugin release date inside a function which you can call from the core code? A failure to find the function, or if null/empty return would prevent the plugin being made live.

**Comment by ozh** [comment]
Requiring all the info won't help making sure the plugin is valid, requiring a release date would also break 100% of existing plugins which we won't do

Ideally we need a sandboxed activation process, like it's done in WordPress, but I haven't butchered and dissected their way of doing it yet :)

**Comment by fredl99** [comment]
> (no info) as plugin name and plugin author are absurdly linked to http://sho.rt/admin/(no%20info) 

If this behaviour is reliable and reproducable then why not ship a prepared (static) page with that name? 

It could contain some information that there's something wrong with that file, maybe a hint to upgrade or some other notes. If it's not static the page could also tell the plugin's filename and/or a link to deactivate it.

Not a solution but at least some use for that link. Just an idea...

**Comment by peterberbec** [comment]
Quick and dirty <php? test

**Comment by ozh** [comment]
We should maybe have a look at https://github.com/Corveda/PHPSandbox. Then, if not trivial to use and 100% foolproof, this issue will be closed

**Comment by ozh** [comment]
During all these years, I've never read from someone troubled by this lack of verification. Closing.
