### ISSUE TITLE
Bookmarket not Working With https websites

### ISSUE THREAD

**Issue by wpdiv** [YOURLS/YOURLS#1900]
I am absolute beginner of YOURLS and just installed your script in http://www.wpdiv.in and works fine. But i did experience some issues.

1. I have downloaded your script today from gitub installed successfully. Showing as v1.7 version. But i have noticed some of the sites using v1.7.1, why does it so?

2. Bookmarklet not working with 'https' secured domains but no issues with 'http' domains

Note: I am using Google Chrome browser (Version 42.0.2311.135 m)

3. Is it possible to categorize the shorten URL into categories like bitly interface?

4. default shorten URLs generated with numbers such as ....

http://wpdiv.in/4
http://wpdiv.in/5

How can i force make it as random string?

Please help me to troubleshoot the above issue.

**Comment by ozh** [comment]
This is an example of a bad issue: you address 3 different problems, two of which are not relevant to the issue title hence won't be searchable by other users.

Regarding 1.7.1 : they're running [current master](https://github.com/YOURLS/YOURLS/archive/master.zip)

Regarding HTTPS bookmarklets: HTTPS sites won't accept that you load a HTTP javascript. Either you can host your YOURLS install on HTTPS, or you cannot use these bookmarklets on HTTPS sites.

Regarding random vs sequential short URL: I'll let you RTFM.

**Comment by WPDIV** [comment]
Sure, Let me RTFM.
