### ISSUE TITLE
Allow multiple URL for the same reference

### ISSUE THREAD

**Issue by Nhoya** [YOURLS/YOURLS#1901]
Hey there, when i try to short an URL that already exist it gives me the previous shortned URL, there is a way shorten "already-shortned" links?

eg google.com -> http:// sh.rt/1a && http://sh.rt/344bfsha32

**Comment by chtaube** [comment]
Sure. Just take a look into the configuration file `user/config.php` within your installation. Look for this:

```
/** Allow multiple short URLs for a same long URL
 ** Set to true to have only one pair of shortURL/longURL (default YOURLS behavior)
 ** Set to false to allow multiple short URLs pointing to the same long URL (bit.ly behavior) */
define( 'YOURLS_UNIQUE_URLS', true );
```

Read the comment block. Then edit the file:

Replace
```
define( 'YOURLS_UNIQUE_URLS', true );
```
with
```
define( 'YOURLS_UNIQUE_URLS', false );
```
Easy, isn't it? ;-)

**Comment by Nhoya** [comment]
yes, thanks man!
