### ISSUE TITLE
expand action, something wrong?

### ISSUE THREAD

**Issue by Nhoya** [YOURLS/YOURLS#1902]
Hey guys i'm trying to use the API for expand a link but something seems go wrong,
This is my request:
curl -s -L "http://sho.rt/yourls-api.php?signature=$apikey&action=expand&format=json&shorturl=http://sho.rt/43

The result is that, dunno why, the site take as keyword the url.. this is the answer from website
{"keyword":"httpshort43,"message":"Error: short URL not found","errorCode":404}

**Comment by dgw** [comment]
Are you sure you've set `YOURLS_SITE` properly in the config? Do you have multiple domains pointed at this YOURLS instance? Does it work on either HTTP or HTTPS (not restricted to one or the other)?

Per [this line](https://github.com/YOURLS/YOURLS/blob/ff14d7e15232a2beee5ee93ddaf1ec5ebb3d5e1a/includes/functions-api.php#L179) of code, the API is doing a dumb string replacement to accept either the full short URL or just the keyword, so any deviation in the prefix from the value of `YOURLS_SITE` will cause it to fail.

**Comment by Nhoya** [comment]
ok found the problem!
 $keyword = str_replace( YOURLS_SITE . '/' , '', $shorturl ) 
in my config accept only the contents after http://sho.rt/... thanks :)

**Comment by ozh** [comment]
I cannot reproduce this. If I try http://127.0.0.1/yourls/yourls-api.php?action=expand&username=yourls&password=yourls&shorturl=http://127.0.0.1/yourls/1 I get:
```xml
<result>
  <keyword>1</keyword>
  <shorturl>http://127.0.0.1/yourls/1</shorturl>
  <longurl>https://github.com/YOURLS/YOURLS</longurl>
  <title>YOURLS/YOURLS &middot; GitHub</title>
  <message>success</message>
  <statusCode>200</statusCode>
</result>
```

**Comment by ozh** [comment]
(using current master)

**Comment by Nhoya** [comment]
hey @ozh i solved the problem using only the last part of the URL, i written regex and now is all ok ;) soon i will release (hope soon) an utlity pack for yourl based on API
