### ISSUE TITLE
Plugin with Per-Link Filters Actions

### ISSUE THREAD

**Issue by just-mike** [YOURLS/YOURLS#1903]
Would you create a sample plugin?

I want the ability to apply filter/actions on a per-link basis. For example, while creating a link, have the a ability to filter all traffic from Canada to a separate, specified link. Another filter can filter based on user agent (desktop vs mobile). Ideally, this filter action can be configured in the link dialog as opposed to plugin admin section. 

I have checked the available plugins and there are non that work on a per-link basis. All plugins work globally. 

My workaround for mobile/desktop filtering looks like this:
Yourls -> PHP filter script -> (Yourls (desktop) OR  -> Yourls (mobile))

Allowing me to collect stats with yourls.

**Comment by ozh** [comment]
A per-link plugin is not different from what you call a "global" plugin: you add an action or a filter, and then conditionally on this hook you check for conditions to trigger or not your custom functions. See example of https://github.com/YOURLS/YOURLS/wiki/Plugin-List#conditional-toolbar for instance.

**Comment by just-mike** [comment]
It feels like I asked one question and you answered someone else's. I see the example checks for a condition in the incoming requests and then does an action (toolbar) if met. How does that get set per link?

I am most likely using wrong terminology. Pre-link probably should be per Short URL

How to make:
http://sho.rt/tb/something show toolbar
http://sho.rt/something NOT show toolbar

http://sho.rt/somethingelse show toolbar 
http://sho.rt/tb/somethingelse NOT show toolbar

**Comment by ozh** [comment]
Same answer as above: each time, check for conditions that trigger or not your custom behavior.

In your example: if shorturl == 'something' then do this or that.
Or maybe: if keyword ends with 'else' do this or that.
Or maybe: compare each keyword with a list of keyword you defined and if found do something special instead of the regular redirection.
Don't know. Depends on what you need.
