### ISSUE TITLE
Redirect all unused domains to a specific site

### ISSUE THREAD

**Issue by shawaj** [YOURLS/YOURLS#1904]
There is a useful plugin "fallback url" that will redirect something like http://sho.rt/nonexistant to http://fallbackurl.com however this does not work in all instances

- if you put just http://sho.rt it does not redirect to fallback url, but gives a permissions error
- if you put http://sho.rt/examplefile.html or anything with a file ending, it redirects back to http://sho.rt instead of back to the fallback url and gives a permissions error

Is there a way using .htaccess or otherwise to rectify this?

Thanks

**Comment by ozh** [comment]
Then at the root of your domain put [a file that will redirect](https://www.google.com/search?q=php+redirect) to the fallback URL.

**Comment by shawaj** [comment]
That's not really a fix though...it's a workaround at best.

Thanks

**Comment by chtaube** [comment]
YOURLS already redirects to the document root as a fallback. I am not sure what the fallback url plugin does differently, but a `index.php` or `index.html` in the document root should really be all you need. I am using this [here](http://chtau.be/invalid).

Of course you shouldn't get a permissions error when accessing the document root. Maybe there is some misconfiguration on your web server? Or you simply need to create the `index.php` file first?

```
<?php
header('Location: http://www.fallback.url/');
```

**Comment by shawaj** [comment]
So if the short URL doesn't exist it automatically redirects to root?

Even when not using the fallback URL plugin?

Thanks

**Comment by chtaube** [comment]
Yes, indeed!

That is why I don't understand what that plugin should be good for…

There is no `index.php` shipped within the default installation of YOURLS. This should result in a 404 error (file not found) when using an invalid URL - which is a safe default, IMO.

If you want something else - like a redirection elsewhere or a simple page with usage instructions or whatever, this is supposed to be done by the admin.

My index page is actually just static html with some javascript in it. No plugin installed.

**Comment by shawaj** [comment]
So why does that plugin exist then?

Does it maybe remove a step in the redirects?

Thanks

**Comment by ozh** [comment]
The plugin exists because someone wanted their YOURLS to do things their way, and that's what the plugin API is for. Namely, the plugin can allow having an index page (public interface or whatever) and a fallback URL that's not the index page.

**Comment by shawaj** [comment]
Yes, so it seems the point is that it removes a step in the redirects.

So instead of sho.rt/test -> sho.rt/ -> fallba.ck

It goes sho.rt/test -> fallba.ck

Which seems like it is much better.

What I wonder, is two things:

- is it possible to include the root in this? At the moment I have done
with .htaccess for root
- is it possible to include things with file extensions in fallback url
plugin - if you do something like sho.rt/test it works fine, but with
sho.rt/test.html it does not work?

Thanks

**Comment by chtaube** [comment]
I'm sorry, but I completely lost track about what you want to do and I cannot reproduce your thoughts. What do you mean with *„is it possible to include the root in this“*? What is the problem with file extensions that you have?

This is the behaviour of YOURLS without any plugin magic:
* [chtau.be/invalid](http://chtau.be/invalid) -> *not a valid short URL => redirects to* chtau.be/ – serves `/index.html`
* [chtau.be/invalid.html](http://chtau.be/invalid.html) => *not a valid short URL => redirects to* chtau.be/ – serves `/index.html`
* [chtau.be/](http://chtau.be/) => *YOURLS is not involved, webserver handles this* – serves `/index.html`
* [chtau.be/1](http://chtau.be/1) => *valid short URL - redirects to long URL*  www.chtaube.eu/

Does it work differently on your end? Even if you disable the *fallback URL* plugin?

**Comment by shawaj** [comment]
Hi again,

Yes but in your example there is an additional redirect, if you are using index.php or similar to redirect to another domain.

In your examples:

- chtau.be/invalid -> not a valid short URL => redirects to chtau.be/ – redirects to fallback.url
- chtau.be/invalid.html => not a valid short URL => redirects to chtau.be/ – redirects to fallback.url

However, with the fallback url plugin it removes a redirect step, which is surely better for SEO purposes:

- chtau.be/invalid -> not a valid short URL => redirects to fallback.url

Only problem is it does not work for things with extension like .html, .php etc so defaults to standard YOURLS functionality as in your example:

- chtau.be/invalid.html => not a valid short URL => redirects to chtau.be/ – redirects to fallback.url

What I want to do, is include that scenario in the fallback url plugin, to minimise the amount of unnecessary redirects.

**Comment by ozh** [comment]
Then contact the plugin author ?

**Comment by shawaj** [comment]
Well yes, I have.

I just wondered if anyone knew of a quick fix to his code to make it happen.

**Comment by fanpero87** [comment]
I was looking to do something like this. Redirect non-existing URLs to a specific URL. 
This was a simple easy solution for me. 
I just added an `index.php` file on the root of the folder and added that line and that was it. It works as intended. 
Very nice! Thanks 

> YOURLS already redirects to the document root as a fallback. I am not sure what the fallback url plugin does differently, but a `index.php` or `index.html` in the document root should really be all you need. I am using this [here](http://chtau.be/invalid).
> 
> Of course you shouldn't get a permissions error when accessing the document root. Maybe there is some misconfiguration on your web server? Or you simply need to create the `index.php` file first?
> 
> ```
> <?php
> header('Location: http://www.fallback.url/');
> ```
