### ISSUE TITLE
Can only go to <url>/admin

### ISSUE THREAD

**Issue by Z3roCoder** [YOURLS/YOURLS#1905]
Is it intended that only /admin is accessible?
You can check it out here: short.novalos.net - It is forbidden, but short.novalos.net/admin is perfectly accessible. 

How can I make it that non-logged in users can access the site as well?

**Comment by chtaube** [comment]
What do you expect to be accessible?

Short URLs generated within YOURLS should be accessible by everyone. Aren't they?

Or do you want to set up a public URL shortening service, where everybody can create shortened links? Then you should probably [read this](https://github.com/YOURLS/YOURLS/wiki/Private-Or-Public).

**Comment by ozh** [comment]
:+1: to what @chtaube says
