### ISSUE TITLE
API returns 403 with hostgator

### ISSUE THREAD

**Issue by shadowloud** [YOURLS/YOURLS#1906]
Hello,

I'm trying to get "http" to return from api, but it redirect me to 403. I was wondering why? I don't think it's normal. For example :

Would work : http://cdn.pol.quebec/yourls-api.php?signature=ee2a5e60e1&action=shorturl&format=simple&url=www.google.com

Does not work : http://cdn.pol.quebec/yourls-api.php?signature=ee2a5e60e1&action=shorturl&format=simple&url=http://www.google.com

How can I fix it? Thank you

**Comment by ozh** [comment]
Hostgator's default server config returns error pages to any URL that contains a query string with a URL in it, eg http://cdn.pol.quebec/admin/index.php?whatever=http://omg.dude/

Most likely you cannot use bookmarklets and I'm surprised anything works at all.

Check https://github.com/YOURLS/YOURLS/wiki/Endless-Spinning-Icon
