### ISSUE TITLE
Rewrite mydomain.com/yourls to mydomain.com/yourls/admin

### ISSUE THREAD

**Issue by xmyfree** [YOURLS/YOURLS#1907]
Sorry I'm new to apache. What I want to do is each time I enter mydomain.com/yourls, I will go to mydomain.com/yourls/admin to log in. Do you know how I can achieve this? Thank you. Appreciate your help :)

**Comment by ozh** [comment]
Make an `index.php` page that will [redirect you](https://www.google.com/search?q=php+redirect)
