### ISSUE TITLE
Unable to shrink URLs with get requests inside

### ISSUE THREAD

**Issue by Nhoya** [YOURLS/YOURLS#1908]
Hey guys, i'v a litte problem, tryng to shrink a link like that http://www.inforge.net/xi/resources/z0r-desktop.13552/update.php?update=13618 via API it gives me 406 error but via Web is all ok, can you suggest some solution?

Thanks for your time!

**Comment by ozh** [comment]
Multiple issues deal with this. As the readme explain, you have to properly URL encode the parameters.
`url=blabla&amp;etc..` and not `url=blabla&etc`
