### ISSUE TITLE
Redirection issue, details inside

### ISSUE THREAD

**Issue by quorn23** [YOURLS/YOURLS#1909]
Hi guys,

I'm probably don't see the forest while surrounded by trees. I have the following setup:
WP Blog in domain.com/blog/ but my blog index.php is in domain.com/
I can reach Yourls admin with domain.com/admin

Now when i change how WP handles Permlinks it "breaks" my page. I can view the first page, but when i try to go to page 2 (domain.com/?paged=2) it just reloads the index page.
I'm using a WP Plugin, so when i post new posts on twitter and co it uses my own domain with yourls to generate a link to the post.

Also i have a php proxy for myself on my domain. Before the installation of yourls i was able to access it with domain.com/proxy/ now this forwards me to domain.com

Can you tell me what went wrong?

**Comment by ozh** [comment]
Sure : as stated in the readme, YOURLS needs its own .htaccess and cannot share the directory with another app that needs its own one as well. See http://yourls.org/#FAQ

**Comment by quorn23** [comment]
Hi Ozh,
Thanks for your answer, yes i know that, i didn't had an htaccess in my root before i installed yourls.
I thought as wordpress is in domain.com/blog i can use yourls in my root. I will install it in a sub folder. I guess the redirection to domain.com/blog in the index is causing that issue. 
*facepalm myself* Thanks and cheers!
