### ISSUE TITLE
REQUEST: Time on site tracking

### ISSUE THREAD

**Issue by multivisas** [YOURLS/YOURLS#1910]
I really need to track the amount of time that is spent on each shortened URL. Is there currently functionality for that or is this something that would need to be added. If it needs to be added please advise me if this project is possible and we can discuss it. I know real time tracking is possible for chat software's so it must be possible for this. I know my situation might be a little unique that i have shortened URL's for individual clients but it is the case and i need to figure it out. Thanks this actually is an urgent situation for me thanks.

**Comment by dgw** [comment]
Maybe modify the [sample toolbar plugin](https://github.com/YOURLS/YOURLS/blob/master/user/plugins/sample-toolbar/plugin.php)?

**Comment by ozh** [comment]
Indeed the only way to do this would be to display all your shortened URLs into an iframe (yuck) like the aforementioned plugin, and in that iframe add code to track time spent (probably a javascript function that would poll a special URL from your YOURLS install every XX seconds to increment a time counter)

See wiki page https://github.com/YOURLS/YOURLS/wiki/Possible-With-A-Plugin
