### ISSUE TITLE
[Suggestion] Plugin that does not count the clicks from a specific IP

### ISSUE THREAD

**Issue by Glutius** [YOURLS/YOURLS#1911]
Can you add an option or a plugin that does not count the clicks from a specific IP?

**Comment by LeoColomb** [comment]
@Glutius As you said, it's completely doable with a plugin.
I'm pretty sure there is already one for it in the [Plugin list](https://github.com/YOURLS/YOURLS/wiki/Plugin-List).

**Comment by LeoColomb** [comment]
For example you can use [Don't Track Admins](https://github.com/dgw/yourls-dont-track-admins) by editing [this line](https://github.com/dgw/yourls-dont-track-admins/blob/71c24903de82abd3dc25128140aff888da1eb729/plugin.php#L46) with your condition.

**Comment by Glutius** [comment]
Thanks, works like a charm!
