### ISSUE TITLE
404 error on shortened urls and stat urls

### ISSUE THREAD

**Issue by DRankex** [YOURLS/YOURLS#1914]
Whenever I try to access one of my shortened urls I get the following error.

[404](http://puu.sh/icpDo/17b012ae3d.png)

I'm using IIs8 on windows server 2012, a dyn dns, [web.config](http://pastebin.com/t1Q2Zac3), [user/config.php](http://pastebin.com/p9Wwp3NF).

I've taken a look at the wiki, but sadly the web.config pasted there didn't work either.

If there is any more information needed from me, I'm happy to supply.

Thanks, I'm sorry for any inconvenience cause by this.

**Comment by ozh** [comment]
Most likely it's because your IIS server lacks [url-rewrite](http://www.iis.net/downloads/microsoft/url-rewrite)

**Comment by DRankex** [comment]
I seem to already have it installed http://puu.sh/icsNG/26971da7e4.png

**Comment by DRankex** [comment]
It even tests positive when I try a shortened url http://puu.sh/icuZT/cc88e29b5f.png

**Comment by ozh** [comment]
For the record, I have not the slightest clue what that thing in the last screenshot is ...

**Comment by LeoColomb** [comment]
@ozh It's the regex pattern setup window for rewrite engine on IIS.

That said @DRankex, I'm not sure this pattern is the default one write on the YOURLS' web.config.

**Comment by DRankex** [comment]
@LeoColomb The second one matches you config in the wiki. http://puu.sh/icztg/b566859a6f.png
