### ISSUE TITLE
get_option() function undefined

### ISSUE THREAD

**Issue by subhojeet** [YOURLS/YOURLS#1915]
![screenshot1](https://cloud.githubusercontent.com/assets/5249581/8005790/7204e4ac-0bab-11e5-8848-68d6f451658f.png)

trying to set up yourls and while installation I get the following error
PHP Fatal error:  Call to undefined function get_option() in /var/www/yourls/includes/functions-compat.php on line 190

Even though the tables are created in the database and the urls can be added to the database but when clicked on shorten it gives a blank page with a similar error in the log that the Call to get_option() function. What should I do. Am I missing something?
Details of server
Server version: Apache/2.2.15 (Unix)
CentOS release 6.6 (Final)
PHP Version 5.3.23

**Comment by ozh** [comment]
You're not missing anything, I did :) Fixing!

**Comment by ozh** [comment]
This should do it, please report

**Comment by subhojeet** [comment]
Working.. :) Thanks...
