### ISSUE TITLE
[Question] How does YOURLS technically work?

### ISSUE THREAD

**Issue by Haklia** [YOURLS/YOURLS#1917]
Hi guys,

I hope I can ask my question here.

I'm wondering how does YOURLS technically work? 
I mean, when my short url is created, what system stores the fact that "short.com" goes to "www.mylongurl.com".

And if I want to set my YOURLS with a short url already used by someone else, what happens?

Many thanks in advance.

OP

**Comment by ozh** [comment]
To use YOURLS, you must first have a place where to host it. For instance, you have `haklia.com` and you host YOURLS on `haklia.com/short` or `short.haklia.com` or you get another different domain name such as `hak.li` or whatever.

When you create a short URL, data is stored in a MySQL database, for instance, in the same record are stored "bleh" and "http://superlongdomain.com/superlongURL" so when you request http://YourShortDomainWhereYouHostYOURLS/bleh (note the "bleh") you're redirected to http://superlongdomain.com/superlongURL

It's not "short.com" that gets redirected.

**Comment by Haklia** [comment]
Ok, thanks. It is a little bit more clear, but also a little bit still confused in my mind.

May be it is my misunderstanding of shortner system.

With a superlongurl.com, this is the domain provider that makes the link between the domain and the ip of my server.

But with the shortdomain.com, in my mind the link with superlongdomain.com is missing.

I understand that it is stored in my db.
But when somebody types "shortdomain.com/bleh" in his browser, how his browser knows that it must go to my "superlongdomain.com/superlongURL"?

Is there a "YOURLS server" that stores users data?

I'm sorry if this questions sound stupid. (I like understand how things work)

**Comment by ozh** [comment]
As I've said: "data is stored in a MySQL database". So, yes, obviously, there's a server that stores data

Example: I have a YOURLS instance set up on http://ozh.in/ and data stored there associate keyword `htlmcolors` with long url `http://www.w3schools.com/tags/ref_colornames.asp` so that when someone requests http://ozh.in/htlmcolors the software installed on ozh.in redirects on http://www.w3schools.com/tags/ref_colornames.asp

**Comment by Haklia** [comment]
Ok. Great.

Many thanks. :-)
