### ISSUE TITLE
Double slash in urls

### ISSUE THREAD

**Issue by Sergey95** [YOURLS/YOURLS#1918]
Good afternoon,

I have double slashes in all urls.
It looks like this:
http://s.link.com//admin/index.php
http://s.link.com//ezgz6

How to fix this?

**Comment by dgw** [comment]
My guess is the value of `YOURLS_SITE` set in config.php has a trailing slash. If that's the case, remove it and the issue should go away.

**Comment by ozh** [comment]
What @dgw said.
