### ISSUE TITLE
Ability to add tags to yourls

### ISSUE THREAD

**Issue by jayzisme** [YOURLS/YOURLS#1922]
It would be great if yourls that have been created could be tagged with keywords which would allow yourl dense sites to be searchable other than current methods.

We have thought about prefixing the custom URL to make them searchable but that breaks the flexibility  of the end user.  

The thought is the implementation of a simple tagging system would work wonders for sites with many active yourls.

**Comment by LeoColomb** [comment]
See #13 and #675.

**Comment by ozh** [comment]
This will be easily feasible when next db schema is implemented. No ETA.

**Comment by WebSpectrum** [comment]
was this ever implemented ??

**Comment by sathish1981** [comment]
@ozh - Is this possible in current build? I have 1.7.7, but still cant find tagging option out of the box. Do you have any suggestions?

**Comment by ozh** [comment]
@sathish1981 still not feasible out of the box because the next DB schema with no ETA isn't there :)

**Comment by HeyHarshi** [comment]
Are we still waiting for a 5-year-old - no ETA - DB Schema?

Should we ?

**Comment by NetOldie** [comment]
It would be nice if tags were possible soon. It provides a much better overview and you can then finally group the URLs.
