### ISSUE TITLE
Nginx : File not found when trying install yourls

### ISSUE THREAD

**Issue by dolomats** [YOURLS/YOURLS#1923]
Hello,
Anyone can help me make Yourls work on my nginx webserver !
i already downloaded last version and uploaded it.
configured the /user/conf.php file.

but when i try accéss to http://site.com/admin to start the instalation, i get "File not found"
i tried change the nginx rewrite rules following these topics but without succes : 

https://github.com/YOURLS/YOURLS/wiki/Nginx-configuration
https://github.com/YOURLS/YOURLS/issues/1715
https://github.com/YOURLS/YOURLS/issues/1652
http://www.chtaube.eu/kb/nginx_configuration

I m using Nginx+PHP-FPM and have wordpress installed
here is my nginx virtual.conf setting

"server {
    listen       80;
    server_name  website.com www.website.com;
 
    location / {
        root   /var/www/website/public_html/;
         index  index.html index.htm index.php;
		 try_files $uri $uri/ /index.php?$args;
    }
	
	rewrite ^/sitemap(-+([a-zA-Z0-9_-]+))?\.xml$ "/index.php?xml_sitemap=params=$2" last;
    rewrite ^/sitemap(-+([a-zA-Z0-9_-]+))?\.xml\.gz$ "/index.php?xml_sitemap=params=$2;zip=true" last;
    rewrite ^/sitemap(-+([a-zA-Z0-9_-]+))?\.html$ "/index.php?xml_sitemap=params=$2;html=true" last;
    rewrite ^/sitemap(-+([a-zA-Z0-9_-]+))?\.html.gz$ "/index.php?xml_sitemap=params=$2;html=true;zip=true" last;
	
	include global/restrictions.conf;
	include global/wordpress.conf;
	
	location ~ \.php$ {
    include /etc/nginx/fastcgi_params;
    fastcgi_pass 127.0.0.1:9000;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME /var/www/website/public_html/$fastcgi_script_name;
}

}
"
Thanks for help

**Comment by ozh** [comment]
There are already several issues, some still on going, about nginx configuration, and a wiki page. Please search before filing a new issue.

**Comment by dolomats** [comment]
i already searched for a while. you can see the links of the topic that i followed without succéss.

**Comment by ozh** [comment]
Indeed, my bad, sorry. This said, I have no further resource to point you to...

**Comment by LeoColomb** [comment]
@dolomats Your `try_files` dosn't seem to match with recommanded one: 
[`try_files $uri $uri/ /yourls-loader.php;`](https://github.com/YOURLS/YOURLS/issues/1715#issuecomment-50729488)

**Comment by dolomats** [comment]
Hi, 

 Thanks for the advice, i already did this and it shows me file not found.

Thank you for help...

**Comment by dolomats** [comment]
hello finally i install it on another apache server and it worked fine

**Comment by filljoyner** [comment]
I was able to fix this for nginx by creating a copy of yourls-loader.php and name it index.php. Change mod_rewrite to the follow:

`# BEGIN YOURLS
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^.*$ /index.php [L]
</IfModule>
# END YOURLS`

**Comment by LeoColomb** [comment]
@filljoyner `.htaccess` file is for Apache configuration, not nginx... 
Are you sure of what you're talking about? :confused:

**Comment by amnya** [comment]
> I was able to fix this for nginx by creating a copy of yourls-loader.php in the root directory and naming it index.php

This resolved my issue. Initially i had an installation where all links were always going to root. Did a fresh installation and i started getting error 404 GNINX, copy pasting the yours-loader and renaming it to index solved the issue immediately. Thank you.
