### ISSUE TITLE
Link shortner with single letter or number !?

### ISSUE THREAD

**Issue by dolomats** [YOURLS/YOURLS#1924]
Hello,

 After i figured out how to make it work (fortunately), i m facing some issue.

 The link got shortned with a single letter or number like :

    http://domaine.com/a
    http://domaine.com/f
    http://domaine.com/8
    http://domaine.com/1

i would like to have some word istead of letters.

 Any help please !

**Comment by LeoColomb** [comment]
Its not an issue, this is the default behavior.
See #1871.
