### ISSUE TITLE
Moving search to top of index page

### ISSUE THREAD

**Issue by fncll** [YOURLS/YOURLS#1925]
Before I delve in and try, would it make sense to write a plugin to move the search/filter form to the top of the index page table of results (are their appropriate hooks to do so)? Thanks!

**Comment by ozh** [comment]
Any plugin makes sense if you feel the need for it :-)

if you think hooks are missing and could be a valuable addition (e.g.be useful to several people) feel free to open a pull request with suggested new ones

**Comment by fncll** [comment]
I was just wondering if hooks that would allow me to write such a plugin already exist (before I start blundering around trying to figure it out)?
