### ISSUE TITLE
URL is coming as numbers

### ISSUE THREAD

**Issue by ponibass** [YOURLS/YOURLS#1927]
I have installed yourl in google cloud server. While creating short url, it is coming as 1. Second time it is coming as 2. I didnt get 5 digits short url. Please give me solutions.

**Comment by dgw** [comment]
Install and configure [this plugin](https://github.com/YOURLS/random-keywords).

**Comment by ozh** [comment]
As @dgw said. By the way, there are a lot of issues about this, please SEARCH before opening issues
