### ISSUE TITLE
In Nginx meta data and image not shown

### ISSUE THREAD

**Issue by dipenpatel235** [YOURLS/YOURLS#1928]
Hello...
I tested yourls using httpd(apache) and nginx both.
so in apache it is working fine but in nginx when we share short link on facebook so it is not shown image and meta data.
i used same below nginx.conf file
https://github.com/YOURLS/YOURLS/wiki/Nginx-configuration

Thanks.

**Comment by LeoColomb** [comment]
Interesting.
Could you comply with [Contributing Guidelines](https://github.com/YOURLS/YOURLS/blob/master/CONTRIBUTING.md), eg: give some software versions?
Thanks!

Ref: #1715

**Comment by dipenpatel235** [comment]
./nginx -V
nginx version: nginx/1.7.7
built by gcc 4.8.2 20131212 (Red Hat 4.8.2-8) (GCC)
TLS SNI support enabled

**Comment by chtaube** [comment]
Seems like I cannot confirm this, facebook's preview looks fine to me… but maybe I did understand this wrong?

I'm running nginx 1.8.0 and YOURLS 1.7-git-135.12024cc

![yourls-facebook](https://cloud.githubusercontent.com/assets/929763/8762748/21465390-2d82-11e5-96a8-e6f8a38ab801.jpg)

**Comment by LeoColomb** [comment]
@chtaube Thanks a lot for your feedback: :kissing_closed_eyes: 
@dipenpatel235 Is your install clean and based on the latest master version?
If yes, could you paste here your nginx conf?

**Comment by dipenpatel235** [comment]
Thanks For Your Prompt Replay...
Now I Fixed.
Reason for Not displayed images
in my conf file i added extra page speed  and gzip so i removed that and now starting displayed....
Thanks...

**Comment by LeoColomb** [comment]
> So may be issue in pagespeed

Good to know, thanks for your reply!
:peach:
