### ISSUE TITLE
Redirect to URL with username:password@link not working

### ISSUE THREAD

**Issue by ytlevine** [YOURLS/YOURLS#1930]
If I have a short URL redirecting to username:password@link, the username and password don't seem to be stored/sent as part of the URL.
Any way to get this to work correctly?
Thanks!

**Comment by ozh** [comment]
URLs with embedded user:pass are [correctly sanitized](https://github.com/YOURLS/YOURLS-unit-tests/blob/master/tests/format/urls.php#L58-L63) and shortening such a URL seems to work for me: http://yourls.org/dk

**Comment by ytlevine** [comment]
Tried it again, and it shows up with the full URL, including username:password@URL, but the link from the panel removes the username:password part, even when I click on it directly (not using the short URL).
Unless there's some plugin that's getting in the way?

**Comment by ytlevine** [comment]
Never mind, tried disabling the Google Analytics plugin (https://katz.co/add-google-analytics-link-tagging-yourls/), and it worked correctly, so that must have been the issue.
