### ISSUE TITLE
Trailing whitespaces are not stripped from the long URL

### ISSUE THREAD

**Issue by adigitalife** [YOURLS/YOURLS#1931]
Not sure if this is on purpose or not but this was reported to me by one of my users.  For example, if you enter into the long URL 'http://google.com/ ' then the link will be saved as 'http://google.com/%20'.

I think the simple solution would be to add the following somewhere:
$url =  trim ( $url , " \t\n\r\0\x0B" );

But where exactly?  I was also thinking that this could be a plugin just for those who want it but, again, I'm not sure where to insert it.

Some help please?

**Comment by LeoColomb** [comment]
Yep, strange. Need review.

**Comment by adigitalife** [comment]
I updated one of my old plugins that fixed a different problem:
https://github.com/adigitalife/yourls-fix-long-url

It now also removes trailing spaces but not other possible types of whitespaces.

**Comment by ozh** [comment]
Indeed, leading and trailing whitespace should be stripped (eg shortening ` https//www.google.com/ ` makes `http://%20https//www.google.com/%20` as of now). I'll look into this.
