### ISSUE TITLE
URL is changed on shortening resulting in 404

### ISSUE THREAD

**Issue by Sushubh** [YOURLS/YOURLS#1932]
Took me a while to notice this.

I shortened this URL:
http://linksredirect.com?pub_id=28CL11&url=https://paytm.com/dth

Yourls backend turned it into:
http://linksredirect.com?pub_id=28cl11&url=https://paytm.com/dth

Which gives 404. 

If I try to edit the short link and change the link, the system does not accept it and throws an error. 

Error updating http://linksredirect.com?pub_id=28cl11&url=https://payt[...] (Short URL: thJQAcsgVi)

I checked on this public demo:
https://www.softaculous.com/demos/YOURLS
And was able to replicate the bug.

**Comment by Sushubh** [comment]
https://github.com/YOURLS/YOURLS/issues/1651#issuecomment-38028564 does not appear to fix this issue.

**Comment by LeoColomb** [comment]
Have you tested this on the latest [dev version](https://github.com/YOURLS/YOURLS/archive/master.zip)?

**Comment by Sushubh** [comment]
Just installed it. And same problem. 

http://linksredirect.com?pub_id=28CL11&url=https://paytm.com/dth 
was turned into
http://linksredirect.com/?pub_id=28cl11&url=https://paytm.com/dth

**Comment by LeoColomb** [comment]
Thanks for your feedback!

---
Related: #1889 #1890 #1894

**Comment by Sushubh** [comment]
Hello. Wanted to add something to this post. 

http://linksredirect.com?pub_id=28CL11&url=paytm.com works fine. but a link with extra attributes does not. 

Trying to shorten this URL:
http://linksredirect.com?pub_id=28CL11&url=paytm.com/?utm_source=email&utm_medium=bb&utm_campaign=eoss_bb_bkp_26_07&utm_term=primary

Breaks it.

**Comment by LeoColomb** [comment]
> I tried it again and it seems to work fine now.

Maybe some cached behavior :smile:.
Anyway, thanks for the details! :clap:
