### ISSUE TITLE
t.co referrals flagged as direct

### ISSUE THREAD

**Issue by gerbz** [YOURLS/YOURLS#1934]
When I share a yourls shortened URL on Twitter 98% of the traffic gets flagged as a "Direct Hit" when clearly it's from Twitter.  Shouldn't t.co be easy to detect since every URL on Twitter is wrapped?

Running v1.7

**Comment by ozh** [comment]
YOURLS just gets the referrer as passed by the client. If there's no referrer, that's a direct hit, period (most likely, I guess apps such as Tweetdeck don't pass any referrer).

You could of course make a custom plugin to handle t.co links as Twitter referrals but that's not how the web works (eg nothing prevents t.co links to be shared from any other site)

**Comment by gerbz** [comment]
Twitter is (one of) the most used link sharing tool in town.  To say "this is how we do it, period" doesn't address the issue - which is a real issue.

As for "this is how the web works".  Unfortunately it isn't anymore.  Most mobile apps with in app browsers don't pass referrers which is where the majority of hits happen these days.

Clearly shorteners like bit.ly (which is as direct competition as it gets) have it figured out, so there is a solution out there and it should be considered.

**Comment by ozh** [comment]
Twitter & t.co are the most used tools for you, some users use YOURLS in a vastly different way (a lot of marketing folks using it exclusively for email for instance)

Again : custom referral handling is completely possible with a plugin. See wiki page "Possible With A Plugin" for more info.
