### ISSUE TITLE
Installing as Composer package - How to run afterwards?

### ISSUE THREAD

**Issue by deb0rian** [YOURLS/YOURLS#1938]
Hey guys,

So I've installed YOURLS as a composer dependency, now it's located in /vendor/yourls/yourls/
I've copied config.php file from user folder into my project's root and configured as I please.
How do I now access /admin? I've tried setting symlink to /admin folder, but it's looking for the config in dirname(__FILE__), which is in /vendor/yourls/yourls/
Also I've tried creating /admin folder and placing config.php there... I think you have a bad file structure, config files shouldn't reside that deep in folders, the system is not installable via package managers.

**Comment by ozh** [comment]
I'll let @LeoColomb reply to this one :)

**Comment by LeoColomb** [comment]
> YOURLS as a composer dependency

Very interesting! There is no release available with Composer, except `dev-master` and `2.0-wip`.
Both versions are not Composer-ready at all yet...

> I think you have a bad file structure

Thanks for the review, feel free to make a contribution! :smile_cat: 
If you really want to use Composer, you need to move `yourls-go.php` at the root then fix file inclusions, and manage assets' folders for being accessible on the web (feel free to ask me if you want more details).

> the system is not installable via package managers.

You got it! :smiley: 
But this feature is planned for a next release!

**Comment by ozh** [comment]
Proper way (yes, I'm five years late, so? :) would be:
```bash
composer create-project yourls/yourls .
```
in an empty directory (or replace `.` with `path/to/install`)

**Comment by LeoColomb** [comment]
@ozh Nope, I'm afraid not, ha ha.
`composer create-project` targets framework-based new application projects, eg. you want to build a new application from the Laravel framework.
YOURLS is not a framework but a concrete application, usual usage is not "start a new project based on YOURLS".

Aaaand composer is not supposed to be used as an installer, there is no way to `composer download-and-prepare-ready-to-run yourls/yourls`.

**Comment by ozh** [comment]
@LeoColomb works fine for me :) (this downloads, this doesn't "prepare ready to run")
