### ISSUE TITLE
Logo displaying 

### ISSUE THREAD

**Issue by gicupl** [YOURLS/YOURLS#1939]
Hello,

My logo are displayed only in admin panel but should be visible at home page for everyone.
How to fix it?

http://purpl.pl

**Comment by ozh** [comment]
From the sample file you used:
```
/*
 * This is an example file for a public interface and a bookmarklet. It
 * is provided so you can build from it and customize to suit your needs.
 * It's not really part of the project. Don't submit feature requests 
 * about this file. It's _your_ job to make it what you need it to be :)
 *
```

If you want to insert an image, google for "HTML how to insert an image". If you want to reuse functions used in core YOURLS admin files, have a peek at how those files (eg `admin/tools.php`) are written.
