### ISSUE TITLE
Web Domain to masked DDNS - CSS fails to load

### ISSUE THREAD

**Issue by davidlimjh** [YOURLS/YOURLS#1940]
Im not very sure if this is an issue but when using domain that masks a dynamic DNS, the CSS on YOURLS fails to load.

Here is an example:
"dynamicdns.dns.com" points to the YOURLS install folder.

"www.mydomain.com" is forwarded to the dynamic dns address "dynamicdns.dns.com" with masking.

When accessing the YOURLS admin page using "www.mydomain.com", no CSS & Images load.

When accessing the YOURLS admin page using "dynamicdns.dns.com", everything works fine.

This seems like rather weird behaviour so i'm just putting this here.

[EDIT] Install failed because of MySQL keyword limit, so fixed and removed from post.

**Comment by ozh** [comment]
CSS (and JS and images) are loaded using the domain specified in the config. HTML doesn't understand domain forwarding (ie if you say `<img src="domain.com/blah.gif">` the image has to be on domain.com, your browser won't follow redirection to load the image.
