### ISSUE TITLE
[Bug] Unable to edit urls.

### ISSUE THREAD

**Issue by kamijoutouma** [YOURLS/YOURLS#1941]
When trying to edit a shortened url to change the original url I get redirected to admin-ajax.php which is a blank page pretty much.

I'm not sure if its because i'm on a different ip then the one i made the shortened url with or what.

The edit button goes to a dif url instead of staying on the same url and just changing stuff so you can edit like before. Appearantly delete is doing the same thing o.O

Did something happen? @ozh

**Comment by kamijoutouma** [comment]
I found the problem. There were some issues going on and the entire js folder was returning 404 not found.
Sorry for wasting your time.

**Comment by LeoColomb** [comment]
@kamijoutouma Thanks for your feedback! :confetti_ball:
