### ISSUE TITLE
is developement stopped?

### ISSUE THREAD

**Issue by vishals321** [YOURLS/YOURLS#1943]
This  version has not been updated from 1 year. Is this project dead? If not please include user registration system.

**Comment by LeoColomb** [comment]
> This version has not been updated from 1 year.

Which version?
1 year?!! Don't seem so: https://github.com/YOURLS/YOURLS/pulse

> If not please include user registration system.

What do you mean?

**Comment by vishals321** [comment]
Version 1.7  and user system means normal user register and create urls and he can short urls then.

**Comment by LeoColomb** [comment]
OK, something like this: #1255

**Comment by vishals321** [comment]
Yes exactly
