### ISSUE TITLE
Short Links are 1-digit incrementing numbers

### ISSUE THREAD

**Issue by christianreiss** [YOURLS/YOURLS#1944]
Hey folks,

running the latest git from yourls and everything is fine except that all the created links (except manually created ones) are "just"increments of the last auto-increment, ie 1,2,3,4... I don't want everyone to snoop around in all my links if i hand out a short url.

I noticed that in the config you can set base36. In my understanding a random string is produced uppon creating a new short url.

Am I mistaken or missing something?
Cheers,

-Chris.

**Comment by R0Bzombie** [comment]
You may want to take a look at https://github.com/YOURLS/random-keywords

**Comment by LeoColomb** [comment]
@R0Bzombie Thanks! :kissing: 
@christianreiss Everything is said!

**Comment by christianreiss** [comment]
Even risking re-opening this issue: But I cant let this close and stand without saying a proper thank you! Issue s of course solved and this was lightning fast support. Kudos!
