### ISSUE TITLE
API action to return detailed stats of a shorturl ?

### ISSUE THREAD

**Issue by rishirajpurohit** [YOURLS/YOURLS#1945]
Can we enhance the api to returns complete stats that we have in admin panel for a particular short url. 

for example : traffic sources and referring sites and everything else.

parameters can be shorturl and secret and Return can be in an array.

any help in this direction is greatly appreciated.

**Comment by rishirajpurohit** [comment]
Maybe I found it so never mind

testing https://github.com/YOURLS/YOURLS/blob/master/yourls-infos.php#L460

**Comment by rishirajpurohit** [comment]
nope can't do it. Can someone plz help

**Comment by ozh** [comment]
The API can be extended to anything you want using a plugin, see for instance https://github.com/YOURLS/API-action/. For fetching stats and stuff, see in yourls-infos.php and functions-infos.php

**Comment by AkashBhat15** [comment]
I wanted to add an additional component to the get url statistics api where even the timestamps at which the url was clicked is returned. Could someone please guide me on how to do so?
