### ISSUE TITLE
Explanation on override

### ISSUE THREAD

**Issue by tboulogne** [YOURLS/YOURLS#1948]
Hello,

First of all thanks for your great work, YOURLS' TEAM. True pleasure to work with it.
I'm just stuck on the method to override a function in functions-html.php.

I'd like to override "yourls_die" to customize it's content. Does any body could explain me please.
Could not find a suitable way into wiki.

Thanks

Thierry

**Comment by ozh** [comment]
Function `yourls_die()` [begins with](https://github.com/YOURLS/YOURLS/blob/master/includes/functions-html.php#L426) the action hook `'pre_yourls_die'`.

So you have to create a custom function and have it triggered when action `'pre_yourls_die'` happens, eg:

```php
function tboulogne_die() {
    do_something();
    die();
}
yourls_add_action( 'pre_yourls_die', 'tboulogne_die' );
```

More info about the plugin API in the wiki.

**Comment by tboulogne** [comment]
Thanks for your precious help.
It's works.

Thanks again.

**Comment by tboulogne** [comment]
hello @ozh,

Just realize you're from bzh.... Yours is a bzh's product :-)
Back on this thread with another question if you could help.

How could i get share_data array from a plugin please. Try several technics without success..

Thanks for all.

Regards,
