### ISSUE TITLE
Stats Page

### ISSUE THREAD

**Issue by Lucianss** [YOURLS/YOURLS#1949]
Where is the stats page located?

**Comment by LeoColomb** [comment]
`example.com/[your short id]+`: note the `+`.

**Comment by Lucianss** [comment]
The actual page, for editing...

**Comment by ozh** [comment]
Functions related to stats are located in functions-infos.php. And the page is generated by yourls-infos.php

Honestly I would assume someone looking for some specific code has the basic grep and search abilities :grin: :trollface:
