### ISSUE TITLE
PHP_VERSION_ID for comparison

### ISSUE THREAD

**Issue by LeoColomb** [YOURLS/YOURLS#1951]
For [comparison of PHP versions](https://github.com/YOURLS/YOURLS/blob/858576b2dc5f42c836677f0b49867d88a264645b/includes/functions-install.php#L42-L48), should be more accurate to use [PHP_VERSION_ID](https://secure.php.net/manual/reserved.constants.php#reserved.constants.core) (at least less errors).

``` php
function yourls_check_php_version() {
    return (defined('PHP_VERSION_ID') && PHP_VERSION_ID > 50300)
}
```

**Comment by ozh** [comment]
Postponing to when we want 5.3+
