### ISSUE TITLE
Multiple short URLs when using PHP API

### ISSUE THREAD

**Issue by LymeSimon** [YOURLS/YOURLS#1956]
My YOURLS installation is configured using the default "define( 'YOURLS_UNIQUE_URLS', true );" and when I try to create a new short URL from the admin interface for a long URL that already exists in the database I get the correct warning
http://www.long.url already exists in database

I have a PHP script which uses yourls-api.php in "simple" format with username and password, and every time that script gets called a new short URL is created, resulting in a LOT of duplicate short URLs

### Reproducible Bug Summary 

1. Install YOURLS as detailed below with default configuration
2. Create a user specifically for the API calls
3. Call the script (below) on a different PHP website

This is a bug because each call should find any existing short URL and return that, not create a new one unless the long URL does not exist in the database.

### Technical details

* YOURLS version: v 1.7.1
* PHP version: 5.5.9-1ubuntu4.11
* Ubuntu server 14.04

Script used to create short url:

```php
function moxp($url) {
        // EDIT THIS: your auth parameters
        $username = 'myusername';
        $password = 'mysecretpassword';

        $format  = 'simple';                       // output format: 'json', 'xml' or 'simple'

        // EDIT THIS: the URL of the API file
        $api_url = 'http://moxp.uk/yourls-api.php';

        // Init the CURL session
        $ch = curl_init();
        curl_setopt( $ch, CURLOPT_URL, $api_url );
        curl_setopt( $ch, CURLOPT_HEADER, 0 );            // No header in the result
        curl_setopt( $ch, CURLOPT_RETURNTRANSFER, true ); // Return, do not echo result
        curl_setopt( $ch, CURLOPT_POST, 1 );              // This is a POST request
        curl_setopt( $ch, CURLOPT_POSTFIELDS, array(      // Data to POST
                'url'      => $url,
                'format'   => $format,
                'action'   => 'shorturl',
                'username' => $username,
                'password' => $password
        ) );

        // Fetch and return content
        $data = curl_exec($ch);
        curl_close($ch);

        // Do something with the result. Here, we just return it.
        return $data;
}
```

**Comment by ozh** [comment]
If multiple short URL are created, the problem is in how you call your custom script, which probably makes several concurrent calls. There's also a plugin that might help you, to help with concurrent calls.
