### ISSUE TITLE
Admin Interface Search Improvement

### ISSUE THREAD

**Issue by ernani** [YOURLS/YOURLS#1957]
Admin interface doesn't provide a search tool to list for clicks within the actual day, although the data structure account clicks with `click_time DATETIME`

I am willing to know if there is any interest in implemeting such feature in admin interface.

This could also benefit others with daily click reports via e-mail.

**Comment by ozh** [comment]
You can do it atm with a search "Show links created" and then "between" yesterday and today

This said, I would be totally OK with the dropdown for "Show links created" to also have "today", "this week", "this month". If that's something that sparkles any interest with you, yes please pull request :)

**Comment by ernani** [comment]
I'd say it needs another option on that dropdown then complement  'Show
links created' to something like 'Show links clicked' and then it can be on
a specific day or range.

Makes sense?

**Comment by ozh** [comment]
Yep that would be nice to have both "Show links created" and "Show links clicked" with the same dropdown in both cases: before XX, after XX, between XX & XX, today, this week, this month

**Comment by ernani** [comment]
I will look into it and submit a patch! Thanks for evaluating my proposal!

Cheers,

Ernani
Em 04/09/2015 02:51, "྅༻ Ǭɀħ ༄༆ཉ" <notifications@github.com> escreveu:
