### ISSUE TITLE
Everyone can see your stats by adding + after your shortened link

### ISSUE THREAD

**Issue by debbiediscovers** [YOURLS/YOURLS#1959]
I recently discovered that with bit.ly, if the user has not set his bit.ly settings to private, anyone can see the stats on the bit.ly link (allowing for very interesting competitor analysis).  It appearls that yourls links have the same problem  

http://yourls.org/di+ shows you all the link stats for example. 

Is there a way we can make it private?

Thanks.
Debbie

**Comment by ozh** [comment]
Explained in the [readme](http://yourls.org/#Config).
