### ISSUE TITLE
Admin URL redirect to www

### ISSUE THREAD

**Issue by mayarichman** [YOURLS/YOURLS#1960]
When I installed YOURLS, I set the YOURLS_SITE value to http://www.example.me. Now I want to get rid of the www. I only want to access YOURLS from http://example.me, so I've changed the config, but now when I try to access the url it results in a redirect loop in the browser. The url with www results in the admin dashboard, but without the css.

What should I do? Do I need to add some kind of rewrite rule to .htaccess?

**Comment by dgw** [comment]
Your host must be configured to redirect `example.me` to `www.example.me`. Redirect the other way instead, and this problem should go away.
