### ISSUE TITLE
After upgrade PHP from 5.3 to 5.5, YOURLS 1.7 doesn't work

### ISSUE THREAD

**Issue by vslayer100** [YOURLS/YOURLS#1961]
After upgrade PHP from 5.3 to 5.5, YOURLS 1.7 doesn't work and gives me this message:

SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client

**Comment by ozh** [comment]
Dunno. Works for me. Try changing the [DB driver](https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps) or upgrading to current master.
