### ISSUE TITLE
shortlinks do not work

### ISSUE THREAD

**Issue by migueldvasquez** [YOURLS/YOURLS#1963]
I've installed YOURLS at cafund.org to find out the shortlinks do not redirect correctly.  Can you help with this problem?

example: http://cafund.org/ozh will redirect to http://cafund.org/

**Comment by dgw** [comment]
Needs more info:
* Server OS & version
* Web server in use (Apache, nginx, etc.) & version
** Relevant configuration for the server, e.g. `.htaccess` file contents for Apache or the `server` block for this domain for nginx
* PHP version

**Comment by ozh** [comment]
Your install is severely broken and I suspect you completely messed the .htaccess :
- any request that doesnt match a real file gets a 302 Found redirect to the root : cafund.org/ozh or cafund.org/omglolzjajklr
- you cannot create shortlinks, as the ajax request is also redirected to the root. I know this because you also left username2/password2 as credentials, which is probably a bad idea.

Closing because it's not a YOURLS defect but feel free to comment on, as @dgw asked.

**Comment by migueldvasquez** [comment]
Yes, my installation did not complete exactly as it was intended.  Perhaps that is what is causing the short-link redirecting problem. I am not certain.

My install had the same issue as described here: https://github.com/YOURLS/YOURLS/issues/1617

I did a fresh install in the root directory using the latest Yours version 1.7.

Server: mysql.cafund.org or 208.97.162.120
Server version: 5.1.56-log
Protocol version: 10
Apache
MySQL client version: mysqlnd 5.0.11-dev - 20120503 - $Id: 3c688b6bbc30d36af3ac34fdd4b7b5b787fe5555 $
PHP extension: mysql
PHP: 5.6 FastCGI

I even changed the username and password per your concern.

Again, I get the installation error: 

Error creating table 'yourls_url'.
Error creating table 'yourls_options'.
Error creating table 'yourls_log'.
Error creating YOURLS tables.
File .htaccess successfully created/updated.

Yet the tables where created and the installation was complete.

My .htcaccess files was created and contained this:

# BEGIN YOURLS
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^.*$ /yourls-loader.php [L]
</IfModule>
# END YOURLS

I added the following to prevent a breach in the config.php:
# BEGIN YOURLS
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^.*$ /yourls-loader.php [L]
</IfModule>
<files config.php> 
   order allow,deny 
   deny from all 
</files>
# END YOURLS

I also successfully added the redirect-index and fallback URL plugins to redirect root page requests or bad links to http:/cafoundationfund.org. 

The initial problem still persists.

All short-links including http://cafund.org/ozh will be re-directed via the redirect-index plugin and not to the correct path, http://ozh.org/.

Let me know if you can help with the initial technical request to fix the short-link redirecting.

**Comment by migueldvasquez** [comment]
Yes, my installation did not complete exactly as it was intended.  Perhaps that is the cause of short-link redirecting problem. I am not certain.

My install had the same issue as described here: https://github.com/YOURLS/YOURLS/issues/1617

I did a fresh install in the root directory using the latest Yourls version 1.7.

Server: mysql.cafund.org or 208.97.162.120
Server version: 5.1.56-log
Protocol version: 10
Apache
MySQL client version: mysqlnd 5.0.11-dev - 20120503 - $Id: 3c688b6bbc30d36af3ac34fdd4b7b5b787fe5555 $
PHP extension: mysql
PHP: 5.6 FastCGI

I even changed the username and password per your concern.

Again, I get the installation error: 

Error creating table 'yourls_url'.
Error creating table 'yourls_options'.
Error creating table 'yourls_log'.
Error creating YOURLS tables.
File .htaccess successfully created/updated.

Yet the tables were created and the installation was complete.

My .htcaccess files was created and contained this:

# BEGIN YOURLS
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^.*$ /yourls-loader.php [L]
</IfModule>
# END YOURLS

I added the following to prevent a breach in the config.php:
# BEGIN YOURLS
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^.*$ /yourls-loader.php [L]
</IfModule>
<files config.php> 
   order allow,deny 
   deny from all 
</files>
# END YOURLS

I also successfully added the redirect-index and fallback URL plugins to redirect root page requests or bad links to http:/cafoundationfund.org. 

The initial problem still persists.

All short-links including http://cafund.org/ozh will be re-directed via the redirect-index plugin and not to the correct path, http://ozh.org/.

Let me know if you can help with the initial technical request to fix the short-link redirecting.

Thanks
