### ISSUE TITLE
shortening tries to access the long URL

### ISSUE THREAD

**Issue by tessus** [YOURLS/YOURLS#1966]
Apache 2.2.29, PHP 5.6.10
Apache 2.4.16, PHP 5.6.14
Yourls 1.7.1 (git 858576b)

When I shorten a link via the admin interface or the firefox plugin, the httpd process tries to connect to the URL, which is to be shortened. 

Why would the PHP code try to connect to the long URL during the shortening process?
This is definitely not necessary (because the shortening even works, when blocking the outgoing connection) and a privacy issue.

Can you please comment on this strange behavior?

**Comment by dgw** [comment]
YOURLS fetches the page title of any URL shortened through it. The Static Titles plugin might be able to disable this, but it was last updated almost two years ago: https://github.com/softius/yourls-static-titles

**Comment by tessus** [comment]
@dgw thanks for the info.

But I really think that this is a serious privacy issue and there should be a config option to disable this.

**Comment by ozh** [comment]
Indeed, it's not necessary regarding the shortening process itself. It's necessary to get a title for each shortened link.

If you feel this is an unacceptable tradeoff (privacy vs having a title) then a simple plugin will do. Either YOURLS Static Titles as mentionned, or more blunt approach:


```php
<?php
/*
Plugin Name: No URL Title
Description: Don't fetch long URL titles
Version: 1.0
Author: Ozh
Author URI: http://ozh.org/
*/

yourls_add_filter( 'shunt_get_remote_title', 'ozh_nourltitle');

function ozh_nourltitle( $false, $url ) {
    return $url;
}
```

By the way this is typically the kind of situation where there won't be a config option. 99% of people don't need that, that's what the plugin API is for.

**Comment by tessus** [comment]
@ozh thank you. this works great.

**Comment by McFcologne** [comment]
For me this came also unexpected, since we log access to the shortened links and got these logs flooded with access from yourls
