### ISSUE TITLE
"404 not found" when going to shortened URL

### ISSUE THREAD

**Issue by policies** [YOURLS/YOURLS#1968]
I can access the login/dashboard fine, and I can type in the website to shorten and all, but when I goto the URL it gives me, it says "404 Not Found"

"http://domain.com/url/em8ed" is supposed to go to "http://google.com/"

Please help a.s.a.p! Thank you!

**Comment by policies** [comment]
Whats RTFM mean? Can I get some help?

Thanks!

**Comment by dgw** [comment]
RTFM = Read The Fine Manual (that's the polite version)

What Ozh means is that you seem not to have read the configuration instructions, or have not searched for previous occurrences of this issue (there are many just in this issue tracker).

**Comment by policies** [comment]
Where have I messed up at? I don't know sorry. 

Thanks in advance for any help! :)

**Comment by dgw** [comment]
I can only provide a general guess because you haven't given us *any* details about your setup.

My guess is that you haven't properly configured the rewrite rules in the web server.

**Comment by policies** [comment]
How do I do that?

**Comment by LeoColomb** [comment]
Please read [Contributing Guidelines](https://github.com/YOURLS/YOURLS/blob/master/CONTRIBUTING.md).
For configuration, take a look at [yourls.org](http://yourls.org).
