### ISSUE TITLE
Theming

### ISSUE THREAD

**Issue by MatthieuScarset** [YOURLS/YOURLS#1969]
Hi! 

First of, thanks for making YOURLS!

I'd like to create a theme for my YOURLS site.

Correct me if i'm wrong but there's no theming functionality yet?

Is it possible to have a look at the admin/themes.php file scheduled to be included in 2.0?

Any way I can contribute to this functionality?

I look forward to hearing from you,

Matt

**Comment by phatvphat** [comment]
Good Idea :)

**Comment by R0Bzombie** [comment]
You didn't search very far :)
https://github.com/YOURLS/YOURLS/tree/2.0-wip

**Comment by ozh** [comment]
See also the roadmap in the wiki

**Comment by MatthieuScarset** [comment]
Thank you for your answers.
I'll have a look at the wip ;)
