### ISSUE TITLE
Pls help!!!

### ISSUE THREAD

**Issue by mitulbharti** [YOURLS/YOURLS#1971]
error i am recieving
Error establishing mySQL database connection. Correct user/password? Correct hostname? Database server running? in /home/a2160942/public_html/YOURLS-1.5/YOURLS-1.5/includes/class-mysql.php on line 298

**Comment by dgw** [comment]
YOURLS 1.5 is [almost five years old](https://github.com/YOURLS/YOURLS/releases/tag/1.5). The current release is [1.7](https://github.com/YOURLS/YOURLS/releases/tag/1.7). Please try with the current version and if it still doesn't work, provide the information requested in the [Contributing Guidelines](https://github.com/YOURLS/YOURLS/blob/master/CONTRIBUTING.md).

**Comment by LeoColomb** [comment]
@dgw Thanks! All is said. :love_letter:
