### ISSUE TITLE
question: can I run multiple spam plugins in parallel

### ISSUE THREAD

**Issue by tessus** [YOURLS/YOURLS#1972]
Sorry for open a ticket for a question, but I couldn't find any info on it anywhere.

Is it possible to run several spam plugins at the same time. Namely I am looking into the following 3 plugins:
* [AntiSpam](https://github.com/YOURLS/antispam)
* [Blacklist Domains](https://github.com/apelly/YourlsBlacklistDomains)
* [DNSBL](https://github.com/Diftraku/yourls_dnsbl/)

The reason why I ask is because plugins are using hooks to accomplish their tasks and I'm wondering, if these hooks negatively affect each other.

**Comment by ozh** [comment]
Theory: the plugin API lets you run as many plugin as you want. Some plugins will "hook" onto the same filters or actions and therefore might not run with each other. Some plugins will do fine, even plugins of the same kind (say, spam plugins) because they may use totally different tactics, hooks and functions.

Your case: dunno.

**Comment by tessus** [comment]
Ouch, the answer does not really solve my problem though. Maybe a compat matrix would be a good idea.
Right now how does it work? People install plugins and wait until something breaks? What then?

**Comment by ozh** [comment]
A compat matrix would be a cumbersome nightmare to maintain, there are 100+ plugins and any plugin can work or break with any other.

You can inspect plugins source yourself, if you see `yourls_add_action('this_particular_hook')` in several plugins, chances are they might not work together as expected. Yes, "chances" and "might".

**Comment by tessus** [comment]
Thanks for your answer. I'll look into it.

**Comment by tessus** [comment]
@ozh One last question. What about `yourls_add_filter`? If I see `yourls_add_filter( 'shunt_add_new_link', ...)` in several plugins, might this be a problem to run in parallel as well, or does this only apply to `yourls_add_action`?

**Comment by ozh** [comment]
This potentially applies to both actions and filters
