### ISSUE TITLE
Unnecessary Encoding of percent sign

### ISSUE THREAD

**Issue by SirLouen** [YOURLS/YOURLS#1973]
If I'm already encoding the URL with % signs, I dont know why the system reecondes the % with %25 

I need to "preencode" because google play only admits preencoded referrer tag

For example:
https://play.google.com/store/apps/details?id=com.twitter&referrer=utm_source%3Dtwitter%26utm_medium%3Dsocialmedia%26utm_campaign%3Dtwittercampaign

The first part of the URL  
https://play.google.com/store/apps/details?id=com.twitter&referrer=
Has to be not encoded

But from that point:
utm_source%3Dtwitter%26utm_medium%3Dsocialmedia%26utm_campaign%3Dtwittercampaign
Has to be preencoded

The output of yourls:
https://play.google.com/store/apps/details?id=com.twitter&referrer=utm_source%253Dtwitter%2526utm_medium%253Dsocialmedia%2526utm_campaign%253Dtwittercampaign

It double encodes the % simbols with %25 unnecessarily.

**Comment by LeoColomb** [comment]
Ref: #1303

**Comment by SirLouen** [comment]
I'm trying https://github.com/adigitalife/yourls-fix-long-url to solve this
Lets see if I resolve it

**Comment by SirLouen** [comment]
Impossible. I've tried that plugin and it does not work neither. This functionality looks broken

**Comment by ozh** [comment]
Closing: 2691 and associated PR will supersede
