### ISSUE TITLE
intermittent error:db response

### ISSUE THREAD

**Issue by dprime** [YOURLS/YOURLS#1974]
When shortening via the API, I get intermittent failures with the response "error:db" and nothing else. I can't find any logs on the system that give any further hints. It works about 90% of time. The database is an AWS hosted RDS-MySql instance so high quality. Any ideas?

**Comment by LeoColomb** [comment]
Describe your system (versions), please ! :smile_cat:

**Comment by dprime** [comment]
version 1.7
running on linux (ubuntu) via apache2 and the normal php+mysql stack.
I had a go at modifying the function that does the insert into the database to try and view the error, but because of all the yourls_do_action and filtering/plugin stuff, it's very hard to know what actually ends up executing that query.

**Comment by dprime** [comment]
Ok, I did some more digging (enabled verbose errors in the db driver) and logged everything to a file and found this:
 [last_error] => 23000, 1062, Duplicate entry '9pa' for key 'PRIMARY'

So, what appears to be happening is that because I'm calling yourls quite quickly to shorten several URLs at once, the queries are not safe. We should probably have a serialisable transaction guarded pair of functions to check a shortened URL does not exist and then add it. As long as those pair of queries are executed inside one serialisable transaction, two parallel shorten operations will never mess each other up.

I'm not expert enough in PHP or the db layer used to know how to do this. Otherwise, I'd happily offer a patch to solve the problem.

**Comment by ozh** [comment]
@dprime also have a look at a plugin called Concurrency Fix, it may help

**Comment by dprime** [comment]
Thanks. I used the random-keywords and that seems to have solved the problem.

**Comment by LeoColomb** [comment]
Thanks for your feedback. Feel free to come back if it still happens.
