### ISSUE TITLE
Description for URLs

### ISSUE THREAD

**Issue by thedragon013** [YOURLS/YOURLS#1976]
Hello,

I am planning to use YOURLS for my blog and while testing I came up with a thought about being able to add a description for an URL. That would be very useful when using multiple shorturls to one reference and given it away to twitter, facebook, friends etc. With an description you would be able to mark where which shorturl went to or just make some notes to it.

Of course you could use custom shorturls or title for that but that would not be useful if the description has to be a bit longer than just a few letters. 

So my question is if it would be possible to implement.

Thanks!

Dragon013

**Comment by ozh** [comment]
Several issues about this. It'll be easily done with a plugin in the future.
