### ISSUE TITLE
403 Forbidden Error when accessing the Install file

### ISSUE THREAD

**Issue by bunkertor** [YOURLS/YOURLS#1977]
Hi,
I'm getting this error on my first installation of YOURLS:

Forbidden
You don't have permission to access /admin/install.php on this server.
Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.

This issue has already been discussed on #1723 but unfortunately the user hasn't documented the solution. He's probably referring to editing a .htaccess file but having examined the code, I came to a conclusion that the install script creates .htaccess files on the go.

admin directory permissions are set to 0755, files to 0644. For experiment's sake I changed them all to 0777 for a moment but that didn't make any difference.

The server setup is ok as far as I can tell. I've examined phpinfo() and tried to upload other php scripts and they're all working fine.

Any help would be much appreciated.
thanks.

**Comment by LeoColomb** [comment]
If it's forbidden, it's about your config. Nothing else...
Recheck your sever config, verify your YOURLS config, and be careful about folder hierarchy setup of your server (since ErrorDocument changes the error).

**Comment by dylanh724** [comment]
What did you do to fix this issue?
