### ISSUE TITLE
Moved installation from subfolder and now old links don't resolve

### ISSUE THREAD

**Issue by CJG1975** [YOURLS/YOURLS#1978]
Apologies but I've got 'Google Blindness' on this one.

I've moved my YOURLS installation from /var/www/mydomain.com/s to a different location on the sever /var/apps/mydomain

All new links are working fine but any old links are now just ending up at the root of the domain. I realise I've missed something blitheringly obvious but I've no idea what!

**Comment by LeoColomb** [comment]
Have you updated your config to match your folder changes?

**Comment by CJG1975** [comment]
Hi,

Yes – I’ve updated the config file to reflect these changes. All new links are working perfectly, for some reason the old ones aren’t.

Regards,

Chris
