### ISSUE TITLE
Should yourls_is_active_plugin() be looking at a different array?

### ISSUE THREAD

**Issue by philhagen** [YOURLS/YOURLS#1980]
Not sure if I'm reading this correctly, but it seems yourls_is_active_plugin() should be looking at the $ydb->active_plugins array.

At, https://github.com/YOURLS/YOURLS/blob/master/includes/functions-plugins.php#L363-L370, the function is using $ydb->plugins.  I've found that this array is not completely populated, for example, when the admin page is first loaded, however, $ydb->active_plugins seems to take its contents from the configuration file.

Root reason for asking is that I cannot find a way to conditionally run plugin code only at the time it is activated.  I need to do some database functionality testing to see if the plugin is usable.  It doesn't make sense to do this each time any admin page is loaded.  (Yes, it's just a single, trivial DB query, but it seems I should be able to tell if the plugin is activated yet within the plugin's own code.

**Comment by ozh** [comment]
There's no $ydb->active_plugins array

When YOURLS loads, it does the following : 
- loads plugins from the config info: https://github.com/YOURLS/YOURLS/blob/master/includes/functions-plugins.php#L412
- check if every recorded active plugin is still an active plugin and if so, add it to $ydb->plugins, and eventually resync the config info

So it's indeed $ydb->plugins that has the correct info during a YOURLS instance.

As for conditionally run code upon activation, we've covered that use case :) And you're perfectly right, a useless single DB query is to be avoided at all costs.

## How to run code once when a plugin is activated :

(emphasis to allow easier searching for people looking for the same info)

To run code at the moment a plugin is activated, use action `'activated_'. $plugin_name` that is called at the end of `yourls_activate_plugin()` ([here](https://github.com/YOURLS/YOURLS/blob/master/includes/functions-plugins.php#L491))

Real life example: plugin [Cache Stats pages](https://github.com/YOURLS/cache-stats-pages) creates a cache directory upon activation:
https://github.com/YOURLS/cache-stats-pages/blob/master/plugin.php#L48-L55

**Comment by philhagen** [comment]
Aha, OK, this makes sense and thanks for the example code - I hunted through a number of plugins for an example but didn't get to that one.
Is there a clean way to terminate the module installation from within the ``'activated_'.$plugin_name`` method and notify the user?  If you example, what would happen if the cache directory creation failed?  (In my use case, I would rather back out of installation and display an error message if the necessary MySQL function is not available.The output buffer was an ideal method, but that's closed out when ``'activated_'.$plugin_name`` is called.

**Comment by ozh** [comment]
In my example I simply didnt test the dir creation because well fuck it :) but your custom function can test anything, use its own output buffer, deactivate the plugin if something fails, anything, and pass a notice using [yourls_add_notice()](https://github.com/YOURLS/YOURLS/blob/master/includes/functions-html.php#L802)

**Comment by philhagen** [comment]
Oh yes, I definitely agree failing outright if unable to create the directory doesn't make sense.
ACKACK on yours_add_notice() and makes sense that it would uninstall itself at that point.  Will proceed down that line.
Again, thanks for your help navigating the code - it's very much appreciated.

**Comment by philhagen** [comment]
Much closer, but any reason ``yourls_deactivate_plugin(__FILE__)`` would return "``Plugin not active``" when called from within the ``'activated_'.$plugin_name`` hook?

Would ``yourls_add_notice()`` has no effect when called from within the ``activated_'.$plugin_name`` hook because it had already been called in the header before the plugin code is handled?

**Comment by XLixl4snSU** [comment]
I can't get this to work.

My code looks like this:

`yourls_add_action( 'activated_'.yourls_plugin_basename( __FILE__ ), 'telegram_notifier_install' );
function telegram_notifier_install() {
    yourls_redirect( yourls_admin_url( 'plugins.php?page=telegram_notifier' ) );	
	$message = "<div>OMG, dude, I mean!</div>";
	yourls_add_action( 'admin_notices', function() use ( $message ) { echo (string) $message; } );
	yourls_debug_log( 'Test' );
	mkdir( $dir.'/cache', 0600 );
}`

I added multiple functions for testing, none of them get's executed when activating the plugin. What am I doing wrong?

**Comment by ozh** [comment]
See this for example: https://github.com/YOURLS/cache-stats-pages/blob/master/plugin.php#L48-L55
