### ISSUE TITLE
Redirect doesn´t work -- 404 Not Found

### ISSUE THREAD

**Issue by merylen** [YOURLS/YOURLS#1984]
I recently discover a problem with my redirecting in yourls. When I try to access an short-URL i´m getting an 404.
I´m able to generate new Short-Urls but there is no redirection done. 
In my apache-access.log i see a normal GET for the short-Url. No messages in error.log.

My config:
---------
# cat config.php
<?php
/** MySQL database username */
define( 'YOURLS_DB_USER', 'username' );
/** MySQL database password */
define( 'YOURLS_DB_PASS', '********' );
/** The name of the database for YOURLS */
define( 'YOURLS_DB_NAME', 'yourls' );
/** MySQL hostname.
define( 'YOURLS_DB_HOST', 'localhost' );
/** MySQL tables prefix */
define( 'YOURLS_DB_PREFIX', 'yourls_' );

define( 'YOURLS_SITE', 'http://mysite.de' );
define( 'YOURLS_HOURS_OFFSET', +2 );
define( 'YOURLS_LANG', '' );
define( 'YOURLS_UNIQUE_URLS', false );
define( 'YOURLS_PRIVATE', true );

define( 'YOURLS_COOKIEKEY', 'i](~)sAd)LYsdfkjnkljasnfsepe248248uq1}2#-G47somethingverylong' );
$yourls_user_passwords = array(
	'userone' => 'phpass:!2a!08!.raDlasdkjfnasljfnsalkfjnsaiua' /* Password encrypted by YOURLS */ ,
	'usern2' => 'phpass:!2a!08!EqxhzNd7jTsIn6rybI7HAusvII1H9i8jRqq2ShtQfX.gfmteLCSZS' /* Password encrypted by YOURLS */ 	// You can have one or more 'login'=>'password' lines
	);

define( 'YOURLS_DEBUG', true );

define( 'YOURLS_URL_CONVERT', 36 );
$yourls_reserved_URL = array(
	'porn', 'faggot', 'sex', 'nigger', 'fuck', 'cunt', 'dick', 'gay',
);

---------

**Comment by fm** [comment]
Do you have the .htaccess setup in the root of the folder? https://github.com/YOURLS/YOURLS/wiki/.htaccess

**Comment by merylen** [comment]
Yes, my .htaccess in Document Root looks exactly like the one in the website.

**Comment by merylen** [comment]
Fixed it:
added to my apache-Configuration:
        <Directory /var/www/yourls>
          AllowOverride All
        </Directory>

Seems like the last apache-update disabled this and so .htaccess was not used. Thanks for the hint.
