### ISSUE TITLE
Auto encrypting passwords doesn't work if password contains forward slashes

### ISSUE THREAD

**Issue by berndblume** [YOURLS/YOURLS#1987]
If the password contains one or more forward slashes, auto encryption doesn't work and raises a `'preg_replace problem'`.

The culprit is the prog_quote call in line 173 of includes/functions-auth.php. Should be `preg_quote( $password, '/' )` instead of `preg_quote( $password, '-' )`

Thanks,

Bernie

**Comment by dgw** [comment]
If you've tested that fix and found no issues, feel free to submit a pull request. Or I can, later tonight, if you don't want to deal with git.

**Comment by berndblume** [comment]
I've tested with a password that contains slashes, and now that I've read your response I've tested with a password that contains a dash, just to be on the safe side. My fix does work under both circumstances, so I'll submit a pull request. Thanks, Bernie
