### ISSUE TITLE
Redirection to custom link for stat

### ISSUE THREAD

**Issue by preovaleo** [YOURLS/YOURLS#1990]
Hi,

Is it possible to redirect to a custom link when adding the "+" (to stat)
and if possible that it trigger the counting API?

**Comment by ozh** [comment]
Practically everything is possible thanks to the plugin API. Hook into `load_template_infos` ([here](https://github.com/YOURLS/YOURLS/blob/master/yourls-loader.php#L46)) and redirect to anything else.
