### ISSUE TITLE
Audit of activity

### ISSUE THREAD

**Issue by WindyWo** [YOURLS/YOURLS#1992]
Hi

Is there a way we can view an audit of edits / deletions on YOURLS?

Today, one of our short URLs disappeared, so can only assume it got deleted by mistake.  It would be helpful to be able to look in the 'Recycle bin' in situations like this.

Is this possible?

**Comment by ozh** [comment]
Not out of the box, this would be a neat plugin to make though. See wiki page [Possible With A Plugin]
