### ISSUE TITLE
Browser / cache issues resulting in links not working for a period of time

### ISSUE THREAD

**Issue by WindyWo** [YOURLS/YOURLS#1995]
We seem to have an ongoing problem with the links and admin area not being available, usually after some activity in admin area (e.g. adding new links) or sometimes after testing our own short links.

After a period of time (usually an hour+), the admin area and links work again.  However, the admin area and links always work when we test from another PC.  So its not a server down issue - it appears to be browser / cache related.  I'm concerned that users of the links will have similar user experiences,

Has anyone experienced similar &/or is there something we're missing or doing wrong?

Thank you.

**Comment by ozh** [comment]
Never heard about something similar. It must be indeed related to your caching policy, that superseeds YOURLS admin pages cache. Maybe a plugin with more aggressive non caching header directives would help? Although, to be honest, I don't know how to be more explicit about not caching than [we are](https://github.com/YOURLS/YOURLS/blob/master/includes/functions-html.php#L57-L62) at the moment...

**Comment by WindyWo** [comment]
Hi Ozh,

Thanks for your reply.  

Do you consider an htaccess that keeps no cache on the server enough or will the YOURLS bypass it? What plugin/modification to the server setting do you recommend?

**Comment by ozh** [comment]
Not sure which will have precedence between .htaccess directive and PHP header... Anyway YOURLS will not bypass a .htaccess that prevents cache, since YOURLS itself is supposed to prevent cache, see my comment above

No idea on the server setting you should modify though... sorry. Feel free to comment on when you fix the problem!

**Comment by WindyWo** [comment]
Update:  Thanks Ozh.  The issue was solved by changing the service provider that runs the DNS.
