### ISSUE TITLE
Manually getting/generating API key

### ISSUE THREAD

**Issue by gamerjota** [YOURLS/YOURLS#1996]
Hey there!
I haven't been able to find a solution for this issue: https://github.com/YOURLS/YOURLS/issues/1975
So as an alternative, is there any way to get manually the API key from an account?
Or any way to generate an API key?
Thanks!

**Comment by ozh** [comment]
Is `yourls_auth_signature()` what you're looking for ?

**Comment by gamerjota** [comment]
There we go, thank you!
