### ISSUE TITLE
"Shorten The URL" loads and loads and loads

### ISSUE THREAD

**Issue by derastronaut** [YOURLS/YOURLS#1999]
Hello,

I upgraded my installation from 1.7 to 1.7.1 and now I have the issue that on click on the button "Shorten The URL" the loading-gif appears but nothing happens.

For testing I installed a brand new Yourls-installation with a new database and I get the same issue.

I also checked the config.php hundred of times but I don't get it. Everything was fine before upgrading.

PHP 5.6.13 (CGI with write-permissions)
MySQL 5.5.46
Ubuntu-Server

Checked in Firefox 42.0 and Chromium Version 45.0.2454.101 (both on Ubuntu 14.04)

Greetings
Sebastian

**Comment by tvholic** [comment]
I'm having the same issue.

**Comment by AleksCee** [comment]
Here is the same issue but more details I hope...
The statistic when call the "+" shorten-URL is also not work for some short-links... on both I get this error in the Server-Log:
PHP Fatal error:  Call to undefined function yourls_filter_apply() in /var/www/YOURLS-PATH/includes/functions.php on line 1817
This is only called when the remote-title of the URL is determined.

**Comment by AleksCee** [comment]
See: https://github.com/YOURLS/YOURLS/issues/2000#issuecomment-162240053

**Comment by derastronaut** [comment]
Cool, thanks for the quick patch! Now it works! :)

**Comment by tvholic** [comment]
Yup, that fixed it for me.

**Comment by ozh** [comment]
Oops ! Not sure how this managed to escape the unit tests... Sorry for the annoyance folks, thanks for reporting. I've re-uploaded a 1.7.1 for those who still have the problem!
