### ISSUE TITLE
Call to undefined function yourls_filter_apply()

### ISSUE THREAD

**Issue by GeekTNTdotCom** [YOURLS/YOURLS#2000]
After I upgraded from 1.7.0 to 1.7.1 I keep getting this error when trying to add a new link:

<b>Fatal error</b>:  Call to undefined function yourls_filter_apply() in <b>/home/HIDDEN/public_html/includes/functions.php</b> on line <b>1817</b><br />

Anyone got a clue?

I have tried to re-upload all the files again but the error is still there...

**Comment by AleksCee** [comment]
Hi, I have the same issue see: https://github.com/YOURLS/YOURLS/issues/1999#issuecomment-162237938

**Comment by GeekTNTdotCom** [comment]
thanks AleksCee

I have just uploaded 1.7 and everything works fine again...

**Comment by AleksCee** [comment]
In the code the functions.php is the only file with the function, so I think the function declaration is missing.
https://github.com/YOURLS/YOURLS/search?q=yourls_filter_apply&type=Code&utf8=%E2%9C%93

**Comment by AleksCee** [comment]
here is a "patch"
```
1817c1817
<     $max_bytes = yourls_apply_filter( 'get_remote_title_max_byte', 2048 ); // limit data fetching to 2K in order to find a <title> tag
---
>     $max_bytes = yourls_filter_apply( 'get_remote_title_max_byte', 2048 ); // limit data fetching to 2K in order to find a <title> tag
```

**Comment by ozh** [comment]
Oops ! Not sure how this managed to escape the unit tests... Sorry for the annoyance folks, thanks for reporting. I've re-uploaded a 1.7.1 for those who still have the problem!

**Comment by LeoColomb** [comment]
Just want to celebrate both the 2000th issue and 2000th+ stargazer! :tada: :smiley:
