### ISSUE TITLE
Upgrade to 1.7.1 caused Server 500 Error

### ISSUE THREAD

**Issue by griffmiester** [YOURLS/YOURLS#2001]
I upgraded to 1.7.1, and immediately started getting 500 Errors for my yourls install.

I tried enabling debugging and editing my .htaccess, but it didn't help

I rolled back to 1.7 and it's working again now.

**Comment by LeoColomb** [comment]
What is your PHP version?

**Comment by griffmiester** [comment]
5.4

**Comment by ozh** [comment]
We'll need more details to hopefully fix if it's a YOURLS defect. What's in the server error log?

**Comment by Kriechi** [comment]
I get 500 errors as well - looks like https://github.com/YOURLS/YOURLS/wiki/Endless-Spinning-Icon
But I never changed the webserver config, I only updated YOURLS...

**Comment by ozh** [comment]
That issue has been fixed, I've re-released a 1.7.1 a couple hours after the initial release. Redownload and reinstall.
