### ISSUE TITLE
login admin pannel doesnt work

### ISSUE THREAD

**Issue by kvbappinio** [YOURLS/YOURLS#2002]
Hello,

google says thats a common issue - but i want to bring it to the table again.
First - thanks for this awesome free tool.
Second - i cant login, i set up the username / pw correct.
Installed it, make a good database, but i cant login.
"incorrect username or password"  - when i set the "backend" to public,
i can login and its working fine. But i need it to make private.

Do you have any suggestions ?
Greetz

**Comment by ozh** [comment]
There are numerous issues about this. Some close, some still ongoing, under varying setups. Search, see what applies to your case.
