### ISSUE TITLE
YOURLS Host on Google App Engine

### ISSUE THREAD

**Issue by lovebdsobuj** [YOURLS/YOURLS#2003]
I want to host **YOURLS** on Google App Engine, 
is there any tutorial or anyone help me to host YOURLS on Google App Engine (appspot)...?

**Comment by edwardmaya639** [comment]
Hey Yourls I am asking u that i can put google analytics code in which file or it works or not

**Comment by dgw** [comment]
@edwardmaya639 That's completely unrelated to this issue. Please [search](https://github.com/YOURLS/YOURLS/issues?utf8=%E2%9C%93&q=is%3Aissue+google+analytics) for related threads.
