### ISSUE TITLE
Upgrade to 1.7.1 from 1.7 caused 404 error on short links

### ISSUE THREAD

**Issue by KVaibhavClub** [YOURLS/YOURLS#2004]
After upgrading to 1.7.1 from 1.7, it looks and works all fine from ADMIN panel. but all shorted links are giving '404 not found' error. 

PHP VERSION - 5.5
MySQL VERSION - 5.5
UPGRADE METHOD - standard ZIP extract and overwrite 

* using some custom and tailor made plugins that was working fine on 1.7   
* Falling back to 1.7, works fine.

help plz.
thanks in advance.

**Comment by ozh** [comment]
Try 1.7.1 without your plugins. If it works, activate plugins one by one until something doesn't work and fix the plugin.

Server error log may have additional info. So far thousands of people have succesfully upgraded to 1.7.1 so I suspect this is a custom configuration issue.

**Comment by marvin8** [comment]
Hm.... looks like I got this issue as well. I am trying to upgrade from 1.7-alpha to 1.7.1 and short links now produce a 404. I have tried with out any plugins activated which didn't improve the situation... :-(

Anything I should look for to try and work out why the upgrade is not working?
