### ISSUE TITLE
Returning URL Rather than Page Title (title tag does exist on source)

### ISSUE THREAD

**Issue by xpersonas** [YOURLS/YOURLS#2005]
I'm having an issue where I can't get the page titles to return on certain pages. For instance...

http://www.realtree.com/bowhunting/videos

<title> tag clearly exists. But YOURLs is returning the url rather than a title. 

This started happening after upgrading to 1.7. If anyone could be of assistance it would be great.

**Comment by ozh** [comment]
Indeed. I under estimated the ugliness of other people's website source code :) 

Long story : to get a page title, YOURLS used to download the whole page, then parse it to find a `<title>`. When the page is very long (say, a zip archive) it's really ineffective. YOURLS 1.7.1 now downloads a chunk of the webpage instead. I thought 2K would be large enough for the chunk, but obviously it's not.

Short story: modify [this line](https://github.com/YOURLS/YOURLS/blob/1.7.1/includes/functions.php#L1817) and change `2048` to something bigger such as `15000` and you'll be good.

**Comment by dgw** [comment]
How do you even put more than 2K of HTML before the `<title>` tag? smh

**Comment by ozh** [comment]
@dwg ¯\\\_(ツ)_/¯
