### ISSUE TITLE
Upgraded domain with SSL certificate

### ISSUE THREAD

**Issue by captgnh** [YOURLS/YOURLS#2006]
I see that I can set https: in the config file, but how would I change my current short urls? Would I be able to edit the database and find and replace http with https?

**Comment by captgnh** [comment]
Sorry I'm not familiar enough with this. I have read all the SSL threads, but don't know what to do about short links I already have made. Is there another solution?

**Comment by ozh** [comment]
Redirecting http to https, or having both work, is configured at the server level, YOURLS doesn't care about it. Just enable it, nothing else to do regarding YOURLS.
