### ISSUE TITLE
Cannot read language file

### ISSUE THREAD

**Issue by tomslominski** [YOURLS/YOURLS#2009]
Hi. I got this notice after upgrading to YOURLS 1.7.1 today (although it might've existed before, upgrading was the last thing I did with YOURLS in ages):

`Notice: Cannot read file user/plugins/redirect-index/languages/redirindex-.mo. Make sure there is a language file installed. More info: http://yourls.org/translations in /Applications/MAMP/htdocs/yourls/includes/functions-l10n.php on line 458`

I was under the impression that if no language is specified (my config.php contains `define( 'YOURLS_LANG', '' );`), then YOURLS shouldn't need to look for any language files. In fact, it makes absolutely no sense to look for a redirindex-.mo file since the is no sane situation in which this file would exist.

I know it's just a notice, but I thought it's best reporting this just in case, since I think YOURLS shouldn't need to be checking for language files at all.

**Comment by ozh** [comment]
Thanks for the heads up, I'll look into this
