### ISSUE TITLE
after update from 1.7 to 1.7.1 not showing all letters in admin panel from keywords and not all links working

### ISSUE THREAD

**Issue by soooon** [YOURLS/YOURLS#2011]
Hi all

Just replaced all files for the update and added the db settings to the config file. 

First quesiton, is there not an update for the DB needed? in the ***_options table the version is still 1.5.1 (from before last update)

On http://url.domain.tld/admin I can see the old links but the first letter of all ShortUrls are missing.

some of the short urls are working, but not all -> strange.

Creating an URL e.g. http://www.google.ch with ShortURL 'AB12' is creationg only the Keyword '12' in the DB.

http://url.domain.tld/AB12 is obviously not working
http://url.domain.tld/12 is working, but was not intendetd to be created

Any ideas?

Many thanks

Chris

**Comment by ozh** [comment]
This hasn't changed between 1.7 and 1.7.1. If AB12 isn't working it's because you've picked lowercase default short URL charset. Please SEARCH before opening new issues.
