### ISSUE TITLE
Install Yourls with Big Commerce Site.

### ISSUE THREAD

**Issue by PrashantSigma** [YOURLS/YOURLS#2013]
Hello,
I am the beginner for this feature, just want to know what and how to integrate yourls with BigCommerce site.

The scenario is as below.

1) We have our BigCommerce site (www.bigcomxyz.com) up and running perfectly and it has (www.bigcomxyz.com/admin) for admin panel.
2) We have our shortened domain purchased/setup at domaindiscount24.com .
shortened url as:  "shrt.gs/"
3) Now where and how should we should install the yourls feature to be work with the above short url. We know we have to setup the database and install respective url on that, but how and where the redirection occur based on the database settings. 

Kindly revert back at the earliest. 

Regards,
Prashant

**Comment by ozh** [comment]
That's not a YOURLS question, that's a hosting question. Where should you install YOURLS so it works with your domain shrt.gs? Your hosting provider will tell you.

**Comment by PrashantSigma** [comment]
Hello ozh
Do we require intermediate domain compulsory?
i.e if i write the shrt.gs then it will redirect to that domain and there based on the admin settings into the database it will redirect to the main site?

I have uploaded the yourls code to our hosting server and apply the respective value in the config file. we have the shortened url setup there at the hosting environment. 

Now, based on the Yourls Installation steps, its written as visit shrt.gs/admin to access your admin panel. Hence, want to know about this?

Can you please elaborate more on the installation?. 

I have followed the steps written over here but don't know how to move forward.
http://yourls.org/#Install
http://yourls.org/#Config (set up the config file based on this.

**Comment by ozh** [comment]
Again: not a YOURLS question. You're asking how to install software on a server, can't help with that.

Install YOURLS somewhere so that you can point your browser to shrt.gs/admin or whatever your URL is. If you don't know how to do that, ask your server admin.
