### ISSUE TITLE
Request: Smart URL for Device Detection

### ISSUE THREAD

**Issue by kvbappinio** [YOURLS/YOURLS#2017]
Hello,

looking for a way to smartshorten the url 
which has a Device Detection.
For Examle bla.de/shorturl == redirects to Google Playstore (if android) or to appstore (if IOS).
Would be a killer feature.

Thanks

**Comment by dgw** [comment]
I'm going to guess this is possible with a plugin that detects the useragent. Probably relatively complex, on account of needing to store multiple URLs, but doable.

**Comment by LeoColomb** [comment]
You can try to use the [UA Parser](https://github.com/ua-parser/uap-php) lib in a plugin.
Then, may be add consecutively the different URLs (eg: `sho.rt/blah_ios` & `sho.rt/blah_android`) then use this database records.

Short version:
_get_ `sho.rt/blah` => UA Parser => _redirect_ (_expand_ `sho.rt/blah_[device selection]`).

But I'm sure there are prettiest way!
