### ISSUE TITLE
YOURLS installed correctly, but login doesn't work

### ISSUE THREAD

**Issue by kimbri-nic** [YOURLS/YOURLS#2019]
### Technical details

* YOURLS version: 1.7.1
* PHP version: http://yourls.atmarama-yoga.ch/phpinfo.php

Dear YOURLS team

I've already installed yourls on a different server before and it all worked well. Now, I've installed it and the installation was successful. However, I cannot login. I've checked and changed the login details in the config.php file several times, but it doesn't change anything.

The installation also looks differently then the last time
http://yourls.atmarama-yoga.ch/admin/

Any ideas?
Thank you.

**Comment by ozh** [comment]
Your config.php is broken. See source of http://yourls.atmarama-yoga.ch/admin/ : YOURLS tries to load stuff from http://www.atmarama-yoga.ch/0/
