### ISSUE TITLE
Adding an image and description to DB

### ISSUE THREAD

**Issue by checho221** [YOURLS/YOURLS#2020]
Hi there!

I already have a php code to fetch link in order to get an image and description furthermore the title, now the question is how to add the code or setup the plugin in order to save these data on db when the short link is created with the title.

Thanks in advance

**Comment by ozh** [comment]
Ozh not understand what mean you. Feel free to rephrase and explain.

**Comment by checho221** [comment]
Well, i just want to save: title, img and description of a short-link on db, i already have a working php code that fetches any link to get that info, but i dont know how to set it up like a plugin. 

Thanks

**Comment by checho221** [comment]
Well, i just want to save: title, img and description of a short-link on db, i already have a working php code that fetches any link to get that info, but i dont know how to set it up like a plugin that adds that info to DB. 
Thanks 
----- Mensaje original -----

De: "྅༻ Ǭɀħ ༄༆ཉ" <notifications@github.com> 
Para: "YOURLS/YOURLS" <YOURLS@noreply.github.com> 
CC: "checho221" <herbalista@une.net.co> 
Enviados: Martes, 19 de Enero 2016 13:43:16 
Asunto: Re: [YOURLS] Adding an image and description to DB (#2020) 


Closed #2020 .
