### ISSUE TITLE
Very basic: How to access and use YOURLS once it's installed

### ISSUE THREAD

**Issue by jthimself** [YOURLS/YOURLS#2021]
Here's my story: I'm getting into Twitter & wanted to create custom short URL's. I registered nit.ly [not really, just using that as a pseudonym]. Got it up and running on my webhoster. Using Softaculous on my cPanel I installed YOURLS. No directory name selected, of course, since we are going for short-as-possible URL outcomes

Wanted to try it out, of course. I entered www.nit.ly/YOURLS into my browser, hit enter and...I got the lovely YOURLS readme.html. I was expecting the dashboard.

FORTUNATELY, I had filled in my email address at the bottom of the install form, and that email told me the name of the SQL database, which was nit_your213 . JUST ON A HUNCH, I entered www.nit.ly/nit_your123 into my browser, hit enter, and...there it was! Hallelujah! And it works!

So, for those of us who are only slightly geeky, my polite request would be TELL PEOPLE HOW TO ACCESS THE APP ONCE IT'S INSTALLED.

Thank you for your attention to this matter.

UPDATE: Well, just for fun I tried www.nit.ly [reminder: not its real name] without anything else, and the YOURLS dashboard came up. So that's pretty easy! But...I set up a simple index.htm page on my site, just to see what would happen, and www.nit.ly STILL brings up the YOURLS dashboard! I thought index.htm was always the default. Hmmm.... Well, not an issue for me, I'm not going to use this site for anything except URL shortening, but this would be an issue for somebody who wanted a webpage AND the YOURLS app on the same site.

**Comment by ozh** [comment]
I don't know how Softaculous or whatever installs YOURLS. Everything you're asking for is in the readme.
