### ISSUE TITLE
traffic sources

### ISSUE THREAD

**Issue by bogdanx64** [YOURLS/YOURLS#2023]
hi there, is there any way to see the traffic sources for a specific period of time? thanks!

**Comment by ozh** [comment]
Yes: custom plugin with custom SQL query. See wiki page Possible With A Plugin.

**Comment by bogdanx64** [comment]
Hi, thanks for reply! I don't know how to build that custom plugin. Any suggestions? Thanks!

**Comment by ozh** [comment]
Answer is in the wiki page .........................................

**Comment by bogdanx64** [comment]
hey ozh,
I don't know what you mean.. anyway thank you for your time!
