### ISSUE TITLE
Give the option to always generate SSL long URLs

### ISSUE THREAD

**Issue by micha1848** [YOURLS/YOURLS#2024]
Hi,

is there a way, that YOURLS only use https at the Long URL?

for some special needs (some Podcast directorys can not handle SSL Urls) i need to give acces to my site with both, https and http.
But i want the shorten URLS ONLY route to httpS://.....

Because there no need for users to access the Page without https and the other thing, it prevent YOURLs to create 2 shorten URLS for the same destination.

and no, i dont want https://short.url/xxxxx (because only self signed certificate for that subdomain. :-) )

any Idea? THANKS

**Comment by ozh** [comment]
Make up your mind or be clearer please. You say:
- "only use https at the Long URL"
- "i want the shorten URLS ONLY route to httpS"
- "i dont want https://short.url/xxxxx"

Don't get what you want and what you don't want. The answer anyway will probably be a custom plugin.

**Comment by micha1848** [comment]
O its very simple what i want, but i am sure iam at the wrong Forum.

But i try to eplain it again.

i use Wordpress with booth http and httpS. And i use an Plugin to generate the shortlinks. (there the Support for my question, i know).
And now i want that the link http://shorturl.com/xyz1 only routes to httpS://longurl.end/xyz1
but it even creates another shorturl for http://longurl.end/xyz1

and NO, i can not switch to only httpS.

But like i say, its a Problem with the Wordpress Plugin.
