### ISSUE TITLE
Moving YOURLS to a new host

### ISSUE THREAD

**Issue by pixxies** [YOURLS/YOURLS#2026]
Hi,

I recently changed web host (Bluehost to Siteground) and was wondering how to move my YOURLS to my new host without losing any links?

Thanks in advance.

**Comment by jimlunsford** [comment]
pixxies,

There is this plugin available however I have not used it -
https://github.com/GautamGupta/YOURLS-Import-Export

Regards,

Jim Lunsford


CONTACT: For more contact information, a list of my websites and social
media accounts visit http://jiml.info

DISCLAIMER: All views and opinions expressed in this email message are the
personal opinions of the author. No liability can be held for any damages,
however caused, to any recipients of this message.

WARNING: Although taking reasonable precautions to ensure no viruses or
malicious softwares are present in this email, the sender cannot accept
responsibility for any loss or damage arising from the use of this email or
attachments.

IMPORTANT: The contents of this email and any attachments are confidential.
They are intended for the named recipient(s) only. If you have received
this email by mistake, please notify the sender immediately and do not
disclose the contents to anyone or make copies thereof.

**Comment by ozh** [comment]
Alternative is export all your MySQL data from your old webhost, using a tool such as phpMyAdmin or similar in your control panel, and import using same tool
