### ISSUE TITLE
Issues in a long run?

### ISSUE THREAD

**Issue by psalm23** [YOURLS/YOURLS#2027]
First of all thanks for such a nice software but I wonder. If I spend a lot of times and build thousands of links and some day this project is stopped what will happen to all of my links!

I am very much worried ...

**Comment by jimlunsford** [comment]
psalm23,

Any time you use any type of software you always risk the software being
dropped or unsupported and then your data be useless. This isn't just with
open source it happens with commercial software as well. The cool thing
about open source is that you have access to the source which means that if
this project would be dropped you could always take it and develop it
yourself or have someone else do it. I personally do the following things
when it comes to helping open source projects alive:

1. Stay active in the community
2. Donate to the project monetarily or when getting help offer to donate to
those helping you
3. Promote the project and tell others

If you do these things it will help to keep open source projects alive and
then you won't have to worry about what happens "if".


Regards,

Jim Lunsford


CONTACT: For more contact information, a list of my websites and social
media accounts visit http://jiml.info

DISCLAIMER: All views and opinions expressed in this email message are the
personal opinions of the author. No liability can be held for any damages,
however caused, to any recipients of this message.

WARNING: Although taking reasonable precautions to ensure no viruses or
malicious softwares are present in this email, the sender cannot accept
responsibility for any loss or damage arising from the use of this email or
attachments.

IMPORTANT: The contents of this email and any attachments are confidential.
They are intended for the named recipient(s) only. If you have received
this email by mistake, please notify the sender immediately and do not
disclose the contents to anyone or make copies thereof.

**Comment by ozh** [comment]
I'll have a simpler comment : as long as you pay for your web hosting, your YOURLS setup will be the same as of today, even in 10 years if you don't update YOURLS or if YOURLS has stopped being updated.
