### ISSUE TITLE
Different short URLS for the same link?

### ISSUE THREAD

**Issue by maxswede** [YOURLS/YOURLS#2028]
I can't manage to make more than one Shortened URL per LINK?
I would like to have 5-10 different URL's that goes to the same
LINK as to track where people come from...

**Comment by dgw** [comment]
Duplicate of #1901. Also see #1733. (Relevant search results before these were imported from Google Code and aren't worth pointing out.)

**Comment by ozh** [comment]
Simpler URL : RTFM http://yourls.org/#Config
