### ISSUE TITLE
Securing YOURL

### ISSUE THREAD

**Issue by maxswede** [YOURLS/YOURLS#2029]
HI, the way my setup is now, I have to login to access the Admin areas, 
but anyone seems to be able to generate a link on the "home page".
If I password protect the home page then the links does not work.

How can I solve this?

**Comment by dgw** [comment]
I'm going to guess that you used the sample public front page mentioned in [the relevant wiki page](https://github.com/YOURLS/YOURLS/wiki/Private-Or-Public). If so, the solution is to write your own homepage without the ability for users to create links.

**Comment by ozh** [comment]
Everything is explained in the manual http://yourls.org/

**Comment by maxswede** [comment]
Hi, 
I'm using lox.rocks as short URL
However if I create lox.rocks/aw1 for example, then it works fine.
But if someone types in www.lox.rocks/aw1 then it does not work.
I've pointed the A record of www towards the lox.rocks but still
does not work.

Any good tips?
