### ISSUE TITLE
YOURLS_HOURS_OFFSET now working?

### ISSUE THREAD

**Issue by malcomxar** [YOURLS/YOURLS#2031]
Hi guys, sorry to bother here but  have a problem with this "YOURLS_HOURS_OFFSET" config option.

Problem is, no mather to what I set it to, nothing changes (the time stored in the database is always the same.

I tried
define( 'YOURLS_HOURS_OFFSET', '-3' ); 
define( 'YOURLS_HOURS_OFFSET', -3 );
define( 'YOURLS_HOURS_OFFSET', 0 ); 

When I edit config.php, should I see the changes immediately?

Sorry for the dumb question, I just like to see the stats properly :)

Regards!

**Comment by vaughany** [comment]
I am reasonably sure that the time in the database is not supposed to change: the offset is applied when the time is taken from the database to be displayed.  The general practice I am aware of for web dev as a whole is that all database times should be stored in UTC (which never changes) and apply your timezone offset when displaying.

**Comment by malcomxar** [comment]
Hi, thanks for the reply! Then I have a follow up question. I thought the offset applied to the statistics page (graph indicating amount of clicks and the time of each) so I was checking there, but the offset only applies to the admin panel where it shows the time the link was created. Is there any way for it to apply to the statistics page? 

Just for the sake of messing around, if you create a link and have the offset you can have link clicks "before" the creation of the link (obviously a bug due to the date of creation having offset and the graph not)
![sin titulo](https://cloud.githubusercontent.com/assets/17078883/12847961/a008032e-cbf5-11e5-856b-bdad5e82bb56.jpg)
Can this be solved?
Regards!

**Comment by LeoColomb** [comment]
#1893 duplicate.
