### ISSUE TITLE
A Simple Question

### ISSUE THREAD

**Issue by TonyF57** [YOURLS/YOURLS#2033]
I have looked everywhere for an answer or even a mention of this but have been unable to find anything on the subject.

I have a self hosted install, working OK, I would like to add 5 custom shortened links all using the same originating URL, for example

URL to cloak   Custom Short URL    Short Link
domain.com    word1                        mydomain.com/word1
domain.com    word2                        mydomain.com/word2
domain.com    word3                        mydomain.com/word3
domain.com    word4                        already exists in database - Error message
domain.com    word5                        already exists in database - Error message

I am therefore wondering if there is limit of 3 for the same root URL or an error and more importantly if there is a work round or solution.

Ma thanks

Tony

**Comment by jmergy** [comment]
If the original (full) URL is exactly the same, I can't generate two short URLs. I don't know how you are able to get three. It all sounds spammy to me.

A workaround would be to add a parameter or fake anchor link to change the URL go have it be different but still essentially be the same.

**Comment by gmolop** [comment]
> _If the original (full) URL is exactly the same, I can't generate two short URLs._

Change **_YOURLS_UNIQUE_URLS_** constant in config file.

//_YOURLS/user/config.php_
```php
46 | /** Allow multiple short URLs for a same long URL
47 | ** Set to true to have only one pair of shortURL/longURL (default YOURLS behavior)
48 | ** Set to false to allow multiple short URLs pointing to the same long URL (bit.ly behavior) */
49 | define( 'YOURLS_UNIQUE_URLS', true );
```

**Comment by TonyF57** [comment]
Thanks for your comments jmergy, I can assure you there's nothing spammy about it. If I target 5 keywords with an article, a video, a pdf, a blog post and a press release for example it is only logical that I would want know where traffic is coming from. If I were restricted to 2 links only that of course wouldn't be possible.

Many thanks gmolop, didn't think to look in the config file, I'll go take a look.

Tony
