### ISSUE TITLE
Question regarding Forbidden: Too many URLs added too fast. Slow down please.

### ISSUE THREAD

**Issue by balonfx** [YOURLS/YOURLS#2035]
So if I attempt to use the API, if a user clicks 'get link', what happens is automatically generate multiple links, while the page is actually loading.

Any ideas around this?

**Comment by LeoColomb** [comment]
Not reproducible in the latest release. Please re-open this issue if it still occurs, with a set of reproducible steps. Check this element's CONTRIBUTING.md for an example.

**Comment by wgicio** [comment]
not an ideal solution however if anyone comes across this problem you edit yourls-api.php and put the php sleep function in eg sleep(1); to stop multiple links gettings generated
