### ISSUE TITLE
Yourls not working

### ISSUE THREAD

**Issue by jadesweeeney** [YOURLS/YOURLS#2036]
Hi guys,

Love the plugin, but for the last 6 months or so it seems to keep breaking monthly... lately it's been about fortnightly

It suddenly won't let the users log in for no particular reason

I then have to re-install the whole plugin and re-connect it to the SQL databases

Any ideas??

Jade

**Comment by LeoColomb** [comment]
Not reproducible in the latest release. Please re-open this issue if it still occurs, with a set of reproducible steps. Check CONTRIBUTING.md for an example.
