### ISSUE TITLE
Why are www.* visits not counted if YOURLS_SITE is set up with non-www domain

### ISSUE THREAD

**Issue by sebastian-schmid** [YOURLS/YOURLS#2037]
I know there is a recommendation in user/config.php to not use www.* addresses if YOURLS_SITE is set to a non-www URL.

But that way all short URLs will be redirected but not counted or am I missing something?

Would be great if all visits will count by YOURLS.

How can I catch also "wrong" links (e.g. the user enters the link manually) ?

**Comment by LeoColomb** [comment]
Not reproducible in the latest release. Or is this a question? Then it will be counted.
Please re-open this issue if it still occurs.
