### ISSUE TITLE
Trying to install Yourls for the first time. What am I doing wrong?

### ISSUE THREAD

**Issue by jziadeh** [YOURLS/YOURLS#2039]
My designer is trying to install Yourls for me. My short domain is shark.deals. However, it takes me to the index page. www.shark.deals/admin What is the next step from here? Thank you so much!

**Comment by ozh** [comment]
Everything is in the readme.

**Comment by jziadeh** [comment]
Thanks. I am missing something then. I don't know what it is. Can you guide me please? Thanks

**Comment by gmolop** [comment]
Hi @jziadeh 
Addition to a failed installation, you have a big security problem on your server settings.
_(Nothing to do with YOURLS configuration by the way.)_

Checklist:

- [x] Point "shark.deals" **NS** to your hosting (looks good)
- [ ] Add "shark.deals" as **DNS Zone** in your hosting
- [ ] Set up "shark.deals" zone to your "YOURLS" root folder (away from "freebieshark.com")
- [ ] Follow the [install steps](http://yourls.org/#Install) and read the [FAQ](http://yourls.org/#FAQ)
- [ ] Go to [http://shark.deals/admin/](http://shark.deals/admin/)
- [ ] Check your server settings... you **MUST** be **unable** to access and browse the content of the YOURLS folder [like this](http://www.freebieshark.com/shark.deals/) (see [deny directory listing](https://www.google.es/webhp?sourceid=chrome-instant&rlz=1C1ASUC_enES643ES643&ion=1&espv=2&ie=UTF-8#q=deny%20directory%20listing))

**Comment by jziadeh** [comment]
Thank you so much @gmolop I think that helped! Two questions: for some reason, it isn't working for me on Chrome.. is this because of a DNS issue? It's working fine for me in Firefox, but not Chrome.

Second, what if my readers go to shark.deals - how can I get that domain to redirect to my main domain name? Thank you VERY much for your help!

**Comment by gmolop** [comment]
1. Browser cache maybe? OS cache?... reboot and try again.
2. A few options... PHP redirection, .htaccess...

Something like _(easy option)_:
//shark.deals/**index.php**
```
<?php
header('Location: http://www.freebieshark.com/');
exit;
```

**Comment by jziadeh** [comment]
Thanks! Do you think I went through NameCheap and used the 'Redirect Domain' option, would that work in this case? https://www.namecheap.com/support/knowledgebase/article.aspx/384/77/what-is-url-forwarding-and-how-does-it-work
