### ISSUE TITLE
Allow more detail in Traffic Location stats? (E.g., city, network domain)

### ISSUE THREAD

**Issue by varlokkur** [YOURLS/YOURLS#2040]
Is it possible to allow more detailed information in the Traffic Location view?  I appreciate seeing what countries the traffic comes from, but it'd be much more useful for me to know more specifically where (in the US, especially) people are accessing my site.  I also appreciate the ability to see users' network domains in Google Analytics--is a similar level of detail possible with YOURLS?

Thanks for developing this tool!

**Comment by ozh** [comment]
This would be possible with a special plugin. See wiki page Possible With A Plugin

**Comment by danicasati** [comment]
Any suggestion to achieve this?

**Comment by varlokkur** [comment]
I haven't had any luck figuring it out myself--- I don't have that level of
skill.  I'd be happy to pitch in a few bucks to make it happen, though

**Comment by paulgailey** [comment]
I would also support such a plugin and contribute financially.
