### ISSUE TITLE
Installation redirecting localhost/admin to localhost/admin/localhost/admin/install.php

### ISSUE THREAD

**Issue by pratiksinghal48** [YOURLS/YOURLS#2042]
I am trying to install yourls on wamp server on my computer. After filling details in user/config.php, I tried to go to localhost/admin to install but it redirects to localhost/admin/localhost/admin/install.php and shows this error. 

> 'The requested URL /admin/localhost/admin/install.php was not found on this server.'

If i manually try to go to http://localhost/admin/install.php it show following error

> 'Warning: 42S02, 1146, Table 'yourls.yourls_options' doesn't exist SELECT `option_name`, `option_value` FROM `yourls_options` WHERE 1=1 in C:\wamp\www\includes\ezSQL\ez_sql_pdo.php on line 165'

what to do now.

**Comment by LeoColomb** [comment]
No configuration file? No system/conf version? Total ignorance of the issue template?
Please...
