### ISSUE TITLE
URL's containing # character when using API not shortened correctly

### ISSUE THREAD

**Issue by JoebeeKenobi** [YOURLS/YOURLS#2045]
### Technical details

* YOURLS version: 1.6
* PHP version: 5.4.40

### Reproducible Bug Summary 

1. Use API to shorten URL which contains a '#' in the URL 
2. The # and any characters following it in the URL are lost

This is a bug because...  If using the shortener directly, the '#' and any further characters after it are saved successfully. If using the API the '#' and following characters are lost.

**Comment by ozh** [comment]
How does this work (or not) using latest ?

**Comment by lpiob** [comment]
In 1.7 shortening urls with '#' works correctly.

**Comment by LeoColomb** [comment]
@lpiob Thanks for the feedback!
@JoebeeKenobi Please reopen this issue if it still occur with your updated version.
