### ISSUE TITLE
zeroclipboard to clipboardjs

### ISSUE THREAD

**Issue by Preovaleo** [YOURLS/YOURLS#2047]
HI,

I must say that i don't like flash and mozilla and google are agree with me.
So let me introduce to you [clipboard.js](https://github.com/zenorocha/clipboard.js).
It's a non-flash clipboard manager lib write in js.
It's easy to use and work on every browser.

Do you want me to add a PR?
Have a nice day !

**EDIT:** some change to say the same thing but better

**Comment by ozh** [comment]
@LeoColomb haven't we discussed this option in the past and turned it down for some reason?
If not, it seems indeed a good idea to me

**Comment by LeoColomb** [comment]
Oh, yes, see #1419! :smiley:

**Comment by ozh** [comment]
Despite lack of support for Safari I'm OK for a clean PR with this lib if @Preovaleo is up for it -- @LeoColomb OK ?

**Comment by LeoColomb** [comment]
Yes, of course, OK: anything that help avoiding Flash usage is a big improvement.
