### ISSUE TITLE
Fix http_build_url with empty but set user

### ISSUE THREAD

**Issue by LeoColomb** [YOURLS/YOURLS#2050]
Calling [`yourls_esc_url`](https://github.com/YOURLS/YOURLS/blob/master/includes/functions-formatting.php#L489) with 

``` php
$url = 'Http://@ExAmPlE.com#BLAH'
```

calls [`yourls_lowercase_scheme_domain`](https://github.com/YOURLS/YOURLS/blob/master/includes/functions-formatting.php#L570) which got

``` php
$partial_original_url          = trim( http_build_url( $parts ), '/' );
// $partial_original_url       = 'Http://ExAmPlE.com'
$partial_lower_original_url    = trim( http_build_url( $parts, $lower ), '/' );
// $partial_lower_original_url = 'http://example.com'
$url                           = str_replace( $partial_original_url , $partial_lower_original_url, $url );
// $url                        = 'Http://@ExAmPlE.com#BLAH'
```

then comming back to `yourls_esc_url` and

``` php
if ( !yourls_is_allowed_protocol( $url, $protocols ) ) // TRUE ! <= 'Http' is not a allowed protocol
    return '';
```

returns `$url = ''`.

---

Maybe make `yourls_is_allowed_protocol` case insensitive?

**Comment by LeoColomb** [comment]
Issue introduced by 15a1f56b226df12ccc4370dc673c38352e0838fa.

**Comment by ozh** [comment]
:sunny:

**Comment by ozh** [comment]
Works now
