### ISSUE TITLE
Database connection error on a wordpress installation integration

### ISSUE THREAD

**Issue by medicamin** [YOURLS/YOURLS#2052]
### Technical details

* YOURLS version: 1.7.1
* PHP version: 5.4.45
wordpress: 4.4.1
plugin: yourls-wordpress-to-twitter 

### Reproducible Bug Summary 

there is an installation of wordpress, bbpress and buddypress in which a plugin named yourls-wordpress-to-twitter is active to make auto short links of newly created topics and place this shortlink beside the name of each topic. every thing was good till we changed the host server. 

in the plugin settings page, I had set the installation type to "remote, on another web server", however the installation was on the same server. but as I had less knowledge those days, I could'nt find the correct path to the config.php file. by these settings everything worked great till we changed the server. I noticed there are some times that server cannot be reached by itself!!! so the plugin cannot produce shortlinks automatically. so I changed the installation type to local and placed the correct path to confg.php file. and the test was OK.
but when installation is set on local, I get the error "Incorrect DB config, or could not connect to DB" immediately by creating a topic. (meanwhile, the script itself works normal in standalone, and no database error accures.)

I'm not a developer, But I think there is some issues about $wpdb. 
I need this, please help me fix it.

**Comment by LeoColomb** [comment]
The plugin `yourls-wordpress-to-twitter` is no longer maintained, sorry for that, and another one is [recommended](http://yourls.org/#More#wordpress).

**Comment by medicamin** [comment]
I know, this plugin is too old and is no longer maintained, but I don't think this is a plugin related issue. 
look at class-mysql.php at the line 71

`function yourls_db_connect() {
	global $ydb;

	if (   !defined( 'YOURLS_DB_USER' )
		or !defined( 'YOURLS_DB_PASS' )
		or !defined( 'YOURLS_DB_NAME' )
		or !defined( 'YOURLS_DB_HOST' )
	) yourls_die ( yourls__( 'Incorrect DB config, or could not connect to DB' ), yourls__( 'Fatal error' ), 503 );	

	// Are we standalone or in the WordPress environment?
	if ( class_exists( 'wpdb', false ) ) {
		/* TODO: should we deprecate this? Follow WP dev in that area */
		$ydb =  new wpdb( YOURLS_DB_USER, YOURLS_DB_PASS, YOURLS_DB_NAME, YOURLS_DB_HOST );
	} else {
		yourls_set_DB_driver();
	}
	
	return $ydb;
}`

correct me if I'm wrong. but I thing the problem must be there.
