### ISSUE TITLE
YOURLS for local file system

### ISSUE THREAD

**Issue by adityardesai** [YOURLS/YOURLS#2057]
Hi

I am using YOURLS for one of the Big Data project and trying to index the filenames with specific prefix. I have my dataset on my local machine and generating the short URLs. YOURLS is generating the Short URLS but the problem is none of them is accessible. I believe that YOURLs wont work for local file system.

Here is the API Call

<?php

// EDIT THIS: your auth parameters
$username = 'admin';
$password = 'admin';

// EDIT THIS: the query parameters
URL to shrink
$url     = 'C:\wamp64\www\test.pdf'; // URL to shrink

request
$format  = 'json';                       // output format: 'json', 'xml' or 'simple'

// EDIT THIS: the URL of the API file
$api_url = 'http://localhost/YOURLS/yourls-api.php';

// Init the CURL session
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $api_url);
curl_setopt($ch, CURLOPT_HEADER, 0);            // No header in the result
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true); // Return, do not echo result
curl_setopt($ch, CURLOPT_POST, 1);              // This is a POST request
curl_setopt($ch, CURLOPT_POSTFIELDS, array(      // Data to POST
		'url'      => $url,
		'format'   => $format,
		'action'   => 'shorturl',
		'username' => $username,
		'password' => $password
	));

// Fetch and return content
$data = curl_exec($ch);
curl_close($ch);

// Do something with the result. Here, we just echo it.
echo $data;

?>
RETURN RESULTS

{"url":{"keyword":"polar.usc.edu\/5P","url":"http:\/\/C:%5Cwamp64%5Cwww%5Ctest.pdf","title":"http:\/\/C:%5Cwamp64%5Cwww%5Ctest.pdf","date":"2016-03-14 19:31:21","ip":"127.0.0.1"},"status":"success","message":"http:\/\/C:%5Cwamp64%5Cwww%5Ctest.pdf added to database","title":"http:\/\/C:%5Cwamp64%5Cwww%5Ctest.pdf","shorturl":"http:\/\/localhost\/YOURLS\/polar.usc.edu\/5P","statusCode":200}

But the Short URL when tried to access on browser, it returns 404. 

Thanks you!

### Technical details

* YOURLS version: v 1.7.2
* PHP version: 5.6.16

I am new to this and believe that YOURLS will not work for local file system. Can you please fix this, if you believe that I am making any mistake please point me out what wrong I am doing. 

I really appreciate your time and help to me. 

Thanks

**Comment by dgw** [comment]
This is not a YOURLS bug. You are trying to shorten "URL"s that aren't actually URLs.

Have a look at using [`file://` URLs](https://en.wikipedia.org/wiki/File_URI_scheme).
