### ISSUE TITLE
Query String Not Added To URL

### ISSUE THREAD

**Issue by greensleestak** [YOURLS/YOURLS#2062]
I'm trying to use the query string plugin https://github.com/drockney/append-qs to append ?site=blahblah to the end of my tracking link from CPV Lab which I have entered into URL shorten field. 

However, nothing is being recorded for site= when I look in my tracking stats.  

Is this plugin still working?  Why is this info not being appended to the end of the URL I put into the Yourls bar?

**Comment by LeoColomb** [comment]
Well, this is related to the plugin, we can't provide support for external plugins.
Please open an issue in the plugin's repository.
