### ISSUE TITLE
Issue titleURLs with id in the URL string do not shorten (spinning wheel)

### ISSUE THREAD

**Issue by simmonet** [YOURLS/YOURLS#2064]
### Reproducible Bug Summary 

1. URL to shorten = http://www.homes.com/property/530-s-university-blvd-denver-co-80209/id-500012502054/
2. Paste URL into "Enter the URL" form input
3. Entered Custom short URL field (no difference what's typed in here)
4. Clicked "Shorten The URL' button and get spinning wheel
5. Tried removing the last sub directory i.e. http://www.homes.com/property/530-s-university-blvd-denver-co-80209/ and URL shortened fine
6. Added in i to end of URL i.e. http://www.homes.com/property/530-s-university-blvd-denver-co-80209/i and URL shortened fine
7. Added in id end of URL i.e. http://www.homes.com/property/530-s-university-blvd-denver-co-80209/id and got spinning wheel

This is a bug because I would think that there wouldn't be any reserved words in the URL unless specified.. and all my property URLs have an id in them

Tried difference URLs of different properties with id in the same position with same results (i.e. doesn't work)

URLs without id as the first characters of the last folder in them work fine - even placing id in a different position in the URL works

No other issues creating other urls

Strange

Thank you

### Technical details

* YOURLS version: 1.7.1
* PHP version: 5.4

**Comment by LeoColomb** [comment]
Thanks a lot for filing this very strange issue! We'll triage and take a look at it as soon as possible!

**Comment by simmonet** [comment]
Great.. thanks


Grant Simmons
VP of Search Marketing
p.757-351-8322   c.310-795-8155
[image: Homes.com] <http://www.homes.com/>
[image: Like us on Facebook] <https://www.facebook.com/homesdotcom> [image:
Follow Homes.com on Twitter] <https://twitter.com/homesdotcom> [image:
Check out the Homes.com YouTube Channel]
<https://www.youtube.com/user/homesdotcom> [image: Connect with Homes.com
on Pinterest] <https://www.pinterest.com/homesdotcom/> [image: Circle
Homes.com on Google Plus] <https://plus.google.com/+homesdotcom>

**Comment by ozh** [comment]
I bet your server trips up when you try to access a URL with "id" in the query string. Quick check: http://sho.rt/admin/index.php?id=omg, does this work? (replacing sho.rt with your actual YOURLS URL of course)

**Comment by simmonet** [comment]
Nope.. that works...

It only seems to happen when it's (id) directly after a /

I tried using the string id elsewhere in the URL and it worked

http://www.homes.com/id-500 --- does not work
http://www.homes.com/i-500   --- works
http://www.homes.com/500-id --- works

Strange

Cheers


Grant Simmons
VP of Search Marketing
p.757-351-8322   c.310-795-8155
[image: Homes.com] <http://www.homes.com/>
[image: Like us on Facebook] <https://www.facebook.com/homesdotcom> [image:
Follow Homes.com on Twitter] <https://twitter.com/homesdotcom> [image:
Check out the Homes.com YouTube Channel]
<https://www.youtube.com/user/homesdotcom> [image: Connect with Homes.com
on Pinterest] <https://www.pinterest.com/homesdotcom/> [image: Circle
Homes.com on Google Plus] <https://plus.google.com/+homesdotcom>

**Comment by ozh** [comment]
That's a server side setting on your side, probably a `mod_security` setting, that prevents this behaviour. You should ask your server admin to fix this.

**Comment by simmonet** [comment]
Not sure how the server side portion works... how would I explain to them
what's happening?

It seems specific to YOURLS as opposed to the server string /id being an
issue.

Everything else seems to work fine...

Cheers


Grant Simmons
VP of Search Marketing
p.757-351-8322   c.310-795-8155
[image: Homes.com] <http://www.homes.com/>
[image: Like us on Facebook] <https://www.facebook.com/homesdotcom> [image:
Follow Homes.com on Twitter] <https://twitter.com/homesdotcom> [image:
Check out the Homes.com YouTube Channel]
<https://www.youtube.com/user/homesdotcom> [image: Connect with Homes.com
on Pinterest] <https://www.pinterest.com/homesdotcom/> [image: Circle
Homes.com on Google Plus] <https://plus.google.com/+homesdotcom>

**Comment by ozh** [comment]
When you want to shorten a URL, your browser tries to load a URL like http://sho.rt/yourls.php?url=http://homes.com/id and your server forbids it.

I suspect that a server setting, most likely a mod_security directive if your webserver is Apache, is preventing any client from accessing a URL on your server with a query string containing the word "id". 

What's your actual YOURLS URL ?

**Comment by simmonet** [comment]
go.homes

Cheers

Grant Simmons

**Comment by ozh** [comment]
Here's what you tell your server admin : the comment I made earlier, plus a couple examples as below:

http://go.homes/admin/index.php?omg=/hello works (ie you get a page and no error)
http://go.homes/admin/index.php?omg=/id doesn't work (connection is closed, there's probably an error in the error log, and you're redirected to index

Tell them that this is specific to your server setup and not software related. For instance, http://yourls.org/admin/index.php?omg=/id works.

So, the problem is that there's a server setting that thinks preventing clients to access URLs with a query string containing "/id" is a good idea

Might be a stupid or erroneous RewriteRule in the .htaccess or server config, or a mod_security rule, or God knows what. Can't help further, hope that helps :)

(to be extra sure check your .htaccess in go.homes web root looks like [this one](https://github.com/YOURLS/YOURLS/wiki/.htaccess))

(nice short URL btw, top level domain nicely matches your long URL!)

**Comment by simmonet** [comment]
Thank you...

And thank you :-)

We're the .homes registrar, so I grabbed that one first!

Cheers

Grant Simmons
