### ISSUE TITLE
Keep 5 versions of JQuery

### ISSUE THREAD

**Issue by Preovaleo** [YOURLS/YOURLS#2067]
Hello,

Is it relative to keep 5 versions of JQuery?

regards

**Comment by LeoColomb** [comment]
Not sure to understand your question. Could you explain, please?

**Comment by Preovaleo** [comment]
autocorrect :-1: relative => relevant

is this relevant to keep 5 version of jquery ? from 1.3 to 1.9

**Comment by LeoColomb** [comment]
Absolutely not, it's not relevant. Why do you ask? What is in your mind?

**Comment by Preovaleo** [comment]
So could we remove 4 of them ?

**Comment by LeoColomb** [comment]
Aaah right, got it! Well, need @ozh review.

**Comment by ozh** [comment]
Hmm, yeah, indeed. I've been probably a bit too conservative here :) Keeping latest jQuery only, renamed `jquery.js`, should be enough, especially now that jquery dev is much slower than it used to be a couple years ago
