### ISSUE TITLE
Only one front end in future release

### ISSUE THREAD

**Issue by Preovaleo** [YOURLS/YOURLS#2068]
Hi,

Do you think it could be better to use only one front end php file in the 2.0 release.
If yes, do you think it cold be a good idea to use a framework?

regards

**Comment by ozh** [comment]
Can you elaborate? What would be "only one front end php file" ?

**Comment by Preovaleo** [comment]
Hi,
I think it's better to have a public dir with js,css,img dir and only one index.php file.
We can do a router class to manage what script to call.

**Comment by ozh** [comment]
There won't be an index.php : a lot of people have a custom index.php to suit their needs (a public interface, a redirection, a list of recently shortened URLs, etc...)

In the future, yes, we'll probably streamline the root directory anyway

**Comment by LeoColomb** [comment]
Yes, this is the principe of a intern routing script, _à la_ NodeJS.
This the modern way to create local pages, with the use of template and sections, instead of the old hard scripted PHP files with direct access.

**Comment by LeoColomb** [comment]
There is no need to be the `index.php` absolutely. It depends of how the fallback directive is set in the server config.
