### ISSUE TITLE
no htaccess?

### ISSUE THREAD

**Issue by Preovaleo** [YOURLS/YOURLS#2071]
Hello,

Is there a reason why this project doesn't have an htaccess?

regards,

**Comment by Preovaleo** [comment]
I see that you crate it in install.php but why it is not in this repo

**Comment by Preovaleo** [comment]
because IIS

**Comment by dgw** [comment]
Technically it *is* in this repo because the actual `.htaccess` text is in `includes/functions-install.php` :stuck_out_tongue_winking_eye:

[Relevant](https://youtu.be/KJFvItrmoDY?t=1m37s) :wink:

**Comment by ozh** [comment]
Also because the .htaccess varies on the setup, for instance if YOURLS is in the root dir or in a subdir
