### ISSUE TITLE
Domain forwarding 

### ISSUE THREAD

**Issue by jleckenby** [YOURLS/YOURLS#2073]
The client I work with is planning to change the destination of the URL we use with our link shortener. The domain we use with YOURLS (http://enom.social) is already forwarding to Rightside's Twitter, and we want to direct that domain to now point at Enom's Twitter account. If we change the destination of that link, will that break the links we already have with YOURL or cause any other issues? Thanks for your help.

**Comment by ozh** [comment]
Not sure what you mean with "the domain is fowarding".

You can have the root of the domain pointing to something (eg http://sho.rt/ redirecting to whatever) and have all other urls (YOURLS stuff such as http://sho.rt/admin/ or short URLs such as http://sho.rt/jKiu12) pointing to something else.

If I didn't get your question, please clarify more.

**Comment by jleckenby** [comment]
Thanks so much for the reply, and apologies for being unclear.

We use http://enom.social as our core domain for YOURLS, and after
shortening a link with YOURLS we get something like:
http://enom.social/dotcloud. We are wanting to make sure that if we
redirect that core domain alone (http://enom.social) to a different page,
those shortened links created with YOURLS (i.e., http://enom.social/dotcloud)
will not be broken or effected in any way.



​​
*John Leckenby*
Content Strategist, N2Q Consulting
t: 360-303-9853 <360.303.9853>
e: jleckenby@notothequo.com | w: www.notothequo.com
<https://www.facebook.com/n2qconsulting/?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>

<http://twitter.com/notothequo?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>

<http://www.notothequo.com/blog/?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>

<https://www.instagram.com/n2qconsulting/?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
Social Media | Web Design | SEO | PPC

**Comment by ozh** [comment]
Sure, no problem.

**Comment by gmolop** [comment]
I think I know what you mean... And if I get you well, yes, you can move/switch domain with no problem...

 In fact, I have an installation with five domains pointing to the same (unique) installation... 
The only thing is to have well config the ns or the a record for that domain.

I made a plug in to handle different domains for the same instance of yourls, but what it really does, it helps to be in the right domain even if it's different.
If you think that can helps, let me know.

Oh another thing to take care of, in the config file, replace the static var with your domain name for a dynamic one so you can be sure it will work with both until you finish the migration.
