### ISSUE TITLE
How fix error CSS of YOURLS ???

### ISSUE THREAD

**Issue by ruaconx11** [YOURLS/YOURLS#2077]
I has install Yourls :( , ít error syntax + css !  How fix it ???
http://giasuketoantruong.net/ketoan/YOURLS/admin/
http://prntscr.com/amc0bd
http://i.imgur.com/l8cpr5T.png

**Comment by LeoColomb** [comment]
Your YOURLS instance is not well configured. Please see documentation: https://yourls.org/#Config.

**Comment by ruaconx11** [comment]
thanks you !
