### ISSUE TITLE
Missing or malformed URL

### ISSUE THREAD

**Issue by Jason-Khoo** [YOURLS/YOURLS#2078]
Hi guys,

Have you all encounter this error when try to shorten the link below:-
I need to shorten the link but it seems that Yourls is returning "Missing or malformed URL" and did not allow it to saved to db.

https://forms.na1.netsuite.com/app/site/crm/externalcustrecordpage.nl?compid=3777555&formid=26&h=AACvPvgQjMAHZPyKm2PwL4vRHkNcHmTEgBkBAdmeUCFjXhKTkn4mdozj9DpnJvCtEfdrDp7MvMVZxY3KAi3fZ8_B4MYXbz7pK-bY4yuOVFMlN8QqyOGKLJeGa5W8FEmyNtgLZr2ZMFZ3O5NSDfDV2nxreK0W7jaE77EYdG7C5I59bSpeaqDJOyfV5AdsVUKf7FIkoQHA3WPzqD4ZtVxuzfnpbHPJNSsblyt4BWWvW8YIS9KNxtYjEWcL1S6km8EseM3OkT-vf7gNBgfbEaUkYwuKaJBPGQmuM5nz093GsmwipOfMlahSouduKJSCzssT2-vfoHlsBMNoyM8eTkuDatUWCdEwGy0nC_hiusu6j0cn2cU1pqVLhlvO1WnZjPDWIpD3Q9ZjyB0BZAAPO8TQm4sPoif3K3vMAH5YGwgv0hE32K8a_IUyBDuiGyTr_KIKmQgHgtL0M9LvwXozaj6csih4RHn0_QNLLgXCH4mojcoH-zvYYNQCP7viGarYWZEdabEDFTz5HqEb_4yPgwGR6Y8nACl_IcU36KXfd1IDZ3g7H71uHdIvk12yB18yAYC6AZllQ1c358Mh0-1N_rzJVEx9BM0gAL2XgZGBwKDEhWKLkib_jdZNgPWC8c-oJ-6MTGHti1WhKc1pZIwkEDH5HNoBeZB-Kc1uqycxWN3EtysxW_mm6To%3D

Note = The form above is actual live form, pls don't spam or abuse, thanks and appreciate that.

**Comment by ozh** [comment]
Works fine with me: http://yourls.org/dq

**Comment by Jason-Khoo** [comment]
Hi ozh,

Thanks for the prompt reply, any idea the setup wrong somewhere? :(

**Comment by dgw** [comment]
Nobody's going to be able to even take a guess without any details about the server setup.
