### ISSUE TITLE
PHP 5.6 Workaround

### ISSUE THREAD

**Issue by rahul286** [YOURLS/YOURLS#2080]
I upgraded to PHP 5.6 and ran into error:

> ezSQL_mysql requires mySQL Lib to be compiled and or linked in to the PHP engine

`mysql_connect` function is deprecated in PHP 5.5

### Workaround

Add following line to `user/config.php` file:

`define ('YOURLS_DB_DRIVER','mysqli');`

**Comment by ozh** [comment]
:+1:

**Comment by 3L1AS** [comment]
Thanks rahul286, you saved my day (yourls) while upgrading to PHP 7.

**Comment by ozh** [comment]
Note that, unless user defined, YOURLS always tries to pick PDO first, then mysqli, whichever is installed

**Comment by saower** [comment]
My server is PHP7.0  and the same error . How to resolve the error ?
