### ISSUE TITLE
Notice: Uninitialized string offset:

### ISSUE THREAD

**Issue by bboilard** [YOURLS/YOURLS#2081]
Everything in the Admin seems to be fine... When I try shortened URL's I get nothing but this.
http://bwine.me/i/8bgo3

Notice: Uninitialized string offset: 0 in /var/www/html/i/includes/geo/geoip.inc on line 629
Notice: Uninitialized string offset: 1 in /var/www/html/i/includes/geo/geoip.inc on line 629
Notice: Uninitialized string offset: 2 in /var/www/html/i/includes/geo/geoip.inc on line 629
Notice: Uninitialized string offset: 3 in /var/www/html/i/includes/geo/geoip.inc on line 629
Notice: Uninitialized string offset: 4 in /var/www/html/i/includes/geo/geoip.inc on line 629
Notice: Uninitialized string offset: 5 in /var/www/html/i/includes/geo/geoip.inc on line 629
Notice: Uninitialized string offset: 0 in /var/www/html/i/includes/geo/geoip.inc on line 629
Notice: Uninitialized string offset: 1 in /var/www/html/i/includes/geo/geoip.inc on line 629
Notice: Uninitialized string offset: 2 in /var/www/html/i/includes/geo/geoip.inc on line 629
Notice: Uninitialized string offset: 3 in /var/www/html/i/includes/geo/geoip.inc on line 629
Notice: Uninitialized string offset: 4 in /var/www/html/i/includes/geo/geoip.inc on line 629
Notice: Uninitialized string offset: 5 in /var/www/html/i/includes/geo/geoip.inc on line 629
Notice: Uninitialized string offset: 0 in /var/www/html/i/includes/geo/geoip.inc on line 629
Notice: Uninitialized string offset: 1 in /var/www/html/i/includes/geo/geoip.inc on line 629
Notice: Uninitialized string offset: 2 in /var/www/html/i/includes/geo/geoip.inc on line 629
Notice: Uninitialized string offset: 3 in /var/www/html/i/includes/geo/geoip.inc on line 629
Notice: Uninitialized string offset: 4 in /var/www/html/i/includes/geo/geoip.inc on line 629
Notice: Uninitialized string offset: 5 in /var/www/html/i/includes/geo/geoip.inc on line 629
Notice: Uninitialized string offset: 0 in /var/www/html/i/includes/geo/geoip.inc on line 629
Notice: Uninitialized string offset: 1 in /var/www/html/i/includes/geo/geoip.inc on line 629
Notice: Uninitialized string offset: 2 in /var/www/html/i/includes/geo/geoip.inc on line 629
Notice: Uninitialized string offset: 3 in /var/www/html/i/includes/geo/geoip.inc on line 629
Notice: Uninitialized string offset: 4 in /var/www/html/i/includes/geo/geoip.inc on line 629
Notice: Uninitialized string offset: 5 in /var/www/html/i/includes/geo/geoip.inc on line 629
Fatal error: error traversing database - perhaps it is corrupt? in /var/www/html/i/includes/geo/geoip.inc on line 644

**Comment by dgw** [comment]
Maybe, as the error says, the geoip database file is corrupted?

**Comment by bboilard** [comment]
Well I thought of that also, downloaded the zip file twice... and uploaded it.. same result.
I did noting if I turn off the stats it works.... but with the stats on I get the above error... But I need logging.

**Comment by dgw** [comment]
Strange. The GeoIP dat files haven't been changed in 2 years, so they should be fine. If you're uploading via FTP it could be a transfer mode or encoding issue, but other than that I'd have to keep speculating.

**Comment by zefareu** [comment]
This is happening to me as well. @bboilard -- how do you turn off the stats? I don't need them, and if that works, it might solve this for me.
