### ISSUE TITLE
Feature req. - Additional protocols

### ISSUE THREAD

**Issue by JayHoltslander** [YOURLS/YOURLS#2082]
Would like to see support for some network paths (Sharing intranet links)

afp://computer.local/drive-name/folder/file.psd
\Volumes\drive-name\folder\file.psd
drive-name:folder:file.psd
file:///Volumes/drive-name/folder/file.psd

**Comment by LeoColomb** [comment]
Your request is documented in the documentation. 
Please see https://github.com/YOURLS/YOURLS/wiki/Public-Shortening#protocols.

**Comment by JayHoltslander** [comment]
Thank you. I hadn't seen that. However upon adding the
``$yourls_allowedprotocols = array( 'afp://', 'facetime://' );``
to config.php
The admin no longer show's the generated shortlink. Thoughts?
![](http://i.imgur.com/bmXoKCf.jpg)

**Comment by JayHoltslander** [comment]
Disregard. I discovered it was the lack of including http and https in the array

**Comment by JayHoltslander** [comment]
@LeoColomb I've found that after adding ``file:///`` as an accepted protocol for YOURLS that shortening the URL via bookmarklet still results in "**Missing or malformed URL**" and a resulting path in the URL bar of:

``http://mysite.com/admin/index.php?up=file%3A&us=%2F%2F&ur=%2FVolumes%2FDrive%2Ffolder%2Ffilename.psd``

from the long URL of 

``file:///Volumes/Drive/folder/filename.psd``

Any suggestions?

**Comment by dgw** [comment]
The protocol prefix is `file://`. The third `/` results from [omitting the hostname](https://en.wikipedia.org/wiki/File_URI_scheme#Format).
