### ISSUE TITLE
Create Cherokee Documentation

### ISSUE THREAD

**Issue by lylebrown** [YOURLS/YOURLS#2083]
Cherokee documentation link no longer goes to a valid URL. [Information (pulled from wayback machine)](https://web.archive.org/web/20110210161520/http://www.ututech.com/2010/10/configuring-yourls-to-work-with-cherokee-web-server/) seems to be partially inaccurate. A document on server config included in the wiki itself would be very useful.

I can put together at least a rough draft of this in the near future.

**Comment by ozh** [comment]
Yes please. I for one don't use and don't plan to use Cherokee, so this will have to come from the community :)
Leaving the issue open for anyone willing to contribute

**Comment by lylebrown** [comment]
Done! Github doesn't allow pull requests for Wiki pages (which is a shame), so you'll have to just grab it from [my fork's wiki](https://github.com/lylebrown/YOURLS/wiki) and edit the .md files yourself.

[Home](https://raw.githubusercontent.com/wiki/lylebrown/YOURLS/Home.md): Added reference to Cherokee-config in "Basis" section.
[Cherokee-configuration](https://raw.githubusercontent.com/wiki/lylebrown/YOURLS/Cherokee-configuration.md): Added page.

**Comment by ozh** [comment]
@lylebrown Looks neat. A nice alternative would be you hosting this doc in a repo of yours (eg lylebrown/YOURLS-Cherokee as a simple readme.md for instance). As a Cherokee user, you could then easily address users' issues or feedback. As a rule of thumb, I'd rather not add to YOURLS bits that we're not able to maintain ourselves :)

**Comment by lylebrown** [comment]
@ozh Alright, [lylebrown\YOURLS-Cherokee](https://github.com/lylebrown/YOURLS-Cherokee) exists, and I'm happy to maintain it. Putting a link in the YOURLS wiki's Home.md, similar to how it was suggested in my previous comment, should be enough to close this issue.

**Comment by ozh** [comment]
:pizza: !
