### ISSUE TITLE
General inquiry regarding YOURLS

### ISSUE THREAD

**Issue by ItsAdventureTime** [YOURLS/YOURLS#2084]
Hello,

I would like to inquire if YOURS is compatible running nginx with HHVM or PHP 7?

Thanks.

**Comment by LeoColomb** [comment]
Well, it may : [![Build Status](https://travis-ci.org/YOURLS/YOURLS.svg?branch=master)](https://travis-ci.org/YOURLS/YOURLS)

:smile:
