### ISSUE TITLE
Unable to install 1.7.1 (hhvm, nginx), throws an exception

### ISSUE THREAD

**Issue by lhorace** [YOURLS/YOURLS#2085]
### Technical details
- YOURLS version: 1.7.1
- PHP version: HHVM 3.12.1 (PHP 5.6.99-hhvm)
- Any other useful information depending on context (server version, mysql version, browser version, OS version...)
  Nginx 1.6.3, MySQL 5.5.44-MariaDB
### Reproducible Bug Summary
1. Extract yourls 1.7.1 into the root of your webserver
2. Create a user and a database
3. Modify user/config.php
4. Navigate to http://yoururl.com/admin
## Expected Results:

Redirected to install.php
## Actual Result:

Empty output

While digging into this issue, an uncaught expection is thrown, which makes it impossible to install the software.

```
`Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42S02] [1146] Table 'yourls_db.yourls_options' doesn't exist' in /var/www/vhosts/rd.lhprojects.net/htdocs/includes/ezSQL/ez_sql_pdo.php:249

Stack trace:
#0 /var/www/vhosts/rd.lhprojects.net/htdocs/includes/ezSQL/ez_sql_pdo.php(249): PDO->query()
#1 /var/www/vhosts/rd.lhprojects.net/htdocs/includes/ezSQL/ez_sql_pdo_yourls.php(54): ezSQL_pdo->query()
#2 /var/www/vhosts/rd.lhprojects.net/htdocs/includes/ezSQL/ez_sql_core.php(228): ezSQL_pdo_YOURLS->query()
#3 /var/www/vhosts/rd.lhprojects.net/htdocs/includes/functions.php(1018): ezSQLcore->get_results()
#4 /var/www/vhosts/rd.lhprojects.net/htdocs/includes/load-yourls.php(160): yourls_get_all_options()
#5 /var/www/vhosts/rd.lhprojects.net/htdocs/admin/install.php(4): include()
#6 {main}`
```

This bug must have been recently introduced because I've never came across this particular problem before.

A possible temporary workaround is problably to comment out #4 /var/www/vhosts/rd.lhprojects.net/htdocs/includes/load-yourls.php(160): yourls_get_all_options()

Regards,
Horace

**Comment by skinnrg** [comment]
I am having the exact same issue.

**Comment by emanb29** [comment]
+1, same issue

**Comment by ozh** [comment]
The DB layer has changed since, so I guess this issue is obsolete? Closing.
