### ISSUE TITLE
Clicks Counter Decreases

### ISSUE THREAD

**Issue by saud978** [YOURLS/YOURLS#2087]
### Technical details

* YOURLS version: 1.7.1
* PHP version: 5.5

After installing the new version (upgrading from version 1.5 to 1.7.1) I had 500,000,000 clicks in the database.
Then I notice that the counter start to decrease in millions digit (increasing form 500,000,000 to 500,999,999 then decrease to 499,000,000 instead of 501,000,000 etc.
Now my clicks counter at 491,007,947

This is a bug because... No idea

**Comment by dgw** [comment]
…did you fix it? Was it not actually a bug?

**Comment by saud978** [comment]
I'm not sure, I think it's because a plug-in I installed "AntiSpam" &
"Phishtank" maybe they deleted some url's from the database.

I disabled them to check, then I'll report if it doesn't  works
