### ISSUE TITLE
Infinite spinning circles - Can't modify, add or delete any URL's

### ISSUE THREAD

**Issue by dylanh724** [YOURLS/YOURLS#2089]
Technical details

YOURLS version: 1.7.1
PHP version: 5.6
Any other useful information depending on context (server version, mysql version, browser version, OS version...) Chrome stable, running on namecheap's cpanel
Reproducible Bug Summary

Load YOURLS into it's own directory
/YOURLS/user/config-example.php >> Edit and save as config.php
Went to /yourls/admin/
Logged in >> Seems to work!
I can't edit, modify, add, or delete anything. When I click delete, "Are you sure?" Yes. Nothing. I click on edit -- infinite spinning circle. I click edit -- infinite spinning circle.
Tried refreshing.

**What seems to be the problem?**

**Comment by ozh** [comment]
Read the wiki.

Tip for beginners: installing YOURLS for the first time and opening several issues in a row is an obvious sign that you didn't read the docs.

**Comment by dylanh724** [comment]
You mean ONE issue, and resolving it myself? What an ass..
