### ISSUE TITLE
Cannot add or delete urls - js/insert.js doesn't seem to be updated for modern browsers

### ISSUE THREAD

**Issue by dylanh724** [YOURLS/YOURLS#2090]
In reference to:
https://github.com/YOURLS/YOURLS/issues/2089 (version info here)
https://github.com/YOURLS/YOURLS/issues/392

and direct relevance to http://www.davewooding.com/yourls-not-working/

and after reading the wiki, the FAQ, and the installation guide and an unnecessary close the reason of a mod having a bad day or in-denial,

**You cannot add or delete urls that start with http. **This includes deleting, modifying, or adding or you will get an Ajax **Access-Control-Allow-Origin err**.

Could it be the insert.js needs updating for modern browsers?

If I follow the instructions above http://www.davewooding.com/yourls-not-working/ and modify insert.js - I actually CAN delete a url without an ajax error, proving that it is, indeed, something to do with this file, although I can't add because the code stops due to having "illegal characters" (hidden line break chars? Issue with replace("http://", "") thinking // is a comment or something, even if it's within a string? I'm not sure, but I do know that this file needs work.

Any suggestion what to do without an instant close of topic? I'm still looking into this BUG as I speak and will reply if I find a solution before someone else.

**EDIT 1:**
I checked out my config.php and noticed something:
Although I have `define( 'YOURLS_SITE', 'http://my.site' );` , my.site/admin will redirect to www.my.site/admin

Could CORS be failing because www vs no www?

**Comment by dylanh724** [comment]
Resolved - The .htaccess generated does NOT predict that a parent directory's .htaccess could possibly redirect to www, and does not counter-measure this (which 90% of sites in 2016 seem to do), therefore failing CORS due to www vs non www.

**Comment by LeoColomb** [comment]
@dylanh724 Thanks for your feedback.

That said, please respect people and try to make more constrictive reports to avoid "Oh big problem! Nevermind, I've read the docs and it's now fixed.".  
Also, if you think documentation or even the YOURLS itself isn't as good as it should be, your contribution is welcome.

**Comment by dylanh724** [comment]
"That said, please respect people and try to make more constrictive reports to avoid "Oh big problem! Nevermind, I've read the docs and it's now fixed.".

How was this relevant to this post? I fixed this by research, trial and error.
