### ISSUE TITLE
Error : The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there was an error in a CGI script.

### ISSUE THREAD

**Issue by Kanchan-1024** [YOURLS/YOURLS#2091]
I Install and create DB for Yourls on localhost using Xampp v3.2 but when i want to run it it shows error :

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there was an error in a CGI script.

**Comment by LeoColomb** [comment]
> The server encountered an internal error

See server configuration.  
Without more YOURLS information, providing advice is impossible.
