### ISSUE TITLE
Random URLs?

### ISSUE THREAD

**Issue by mhenders** [YOURLS/YOURLS#2092]
Hello,

I've just installed YOURLS, and the URLs created are sequential, i.e. it'd be possible for someone to discover all my shortened URLs by starting with /1. 

Is there a confirmation option for setting the minimum length of a URL stub, and randomizing the URLs? e.g. so that the first URL might be something like /a7s45a ?

Thanks so much!

**Comment by LeoColomb** [comment]
Dup. #1946
