### ISSUE TITLE
Filter API call returned URLs based on site username

### ISSUE THREAD

**Issue by U54** [YOURLS/YOURLS#2093]
I have a similar question as [#833](https://github.com/YOURLS/YOURLS/issues/833) but unfortunately when I click the Google code link it just gives me a redirect page (so I cannot see what comments/answers were left on that).

On my site I will have a feature where users can create short links, there is a tab called "My Links" and I am needing to show their shortened urls and how many clicks each one has received, so this is all done through the API. My only issue is that it seems there is no way for me to filter the URLs that the specific user on my site has made. 

My idea to achieve this is: When a user is creating a short url (`action = "shorturl"`) I would like to pass their user ID from my site in the API call and store that in yourls_url.

Right now for `action = "stats"` there are these filters: `"top", "bottom", "rand", "last""`. I am hoping to have a new filter here called something like `"userid"`. This way when a user visits their "My Links" page I could have an API call pull all of the URLs which were created by their user ID and have them appear with the data of how many clicks each one has received.

I hope this makes sense, it seems like this would be a fairly common thing, so maybe I'm just missing something? Is there already a way to do this that I'm just not seeing, or would I need to create a plugin to achieve something like this? I'm not very familiar with PHP (my other site does not use PHP) so any information would be extremely appreciated!

**Comment by ozh** [comment]
You can easily create custom API actions, there's a plugin example for this in the plugin list

Also, check plugin "Multi User", there are probably thing you'll want to copy

**Comment by U54** [comment]
I have created the custom API actions so now when a user creates a short URL it will attach their site user ID to the yourls_url table as shown below:

<img width="1191" alt="table" src="https://cloud.githubusercontent.com/assets/16723563/15490356/05453740-211c-11e6-97d6-73ee3b295ce3.png">

I am having issues creating the filter to return all of the URLs created by the user when they visit their "My Links" page. This is currently what I have to handle the return:

```
yourls_add_filter( 'api_result_stats', 'separate_users_api_stats' );

function separate_users_api_stats() {
	global $ydb;

	$user = ( isset( $_REQUEST['user'] ) ? $_REQUEST['user'] : '' );

    $table = YOURLS_DB_TABLE_URL;
    $result = $ydb->query("SELECT * FROM `$table` WHERE  `user` = '" . $user . "'");

    return $result > 0;

}
```

To test this I can try  `http://sho.rt./yourls-api.php?action=stats&user=test123&limit=10&filter=last&signature=xxxxxxxxxx` but unfortunately all I receive is:

<img width="758" alt="return" src="https://cloud.githubusercontent.com/assets/16723563/15490501/77dba55e-211d-11e6-894c-b6103e58b2b5.png">

As I mentioned I'm not too familiar with PHP/MYSQL so I've been stuck on this for quite some time now, if anyone has any ideas as to where I'm going wrong or could offer an example it would be greatly appreciated!
