### ISSUE TITLE
always redirecting to main page

### ISSUE THREAD

**Issue by Artemiis** [YOURLS/YOURLS#2096]
* YOURLS version: 1.7.1
* PHP version: 5.5.9
* Nginx 1.4.6 Ubuntu 14.04 Server

I installed a new fresh copy of yourls with the nginx config provided here. I be able to use the interface, api and so, but yourls always redirect to my main page (index.php)
I've checked the mysql database (there are all the links should be) und other nginx settings.
yourls-loader deos always refer to main page.

When it's not a bug please tell me, i dont know what to do that it's working.
I've used yourls for some months on a other server with lighttpd, working great so perhaps nginx is the problem.
Sorry for my bad english ;)

**Comment by dgw** [comment]
I'm using a very similar config to the one in the YOURLS wiki with nginx on Ubuntu 12.04, and have had no issues. (The only real difference is that I don't have another `try_files` directive in the php block.)

Not sure if #1715 has anything relevant to you, but without seeing any of your actual config there's no real way to make any suggestions beyond "You did something wrong." 😉

**Comment by Artemiis** [comment]
is use this config:
server {
        listen [::]:80;
        root /var/www/yourls/;
        index index.html index.htm index.php;

        location / {
        try_files $uri $uri/ /yourls-loader.php;
        location ~ \.php$  {
                fastcgi_pass   unix:/var/run/php5-fpm.sock;
               fastcgi_index  index.php;
               fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
                include        fastcgi_params;
                }
        }      
        include /etc/nginx/ssl.conf;
}

but with other configs  (i had this thread and tried some things): same problem.
in yourls i have only copied the frontpage to index.php and set up the /user/config.php

**Comment by dgw** [comment]
No `server_name` or only omitted here for privacy?

Only listening on IPv6? (Probably unrelated, but worth checking.)

See if changing these two lines helps at all:

````
root /var/www/yourls;  # no trailing slash
index index.php;  # this is what I use
````

**Comment by Artemiis** [comment]
i only dropped for privacy, i know that this works, yeah only v6, because i don't have a public v4 and i use a reverse proxy for v4...

no changes but thanks for helping...

**Comment by Artemiis** [comment]
Okay, now i know, that the problem it that yourls-loader.php exít at the end with:
`// Past this point this is a request the loader could not understand
yourls_do_action( 'loader_failed', $request );
yourls_redirect( YOURLS_SITE, 301 );
exit;`

**Comment by Artemiis** [comment]
i'have checked same config with lighttpd (witch worked for me ), same problem.
Witch packages should i have on my ubuntu?

**Comment by Artemiis** [comment]
Issue solved.
I used a reverse proxy and so 2 domains.
This plugin allows multiple domains: Allow aliases by Aylwin
So no bug.

**Comment by LeoColomb** [comment]
@Artemiis Thanks for your feedback!
