### ISSUE TITLE
Admin login issue

### ISSUE THREAD

**Issue by Jeremyboy222** [YOURLS/YOURLS#2097]
First of all, thanks for this (what looks likes) wonderful software. I am however stuck in installing it. I hope that someone can help me! Thanks in advance.

### Technical details

* YOURLS version: 1.7.1
* PHP version: 5
* Webhosting with DirectAdmin panel.
* Any other useful information depending on context (server version, mysql version, browser version, OS version...)

### Reproducible Bug Summary 

1. Fresh install of YOURLS
2. Follow and execute all steps
3. At the admin login screen, I try to login but I can't. It says "Invalid username or password". I also notice that the password doesn't get encrypted in the config file after running a page of YOURLS. I also tried the MD5 method, but that one doesn't work either..

This is a bug because... I can't use YOURLS :(

**Comment by LeoColomb** [comment]
Are you sure you correctly configured the user in your `config.php` file?

**Comment by Jeremyboy222** [comment]
Hello,

Yes! I'm 100% sure. I even tried to add a second user.. It didn't work.. But as I said, I find it very strange that the password doesn't get encrypted in the config.php file..

Kind Regards,
Jérémy

**Comment by Jeremyboy222** [comment]
@ozh Do you know a solution for this issue? Thanks in advance!

**Comment by Jeremyboy222** [comment]
Issue solved! I got some wrong type of quotes in my config file. I just used a fresh new one and it's working wonderful now! Thanks and sorry for disturbing.
