### ISSUE TITLE
Plugin list update

### ISSUE THREAD

**Issue by adigitalife** [YOURLS/YOURLS#2098]
Not sure where to post this so I'll just place it here.  Please update the plugin list with the new locations on github.

Case insensitive: https://github.com/adigitalife/yourls-case-insensitive
Allow aliases: https://github.com/adigitalife/yourls-allow-aliases
Check URL: https://github.com/adigitalife/yourls-check-url
Change error messages: https://github.com/adigitalife/yourls-change-error-messages
Fix long URLs: https://github.com/adigitalife/yourls-fix-long-url
HTTP Proxy: https://github.com/adigitalife/yourls-http-proxy

**Comment by ozh** [comment]
All updated ! Thanks
