### ISSUE TITLE
Install in sub-directory, but urls from root?

### ISSUE THREAD

**Issue by pin8all** [YOURLS/YOURLS#2099]
This isn't a bug but something I haven't been able to find an answer for in the docs.

Installing YOURLS in www.example.com/yourls produces short URLS like:

http://www.example.com/yourls/short

Is it possible to produce short URLS like:

http://www.example.com/short

without installing YOURLS in the root directory?

Thank you

**Comment by fredatipik** [comment]
This page gives explanation how to do that: https://yourls.org/docs/guide/server-configuration. You have to add this code to your .htaccess file on the root folder of your site: `<IfModule mod_rewrite.c>
RewriteEngine on
RewriteCond %{HTTP_HOST} sho.rt$
RewriteCond %{REQUEST_URI} !^/yourls_subdir/
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ /yourls_subdir/$1
RewriteCond %{HTTP_HOST} sho.rt$
RewriteRule ^(/)?$ yourls_subdir/yourls-loader.php [L]
</IfModule>`
(replace sho.rt and yourls_subdir with your hostname and directory name)

However, I did put this code in my .htaccess and there is no change. I still see shortcodes as doma.in/yourls_sub/shorturl.
