### ISSUE TITLE
Being redirected to :2086 instead of proper URL

### ISSUE THREAD

**Issue by entreprenewer** [YOURLS/YOURLS#2101]
### Technical details

* YOURLS version: 1.7.1
* PHP version: 5.2.17

### Reproducible Bug Summary 

1. Entered http://dealguardian.net/product/831/?hop=JonathanLev as the link I want to shorten
2. Tried out the short link (http://jle.vi/whm)
3. Redirected to http://jle.vi:2086

This is a bug because I want to redirect to the link in Step 1. 
I think it has something to do with DealGuardian redirecting people. 

How can I get it to work so that when someone goes to http://jle.vi/whm they go to the right place?
Thanks
JL

**Comment by LeoColomb** [comment]
Have you tested your installation with other links?
If you get the same error, please review your configuration...
If not, how this link is shown in your admin interface?

**Comment by entreprenewer** [comment]
Hi @LeoColomb, thanks for your prompt reply. I have been using and recommending YOURLS for years, it works well with all other links. 

Here's a screenshot of how it looks in admin:
<img width="1113" alt="screen shot 2016-05-30 at 14 44 28" src="https://cloud.githubusercontent.com/assets/1540530/15648722/0c3ace1c-2675-11e6-9990-989606db537b.png">

**Comment by ozh** [comment]
Out of the box, shortening http://dealguardian.net/product/831/?hop=JonathanLev works just fine: http://yourls.org/dr

So the problem is caused by something in your setup : see https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps, feel free to report back with additional details if any

**Comment by entreprenewer** [comment]
This seems to be an issue with my web host, as /whm is set up to redirect to a cPanel that I don't have installed. Proceeding to work with them on it. Thank you.

**Comment by LeoColomb** [comment]
@entreprenewer Thank's a lot for your reply!

**Comment by ozh** [comment]
Hostgator ?
