### ISSUE TITLE
Short Urls link internally instead of to the target link

### ISSUE THREAD

**Issue by seniorrossi** [YOURLS/YOURLS#2103]
Hi 

I have newly setup yourls (v 1.71, mySQL 5.5,).

Now, what is happening is that short URLs do not link to the external target link, i.e.
instead of:
www.ownsite.www/shorturl ==> link to www.externalsite.www/longurl
I get this:
www.ownsite.www/shorturl ==> www.ownsite.www/shorturl

Anybody have an idea, what I am missing here?
Thanks!

**Comment by dgw** [comment]
So your YOURLS is redirecting to itself? 😕

**Comment by seniorrossi** [comment]
Yes

**Comment by dgw** [comment]
If it was redirecting to itself, it would exceed the redirect limit and your browser would display an error. So more likely, the server is not configured correctly and isn't redirecting at all.

**Comment by ozh** [comment]
:+1: @dgw :)

@seniorrossi feel free to add more details that we may use to be able to help you. Closing the issue, this is obviously a config issue and most likely not in YOURLS itself.
