### ISSUE TITLE
Track Homepage 

### ISSUE THREAD

**Issue by blacksky86** [YOURLS/YOURLS#2107]
So I have read that there's no index.html, which is fine, but I can't seem to figure out how to make it so that when the user goes to example.com(my short url) it redirects them to newexample.com and tracks it. 

It seems that on the dashboard is it always want's a trailing slash and then something. I have removed the trailing part and when I click save, it just goes to 0. 

Is there any way to do this? I tried to look for a solution, but it seems I didn't find it. Thank you.

**Comment by dgw** [comment]
I think the best you could do would be creating a shorturl keyword for `home` or whatever, then redirecting `example.com/` to `example.com/home`, which would redirect to `newexample.com`.

**Comment by LeoColomb** [comment]
@dgw's solution is easy and fine.
But if you want better than easier, you may start with a plugin like [yourls-redirect-index](https://github.com/tomslominski/yourls-redirect-index) and add a keyword count update inside.

Definitely doable with a plugin.
