### ISSUE TITLE
Allow to define tags

### ISSUE THREAD

**Issue by leowzukw** [YOURLS/YOURLS#2109]
### Feature request Summary 

1. It would be interesting to be able to attach tags to shortened urls.
2. One may use it to record where shortened urls (possibly redirecting to the same long one) were posted. For instance, a shortened url shared inside the version 2 of a program would be associated with tag `v2`, while a short url shared on Diaspora would be attached a `diaspora` tag. This way, it would be easier to see whether a certain version is still active.
3. Wider, tags would improve global organization of shortened urls, to group deprecated urls, old ones used once and no more active…

*This is a feature request may be implemented with the database related changes planned with version 2.0.*

#### Ideas for implementation

 + You may attach several tags to an entry.

**Comment by ozh** [comment]
See roadmap
