### ISSUE TITLE
Problem with Yourls 1.7.1 / Debian 8.5

### ISSUE THREAD

**Issue by thheide** [YOURLS/YOURLS#2110]
Hi,
we have a problem with
yourls 1.7.1
on Debian 8.5
with PHP 5.6.20
Apache 2.4.10

We can't login on http://mydomain.com/admin
the browsers says nothing.

the php.log file says:
[15-Jun-2016 08:09:01 Europe/Berlin] PHP Fatal error:  Directive 'allow_call_time_pass_reference' is no longer available in PHP in Unknown on line 0

**Comment by ozh** [comment]
Not a YOURLS problem but a PHP config problem. Edit your php.ini and remove the allow-call-time-pass-reference entry. See http://php.net/manual/en/ini.core.php#ini.allow-call-time-pass-reference

**Comment by thheide** [comment]
No Chance. After the remove of the allow_call reference on the php.ini:
i can't login on /admin with the correct username/password :-(

**Comment by thheide** [comment]
After a fresh install with a new databsae on the same server.. we have the same problem.

we can't login.
The browser says: Please Log in

**Comment by ozh** [comment]
And nothing in the error log ?

**Comment by thheide** [comment]
No.
yourls-Debug-Level=true display in the broweser this:
DB driver: pdo
SELECT `option_name`, `option_value` FROM `yourls2_options` WHERE 1=1
SELECT `option_value` FROM `yourls2_options` WHERE `option_name` = 'active_plugins' LIMIT 1

allow-call-time Problem:
Can you fix in a newer Version the:  allow-call-time- problem?

**Comment by thheide** [comment]
we solve this problem.
it was an apache fail configuration..
