### ISSUE TITLE
Public Prefix & Shorten short only with http://

### ISSUE THREAD

**Issue by seventhsite** [YOURLS/YOURLS#2111]
* **YOURLS version: 2.0**
* PHP version: 7.0.7-4+deb.sury.org~trusty+1
* LAMP
 

http://test.ali.onl/ru.aliexpress.com/ru_home.htm - redirect to main page test.ali.onl
http://test.ali.onl/http://ru.aliexpress.com/ru_home.htm - redirect to http://test.ali.onl/index.php?url=http%3A%2F%2Fru.aliexpress.com%2Fru_home.htm and create short link.

Plugin works only if I write by hand http:// before url.

```
root@test:/var/www/test.ali.onl/user/plugins/public-pns# cat plugin.php
<?php
/**
Plugin Name: Public Prefix-N-Shorten
Plugin URI: http://yourls.org/
Description: Redirect "Prefix n' Shorten" bookmarklets to public interface
Version: 1.0
Author: Ozh
Author URI: http://ozh.org/
**/

// URL of your public interface, with query parameter to which the long URL will be passed
// This URL must contain a query string with "parameter equals %" (eg "url=%")
define( 'OZH_PUBPNF_URL', 'http://test.ali.onl/index.php?url=%' );

yourls_add_action( 'load_template_redirect_admin', 'ozh_pubpnf' );
function ozh_pubpnf( $args ) {
        // Long URL requested?
        $url = $args[0];

        // If logged in and don't want to change behavior for logged in users, do nothing
        if( yourls_is_valid_user() === true )
                return;

        // Otherwise, interrupt
        $redirect = str_replace( '%', rawurlencode( $url ), OZH_PUBPNF_URL );
        yourls_redirect( $redirect, 302 );
        die();
}
```

Is plugin need other settings except activation?

**Comment by seventhsite** [comment]
Offtopic - where can I ask other questions? Is there any forum?

**Comment by ozh** [comment]
Works as expected.

**Comment by ozh** [comment]
There's no forum. You can ask questions as issues here, make sure to write them properly so they can benefit other people with the same questions.

**Comment by seventhsite** [comment]
Is it possible to make shortening for URL's without http:// ?

**Comment by dgw** [comment]
As @ozh said, it is expected behavior that the plugin only activates on URLs beginning with a protocol. The intent, as indicated by "Prefix-N-Shorten" in the name, is to prefix the URL already in your address bar—which, until Chrome popularized not displaying the protocol for plain HTTP pages, would begin with `http://`.

It would be possible to modify the plugin's URL matching to also work on URLs not starting with a protocol, yes.

**Comment by seventhsite** [comment]
> until Chrome popularized not displaying the protocol for plain HTTP pages, would begin with http://.

This is why I ask.

> possible to modify the plugin's URL matching to also work on URLs not starting with a protocol, yes.

How can I do it?

**Comment by ozh** [comment]
Practically, you cant. http://sho.rt/http://somesite/ is unambiguous, while http://sho.rt/somesite/ (or http://sho.rt/somesite.com/) might be a subdirectory.

Your option would to code a custom plugin that would consider all subdirectories as long URL to shorten and prefix.
