### ISSUE TITLE
define( 'YOURLS_URL_CONVERT', 36 ); -- Question for bulk import.

### ISSUE THREAD

**Issue by stevenmcastano** [YOURLS/YOURLS#2112]
I'm trying to move a ton of links from bit.ly over to my YOURLS installation. I have a branded bit.ly domain so I have a ton of links like ```http://link.mydomain.com/htGuDH50``` and I exported all my links, created a CSV file and I intended to use the the "[Bulk Import and Shorten](https://github.com/vaughany/yourls-bulk-import-and-shorten)" to import all of them.

But in both your YOURLS documentation and in the documentation for the plugin is recommends basically not changing the above setting from base 36 to base 62 to have mixed case URLs once you're installation already has links in it. Is there any way to get around this? A way to do it and make sure it works so I can have the mixed case short-links?

I've already installed the "[Case Insensitive](https://github.com/seandrickson/YOURLS-Case-Insensitive/)" plugin, so even if I use the "[Force Lowercase](https://github.com/yourls/force-lowercase)" plugin... everything should work.

My guess is, if I use Force Lowercase, everything will come in and become lower case, but then when I switch my DNS over to my YOURLS installation even though the link coming in would be ```http://link.mydomain.com/htGuDH50``` and the link in YOURS would be ```http://link.mydomain.com/htgudh50```, the Case Insensitive plugin will make it work anyway... but I'd love to avoid that and have the original links working as they should be.

Any help anyone could provide would be great! Thanks!

*SMC

### Technical details

* YOURLS version: 1.7.1
* PHP version: 5.5.9
* OS: Ubuntu 14.0.4 LTS
* Web Server: nginx 1.10.1 using php-fpm

**Comment by ozh** [comment]
Just set it on base 62 and nothing else. Going from 36 to 62 and leaving it as is is OK. Don't use case plugins, as bitly IS case sensitive and you could have `abc123` and `ABc123`.
