### ISSUE TITLE
How to change the tab title from YOURLS--Youre own.....

### ISSUE THREAD

**Issue by lightning30** [YOURLS/YOURLS#2113]
How do I change the tab title of a page? Right now it is showing as YOURLS--Your Own..... I want it to have my website title. thank you.

**Comment by lightning30** [comment]
Got the issue fixed. Just had to add 

<title>TITLE HERE</title>

above where the pho code starts. It overrides wherever the previous page title was coming from.

**Comment by koesxl** [comment]
do you mind being more specific? i'm having the same issue but i have no clue where to put the <title>

**Comment by LeoColomb** [comment]
* Admin area: [really simple plugin](https://github.com/YOURLS/YOURLS/blob/3438b06/user/plugins/sample-plugin/plugin.php#L38-L60);
* Your custom pages: your code with your HTML `<title>`.
