### ISSUE TITLE
YOURLS is accessing the long URL

### ISSUE THREAD

**Issue by Purlek** [YOURLS/YOURLS#2114]
### Technical details

* YOURLS version: 1.7.1
* PHP version: php5-fpm (php5.5.9)
* ShareX version: 11.0.1
* Server version: Ubuntu 14.04.4 LTS

### Reproducible Bug Summary 

1. Have plugin listed below. 
2. Use API to shorten a URL containing GET variables (i.e. /index.php?var=example)
3. YOURLS API does not return shortened URL.

1. Shorten URL with YOURLS
2. YOURLS accesses the destination of the long URL, leaving a mark as though YOURLS was a user accessing it.

An explanation of my problem. I have YOURLS setup on a home server. I have [this plugin (redirect with get)](https://github.com/fnkr/YOURLS-redirect-with-get) setup with my installation. 
I'm currently using ShareX to upload a picture, of which I attempt to shorten a URL containing a GET variable at the end of it. The URL attempting to be shortened works properly. The shortened URL of the long URL works properly. 
And at this point are the two problems I'm experiencing, first, ShareX is using the YOURLS API on my server, however, upon shortening the URL while utilizing the above mentioned plugin, it does not return the shortened URL, and thus, ShareX is not able to copy the shortened URL to my clipboard. Instead, I have to access the YOURLS webpage and copy it manually..

And the second problem is that upon shortening a URL, YOURLS accesses the destination of the long URL, and it shows a request similar to that of a user's in the access logs. Is there a way to avoid this?

**Comment by dgw** [comment]
YOURLS fetches the long URL to retrieve the page title if no title is specified in the API request. It appears there is no setting to override this behavior. However a plugin can short circuit the title retrieval by returning true from a filter on `shunt_get_remote_title`.

The API issue is beyond my current ability to look into things.

**Comment by ozh** [comment]
Regarding YOURLS requesting remote URL, see @dgw's comment.

Regarding the other problem, I don't know ShareX and how it works, sorry

**Comment by Purlek** [comment]
I've been looking over the source for both ShareX and YOURLS today. I believe the issue is within the API or the GET plugin. 

ShareX has a pretty simple interface with YOURLS, relevant code below, can post more if you need:

**(ShareX/ShareX.UploadersLib/URLShorteners/YourlsURLShortener.cs _Line 85-95_)**
```
                arguments.Add("action", "shorturl");
                arguments.Add("url", url);
                //arguments.Add("keyword", "");
                arguments.Add("title", url);
                arguments.Add("format", "simple");

                result.Response = SendRequest(HttpMethod.POST, APIURL, arguments);
                result.ShortenedURL = result.Response;
            }

            return result;
```

As for the API, I feel that it has something to do with **(includes/functions-api.php _Line 17-26 or 102-106_)** with the **yourls_api_action_shorturl()** function, or the **yourls_api_output()** function, given that it's simply not returning a shorturl. As for the plugin's code, it's not very complicated, and it simply changes what's passed as the $url variable to include the query string at the end of the long URL.

Maybe I'm hugely misunderstanding the problem and it does actually lie within ShareX, but at first glance it doesn't seem that way.

**Comment by dgw** [comment]
Yep, ShareX uses pretty simple code there. And it looks like the `title` parameter [isn't even sent](https://github.com/ShareX/ShareX/blob/d5d1dae20c50a12947ee2971edc71018178f5d7d/ShareX.UploadersLib/URLShorteners/YourlsURLShortener.cs#L88).

It could be instructive, if you have access to the webserver log files, to have a look at the log lines from ShareX's requests to see exactly what arguments it sends. You might need to alter the logging settings to capture POST parameters, but it probably would be useful information to have for debugging. Failing that, I'm not sure how one would go about debugging YOURLS more in-depth (more of a Python guy these days than PHP), but maybe @ozh can provide some pointers if server logs don't help.

**Comment by Purlek** [comment]
In the end, my fault. Not YOURLS or ShareX.

While troubleshooting something else I had changed "ClipboardContentFormat" to "$shorturl" instead of "$result" within ShareX.
