### ISSUE TITLE
graph y axis broken

### ISSUE THREAD

**Issue by digininja** [YOURLS/YOURLS#2117]
Before any bug report:

Thanks you!

### Technical details

* YOURLS version: Powered by YOURLS v 1.7.2 – 7 queries 
* PHP version: PHP 5.6.22-0+deb8u1 (cli) (built: Jun  9 2016 07:14:06)

### Reproducible Bug Summary 

1. fresh install of yourls
2. created my first shortcut
3. visited it once
4. looked at the traffic stats graph
5. the y axis has the label 1 on it twice, the second where 2 should be.

This is a bug because... the graph goes to 2 but the axis label is 1 and there has been only 1 hit so it shouldn't go that high anyway.

![broken_graph](https://cloud.githubusercontent.com/assets/117081/16691917/98b9fb9a-4526-11e6-8866-1e4a513f9a69.png)

**Comment by ozh** [comment]
Get two hits. Problem solved :)

Anyway, it's how the graph lib from Google works. Not a YOURLS defect I think, but if you think there's something improvable, feel free to submit a patch.

**Comment by digininja** [comment]
Fair enough
