### ISSUE TITLE
Short link problem without http:// prefix issue.

### ISSUE THREAD

**Issue by erreip88** [YOURLS/YOURLS#2118]
* YOURLS v 1.7.1 
* PHP version: 5.6

Hello Guys,
I've set up from 2 years Yourls script on my domain, it's working very good.

Why if I visit the link with WWW instead HTTP the script redirect me to my website home page and not the page I've choosed to short link?

Example: 

http://domain.com/Jy9n3 - OK
www.domain.com/Jy9n3 - REDIRECT ON -> www.domain.com

**Comment by ozh** [comment]
Because your server is configured that way. Not a YOURLS defect: http://www.yourls.org/d9 = http://yourls.org/d9 for instance.
