### ISSUE TITLE
Toolbar Error with Mobile Devices Only

### ISSUE THREAD

**Issue by mweth** [YOURLS/YOURLS#2120]
* YOURLS version:  1.7.1

* PHP version:  5.6

* Any other useful information depending on context (server version, mysql version, browser version, OS version...)

### Reproducible Bug Summary 

1. Activate YOULRS toolbar plugin
2. Create new link
3. Visit link on pc browser, noting toolbar across the top
4.  visit link on mobile device, noting that page is forced into non-mobile viewing mode

I do not know if this is a bug or a feature request, but the toolbar plugin currently forces all pages to render in desktop mode when viewing on a mobile device.  My specific installation example:  http://mqw.fyi/3

Is there a way to make the toolbar appear differently or allow mobile view when using a mobile device?

**Comment by ozh** [comment]
From the plugin readme: `This is a sample plugin, for illustration purpose.`
From the plugin itself: `Disclaimer: Toolbars ruin the user experience. Be warned.`

Plus, your question is about HTML rendering in your custom toolbar, not about YOURLS itself. Sorry, cant help.
