### ISSUE TITLE
YOURLS omits fragment from Location header

### ISSUE THREAD

**Issue by dgw** [YOURLS/YOURLS#2121]
### Technical details

* YOURLS version: 1.7.1
* PHP version: 5.5.35+dfsg-1+donate.sury.org~precise+4 (FPM instance)
* MySQL version: 14.14 Distrib 5.5.49
* Webserver: nginx/1.10.1

### Reproducible Bug Summary 

1. Create a short URL `http://yourls.server/fragment` that contains a `#fragment`, e.g. `http://example.com/#test`
2. View headers sent by YOURLS using cURL or equivalent:
````
$ curl --head http://yourls.server/fragment
HTTP/1.1 301 Moved Permanently
Date: Mon, 18 Jul 2016 20:53:18 GMT
Content-Type: text/html
Connection: keep-alive
Location: http://example.com/
[…]
````

### Supporting Data

Confirmations that YOURLS stored the fragment in its database:
![image](https://cloud.githubusercontent.com/assets/164140/16930013/5ff1a6e8-4d08-11e6-9bb1-ed1e3b45489b.png)
![image](https://cloud.githubusercontent.com/assets/164140/16930086/bdd724fe-4d08-11e6-97ed-a67d0d611907.png)

**Comment by dgw** [comment]
Note that this was initially reported as a bug in a plugin for YOURLS 1.6 (dgw/yourls-dont-track-admins#2) but occurs even with that plugin disabled under 1.7.1.

**Comment by rengawslin** [comment]
Experiencing the same issue with the following software versions:

- **YOURLS Version:** 1.7.1 (also tested 1.7.2, cloned from the repo) 
- **Active YOURLS Plugins:** Query String Forward, Allow Hyphens in Short URLs
- **PHP Version:** php-5.4.14
- **MySQL Version:** 5.1.50
- **Webserver:** apache-2.2.24-sunc-prefork

**Comment by ozh** [comment]
Cannot reproduce. Test with http://yourls.org/ds :

```
$ curl --head http://yourls.org/ds
HTTP/1.1 301 Moved Permanently
Date: Tue, 13 Sep 2016 20:07:58 GMT
Server: Apache
Location: http://example.com/#example
Vary: Accept-Encoding
Content-Type: text/html
```

**Comment by dgw** [comment]
Discussion and resolution in #2142 led me to test again after disabling Google Analytics plugin. The issue was not present. I apologize for the erroneous report; most likely I did not perform the test under the correct conditions, and CloudFlare caching masked the behavior change when I tested disabling various plugins. But I'm glad the culprit has been found!
