### ISSUE TITLE
How to modify statistics page in 2.0 whithout hacking yourls-infos.php?

### ISSUE THREAD

**Issue by seventhsite** [YOURLS/YOURLS#2128]
Technical details

* YOURLS version: 2.0
* PHP version: 7

There is no examples in theme.php how to modify design of statistics page. Now I see only one way - edit yourls-infos.php. Is there another ways whithout hacking the core?

**Comment by ozh** [comment]
2.0 is far from being functional at this point. I don't think we've ever worked on yourls-infos actually...
