### ISSUE TITLE
Using Yourls in Intranet while urls remain accessible to public

### ISSUE THREAD

**Issue by ayyoovod** [YOURLS/YOURLS#2129]
I'm running Yourls (v 1.7.1) as private installation and I would like to make it accessible through EZproxy so that only users in our network or using their single sign on can create new URLs. But I also want the created URLs to be accessible to the public without any need to login.
I'm not sure how to accomplish this.

**Comment by LeoColomb** [comment]
Your question is completely related to your proxy and firewall configuration. No relation with YOURLS.
Please ask your sysadmin.
