### ISSUE TITLE
%2f symbol omitted in the shortned URL

### ISSUE THREAD

**Issue by ayyoovod** [YOURLS/YOURLS#2130]
There are few topics on the same subject but I can't access them on Google Code since it automatically redirect me to Git. So I would like to get some help instead if just closing the issue. Thanks.

I use Yourls to shortned long Subscription Databases links for our library. Some of them have %2f symbols in the long URL but it doesn't get translated properly in the short URL. Here is an example where the "%2f" is translated to "/"

https://apps.fastcase.com/PartnerBenefits/?IPKey=xZ9PIlnqIH3NZFSTa380eZThK4dwD1BV1Lvl0g4oRIyi7p**%2f**DhkC1P1EfmZy0xyKuYMqlChiI8aUiMX2BdpYHPtj8X2RqEmGWFypI3Na%2f76ZuZ9GmpAn%2bQ5sJIlxW4ZX3&LogoutUrl=http://law.umkc.edu/library/

Becomes:

https://apps.fastcase.com/PartnerBenefits/?IPKey=xZ9PIlnqIH3NZFSTa380eZThK4dwD1BV1Lvl0g4oRIyi7p**/**DhkC1P1EfmZy0xyKuYMqlChiI8aUiMX2BdpYHPtj8X2RqEmGWFypI3Na**/**76ZuZ9GmpAn+Q5sJIlxW4ZX3&LogoutUrl=http://law.umkc.edu/library/

* YOURLS version: v 1.7.1
* PHP version: 5.4
* mySQL, on shared Linux hosting platform

**Comment by LeoColomb** [comment]
X-Ref: #1303
