### ISSUE TITLE
Can't seem to IGNORE Update Messages ???

### ISSUE THREAD

**Issue by ECHSBACHS** [YOURLS/YOURLS#2132]
I tried adding the following line at the end of config.php:

define( 'YOURLS_NO_VERSION_CHECK', true );

but, the UPDATE Message is still appearing ???

HOW TO 'IGNORE' Update Messages ???

Thanks.

**Comment by ozh** [comment]
Cannot replicate this and from what I read in the code I don't get how this can happen.
Add define( 'YOURLS_DEBUG', true ); in your config.php and report what it's logging please

**Comment by ECHSBACHS** [comment]
OK . . . 
I Added  define( 'YOURLS_DEBUG', true );  in config.php . . .

Now What ?

Thanks.

**Comment by ozh** [comment]
Now report what it is logging in the footer of every page, in particular when there's an update notice displayed

**Comment by ECHSBACHS** [comment]
Nothing is in the 'footer' ?
- Sorry, I don't get it ???

**Comment by LeoColomb** [comment]
Could you provide a screenshot of the page where the notice appears, please?

**Comment by ECHSBACHS** [comment]
(Please See attached)

Thanks.

---------------

**Comment by ECHSBACHS** [comment]
attached.

![duelupgdnoticepic](https://cloud.githubusercontent.com/assets/19473995/18061031/1bd77c64-6def-11e6-8caf-83ad6af36b4c.jpg)

**Comment by ozh** [comment]
This install looks modified to the point we cannot provide generic tips. Sorry, you're on your own there.

**Comment by ozh** [comment]
Actually I got your screenshot... OBVIOUSLY we're talking about the admin interface, not a custom public one.
