### ISSUE TITLE
tel: links return 'Missing or Malformed Link message

### ISSUE THREAD

**Issue by cshenry13** [YOURLS/YOURLS#2135]
### Technical details

* YOURLS version: 1.7.1
* PHP version: 5.4.45
* MySQL version: 5.5.48-37.8
* Using the Google Analytics plugin, allow hyphens plugin, and QR code shortcode plugins

### Reproducible Bug Summary 

1. Tried using 'tel://' and 'tel:' but both flash the warning about 'Missing or malformed link'

This is a bug because according to http://blog.yourls.org/2013/01/its-alpha-but-its-stable-for-now/, it might have been working in 2013.

If this is NOT part of the scope of YOURLS, I apologize for posting here, but my understanding was it would work.

**Comment by ozh** [comment]
It should have worked, indeed. For some reason I forgot this protocol in the list of allowed stuff from the box. I've just pushed a change to fix it, available in current [master.zip](https://github.com/YOURLS/YOURLS/archive/master.zip)

If for some reason you don't want to update to latest master, you can also make a very simple plugin  like this one: https://github.com/YOURLS/custom-protocol

**Comment by cshenry13** [comment]
Thank you, that was perfect.
