### ISSUE TITLE
Fatal PHP error can't load page too many redirects

### ISSUE THREAD

**Issue by templbi** [YOURLS/YOURLS#2136]
### Technical details

* YOURLS version: 1.7.1
* PHP version: 5.4 native 
* Any other useful information depending on context (server version, mysql version, browser version, OS version...)

I have this installed on grg.bz. I installed it through GoDaddy hosting using Installatron. 

I can open grg.bz/admin and use the platform but if I just click on grg.bz it gives an error of too many redirects. 

When I open the error log it has this: [25-Aug-2016 16:53:47 UTC] PHP Fatal error:  Class 'Gettext_Translations' not found in /home/billyt/public_html/grg.bz/includes/pomo/mo.php on line 14

This was a fresh install on a new site. Is it something I am doing, a bad install, or..

**Comment by LeoColomb** [comment]
Please ask "Installatron" administrators first. If it's already done, try to reinstall manually.
