### ISSUE TITLE
SSH Update not working (for me)

### ISSUE THREAD

**Issue by SkyNetGlobal** [YOURLS/YOURLS#2138]
I thought I'd update my YOURLS install and tried to update it using the commands on this page:
https://github.com/YOURLS/YOURLS/wiki/Install-From-Git

I SSH'd into my server and issued this command:

"bash git pull https://github.com/YOURLS/YOURLS.git master"

and without the "bash" too, like this:

"git pull https://github.com/YOURLS/YOURLS.git master"

but received this error message:

"fatal: Not a git repository (or any of the parent directories): .git"

Am I doing something wrong?
Please be nice - it's my first post on GitHub!

Running Yourls ver 1.7.1

**Comment by dgw** [comment]
If you didn't install from Git, then your install folder isn't a git repository.

I haven't tested this, but you should be able to `git init` an empty repo in your YOURLs dir, then `git remote add origin https://github.com/YOURLS/YOURLS.git && git pull origin master`

Again, not tested—so you might have to use `git fetch` instead of `git pull`, or `git checkout master` after pulling, or something else I've not thought of depending on how git handles you turning an existing directory into a repo.

**Comment by SkyNetGlobal** [comment]
Wow - that's a fullsome reply - thanks!

Firstly, I did a manual install a few years ago, into a subdirectory on my server, so, yes, my "install folder" is not a git repository. I do not know the difference.

I think you are saying that I could create a new directory (you call a repo - right?) inside the same folder where it currently exists, and then somehow (with those commands) convert the existing directory into a "repo" instead - right again?

**Comment by dgw** [comment]
A git "repo" is all contained in a subfolder called `.git`. The files you see are the "working copy", which  you can play with and edit and then have git compare the differences to what's stored in the repo and apply the changes in a commit. (That's a **very** basic explanation, but it hits the basics.)

So if you `git init` inside the existing YOURLS directory you're running from, Git will create the `.git` folder and set it up. Then when you add the remote URL and tell it to `git pull`, it populates your new (empty, local) repo with the data from the remote repo.

**Comment by SkyNetGlobal** [comment]
OK - thanks again - I am slowly understandning this.

Playing devils' advocate here - is it not easier to do a manual install/update over the top of the existing install? What are the differences of that versus creating a .git _subfolder_ called ".git" and then me updating the .git subfolder and me updating that subfolder with a "git pull"?

**Comment by dgw** [comment]
It very likely is simplest to just download the current ZIP and extract it over the existing files (ideally after making a backup copy of your existing install folder in case of problems). Unless you want to run pre-release code, bothering with the Git repo is probably not worth it.

**Comment by SkyNetGlobal** [comment]
Thanks, dgw - I was coming to that conclusion. I think I'll follow your suggestion.

**Comment by ozh** [comment]
(For the record, there was a couple formatting errors in the doc, like the "bash git", there's no "bash" supposed to be typed in)
