### ISSUE TITLE
Kibana encoding error - Unable to parse URL

### ISSUE THREAD

**Issue by TiTi** [YOURLS/YOURLS#2140]
When I use the popup bookmark to shorten the following url and use it back it doesn't work: 

> http://ly-eodgw:3402/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(columns:!(_source),filters:!((meta:(disabled:!f,index:longrequests_read,key:database,negate:!f,value:POSTGREC%3Buser%3DDBADM),query:(match:(database:(query:POSTGREC%3Buser%3DDBADM,type:phrase)))),(meta:(disabled:!f,index:longrequests_read,key:contextName,negate:!f,value:'conncont(GLOBAL)'),query:(match:(contextName:(query:'conncont(GLOBAL)',type:phrase))))),index:longrequests_read,interval:auto,query:(query_string:(analyze_wildcard:!t,lowercase_expanded_terms:!f,query:'*')),sort:!(date_time,desc))

Kibana is an HTML visualization for Elasticsearch. It says:

> Unable to parse URL
### Technical details
- YOURLS version: 1.7.1

In the admin panel, I can see (when editing) that the url is:

> http://ly-eodgw:3402/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(columns:!(_source),filters:!((meta:(disabled:!f,index:longrequests_read,key:database,negate:!f,value:POSTGREC;user=ESKDBADM),query:(match:(database:(query:POSTGREC;user=ESKDBADM,type:phrase)))),(meta:(disabled:!f,index:longrequests_read,key:contextName,negate:!f,value:'conncont(GLOBAL)'),query:(match:(contextName:(query:'conncont(GLOBAL)',type:phrase))))),index:longrequests_read,interval:auto,query:(query_string:(analyze_wildcard:!t,lowercase_expanded_terms:!f,query:'*')),sort:!(date_time,desc))

I also got the same value on the `Location:` header returned by yourls.

**%3C and %3D have been replaced with ";" and "="**

:-(

**Comment by LeoColomb** [comment]
#1303

**Comment by ozh** [comment]
Closing: 2691 and associated PR will supersede
