### ISSUE TITLE
Unable to redirect to a url with an anchor tag (hash / pound sign)

### ISSUE THREAD

**Issue by phfft** [YOURLS/YOURLS#2142]
Version: 1.7.1

Trying to create a short URL for an address with an anchor tag:

http://domain.com/page.php#anchor

YOURLs will go to the default redirect page (when URL not found or bad) and not the specified long URL with anchor. 

ETA: Noticed issue #2045 suggested that this was fixed in 1.7. Maybe re-introduced in 1.7.1?

**Comment by ozh** [comment]
Cannot reproduce, or I don't understand. Example: http://yourls.org/ds

**Comment by phfft** [comment]
Looks like when I deactivated the Google Analytics plugin the redirects started working. Wish I knew why (v1.1 - https://katz.co/2300/).

Thanks for looking into it and inspiring me to check out what the difference may have been in your environment vs. mine.
