### ISSUE TITLE
Including "includes/load-yourls.php" in a custom PHP script

### ISSUE THREAD

**Issue by amindeed** [YOURLS/YOURLS#2145]
Hi everyone,

I'm working on a PHP script to which I will be passing GET query parameters to execute actions on the behalf of a social net account through its API.

For security (as the access keys are on the same file), I check if the user is logged in to YOURLS by calling the function **yourls_is_valid_user()** prior to doing anything. I've tried to include/require only the necessary files/dependencies for this, but as there are uses of global variables declared in **"user/config.php"** I couldn't find any way out other than including **"includes/load-yourls.php"**
So I'm wondering if that's a sane way to make things done.

Thanks for your help.

**Comment by ozh** [comment]
If your question is "how can I load YOURLS just enough to be able to use `yourls_is_valid_user()` from within another script", yes, I can't think of another way

**Comment by amindeed** [comment]
Yes, that's it. Thank you @ozh ! :)
