### ISSUE TITLE
Feature Request: Option for changing cache time of 301s

### ISSUE THREAD

**Issue by hilburger** [YOURLS/YOURLS#2147]
Hi everybody, 

it does not seeem to be possible to set a cache time for links. 
I have only found this thread here: 
http://stackoverflow.com/questions/31996596/set-cookie-expiration-to-2-minutes-for-yourls

But here it is suggested to make changes within the core which I want to avoid. 
Should this be a feature or is there a plugin which I haven't found yet? 

Thanks you!

### Technical details
* YOURLS version: 1.7.2

**Comment by dgw** [comment]
It may be that using a plugin such as [one of these](https://github.com/YOURLS/YOURLS/wiki/Plugin-List#302-instead) to issue 302 or 307 redirects (which are temporary and shouldn't be cached without explicit instructions to do so via `Cache-Control` headers) will solve your issue.

**Comment by ozh** [comment]
As far as I understand, a 301 redirect with a limited caching time is just a 302 redirect... It makes no sense to say "hey, browser, this is a **permanent** redirect, but check it **again in 90s** just to be sure..."

Hence, what @dgw says.

If for some reason that escapes me you still want to send a 301 *and* prevent caching it, this simple plugin should do:

```php
<?php
/*
Plugin Name: 301 errr I mean 302 wait no it is 301
Plugin URI: http://yourls.org/
Description: Plugin to confuse clients following a redirection
Version: 0.1
Author: Ozh
Author URI: http://ozh.org/
*/

yourls_add_action( 'redirect_shorturl', 'hilburger_301andahalf' );

function hilburger_301andahalf() {
    yourls_add_action( 'status_header', 'hilburger_301andahalf_just90s' );
}

function hilburger_301andahalf_just90s() {
    header( 'Cache-Control: private, max-age=90' );
}

```
