### ISSUE TITLE
Seg fault in version check

### ISSUE THREAD

**Issue by FeanorsCurse** [YOURLS/YOURLS#2148]
Hi,

yourls was seg faulting for me. I found the culprit to be these lines of code:

/includes/load-yourls.php

``` php
// Is there a new version of YOURLS ?
if( yourls_is_installed() && !yourls_is_upgrading() && yourls_maybe_check_core_version() ) {
    yourls_new_core_version_notice();
}
```

When I comment these out, everything works fine. Had pulled the latest version from git beforehand.

**> php --version:**

PHP 5.5.9-1ubuntu4.19 (cli) (built: Jul 28 2016 19:31:33)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies

**> apachectl -V**

Server version: Apache/2.4.7 (Ubuntu)
Server built:   Jul 15 2016 15:34:04
Server's Module Magic Number: 20120211:27
Server loaded:  APR 1.5.1-dev, APR-UTIL 1.5.3
Compiled using: APR 1.5.1-dev, APR-UTIL 1.5.3
Architecture:   64-bit
Server MPM:     prefork
  threaded:     no
    forked:     yes (variable process count)
Server compiled with....
 -D APR_HAS_SENDFILE
 -D APR_HAS_MMAP
 -D APR_HAVE_IPV6 (IPv4-mapped addresses enabled)
 -D APR_USE_SYSVSEM_SERIALIZE
 -D APR_USE_PTHREAD_SERIALIZE
 -D SINGLE_LISTEN_UNSERIALIZED_ACCEPT
 -D APR_HAS_OTHER_CHILD
 -D AP_HAVE_RELIABLE_PIPED_LOGS
 -D DYNAMIC_MODULE_LIMIT=256
 -D HTTPD_ROOT="/etc/apache2"
 -D SUEXEC_BIN="/usr/lib/apache2/suexec"
 -D DEFAULT_PIDLOG="/var/run/apache2.pid"
 -D DEFAULT_SCOREBOARD="logs/apache_runtime_status"
 -D DEFAULT_ERRORLOG="logs/error_log"
 -D AP_TYPES_CONFIG_FILE="mime.types"
 -D SERVER_CONFIG_FILE="apache2.conf"

**Comment by ozh** [comment]
Can you dig deeper and check what particular thing in this block is segfaulting? `yourls_new_core_version_notice()`? `yourls_maybe_check_core_version()`?

**Comment by FeanorsCurse** [comment]
Sure, I'll dig into it - gimme a couple of days, I'm pretty swamped at work atm.

**Comment by FeanorsCurse** [comment]
I enabled the version check again and now it works... sorry no idea what changed! Guess this can be closed then.
