### ISSUE TITLE
Spelling mistake "intented" in readme.html

### ISSUE THREAD

**Issue by JDLH** [YOURLS/YOURLS#2149]
### Technical details

* YOURLS version: HEAD of master, https://github.com/YOURLS/YOURLS/commit/bb4a764b65ee8d54b162dc4447e59d4853758a16
* PHP version: not applicable
* Any other useful information: not applicable

### Reproducible Bug Summary 

1. Use web browser to visit http://yourls.org/#noindex 
2. Read text under heading, "There is no index page at the root of the install"

**Observed behaviour**: the text begins, "Indeed. It's intented…"

**Expected behaviour**: the text should read, "Indeed. It's intended…"

This is a bug because the correct spelling of the word is "intended" with a "d". "intented" is a misspelling.

**Comment by JDLH** [comment]
Fix proposed in Pull Request https://github.com/YOURLS/YOURLS/pull/2150 .  I wanted the Pull Request to appear as part of this Issue, but I guess I don't understand how to make Github do that.

**Comment by ozh** [comment]
Just open a pull request :)
