### ISSUE TITLE
Issue title -- be DESCRIPTIVE

### ISSUE THREAD

**Issue by opsuk** [YOURLS/YOURLS#2151]
Before any bug report, check you are using the LATEST release or the development branch. Make sure you have SEARCHED closed issues first. Read the GUIDELINES linked in the yellow notice box above. Now please DELETE these first lines.

### Reproducible Bug Summary 

1. Replacing version 1.7 with 1.71

Having replaced the directories, the page is still telling me to upgrade to 1.71 and that I am still on 1.7.

### Technical details

* YOURLS version: 1.7.1
* PHP version:
* Any other useful information depending on context (server version, mysql version, browser version, OS version...)

**Comment by chtaube** [comment]
That report got closed as it's not an Yourls Issue. :)

Anyway, try restarting the webserver and/or PHP process. It could simply be a caching issue. Refreshing the webpage within the browser or clearing the browsers cache might help, too.

**Comment by ozh** [comment]
to be honest that report got closed because "SERIOUSLY CAN YOU PLEASE READ WHAT YOU POST ??" :)

**Comment by opsuk** [comment]
Thank you. Immensely helpful.

I posted a problem I do not know the answer to. If you can't help, then say so.

I won't bother you again as you clearly do not wish to help.

Jason 



m:      07974224475

e:       jason@ops.uk



This message is sent in confidence and for the attention of the addressee only. Unauthorised recipients are requested to preserve this confidentiality and to advise the sender immediately of any error in transmission. If you contact us by e-mail, we will store your name and address to facilitate communications. Whilst we have taken reasonable precautions to ensure that any attachment to this e-mail has been swept for viruses, we cannot accept liability for any damage sustained as a result of software viruses and would advise that you carry out your own virus checks before opening any attachment.

**Comment by phy25** [comment]
- PHP version:
- Any other useful information depending on context (server version, mysql version, browser version, OS version...)

If you don't post these info and just ignore the template's words, maybe nobody CAN help you at all.

**Comment by dgw** [comment]
The issue title is "Issue title -- be DESCRIPTIVE", after all. And a good chunk of the issue template was left blank, as @phy25 pointed out. If you don't even change the default issue title…
