### ISSUE TITLE
Encoding breaks firebase storage links

### ISSUE THREAD

**Issue by tomermes** [YOURLS/YOURLS#2153]
This is a sample firebase storage url:

https://firebasestorage.googleapis.com/v0/b/my-app-id.appspot.com/o/images%2F1472226525901.png?alt=media&token=24ae5256-514d-1126-7a00-f1ce822050ce

When shortened the url saved in the db is with "/" instead of %2F (after images token).
Firebase domain return 404 for those links.

**Comment by tomermes** [comment]
You can remove the encoding of the url in includes/functions.php, at the function "yourls_add_new_link".
Just remove the two rows which makes encodeURI and escape.

**Comment by dgw** [comment]
[Don't Hack Core](https://github.com/YOURLS/YOURLS/wiki/Dont-Hack-Core)!

This should be tweakable with a plugin, or perhaps YOURLS should not be decoding entities in URLs like this one.

**Comment by tomermes** [comment]
ok so fix needed

**Comment by LeoColomb** [comment]
X-Ref: #1303

**Comment by ozh** [comment]
Closing: 2691 and associated PR will supersede
