### ISSUE TITLE
Is it possible to add @ as a supported character?

### ISSUE THREAD

**Issue by adigitalife** [YOURLS/YOURLS#2155]
Some users want to use hyphens in their short URLs so I created a plugin to add it.  Now, some users want @ in their short URLs.  But adding it to the charset breaks YOURLS.  Short links can be create with @ in them but none of the short links work anymore (with or with @).

What's preventing @ from working?

**Comment by ozh** [comment]
Probably an encoding issue, maybe somewhere the `@` becomes a `%40`. Check how short URLs are stored (with a @ ?) and what YOURLS receives when requested a short URL, see https://github.com/YOURLS/YOURLS/blob/master/yourls-loader.php#L20-L21

**Comment by adigitalife** [comment]
Actually, simply adding @ to the charset already breaks the site.  No need to create any short links.  Here's how I reproduce the issue:

1) Add @ to function yourls_get_shorturl_charset() in includes/functions.php

`    if( defined('YOURLS_URL_CONVERT') && in_array( YOURLS_URL_CONVERT, array( 62, 64 ) ) ) {
        $charset = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ@';`

2) Try any existing short link.  Doesn't work.  Simply goes to the YOURLS home page.

3) Remove @ from function yourls_get_shorturl_charset(), site goes back to normal.

Other special characters are fine:

`$charset = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!-_.?#$';`

But as soon as I add @, all short links stop working.

**Comment by mdbuerkle** [comment]
As far as I remember, changing the charset also invalidates all short links that have been created until then - so "2) try an existing short link" will never work.
Anyhow, when chaning charset, You also have to change YOURLS_URL_CONVERT accordingly, i.e. it would be "63" with the "@" in Your case.
Did You try to add a new short link with the "@" in Your charset, then?

**Comment by adigitalife** [comment]
But why does 2) work if I use other special characters in 1)?  So...

1) Add one or more special characters (except @) to function yourls_get_shorturl_charset() in includes/functions.php

`if( defined('YOURLS_URL_CONVERT') && in_array( YOURLS_URL_CONVERT, array( 62, 64 ) ) ) { $charset = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!-_.?#$';`

2) Try any existing short link. They all work.

3) Create new short links with the added special characters.  They all still work.

But, as I said, once @ is added none of the short links work anymore.  So at least in my case, the only problem is really with @.

I'll try changing 62 to 63 when I can.  It may or may not work.  But the question still remains: Why does @ behave different than the other special characters?

**Comment by slabbint** [comment]
I would also like to add the @ character to the list of supported characters.

**Comment by TuKod** [comment]
[RFC 3986](http://www.faqs.org/rfcs/rfc3986.html) - Uniform Resource Identifier (URI): Generic Syntax

      reserved    = gen-delims / sub-delims

      gen-delims  = ":" / "/" / "?" / "#" / "[" / "]" / "@"

      sub-delims  = "!" / "$" / "&" / "'" / "(" / ")"
                  / "*" / "+" / "," / ";" / "="

Use any of the above "reserved" chars in the wrong place in your URL/URI and it will break.

So to use an @ you would have to **Lengthen** your URL by encoding the @ into %30

The dash (-) is not on the reserved list at this time (it was in the past).  The tilde (~) is also not on the reserved list at this time.  However, there is great wisdom in only using alphanumerics as these will **Never be reserved.**

In the lists above, "sub-delims" are likely to work in a YOURLS plugin, and "gen-delims" are very likely to fail.

Lan

**Comment by ozh** [comment]
If you want to use `@` in your short URL, this simple plugin will do:

```php
<?php
/*
Plugin Name: AT in Short URLs
Plugin URI: http://yourls.org/
Description: Allow AT symbol in short URLs (like <tt>http://sho.rt/bl@h</tt>)
Version: 1.0
Author: Ozh
Author URI: http://ozh.org/
*/

// No direct call
if( !defined( 'YOURLS_ABSPATH' ) ) die();

yourls_add_filter( 'get_shorturl_charset', 'ozh_at_in_charset' );
function ozh_at_in_charset( $in ) {
	return $in.'@';
}
```
