### ISSUE TITLE
Host Name Changed Fixed But URLs don't work

### ISSUE THREAD

**Issue by phillycodehound** [YOURLS/YOURLS#2156]
Hi

I have a url shortener at http://s3th.me/admin

http://s3th.me/freelanceunionprofile

If you go to the second domain name you'll see that I get a 404 but it's in the server and in the install. So I'm confused. Help please.

**Comment by phillycodehound** [comment]
The app even shortens new links but still don't resolve? Any ideas?

**Comment by ozh** [comment]
http://s3th.me/readme.html#FAQ
