### ISSUE TITLE
YOURLS on sub.domain.com

### ISSUE THREAD

**Issue by cchhh1** [YOURLS/YOURLS#2159]
Hi
Can i install YOURLS on subdomain?
In user/config.php i can set: `define( 'YOURLS_SITE', 'http://sub.domain.com' );`
How should i edit .htaccess file for "sub" folder to make it work?

**Comment by ozh** [comment]
This depends on your server configuration, this is not a YOURLS question. You should ask your server admin.

**Comment by cchhh1** [comment]
This is working for me
My .htcacces:
```
<IfModule mod_rewrite.c>
	RewriteEngine On
RewriteRule ^sub$ http://sub.domain.com [R=301,L]
</IfModule>

# BEGIN YOURLS
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^.*$ /yourls-loader.php [L]
</IfModule>
# END YOURLS

```

**Comment by cchhh1** [comment]
@ozh Can i edit "added to database" information? How to delete stats link?
![you1](https://cloud.githubusercontent.com/assets/22476214/19366803/c0836706-9198-11e6-8d64-c7dbea5cba1d.jpg)
