### ISSUE TITLE
using API - bug found

### ISSUE THREAD

**Issue by bizactuator** [YOURLS/YOURLS#2162]
* YOURLS version: v 1.7.1 – 9 queries
* PHP version:  5.6.27
* Any other useful information depending on context (server version, mysql version, browser version, OS version...)

### Reproducible Bug Summary 

1. Setup the API
2. Connect the API and then have it shorten a Long URL in this format:
http://somelink.com/affiliate.php?aff=23&pid=111

3. The url gets shortened, but the &pid=111 no matter what I put there, always falls off, nothing after the & sign. 

This is a bug because... if I go into the admin I can put long urls having that exact url:
http://somelink.com/affiliate.php?aff=23&pid=111
and it works fine, but having the API create it, does not work. it never passes anything past the &.
I had it put it like this:
http://somelink.com/affiliate.php?aff=23?pid=111
and that worked, so it put that whole thing in there, but that does not work because two ? marks make the second one absolete... when I put the & back as either just a & or &amp; it breaks both ways.

**Comment by dgw** [comment]
Sounds like the input isn't being urlencoded.

**Comment by bizactuator** [comment]
how do I encode the url then? what do you recommend?

**Comment by dgw** [comment]
Look for a url encoding function in whatever language you're using to call the API. Most have such a thing. Or for this specific case you can just string-replace '&' with '%26'.

**Comment by bizactuator** [comment]
ah ok. That worked. :) I just had it put this: 

  var affUrl = "[LinkCode]";
  var long1 = encodeURI(affUrl + "%26pid=170"); // Probably best to use ? instead of & here
  var long2 = encodeURI(affUrl + "%26pid=171");

then it built it right at the api. :) thank you!!

 I first tried it as:
  var affUrl = "[LinkCode]";
  var long1 = encodeURI(affUrl + "&pid=170"); // Probably best to use ? instead of & here
  var long2 = encodeURI(affUrl + "&pid=171");

But that encodeURI did not change the & to %26, so I did it manually, and tested it and it works. :)

Thank you!
