### ISSUE TITLE
The part of url after the hash (#) symbol is not present after following the shortened url

### ISSUE THREAD

**Issue by VitalyStakhov** [YOURLS/YOURLS#2164]
hi,

#2045 supposes to fix the issue, which I'm encountering in 1.7.1

In admin panel, shortening http://example.com/#example redirects to just http://example.com
In admin, original url is correct, however the shortened one misses the '#' and everything after it. Happens consistently for all urls with # in them, where the part of url after the '#' is removed.  Any ideas?

Thanks

**Comment by LeoColomb** [comment]
See #2142.
