### ISSUE TITLE
Create clickable tabs in YOURLS?

### ISSUE THREAD

**Issue by joshp23** [YOURLS/YOURLS#2165]
Running 1.7.1 on a fully updated Ubuntu 14.04 box... cannot seem to get clickable tabs on custom pages or plugin option pages to work. I've been coding in div's and doing what I normally would do in order to get this to work, but they always come out like a static menu tree. Looked all over for a solution... coming up empty.

How do I invoke clickable tabs on a custom page in YOURLS?

**Comment by joshp23** [comment]
I worked in tabs by manually calling 


	/css/infos.css?v=1.7.2"
	/js/infos.js?v=1.7.2"

to my plugin, is there a cleaner way to accomplish this?

**Comment by ozh** [comment]
What do you call a clickable tab? Is that something present in the YOURLS admin interface?

**Comment by joshp23** [comment]
Like the tabs in the stats page. Does this make sense?
