### ISSUE TITLE
Public shortened link statistic/info

### ISSUE THREAD

**Issue by skeith** [YOURLS/YOURLS#2168]
### Technical details

* YOURLS version: 1.7.1
* PHP version: 7.0
* Ubuntu 16.06, nginx

### Asking support question

While having this
```
<?php
define( 'YOURLS_PRIVATE', true );
```
How can we have a public shortened link statistic/info ?

**Comment by joshp23** [comment]
define('YOURLS_PRIVATE_INFOS', false);

**Comment by ozh** [comment]
Indeed. :pizza: @joshp23 :)

**Comment by skeith** [comment]
I am truly sorry for my ignorance of this page `https://yourls.org/#Config`

Please forgive me

**Comment by joshp23** [comment]
PIZZA!
