### ISSUE TITLE
Callback functions not invoked for failed JSONP API requests

### ISSUE THREAD

**Issue by neocotic** [YOURLS/YOURLS#2169]
The problem that I'm having is that when a JSONP request fails, YOURLS is setting the HTTP status code accordingly. Unfortunately, most browsers will not bother evaluating and processing JavaScript within the response body of a resource that failed to load, which makes sense really.

I think that it would be best that the API simply always returned HTTP status code 200 for all JSONP requests. Then it's the responsibility of the consumer to check the response for the `errorCode` etc.

**Comment by ozh** [comment]
So, regular HTTP error codes for standard API requests, but `200 OK` for all JSONP? Yes indeed. Makes sense.

**Comment by LeoColomb** [comment]
@neocotic No, it's absolutely not standard. If a server fail, it should answer with a 5xx, not with a 200 even for JSONP.
Your implementation should manage HTTP failures before parsing answer.
I'm also tempted to say that JSONP is about to dead (in general), as a [tricky way to bypass policies](https://en.wikipedia.org/wiki/JSONP).
