### ISSUE TITLE
Yourls Deceptive?

### ISSUE THREAD

**Issue by bizactuator** [YOURLS/YOURLS#2170]
I have the latest version of YOURLS, the latest STABLE PHP, and everything. My password is very secure, and somehow my YOURLS is now being blocked on every page load:

"Deceptive site ahead

Attackers on olink.us may trick you into doing something dangerous like installing software or revealing your personal information (for example, passwords, phone numbers, or credit cards)."

It is happening in chrome and firefox.

I don't see any problem. Why did that happen and not on my other domains with the same versions installed?

Is there something that happened?

Can you help me figure out what happened?

-Richard

**Comment by dgw** [comment]
Likely nothing to do with YOURLS. Google has flagged that domain as `SOCIAL_ENGINEERING`. See the Webmasters Help Center for steps to [get the flag removed](https://support.google.com/webmasters/answer/6350487?hl=en).
