### ISSUE TITLE
Addition of a reset clicks to zero button under Actions

### ISSUE THREAD

**Issue by jonnyrrr** [YOURLS/YOURLS#2171]
Apologies if I am not doing this correctly, this is not a bug report, but I could not find any reference to this request anywhere. 

Can a button under Actions be added that resets the clicks to zero so you do not have to manually edit the database to achieve this?

**Comment by ozh** [comment]
Short answer is: sure, basically anything is [possible with a plugin](https://github.com/YOURLS/YOURLS/wiki/Possible-With-A-Plugin)

In this case, you'd need a plugin that would hook a function right after the button are printed (see filter `'table_add_row_action_array'` in [functions-html.php](https://github.com/YOURLS/YOURLS/blob/master/includes/functions-html.php#L531)) and add your button in the mix that would trigger an ajax event and reset the counter.

A less convenient but easier way to code this would be to make a plugin that adds an admin page where you'd enter the link to reset, similar to plugin Mass Delete, for instance. See plugin list.
