### ISSUE TITLE
Missing index.php file

### ISSUE THREAD

**Issue by jaimecoj** [YOURLS/YOURLS#2174]
Hello. I'm using realease 1.7.1 and I saw it doesnt include a index.php in root folder. 

Is it not needed anymore?

I'm using nginx. It can not find the index file and throws error 403.

**Comment by gmolop** [comment]
Hi @jaimecoj 
It's in the [FAQ](http://yourls.org/#FAQ)

> **There is no index page at the root of the install**  
>  
> - Indeed. It's intented. It's up to the user to make what they need. Some will redirect the root to a different place, some make a public interface for anyone to shorten links, some make a portfolio. You make it.  
> - If you want to make a public interface and run your own little bitly.com, there's a sample file provided as an example: `sample-public-front-page.txt.` This implies important issues to deal with: spam, performance and security. Read [Public Shortening](http://yourls.org/public) for important information.
