### ISSUE TITLE
Create own CSS

### ISSUE THREAD

**Issue by wefixit-AT** [YOURLS/YOURLS#2175]
### Technical details

* YOURLS version: 1.7.2
* PHP version: 5.5.21

What are the right way to add own CSS style?
It seems that the article in the wiki is not up-to-date: https://github.com/YOURLS/YOURLS/wiki/Style

**Comment by ozh** [comment]
Actually this wiki page relates to a future version of YOURLS. I added this missing information.

A good way to currently do this is to hook into one of the actions of function `yourls_html_head()` ([here](https://github.com/YOURLS/YOURLS/blob/master/includes/functions-html.php#L26-L133)) and echo your inline CSS or `<script src="some file"></script>`

Eg, in a plugin:
```
yourls_add_action('html_head', 'my_own_css');
function my_own_css(){
    // print some CSS
}
```

**Comment by scriptgeni** [comment]
I've created a simple plugin for this.
[yourls-custom-header-footer](https://github.com/scriptgeni/yourls-custom-header-footer)

**Comment by ozh** [comment]
@scriptgeni nice, added to the plugin list. Thanks!

**Comment by julienth37** [comment]
@ozh hope people will not do inline css (modern website must don't have inline css)

**Comment by scriptgeni** [comment]
@julienth37 As you might know, every Wordpress theme has Custom CSS option, this is just a simple plugin to overwrite the Yourls default CSS if you want to have some different styling.
