### ISSUE TITLE
How to realize some interesting selections?

### ISSUE THREAD

**Issue by seventhsite** [YOURLS/YOURLS#2178]
Hello!
I want to know more about users of my public YOURLs site. For example: 
- what IP was created more URLs than others.
- How often (average) new URLs creating
- maybe with graph about days of week and hours of new creatings.
And other interesting selections.
What is the easiest way to see it for me (if it is possible without coding)?

**Comment by ozh** [comment]
Not possible without coding. You need to craft custom SQL queries, fetch data from the DB and figure how you want to display it.

You could have a peek to the mass delete plugin if you want something to code from.
