### ISSUE TITLE
Disappearing urls

### ISSUE THREAD

**Issue by westcoast2016** [YOURLS/YOURLS#2179]
This has happened many times over the few years I've used this plugin, periodically urls just stop working.

I've looked around the forums to figure out if it's a known issue and I can't find anything.

Does anyone know why they would just be deleted without my doing so? I remake them when I see an issue, but I have 870 urls now, (there was more) so I'm sure I've missed a bunch and link around the net will not work.

**Comment by LeoColomb** [comment]
This issue has no reproducible steps. Please re-open this issue if it still occurs, with reproducible steps and system details. Check this element's [Contributing Guidelines](CONTRIBUTING.md) for an example.

**Comment by Davidiborra** [comment]
Hi guys, 

I have the same issue with urls that randomly disappear from the list. Our db is not big on 10 - 15 urls 20k clicks  and and every now and then urls stop working, when we go to the admin panel the shortened url is not on the list. Have anyone experienced this issue?


Thanks

**Comment by ozh** [comment]
This problem is external to YOURLS and you should check with how your DB is updated (is there some slave/master setup or load balancing? is there a DB cache layer or something like this outside of YOURLS? etc...)

Out of the box, YOURLS just reads and writes the DB blindly on each request.
