### ISSUE TITLE
The right way to go to HTTPS

### ISSUE THREAD

**Issue by seventhsite** [YOURLS/YOURLS#2180]
### Technical details

* YOURLS version: 2.0
* PHP version: 7.0.14-2+deb.sury.org~trusty+1

I want site, that worked by http and https. But short links must be with http (like bit.ly)
I just register SSL-certificate and create new apache config file. So, now my site working over http and https. But over https browser don't load two files (because it loading over http):

- theme.css
- style.css

And I can't find where I can chang they way from absolute to relative. Or, may be, there is another right way for https?

**Comment by ozh** [comment]
You want everything to be on HTTPS, except redirections that should be on HTTP ?

**Comment by seventhsite** [comment]
I think yes. (I don't know how to do in right way, but I scared about news of google chrome and untrasted sites)

**Comment by ozh** [comment]
Then why don't you just put everything on HTTPS ? On a trust level, that is really the best thing to do.

**Comment by seventhsite** [comment]
Because short links will be longer for one character)
Not untrusted, but insecure. News says about Firefox and Chrome, that they will warn about insecure pages with form fields.

**Comment by ozh** [comment]
Chrome will warn about pages with login fields that are not on HTTPS, yes. Regarding redirection links not being on HTTPS, I think that's a moot point, really.

If you want to achieve this, configure everything on https (ie set `YOURLS_SITE` to `https://yoursite`) and just use `http` link for redirections when you publicize your links. Simple. Like https://yourls.org/admin/ (https) but http://yourls.org/ds (http)
