### ISSUE TITLE
How to Restart keyword count? And other related questions

### ISSUE THREAD

**Issue by thbmatrix** [YOURLS/YOURLS#2184]
Hello,

I want a little help of you experienced guys.

I've created a couple of entries, just to test software's behavior LOL. Then I deleted some and seen that the count for keyword was starting in a letter, not in a number anymore. So I cleaned up the whole database, as I had no data. Well, didn't work. 

So, question (1): How do I make it start from the 0 (or 1, IDK) again?

Another question (the first related) is: (2) why is keyword not unique/indexed in the database? Would it be any harmful if I make it unique?

And finally, last question (3): Is there any way to prevent, if I create a 'public page', that users create links with keywords lesser than 'N' characters, and restrict them for my own use?

Thanks for your attention.

Best Regards,
[Bruno Moreira-Guedes](http://bruno.today/)

**Comment by ozh** [comment]
1) manually reset `options.next_id` in the database

2) I think [it is](https://github.com/YOURLS/YOURLS/blob/1.7.1/includes/functions-install.php#L222)

3) There's a way to do everything with a plugin. See https://github.com/YOURLS/YOURLS/wiki/Possible-With-A-Plugin
