### ISSUE TITLE
[Feature Request] Password protecting redirects & Redirects which expire

### ISSUE THREAD

**Issue by GhostCyborg** [YOURLS/YOURLS#2185]
**Hello**, wanted to give a possible feature request:

It would be nice to be able to password protect short URLs. Meaning users would be able to create a short URL and as an extra optional option they could enter a password, and when people try to access the short URL they would be prompted to enter a password before they can be redirect. Another feature which would be awesome to see in the future, would be the ability to create a short URL which expires after **X** amount of time. Couldn't find another feature request suggesting this, so I decided to make my own, please do correct me if i'm wrong.
Thanks, **GhostCyborg**

**Comment by ozh** [comment]
This is typically plugin territory. See the plugin list.

**Comment by GhostCyborg** [comment]
@ozh There isn't any plugin which do any of the things I mentioned..

**Comment by ozh** [comment]
Hence the very first link of the plugin list
