### ISSUE TITLE
yourls_allow_duplicate_longurls where to set it to allow

### ISSUE THREAD

**Issue by bizactuator** [YOURLS/YOURLS#2186]
I have spent like 3 hours searching the web, I know I've seen it somewhere.
But I cannot find it.

The links to the old pages that talked about it are not there anymore.

Can someone point me to where I can see how to allow duplicate long yourls?

### Technical details

* YOURLS version:  v 1.7.1
* PHP version: 5.6.28

**Comment by gmolop** [comment]
File: `user/config-sample.php`

`/** Allow multiple short URLs for a same long URL`
` ** Set to true to have only one pair of shortURL/longURL (default YOURLS behavior)`
` ** Set to false to allow multiple short URLs pointing to the same long URL (bit.ly behavior) */`
`define( 'YOURLS_UNIQUE_URLS', true );`

Set it to `false`.

**Comment by LeoColomb** [comment]
Thanks @gmolop! 👌
