### ISSUE TITLE
Historical click - request to add it to the API

### ISSUE THREAD

**Issue by tonysms** [YOURLS/YOURLS#2187]
This is not a bug, but a feature request.

The current API ( action=url-stats) returns only the total number of the clicks for a specific url. There is no way to get the history for the clicks from the API at the moment.

Is it possible to add an API call to get the historical clicks data for a specific url? It would be very useful for native representation of the history dashboard.

**Comment by LeoColomb** [comment]
It should be possible with a plugin.
Have you see the [plugin example](https://github.com/YOURLS/API-action)? You can find some concrete implementations in the [plugin list](https://github.com/YOURLS/YOURLS/wiki/Plugin-List#api-action).

**Comment by shovanuk** [comment]
Hi, using the API How can I get URL stats only for the month of may? 

This is the code I am using right now that retrieves overall click number
`=IMPORTXML("http://website.org/yourls-api.php?action=url-stats&format=xml&signature=XXX&shorturl=" & C11,"result/link/clicks")`

Thanks

**Comment by ozh** [comment]
@shovanuk same answer as above: you need to make a custom API action plugin.
