### ISSUE TITLE
Question about redirect functions

### ISSUE THREAD

**Issue by DatDraggy** [YOURLS/YOURLS#2188]
So this isn't really a bug or something like this but I hope I still get a reply.

I am trying to make a plugin that changes the redirect to a meta refresh one instead of 301 if the URL belongs to youtube.

```
yourls_add_action( 'pre_redirect', 'no_preview_func');

function no_preview_func( $location, $code = 301 ) {
	
	if(substr($location, 0, 23) == "https://www.youtube.com" || substr($location, 0, 16) == "https://youtu.be" ){
		$location = $location[0];
		return '<meta name="description" content="' . $location . '" />
				<meta property="og:title" content="Youtube" />
				<meta property="og:description" content="' . $location . '" />
				<meta http-equiv="refresh" content="1;URL=' . $location . '">';
	}
	else{
		yourls_do_action( 'pre_redirect', $location, $code );
		$location = yourls_apply_filter( 'redirect_location', $location, $code );
		$code     = yourls_apply_filter( 'redirect_code', $code, $location );
		// Redirect, either properly if possible, or via Javascript otherwise
		if( !headers_sent() ) {
			yourls_status_header( $code );
			header( "Location: $location" );
		} else {
			yourls_redirect_javascript( $location );
		}
	}
	die;
}
```

How does the pre_redirect work and where is the difference between "yourls_add_action" and "yourls_do_action"?

I'm having trouble with understanding in what order and even how the pre_redirect works. Even if this plugin is enabled the status code is still 301. Is there any way to remove the status code and output the html (meta stuff) with a code 200?

Also, when I enable the plugin, I get a "too many redirects" error. Any body know why?

I'm so lost lmao

Currently, I have this hardcoded in functions.php on line 683 and it works totally fine but I can't really tell users that want this plugin to fuck up their functions. 
https://puu.sh/twSJo/50948e69bd.png
Btw, ownlib_left is the same as the substring in my plugin

**Comment by LeoColomb** [comment]
See plugin [302-instead](https://github.com/EpicPilgrim/302-instead/blob/master/plugin.php) as an example.
Your "meta stuff" seems very awkward... and may not work or may throw errors. Do you really need it?

> hardcoded in functions.php on line 683

[...](https://github.com/YOURLS/YOURLS/wiki/Dont-Hack-Core)

**Comment by DatDraggy** [comment]
No 302 does not what I want and didnt really help with my problem either. Its still code 301 and not an html redirect andthat means Applications like telegram will still show the big ass video preview that i dont want.

**Comment by tinjaw** [comment]
> Alright... Fixed it after hours of confusion

@DatDraggy Did you publish your plugin?
