### ISSUE TITLE
Different Install URL and Short Link Base URL

### ISSUE THREAD

**Issue by vacquah** [YOURLS/YOURLS#2193]
I have installed Yourls in a subdomain so my config looks like this :

`define( 'YOURLS_SITE', 'http://sub.domain.com' );`

However,  this is not my preferred short link base url. I'd like it to be simply domain.com.

I can't tell if this is not a supported feature or not. Seems wherever you install yourls thats your base short link url?   Perhaps its the same issue referred to over here [https://github.com/YOURLS/YOURLS/pull/2063](url)

**Comment by ozh** [comment]
Out of the box, it isn't the behavior. However I think there's a plugin for that.
