### ISSUE TITLE
links are deleted from database

### ISSUE THREAD

**Issue by vinso** [YOURLS/YOURLS#2194]
Hello 

i Use yourls for few month . I have updated it 2 days ago but the probelm is still there.

My problem is that the short link i have created , are deleted from my yourls and from the database too , but i have not done anything i dont want them to be deleted.

So it looks like .

Day 1 - Overall, tracking 100 links, 

Day 2 - Overall, tracking 88 links, 

Day 3 - Overall, tracking 82 links, 

Any help ? thank you

**Comment by LeoColomb** [comment]
This issue has no reproducible steps. Please re-open this issue if it still occurs, with reproducible steps and system details. Check this element's [Contributing Guidelines](https://github.com/YOURLS/YOURLS/blob/master/CONTRIBUTING.md) for an example.
