### ISSUE TITLE
How to convert the site to HTTPS

### ISSUE THREAD

**Issue by Xeng677** [YOURLS/YOURLS#2195]
I just want to know how to change the site to use https rather than http. 

I have the site running on http, but want it to be more secure.... 

Thanks for the help!

Lane

**Comment by LeoColomb** [comment]
Just change your [`YOURLS_SITE`](https://yourls.org/#Config) settings to `https://your.domain`.
Obviously, that suppose a certificate has been added and configured by your host.

**Comment by ddaddy** [comment]
I've changed my site to `https://` in the config and when I use the API I get a valid `https://` shortened address back, however the address it redirects to is `http://`. What could be the problem? Am I missing another setting somewhere?

**Comment by ddaddy** [comment]
I can also see in the admin page that the original links are `http://`. How can I make them use `https://`?
Thank you.

**Comment by Xeng677** [comment]
I came across this. Any url you shorten  with have to be redone. As the
default is http. There is a ssl module to install with converts https to
https short links.... with out the.module, you will always get http short
links...

Make sure to re direct the default http site to https. Just makes thing
easier...

**Comment by ddaddy** [comment]
Thanks. I'm not too worried about old links, I just need new ones as https.
So your saying I need a module to enable https links? any idea what it is or where it is?

I have redirected my http site to https.

Thanks for the help.

**Comment by Xeng677** [comment]
Yup it is a free plug, which you download from the.link on the admin site
plugins page... near the bottom if I remember. Download it, upload to
server plugin folder and use the admin page to enable it. And you are done.
