### ISSUE TITLE
Empty response from API when using format=json for some concrete URL

### ISSUE THREAD

**Issue by p1ratrulezzz** [YOURLS/YOURLS#2198]
### Technical details

* YOURLS version: 1.7.2
* PHP version: 7.0

### Reproducible Bug Summary 

1. Sending POST request to API with format=json and url=https://www.socialit.ru/vopros-otvet/vopros-otvet_467.html
2. Got empty response
3. If format=xml, result is ok

The RAW POST request
```
POST /yourls-api.php HTTP/1.1
HOST: zhmak.nu
content-type: application/x-www-form-urlencoded
cookie: __cfduid=d5922607b9b50da1909aad0dcdf22bda51486561505
content-length: 111

signature=123456&url=https://www.socialit.ru/vopros-otvet/vopros-otvet_467.html&action=shorturl&format=json
```

got empty response here

though same for github.com is OK
```
POST /yourls-api.php HTTP/1.1
HOST: zhmak.nu
content-type: application/x-www-form-urlencoded
cookie: __cfduid=d5922607b9b50da1909aad0dcdf22bda51486561505
content-length: 71

signature=123456&url=https://github.com&action=shorturl&format=json
```

got normal response

```
{
"url": {
"keyword": "ZW6SQ",
"url": "https://github.com",
"title": "How people build software · GitHub",
"date": "2017-02-08 14:13:30",
"ip": "4*.*.*.*"
},
"status": "success",
"message": "https://github.com added to database",
"title": "How people build software · GitHub",
"shorturl": "https://zhmak.nu/ZW6SQ",
"statusCode": 200
}
```

**Comment by ozh** [comment]
Indeed. No idea why. The whole socialit.ru domain acts like this.

**Comment by ozh** [comment]
Spent some time again on this issue. This time the issue seems opposite with socialit.ru : XML returns null while JSON returns an object. No clue.

**Comment by ozh** [comment]
Closing, as this is, it seems, very specific to that web server and not a generic YOURLS defect.

Would love to understand the problem, though :)
