### ISSUE TITLE
Blank page on redirect

### ISSUE THREAD

**Issue by francescolia** [YOURLS/YOURLS#2201]
I repeat question because on Code Google there isn't anymore the copy of issue because google deleted it and all the project data.

I can use admin without any problem but when i call the shorten url i got a blank page.

Server New. Debian + Php + Mysql.

### Technical details

* YOURLS version: 1.7.1
* PHP version: 7.1 and 5.6 (tried both)
* Any other useful information depending on context (server version, mysql version, browser version, OS version...)

**Comment by francescolia** [comment]
Ok simply resolved. It was an upgrade of 1.5. I simply removed all old files and done a clean install with old mysql. It works.

**Comment by francescolia** [comment]
But if you restore the Blank Page Issue that is not more on Google Code will be better to all.

**Comment by LeoColomb** [comment]
Yes, we know, but I'm not sure there is a recovery option... 😸
