### ISSUE TITLE
How to block google from indexing yourl?

### ISSUE THREAD

**Issue by Ruriko** [YOURLS/YOURLS#2202]
How do I make search engines not to index any yourl links?

**Comment by TuKod** [comment]
Why would you want to?

By allowing Search Engines to crawl your YOURLS site, will transfer link juice from the short url to the long one.

To prevent honest Search Engines from crawling your whole site, or even one URL, you could use robots.txt (Google robots.txt for info).

Regards,

Lan

**Comment by ozh** [comment]
YOURLS links are not "indexed". If Googlebot finds a YOURLS link, eg a page somewhere or a tweet contains http://sho.rt/blah, Googlebot will *follow* it and, if allowed by the destination, index and archive the destination page.

YOURLS links are only redirects, they are not indexed by Google.

If your question is "how do I prevent Google from following YOURLS links", answer is "make a custom plugin that checks user agent before redirection to prevent googlebot from being redirected"

**Comment by Sushubh** [comment]
Just wanted to mention here that Google is indexing yourls short links for me. 

https://www.google.co.in/search?q=site%3At.broadbandforum.co

I added robots.txt file few days ago but it only seems to prevent indexing of content (on some links but not all at the moment) but the links still make it to Google search results. 

Google suggest adding <meta name="robots" content="noindex" /> to meta tags which is not applicable in case of redirected links. The other option is the X-Robots-Tag HTTP header... implementation of which is outside my area of expertise. Just wanted to post this here in case some developer would consider making a plugin that can do this? 

This is not that big of a deal for me except that it seems to pollute the site search results for my domain as I am using the same domain (subdomain) for YOURLS. I am not sure if it is hurting my site's ranking/authority in Google's eyes as these links end up redirecting to other domains :) Cheers.

**Comment by ozh** [comment]
Indeed. I think Googlebot has changed behavior over past years.

Quick research makes me think too we may add PHP header `header("X-Robots-Tag: noindex", true);` to every redirection page but I'm not sure it's not outdated.

**Comment by Sushubh** [comment]
https://developers.google.com/search/reference/robots_meta_tag does not indicate that these are deprecated.

**Comment by ozh** [comment]
People monitoring this issue : YOURLS 1.9.2 (soon) will address this issue with a filter allowing you to use a plugin and fine tune the SEO behavior you'll like. See #3517 for more info.

**Comment by richn** [comment]
I would like to filter known bots from the click statistic / analytics.
Social Media pages (i.e. YouTube) will follow the link each time it is posted in a content piece (I guess for security reasons).
That might give you large numbers of bot clicks in the stat.

**Comment by dgw** [comment]
@richn Click logs are an entirely separate concern from search-engine indexing. Please consult [the Awesome list](https://github.com/YOURLS/awesome#d), in particular the plugins whose names start with "Don't Log". (Some customizations or updates might be needed to make sure a given plugin excludes the bots you want to exclude, but the foundation is there for you to build on.)
