### ISSUE TITLE
How to add Open Graph meta tags?

### ISSUE THREAD

**Issue by adigitalife** [YOURLS/YOURLS#2203]
I'd like to add Open Graph meta tags to YOURLS headers.  Something like:

`<meta property='og:title' content='URL Shortener' />`

I was thinking to make a plugin to do this but I'm not sure exactly how.  Any ideas?

**Comment by ozh** [comment]
That's a HTML tag. A YOURLS redirect doesn't output any HTML, it just sends a location header
