### ISSUE TITLE
Trying to login, but just says please login

### ISSUE THREAD

**Issue by joekinguk** [YOURLS/YOURLS#2205]
### Technical details

* YOURLS version:  v 1.7.1
* PHP version: 5.4.45
* Any other useful information depending on context (server version, mysql version, browser version, OS version...)

When I try to login with correct username and password it just resets and says please login instweead of logging me in.

When I try with wrong password it says invalid username or password.

Anyone know how I can fix this.

And is there a reset password feature?

UPDATE: The above is using Chrome, but I managed to login using Firefox. Hope this helps someone else experiencing this issue.

**Comment by LeoColomb** [comment]
There are a a lot of issues already dealing with that topic. Please [search](https://github.com/YOURLS/YOURLS/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20login).

It might be a wrong server or YOURLS configuration.
