### ISSUE TITLE
yourls_sanitize_url_safe() breaks redirect after admin login

### ISSUE THREAD

**Issue by dawolf** [YOURLS/YOURLS#2206]
### Technical details

* YOURLS version: 1.7.2
* PHP version: 5.6

### Reproducible Bug Summary 

1. Install YOURLS
2. Visit /admin Login page
3. Enter valid credentials
4. Browser is redirected to http://admin/? instead of going to http://YOURDOMAIN/admin

Expected behaviour: Show YOURLS admin page.

Cause: This change is responsible for the problem: https://github.com/YOURLS/YOURLS/commit/6748ce8a947e38e5b411ca6729967aa47b3fae9f#diff-de33dce122935846f969c7ff08091a8e

Replacing yourls_redirect( yourls_sanitize_url_safe($url) ); with yourls_redirect( $url ); fixes the problem.

**Comment by tsfoer** [comment]
Thanks for the hint, this drove me nuts!

**Comment by LeoColomb** [comment]
Ref: #2056
