### ISSUE TITLE
URL masking

### ISSUE THREAD

**Issue by rejoicing** [YOURLS/YOURLS#2207]
Before any bug report:
- [ ] Check you are using the **LATEST** release or the development branch.
- [ ] Make sure you have **SEARCHED** closed issues first. 
- [ ] Read the **GUIDELINES** linked in the yellow notice box above.
- [ ] **COMPLETE** this issue template.
- [ ] **DELETE** these first lines.

Thanks you!

### Technical details

* YOURLS version:
* PHP version:
* Any other useful information depending on context (server version, mysql version, browser version, OS version...)

### Reproducible Bug Summary 

1. This is the first step 
2. second step
3. etc... _METHODOLOGY_

This is a bug because... _DESCRIPTION_

**Comment by rejoicing** [comment]
Can Yourls mask the short URL so that the URL does not change in the address bar once the redirect is completed? If not, can you add this change? Thank you.

**Comment by dgw** [comment]
Probably possible with a plugin, but not likely to be added in core.

**Comment by ozh** [comment]
&uparrow; this.
