### ISSUE TITLE
404 logging

### ISSUE THREAD

**Issue by sirtet** [YOURLS/YOURLS#2208]
I lately found out that i had forgotten (or deleted?) some shortlinks that i announced on some print mediums... Bummer.

Now i thought that there could be some option/plugin to help with/against this:

If all 404's were logged, and above a certain treshold an alert (like a mail or so) would happen, one could see that there's something wrong, multiple people trying to access a non-existing shortlink...

Maybe it could also be distinguished between no-longer- and never-did-exist- links, for users who delete links after some time and don't want alerts about that.

Actually, after writing this here, and not being sure if the idea makes sense, i remember, that my site, made with drupal, has such a 404-logging module. So, that's probably not such a far-fledged idea...

**Comment by ozh** [comment]
You can log 404, see plugin list, I don't think there's something exactly like this right now but you may find something to hack on.

Now, the simple option is just to *create* those missing shortlinks....

**Comment by sirtet** [comment]
> Now, the simple option is just to create those missing shortlinks....

Right, that's the easy part, but only after you realized you have to ;-)

**Comment by sirtet** [comment]
Hmm, can't find any plugin about 404-logging...

I did read through all plugins, and i noticed there are some duplications. eg. __Advanced Reserved URLs__
and some dead, eg. __Piwik Stats__
