### ISSUE TITLE
accessibility: issues with screen readers on the admin dashboard

### ISSUE THREAD

**Issue by lilmike** [YOURLS/YOURLS#2209]
### Technical details

* YOURLS version: 1.7.1
* PHP version: 7.1.2
* Any other useful information depending on context (server version, mysql version, browser version, OS version...) Windows 7, Firefox, Jaws for windows (tested).

### Reproducible Bug Summary 

1. Load a screen reader (I used jaws for windows, as that's my screen reader I use -- there is a demo available).
2. Browse to yoursite/admin, and log in if necessary.
3. Try to navigate the table. You may notice the screen reader jumping around the contents seemingly randomly.

This is a bug because... It makes it very difficult to view the entire table of links (and possibly other items).

**Comment by LeoColomb** [comment]
Thanks a lot for filing this issue too! You're right, there is a room for improvements regarding accessibility.

Would you like to write a patch for this? We'd be more than happy to walk you through the steps involved. :rocket:

**Comment by lilmike** [comment]
I would be happy to write a patch given the steps. I believe the actions issue, as stated, is a CSS issue, so should be pretty easy to fix.
Michael.

Sent from my iPhone

On Mar 13, 2017, at 3:42 AM, Léo Colombaro <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks a lot for filing this issue too! You're right, there is a room for improvements regarding accessibility.

Would you like to write a patch for this? We'd be more than happy to walk you through the steps involved. 🚀

**Comment by ozh** [comment]
Closing in favor of PR you opened
