### ISSUE TITLE
action links are (mostly) hidden from screen readers

### ISSUE THREAD

**Issue by lilmike** [YOURLS/YOURLS#2210]
### Technical details

* YOURLS version: 1.7.1
* PHP version: 7.1.2
* Any other useful information depending on context (server version, mysql version, browser version, OS version...): jaws for windows (and NVDA) tested, Firefox, Windows 7.

### Reproducible Bug Summary 

1. Turn on your screen reader of choice.
2. Navigate to yourdomain/admin, and log in if necessary.
3. First, look at the actions column of the links table on the dashboard. You will find (mostly) that the screen reader sees it as blank.
4. Try the same on the plugin page. Again, actions columns seem blank.
5. Repeat steps 3 and 4, except with css toggled off (with an addon like disable css for firefox, etc). You will notice the page, though ugly (and cluttered to a screen reader as well), shows all the action links to the screen reader.

This is a bug because... Screen readers need to be able to see the links without turning off css.

**Comment by LeoColomb** [comment]
Hi @lilmike, thanks a lot for filing this issue!
I'm merging this issue with the other #2209 that you opened, as a global accessibility-on-YOURLS issue.
