### ISSUE TITLE
Order and pagination

### ISSUE THREAD

**Issue by lupa18** [YOURLS/YOURLS#2212]
### Technical details

* YOURLS version: 1.7.1
* PHP version: 7.1.2

### Reproducible Bug Summary 

1. Have a listing of more than 15 urls 
2. Clic on "clics" column for sorting that criteria
3. The result is that only order first page

This is a bug because I expected that order all list, and not only the first page, doesn't?

**Comment by ozh** [comment]
The quick sorting is applied to the current screen. To sort all results, you'll want to fiddle with the search parameters down the table (ie "order by clicks" for instance, default being by date)
