### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by girlsapink** [YOURLS/YOURLS#2214]
### Technical details

* YOURLS version: 1.7.1
* PHP version: 5.6

I completed the creation of YOURLS up to the short address after the installation was completed.
However, if you connect to the newly created short address, 500 Internal Server Error output will not work. Is there a solution?

**Comment by ozh** [comment]
Check server logs. Check wiki page Troubleshooting First Step. Definitely not a YOURLS defect, this is some misconfiguration on your end.
