### ISSUE TITLE
Does not work on Chrome Stable - Random blank pages

### ISSUE THREAD

**Issue by dylanh724** [YOURLS/YOURLS#2215]
For example, on **56.0.2924.87 (64-bit)** (and earlier versions), whenever you edit a link, the screen just goes white when attempting to edit (there's something blocking the code?).

Seems to work fine on Firefox

**Comment by ozh** [comment]
Chrome 56.0.2924.87 on 64 bit here. Works for me.

**Comment by dylanh724** [comment]
So if it doesn't work for you, close it? Don't want others seeing all the yourl issues eh

**Comment by dgw** [comment]
It works for me, too. Possibly a Chrome extension conflict?

**Comment by ozh** [comment]
@dylanh724 if it works for me, based on your report, how do you think I can help? If it works for me, I assume there's something particular on your setup that fails the whole thing. That being much more likely that something on *my* setup makes it work while others would fail.

So, my estimate is that it's not a YOURLS defect but a user config error. Not being that particular user and not having additional info, I don't see what bug I can fix. Feel free to add additional info that might tend to prove there's a bug to fix, or feel free to keep complaining that no one helps. Up to you.
