### ISSUE TITLE
Logging in HTTP should get you logged in HTTPS and vice versa

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#2218]
Currently I think logging in on http://sho.rt/ doesn't log you on https://sho.rt/ and the other way round. This is dumb, right?

Additional thoughts: ideally we could find a way to check if HTTPS is available (make a request on https://sho.rt/ and check the result?) and redirect the login form to HTTPS, but I'm not sure this would be reliable

**Comment by ozh** [comment]
Slightly more complicated that this:
- when logging in on HTTPS, we're not logged on HTTP and cannot log on HTTP
- when logging in on HTTP, we're logged on HTTPS. But then accessing via HTTPS unlogs on HTTP

**Comment by gmolop** [comment]
Hi there, I think it's not dumb at all, and in fact, I like the way it's right now. Keep normal and secure session access shared could cause a security breach ¿?

But if I think it more deeply, If I don't have ssl on my site, then it does not matter, all traffic will go unsecure, but if I have, why I would allow to access admin area without it? 
Just force https to (at least) admin zone in htaccess and keep (optionally) short link access to be available at both protocols.

Don't see the point to share really, maybe I'm missing something that this behaviour could be helpful without compromise the session.

**Comment by ozh** [comment]
This all boils down to the fact that we currently store the auth cookie with setting the secure flag if on SSL, and that we re-store that cookie on each successful logging (cookie can be created on HTTP, then updated on HTTPS, making it unreadable back on HTTP)

I see 2 solutions:
- dont re-store cookie on each successful logging
- store with secure flag only if `yourls_needs_ssl()`, not just `yourls_is_ssl()`

We could also update `yourls_needs_ssl()` : not only checking for const `YOURLS_ADMIN_SSL` but also checking if `YOURLS_SITE` simply begins with `https://` instead of `http://`

**Comment by ozh** [comment]
@gmolop yeah eventually I think you're right. If the user can access via HTTPS, chances are they'll stick on HTTPS. I just came across that minor annoyance while testing stuff.
