### ISSUE TITLE
admin page pre-populate "Custom short URL" field?

### ISSUE THREAD

**Issue by atomarch** [YOURLS/YOURLS#2220]
* YOURLS version: 1.7.1

Is there a way to have the "Custom short URL" field pre-populated when the admin page loads? I don't see any hooks/filters for this in the documentation.

I see in includes/functions-html.php that the yourls_html_addnew() function accepts two parameters:

function yourls_html_addnew( $url = '', $keyword = '' ) {

however, admin/index.php calls it without any arguments "yourls_html_addnew();" and that appears to be the only place in core where this function is called.  Per the instructions, I don't want to hack core ;)

Reason behind this request..... If a user is logged into the admin page, and later they enter a short URL that isn't in the database, to have it pre-populate that value into the "Custom short URL" field as a convenience so they can create a new entry.

Thanks!

**Comment by dgw** [comment]
> If a user is logged into the admin page, and later they enter a short URL that isn't in the database, to have it pre-populate that value into the "Custom short URL" field

What value? I'm not sure I understand where the pre-populated value would come from.

**Comment by ozh** [comment]
The way I would do it currently would be to hook into html_head or something like this and inject Javascript that would change the default value

**Comment by atomarch** [comment]
@dgw I'm referring to $keyword.  In the function there is code that allows you to set the value:

<strong><?php yourls_e('Custom short URL'); ?></strong>:<input type="text" id="add-keyword" name="keyword" value="<?php echo $keyword; ?>

However, nothing in core ever actually calls yourls_html_addnew() with any parameters.

@ozh thank you, I'll play around with this!  I was just thinking the loader_failed hook might also be helpful here...

**Comment by atomarch** [comment]
I think I'm 99% there...it's working with the exception of one small thing - the value is populated, but after a split second, the text field is emptied.  Any thoughts as to why this is happening would be appreciated!

1. User goes to myurl.com/does_not_exist , which triggers the redirect_keyword_not_found action
2. User is redirected to myurl.com/admin/?keyword=does_not_exist
3. Per @ozh suggestion, I use javascript to take value of keyword and insert into the add-keyword text field (i.e. "Custom short URL" field)
4. With javascript debugger turned on, I can see the text box does successfully get populated with "does_not_exist", however, later it is getting cleared out.  It appears this is happening in jquery-1.9.1.min.js .....I have no idea why......

My Code:

yourls_add_action( 'redirect_keyword_not_found' , 'atomarch_test' );

function atomarch_test($request) {
 yourls_redirect( yourls_admin_url() . "?keyword=" . $request[0] );
}

yourls_add_action( 'html_addnew' , 'atomarch_fill_keyword' );

function atomarch_fill_keyword() {

 if( isset($_GET['keyword']) && $_GET['keyword']) {
       // with javascript debug enabled
        echo "<script> debugger; document.getElementById('add-keyword').value='" . $_GET['keyword'] . "'; </script>" ;
 }
}

**Comment by atomarch** [comment]
Got it working.  Had to use jQuery to set the value and not document.getElementById.value:

yourls_add_action( 'redirect_keyword_not_found' , 'atomarch_test' );
function atomarch_test($request) {
 yourls_redirect( yourls_admin_url() . "?keyword=" . $request[0] );
}

yourls_add_action( 'html_addnew' , 'atomarch_fill_keyword' );

function atomarch_fill_keyword() {

 if( isset($_GET['keyword']) && $_GET['keyword']) {
    echo "<script> \$(function() { \$( \"#add-keyword\" ).val(\"" . $_GET['keyword'] . "\"); }); </script>";
 }
}

Thank you for the guidance!

**Comment by ozh** [comment]
Neat. I'm sure if you'd make a little public plugin on a github repo, people with similar needs would benefit from it :)

**Comment by atomarch** [comment]
@ozh , I did :) Here is the link:

https://github.com/8thwall/keyword-not-found-set-field-yourls

Thanks!

**Comment by ozh** [comment]
@atomarch added to the plugin list, thanks!
