### ISSUE TITLE
Wrong time on statistics graph

### ISSUE THREAD

**Issue by seventhsite** [YOURLS/YOURLS#2221]
### Technical details

* YOURLS version: 2.0
* PHP version:  7.0.15-0ubuntu0.16.10.4

There is right time on server 
```
root@server:~# date
Thu Mar 30 15:18:20 MSK 2017
```
and admin page show right times of link creation. But only in hits graph time is wrong - it last point show -3 hours from Msk. 
GMT now 1:18 pm. 
Last point show 12 pm.
Moscow, server and my PC time is 3:18 pm.

![Screenshot](https://s8.hostingkartinok.com/uploads/images/2017/03/1a5a8796c6791e3d65437b82ba212931.png).

**Comment by ozh** [comment]
Yeah, known behavior. There are inconsistencies in time management across the code. Leaving the issue open, this shouldn't be something major to refactor in the code, but honestly something I don't care about at all. Patches welcome :)

**Comment by gmolop** [comment]
I thought it was fixed in [PR:2048](https://github.com/YOURLS/YOURLS/pull/2048) but it looks like we left out the offset in `current_timestamp`.

**Comment by ozh** [comment]
Supposed to be fixed by #2228
