### ISSUE TITLE
New plugin to limit custom keyword length

### ISSUE THREAD

**Issue by adigitalife** [YOURLS/YOURLS#2223]
Sorry, I wasn't sure what was the best way to share this.

I've made a simple plugin to limit the number of characters allowed for the custom keyword:
https://github.com/adigitalife/yourls-limit-keyword-length

I've noticed that some of my new users don't quite get the concept of URL shortening and use some really long keywords.  Or sometimes, they put the long URL in the custom short URL field.  As a result, it messes up the table view when there are rows with extremely long short URLs.

Anyway, please feel free to add it to the plugin list.

**Comment by LeoColomb** [comment]
👍
