### ISSUE TITLE
URL redirects to root domain only on Safari when generated via the API

### ISSUE THREAD

**Issue by gitChirag** [YOURLS/YOURLS#2224]
Steps to reproduce:
1. Try using the following URL on Safari 10, macOs El Capitan, generated by the API:
http://short.infeedo.com/41G3yi0EzOKpZum8B6nwLUDMoeYxTFCqkcR9Jg5r
2. Try using the following URL on Safari 10, macOs El Capitan, generated using the Yourls admin interface:
http://short.infeedo.com/41G3yi0EzOKpZum8B6nwLUDMoeYxTFCqkcR9Jg5

To reproduce the issue, use Safari Incognito window.
Both the links work perfectly on all browsers except the first one redirects to the base url on Safari. Requesting some help here or some direction to help me fix the issue.

### Technical details

* YOURLS version: 1.7.2
* PHP version: 7.0.15
* OS: Ubuntu, using LAMP stack

**Comment by dgw** [comment]
Have you tested on multiple instances of Safari 10? Different user account, different installation/Mac? Could be a cached state or some issue with the user profile.

**Comment by gitChirag** [comment]
@dgw Yes, have tried to reset cache, tried different macbook machines, all using the same os and browser. Also, tried on crossbrowsertesting.com

**Comment by dgw** [comment]
@gitChirag Sounds like an odd bug, then. As far as I know the API creates links the same way as the web interface…

**Comment by ozh** [comment]
I won't contribute here because I don't use Safari, but that very looks like a client / cache bug.

Yes, the API or the admin interface all use the same functions and once stored, nothing in the DB tells the client how or why a short URL was created. Also, nothing in the code checks what user agent requests a redirection before redirecting it (unless, of course, plugins interact)

Closing because I believe it's not a YOURLS bug per se but feel free to provide additional details till someone can provide any helpful tip.

(also, I think you copy/pasted the same URL twice)

**Comment by gitChirag** [comment]
@ozh Thanks for your response. Request you to help me a bit or give me some direction here because that's not a cache issue. The 2nd url has one character omitted in the end because I tried copy/pasting the same url in the admin panel and check if any character in the string is causing the issue. 
The 2nd url is working on all safari browsers but the first one is not working on any safari browser.

**Comment by ozh** [comment]
There's a difference between these two links: first one redirects to http://amber.infeedo.com/#/token:bleh, second one redirects to https://amber.infeedo.com/#/token:bleh -- note the https

I think here's your problem: server misconfiguration regarding SSL and/or Safari doing something weird on this HTTP vs HTTPS request. All other tests I've run show nothing unexpected regarding the redirection headers that your links send. Not sure what tools exists for Safari but you can check server responses using web based tools such as http://headers.cloxy.net/ or http://www.webconfs.com/http-header-check.php

**Comment by gitChirag** [comment]
@ozh Thanks a lot. Your attention to detail saved me. Short URL generated via admin panel with only http caused the issue too. I just need to put https everwhere instead and fix the issue.
