### ISSUE TITLE
Search engines generate short URL's with p'n's

### ISSUE THREAD

**Issue by seventhsite** [YOURLS/YOURLS#2225]
* YOURLS version: 2
* PHP version: 7.0.15-0ubuntu0.16.10.4

Search engines index links like http://sho.rt/index.php?url=http://long.com/ and create new short URL's by itself. How to forbid it? 
I think the best way, write it in robots.txt, but how?
Thank you in advance!

**Comment by ozh** [comment]
I guess a robots.txt directive like "Disallow: /index.php" may work, but in the first place I don't get how search engines come across such URLs ...

**Comment by seventhsite** [comment]
I'm also don't know. May be from browsers of other users or maybe anywhere somebody write about it and post a link.
Thank you! I hope it will not have negative effect foe indexing other links and all site?
