### ISSUE TITLE
New plugins for Yourls

### ISSUE THREAD

**Issue by prog-it** [YOURLS/YOURLS#2229]
I've made a simple plugins for Yourls.
1. Allows you to get the Thumbnail URL image (long URL) by adding `.i` to the end of the keyword: https://github.com/prog-it/yourls-thumbnail-url
2. Allow you preview URL with QR Code and Thumbnail image. Need add the character '~' to a short URL to display a preview page with QR code and Thumbnail image before redirection. Include custom translation: https://github.com/prog-it/yourls-preview-url-with-qrcode-thumbnail

Please feel free to add it to the plugin list.

**Comment by ozh** [comment]
Added to the list ! Thanks ! 🍰
