### ISSUE TITLE
Release notes feed

### ISSUE THREAD

**Issue by tbitai** [YOURLS/YOURLS#2231]
### Technical details

* YOURLS version: latest wiki
* PHP version: irrelevant

### Feature request

The wiki refers to the blog for announcements, so I assume we have to follow the blog for release notes. It would be nice to be able to do this via a feed. The blog has no documented feed, but I noticed that there's an RSS feed under http://blog.yourls.org/feed/. Is this something we can rely on? If yes, please document this.

**Comment by tbitai** [comment]
I just noticed that you link the announcements in your GitHub release notes, so an alternative would be to just use GitHub's [quasi-documented](https://github.com/isaacs/github/issues/410#issuecomment-292196044) Atom feed: https://github.com/YOURLS/YOURLS/releases.atom

**Comment by LeoColomb** [comment]
Hmmm, [important announcements](http://blog.yourls.org/) != [release notes/change log](https://github.com/YOURLS/YOURLS/releases).
The first link is more "commercial", the second is very technical.

**Comment by tbitai** [comment]
For sure they're different. What I (and I assume many others) want is notifications whenever we need to take action. Isn't the release notes feed enough for that? If not, can you assure that the blog feed will work?

**Comment by LeoColomb** [comment]
This behavior is [already active in core](https://github.com/YOURLS/YOURLS/blob/31215e373b31a3804d7d3bf4ed2eb0cab3875923/includes/functions-http.php#L251-L352)! A notification will appear on your admin interface if a new version is published and available.

**Comment by ozh** [comment]
@tbitai example: 

![](http://blog.yourls.org/wp-content/uploads/2014/01/update-notice.png)

**Comment by tbitai** [comment]
Great, thanks! :)
