### ISSUE TITLE
"Cannot redeclare geoip_country_code_by_name()"

### ISSUE THREAD

**Issue by uusijani** [YOURLS/YOURLS#2237]
### Technical details

* YOURLS version: master (at e36ec69)
* PHP version: 5.6.30
* I'm running Yourls on shared hosting and they have php5-geoip installed

### Bug Summary 

After pulling recent changes (up to e36ec69) today, I've hit what appears to be a regression of [issue #359](https://github.com/YOURLS/YOURLS/issues/359): I get a blank page and a "Cannot redeclare geoip_country_code_by_name()" (in includes/geo/geoip.inc on line 1602) error in my log.

I can work around the issue by checking out d5a5522, which is the last commit prior to "Update GeoIP" (96a159b).

**Comment by ozh** [comment]
Thanks for this clear issue.

Indeed, in latest `geoip.inc` they [blindly declare functions](https://github.com/YOURLS/YOURLS/blob/96a159b2219de072abadab800c6569fe6daf6c2c/includes/geo/geoip.inc#L1537) while in previous version they declared it [only if not existent](https://github.com/YOURLS/YOURLS/blob/d5a5522f405b5481a4227861ba3f631b898cf172/includes/geo/geoip.inc#L386-L387)

God, what an awful lib :) Simple to use, nice overall results, but so badly written :)

I'll revert this update. Again, thanks for the report.

**Comment by LeoColomb** [comment]
> they declared it only if not existent

Ha ha, no, they never, it's [_your_ own added declarations](https://github.com/YOURLS/YOURLS/commit/9477cc84043f42734aab03aad1e12300abaca09f)! 😉

**Comment by ozh** [comment]
Ah, this explains why I couldn't find on their repo when they removed these checks :) Anyway, this lib is quite a mess, they introduce a class but don't completely use it, the code is not pretty. We'll switch to geoip2 one of these days (or another easy to use lib)
