### ISSUE TITLE
Move 3rd party into `vendor/` dir

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#2238]
To do one of these days:

- [x] move every 3rd party script (that leverages composer, eg Requests, phpass, future mysql stuff, ...) from `includes/` to `includes/vendor`
- [x] use composer's autoloader from there instead of manual `require()`
- [x] since composer cannot checkout just the libraries but [insists in downloading all the crap every time](https://github.com/composer/composer/issues/1750), and we don't want to ship that, make a tedious build script such as [sensiolabs'](https://github.com/sensiolabs/SensioDistributionBundle/blob/f2bbaa81fe980f64ccf32bb63038bf130855f5f1/Resources/bin/build.sh#L61-L69) to remove tests, docs, bins and whatnot before committing new files

This will eventually simplify updating libs and how they are used, despite being quite a burden to clean up things before shipping.

**Comment by LeoColomb** [comment]
Related: #1584 

Globally 👍, but as discussed before, composer dependencies should not be included in general packages, at least not in the repo.
That said, the sensionlabs build script can be used to build releases packages for distribution.

**Comment by ozh** [comment]
I want something to be usable out of the box (download the zip, or git pull) without any additional steps (no composer call, no build script or anything like this). It's an end product for any user, including very noobs, not a lib to be used in other projects by geeks

**Comment by ozh** [comment]
Closing this issue, taken care of by #2252
