### ISSUE TITLE
Traffic Statistics *Possible* Bug

### ISSUE THREAD

**Issue by carterwarren** [YOURLS/YOURLS#2240]
Hi, 

We've been using your software for a while now and have been enjoying it. A client recently asked for the Traffic Statistics and we sent it over to them. After doing so, we looked at the dates more carefully and noticed there seems to be a hole within those dates as you can see below. It seems odd that no one clicked the link between the 06 - 11. We haven't seen any errors pop up, so I was hoping you could explain how these numbers are generated in more detail.

Thanks so much.

> 11/04/2016 - 145305
> 11/06/2016 - 19967
> 11/11/2016 - 377
> 11/16/2016 - 188
> 11/21/2016 - 148
> 11/26/2016 - 215

**Comment by ozh** [comment]
Stats are very blindly updated on each request, see [this code](https://github.com/YOURLS/YOURLS/blob/master/yourls-go.php#L19-L29)

The only possible case where stats can be *not* updated is when the same client requests a short URL several times: on first occurrence, the client (Firefox, Chrome, whatever) requests the short URL, to which the server replies with a "301 Permanent Redirect" to the long URL. On subsequent occurrences, the client has this permanent redirect in cache so it actually doesn't send a request to the server (ie you type "http://sho.rt/blah" and your browser won't even connect to sho.rt, it will remember that this is a redirection and will directly send a request to the redirected page). This behavior depends on the browser cache configuration.
