### ISSUE TITLE
Can't connect db to new YOURLs installation

### ISSUE THREAD

**Issue by phillycodehound** [YOURLS/YOURLS#2241]
I'm running the latest version of YOURLs. I moved it from one server to another. Reimported the database after installing the software and non of the old URLs show up. How do I make the program see the database correctly?

Thanks in advance.

**Comment by LeoColomb** [comment]
Missing a lot of information, please don't clear out the issue template when creating a new issue.

Check and recheck your database config in `config.php` file.

**Comment by ozh** [comment]
I'll add to @LeoColomb's answer: YOURLS doesn't know or care if the DB is new or not. If your install cannot see the DB, it's most either a DB config problem, or an import problem with your old data (not imported correctly, or not imported in the right place, ...). Use a tool like phpMyAdmin or something similar to see what's in your DB.
