### ISSUE TITLE
Links are showing in application but not connecting to actual sites linked.

### ISSUE THREAD

**Issue by phillycodehound** [YOURLS/YOURLS#2242]
Before any bug report:
- [ ] Check you are using the **LATEST** release or the development branch.
- [ ] Make sure you have **SEARCHED** closed issues first. 
- [ ] Read the **GUIDELINES** linked in the yellow notice box above.
- [ ] **COMPLETE** this issue template.
- [ ] **DELETE** these first lines.

Thanks you!

### Technical details

* YOURLS version: 1.7.2
* PHP version: Latest
* Any other useful information depending on context (server version, mysql version, browser version, OS version...)

### Reproducible Bug Summary 

1. Installed YOURLS 1.7.2
2. Hooked up Existing DB with existing URLs
3. When I log in and click on a link that is shortened I get 404 "Not found on Server" (Ie. http://pbnyc.co/2u)
4. All three tb tables are intact.

This is a bug because... your system isn't working....

![chrome_2017-05-02_08-20-26](https://cloud.githubusercontent.com/assets/119312/25617437/4d4007ac-2f10-11e7-980e-e24e3426e930.png)
![chrome_2017-05-02_08-20-08](https://cloud.githubusercontent.com/assets/119312/25617445/5647d262-2f10-11e7-99c5-60c16c3088b8.png)

**Comment by LeoColomb** [comment]
Hmm, I supposed you've bypassing installation by coping an existent database, then no `.htaccess` is present at the root.
Could you confirm?

> your system isn't working

🤔

**Comment by phillycodehound** [comment]
![firefox_2017-05-02_08-26-45](https://cloud.githubusercontent.com/assets/119312/25617641/4e83c36e-2f11-11e7-9d72-7a09f1b941b1.png)

This is the urls dtabase

**Comment by phillycodehound** [comment]
what do I need to put in the .htaccess file

**Comment by LeoColomb** [comment]
RTFM: https://github.com/YOURLS/YOURLS/wiki/.htaccess

**Comment by phillycodehound** [comment]
Okay. BTW I've become a backer at $5 month. I appreciate your help

**Comment by phillycodehound** [comment]
That worked thanks for your help.

**Comment by ozh** [comment]
Whoohoo, our first backer! Much appreciated :)
