### ISSUE TITLE
Finally reproduced the "infinite spinny circle" bug

### ISSUE THREAD

**Issue by dylanh724** [YOURLS/YOURLS#2243]
In reference to https://github.com/YOURLS/YOURLS/issues/2089 and a few others from other people I noticed,

Every now and then, it would work - and then stop working. I realized that it would only work after I clicked on "admin interface" (which instead of /admin/ goes to SPECIFICALLY /admin/**index.php**). I know that /admin/ should likely default to index.php, and that is indeed the page that shows up, but **yourls will not work UNLESS I specifically am at /index.php and not just /**

What could possibly cause this? As long as I click on "admin interface" or directly browse to /admin/index.php , it works like a charm.

**Comment by ozh** [comment]
What's the server's response that causes an Ajax error when you try to edit a link? See https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps#use-your-browser-developer-tools to check that server response

**Comment by dylanh724** [comment]
There is 100% nothing on the /admin/ page, but /admin/index.php shows a normal Ajax in the logs.

As in -- no logs at all for just /admin/

**Comment by ozh** [comment]
I'm not talking about the server logs, but what goes on during the ajax request. As explained in the wiki linked above, it's most likely javascript errors, in the page on the client side, not server side errors. 

Example with firebug in firefox to inspect the ajax response. 

![image](https://cloud.githubusercontent.com/assets/223647/25752052/65b09320-31b7-11e7-8bf7-9c101479ce7b.png)

**Comment by ozh** [comment]
No feedback, closing. Feel free to comment on.
