### ISSUE TITLE
upgrade issue from 1.7.1 to 1.7.2

### ISSUE THREAD

**Issue by sachinbanugariya** [YOURLS/YOURLS#2246]
we are using:
centos 6.8
& YOURLS running version 1.7.1
& MySQL  Ver 15.1 Distrib 10.0.29-MariaDB
& PHP 5.5.38 versions

we are not able to upgrade 1.7.1 to 1.7.2.
we follow below steps:
Backup the database!
Unzip the YOURLS archive
Upload files to your server, overwriting your existing install
Point your browser to http://your-own-domain-here.com/admin/
Tip: you can now move your config.php file to the /user directory

but still not able to see latest updated version 1.7.2 for yourls.
i also try to upgrade with 
https://hostname/admin/upgrade.php
![yourls](https://cloud.githubusercontent.com/assets/22053179/25900195/3f7ba0f8-35b0-11e7-8040-134ced14c575.png)
please provide some guide how can i upgrade yourls.

thank you

**Comment by ozh** [comment]
Sorry, I definitely cannot reproduce this. I've just installed a fresh 1.7.1 and updated as told, it simply works.

Feel free to provide any additional detail you think might help.
