### ISSUE TITLE
Phishing page on urlsmall.net

### ISSUE THREAD

**Issue by Scam-Watchers** [YOURLS/YOURLS#2247]
urlsmall.net/clanex666
This is a Runescape phishing page to get accounts with bank details linked to them.
http://runescape.com is the site it's a phishing page of.

**Comment by ozh** [comment]
So contact the owner of urlsmall.net ......................

**Comment by LeoColomb** [comment]
... or provide your report to official report pages such as [Google](https://safebrowsing.google.com/safebrowsing/report_phish) or [US Gov](https://www.us-cert.gov/report-phishing).
We are not an authoritative institution or a company which can handle abuse reports correctly and efficiently.

**Comment by Scam-Watchers** [comment]
Dumb ass

**Comment by Scam-Watchers** [comment]
Can't even block a url, low budget much
