### ISSUE TITLE
Suggestion: Allow Alternate/Fallback URL with Fallback Toggle accessible via admin UI/API 

### ISSUE THREAD

**Issue by tfrancois** [YOURLS/YOURLS#2248]
YOURLS version: 1.7.2

I would like to propose an option that would be incredibly valuable to Yourls administrators/developers.

The ability for Yourls to have a primary/default Long URL and a second optional fallback URL as part of each URL entry.  A flag or toggle that can be turned on/off via an API call or via the Admin UI would allow users to toggle between either the default or fallback, allowing functionality that would permit users to redirect short urls/keywords based on a condition.  The fallback URL should not  adhere or be affected by the YOURLS_UNIQUE_URLS setting, as multiple entries should be allowed to have the same fallback URL regardless if their primary is a unique URL.

I think this would a valuable, dynamic and elegant feature/enhancement that could provide tremendous value to this excellent solution.

Possible Use Cases:
- Ability to programatically/manually set URL expiry without deleting a URL
- Ability to have on/off hours or peak on/off times for a service or site
- Ability to redirect traffic to back up site if maintenance is occurring on primary URL
- And so much more!

I believe this functionality can be added fairly quickly via a plugin.  I hope its adopted and taken on by someone in the near future.  Thank you!

**Comment by ozh** [comment]
Definitely plugin territory indeed, although I doubt many would use this. Leaving this open so it may attract a plugin dev's interest, but not something that I'll dig into personally.

**Comment by ozh** [comment]
Closing issues labelled with "plugin domain". They are given visibility in the wiki for aspiring plugin coders.
