### ISSUE TITLE
Why copy config.php to user during upgrade?

### ISSUE THREAD

**Issue by johnyradio** [YOURLS/YOURLS#2250]
Hello, 

your [upgrade instructions](https://yourls.org/#Install) Step 5 says "Tip: you can now move your config.php file to the /user directory"

It's unclear what is the purpose of this step, whether it is required, what the benefit is, and what are the drawbacks if i don't do it. 

I also noticed that config.php is _already_ in /user (from my existing installation), and there's no config.php at the root dir of the upgrade. What config.php are we talking about?

My upgraded install seems to be working fine. 

Confused. Fyi, i'm going from 1.7.1 to 1.7.2

thx

**Comment by ozh** [comment]
Well, if your config.php is already in /user, then I guess you're all good, right? :)

This will be a concern for people whose config.php is not in /user, probably coming from a very old YOURLS version.
