### ISSUE TITLE
The codes from API example is not working

### ISSUE THREAD

**Issue by KobeLai** [YOURLS/YOURLS#2257]
### Technical details

* YOURLS version: YOURLS version: 1.7.2
* PHP version: PHP 7.0.15
* Ubuntu 16.04.2 LTS/Apache 2.4.18/mysql  Ver 14.14 Distrib 5.7.18

### Reproducible Bug Summary 

Hello,
I tried to use the exactly same codes from the API example
```
var api_url  = 'http://sho.rt/yourls-api.php';
var response = $.get( api_url, {
    username: "your_username",
    password: "your_password",
    action:   "shorturl",
    format:   "json",
    url:      "https://www.google.com/"
    },
    // callback function that will deal with the server response
    function( data) {
        // for instance, return short URL
        return data.shorturl;
    }
);
```
it did shorten the URL but it didn't return any data.
Also, since it does not return any data, I have to change the code from `return data.shorturl;` to `return data;` so the code will actually run or it will show the error message `Cannot read property 'shorturl' of undefined
` in the Console and not run the code.

Thanks

**Comment by ozh** [comment]
Yeah actually the code to do something with the returned data should be in the callback function. Something like:
```js
var api_url  = 'http://sho.rt/yourls-api.php';
var response = $.get( api_url, {
    username: "yourname",
    password: "yourpassword",
    action:   "shorturl",
    format:   "json",
    url:      "http://ozh.org/"
    },
    // callback function that will deal with the server response
    function(data) {
        // now do something with the data, for instance show new short URL:
        alert(data.shorturl);
    }
);
```

I'll update the doc accordingly.
