### ISSUE TITLE
password does not work (latest version v 1.7.2)

### ISSUE THREAD

**Issue by oddstrange201** [YOURLS/YOURLS#2259]
I noticed my admin credentials no longer work today, nothing had been changed on the server

I have checked past issues, Also I edited the config and double checked it. I also added a duplicate config.php to the /user directory

This seems to be a bug, would it be easier just to burn the directory and start over, or try to fix the bug?

thanks

**Comment by dotLuxury** [comment]
We were seeing a similar issue where passwords were created with special characters and the entire password field was not escaped. We moved to a limited character set for passwords, using longer cap-sensitive alpha-numeric and haven’t had any issues since.


Best Regards,
A2

**Comment by oddstrange201** [comment]
@dotLuxury 

would that be say I am putting in 

Ex@mple

and your suggesting 

EXAMPLE


kind of defeats password security does'nt it, then again it is an open source product ;)

**Comment by oddstrange201** [comment]
and that actually did not fix it

I tried to make the password as you see here

$yourls_user_passwords = array(
	
	 'admin' => 'phpass:test' /* Password encrypted by YOURLS */ ,
	// You can have one or more 'login'=>'password' lines
	);


No joy

**Comment by oddstrange201** [comment]
I torched the install, as with most open source a restart of the db and the directory fixed it all, and the special character password works again, who knows why software breaks, it works now!

Thanks

**Comment by ozh** [comment]
For the record, you can simply change/reset your password by editing it normally, as you did the first time.

ie: you have:

```
$yourls_user_passwords = array(
	'joe' => 'phpass:!2a!08!m4jjDIab7[.....]Dm' /* Password encrypted by YOURLS */ ,
	);
```

you edit it as:

```
$yourls_user_passwords = array(
	'joe' => 'MyPassWord',
	);
```

and next loading of YOURLS will re-encrypt it.

Don't edit it as `joe => 'phpass:sometext'`, that won't work.

**Comment by dotLuxury** [comment]
We ran into challenges specifically with comma (,), single quote ('), dollar ($), and bang (!).

The ' and , make sense as they are delimiters...

It was an easier path for us to limit character input than escape the whole value.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ozh** [comment]
Actually you are supposed to be able to use any character in your password, YOURLS doesn't care.

For all I know, you totally can have `'joe' => "@@$$@@"` or `'joe' => '"""'`. The unit tests, which all [pass](https://travis-ci.org/YOURLS/YOURLS), check a [number of crazy passwords](https://github.com/YOURLS/YOURLS-unit-tests/blob/master/tests/auth/auth.php#L36-L47)

**Comment by dotLuxury** [comment]
To help, I'll try to reproduce the issues, over the weekend, we had seen and file ticket with the details. The easy one was a single quote (') in the password as that is the field delimiter for the password value (and all array or single values) in .../user/config.php.

Let's stop this thread and can re-engage on the ticket when filed.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ozh** [comment]
Just a quick note: a string in PHP can be either `'singlequotes'` or `"doublequotes"` so if you need to use a single quote within the password, well, enclose the string within double quotes ...

**Comment by dotLuxury** [comment]
That’s an excellent piece of info! Thanks. Will still see if we can duplicate the issues we had seen and file a ticket.

Best Regards,
A2

. L   U   X   U   R   Y
Discover.Luxury  •  twitter @dotLuxury<http://twitter.com/dotLuxury>  •  instagram dotLuxury<http://instagram.com/dotLuxury>

**Comment by oddstrange201** [comment]
I agree that you should have a way to use stronger passwords, I believe that there is a github bashing websites for not using strict password compliance as it is, 

I found it easier to just redo the install, also I am completely ignorant when it comes to the code side of this project, the function side is awesome though!

Bit.ly is getting a little long in the tooth, banning and stopping links that they have no business doing, so having our own server to create shortlinks is a great thing

**Comment by ozh** [comment]
@oddstrange201 again, if this wasn't clear before : as far as I know, you can use WHATEVER password you want, with whatever special char or anything. It's just a string like another one.
