### ISSUE TITLE
segfault using php7?

### ISSUE THREAD

**Issue by kkretsch** [YOURLS/YOURLS#2260]
### Technical details

* YOURLS version: 1.7.2
* PHP version: 7.0.19-1~dotdeb+8.1
* Debian 8.8 VPS server using MariaDB  10.0.30-MariaDB-0+deb8u2

### Reproducible Bug Summary 

1. Install yourls
2. admin backend login works
3. using shortlinks breaks
Neither the redirect us nor the statistcs view of the short links works. It just gets back no data from the webserver.
I don't get error log entries in the vhost apache logs but massive entries in the central error log like:
[Tue Jun 06 18:10:31.102360 2017] [core:notice] [pid 896:tid 139861265053568] AH00052: child pid 964 exit signal Segmentation fault (11)
[Tue Jun 06 18:10:31.102437 2017] [core:notice] [pid 896:tid 139861265053568] AH00052: child pid 965 exit signal Segmentation fault (11)
[Tue Jun 06 18:10:33.105175 2017] [core:notice] [pid 896:tid 139861265053568] AH00052: child pid 1322 exit signal Segmentation fault (11)
[Tue Jun 06 18:10:34.106307 2017] [core:notice] [pid 896:tid 139861265053568] AH00052: child pid 1350 exit signal Segmentation fault (11)
[Tue Jun 06 18:10:34.106381 2017] [core:notice] [pid 896:tid 139861265053568] AH00052: child pid 1351 exit signal Segmentation fault (11)
[Tue Jun 06 18:10:36.109416 2017] [core:notice] [pid 896:tid 139861265053568] AH00052: child pid 1406 exit signal Segmentation fault (11)
[Tue Jun 06 18:10:37.110551 2017] [core:notice] [pid 896:tid 139861265053568] AH00052: child pid 1434 exit signal Segmentation fault (11)
[Tue Jun 06 18:10:37.110624 2017] [core:notice] [pid 896:tid 139861265053568] AH00052: child pid 1435 exit signal Segmentation fault (11)
[Tue Jun 06 18:10:39.114792 2017] [core:notice] [pid 896:tid 139861265053568] AH00052: child pid 1490 exit signal Segmentation fault (11)
[Tue Jun 06 18:10:40.116263 2017] [core:notice] [pid 896:tid 139861265053568] AH00052: child pid 1519 exit signal Segmentation fault (11)

Is php7 supported?

**Comment by LeoColomb** [comment]
> I don't get error log entries in the vhost apache logs but massive entries in the central error log like

Everything is in this sentence!
It shouldn't be related to YOURLS directly, this is [often more general](https://stackoverflow.com/q/7745578). 
Preliminary debugging: did you try your server with a very basic PHP page?

**Comment by kkretsch** [comment]
As I wrote the admin part runs, the setup did work, and the server runs some other virtual hosts like piwik. So I don't think that ticket should be closed so fast.

Back to my question: php7 _is_ supported?

**Comment by LeoColomb** [comment]
> php7 is supported

[Yes](https://travis-ci.org/YOURLS/YOURLS).

**Comment by ozh** [comment]
[Very yes](https://php7.yourls.org/admin/). 🐕

**Comment by ozh** [comment]
If admin part works and redirection doesn't, then the problem mostly sits between the apache, its conf and the mod_rewrite module.

Basically if admin part works, YOURLS works. The redirection part is very simple in itself and if there's a problem then it's a server config problem. Check https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps
