### ISSUE TITLE
Title doesn't support apostrophe

### ISSUE THREAD

**Issue by adigitalife** [YOURLS/YOURLS#2262]
1. Add a link
2. Edit the link
3. Add an apostrophe in the title (e.g. Bob's link)
4. Click 'Save' (it doesn't work)
5. Remove the apostrophe (e.g. Bobs link) and click 'Save' (now it works)

Is there a technical reason why apostrophes aren't supported in the title?  If no, can we please add support?  I think it will allow the titles to be more descriptive.

**Comment by 1294822** [comment]
I am using the latest version, and did not find this problem

**Comment by ozh** [comment]
Fixed in 1.8
