### ISSUE TITLE
Suggestion: Overlay on Shortener Target Page

### ISSUE THREAD

**Issue by wwadvice** [YOURLS/YOURLS#2263]
[New & first post to Github so please excuse is this is not the way to do things.]

Didn't find this in the plugin area...

A feature similar to snip.ly, where the target page is opened up in an iframe instead of directly so a 'box' can be placed somewhere overlaying the target page.

**Comment by dgw** [comment]
This is possible with a plugin, and in fact there is a sample implementation [included in the YOURLS source code](https://github.com/YOURLS/YOURLS/blob/master/user/plugins/sample-toolbar/plugin.php). Also see [the conditional example](http://blog.yourls.org/2011/03/yourls-plugin-example-conditional-toolbar/).

**Comment by wwadvice** [comment]
I will check that out. Didn't think to use 'toolbar' for what I was thinking of. Thank you.

**Comment by ozh** [comment]
Thanks @dgw :)
