### ISSUE TITLE
function yourls_apply_filter fix

### ISSUE THREAD

**Issue by 1294822** [YOURLS/YOURLS#2264]
the  function of yourls_apply_filter,
change 
```
if( $the_['type'] == 'filter'){
 	$value = $_value;
to 
if( $the_['type'] == 'filter' && $_value){
	$value = $_value;
        break;
}
```
it fixed  bug for filter plugin

**Comment by LeoColomb** [comment]
Thanks for your submission. Could you explain?

**Comment by 1294822** [comment]
I use a lot of filter plugin, but it does not work. Analysis found that yourls_apply_filter function only use the results of the last filter plug-in, and the final result may be passed. An error message should be thrown when an error is found.

**Comment by ozh** [comment]
I still don't get it and it seems to me that the filter hooks work as expected.

Can you describe a situation where a filter does not work please

**Comment by 1294822** [comment]
i changed yourls_apply_filter function like this`function yourls_apply_filter( $hook, $value = '' ) {
	global $yourls_filters;
	if ( !isset( $yourls_filters[ $hook ] ) )
		return $value;
	
	$args = func_get_args();
	
	// Sort filters by priority
	ksort( $yourls_filters[ $hook ] );

	// Loops through each filter
	reset( $yourls_filters[ $hook ] );
	do {
		foreach( (array) current( $yourls_filters[ $hook ] ) as $the_ ) {
			if ( !is_null( $the_['function'] ) ){
				$args[1] = $value;
				$count = $the_['accepted_args'];
				if ( is_null( $count ) ) {
					$_value = call_user_func_array( $the_['function'], array_slice( $args, 1 ) );
				} else {
					$_value = call_user_func_array( $the_['function'], array_slice( $args, 1, (int) $count ) );
				}
			}
            if( $the_['type'] == 'filter'){
			 	$value = $_value;
                echo "$the_[function] ";
                var_dump($value);
			}
			//if( $the_['type'] == 'filter' && $_value){
//			 	$value = $_value;
//                break;
//			}
            

		}

	} while ( next( $yourls_filters[ $hook ] ) !== false );
    
	if( $the_['type'] == 'filter' ){
	   print_r($value);
	   die('exit');
	   return $value;
	}

}
`
and got the result
`
  ozh_yourls_antispam_check_add bool(false)
  apelly_blacklist_domain_root bool(false)
apelly_spam array(4) {
  | ["status"]=>
  | string(5) "error"
  | ["code"]=>
  | string(12) "error:bypass"
  | ["message"]=>
  | string(34) "这个不是一个正常的网址."
  | ["errorCode"]=>
  | string(3) "400"
  | }
  | abaumg_shortshort_check_and_bypass bool(false)
  | exit

`

coming soon

**Comment by ozh** [comment]
Sorry, unreadable, don't know what you're talking about, doesn't understand my simple question. Closing, feel free to comment on.
