### ISSUE TITLE
Different instructions

### ISSUE THREAD

**Issue by JeremyHutchings** [YOURLS/YOURLS#2265]
Clone

![2](https://user-images.githubusercontent.com/439559/27972271-a2cc2f88-630a-11e7-95b7-5cff03c10054.png)

Fork

![1](https://user-images.githubusercontent.com/439559/27972291-aeee82ca-630a-11e7-8be9-9dc47023a07c.png)

**Comment by ozh** [comment]
Indeed. Changing "fork" to "clone", thanks for noticing.
