### ISSUE TITLE
IPv6 addresses & column width

### ISSUE THREAD

**Issue by atdr** [YOURLS/YOURLS#2266]
![screen shot 2017-07-12 at 21 19 11](https://user-images.githubusercontent.com/10052770/28138221-e637591e-6747-11e7-9186-da66a06f82f5.png)

### Technical details

* YOURLS version: 1.7.2
* PHP version: 7.0.18
* nginx 1.10.3 on Ubuntu 16.04.2

### Reproducible Bug Summary 

1. Create shortlink from IPv6 address
2. View admin interface

IPv6 addresses expand the *IP* column width, causing the contents of the *Actions* column to be broken onto multiple lines which increases row height.

These links are created automatically by WordPress plugin [YOURLS Link Creator](https://wordpress.org/plugins/yourls-link-creator/) running on a server with both IPv4 and IPv6 addresses.

**Comment by ozh** [comment]
Indeed. Someone should submit a PR with a fix for this :) (either a CSS fix, or a clever way to output this)

Interestingly though, I'm on IP V6 myself, but all my YOURLS instance display my IP V4 in that column... Not sure why...

**Comment by gehwissenlos** [comment]
I have a similiar problem with IPv6 addresses on the Sleeky backend. I see only some parts, not the whole address.
Would it be possible to show only some digits like it is now but add a title-tag to the table:
<td class="ip" id="ip-y1356258652" title="2001:0db8:85a3:08d3:1319:8a2e:0370:7344">2001:0db8:85a3:08d3:1319:8a2e:0370:7344</td>
With mouseover you would see the full address but it doesn't destroy the admin interface.

**Comment by gehwissenlos** [comment]
include/functions-html.php, line 625 could look like this (quik'n'dirty):
`if ($cell_id == 'ip') {
			$row .= sprintf( '<td class="%s" id="%s" title="%s">', $cell_id, $cell_id . '-' . $id, preg_replace_callback( '/%([^%]+)?%/', array( $callback, 'callback' ), $elements['template'] ) );
		} else {
			$row .= sprintf( '<td class="%s" id="%s">', $cell_id, $cell_id . '-' . $id );
		}`
I think there is a better way to do this but this could be an idea of a solution.
