### ISSUE TITLE
403 Forbidden Access to this resource on the server is denied!

### ISSUE THREAD

**Issue by amzens** [YOURLS/YOURLS#2267]
HI, i shorten urls with YOURLS everything is good but if i paste shorten link to other forum and i click for link in forum got"403 Forbidden Access to this resource on the server is denied! I copy this link from forum right click and is this"http://jeuxvideo.digidip.net/visit?url=hereismyshortenlink" Please help me.

**Comment by LeoColomb** [comment]
This issue seems to be more related with the forum than YOURLS itself. Please ask first to the forum administrator. 

Also, please don't cleanup the issue template.
