### ISSUE TITLE
Url Issue

### ISSUE THREAD

**Issue by SimPlaysGames** [YOURLS/YOURLS#2273]
### Technical details

* YOURLS version:  v 1.7.2

It worked ok before, and I do not know what could have changed to not make it work.
When I try to create a new shortened url it does not work, I think I might know why. When I try to press the bookmark button it opens a new url.

Which is something like

sikom.mesikom.me/url.php?url=https%3A%2F%2Fsikom.me%2Furl.php%3Furl%3Dhttps%253A%252F%252Fsikom.me%252Furl.php%26title%3DSikom%2527s%2520URL%2520Shortener%26text%3D&title=Sikom%27s%20URL%20Shortener&text=

**Comment by ozh** [comment]
I don't get what this is about sorry.
