### ISSUE TITLE
1.7.2 release missing /index.php

### ISSUE THREAD

**Issue by helioloureiro** [YOURLS/YOURLS#2275]
Hi,

Not sure whether it is intentional, but I just downloaded the 1.7.2 release files (checked in both tar.gz and zip) and they are missing the /index.php for yourls.  And no further information about installation to generate an index.php from template or alike.

I had a previous 1.7.0 version running, so I just copied the index.php from there.

**Comment by ozh** [comment]
http://yourls.org/#FAQ

**Comment by helioloureiro** [comment]
I would be good to have further information on README.md or even an INSTALL mentioning it. index-template.php would be super.
