### ISSUE TITLE
Another encoding issue (edit: caused by "Redirect with Get")

### ISSUE THREAD

**Issue by peterberbec** [YOURLS/YOURLS#2277]
Sorry to add another one. :(

### Technical details regarding my environment

* YOURLS version: 1.7.3
* PHP version: 7.0+35ubuntu6
* Apache version: 2.4.18-2ubuntu3.4
* MariaDB version: 10.0.31-0ubuntu0.16.04.2

### Reproducible bug summary 

Shorten a url like https://pix.berb.ec/#15022661159797/15022669376570

If I use the instant shorten bookmarklet, `https://pix.berb.ec/#15022661159797/15022669376570` is stored.
If I use the regular shorten bookmarklet, `https://pix.berb.ec/#15022661159797/15022669376570` is stored.
If I use the address bar, `https://pix.berb.ec/` is stored.
If I enter it manually in the admin page, `https://pix.berb.ec/#15022661159797/15022669376570` is stored.

Problem is, none of them resolve correctly. They all bring me to `https://pix.berb.ec/`

**What is the expected or desired behavior?**

Entering the short link of https://berb.ec/smiley and being navigated to `https://pix.berb.ec/#15022661159797/15022523347054`

### Reproducible bug summary 

1. Shorten link as shown above
2. Navigate to short link

---
It didn't help, but someone suggested a no_decode plugin. I added some functions, but it didn't help:

```yourls_add_filter( 'encodeURI', 'stewx_no_decode' );
function stewx_no_decode( $decoded, $original ) {
    return $original;
}

yourls_add_filter( 'escape', 'berbec_no_escape' );
function berbec_no_escape( $not_escaped ) {
    return $not_escaped;
}

yourls_add_filter( 'sanitize_url', 'berbec_no_sanitize');
function berbec_no_sanitize( $not_sanitized ) {
    return $not_sanitized;
}

yourls_add_filter( 'sanitize_string', 'berbec_no_sanitize_string');
function berbec_no_sanitize_string( $not_sanitized_string ) {
    return $not_sanitized_string;`

**Comment by dgw** [comment]
So the hash component is stored in the database, but not sent with the redirect headers? I'm getting flashbacks to dgw/yourls-dont-track-admins#2, but #2121 is probably more relevant.

Have you tried disabling plugins to see if a plugin is causing it? tl;dr of #2121: The Google Analytics plugin was removing the `#hash` from URLs during its processing. As far as I know, it still does (see katzwebservices/google-analytics-for-yourls#11).

**Comment by peterberbec** [comment]
I don't have any Analytics plugins.

I use:

Allow Hyphens
Case-insensitive
Keywords, Charset &  Length
Mailto: Quickshare
Redirect with Get
and
reCaptcha

I tried disabling Redirect with Get and reCaptcha, and it worked!

I re-enabled reCaptcha, and it's still working.

Now let's re-enable Redirect with Get.... and it's broken again.

Thanks! now to change the title.

**Comment by peterberbec** [comment]
Redirect with Get lives at https://ge1.me/yourls-redirect-with-get and hasn't been touched since 2013.

**Comment by peterberbec** [comment]
Here's hoping the author is still around.

https://github.com/fnkr/YOURLS-redirect-with-get/issues/1

**Comment by ozh** [comment]
Alternative plugin: https://github.com/drockney/append-qs
I just had a lookd at fnkr's plugin and I think it's really messy

**Comment by ozh** [comment]
I've just had a look at several plugins that pass the query string upon redirection, and I think they all miss the point and overcook.

I think [this](https://gist.github.com/ozh/1d078e9cbd5f9757be3bb32011c48461) is just what's needed. Untested live so I'm all ears if it's not working as I expect :)

**Comment by dgw** [comment]
It is messy, yeah. Also unmaintained, and fnkr.net is just a blank white page (?).

Assuming I read the code correctly, that alternative plugin will also break with fragments, but in a different way: `https://exam.pl/short?foo=bar` that points to `https://example.com/longurl#section` will ultimately redirect to `https://example.com/longurl#sectionfoo=bar`—breaking both the query pass-through functionality and the fragment at once. (It might even go to `...#sectionfoobar`, because I can't find in the code where the `=` is reinserted between key and value when building the new URI.)

**Comment by peterberbec** [comment]
@ozh Your plugins seems to work. https://berb.ec/mta? q=M104 resolves to the proper bus info again. Thanks!

**Comment by fnkr** [comment]
Hi, I'm the author of the mentioned YOURLS plugin. I wrote this plugin several years ago in a couple of minutes. I am no longer using it but will merge any pull request that improves it.

**Comment by ozh** [comment]
I updated my short plugin to limit its behavior to short URL redirections, not internal redirections (eg for instance when you log in or out and are redirected to an admin page). Still very much simpler than all other alternatives I think.

**Comment by rinogo** [comment]
I released this plugin a few years ago - it works up to at least 1.7.9, but there's a report that it may be broken now. Regardless, it might be everyone's best bet at this point for getting "Keep Query String" working.

https://github.com/rinogo/yourls-keep-query-string
