### ISSUE TITLE
Yourls 2.0

### ISSUE THREAD

**Issue by scriptgeni** [YOURLS/YOURLS#2285]
Why is the Edit Action not working on Alpha Version 2.0
https://github.com/YOURLS/YOURLS/blob/2.0/includes/admin/admin-ajax.php
The other actions, share, delete and stats are working, only the Edit functions goes to a blank page

Thanks.

p.s. I know this is maybe not the right place the ask this question, is there a dev issue ticket list?

**Comment by ozh** [comment]
I'm not sure the 2.0 dev branches will be expanded. A lot of things have changed in master... Bootstrap is not the same... Not using enough 3rd party libs and re-inventing the wheel instead... So, not saying it won't, but not saying it will either.

Anyway, regarding your question: I don't know :)

(yes, this is a correct place to submit this issue)

**Comment by scriptgeni** [comment]
Ok thanks, do you have some tip how we could include Bootstrap classes? I've created a simple plugin to add Bootstrap and Bootswatch https://github.com/scriptgeni/yourls-bootstrap-bootswatch (still working on it). But the thing is the class name are hardcode in functions_html.php and some other place. Is there a way to hook an extra CSS class to tables or other elements without changing the core files?
