### ISSUE TITLE
Change how the reserved keywords are checked

### ISSUE THREAD

**Issue by jfix** [YOURLS/YOURLS#2286]
We're using the `$yourls_reserved_URL` array to avoid people using swearwords as keywords. We've noticed recently that the behaviour seems to be to check whether a suggested keyword is in the list. Otherwise it's acceptable. So if you concatenate `%$#!` (the swear word) with `TEST` to form `%$#!TEST` it will be accepted.

I would like to suggest to change that approach to check whether the keywords contains any of the reserved keywords. Of course this will refuse keywords like `ClassException` (if `sex` is in your list).  Maybe an additional flag should be introduced, `$yourls_reserved_URL_strict` that could by default be set to `true` (to be retro-compatible) or `false` to activate the new behaviour.

- [x] Check you are using the [**LATEST** release](https://github.com/YOURLS/YOURLS/releases/latest) or the development branch.
- [x] Make sure you have [**SEARCHED** existing issues](https://github.com/YOURLS/YOURLS/issues?utf8=%E2%9C%93&q=is%3Aissue) first. 
- [x] Read the [**GUIDELINES**](https://github.com/YOURLS/YOURLS/blob/master/CONTRIBUTING.md) linked in the yellow notice box above.
- [x] **COMPLETE** this issue template.

### Technical details regarding my environment

* YOURLS version: 1.7.2
* PHP version: 5.6

**Comment by ozh** [comment]
That's definitely [plugin territory](https://github.com/YOURLS/YOURLS/wiki/Possible-With-A-Plugin). Most people don't need such a feature (typically single user install with no public interface don't need that, which accounts for roughly 70% of YOURLS installs).

This said, this would make a very interesting plugin (so far there's nothing similar that I know of)

**Comment by jfix** [comment]
So, I've written my plugin but am unsure which hook to use. Two places seem most appropriate, both in the `functions.php` file:

1.  `yourls_do_action( 'add_new_link_custom_keyword', $url, $keyword, $title );` [line 246](https://github.com/YOURLS/YOURLS/blob/master/includes/functions.php#L246)
2. `$keyword = yourls_apply_filter( 'custom_keyword', $keyword, $url, $title );` [line 249](https://github.com/YOURLS/YOURLS/blob/master/includes/functions.php#L249)

In case the plugin detects that a swear word of the list is used as a substring inside the submitted keyword, I'd like to return a message equivalent to the case where `!yourls_keyword_is_free( $keyword )` ([line 250](https://github.com/YOURLS/YOURLS/blob/master/includes/functions.php#L250)).

However, with either hook I cannot see how to achieve it. With the filter, the only thing I see I could do is to have my plugin return a known bad word so that it will be caught in line 250, but that doesn't seem clean. And for the action hook, I can't see how I can influence the subsequent flow of execution.

Any pointers gratefully received.

**Comment by dgw** [comment]
How about `shunt_add_new_link` (line 199)? It gets the keyword (if any) and returning a truthy value short circuits the link creation. The function would have to print a message itself, though.

**Comment by ozh** [comment]
I think @dgw's suggestion is sound here. Apply your custom filtering rules as early as possible. Depending on your use case, you will also want to check keyword after editing (to make sure "kd9Po" isn't edited into "niggercuntfaggot" for instance)

**Comment by jfix** [comment]
Thanks @dgw and @ozh I'll try this. I should probably say "again", because I initially actually did use that particular hook, but somehow it got hung, i.e. it never returned. Only later did I think to check the PHP log for any traces, because of the number of arguments that might be passed and expected. I found later that these errors get dumped into the error log.

By the way, one thing that might benefit debuting plugin developers is the addition of a small section on how to pass arguments to a hook'ed function. I looked at many plugins, and sometimes they passed one argument, say `$keyword`, sometimes none, but still it was possible to retrieve them from within the function via `$args[0]` etc. I couldn't find an explanation that would explain the logic behind it. Maybe I just didn't look at the right place... :-(

**Comment by ozh** [comment]
Everything is explained on the wiki... here in particular: https://github.com/YOURLS/YOURLS/wiki/Plugins

**Comment by jfix** [comment]
It probably is, just not very explicitly.  As I understand it now, having re-read the page looking for information on argument passing, 'action' functions seem to pass in an _array of arguments_, like mentioned here:

> Now if you hook a custom function into the event 'pre_redirect', it will be passed `array($location, $code`) as an argument.

Whereas 'filter' function pass in arguments _one by one_ (i.e. not bundled into an `array`), like mentioned in this example:

> `$keyword = yourls_apply_filter( 'random_keyword', $keyword );`
> If a custom function hooks into the 'random_keyword' filter, it will be sent $keyword as an argument.

The fact that these are given as examples only makes it not 100% clear for the reader whether this is the case of this particular example, or a generalisation that can be assumed for all cases of 'action' or 'filter' functions, respectively.

I think it would be worth highlighting the fact that arguments are passed differently, depending on the hook type.
