### ISSUE TITLE
Moving YOURLs install to sub-directory

### ISSUE THREAD

**Issue by shaunopp** [YOURLS/YOURLS#2287]
I've searched on this and found others reporting the issue but no fix that worked for me. 

To avoid a conflict with an upcoming WordPress install I've moved my YOURLS install from the root directory to a sub-folder. After copy/pasting my installed files from the root to the sub-directory I modified the config.php changing YOURS_SITE to reflect the new location. Now I'm able to create new URL's from the sub-directory and though it shows the new path in the YOURLS UI when I navigate to the URL (in a browser or click it in YOURLS) it's still going to the root.

**Comment by ozh** [comment]
Did you move and edit the [.htaccess](https://github.com/YOURLS/YOURLS/wiki/.htaccess) as well ?

**Comment by shaunopp** [comment]
I didn't edit the .htaccess file, is that my issue?

**Comment by ozh** [comment]
I guess I'll let you answer this one.

**Comment by shaunopp** [comment]
I guess the more appropriate question is what do I need to change in the .htaccess file as it's not something I setup on install.

**Comment by shaunopp** [comment]
I'm guessing change the RewriteBase to my sub-directory? Any other edit?  

# BEGIN YOURLS
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^.*$ /yourls-loader.php [L]
</IfModule>
# END YOURLS

**Comment by LeoColomb** [comment]
@shaunopp See the specific case [in the wiki](https://github.com/YOURLS/YOURLS/wiki/.htaccess#case-yourls-installed-in-subdirectory), as @ozh advised you.
