### ISSUE TITLE
i just want to get my webserver to the public interface when i browse to guardiansofentity.de/yourls  and have my install private . What do i need to do ? 

### ISSUE THREAD

**Issue by Yodale1000** [YOURLS/YOURLS#2291]
Before my submission:

- [ ] Check you are using the [**LATEST** release](https://github.com/YOURLS/YOURLS/releases/latest) or the development branch.
- [ ] Make sure you have [**SEARCHED** existing issues](https://github.com/YOURLS/YOURLS/issues?utf8=%E2%9C%93&q=is%3Aissue) first. 
- [ ] Read the [**GUIDELINES**](https://github.com/YOURLS/YOURLS/blob/master/CONTRIBUTING.md) linked in the yellow notice box above.
- [ ] **COMPLETE** this issue template.

### Technical details regarding my environment

* YOURLS version:
* PHP version:
* Any other useful information depending on context (server OS & version, MySQL version, browser version, …)

### Reproducible bug summary 

**What is the current behavior?**

This is a bug because…

**What is the expected or desired behavior?**

### Reproducible bug summary 

1. First step 
2. Second step
3. …

---

**Comment by LeoColomb** [comment]
> What do i need to do ?

Just read the documentation, please.

**Comment by Yodale1000** [comment]
I read it but i don´t what to do thats why im writing to you ;(
