### ISSUE TITLE
Ad pages before the address is navigated

### ISSUE THREAD

**Issue by ersingo** [YOURLS/YOURLS#2297]
Hello there. I could not find a relevant document on your plugin page. How can I show the ad pages before the link is redirected?

php: 5.6

**Comment by dgw** [comment]
Googled "yourls interstitial" and got https://github.com/joelgratcyk/yourls-interstitial-plugin right at the top.

**Comment by ozh** [comment]
@ersingo for future reference: https://github.com/YOURLS/YOURLS/wiki/Plugin-List. As a rule of thumb, any question you have is probably answered in the wiki, or in closed issues here.
