### ISSUE TITLE
Chrome 61 PDF url not working

### ISSUE THREAD

**Issue by masumonline** [YOURLS/YOURLS#2299]
* YOURLS version: 1.7.2
* PHP version: 5.6.32
* Debian 8, nginx

### Reproducible bug summary 

**all redirect work except pdf **

In chrome 61 pdf redirection is not working. I think chrome 61 change something so the script needed to change.

1. check chrome version 61 is needed
2. create a pdf redirect url. 
3. enter the pdf short url in browser then press enter

**Comment by dgw** [comment]
More detail may be necessary. I tested this on my YOURLS instance using an old shortlink pointing directly to a PDF file and it worked fine. (Granted, my instance still runs 1.7.1, but glancing through the commit log doesn't turn up anything that should affect this.)

What exactly is happening _after_ step 3 of the bug summary?

**Comment by masumonline** [comment]
here is the link
http://url.officextracts.com/ksosguide

here is the destination 
http://bd.klupdate.com/vupdate/installer/corporate/How_to_install_Kaspersky_small_office_security_5.pdf

in chrome 61 it do nothing 
but in other browser it work fine. tested on IE, Chrome 60, Opera, Firefox. Every where it work only problem on chrome 61

**Comment by ozh** [comment]
Works for me on Chrome 61. Cannot reproduce. There's something on your Chrome install that may break things but this isn't a YOURLS defect anyway... (YOURLS doesn't care which browser you're using)

**Comment by dgw** [comment]
Works here too, also on Chrome 61. Almost certainly a problem with OP's Chrome install (extension conflict?), not YOURLS.
