### ISSUE TITLE
CSS not loading

### ISSUE THREAD

**Issue by baxandrei** [YOURLS/YOURLS#2302]
I have an problem, but i don`t have errors in developer console or php error_log

Is fresh install, but css not work

http://prntscr.com/gscnq2

**Comment by LeoColomb** [comment]
Duplicate of #1731

**Comment by LeoColomb** [comment]
Missing a lot of information, please don't clear out the issue template when creating a new issue. Also, we've seen your comment on #1731, if you think your case is related please stick to it.

**Comment by baxandrei** [comment]
I can't reopen #1731, so i send a new ticket, but no problem, you can close it too. i don`t need solution anymore, i deleted script and create my own. thanks.
