### ISSUE TITLE
Prevent YOURLS from accessing the long URL to shorten (fetch the page to get its title) #1206

### ISSUE THREAD

**Issue by grandfso** [YOURLS/YOURLS#2303]
### Technical details regarding my environment

* YOURLS version: 1.7.2
* PHP version: 5.5

I have the same question as has been asked in #1206 however, the links provided there do not work anymore and I cannot read the comments. 
My use case is that I am generating a long URL for the user, that will trigger an action when visited. Then I will shorten the URL to make it look better, then send it to the user. 
If YOURLS visits the url to get the title, it triggers the action.

Therefore I would like to ask the same question:

"How can I disable fetching of the page from the long URL"

thanks!

**Comment by LeoColomb** [comment]
Duplicate of #1966

**Comment by grandfso** [comment]
Thank you!
