### ISSUE TITLE
2.0 - non-specific links result in broken styling

### ISSUE THREAD

**Issue by AlexM-Dev** [YOURLS/YOURLS#2304]
### Technical details regarding my environment

* YOURLS version: 2.0-alpha-dont-use
* PHP version: 7.0
* Running apache

### Reproducible bug summary 

When navigating to 'non-specific' links such as /admin/, the css goes a bit awry. Likewise with links such as /admin/index.php and /admin/plugins.php (along those lines).

This is at /admin/plugins.php: https://i.allym.me/img/bb25ee.png which should actually look like https://i.allym.me/img/8713e5.png.

1. Simply navigating to those sort of links will be able to reproduce the issue. Other factors may include installed plugins (?) - https://i.allym.me/img/335921.png

**Comment by LeoColomb** [comment]
> 2.0-alpha-dont-use
