### ISSUE TITLE
PLugin "Query String Keeper" not work with plugin "YOURLS Toolbar"

### ISSUE THREAD

**Issue by flynhox** [YOURLS/YOURLS#2309]
Hello,

When i active plugin "Query String Keeper" it work very good, but when i try combine "Query String Keeper" and "YOURLS Toolbar" plugin, when i click on close button to close toolbar, the page not show query string after long url, it just show origin url .

How i can fix that ? Please help me, thanks !

**Comment by ozh** [comment]
See with plugin author or, more likely, make or get someone to make a plugin that combines both features
