### ISSUE TITLE
blank white screen when trying to install plus error in Error_log

### ISSUE THREAD

**Issue by boldcity** [YOURLS/YOURLS#2311]
- [ ] Check you are using the [**LATEST** release](https://github.com/YOURLS/YOURLS/releases/latest) or the development branch.
- [ ] Make sure you have [**SEARCHED** existing issues](https://github.com/YOURLS/YOURLS/issues?utf8=%E2%9C%93&q=is%3Aissue) first. 
- [ ] Read the [**GUIDELINES**](https://github.com/YOURLS/YOURLS/blob/master/CONTRIBUTING.md) linked in the yellow notice box above.
- [ ] **COMPLETE** this issue template.

### Technical details regarding my environment

* YOURLS version:  1.7.2
  * Plugins enabled: none
* PHP version:  5.4.16
* Any other useful information depending on context (server OS & version, MySQL version, browser version, …)  CentOS 7

### Reproducible bug summary 

**What is the current behavior?**
im am currently receiving this error in my server error log
[Tue Oct 31 19:12:39.120511 2017] [:error] [pid 1752] [client 192.168.1.2:50020] PHP Fatal error:  Uncaught exception 'YOURLS\\Exceptions\\ConfigException' with message 'Cannot find config.php. Please read the readme.html to learn how to install YOURLS' in /var/www/bcgems.tk/public_html/includes/YOURLS/Config/Config.php:89\nStack trace:\n#0 /var/www/bcgems.tk/public_html/includes/load-yourls.php(18): YOURLS\\Config\\Config->find_config()\n#1 /var/www/bcgems.tk/public_html/admin/index.php(3): require_once('/var/www/bcgems...')\n#2 {main}\n  thrown in /var/www/bcgems.tk/public_html/includes/YOURLS/Config/Config.php on line 89

i used github to clone the file into my public_html folder which is at /var/www/bcgems.tk/public_html.
when i got to http://boldcitygems.tk/admin i receive a blank white page and no source code visible. the error above it what pops up each time i try to go to the admin folder.

**Comment by LeoColomb** [comment]
> Cannot find config.php. Please read the readme.html to learn how to install YOURLS

Please read the error output! 😄

**Comment by boldcity** [comment]
i have read the readme and have installed it the way it says i have configured the config.php with my info and is in the user folder. that why im asking here.

**Comment by LeoColomb** [comment]
Ah, maybe related to #2294 then. Any idea @ozh?

**Comment by boldcity** [comment]
picture of the user folder
https://gyazo.com/45db0e176fdc95c10117f09e4e84eaaf

**Comment by LeoColomb** [comment]
@boldcity Why do you close the issue? Solved? How? Thx 👍

**Comment by boldcity** [comment]
i deleted everything related to yourls and uploaded the files from the zip file instead of doing git clone and put it in its own folder and now it works still not sure what the actual issue was.
