### ISSUE TITLE
the YOURLS website is currently down

### ISSUE THREAD

**Issue by maustyle** [YOURLS/YOURLS#2313]
http://yourls.org/pluginlist

**Comment by maustyle** [comment]
http://yourls.org/wiki

**Comment by simon511000** [comment]
http://yourls.org/cookie+

**Comment by dgw** [comment]
@LeoColomb Looks like the fix you committed needs to get pulled down to the official server. :D

**Comment by ozh** [comment]
Nah, I think that's precisely this commit that broke everything. Will look into it.

**Comment by ozh** [comment]
For the record, turns out I think that's a separate issue
