### ISSUE TITLE
Show IP Address and User_Agent Data

### ISSUE THREAD

**Issue by orcunbaslak** [YOURLS/YOURLS#2317]
Is it possible to show IP addresses and User agents in the stats page? I'm using YOURLS only for myself. 

I can check the data via phpmyadmin but it would be much nicer to see it in the interface.

Br,

**Comment by ozh** [comment]
Yes. See wiki page "Possible with a plugin"

**Comment by orcunbaslak** [comment]
Hello Ozh,

I'm not a plugin writer and don't know PHP. It's very interesting not to have a such plugin. I've checked the list. Can you point me to a plugin that does this job?

**Comment by ozh** [comment]
If there is no such plugin in the list, it's because it doesn't exist as far as I know.
