### ISSUE TITLE
How many times yourls will try to create new keywords if found duplicate keywords?

### ISSUE THREAD

**Issue by plonknimbuzz** [YOURLS/YOURLS#2321]
* YOURLS version: 1.7.2
  * Plugins enabled: random keywords

Actually i was spending my lastest 2 days to find url shorten algorithm that suite for me. But i stop to find it after i realize that Yourls is to good to ignored. So I try using yourls with plugin **random keywords** enabled (62 encoding no hyphen).

--skip--
1. i look random-keywords/plugin.php is only random string without any unique id guarantee. So i guessing there is a loop function to try new keywords if found duplicate.
2. in includes/functions.php i found this https://github.com/YOURLS/YOURLS/blob/5725e562e0e749144e7390109e32eb3ee050dd6e/includes/functions.php#L266-L297

if im not wrong, there is unlimited try to find new possible non-duplicate keywords.
**my question:** is this true?

because i want to give limit if this true for my personal usage. 

thanks

**Comment by ozh** [comment]
Yes: when you want to store a new short URL, YOURLS will try with the given keyword till the given keyword is free (line 277).

Practically, this will mostly never happen. In the infinitesimal off chance that a provided keyword already exists, it will get another one from the plugin (line 276) and try again. Unless you plan on shortening literally trillions of URLs, you don't need to set a limit, and if so you just need to increase value of `$ozh_random_keyword['length']`

**Comment by plonknimbuzz** [comment]
i see. so, i think i no need give limit then .

thanks for the knowledge.
