### ISSUE TITLE
Acces detailed click logs

### ISSUE THREAD

**Issue by orcunbaslak** [YOURLS/YOURLS#2322]
Hello Ozh,

I'm not a plugin writer and don't know PHP. It's very interesting not to have a such plugin. I've checked the list. Can you point me to a plugin that does this job of accessing all clicks details such as agent-info, referrer, ip address etc?

Br,

**Comment by LeoColomb** [comment]
Please don't clear out the issue template when creating a new issue, it's there for a reason.
Not only is this a super vague request, but as @ozh answered you on #2317, you may find everything in [the wiki](https://github.com/YOURLS/YOURLS/wiki/Plugin-List).
