### ISSUE TITLE
Not getting referrer data or displaying $num_queries

### ISSUE THREAD

**Issue by hyxos** [YOURLS/YOURLS#2327]
* YOURLS version: current
* Plugins enabled: vanilla
* PHP version: 5

### Bug description 

I updated to the most recent version and noticed the $num_queries variable in the admin panel isn't populating. I also noticed that my most recent shortlink was not recording referrer data.
I believe it ma be related to this commit. 

https://github.com/YOURLS/YOURLS/commit/6bdd6a6d7eb0b274b96f52049da72a55a7e89405#diff-7fba462a75a3d192f9fa6f1b7816d170

I wanted to know if anyone else was noticing this issue and will be glad to go into more detail as necessary.

**Comment by ozh** [comment]
"Powered by YOURLS v 1.7.3 – 0 queries" ... Yep, indeed. Will look into this.

**Comment by maustyle** [comment]
i still haven't figured out how to see the referer for any link. 
correct me if i am wrong, but i expect to see a URL from which the user clicked the short URL.
i can only see the short link itself and no other URL where the link was supposed to be clicked from.
i tried to find an additional plugin to show more referes but i could only find plugins that hide the referer.

**Comment by ozh** [comment]
Issue is still marked "Opened" so....

**Comment by dylanh724** [comment]
Is this the same issue? I am getting # of hits, but I'm getting no referrer data:

![image](https://user-images.githubusercontent.com/8840024/49271862-67ecf400-f4aa-11e8-9491-f9fa7d89d001.png)

**Comment by ozh** [comment]
This was fixed some time ago.
