### ISSUE TITLE
Keep url extension

### ISSUE THREAD

**Issue by CheweyZ** [YOURLS/YOURLS#2329]
- [x] Check you are using the [**LATEST** release](https://github.com/YOURLS/YOURLS/releases/latest) or the development branch.
- [x] Make sure you have [**SEARCHED** existing issues](https://github.com/YOURLS/YOURLS/issues?utf8=%E2%9C%93&q=is%3Aissue) first. 
- [ ] Read the [**GUIDELINES**](https://github.com/YOURLS/YOURLS/blob/master/.github/CONTRIBUTING.md) linked in the yellow notice box above.
- [ ] **COMPLETE** this issue template.

Ability to save extension with short url ive noticed this as on many platforms sendinga short url of say an image then it wont render any thubnail so would be a really good option to add a flag for like "keep extension"

**Comment by ozh** [comment]
English, please.

If I have understood correctly, you want http://longurl/something.bla to be shortened with http://sho.rt/abc.bla : see wiki page https://github.com/YOURLS/YOURLS/wiki/Possible-With-A-Plugin
