### ISSUE TITLE
How to style admin panel?

### ISSUE THREAD

**Issue by Drumrocker365** [YOURLS/YOURLS#2330]
How do you style the admin panel? I am doing a private installation just for me, but I really can't stand how outdated the graphics look. I know, first world problem. Anyway, I was going to try and slap bootstrap on it and make it look a bit better. Please excuse me if this is the wrong place to post this... I have checked everywhere and I am not really sure how to ask for help. I am new to GitHub.

**Comment by LeoColomb** [comment]
Theming feature is on the roadmap (see #1234).
Currently it's not well supported.

**Comment by Drumrocker365** [comment]
@LeoColomb gotcha. Sorry, I somehow thought it was already supported. I'll be looking forward to when it becomes available!
