### ISSUE TITLE
Allow uppercase chars in short keywords

### ISSUE THREAD

**Issue by mhow2** [YOURLS/YOURLS#2333]
- [x] Check you are using the [**LATEST** release](https://github.com/YOURLS/YOURLS/releases/latest) or the development branch.
- [x] Make sure you have [**SEARCHED** existing issues](https://github.com/YOURLS/YOURLS/issues?utf8=%E2%9C%93&q=is%3Aissue) first. 
- [x] Read the [**GUIDELINES**](https://github.com/YOURLS/YOURLS/blob/master/.github/CONTRIBUTING.md) linked in the yellow notice box above.
- [x] **COMPLETE** this issue template.

### Technical details regarding my environment

* YOURLS version: 1.7.2
* Plugins enabled: Allow Hyphens in Short URLs, YOURLS Import Export
* PHP version: php 7.0
* Base 36 (default settings).

### Bug description 
I know there a several bug reports about this (but answers are missing because issue's imported from google code). I can't find a proper (easy) solution.

I need to enable all cases short keywords, as `LinK` or `link` to lead to any long URL.
From the FAQ I can read it's recommended *not* change from base 36 to base 62 as it would break my existing links.
So what is the solution here ?

**What is the current behavior?**
Can't use uppercase chars in keywords. (they are stripped).

This is not a bug, more like a support request for a use case that looks not so specific to me.

**What is the expected or desired behavior?**

A possibility to migrate from base 36 to base 62.

A workaround would be to use https://github.com/YOURLS/force-lowercase but as stated in the disclaimer, this is *not* a real solution.

**Comment by ozh** [comment]
Actually you CAN change from 36 to 62, because charset will expand.

But if in the future you decide to change back from 62 to 36 things could go wrong

**Comment by mhow2** [comment]
Thanks @ozh, that's what I was thinking but I was unsure. could you updated the FAQ ?
