### ISSUE TITLE
admin password reset

### ISSUE THREAD

**Issue by adinkrahene** [YOURLS/YOURLS#2337]
Great program thanks for allowing us to use it. I do have a question, how do I reset the admin password?
Thanks for your help in advance.
- [ ] Check you are using the [**LATEST** release](https://github.com/YOURLS/YOURLS/releases/latest) or the development branch.
- [ ] Make sure you have [**SEARCHED** existing issues](https://github.com/YOURLS/YOURLS/issues?utf8=%E2%9C%93&q=is%3Aissue) first. 
- [ ] Read the [**GUIDELINES**](https://github.com/YOURLS/YOURLS/blob/master/.github/CONTRIBUTING.md) linked in the yellow notice box above.
- [ ] **COMPLETE** this issue template.

### Technical details regarding my environment

* YOURLS version:
  * Plugins enabled:
* PHP version:
* Any other useful information depending on context (server OS & version, MySQL version, browser version, …)

### Bug description 

**What is the current behavior?**

This is a bug because…

**What is the expected or desired behavior?**

### Reproducible bug summary 

1. First step 
2. Second step
3. …

---

**Comment by PopVeKind** [comment]
Edit the `user/config.php` file to change the admin/user passwords.

See: `yourls_user_passwords` http://yourls.org/#Config

Just added in case any serious noob is looking for this...
