### ISSUE TITLE
Categories and/or keywords

### ISSUE THREAD

**Issue by solutionssquad** [YOURLS/YOURLS#2338]
Please allow me to preface the following with the fact that I am a newb at this!

I am trying to use URLS for internal user, where a shortened URL is listed on our WIKI for each of our clients, and then redirects to a dropbox link with files related to that client.
I have been given a fantastic budget of $0 for this.

What I need to be able to do, is distinguish between the links and clients. 
This would ideally mean that when a URL is being shortened, we can also fill a field that identifies the client it's for, which would also be searchable, editable and visible in the admin panel.

I tried using some of the code from some existing plugins but have failed.
The best I was able to do was update a field on the initial entry, but nothing else from there including the ability to edit.

Would anyone be kind enough to provide me with some assistance, code, or guidance on this?

Thank you in advance.

**Comment by ozh** [comment]
There's a plugin for multi user support. AFAIK nothing more at this moment.
