### ISSUE TITLE
How do I prohibit hyphens from being in short url links?

### ISSUE THREAD

**Issue by trstaley** [YOURLS/YOURLS#2344]
* YOURLS version: latest version from github as of 12/30/2017
  * Plugins enabled: none
* PHP version: 5.6 and 7.0
* Any other useful information depending on context (server OS & version, MySQL version, browser version, …)

NEED HELP
Occasionally short links are auto generated that contain a hyphen as the last character.  On android devices the link is displayed, but the hyphen is not actually part of the link.  Thus the link does not work.

This is not be a bug with Yourls, but rather is an Android issue.  I would like information on how to exclude hyphens from short urls.  I have been unable to find the information on the web thus far, which simply states how to exclude a character.  What I have found thus far talks about the random-keywords plugin; which I have not installed or any other plugins thus far.  Any help would be greatly appreciated.

**Comment by PopVeKind** [comment]
@trstaley - There are five core plugins that are automatically loaded with YOURLS. One of these is

- **_Allow hyphens in short URLs_** (like `http://sho.rt/hello-world`)

It is easy to activate this by mistake.  To deactivate this, follow these steps:

1. Login to the admin area of your account.
1. On the menu (top-left) click `Manage Plugins`
1. On the list find the row that says `Allow hyphens in short URLs`
1. Mouseover the `Action` column of that row and the word `Deactivate` will appear.
1. Click `Deactivate`
1. Check the status line under the word `Plugins` If you have no plugins activated it will say something like:
`You currently have 5 plugins installed, and 0 activated`
1. If it says **1** _(or more)_ **activated** you should review what plugins to have activated.
## Known Issues
Added character problems (hyphens, slashes, etc.) are known problems for various platforms.  Likewise, what to do with short URLs with added characters when the added character plugin is deactivated?

I am currently looking at code changes that would do the following:
1. Any keyword in the database would be valid _(if it got in there it was valid!)._
1. Any keyword could be edited/deleted from the database.
1. Automatically generated keywords would begin and end with an alphanumeric character (first and last characters would be letters or numbers within the valid range.).
1. Manually generated keywords would be considered valid and added to the database.

## Custom Charset
>  I have been unable to find the information on the web thus far, which simply states how to exclude a character.

**[yourls-additional-charsets](https://github.com/josheby/yourls-additional-charsets)** is a plugin that will allow you to create any custom charsets you desire.

**Comment by trstaley** [comment]
Thank you for that information.  I also found the plugin Keywords, Charset & Length which allows you to define the chars that are permitted in a short url.  This is what I needed.
