### ISSUE TITLE
Unable to get YOURLS to install [Uncaught PDOException] on nginx

### ISSUE THREAD

**Issue by blinkingline** [YOURLS/YOURLS#2350]
### Technical details regarding my environment

* YOURLS version: 1.7.3 Fresh install
  * Plugins enabled: None
* PHP version:  7.0.22-0ubuntu0.16.04.1
* Any other useful information depending on context (server OS & version, MySQL version, browser version, …)
Nginx version: 1.10.3-0ubuntu0.16.04.2

### Bug description 

**What is the current behavior?**

When I'm trying to install a fresh instance of YOURLS, I get everything set up and working and click "Install YOURLS", at which point the browser returns a 500 error.  Looking at the error log, it looks like this is being caused by something in PDO:

`    
2018/01/08 19:42:35 [error] 21546#21546: *5 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or acces$
Stack trace:
#0 /usr/share/nginx/YOURLS/includes/vendor/aura/sql/src/ExtendedPdo.php(748): PDOStatement->execute()
#1 /usr/share/nginx/YOURLS/includes/functions-install.php(252): Aura\Sql\ExtendedPdo->perform('CREATE TABLE IF...')
#2 /usr/share/nginx/YOURLS/admin/install.php(46): yourls_create_sql_tables()
#3 {main}
  thrown in /usr/share/nginx/YOURLS/includes/vendor/aura/sql/src/ExtendedPdo.php on line 748" while reading response header from upstream, client: 173.239.228.14$`

This is a bug because…

**What is the expected or desired behavior?**

It shouldn't throw an exception and install should complete. 
### Reproducible bug summary 

I've double checked by DB credentials, and they look good.  My nginx config looks like this (with server details removed)

```
# Rewrites
  location / {
    # Try static files, then yourls-loader.php
    try_files $uri $uri/ /yourls-loader.php?$args;
  }
    location ~ \.php$ {
        fastcgi_pass unix:/var/run/php7.0-fpm.sock;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_index index.php;
        include /etc/nginx/fastcgi_params;
        include /etc/nginx/fastcgi.conf;
     }

```

What am I missing?

**Comment by dgw** [comment]
The error message part is truncated. You are missing the actual error, which is somewhere after "Syntax error or acces" but before the stack trace.

Perhaps you can get the full error message from PHP's own log?

**Comment by blinkingline** [comment]
Sorry about that!  Full error message is:

`2018/01/08 19:42:35 [error] 21546#21546: *5 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes in /usr/share/nginx/YOURLS/includes/vendor/aura/sql/src/ExtendedPdo.php:748
`
I'm not sure what key it's talking about...

**Comment by dgw** [comment]
MySQL version could be relevant here.

Basically, the database is trying to create indexes and failing because the maximum index key length is too low for the character encoding you're using. Unless I'm mistaken YOURLS is more or less tweaked to operate on `utf8` databases, and mileage with other charsets may vary.

Enabling `innodb_large_prefix` in MySQL options might be a fix too, but it's probably better to just change the DB charset.

**Comment by blinkingline** [comment]
I'm running 10.0.31-MariaDB-0ubuntu0.16.04.2, and it looks like I'm currently on charset utf8mb4.  

I changed that to utf8 and enabled innodb_large_prefix too, just for fun, and that seems to have fixed it.  Thanks!

**Comment by dgw** [comment]
Yep, utf8mb4 means you have a roughly a quarter of the normal key length limit. Changing charsets on its own would probably have fixed it, but as long as you're happy running your database with `innodb_large_prefix` I don't think there's any measurable performance impact. Glad you got up and running!

**Comment by MoonCactus** [comment]
@blinkingline or @dgw may I ask how/where you fix that exactly?
I added `innodb_large_prefix=1` to`my.cnf` and restarted the sql server but it had no effect (mariadb 10.1 on ubuntu 18)

**Comment by MoonCactus** [comment]
It did fix my issue, many thanks!
```
ALTER DATABASE yourls CHARACTER SET utf8 COLLATE utf8_general_ci;
```

**Comment by joshp23** [comment]
I have my character set as InnoDB and was getting this error on upgrade. I changed collate to `utf8_unicode_cli` and the update ran fine.
