### ISSUE TITLE
YOURLS_COOKIEKEY - 3 Developer Questions

### ISSUE THREAD

**Issue by PopVeKind** [YOURLS/YOURLS#2359]
PHP version: 5.6.32
    Active Plugins:
        admin-ydb/plugin.php
    YOURLS Version: 1.7.3
    YOURLS DB Ver: 482

_Regarding /admin/config (DB config) and the full-fledged installer._

## - Ideas and structure
1. My idea is that the full-fledged installer should generate the initial cookie_key, and install it in the database.
1. The /admin/config would have a simple method (one click) to generate and install a new cookie_key.
## - 3 Developer Questions
1. The two pages cited below in References, appear to generate a key of semi-random _(at least no apostrophe)_, printable characters.  **Would someone share the exact code for this?** (no need to reinventing the wheel!).
1. **How long should this key be?** 32, 40, 64, 128. 256, 512, 1024, or 2048?
    1. [WordPress Salt](https://api.wordpress.org/secret-key/1.1/salt/) is now recommending 64 character keys, and reportedly changing to 128 character keys.
    1. Previously WP used 32 and 40 character keys.
    1. Today some web pages recommend using longer keys, even 256 or 512 and higher (2048 is even recommended by some paranoid about security!).
    1. Web pages giving YOURLS advice (older ones) often recommend something akin to a 32 character key.
    1. **This may be a good time to lengthen the key.** I'd recommend either 64 or 128 characters.
1. **Automatic cookie_key updates?**
    1. My friends at WPMU are recommending **64-128** character keys **AND _automatic updates!_**
        1. Daily
        1. Weekly
        1. Monthy
        1. During Admin Area Access.
    1. In WP this currently is available via WP plugins.
    1. It is reported WP Core will merge this in as a standard admin security setting.
    1. With the cookie_key moved to the YOURLS DB, automating its regeneration would be easy.
## - References
**config.php**
> A random secret hash used to encrypt cookies. You don't have to remember it, make it long and complicated. Hint: copy from http://yourls.org/cookie

**[ozh](https://github.com/YOURLS/YOURLS/issues/2255#issuecomment-303807745)**
> The cookie key ... you're supposed to make it long, complex, unique, and absolutely not memorable because you don't have to memorize it. Something like http://api.yourls.org/services/cookiekey/1.0/

**Comment by PopVeKind** [comment]
Would it be better to also randomise the **length** of the cookie_key (YOURLS_COOKIEKEY)?

## Fixed Length Examples
WordPress Salt is [generated](https://api.wordpress.org/secret-key/1.1/salt/) at a fixed 64 character length.
YOURLS_COOKIEKEY is [generated](http://api.yourls.org/services/cookiekey/1.0/) at a fixed 40 character length.

The fixed length gives an evil person some information useful in cracking into a system.

## Randomizing the cookie_key length.
What if while creating the cookie_key, we first randomized the **length**.  Fetch a random number between 0-9.  Add that number to 55 giving us a random range from 55-64.  We would then make our cookie_key that long, denying the cracker the fixed length information?

**Comment by ozh** [comment]
Yeah why not randomize cookie length. Sure. Honestly I don't get why you don't just ask that simple question instead of writing another chapter of a book.
