### ISSUE TITLE
Different urls via webinterface & api

### ISSUE THREAD

**Issue by TimoC1982** [YOURLS/YOURLS#2368]
### Technical details regarding my environment

* YOURLS version: 1.7.2
  * Plugins enabled: Allow Hyphens in Short URLs, Fix Long URL, Random Backgrounds, Sample Admin Page, Sample Plugin, YOURLS Toolbar
* PHP version: 7.0.2.5 on a Ubunto 16.04 Plesk Enviroment

### Bug description 

**What is the current behavior?**
Try to short a affiliate Link with the Interface: the complete link is shortend and usable. 
If i try to short a link with the API:
Curl Get: https://mydomain.com/yourls-api.php?signature=mysignatore&action=shorturl&format=json&url=http://partners.webmasterplan.com/click.asp?ref=829903&site=14435&type=text&tnb=8&diurl=http%3A%2F%2Fdreamlines.de%2Fnode%2F254590

I got an shortlink that works but send me directly to the affiliate hoster. I checked the respond an:

{
	"status": "fail",
	"code": "error:url",
	"url": {
		"keyword": "1",
		"url": "http:\/\/partners.webmasterplan.com\/click.asp?ref=829903",
                 "title": "Erfolgreiches Affiliate Marketing bei affilinet - affilinet",
		"date": "2018-02-28 13:20:39",
		"ip": "xxxxxxx",
		"clicks": "1"
	},
	"message": "http:\/\/partners.webmasterplan.com\/click.asp?ref=829903 already exists in database",
	"title": "Erfolgreiches Affiliate Marketing bei affilinet - affilinet",

It looks like that he didn't took the complete URL. on the Webinterface that Action works fine!

Same link as in the webinterface

I took a search on the issues (found nothing about that) and tried to fix that with the Long URL plugin without any luck, Hints?

Regards
Timo

**Comment by dgw** [comment]
You have to urlencode the long URL passed to the API.

`https://mydomain.com/yourls-api.php?signature=mysignatore&action=shorturl&format=json&url=http://partners.webmasterplan.com/click.asp?ref=829903&site=14435&type=text&tnb=8&diurl=http%3A%2F%2Fdreamlines.de%2Fnode%2F254590` is interpreted as `url=http://partners.webmasterplan.com/click.asp` and then `ref=829903` etc. as additional parameters to the API.

The function to urlencode depends on what language/environment you're sending the API calls from, but your API request URL should look like e.g. `https://mydomain.com/yourls-api.php?signature=mysignatore&action=shorturl&format=json&url=http%3A%2F%2Fpartners.webmasterplan.com%2Fclick.asp%3Fref%3D829903%26site%3D14435%26type%3Dtext%26tnb%3D8%26diurl%3Dhttp%253A%252F%252Fdreamlines.de%252Fnode%252F254590`
