### ISSUE TITLE
Suggestion - Add checkbox on Admin interface for bulk action

### ISSUE THREAD

**Issue by skeith** [YOURLS/YOURLS#2372]
### Technical details regarding my environment

* YOURLS version: 1.7.2
  * Plugins enabled: Keywords, Charset & Length, Mass Remove Links, YOURLSs Password Protection
* PHP version: 7.0.18
* Any other useful information depending on context (server OS & version, MySQL version, browser version, …) : Ubuntu 16.04, mysql 14.14

### Suggestion

I can only see #1294 being closed without any more details, so I wanted to revive the suggestion. Adding checkbox (not only on search results, but also on mail admin interface listing) will help on managing multiple links at once

**Comment by ozh** [comment]
I only imagine "Delete" being a practical implementation of this. See plugin Mass Delete maybe?

**Comment by skeith** [comment]
> only imagine "Delete" being a practical implementation of this. See plugin Mass Delete maybe?

Did you see my plugin list above? I already have Mass Remove, but it is not practical. Why? because it is using only filter such as date range, IP and URL contain. What if someone want to delete a set of links that is a combination of those three? They would do them three times.

And yes, I originally want this for delete functions because I haven't see any plugins that I need to do bulk action with.

**Comment by LeoColomb** [comment]
Thanks for your feedback @skeith!

> I already have Mass Remove, but it is not practical.

Maybe consider to create a pull request there? I'm sure this feature will be relevant for this plugin. 😺

**Comment by skeith** [comment]
I wish I could, I am not that savvy
