### ISSUE TITLE
Where is the HTML layout located?

### ISSUE THREAD

**Issue by BaileyJM02** [YOURLS/YOURLS#2373]
## -- **Not a Bug** --

Hello everyone,

So, I'm forking this repo and designing a new HTML/CSS layout. I would like some information:

- Where are the HTML layout files.. are they created within the PHP scripts?
- Is there any bits that are _delicate_ meaning that if I change them the whole layout will break? As in bits that kinda work but not really stable?

Thanks!

**Comment by dgw** [comment]
There aren't really layout files. YOURLS wasn't built with the "views" separated from the "control"/logic, so they're pretty intermingled.

AFAIK there's WIP theming in [the `2.0-wip` branch](https://github.com/YOURLS/YOURLS/tree/2.0-wip), but I have no idea how feature-complete or functional it is.

Ref: #1234
