### ISSUE TITLE
403 Forbidden error in title creation

### ISSUE THREAD

**Issue by jrsparkes** [YOURLS/YOURLS#2374]
I've looked through everything and can't find the same issue
I'm using YOURLS v1.7.2 installed using Softaculous on SiteGround hosting
I don't have any activated plugins
PHP version 7
Further info on server etc can be found here http://jos.tips/i.php

When I shorten a url for a website that's also hosted on my own SiteGround account I receive a "403 Forbidden Error" in place of the title. 
The shortened link actually works alright, but if want to maintain a proper record I'm having to go back and edit the title manually
Shortened links from other people's website domains have a correctly written title

![yourls403error](https://user-images.githubusercontent.com/15161055/37470229-fbeb74f6-285e-11e8-9ed0-fc265e9d841e.JPG)

(Picture explains what I'm seeing)

I went back to SiteGround as since it's only on domains in my own hosting account I figured it was something at their end. They came back to me saying they have double checked the server logs and are not seeing any information indicating that the access is actually prevented server-side, which leads them to believe that something within the application setting needs to be configured.

I can't find anything else to help me and wondered if it's possible to please point me in the right direction of what to do next or what to ask SiteGround for next, so that this will work properly.

**Comment by LeoColomb** [comment]
Thanks for your precise report @jrsparkes.

As we can see on the picture, and as you explain, only one domain (or so) follows the 403 behavior.
Then I'm pretty sure **this is not a YOURLS issue at all**, but much more an real error on your SiteGround site while proceeding the YOURLS request.

I often see this behavior when the target site block non-javascript-browsers, saying a javascript execution is required and denying access.
