### ISSUE TITLE
Search All Fields Not Providing Expected Results (lowercase vs. uppercase letters)

### ISSUE THREAD

**Issue by jamiers99** [YOURLS/YOURLS#2375]
I wasn't sure if I was supposed to link this to closed ticket #1770

### Technical details regarding my environment

* YOURLS version: 1.7.2
  * Plugins enabled: 404 Not Found. Allow Forward Slashes in Short URLs, Don't encode/decode, Short URL so what
* PHP version:  5.6.30
* Any other useful information depending on context (server OS & version, MySQL version, browser version, …):  MySQL 5.5.51-38.2, Chrome 64.0.3282.186 

### Bug description 

**What is the current behavior?**
I notice that when I use the search at the bottom of the page, that Title is not being searched for upper OR lower case letters.  I currently have 1.7.2 with plugins noted above:

I have two items in my entries for titles:
* Bulk Distribution Operations ILT
* Bulk Distribution Fundamentals WBT
When searching for 'bulk' no entries appear.  When searching for 'Bulk' both entries appear.

But... I have dozens of entries that show WBT in the title:
blah blah WBT
blah2 WBT
Blah Blah Blah3 WBT
When searching 'wbt' they appear, when searching 'WBT' they appear, but when searching 'Wbt' or 'wBt' they do not appear.

This is a bug because…  searching is not consistent with expected behavior of user.  Lower case letters are typically used in search engine queries.

### Reproducible bug summary 

1. Type word into search box
2. results not expected

**Comment by jinbo-yu** [comment]
if url contains char "%", the result is wrong too!

**Comment by jamiers99** [comment]
It doesn't appear as this has been fixed in 1.7.3.  Is this on the roadmap to be fixed?

**Comment by ozh** [comment]
I cannot reproduce this.

Test data : shorten URL with "WBT", "wbt" or "wBt" in the URL 🔴, short URL 🟠 or title 🟢 :
![image](https://user-images.githubusercontent.com/223647/161389732-85fa89ec-a97d-4ba1-baa4-3823312bf21f.png)


When I search for "WBT", "wbt" or "wBt" I get the expected result : 

1. ![image](https://user-images.githubusercontent.com/223647/161389798-c0664ffe-34a6-4314-b834-869d48a32e02.png)
2. ![image](https://user-images.githubusercontent.com/223647/161389771-264c0404-9956-44da-837f-5475adb70d4f.png)
3. ![image](https://user-images.githubusercontent.com/223647/161389810-7d33fb36-e88e-4151-a066-2e220405fa8f.png)

If I search for "wbT" for instance I get no result.

I guess the original issue was somehow fixed along the road. Feel free to reopen, or open a new issue with details, if this is not the case.
