### ISSUE TITLE
Is YOURLS down? When one of our shortened links is clicked we're getting "Fatal error - Incorrect DB config, or could not connect to DB'. Can't even get into our account.

### ISSUE THREAD

**Issue by GwenGIS** [YOURLS/YOURLS#2377]
- [ ] Check you are using the [**LATEST** release](https://github.com/YOURLS/YOURLS/releases/latest) or the development branch.
- [ ] Make sure you have [**SEARCHED** existing issues](https://github.com/YOURLS/YOURLS/issues?utf8=%E2%9C%93&q=is%3Aissue) first. 
- [ ] Read the [**GUIDELINES**](https://github.com/YOURLS/YOURLS/blob/master/.github/CONTRIBUTING.md) linked in the yellow notice box above.
- [ ] **COMPLETE** this issue template.

### Technical details regarding my environment

* YOURLS version:
  * Plugins enabled:
* PHP version:
* Any other useful information depending on context (server OS & version, MySQL version, browser version, …)

### Bug description 

**What is the current behavior?**

This is a bug because…

**What is the expected or desired behavior?**

### Reproducible bug summary 

1. First step 
2. Second step
3. …

---

**Comment by dgw** [comment]
That error means there's a database problem. Contact the person or company that runs your YOURLS site, we can't do anything about it.
