### ISSUE TITLE
Responsive design / Mobile friendly interface

### ISSUE THREAD

**Issue by koulaxizis** [YOURLS/YOURLS#2378]
Hey!! First of all, thank you very much for this great app!

I'd like to share a thought: I think that it's a huge downside the fact that YOURLS isn't responsive and mobile-friendly.

Are there any plans on that matter?

Once again, thank you for your efforts!

**Comment by dgw** [comment]
Lots of work has gone into redesigning for 2.0, see #1383 for example. It's not finished yet (e.g. #1621), and there's no ETA for when 2.0 will come out, but there are plans. :smile_cat:

**Comment by koulaxizis** [comment]
Looking forward to it! Keep up the good work! :)

**Comment by mtsmayad** [comment]
I wish YOURLS v2 is responsive,SEO friendly, Multi domains and multi themes ready ... I got stuck restyling the old up to my tasre :( http://icu2.cf/r/

**Comment by elimae17** [comment]
I love YOURLS. I've been using it for more than 7 years now without any problems! But I've always wondered about the lack of responsiveness. I just found this old post. Are there still plans to make YOURLS responsive at some point in the future?

**Comment by ozh** [comment]
More or less, but more "less" than "more" tbh
