### ISSUE TITLE
Yourls not redirecting and being indexed by Google 

### ISSUE THREAD

**Issue by directive** [YOURLS/YOURLS#2381]
Yourls not redirecting, being indexed by Google

Yourls is getting indexed, when it should be a 301 redirect to whatever page it points to
so if we make a Yourl short URL that is dit.io/somerandompage and it redirects to oursite.com/somerandompage, Google should see that as a 301 redirect and not index dti.io/somerandompage.

Basically we want to figure out how this URL is getting generated, really weird it's sticking a subdomain into it.

When you click on link the result is reproducible
https://www.google.com/search?q=backup+and+disaster+recovery+oneonta+ny

Here is screen capture:
![chrome_2018-04-09_10-04-32](https://user-images.githubusercontent.com/349601/38506928-39ec8644-3be9-11e8-9b69-52b0eb48d0af.png)

Thanks in advance for any assistance.

**Comment by PopVeKind** [comment]
@directive - 
There are many misunderstandings and misconceptions about both Google and the 301 redirect, let's see if we can sort some of these out.

# Domain Name
The first question I have is, is the YOURLS domain name **dti.io**

If it is, congrats!  You should tell us one short URL and what you expect it to do.  For example:

http://dit.io/yourls
should 301 redirect to
http://yourls.org/

You can make a temporary keyword if you deleted this already.

# https

Are you using http:// or https:// for your YOURLS?

If your admin area runs in https you will need to add
`define('YOURLS_ADMIN_SSL', true);`
in your config.php

If you want to use https in your short URLs you will need https something like:\
`define('YOURLS_SITE', 'http://dit.io');`
also in your config.php
> Yourls not redirecting

here are examples of actual, working keywords, `yourls` and `ozh`
http://a.fil.net/s/yourls
http://a.fil.net/s/ozh

These two keywords were loaded into your site from the beginning and unless you deleted them, they should still work and are great for testing your site.

You have provided us with no information as to any short URL that is or is not working.

> Yourls is getting indexed

The example URL you have given is:

https://boreas.dti.io/gallery/category/82-services/66-backup-and-disaster-recovery-for-oneonta-small-businesses.html

This is obviously NOT a YOURLS short URL, Likewise, following that Google listing leads to an https configuration error (which you need to fix first if this is your YOURLS site..

# Yourls is getting indexed

A misconception many people have is that Google never indexes pages that have 301 redirects.  This is not exactly true. However, in your case, Google did NOT index your YOURLS short URL,  Google indexed a page that seems to be configured incorrectly for https.

Can you give us a **real-world** example of a failure on your site?  For example...
http://dit.io/yourls
is not redirecting to...
http://yourls.org/
Then we can test it for ourselves and be better able to help you.

**Comment by ozh** [comment]
There's a badly misconfigured setup somewhere.

You're saying that your YOURLS instance is hosted at dit.io. Use a tool like http://www.webconfs.com/http-header-check.php for instance to see how page are redirected:
- http://dti.io/gfklgwmkgmfdkglmdfk returns a "302 Found" and redirects to `''` (empty string) when it should return a 404 and eventually redirect to http://dti.io/
- http://dti.io/admin/index.php returns a "302 Found" and redirects to http://dti.io/ when it should return a "200 OK" and serve content

On top of this there's something misconfigured with your HTTP/HTTPS choice and setup.

Everything you need to know is in the wiki, you should probably start with the .htaccess wiki page.
