### ISSUE TITLE
FAQ with better examples ? 

### ISSUE THREAD

**Issue by haywardgb** [YOURLS/YOURLS#2385]
I'm trying to get this working with Privatebin. The example urls provided in all the documentation I've read so far, doesn't give full urls , it cuts off the end leaving you to guess the rest . This url shortener came highly recommended in the privatebin community, but nobody seems willing to show how they got it working. 

At the risk of being an obvious noob.. Can anyone please explain to me how you use this with Privatebin . I don't want to use public urls, I want to use a token and that's where I'm getting stuck :(

Thank you .

**Comment by haywardgb** [comment]
Sorry. Gave up. Going to continue using your web app for personal use, it rocks in that respect. But I'll just let the users deal with long urls for privatebin. Sorry for the post.

**Comment by LeoColomb** [comment]
@haywardgb Thanks for this feedback!

Feel free to contribute and improve the documentation! 🙂

**Comment by PopVeKind** [comment]
@haywardgb - I just happened on this post today. Sorry you could not get it working.

I know NOTHING about Privatebin.

That said, YOURLS uses URLs that begin with something like http://sho.rt

**You said** you are trying to make it work with a token, but didn't mention what your token looked like.  If you have tokens that look something like `http://ti.ny/123` you might be able to get it to work.  But if your token looks like `localhost/123` or `~something/123` - that may cause you a problem.

> The example urls provided in all the documentation

Can you give a URL to this documentation? Is this YOURLS or Privatebin documentation?

> This url shortener came highly recommended in the privatebin community, but nobody seems willing to show how they got it working.

On the YOURLS Gihub you closed this after only 3 days.  I think many people do not log in for more than 3 days.  I try to log in at least once a week and totally missed your post before you closed it.

Did you try to PM anyone at the Privatebin site who recommended YOURLS?  I think that would be your best choice.  Try someone **[here](https://github.com/PrivateBin/PrivateBin/issues/238)** and**[here](https://github.com/PrivateBin/PrivateBin/wiki/FAQ#the-url-is-so-long-cant-i-just-use-an-url-shortener)** then post about how you did it on the YOURLS site.!
