### ISSUE TITLE
Delete 10 Core Constants from config.php and add to Database,

### ISSUE THREAD

**Issue by PopVeKind** [YOURLS/YOURLS#2387]
PHP version: 5.6.34
    Active Plugins:
        admin-ydb/plugin.php
    YOURLS Version: 1.7.3
    YOURLS DB Ver: 482

View (and play with) a working demo of a live YOURLS with DB Core Options.
http://a.fil.net/s/admin/db-config.php

The purpose of this project is to delete all Ten Core Constants from config.php leaving only the five DB constants.

Core Constants are problematic simply because they are constants.  Constants are also problematic due to typographical errors and misunderstood instructions.  All of these problems are solved by improving logic performance and making options selectable with a click, as a DB option.

This project deletes 10 options from config.php and adds 10 options to the Database.

There are three versions available on the menu at the top of the page.

**[View Normal](http://a.fil.net/s/admin/db-config.php)** - this is a short and sweet form.
**[View Noob Help](http://a.fil.net/s/admin/db-config.php?dev=noob)** - this adds some Noob Help to the normal form and reveals all Defaults.
**[View Developer Notes](http://a.fil.net/s/admin/db-config.php?dev=notes)** - Here you can view what is being stored in the DB via the $ydb property.

**Comment by LeoColomb** [comment]
Closing in favor of #2388
