### ISSUE TITLE
Where is the YOURLS Road Map?

### ISSUE THREAD

**Issue by PopVeKind** [YOURLS/YOURLS#2390]
Technical details regarding my environment:

    YOURLS version: 1.7.3
    Plugins enabled:
        admin-ydb/plugin.php
    PHP version: 5.6.34
    OS: Linux
    Web Server: Apache/2.4.29
    YOURLS DB Ver: 482

**Can someone tell me the URL for the YOURLS Road Map?**

I just get a 404 error.

**Comment by LeoColomb** [comment]
https://github.com/orgs/YOURLS/projects/1
