### ISSUE TITLE
HTTPS Plugin Development

### ISSUE THREAD

**Issue by PopVeKind** [YOURLS/YOURLS#2391]
@ozh commented on [Dec 16, 2017](https://github.com/YOURLS/YOURLS/issues/1254#issuecomment-352122921)

> # HTTPS
> 
> I think this should not be part of the installer. The one think I don't want to end up with is an installer with a gazillion options to pick from. Since this does not depend on YOURLS but primarily on the server setup, I think YOURLS should not care about this.
> 
> For the record, as of writing, 89.9% of YOURLS install are on http instead of https. The truth is: the vast majority of people just don't care. It's a personal URL shortener, no sensitive data transmitted, it just works, period.
> 
> This said, I like your "one pulldown" concept, and I think that would make a neat plugin. That would even make a neat core plugin and we could deprecated a couple YOURLS_ constants. That would really make a worthy PR to work on, and with it we could do our tiny part in promoting https.
> 

I agree!  In fact, I would say we need to deprecate **ALL** YOURLS_ constants (except the 5 for the DB).  This might be the start of that. I think we should get rid of **All [10 Core Options](http://a.fil.net/s/admin/db-config.php)** and replace them with **_Optional Core Plugins!_**

The thinking here is if you do not need https, why be forced to set an option to HTTP?  Likewise, if you need English, Private, Zero hours offset, Unique URLs, 36 Character Charset, etc. Why do you need an option for what should be the default?  HTTP/HTTPS is the same.  Each of these only needs a Plugin for the Limited Few that doesn't want the default. A Core Plugin for the exception, not a required option for the default!

This issue is to discuss a new Core Plugin, **HTTPS**
This will replace the mess of YOURLS_ constants and code that is currently being used.

**Comment by PopVeKind** [comment]
# Incoming HTTP/HTTPS
As ozh pointed out, there really is no difference between HTTP and HTTPS on an arriving request, once it reaches the YOURLS program.  In fact, YOURLS is largely blind to both the protocol (HTTP/HTTPS) issue and the domain name.  This is really the way it should be.  Once a request reaches YOURLS it need only process the keyword or deliver the admin page.
# Restricted Access
If it is desired to do something like restrict a domain name, or to restrict access to the admin directory, this should be done in server settings.  For example, in Apache `.htaccess` one might want to restrict access to the admin directory to HTTPS.

### Therefore, YOURLS needs to do NOTHING based on the Incoming Domain Name or Incoming Protocol (HTTP/HTTPS).

**Comment by PopVeKind** [comment]
# In the beginning...
In order to come up with a **Great HTTPS Plugin**, let's take a look at our history.  Why is HTTP/HTTPS a problem?

To begin with, YOURLS was not designed for HTTPS.  It had a simple constant, YOURLS_SITE, that was used for the file location, for links to the admin area, for building ShortURLs, and for the protocol for everything.  Things were simpler back then. Four purposes and only one constant! Efficient under the conditions that existed back then.
# HTTPS is Born
With HTTPS we crashed head-on with YOURLS_SITE.  Anyone who has worked with PHP constants can tell you one thing about them, they are constant!  They don't change!  But now we needed YOURLS_SITE to be sometimes HTTP and sometimes HTTPS!  So we embarked on a bunch of programming to attempt to change a constant without changing a constant.  Sounds like a mess right?  Well...

We tried matching the protocol to that received and finally came up with the idea for the code behind `YOURLS_ADMIN_SSL`. - and that is where we are now.
# A Better Idea
It may have been better to just build two constants, on for Short URLs and one for Links to the admin area. But that idea has problems too!  For example, adding yet another constant to the soup!

**Comment by PopVeKind** [comment]
# Good, Better, Best
1. The best idea then is to get rid of the problem, `YOURLS_SITE`.
1. And get rid of the problem fix, `YOURLS_ADMIN_SSL`.
1. Then assume the default (HTTP everywhere).
1. Finally, make an HTTPS Core Plugin that sets a database option when HTTPS is needed. Either in the admin area only or in everything, as selected in the HTTPS Plugin.
# Mixing it Up
So how do we replace `YOURLS_SITE`?
Assume `YOURLS_SITE` was originally `http://sho.rt`
The default or the database option currently has the correct `http://` or `https://`
`$_SERVER['HTTP']` is equal to the domain `sho.rt`
Together these two are a direct replacement for `YOURLS_SITE` with the correct protocol already applied.

# $_SERVER['HTTP']
**Note:** `$_SERVER['HTTP']` is safe to depend on.  75 million WordPress sites and all YOURLS sites currently depend on this already.

**Comment by PopVeKind** [comment]
# Developers
I know the above is quite long.  It is for Developers who want to understand the problem and the path to a solution.  It is not a summary, but a roadmap.  It has enough detail that developers could understand what is happening.

**Comment by dgw** [comment]
@PopVeKind Please be mindful that every time you post something (an issue or a comment) in the YOURLS repo, 300+ people get an email. Given the choice between a long reply (about which @majordome will complain) or several short replies, prefer the option that generates the fewest emails: one long reply.

**Comment by PopVeKind** [comment]
# TWO URLs
It should be noted that YOURLS does not directly interact with HTTP/HTTPS/SSL/TSL
All of these interactions are done by the web server (nginx, apache, etc.).

The only thing YOURLS does is use the HTTP/HTTPS protocols in making two kinds of URLs:
1. A ShortURL (perhaps `http://sho.rt`)
1. An AdminURL (perhaps `https://sho.rt`)

# ORIGINAL YOURLS
The original YOURLS used an option (constant), `YOURLS_SITE`, to supply both the protocol and the domain name.  Something like `http://sho.rt` (with no trailing slash).  The problem began when people wanted to use HTTPS for their admin pages, PHP does not allow a constant to be redefined.

# YOURLS TODAY
Today YOURL:S adds another option (constant), `YOURLS_ADMIN_SSL`  It activates some rather complex code to try to determine what URLs should start with `https://` and which should begin with `http://`

# Simplify Code
1. Remove all code added because of HTTPS.
1. Delete Options `YOURLS_SITE` and `YOURLS_ADMIN_SSL`
1. Create a Core Plugin that stores two things in the database
    1. A ShortURL Protocol (`http://` or `https://`)
    1. An AdminURL Protocol (`http://` or `https://`)
1. If either Protocol is empty in the database (No HTTPS Plugin), default to `http://`
1. Adjust the code for link URLs as follows:
    1. For ShortURLs: `YOURLS_SITE` is replaced with:
The ShortURL Protocol +  $_SERVER['HTTP_HOST']
Example: `http://sho.rt`
    1. For AdminURLs: `YOURLS_SITE` is replaced with:
The AdminURL Protocol +  $_SERVER['HTTP_HOST']
Example: `https://sho.rt`

# Trailing Slash Error
Although not designed for it, this PR would completely eliminate the trailing slash error.

`YOURLS_SITE` and `YOURLS_ADMIN_SSL` should be deleted from config.php but if not, they would simply be ignored.

**Comment by PopVeKind** [comment]
# DELETE YOURLS_SITE

One Critical part of this plugin will be to delete the constant `YOURLS_SITE` and replace it with its component parts in the database required to build a replacement.  For example, to support **MultiSite**, the domain name should not be stored in an option or the database.

The database should store separately two HTTP(S) protocols, one for the ShortURLs and one for the AdminURLs   This can be accomplished by a single setting in the **HTTPS Plugin** similar to **the [DB Options Demo](http://a.fil.net/s/admin/db-config.php) No. 10**. 

I would NOT recommend this be a Core Plugin (this plugin does not ship with YOURLS) as less than 11% of sites would use it.  I do recommend the **HTTPS Plugin** be maintained by the **_Core Team_** as it is required for sites using HTTPS for any purpose.

The other parts of `YOURLS_SITE` could be replaced by PHP code.

_Core Team recommendations would be appreciated._

**Comment by ozh** [comment]
Delete a constant and move all HTTPS functionality to a plugin? Yes, PR very welcome on this.
