### ISSUE TITLE
Does the server take it?

### ISSUE THREAD

**Issue by valbiojun** [YOURLS/YOURLS#2392]
### Technical details regarding my environment

* YOURLS version: v 1.7.2
  * Plugins enabled: noone
* PHP version: 5
* Any other useful information depending on context (server OS & version, MySQL version, browser version, …) Server with 8 CPUS 8Gb Ram Memory 3TB Disk

### Question description 

We are trying to bring into our advertising agency a URL shortener and we need to make sure our server could handle doing this.

Our question is, how many simultaneous redirects can be performed without compromising the server's functioning because as an agency we have shortened urls that can be clicked simultaneously by tens, hundreds and sometimes thousands of people at the same time.

Anyone have any idea if the server settings listed above can account for such a situation?

Thanks

Junior

**Comment by ozh** [comment]
This should help: https://github.com/YOURLS/YOURLS/wiki/Public-Shortening#performance
