### ISSUE TITLE
How To add to the Roadmap?

### ISSUE THREAD

**Issue by PopVeKind** [YOURLS/YOURLS#2393]
# Roadmap
The old roadmap was deleted and many things were not transferred to the new one.  Does the old roadmap exist anywhere for reference?

- I would like to see **#1344** added to the RoadMap under **ideas**.
- I would like to see **#2388** added to the RoadMap under **To do**.
- I would like to see **#2391** added to the RoadMap under **In progress**.

Each of these will require a PR and Plugin and will delete one or more YOURLS_ constants and options.
# Pull Request
The Pull Request Wiki states: 

> Please ask first Before embarking on any significant pull request

I may have missed it, but I cannot find the method I should use to **"ask first?"** Is there an example somewhere of how to do this?

I would like to work on the **PR** and _HTTPS Plugin_ proposed by @ozh and described in #2391

==========

**Comment by LeoColomb** [comment]
> How To add to the Roadmap?

You can't. Road map edition is reserved to the core team.
Note that road map is only indicative and not strictly followed.

> I should use to "ask first?" Is there an example somewhere of how to do this?

This means avoid opening a new-feature-PR without a discussed orientation, to avoid contributor wasting time on a non-desired/out-of-scope feature.

Feel free to read more about how to contribute on the [Open Source Guide](https://opensource.guide/how-to-contribute/). :octocat: 

> work on the PR and HTTPS Plugin

Plugins are not supposed to be submitted directly with a PR. Feel free to create a new repo for each new plugin. 👍 
See https://github.com/YOURLS/plugin-sample
