### ISSUE TITLE
GDPR compliance

### ISSUE THREAD

**Issue by simonrperry** [YOURLS/YOURLS#2395]
Hi - We're regular users of YoURLs and love it. You've done a great job.

With locking down our GDPR compliance (as I'm sure you all are/have been) and it occurred to me we should find out if YoURLs is touched.

I know this plugin has been working successfully without a need to update it for a year, so sorry to drag you back to it.

Have you looked over YoURLs to see if any there's any data stored (guess visitor's IPs) that has GDPR compliance issues? 

Thanks in advance.

**Comment by LeoColomb** [comment]
YOURLS is sadly not GDPR compliant out-the-box. We're working on it.
See #2386 (which is closed for the feature request but relevant for the current status of YOURLS-GDPR).

**Comment by simonrperry** [comment]
Many thanks Leo - Good to see you already on it.

(Not sure why that thread didn't come up in my GDPR search. No matter)

**Comment by Pippen78** [comment]
Hi there,

are there any news on the GDPR compliance issue? I am running YOURLS with the rather old Pseudonymize plugin but it seems to me that obfuscating the last bit of IPv4 and IPv6 addresses (or in this case replacing them with zero to make them untraceable to an individual) is exactly what Rebrandly are doing to anonymise IPs: "To produce click metrics we analyze a variety of sources of data, none of them considered personal data under GDPR- save for the IP address. While an IP address can be considered personal data, we anonymize it by truncating the last class of digits prior to any reporting or storing. As such, no personal data is stored and Rebrandly click metrics are not subject to GDPR laws. Even cases of IPv6, we anonymize the data and remain compliant." (https://support.rebrandly.com/hc/en-us/articles/360009909513-Rebrandly-URL-shortener-is-GDPR-Compliant)

So is this what this old plugin does? Anonymising before anything is stored? Will this become a core feature? It seems to me that this is quite important...

Thanks for the update and keep up the great work!

**Comment by ozh** [comment]
"Will this become a core feature" : definitely not. I'm wildly uninterested by the matter, I must admit. Not sure what @LeoColomb was referring to when mentioning "we're working on it". To me it's definitely plugin territory.

**Comment by dgw** [comment]
> Not sure what @LeoColomb was referring to when mentioning "we're working on it". To me it's definitely plugin territory.

Why is this issue still open, then?

Let's just close it and move on, unless the plan is (eventually) to ship a plugin _with_ YOURLS that would address this, just not enabled by default.
