### ISSUE TITLE
Support for lighttpd

### ISSUE THREAD

**Issue by okoestner** [YOURLS/YOURLS#2396]
Version: v 1.7.2
PHP: 7.0

I installed yourls successfully on my raspi running lighttpd. Unfortunately when trying to access a shortened url I get a 404 error :(

Lighttpd does not support .htaccess files. Might this be the reaseon?

Did anyone successfully install yourls on lighttpd? How would the config file for the yourls vhost or directory need to look like?

**Comment by dgw** [comment]
See #1809, where a couple of other users shared their lighttpd configurations for YOURLS.
