### ISSUE TITLE
404 errors after switching site to PHP7

### ISSUE THREAD

**Issue by dougdavis22** [YOURLS/YOURLS#2397]
### Technical details regarding my environment

* YOURLS version: 1.72
  * Plugins enabled: Random Keywords 1.1
* PHP version: cPanel ea-php55 (cli says 5.6.36)
* Any other useful information depending on context (server OS & version, MySQL version, browser version, …)

### Bug description 

**What is the current behavior?**

YOURLS running fine on the above configuration.  If I switch the server to run PHP7 via cPanel, YOURLS starts failing with 404 errors to shortlinks.

This is a bug because…

**What is the expected or desired behavior?**

YOURLS should behave as per current configuration.

### Reproducible bug summary 

1. Switch server to PHP7 via cPanel
2. Create new shortlink in YOURLS admin
3. Navigating to the shortlink gives 404 error

---

Reverting to previous PHP version resolves the issue.

**Comment by dougdavis22** [comment]
I literally just get redirected to my site’s 404 error page.

**Comment by LeoColomb** [comment]
So YOURLS and your site live in the same directory? Are you **sure** your server configuration is compatible with PHP 7 and try first YOURLS before running your site?

**Comment by dougdavis22** [comment]
Apologies - I've just switched to PHP7 again and tested and it seems to be fine now.  God knows what I was doing last time to cause this!

Please go ahead and close the issue.  Thanks.
