### ISSUE TITLE
Storing Database Constants outside of config.php

### ISSUE THREAD

**Issue by Nhaztaljik** [YOURLS/YOURLS#2400]
I am using YOURLS version 1.7.2, no plugins.

I am attempting to store database constants in a file outside of the repository. I am calling them with a require in the config file. This is causing the URL loader to break somehow. My admin panel still works, though accessing short URLS simply results in a 500 error. Everything works fine when database constants are defined where they should be. 

Is there anyway to get this concept to work without breaking the URL loader?

**Comment by ozh** [comment]
Just `<?php require('/path/to/my/config/file.php'); ?> from `user/config.php` ...

**Comment by Nhaztaljik** [comment]
I've already done this as I mentioned in the original thread. It works... but causes URL loader to break.

**Comment by ozh** [comment]
YOURLS reads `config.php` upon loading. Just as any PHP script, it doesn't care if information is stored in this file, or if the file just loads another file, or whatever. Loading `config.php` occurs in the same way upon YOURLS instantiation, be it for displaying dashboard or redirecting. The behavior you report is linked to something else in your setup than just doing a proper `require(/physical/path/to/file.php)`
