### ISSUE TITLE
Any suggestions? Criticism welcome - Finishing touches on fallback redirection plugin

### ISSUE THREAD

**Issue by mvs12** [YOURLS/YOURLS#2404]
In [another thread](https://github.com/YOURLS/YOURLS/issues/2403) I asked whether YOURLS could **simultaneously** work as normally for existing keywords, **while also** redirecting anything not existing to another domain. Predictably, it's possible...just not right out the box. There doesn't seem to be a plugin for it, either. By the way, thanks to @LeoColomb for the quick response. 

Rather than complaining or dropping the subject, I thought I'd follow LeoColomb's and @Ozh's advice in countless other threads to write the plugin myself. After all, Seeing how writing the plugin yourself always gets encouraged, and that the plugin page is also [pretty inviting](https://github.com/YOURLS/YOURLS/wiki/Plugins), it might be worthwhile. Thankfully it paid off (unless there's some error I'm unaware of). Despite not having a clue about programming in php, some 10 grueling hours later I now have a working plugin.  Regardless, I've learned a ton.

**While it does work, I was hoping for some input on anything I'm doing in a "hack" way**. Or anything that I might simply have not tested for. The gist for the code is here:

[**Plugin - Fallback Domain Redirect with UTM**](https://gist.github.com/mvs12/ce6db0b608fe204bd381d7425bd5896b) - Working but still in progress

**What the plugin does:**
- **Redirects the original URL to the fallback domain like a wildcard redirect** 
   i.e.   sho.rt/blog/the-beach/232#heading1   →   
          MyLongDomain.com/blog/the-beach/232?utm_source=xyz#heading1
- Works with anchor links.
- If the sho.rt keyword exists, it doesn't interfere.
- Adds hyphens and slashes to the character set.
- Removes any UTM parameters if present before redirecting to the fallback domain.
- Adds a UTM Source parameter
- Creates a configuration page.

Anyway, unless there's something catastrophic I'm not aware of, the plugin seems to be working OK for me. Or at least it solves my initial needs.

If this is something that there would be public interest for (other threads seem to indicate that might be a possibility), then I'd be inclined to put more time and effort in. But if not then just for my own use it's probably not worth it to complicate it further.

In any case, for someone who woke up this morning without much of a clue of php or plugins, I feel a bit proud of my self. Though now I need to go die on the sofa a few hours...

**Comment by ozh** [comment]
Just reading the code, havent tried the plugin, some feedback:
- prefix all your functions and stuff with a unique name. "hyphen_in_charset" is way too generic. For instance use "fdrutm_" as a prefix for everything.
- stick to one code standard. For instance, opening braces one the same line as "function stuff()" or the "if" test, OR on the line after, but dont' mix styles, it makes reading code difficult. Same comment about indentation which is sometimes present and sometimes lacking, very difficult to read. See https://github.com/YOURLS/YOURLS/wiki/Coding-Standards
- function slash_in_charset() blindly adds slash to the charset. What if there is already another plugin that adds it? Not sure how things will work with 2 slashes in the charset, better check before adding. Same for hyphen.
- I don't get what the opening brace on line 112 is for. I don't see any matching "if" or function declaration. Or maybe your inconsistent coding style lost me, but I think that's a problem.

**Comment by mvs12** [comment]
Thanks for the input.
- Yeah, that isn't so much an inconsistent coding style as much as it is a lack of coding style. I'm learning as I go. At this point I'm much more concerned with getting it working as desired. In any case, I definitely appreciate uniformity, so I'll take care of that as I go.
- "hyphen_in_charset" is way too generic." - Yeah that was extrapolated from the [Allow Forward Slashes in Short URLs plugin](https://github.com/williambargent/YOURLS-Forward-Slash-In-Urls/blob/master/plugin.php). I've learned since.
- "function slash_in_charset() blindly adds slash to the charset" - Thankfully, I've since changed the method of getting the URL altogether. Now the plugin no longer requires modifying the charset, works with a much wider variety of charactcers plus it probably runs a lot quicker too. Before it was treating URL path as a keyword. Now it simply saves the path and makes use of it if the keyword is wrong or the loader can't understand the request.

Basically, **at this point the main question is if this is a plugin whose function you think would be valuable to other users**. That functionally being URL forwarding to a different domain for non-existent shorturls. If this is something that, properly functioning and vetted (or however these things are done), you'd be interested in adding to the plugin list, then I'd be willing to put in a different amount of effort than if it's just for me. Mainly with regards to making sure it works with situations that don't apply to me. If you don't think there would be enough interest to warrant that, which is perfectly fine, then I'd probably just leave it as is and not bother packaging it in a shareable form.

Just in case it isn't clear, the usage scenario is:

Someone owns the website:
https://www.JanesTenneesseFlowerhop.com/

And a given existing URL for that site is:
https://www.JanesTenneesseFlowerhop.com/weddings/bouquet/arrangement-[1]

If the person is on the go and simply wants to have a shorter, easier to spell and share URL without having to create a keyword for it, instead of the previous URL they could share:
https://JTFlowers.com/weddings/bouquet/arrangement-[1]

Which would redirect to:
https://www.JanesTenneesseFlowerhop.com/weddings/bouquet/arrangement-[1]/?utm_source=yourls

It certainly is convenient for one-time use URLS to write on the back of a business card or whatever. The UTM source is optional and to allow the user to see how much use they're getting out of method, and to distinguish it from direct traffic.

Anyway, let me know if you think this would be useful enough to others to warrant putting in the last 10% of effort or not.

**Comment by ozh** [comment]
> Anyway, let me know if you think this would be useful enough to others to warrant putting in the last 10% of effort or not.

Well, if that's useful to you, and since there are dozens of thousands of users, there are probably a couple others who would find this useful, I guess.
