### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by wci-aw** [YOURLS/YOURLS#2406]
- [y ] Check you are using the [**LATEST** release](https://github.com/YOURLS/YOURLS/releases/latest) or the development branch.
- [y ] Make sure you have [**SEARCHED** existing issues](https://github.com/YOURLS/YOURLS/issues?utf8=%E2%9C%93&q=is%3Aissue) first. 
- [y ] Read the [**GUIDELINES**](https://github.com/YOURLS/YOURLS/blob/master/.github/CONTRIBUTING.md) linked in the yellow notice box above.
- [ ] **COMPLETE** this issue template.

**Describe the bug**

**To Reproduce**
1. Go to 'http://2share.info/wci'
2. See error:
Not Found
The requested URL /wci was not found on this server.
Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

**Expected behavior**
Usuell the site with corresponding link shall be opened http://2share.info/wci > https://www.worldcheckin.com but instead a 404 failure is displayed in browser.
Failure Screenshot > https://www.screencast.com/t/TcK1N0Vt
DC screenshot > https://www.screencast.com/t/qtGBY6x5bf

I have just updated version 1.7 to 1.7.2 and pointend then into new folder public_html/2share.info/yourls/YOURLS-1.7.2_AW
Url Folder Screenshot > https://www.screencast.com/t/6sECeM0V then, the error ocur.

I have then tried to switch back to old version by pointing back into old folder
public_html/2share.info/yourls/YOURLS-1.7_AW also even tried to switch PHP version from 5.6 to 7.1 pr 7.2 with same failure.

**Environment (please complete the following information):**
- YOURLS version: 1.7.2
  - Plugins enabled: 
Allow Hyphens in Short URLs; Fix Long URL; Force Lowercase; Google Analytics; Google Safe Browsing; Popular Links; QR Code Short URLS
- PHP version: 5.6
- Other relevant details depending on the context (
server version perl 5.16.3, cpanel vers. 72.0 (build 7), appache 2.4.33, Linux
MySQL version, 5.6.39
browser version, …)

**Additional context**

**Comment by LeoColomb** [comment]
This error always comes from a bad `.htaccess` configuration.
Be sure to have:
* A valid `.htaccess` configuration
* A working Apache with all needed extensions (i.e. `mod_rewrite`)

**Comment by wci-aw** [comment]
Hi support team,

1. the addon domain has been recently migrated from cpanel account worldcheckin to wussleri 
2. the addon domain has pointed to public_html/2share.info/yourls/YOURLS-1.7_AW
then I made and update of yourls software by creating a new folder and pointed then the addon to public_html/2share.info/yourls/YOURLS-1.7.2_AW
3. then I tried to use a combination of wordpress with yourls combined apppoach by mixing the software in folder public_html/2share.info/wp+yourls
4. As I found out, that the forward of shorten links is not working any more I have then pointed the addon domain back to public_html/2share.info/yourls/YOURLS-1.7.2_AW without success.

I cannot say if it has worked before (right after migration 1 week ago) as I did not checked about the same if there is a problem existing after the migration. The only thing I can say is, that it is already not working because of httaccess rules.

The goal is to use the mixed approach with the addon domain share.info to point to folder public_html/2share.info/wp+yourls to use wordpress together with yours.

Please help to find out how to estabish this and adjust or give advice to change the htaccess rules correspondingly.

Best, Alex

**Comment by wci-aw** [comment]
Hi just be informed,

to enable a combined usage of "yourls" together with "wordpress" in one folder where software is installled. In my case it has helped to use these rules. Will you agree or would you suggest any other approach or rules to be used?

Best, Alex

```
# BEGIN YOURLS
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^.*$ /yourls-loader.php [L]
</IfModule>
# END YOURLS


# BEGIN WordPress
#<IfModule mod_rewrite.c>
#RewriteEngine On
#RewriteBase /
#RewriteRule ^index\.php$ - [L]
#RewriteCond %{REQUEST_FILENAME} !-f
#RewriteCond %{REQUEST_FILENAME} !-d
#RewriteRule . /index.php [L]
#</IfModule>
# END WordPress
```

**Comment by LeoColomb** [comment]
> to enable a combined usage of "yourls" together with "wordpress"

[As explained in the wiki](https://github.com/YOURLS/YOURLS/wiki/.htaccess), this situation **can't** be done.

> Yourls Url: http://2share.info/wci forward to worldcheckin.com > 404 Error

I can only stick to [my previous advice](https://github.com/YOURLS/YOURLS/issues/2406#issuecomment-401616044).

Be sure to have:
* A valid `.htaccess` configuration
* A working Apache with all needed extensions (i.e. `mod_rewrite`)

**Comment by LeoColomb** [comment]
I'm closing since it doesn't seems to be a real bug with YOURLS, but feel free to continue the discussion here.
