### ISSUE TITLE
YOURLs breaking URLs with ä in them

### ISSUE THREAD

**Issue by fncll** [YOURLS/YOURLS#2408]
**Describe the bug**
Creating short links to URL's with an ä in them results in a non-functional link.

**To Reproduce**

1. Shorten a URL such as http://www.artnet.com/artists/käthe-kollwitz/

2. In YOURL's admin the link will be borked: http://www.artnet.com/artists/k%8Athe-kollwitz/ and 

**Expected behavior**

A link that works. Properly encoded or not encoded. I am not sure.

**Environment (please complete the following information):**
- YOURLS version: 1.7.2
  - Plugins enabled: Allow Hyphens in Short URLs

**Comment by dgw** [comment]
I tested the given URL (`http://www.artnet.com/artists/käthe-kollwitz/`) in my own YOURLS instance, which is still (perhaps shamefully) running YOURLS 1.7.1. It seems to work fine, and I also have the "Allow Hyphens in Short URLs" plugin enabled.

![image](https://user-images.githubusercontent.com/164140/42435287-a5fb2e3e-831b-11e8-8976-1e1c7d874a48.png)

If I click the short URL, it works. The long URL works, too.

It also works if I copy the link from my browser's (Chrome on Ubuntu) address bar after clicking it, and shorten the pre-encoded version, `http://www.artnet.com/artists/k%C3%A4the-kollwitz/`.

![image](https://user-images.githubusercontent.com/164140/42435384-f984c9b6-831b-11e8-8330-7083404fcf58.png)

I would first suspect a configuration issue with your webserver, which you did not disclose in your report. (HTTPd name and version as well as OS name and version would be helpful.) I don't want to speculate too much, but this is the most likely reason.

There could also be a regression in YOURLS itself, I guess. I'll have to create a local test instance of 1.7.2 with the same plugin enabled and try the two URLs again on it.

**Comment by dgw** [comment]
Update: I quickly set up a new YOURLS instance from the 1.7.2 archive on my localhost (Ubuntu 18.04) running under PHP 5.6 (FPM) and nginx. It shortens the given URL perfectly fine, just as my production instance running 1.7.1 does. So it seems this is a configuration problem with your server, @fncll. Please provide further details on your environment as listed above (the webserver you're using, what PHP version, on what OS, etc.) and I or another user will try to help you fix this.

Closing the issue, as it does not appear to be a bug, but please do continue the discussion. :smile_cat:

**Comment by fncll** [comment]
I apologize for not providing full information. When I went to check my PHP settings I discovered it was running PHP 7.0 -- perhaps an artifact of a recent server move. At any rate, things are fine with PHP 5.6.

**Comment by dgw** [comment]
That's interesting. I created a PHP 7.2 test instance just now and it also works correctly. Then I switched it to PHP 7.0… it also works correctly.

I don't know what caused the issue on your server, but I am glad that it doesn't appear to be a compatibility problem between YOURLS and PHP 7.x. And I'm glad you got it solved on your end! :smile_cat:
