### ISSUE TITLE
New iOS app for shortening YOURLs URLs

### ISSUE THREAD

**Issue by jooonni** [YOURLS/YOURLS#2410]
I developed a **full native iOS app** for shortening URL. It is available on the App Store since a few days.
Click [here](https://itunes.apple.com/sa/app/yourls-shortener/id1404639770) to go to the App Store.

**Comment by ozh** [comment]
Hi. Neat! Feel free to open a pull request on https://github.com/YOURLS/awesome-yourls to get it listed!
