### ISSUE TITLE
Duplicate urls?

### ISSUE THREAD

**Issue by youradds** [YOURLS/YOURLS#2411]
I'm on the latest version. I found this report when looking into this issue:

#35

It says the issue is fixed - but it won't let me add the same URLs more than once. Do I need to change a setting somewhere? Or has this bug re-emerged?

**To Reproduce**
1. Add a new short link from the front end with an existing end URL that already exists 

**Expected behavior**
It should allow me to add the same URL again (with a different short link)

**Screenshots**
n/a

**Environment (please complete the following information):**
- YOURLS version:
  - Plugins enabled: Allow Hyphens in Short URLs
- PHP version: not sure (PHP 7 I think)

**Additional context**
n/a

**Comment by dgw** [comment]
Add `define( 'YOURLS_UNIQUE_URLS', 'false' );` to config. See [here](https://yourls.org/#Config) for other options.

**Comment by youradds** [comment]
Thank you :)
