### ISSUE TITLE
/index.php/yadayada loads home page

### ISSUE THREAD

**Issue by yaydood** [YOURLS/YOURLS#2412]
**Describe the bug**
The main page's contents is loaded even with invalid or non existent URLs. 

**To Reproduce**
1. Go to any-yourls-install/index.php/yadayadaywhatever 
or
1. Go to any-yourls-install/index.php?adsfasga=asdfasdf&asgf=sffgas
or
1. Go to any-yourls-install/?adsfasga=asdfasdf&asgf=sffgas

**Expected behavior**
Get redirected to home page

**Environment (please complete the following information):**
- YOURLS version: Any/Many
  - Plugins enabled: None
- PHP version: 7.2

**Comment by dgw** [comment]
I think you'll find that this is common to pretty much any webapp. Unknown GET parameters are ignored. It's just how most apps are written, and it's not a bug.

Try going to https://www.facebook.com/?lkasdhlkfjashgdf=oiuwger ­— it won't do anything different, just show you the homepage. Same if you try https://www.facebook.com/index.php/lkasdhfkuwer or https://www.facebook.com/index.php?oiyqiwueyr=oiuqtyiuyer&oiyqwer=lkbzjher.

Wikipedia is the same: https://en.wikipedia.org/w/index.php?oiqywiueyr=ioutyquywe and https://en.wikipedia.org/?oiyiutkjsbc=bhsilkjhgdf just show the main page. (In Wikipedia's case, the underlying software does parse the PATHINFO after the PHP script, and so https://en.wikipedia.org/w/index.php/path/to/something will actually redirect.)

For YOURLS, there's no reason to bother removing extra stuff from the URL. It doesn't provide any application-level benefit, just generates an extra round-trip to the server for no user gain.

**Comment by yaydood** [comment]
Wikipedia and Facebook show canonical meta tag which indicates that this page is invalid at this URL. Most of the times such page does not get indexed in Google for example. 

Anyways .. I took care of this in my template itself.
