### ISSUE TITLE
NOSTATS is missing in config-sample.php download

### ISSUE THREAD

**Issue by studioart** [YOURLS/YOURLS#2414]
**Describe the bug**
in documentation here http://yourls.org/#Config is mentioned "YOURLS_NOSTATS", but when we download YOURLS, in config-sample.php is nothing concerning this.

How can we add this?
Sorry, we are no coders ;-)
Thanks.

**Environment (please complete the following information):**
- YOURLS version: 1.7.2
  - Plugins enabled: none
- PHP version: 7.1.11

**Comment by ozh** [comment]
Just like other constants: add `define('YOURLS_NOSTATS', true);` in your config.php
