### ISSUE TITLE
YOURLS reads login credentials from GET parameters

### ISSUE THREAD

**Issue by dgw** [YOURLS/YOURLS#2424]
This is a follow-up to #2422, which centered around broken login if username and password are passed in the URL via GET parameters (`https://your.ls/admin/?username=foo&password=barbaz`).

I suggested it should either be fixed, so what that issue's OP wanted to do would work correctly, or removed entirely so the login credentials are ignored if passed in the URL. The consensus is that YOURLS is doing something it shouldn't—the login form fields are meant to be POSTed, and reading them from GET requests is a bug for security reasons.

For the moment I am self-assigning this, perhaps to take a look at it this weekend. (I've already had a cursory look at the code in `functions-auth.php` and found the "sloppy coding" @ozh mentioned… :joy_cat:) Milestone 1.8 because, well, it's not coming out any time soon anyway. :stuck_out_tongue:

But in all seriousness, this does need fixing. We don't want webservers that handle YOURLS requests storing passwords in their request logs, do we?

**Edit:** I got issue 2424… I feel special now.

**Comment by ozh** [comment]
Neat, thanks

I think it all boils down to https://github.com/YOURLS/YOURLS/blob/master/includes/functions-auth.php#L52-L59 where we're just checking on $_REQUEST which matches either POST or GET. I think it's fine for API auth but we should restrict to $_POST for web auth.

So, this "elseif API or normal: login with username & pwd" block should in fact be split in two, "elseif API login with username & pwd then check REQUEST, elseif web login using username & password: check POST"

**Comment by PopVeKind** [comment]
Ah, the old `$_REQUEST` problem. Most "Best Practices" suggest "Do NOT Use  `$_REQUEST`" as it opens a gate for security issues. At best `$_REQUEST` invites sloppy(er) coding. Can we add a YOURLS Coding Standard?

- - -
### YOURLS Coding Standard
**Do NOT use `$_REQUEST`**
Instead, use any of these _(as appropriate)_:
- `$_GET`
- `$_POST`
- `$_COOKIE`
- - -
This will prevent a `$_GET` in the URL from inadvertently becoming an injected `$_POST` or `$_COOKIE`. This should work well in the API / POST split Ozh suggested. The nuance value returned in most YOURLS posts may be useful as a trigger also, just something to consider.

**Comment by dgw** [comment]
Old indeed. A quick check of line blame from my phone just now tells me that code has been there for probably 9 years or more.

Definitely going to split up the checks as @ozh suggested when I get a chance.

**Comment by ozh** [comment]
3 years laters, made up my mind: GET or POST is exactly the same. Something intended to work with POST working with GET is fine, I think. There's no security benefit, and if some dude wants to log using GET, so be it.
