### ISSUE TITLE
MySQL Connection Error on ARM64 Container.

### ISSUE THREAD

**Issue by khasim** [YOURLS/YOURLS#2427]
I am trying to run yourls on ARM64 docker container, as there is no official binary available on hub.docker. I tried to run 

**docker build -t yourls  Docker_file_path**

I tried all three docker files in apache, fpm and fpm-alpine.

I continuously see the mysql connection error as shown below: 

**docker run --name some-yourls --link mysql1:some-mysql1 -p 8080:80 yourls**

Warning: mysqli::__construct(): (HY000/2002): Connection refused in Standard input code on line 17

MySQL Connection Error: (2002) Connection refused

MySQL Connection Error: (2002) Connection refused

Warning: mysqli::__construct(): (HY000/2002): Connection refused in Standard input code on line 17

Warning: mysqli::__construct(): (HY000/2002): Connection refused in Standard input code on line 17

MySQL Connection Error: (2002) Connection refused

MySQL Connection Error: (2002) Connection refused

Any suggestion on how to fix this error ? Also, as the build is successful and as we are not far from getting it working on ARM64 containers, can we get an official binary released on hub.docker ?

**Comment by LeoColomb** [comment]
Thanks for your report @khasim!

That said it seems relative to the docker image, so please move the discussion on the relevant repository: https://github.com/YOURLS/docker-yourls

While opening the issue there, I suggest you to get more precise output data:
* Does the MySQL container receive the request?
  * If no, are you ***sure*** your configuration is clean and correct? Have you checked the official doc?
* Are you sure your basic ARM64 config is working? I mean if you pull the raw apache or fpm image with a basic file requesting the MySQL connection, does it work?
  * If no, we won't be able to fix this and need to be handle by apache or fpm image maintainers.
