### ISSUE TITLE
Enable self-destructing URLs

### ISSUE THREAD

**Issue by sushinger** [YOURLS/YOURLS#2429]
**Is your feature request related to a problem? Please describe.**
I setup Websites and Web-Accounts quite often for customers and sometimes I need to provide a password quick and easy. This applies especially in those situations, when I have setup an account for testing and the recepient wants to see immediate results without hustleling around with email-confirmations etc.

**Describe the solution you'd like**
I'd like to create an URL that will do nothing else but after being clicked it shows a specific text, string or even an unformatted paragraph. As soon as this URL has been clicked, the URL should not "work" anymore and cannot be used to open the target page a second time.
The target page - containig the text/string/paragraph etc. - should not be able to be opened a second time and cannot be reloaded. Instead it should redirect to a specific landing-page.

**Describe alternatives you've considered**
This function would enable us to replicate a service like one-time-secret.com or privnote.com on our own server.

**Additional context**
sorry, nothing else …

**Comment by ozh** [comment]
See wiki page "Possible with a plugin"
