### ISSUE TITLE
Admin console sends referrer everywhere

### ISSUE THREAD

**Issue by tobozo** [YOURLS/YOURLS#2432]
Found this in [functions-html.php](https://github.com/YOURLS/YOURLS/blob/master/includes/functions-html.php#L89) `<meta name="referrer" content="always" />`

As a result the full URL to the admin console is sent every time someone tests a link from there, and this can't be bypassed by HTTP "referrer-policy" headers.

In some circumstances (e.g. no multi factor auth implemented) this can create an attack surface (DDoS, Brute force) by making the admin console address known by the owner of target URL's site.

What are the drawbacks of using `<meta name="referrer" content="none" />` in the admin console instead? 
Will this break some plugins or core functionalities ?

I've shortened [this URL](https://www.whatismyreferer.com/)  as a practical test.

**Comment by ozh** [comment]
Hmmm. I [added this](https://github.com/YOURLS/YOURLS/commit/46ab72292b3206a8e4e143d3dfcc3668293069a3) because of #1762 but cannot really understand why now...

**Comment by tobozo** [comment]
Maybe the HTML template is used outside the admin console, and maybe some parts of the admin console are intended to be exposed (e.g. multi user environment), and in this case the referrer would matter ?

**Comment by dgw** [comment]
I can't think of a situation in which it would be desirable to send YOURLS' admin console URL as a referrer. Doesn't mean there exists no such situation, just that I can't imagine it. :smile_cat:

The value "always" [is deprecated](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#attr-name) for `<meta name="referrer">` anyway. I think YOURLS shouldn't use it any more.

If passing along the referrer is important for short URLs, I think that's doable by sending another header along with redirections: `Referrer-Policy: unsafe-url` ([header docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy)). I need to verify that the header applies to 3xx response codes or when a `Location` header is also sent, but I don't see why it wouldn't.

**Comment by tobozo** [comment]
`Referrer-Policy: unsafe-url` is the way I chose to go along with not using HSTS so the referrer is properly forwarded with all 3xx responses.

But the /admin/ folder requires exactly the opposite, should this be be taken care of in the core instead of web server rules like I did?

**Comment by dgw** [comment]
I was thinking of sending `no-referrer` on admin pages and `unsafe-url` with redirects, yes. Mostly waiting for @ozh's input before I actually implement anything.

**Comment by ozh** [comment]
Reading https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy I think `unsafe-url` are not ideal either.

To be honest I really don't know what I had in mind back then. Now, I think we *should not* try to enforce anything regarding referrer and let this open to plugin and user choice (ie not send any header but allow plugins to add any via a filter)

**Comment by dgw** [comment]
Should it be a filter, or an action? A filter implies passing each plugin that registers for the hook an array of headers and allowing removal or modification before YOURLS finally sends the whole batch of headers at once. I think an action is simpler, since it only lets plugins _add_ headers.

Since YOURLS itself will send only basic headers for most requests, allowing plugins to add more should be enough in most cases (and is much simpler to implement than a full-on filter hook). In fact, we already have the `admin_headers` hook:

https://github.com/YOURLS/YOURLS/blob/3485c271580d88586fae0f7ee5027e5f8ed723fe/includes/functions-html.php#L59-L67

So assuming I didn't miss another hook in my Ctrl-F through the hook list for "head", all that's needed is a hypothetical `redirect_headers` (or `go_headers`, etc.) action to let plugins send their own. Thoughts?

**Comment by ozh** [comment]
The action hook `admin_headers` is indeed enough to add what's needed if needed on admin pages. Upon redirection, we already have `redirect_shorturl`:

https://github.com/YOURLS/YOURLS/blob/3485c271580d88586fae0f7ee5027e5f8ed723fe/includes/functions-html.php#L59-L67

And there's even `pre_redirect` for internal redirection. I think we're covered here then ?

**Comment by dgw** [comment]
Sounds like it.

I'll close this, since referrer won't be sent from admin console any more except for HTTP-to-HTTP (and hosting YOURLS admin without HTTPS is pretty bad in 2018).

**Comment by ozh** [comment]
Anyway someone on HTTP can totally have a plugin that blocks referrer then, if needed
