### ISSUE TITLE
Install YOURLS button doesn't work

### ISSUE THREAD

**Issue by Scotxd** [YOURLS/YOURLS#2433]
* YOURLS version: LATEST
  * Plugins enabled: None
* PHP version: PHP 7.2.9-1+ubuntu18.04.1+deb.sury.org+1
* Server OS: Ubuntu 18.04.1 LTS (GNU/Linux 4.15.17-1-pve x86_64)

**What is the current behavior?**
YOURLS does not install. The "Install YOURLS" button appears to do nothing.

**What is the expected or desired behavior?**
INSTALLING YOURLS

### Reproducible bug summary 

1. Visit https://wemake.blackniggers.work/admin/index.php (must visit the specific file or it will 403).
2. Click "Install YOURLS"
3. Profit

After installing php7.2-mysql in order for the Install YOURLS button to actually show up, after a PDOException error, I can't actually shorten URLS it seems. After clicking Install YOURLS, it brought me to the same page but with a ? at the end of the url, and the whole page was white. After turning on debug mode and restarting nginx, it... still gave me a blank screen? I just assumed it worked, so after shortening test.com with ShareX, YOURLS literally gave me the html script of user/install.php. I have literally no idea what's going wrong as I don't know where I went wrong or the error that is happening. The debug script given at install.php is as follows:
`Connected to database yourls on localhost 
SQL: SHOW TABLES LIKE 'yourls_options' (0.00010 s)`

**Comment by dgw** [comment]
I'm sorry it sometimes takes a while to get an answer, but please don't open a new thread to continue an existing conversation. I'll return to #2431.
