### ISSUE TITLE
MFA Login

### ISSUE THREAD

**Issue by Noiden** [YOURLS/YOURLS#2434]
I would like more security and therefore request MFA support.

A Google-authenticator implementation. So you can use other apps also, like Authy.

Thanks.

**Comment by ozh** [comment]
See existing plugins. Also, see wiki page "Possible with a plugin".

**Comment by dgw** [comment]
@ozh I could not find any plugins that implement 2FA, neither in web search nor in the awesome-yourls list. Don't you think it would be a good feature to add into core? I do.

**Comment by Noiden** [comment]
I can't either find any plugin with this and I think as @dgw that it would be nice in the core.

Anyway, if any plugin coder see this, please make a plugin for this. =)

**Comment by dgw** [comment]
Maybe it can be a core plugin. The 95% of users who won't make use of it probably _should_, but don't because they're not security-conscious. YOURLS should help with that, not leave them to be ignorant.

**Comment by ozh** [comment]
Totally open to have a core plugin with this, if the plugin is quality

**Comment by ozh** [comment]
Side note: https://github.com/PHPGangsta/GoogleAuthenticator seems to be the easiest and most compatible lib

**Comment by MatthewC** [comment]
I know it's been 4 years since the last comment @ozh, but just wanted to leave this here in case someone's interested: https://github.com/MatthewC/yourls-2fa-support

Not sure if you'd consider this quality.

**Comment by ozh** [comment]
@MatthewC I didn't look the plugin code but your plugin readme is very clear. Be sure to get listed on https://github.com/YOURLS/awesome-yourls ! Open a PR there and add your plugin
