### ISSUE TITLE
Login form has no hooks

### ISSUE THREAD

**Issue by dgw** [YOURLS/YOURLS#2436]
I spent a little time looking around to see how one might go about implementing a plugin to provide multi-factor authentication (as requested in #2434) or OpenID login (I have a WordPress plugin that consumes OpenID), for example. In the process, I could not find any way for plugins to add fields on the login form.

Perhaps YOURLS doesn't need quite as many hooks [as WordPress has](https://codex.wordpress.org/Customizing_the_Login_Form#Login_Hooks), but I do think at least one injection point (below username & password, but above the submit button) would be useful. A plugin implementing two-factor auth would add a field there asking for the TOTP code (for example); a plugin implementing OpenID as a consumer would add, say, "or" and a field for the user's OpenID URL.

Per usual, before I actually get into any code, I'd like to flesh out exactly what hooks are appropriate. We can copy WordPress's hook name `login_form` for the one at the bottom of the login form. It's also trivial to add a `login_head` hook in case plugins need to add tags in the header for CSS/JS that's needed only on the login page. Putting a `login_footer` hook might not be as useful…

Left to my own devices, I'd implement the first two (`login_head` and `login_form`) as a start.

**Comment by ozh** [comment]
Completely open to add as many hooks as needed, if needed, anywhere. Regarding the login form, `yourls_login_screen()` calls `yourls_html_head( 'login' );` so you can inject anything in the head using the first parameter of `yourls_html_head()`, but having specific `pre_login_form` and `post_login_form` wrapping the login form itself cannot hurt.
