### ISSUE TITLE
Prevent hitting a long url before making it short

### ISSUE THREAD

**Issue by rakeshbhatt10** [YOURLS/YOURLS#2437]
**Is your feature request related to a problem? Please describe.**
Yes we want to long url not to get clicked while generating short url

**Describe the solution you'd like**
Some kine of settings would help

**Describe alternatives you've considered**
Right now just checking current code  to see if we can comment that portion of code

**Additional context**
Our ling url is alos tracing  url. Which we use internally

**Comment by ozh** [comment]
This happens when YOURLS fetches the title of the remote page. Use a plugin such as Static Titles to shunt this. See https://github.com/YOURLS/awesome-yourls
