### ISSUE TITLE
Stats page returning 404 error

### ISSUE THREAD

**Issue by dpDesignz** [YOURLS/YOURLS#2441]
**Describe the bug**
When I click the stats button on a short link, I get a 404 page.

**To Reproduce**
1. Go to 'http://dp3.me/admin/' (Private shortener)
2. Click on 'Stats next to a link'
4. See 404 page

**Expected behavior**
I expect to see the links stats

**Screenshots**
http://dp3.me/support/stats-link.png
http://dp3.me/support/404-error.png

**Environment (please complete the following information):**
- YOURLS version: 1.7.2
  - Plugins enabled: Allow Hyphens in Short URLs, dpDesignz Backend (copy of "Sleeky" backend)
- PHP version: 7.0

**Comment by dpDesignz** [comment]
Apologies, I moved my directory before doing the upgrade and didn't realise that the .htaccess file hadn't copied over. Please delete this.

**Comment by dgw** [comment]
> Please delete this.

Can't, sorry. (isaacs/github#253) :crying_cat_face: But glad you figured it out!
