### ISSUE TITLE
Wrong redirecting after login : ignore server port

### ISSUE THREAD

**Issue by lekpamartin** [YOURLS/YOURLS#2443]
- [x] Check you are using the [**LATEST** release](https://github.com/YOURLS/YOURLS/releases/latest) or the development branch.
- [x] Make sure you have [**SEARCHED** existing issues](https://github.com/YOURLS/YOURLS/issues?utf8=%E2%9C%93&q=is%3Aissue) first. 
- [x] Read the [**GUIDELINES**](https://github.com/YOURLS/YOURLS/blob/master/.github/CONTRIBUTING.md) linked in the yellow notice box above.
- [x] **COMPLETE** this issue template.

**Describe the bug**

**To Reproduce**
1. Go to 'login page'. Server listen on port 82 for example : http://IP:82/admin
2. Login
4. Login is succes but you are redirect to http://IP/admin

**Expected behavior**
After login, you are redirect to wrong server URL : bypass server PORT. 

**Screenshots**

**Environment (please complete the following information):**
- YOURLS version:
  - Plugins enabled:
- PHP version:
- Other relevant details depending on the context (server OS & version, MySQL version, browser version, …)

**Additional context**

**Comment by dgw** [comment]
Hmm… Sounds like a perfect test case for #2442 if you ask me.

**Comment by ozh** [comment]
Exactly. Closing, please follow this other issue.
