### ISSUE TITLE
Unable to activate any plugins "No plugin specified, or not a valid plugin" 

### ISSUE THREAD

**Issue by gtmaniak** [YOURLS/YOURLS#2444]
**Describe the bug**
Currently running 1.7.2 and cannot activate any plugins. Even stock sample plugins.

Error "No plugin specified, or not a valid plugin"

**To Reproduce**
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
- YOURLS version: 1.7.2
  - Plugins enabled: None
- PHP version: 5.6
- Other relevant details depending on the context (server OS & version, MySQL version, browser version, …)

**Comment by PopVeKind** [comment]
Is it April First? Cause this seems like a joke!

**Comment by gtmaniak** [comment]
No, this is not a joke, I cannot activate any plugins at all...

**Comment by PopVeKind** [comment]
### Apache or Nginx?
This could be the server block or .htaccess
### Program Transfer Coruption
It seems the program is not finding your plugin directory.
You might want to download a NEW copy of YOURLS and then upload the program files again (overwrite).

I have in the past downloaded files that were corrupted along the way.  I have also uploaded files that were corrupted along the way.
### /user/ directory
What directory is your **`/user/`** directory in? Is this your DocumentRoot (Apache) or Webroot (Nginx)? Or is it in a subdirectory like `/s/` or `/e/` or `/y/`?

**Comment by AhmadKahlid** [comment]
I have the same issue with [Reset URLs](https://gist.github.com/ozh/a0090f46569b50835520d95f9481d9fd) plugin, but another plugins (like: Random Backgrounds, Random Keywords, ...) can be activated/deactivated successfully.

PHP version: 7.2
MySQL version: 8.0
Server/OS: IIS7 / Microsoft windows server 2008 r2

**Comment by LeoColomb** [comment]
@AhmadKahlid If other plugins can be activated successfully then the issue is different. Be sure to put the `plugin.php` is a directory named with a simple chars and no space (eg. `plugins/reset-urls/plugin.php`).

---
Closing as inactive.
