### ISSUE TITLE
Not possible to forward path to short URL

### ISSUE THREAD

**Issue by DarrienG** [YOURLS/YOURLS#2446]
**Is your feature request related to a problem? Please describe.**
I'm frustrated that I can't send the rest of the PATH from a short URL to a long URL. It doesn't seem like this service allows it even with a plugin.

**Describe the solution you'd like**
I want:

`sho.rt/place/assets/images/dog.jpg -> longurl.com/assets/images/dog.jpg`

**Describe alternatives you've considered**
I've looked at a number of plugins, and attempted to write a plugin myself, but it doesn't appear the plugin API supports this behavior.

**Comment by dgw** [comment]
Why not implement this directly in the webserver with a rewrite?

**Comment by davemachado** [comment]
The webserver doesn't have access to the short URL and the long URL at the same time - it's either processing the original request (short URL) or redirecting/rewriting to the long URL. The YOURLS service does the translation in between. Since there are plugins that support forwarding the query string (`?foo=bar...`) to the long URL, I would hope it is possible to accomplish something similar for forwarding `/assets/images/dog.jpg`.

**Comment by ozh** [comment]
" It doesn't seem like this service allows it even with a plugin" -> virtually anything is possible with plugins. Seriously.

This said your example is incomplete and I cannot give any pointers. In your example "sho.rt/place/assets/images/dog.jpg -> longurl.com/assets/images/dog.jpg", how does YOURLS know that this isn't redirected to anotherurl.com/assets/images/dog.jpg ? What is this "place" part supposed to be regarding the "sho.rt" URL ? Or is it that "sho.rt/place" sends to "longurl.com", and thus "sho.rt/place/whatever" sends to "longurl.com/whatever" ?

**Comment by DarrienG** [comment]
The last example is what I'm looking for. sho.rt/place is supposed to be longurl.com So therefore sho.rt/place/images/dog.jpg should be longurl.com/images/dog.jpg

**Comment by ozh** [comment]
So this is the very same principle as the query string plugin except you don't check query string but the whole requested URL 

- get requested short URL (eg "place" or "place/blah") with `yourls_get_request()` and explode it on `/` if any to get the existing short URL (eg "place" here)
- if short URL exist, redirect to "long URL + rest of the string you got with `yourls_get_request()`
