### ISSUE TITLE
HOW TO UPDATE LINK KEEP KEYWORD ?

### ISSUE THREAD

**Issue by songhanpoo** [YOURLS/YOURLS#2447]
Hi Team !

i have a little skill dev with php language,
Can you help me for update long url but keep short link ?
where's function in your source ?
i tried use api POST but that add new link.

thank & best regards

**Comment by PopVeKind** [comment]
@songhanpoo Login to your Admin interface, find (there is a search) your short keyword.  On the right column of your keyword row, you will find an edit button. Click that and you can change what you want.
