### ISSUE TITLE
Service Unavailable

### ISSUE THREAD

**Issue by MrsMasternode** [YOURLS/YOURLS#2448]
ver 1.7.2
out of nowhere I get
Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Additionally, a 503 Service Unavailable error was encountered while trying to use an ErrorDocument to handle the request.

first steps to check?

**Comment by LeoColomb** [comment]
> maintenance downtime or capacity problems
> first steps to check?

Get in touch with your host support. ✉️
