### ISSUE TITLE
Protocol Problem PR and HTTPS Plugin

### ISSUE THREAD

**Issue by PopVeKind** [YOURLS/YOURLS#2449]
### I Request to be Assigned to all HTTPS Issues.
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
_**Many issues have been raised about HTTPS Protocol Problems.**_

**Describe the solution you'd like**
_**Rewrite the core to not use constants to define a protocol.**_

**Describe alternatives you've considered**
**_I Request to be Assigned to all HTTPS Issues._**

**Additional context**
# Introduction
I currently have under test an _alpha-prototype_ **_Protocol Problem PR_** and **HTTPS Plugin**. I am refining these to be released before December.  I am asking people to share, on this issue, any ongoing problem they have with anything to do with HTTPS or the involved core constants.

# Protocol Problem PR
## Removed Constants
This PR will remove the following core constants from the YOURLS core code.
- **YOURLS_SITE**
- **YOURLS_ADMIN_SSL**
### For Existing Sites.
The above consrants in config.php will first be parsed and the results will be stored in database entries.
### For Newly Installed Sites.
The following defaults will be stored in the database protocol entries:
- For Short URL Links: **`http://`**
- For Admin URL Links:  **`http://`**
# HTTPS Plugin
The HTTPS Plugin is for advanced users who wish to use HTTPS on all or part or their YOURLS links. It will have one pulldown menu with the following three choices that will change the database protocol entries.
### Only HTTP (Default)
- For Short URL Links: **`http://`**
- For Admin URL Links:  **`http://`**
### Admin HTTPS
- For Short URL Links: **`http://`**
- For Admin URL Links:  **`https://`**
### Full HTTPS
- For Short URL Links: **`https://`**
- For Admin URL Links:  **`https://`**
# Flex HTTPS
The HTTPS Plugin simply determines how links are built. Using the **`Server Block`** (Nginx) or **`.htaccess`**  (Apache) you could receive and handle **`Short URL`** request for any (or all) of the following on the same server, without additional redirection
- **`http://sho.rt/abc`**
- **`https://sho.rt/abc`**
- **`http://www.sho.rt/abc`**
- **`https://www.sho.rt/abc`**
- While **_REQUIRING HTTPS_** for the **Admin Area**. (This would redirect `http://` request to the Admin Area to use `https://`)
# Benefits
**_This PR and Plugin will:_**
- Make setting up **HTTPS** much easier.
- Eliminate the **`YOURLS_SITE` Trailing Slash Problem.**
- Reduce the **Core Constants**.
- **Reduce Newbie Confusion**.
- Move us closer to a true YOURLS **MultiSite**
- Move us closer to a fast and easy **Full-Fledged Broswer Based Installer.**
# Requests
_**I am asking people to share, on this issue, any ongoing problem they have with anything to do with YOURLS HTTPS or the involved core constants.**_ I will use these for testing scenarios.

**Comment by ymage** [comment]
I welcome the proposal.

My only requirement is to have an other way to configure yourls without the  **Full-Fledged Broswer Based Installer**

**Comment by ozh** [comment]
Once again a post that's 2 screen long :(

"I Request to be Assigned to all HTTPS Issues" -> sure, go ahead, that's very welcome. One "small" requirement: submit tiny PR fixing *one* problem at a time and not a gigantic stuff fixing everything but that's impossible to grasp and review

**Comment by PopVeKind** [comment]
@ymage - Yes, I agree!  The Full-Fledged Installer will NOT replace the config.php install. It will augment it by asking browser-based questions and then build a config.php file and load database entries. Simple, fast and easy.  Most of all very Newbie friendly.

**Comment by PopVeKind** [comment]
### "tiny PR fixing one problem at a time"

Yes Ozh, I have finally grasped how the _YOURLS_ community works. Future PRs from me will focus on a single issue/problem and be as small as possible to deal with that issue.

**Comment by PopVeKind** [comment]
### "a post that's 2 screen long"

@ozh - I would like your advice?

I get it in relation to posts within a discussion.  My problem is while introducing a new PR Project.  I would like others to comment/suggest.  So I wrote the two screen overview. Would it be better to break the major headings into different posts which would send a number of emails for the overview?

**Comment by ozh** [comment]
@PopVeKind just write less. Seriously. Less words, less verbosity, less context, less "I'm currently doing this and that in regard to this and that", less headers / subheaders / subsubheaders. The sole fact that you use so many headers and sub headers indicate there are 12 ideas in your posts. Honestly and as harsh it will sound, I didn't read your post past the very first line "I Request to be Assigned to all HTTPS Issues".

**Comment by PopVeKind** [comment]
@ozh  - Got it! Thanks for the harsh, but honest advice, I will adapt.

**Comment by ALLONEPLANET** [comment]
"I am asking people to share, on this issue, any ongoing problem they have with anything to do with YOURLS HTTPS"

SSL certificate is on.
www.a1p.uk redirects to a1p.uk (via Dreamhost setup)
httpaccess has RewriteCond %{HTTPS} =on

typing (or full link with) https://a1p.uk/med1 works
typing (or link with) a1p.uk/med1 does NOT work and gets a 404 error

There may be a workaround for the above situation that I haven't spotted yet?
I may have it configured incorrectly?
Or it may be useful for you to know so you can correct the issue? :-)

Well done on an awesome piece of software. loving it :-)

**Comment by PopVeKind** [comment]
@ALLONEPLANET 

What works:
https://a1p.uk/med1
https://www.a1p.uk/med1

What does NOT work:
http://a1p.uk/med1
http://www.a1p.uk/med1

This is caused by an error in your `.htaccess` file.
### .htaccess
Please note that this filename begins with a dot and also note the spelling.
If you put it in a file called `httpaccess` as your post stated, this will prevent it from working.

Likewise, `RewriteCond %{HTTPS} =on` **MUST ALWAYS** be followed by a `RewriteRule`

If your `.htaccess` file is short, say 30 lines, or less, would you consider posting it here?

Or, copy/paste any lines you think would relate to this domain or problem.

### Something to check:
The `RewriteRule` in `.htaccess` basicly has two parts and looks something like this:

RewriteRule {first part} {second part} [flags]

If you have any rule that the second part begins with `http://` you need to change that to `https://` to force Apache to redirect to the http**S** version.

There is a way to allow YOURLS to service both http and https requests (no dubble redirect) however I would need to know more about your .htaccess to suggest a change.

If your yourls install is **new**, better just stick to `https://`.
If your yourls is **old** with thousands of links to `http://` it might be worth servicing those links in `http://`

**Comment by ALLONEPLANET** [comment]
Thank you PopVeKind for your reply - much appreciated!
The ,htaccess file has the correct spelling (& dot) in the server. Sorry for the confusion.
Here is the complete text within the ,htaccess file:

# BEGIN YOURLS
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
    RewriteCond %{HTTPS} =on
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^.*$ /yourls-loader.php [L]
</IfModule>
# END YOURLS

Thanks :-)

**Comment by PopVeKind** [comment]
@ALLONEPLANET

Your website appears to be doing exactly what your `.htaccess` tells it to do! That didn't help much!

### Short/Easy `.htaccess` Lesson
`RewriteCond` is shorthand for "Rewrite **Condition**". In other words, if this _condition_ is true, do the **next**  `RewriteRule` You can have more than one condition. Your `.htaccess` has three conditions to run yourls.

1. `RewriteCond %{HTTPS} =on` ---The request must be https:// **_(http is NOT allowed!)_**
1. `RewriteCond %{REQUEST_FILENAME} !-f` ---The request is not a physical file.
1. `RewriteCond %{REQUEST_FILENAME} !-d` ---The request is not a physical directory.

The problem line is, `RewriteCond %{HTTPS} =on`  It MUST be `https://` or it fails! 404 File Not Found! If it is http - it fails...

Many well meaning people on the internet think `RewriteCond %{HTTPS} =on` turns on `https`, but it doesn't! That advice is mistaken.
### Some assumptions
Before I tell you some ways to fix your `.htaccess` problem, let's **verify** some assumptions I have made.

1. I assume you want everything to run under http**S** with ssl encryption.  That is the most secure.
1. I assume your `config.php` contains http**S**:
`define( 'YOURLS_SITE', 'https://a1p.uk' );`
1. I assume your `config.php` does **_NOT_** contain any:
`define( 'YOURLS_ADMIN_SSL' ...`
### Very Easy
Just delete `RewriteCond %{HTTPS} =on` from `.htaccess`
**Pros:**
- Very Easy!

**Cons:**
- Allows **Admin Area** to run as http.
- Not secure.
- Not recommended.

### Best Practice
Tomorrow I will post the `.htaccess` file I use on my https sites and I consider **Best Practice!**

**Comment by ALLONEPLANET** [comment]
Thank you
Pop VeKind
Your assumptions are accurate in my case. i did presume by setting HTTPS to
on would mean the whole site would redirect to https :-(

I look forward to seeing your Best Practice .htaccess file. Yay
Cheers :-)

**Comment by PopVeKind** [comment]
## BEST PRACTICE
Just copy/paste this into your` .htaccess` file in your Apache DocumentRoot.
### Best For:
1. **YOURLS Site**
1. **WordPress  Site**
1. **YOURLS plus WordPress Site** _(Together in DocumentRoot)_.

```

# BEGIN YOURLS and/or WordPress
RewriteEngine On
RewriteBase /

# Use HTTPS on this site.
# Comment the next two lines if you use HTTP.
RewriteCond %{HTTPS} !=on
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301] 

# Run index.php in the DocumentRoot
RewriteRule ^index\.php$ - [L]

# Add a trailing slash to /wp-admin
RewriteRule ^wp-admin$ wp-admin/ [R=301,L]

# Run any Physical File or Directory
RewriteCond %{REQUEST_FILENAME} -f [OR]
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule ^ - [L]

# Run YOURLS
RewriteRule ^([0-9a-zA-Z-]+)\+?$  yourls-loader.php [L]

# Run WordPress (or index.php)
RewriteRule ^(wp-(content|admin|includes).*) $1 [L]
RewriteRule ^(.*\.php)$ $1 [L]
RewriteRule . index.php [L]
# END YOURLS and/or WordPress

```

### Pros:
- **VERY EASY** (copy/paste)
- Works with all _Standard YOURLS Setups_.
- Works with _Allow Hyphens in Short URLs_ plugin
- Works with **WordPress!** Single Site, MultiSite SubDomains, MultiSite Networks!
### Cons:
- The Slash(/) is reserved for WordPress. **_You should NOT use a Slash(/)_** in a YOURLS keyword anyway.
- WordPress MultiSite **_SubDirectory_** is NOT compatible with YOURLS nor this .htaccess file.
### Notes:
- _Give WordPress its Own Directory?_ **It works!** Follow WordPress instructions.
- I do not use `<IfModule mod_rewrite.c></IfModule>`  It's redundant!

**Comment by PopVeKind** [comment]
### KISS
_Keep It Simple Sweetheart!_

I love simple things.  If something is simple enough I rarely make a mistake.

The above `.htaccess` is so simple I use it for HTTP, HTTPS, YOURLS, WorfPress, and even YOURLS plus WorfPress!

I hope it helps others too.

Regards,

Pop

**Comment by PopVeKind** [comment]
### FOR ADVANCED ADMINS ONLY

**Add extra characters to YOURLS Charset.**
1. **Do NOT use a slash(/) in YOURLS!** The slash(/) is reserved for WordPress.
1. Add the YOURLS Plugin of your choice and add your extra characters.
1. Add characters to the `.htaccess # run YOURLS` between the Z and the dash(-).


**Example:**
- Add a tilde(~) and an underscore(_) via your plugin.
- Change `[0-9a-zA-Z-]` to` [0-9a-zA-Z~_-]` add between the Z and the dash(-). Like this:
- `RewriteRule ^([0-9a-zA-Z-]+)\+?$  yourls-loader.php [L]`
- `RewriteRule ^([0-9a-zA-Z~_-]+)\+?$  yourls-loader.php [L]`

**Comment by ALLONEPLANET** [comment]
Wonderful.
Thank you Pop VeKind
That sorted my issue. Yay!
Greatly appreciate the Short/Easy .htaccess Lesson and the BEST PRACTICE
help.
Cheers,
Colin :-)
