### ISSUE TITLE
403 forbidden on existing shortened links

### ISSUE THREAD

**Issue by icomputeUK** [YOURLS/YOURLS#2454]
I've been using YOURLS for years and recently experienced an issue where I suddenly couldn't log in using admin and existing shortened links stopped resolving.

After some investigation it seemed that I needed to change my database SQL hostname in config.php to an internal hostname for scripts running on our webserver which then allowed me to log in as admin.

However existing links still do not work - new ones do.  I cannot edit links and get the YOURLS error message - Error, URL not found when I attempt to.  The original link however is valid and original open when clicked (just not the shortened link).

I've tried the three database options as suggested in troubleshooting first steps and turned on debugging.  I'm getting nothing back and changing database engines hasn't made any difference.

I'm stumped.  We have hundreds of links that no longer work and am inundated with complaints from customers trying to use them.

I'd be really grateful if anyone could point me in the right direction to resolve this.

1. Go to any existing shortened link 
2. See error (screenshot)

<img width="424" alt="screen shot 2018-10-29 at 18 37 08" src="https://user-images.githubusercontent.com/32702985/47672785-c3297f00-dbaa-11e8-8119-d23dc96b8131.png">

**Expected behavior**
To be able to edit, delete, share and visit preexisting shortened links.

Please note that NEW shortened links are fine and behave as expected.

**Screenshots**

Error when attempting to edit a pre-existing link

<img width="978" alt="screen shot 2018-10-29 at 18 48 28" src="https://user-images.githubusercontent.com/32702985/47672994-44811180-dbab-11e8-8768-d9e992688e18.png">

Error when attempting to delete a preexisting link:

<img width="255" alt="screen shot 2018-10-29 at 17 58 03" src="https://user-images.githubusercontent.com/32702985/47673548-d8071200-dbac-11e8-86af-2289e031c58d.png">

**Environment (please complete the following information):**
- YOURLS version: 1.7.2
  - Plugins enabled: none
- PHP version: 7.1

Thanks in advance of any help you can give me.

**Comment by dgw** [comment]
> After some investigation it seemed that I needed to change my database SQL hostname in config.php

Get in touch with your host. This makes it sound like they changed something about database hosting and perhaps something went wrong during the data migration.

Based on the information provided, I presently doubt that it's an issue with YOURLS.

**Comment by icomputeUK** [comment]
I have and they claim the hosting is fine and the database is accessible by phpmyadmin where I can perform edits, deletes etc. Which is true.  Because only scripts relating to YOURLS are not working they told me to check my files. 

Any html or php that is not related to YOURLS works fine.

If I delete a record using phpmyadmin and then create a new link using YOURLS then everything is good but I've got thousands and can't do that every one of them.

**Comment by icomputeUK** [comment]
After my updates and installs my plug in for hypens in short links needed reactivating!  As most of our links have hyphens this made it appear that none work working and could not be edited.
