### ISSUE TITLE
Troubleshooting YOURLS Links From Facebook: URL Parameter / Query String "fbclid"

### ISSUE THREAD

**Issue by Matt-AB** [YOURLS/YOURLS#2455]
First, I appreciate your patience with this, my first GitHub post. :) 

**Is your feature request related to a problem? Please describe.**
Facebook has recently implemented a new URL parameter / query string called fbclid, which has interrupted the connections between our YOURLS short links posted on Facebook and the long URLs to which they point. Here is an example: a portion of a link preview from a YOURLS short link posted on Facebook: 

![screenshot 2018-10-30 at 12 06 22 - edited](https://user-images.githubusercontent.com/44614358/47732562-d553fd80-dc3c-11e8-9bf9-90bd154e4cf1.png)

This seems to be one of the more authoritative summaries of the fbclid issue thus far: https://stackoverflow.com/questions/52847475/what-is-fbclid-the-new-facebook-parameter

**Describe the solution you'd like**
I'd like to see a plugin that would somehow bypass the addition of the fbclid query string, thus allowing short links on Facebook to successfully link to their longer URLs. This may be accomplished by eliminating Facebook's fbclid query string from the long URL to which a shortened URL points. My lack of technical expertise means that I have no idea how outlandish this proposal is, but I think it communicates my hopes for an end result.

**Describe alternatives you've considered**
I checked the Plugin List at awesome-yourls and searched the Issues for "query", "parameter", and "fbclid". 

I think that what I'm asking for is essentially the opposite of the "Query String Forward" and/or "Query String Keeper" plugins.

**Comment by dgw** [comment]
I'm not sure what you mean by "has interrupted the connections between our YOURLS short links posted on Facebook and the long URLs to which they point."

On a test link on my YOURLS instance, I appended `?fbclid=` followed by a bunch of random letters (obtained by spamming my phone keyboard, so not a perfect replica of the parameter) and followed the link. It worked just fine. The query string was not passed through to the destination site.

What is the specific problem you see this new parameter causing?

**Comment by Matt-AB** [comment]
Thanks for replying and for pointing out ambiguity in my language. 

I just tried the same method as you and got a different result, which should answer your question about what problem I'm experiencing: In the URL location at the top of my browser, I typed in a YOURLS short link which I know works, and appended `/?fbclid=` followed by a string of random letters. Rather than going to the destination of the short link, the browser showed what I assume is the default error page for YOURLS: it is simply the branded "x.sh" page, where x is our brand.

**Comment by dgw** [comment]
Hmm… I bet that out environments are different, at the least. Whether I append the parameter with `?` or `/?`, my install (on nginx, with php5-fpm) is happy to serve the long URL redirect either way.

Can you provide these details?

  * webserver type
  * PHP version & type (FPM, mod\_php, etc.)
  * YOURLS version
  * A random `fbclid` string that breaks your redirects, in case there is a specific character that I didn't use which breaks it

A gist/pastebin of your server config might be useful, too, if you can share a sanitized version that omits details you'd prefer not to share (like the value of `x.sh`). This is definitely starting to sound like a server configuration thing.

**Comment by Matt-AB** [comment]
Hi, 

The delay in reply is due to my reaching out to colleagues, i.e. those who can actually provide that information. I'm just the person who is taking initiative to solve this, not the one with all of the technical expertise. I will let you know if or when I get a response.

**Comment by matthew-chell** [comment]
Hi,

I am the colleague Matt-AB mentioned.  YOURLS version was 1.5 and I updated it to 1.7.2.  This fixed the problem.  On a side note the link in the facebook post was slight different in on the desktop site verses the mobile site.  On the desktop the link was https://l.facebook.com/l.php?u=http%3A%2F%2Fp2c.sh%2Fundiscussed&h=AT127BHxIa1NUQ9nlCalblRcmi4-DiQElqFOBAspLfo-FH9Hy57d9wOYAKBNZhSuCNP8i1f-Bvbo42SyjDip-OZQ1x7qS21g80WHJ7DutVvU3A-KzD9uYpL-q1r4Om94-Gj9yTZOa2Kh7ywvlGKK4SrGMMjI4TbVHc2CdoRxeet7MHBYQG1U1I3v3dar1jKNXTgd6SBzKqxARQf61nVXfCkcGU-6SFM_DG75JZ2cJ6ohuJki7ZUunC343ybRAoMw2on_tmMgq-GAKJyJCB3DM3nC9QquMDbVa8WFIRa-J0ge0KOj9N7BJgR8NAQjxaCb1iS-fCqq0NZ66MRnsdEAMWYkrKz0kxT62rGRey7SJGLB6TSt4zJISYLLjlYb2Qe07XHUFn4Z5iei5zzk-4oNU7fzjKnLkfny_myOuEqxSfaxN-hfWiW3CleTYw1TdFTM0oHU5IYdQiliGIu_0Ky6GHOkZDrT-q1R-8I while on the mobile it was https://lm.facebook.com/l.php?u=http%3A%2F%2Fp2c.sh%2Fundiscussed%3Ffbclid%3DIwAR1ncw8mrH2DgmPZeq6ansZ9K7XmuUSXxwrwsd-IQ0Dx7VHh0xausrlVbFs&h=AT0nSGaWJo0BFLtNaye4t67b9ufSD_Rx2HEa5P6CDbCUa46btrA1_RVgv3SzWJEcXbc1eHlisHZ-r1qLkOo68VMq6OZPIZI3RkuGR140JTWvlGikx_BwNG5h6f2UO9BO5zQ- .  The difference is that after undiscussed on the desktop link there is & on the mobile version this & is urlencode to %3F.  This caused a query parameter to be passed to the YOURLS site which the 1.5 version did not handle well.
