### ISSUE TITLE
Broken Page: Plugin List

### ISSUE THREAD

**Issue by Vondelphia** [YOURLS/YOURLS#2456]
have to use revision to browse list.

(broken)
https://github.com/YOURLS/YOURLS/wiki/Plugin-List

View history by clicking "106 revisions" and than click the most recent to see entire plugin list:
1. https://github.com/YOURLS/YOURLS/wiki/Plugin-List/_history
2. https://github.com/YOURLS/YOURLS/wiki/Plugin-List/836b77aea28c705778e593cab9e33f586537231c

**Comment by dgw** [comment]
The wiki page in question says:

> You will find the list in the dedicated repository: https://github.com/YOURLS/awesome-yourls

Working as intended. The plugin list was moved to its own repository.

**Comment by ozh** [comment]
The page says "You will find the list in the dedicated repository: https://github.com/YOURLS/awesome-yourls" but people find this unclear? SMH....

**Comment by Vondelphia** [comment]
RIght on... next time I'll slow down and read. I recommend redirecting sidebar link to plugin repo.

GLHF and thanks for your time.

![sidebar-plugin-list](https://user-images.githubusercontent.com/16372882/47749711-14497980-dc64-11e8-93ce-b465b93b24c2.png)

**Comment by ozh** [comment]
Fair enough, indeed the link is confusing, I've reworded things a bit. Thanks
