### ISSUE TITLE
How to change domain name and keep old links working

### ISSUE THREAD

**Issue by fncll** [YOURLS/YOURLS#2457]
**Describe the bug**

I can't figure out the secret .htaccess sauce to redirect old domain to new one for YOURLs requests

**To Reproduce**

I have YOURLs working fine at https://old.com/go/

I need to move it to https://new.com/go/

The new server is the same as the old, we've just changed the domain name associated wth it

**Expected behavior**

I changed the configuration in config.php to:

    define( 'YOURLS_SITE', 'http://new.com/go' );

And requests for the new domain work fine.

I assume I can do a rewrite in the .htaccess file to redirect request for the old domain but can't figure out how to make that work. What I have so far, but clearly incomplete:

```
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /go/
RewriteCond %{HTTP_HOST} ^old.com$
RewriteRule ^(.*)$ "https\:\/\/new\.com"
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ /yourls-loader.php [L]
</IfModule>
```

**Environment (please complete the following information):**
- YOURLS version: 1.7.2
- Plugins enabled: Allow Hyphens in Short URLs
- PHP version: 5.6.31
- Apache/2.2.15 (CentOS)

**Comment by dgw** [comment]
What isn't working, exactly?

I'm years out of practice with Apache rewrites (all of my stuff runs nginx these days), but I feel like something is missing from the first `RewriteRule` line, something like a `$1` to put the original requested path in the new URL.

A quick Google from my phone turned up this: https://serverfault.com/a/344619/13440 — which I've used to try and come up with something useful.

It looks like using this as the first `RewriteRule` might do it for you:

```
RewriteRule ^(.*)$ https://new.com/$1 [R=301,L]
```

Using a 301 will have the browser issue a new request to the new domain, so YOURLS will definitely see it as a request it should handle; and the L flag stops further rewrites, if memory serves.

**Comment by fncll** [comment]
I should have been more specific, sorry about that. Your suggested change is a bit closer: the calls to old.com are redirecting to new.com, but all requests are going to new.com without the /go/, so a call to 
    https://old.com/go/admin
Is redirecting to
    https://new.com/admin

I'm beginning to think this is an issue with something upstream in the server setup. 

This is my current .htaccess in the /go/ subdirectory:

```
<IfModule mod_rewrite.c>
# BEGIN YOURLS
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /go/
RewriteCond %{HTTP_HOST} ^old.com$
RewriteRule ^(.*)$ https://new.com/$1 [R=301,L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^.*$ /go/yourls-loader.php [L]
</IfModule>
# END YOURLS
```

**Comment by dgw** [comment]
Actually, that's probably fixable by redirecting to `https://new.com/go/$1` instead.

I honestly don't remember how the `RewriteBase` works, but it's probably caused by that.

**Comment by fredl99** [comment]
If I got it right, there is one server running two different domains. Old short-links are pointing to the old domain and the very same server is responding to these requests, which isn't wanted.
The cleanest and clearest solution would be to redirect requests from the old to the new domain. This is described in the [Apache docs](http://httpd.apache.org/docs/current/rewrite/remapping.html#canonicalhost). If you still want to rewrite URLs instead (which isn't really good for that, think about it...*) then that section has a few examples, too.
*) There's no need to run through the whole conditional rewrite chain with every single request, just redirecting the old ones to the new domain would be sufficient.

The directive should reside in a .htaccess file within the DocumentRoot of the **old** domain. (If that's the same as for the new domain, well then you can put it there.) If you have access to the configuration itself that would be even better than any .htaccess file.

After all that's a matter of Apache and in no way a YOURLS issue.

**Comment by fncll** [comment]
For whatever reason, the redirect that was in place in the .htaccess in the root of the server, directing requests from old to new wasn't working with YOURLs (though it was working everywhere else on the server), which was just returning a blank page. I ended up modifying the .htaccess in the root of the server to exclude requests for the /go/ directory and then rewriting requests for the old domain using the .htaccess in the YOURLs folder, which seems to be working.

That everything on the server was working except for YOURLs led me to my question here. 

I don't understand your 2nd paragraph: "if you have access to the configuration itself" -- meaning which configuration? I have access to everything and modified YOURL's config with the new domain name and the .htaccess files as just noted.

**Comment by fredl99** [comment]
Good to see you found a working solution.

I was referring to the Apache configuration. It's always better to manage things there instead of within .htaccess files. Whenever Apaches enters a directory it has to read that file and act accordingly. It's a matter of performance.
