### ISSUE TITLE
Using "a" at the beginning custom URL doesn't work

### ISSUE THREAD

**Issue by phamid** [YOURLS/YOURLS#2460]
**Describe the bug**
Using "a" at the beginning custom URL doesn't work

**To Reproduce**
1. Go to custom url
2. Click on type 'apple'
3. make URL
4. See error customurl.com/pple

**Expected behavior**
custom URL should be 'apple' not 'pple'

**Screenshots**

**Environment (please complete the following information):**
- YOURLS version: 1.7.2
  - Plugins enabled: None
- PHP version: 5.6
- Other relevant details depending on the context (server OS & version, MySQL version, browser version, …)
cPanel Version | 74.0 (build 10)
-- | --
Apache Version | 2.4.33
PHP Version | 5.6.35
MySQL Version | 10.0.35-MariaDB

**Additional context**
n/a

**Comment by dgw** [comment]
I can't reproduce this in my YOURLS install (nginx, php5-fpm). Using `apple` as a custom keyword works just as expected.

Would be interesting to see a screencast of this, and see the `.htaccess` file that goes with this problematic YOURLS instance.

**Comment by ozh** [comment]
I'm betting my money it was a case of "Apple" being converted to "pple". If so, the readme is your friend. If "a" were stripped from short URLs, bug reports would have poured in years ago...

If not so, feel free to comment on with specific details.
