### ISSUE TITLE
SSL/TLS Database Connection

### ISSUE THREAD

**Issue by sergiozygmunt** [YOURLS/YOURLS#2468]
### Technical details regarding my environment

* YOURLS version: 1.7.3
  * Plugins enabled: None
* PHP version: 7.2 but I have tried with 7.0 and 7.1

### Bug description 

**What is the current behavior?**

I am unable to connect to a MySQL database which forces SSL/TLS connections. The error is PDOException: SQLSTATE[HY000] [9002] SSL connection is required. Please specify SSL options and retry

**What is the expected or desired behavior?**

It should be able to connect to a SSL/TLS database.

### Reproducible bug summary 

1. Create a MySQL database and require SSL connection to it.
2. Create a YOURLS instance and complete the config.php file.
3. Try to access /admin and get the error.
---

**Comment by LeoColomb** [comment]
When using secure connexion with MySQL and PHP you need to specify certificate path.

Everything is ready to do this with a plugin, i.e. allowing you to pass [PDO options](https://secure.php.net/manual/ref.pdo-mysql.php).

```php
<?php
/*
Plugin Name: Secure MySQL
Plugin URI: https://github.com/YOURLS/YOURLS/issues/2468
Description: SSL/TLS Database Connection
Version: 1.0
Author: YOURLS
Author URI: https://yourls.org/
*/
// No direct call
if( !defined( 'YOURLS_ABSPATH' ) ) die();

yourls_add_filter( 'db_connect_driver_option', function ( $options ) {
    // Add your certificate paths
    // https://secure.php.net/manual/ref.pdo-mysql.php
    return array_merge( $options, [
        PDO::MYSQL_ATTR_SSL_CA => '/path/to/ca',
    ] );
}
```

**Comment by wahidsaleemi** [comment]
Is there a new way to do this? It doesn't work on my install. While I can connect using mysql CLI, yourls doesn't connect with SSL enabled (on the database server).

**Comment by wahidsaleemi** [comment]
Took me a while to find it but this doesn't work, instead use instructions at https://github.com/YOURLS/YOURLS/issues/2783.
