### ISSUE TITLE
CAN'T UPDATE LONG URL

### ISSUE THREAD

**Issue by msdarke** [YOURLS/YOURLS#2469]
When I update the long url the short url doesn't redirect to the new/updated url. On the info page, the long URL is "clearly" displayed on the page, and when I hover with my mouse it is again displayed in the bottom left of the browser screen. But when I click it, it redirects to the index/home page of the website I'm linking to. The same thing happened when I click on the shortened url also. Very annoying. Now I have to delete all my links and start over using a different shortened name for each. Is there a cache folder I can clear out to resolve this issue?

**Comment by LeoColomb** [comment]
> Is there a cache

Yes, right in your browser. Please clear your browser's cache.

See #1964
