### ISSUE TITLE
Root Folder returns Too Many Redirects

### ISSUE THREAD

**Issue by EMREOYUN** [YOURLS/YOURLS#2470]
**Describe the bug**
Root Host returns "Too Many Redirects" error.

**To Reproduce**
1. Install the 1.7.2 Pack
2. Complete Installiation on /admin/install.php
3. Go Your Root Url
4. 
This Page Doesn't Work! 
"example.url" redirected you too many times.
Try clear your cookies (my site doesn't use any cookies).
ERR_TOO_MANY_REDIRECTS

**Expected behavior**
Standart Webpage loads at your root url.

**Environment (please complete the following information):**
- YOURLS version: 1.7.2
- Plugins enabled: Nothing
- PHP version: IDK but higher than 5

**Comment by master3395** [comment]
If you check what php version you got, i am using 7.1.23, and it works fine, i got no errors.

**Comment by danysz** [comment]
I tried both with php 7.1 and 7.2 and I have the same problem.

**Comment by vitalyzhakov** [comment]
Hello!

Try to use dockerised version https://github.com/YOURLS/docker-yourls, it encapsulates configuration and works fine for me.

**Comment by EMREOYUN** [comment]
Wow, nearly a year passed. I fixed the error but idk how to fixed it. :/

**Comment by dgw** [comment]
I know this is frustrating for anyone running into it, but it's not a problem with YOURLS itself. Anyone having this problem in the future should feel free to ask for help fixing their server configuration at the [YOURLS forum](https://discourse.yourls.org/)!

**Comment by krwags** [comment]
Hello,

I experienced this same problem:  "ERR_TOO_MANY_REDIRECTS" - the problem with my setup was Nginx.  The root location "/" of my install was not specifically told to "index" my site's home page (index.php).  

What you need depends upon what your home page is --OR-- if you are even running a home page.  If not, set the "/" location "index" to /yourls-loader.php

If you have the same problem with multiple versions, it points even more towards your web server's setup.  Apache can fall victim to the same issue.  

Here's the relevant bits from my Nginx conf & PHP conf - I noticed the internet didn't seem to have many exmamples:

# Basic Nginx index.php automatic setup:

    server {

      listen 80;
      listen [::]:80;

      include /etc/nginx/default.d/*.conf;
      server_name example.com;
      root /opt/example;

      location / {
         try_files index.php $uri $uri/ /yourls-loader.php$is_args$args;
         index /index.php;
      }
      location ~ \.php$ {
         try_files $uri =404;
         fastcgi_param REMOTE_USER     $remote_user;
         fastcgi_pass unix:/var/run/php-fpm/www.sock;
         fastcgi_param   SCRIPT_FILENAME $document_root$fastcgi_script_name;
      }
    }





BTW - include /etc/nginx/default.d/*.conf only catches my PHP-FPM CGI conf file.  

cat /etc/nginx/conf.d/php-fpm.conf:


# PHP-FPM FastCGI server - unix domain socket configuration:
upstream php-fpm {
        server unix:/run/php-fpm/www.sock;
}
