### ISSUE TITLE
Directory listing images

### ISSUE THREAD

**Issue by master3395** [YOURLS/YOURLS#2471]
- [ ] Check you are using the [**LATEST** release](https://github.com/YOURLS/YOURLS/releases/latest) or the development branch.
1.7.2

- [ ] Make sure you have [**SEARCHED** existing issues](https://github.com/YOURLS/YOURLS/issues?utf8=%E2%9C%93&q=is%3Aissue) first. 
No information there.

- [ ] Read the [**GUIDELINES**](https://github.com/YOURLS/YOURLS/blob/master/.github/CONTRIBUTING.md) linked in the yellow notice box above.
- [ ] **COMPLETE** this issue template.

**Describe the bug**

This is more of a security notice.
I've made a check on Yourls's status.
And found out that  the directory /yourls/images/
Is showing to anyone.
It's not a big deal, but anyone can open that directory, as it's not hidden in the config.

--

**To Reproduce**
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/4199669/50026512-880fcd80-ffe9-11e8-93b5-9e056722e036.png)

**Environment (please complete the following information):**
- YOURLS version:
  - Plugins enabled:
- PHP version:
- Other relevant details depending on the context (server OS & version, MySQL version, browser version, …)

To many plugins to show in an image.
PHP 7.1.23

**Additional context**

**Comment by LeoColomb** [comment]
Thanks for filing this issue, @master3395!

If I understand well, you are reporting that the server is listing files for a specific directory.

As this behavior come from the server and not from the application (YOURLS), the only configuration to blame is the server's one.
Server owners and/or administrators can configure their server as they want (basically the most secure possible), and if they can use well-known example such as [h5bp/server-configs-*](https://github.com/h5bp/server-configs), we, as YOURLS devs, can't help more than pointing to these recommandations.
