### ISSUE TITLE
Is the app maintainted ?

### ISSUE THREAD

**Issue by anmol26s** [YOURLS/YOURLS#2481]
Hi
There has not been any new release from mid of 2017 but there are regular pull request for the app. Is there a plan release in 2019? I asked this because [ Yunohost](https://yunohost.org) uses the release version to install the core app.

https://github.com/YunoHost-Apps/yourls_ynh

If the new releases are missed the new features will not reach to Yunohost.

Thanks

**Comment by ozh** [comment]
Yeah, seems reasonable to bump a minor update with the latest few fixes

**Comment by ozh** [comment]
https://github.com/YOURLS/YOURLS/releases
