### ISSUE TITLE
PostgreSQL support with the now used PDO library

### ISSUE THREAD

**Issue by doronbehar** [YOURLS/YOURLS#2487]
- [x] Check you are using the [**LATEST** release](https://github.com/YOURLS/YOURLS/releases/latest) or the development branch.
- [x] Make sure you have [**SEARCHED** existing issues](https://github.com/YOURLS/YOURLS/issues?utf8=%E2%9C%93&q=is%3Aissue) first. 
- [x] Read the [**GUIDELINES**](https://github.com/YOURLS/YOURLS/blob/master/.github/CONTRIBUTING.md) linked in the yellow notice box above.
- [x] **COMPLETE** this issue template.

### Technical details regarding my environment

* YOURLS version: 1.7.3
  * Plugins enabled: [redirect-index](https://github.com/tomslominski/yourls-redirect-index)
* PHP version: 7.3

This is more of a feature request. I've read #448 and #2239 and I've learned that making YOURLS use PostgreSQL instead of MySQL is possible by creating a plugin as noted [here](https://github.com/YOURLS/YOURLS/issues/2239#issuecomment-348724272). But since commit https://github.com/YOURLS/YOURLS/commit/a190d2f07e72334126a59ccaa7add77920b16478, YOURLS uses PDO so from what I understand, PostgreSQL support should be available without even creating a plugin.

**Comment by HeapUnderfl0w** [comment]
Is there any update for this?

Attempting to set it up using postgres/pdo, but it just doesn't seem to work really. (i think its something on my end, but a small "how to" would be nice)

**Comment by doronbehar** [comment]
@HeapUnderfl0w If you wish, you can use [my fork](https://github.com/doronbehar/YOURLS) which is based on @iWantToKeepAnon's [fork](https://github.com/iWantToKeepAnon/YOURLS) along with upstream's 1.7.4 changes merged (as suggested [here](https://github.com/iWantToKeepAnon/YOURLS/pull/1)).

**Comment by HeapUnderfl0w** [comment]
you my sir are a godsend, thank you very much.

**Comment by ozh** [comment]
@doronbehar any chance this could be packaged as a plugin ?

**Comment by doronbehar** [comment]
@ozh I don't think it should. There should be a configuration value for that instead. TBH, I'm no PHP developer and I'm just a happy user. @IWantToKeepAnon, which is the original author of this fork, [commented in #2239](https://github.com/YOURLS/YOURLS/issues/2239#issuecomment-488309976):

> But I am content right now to use it and merge upstream changes down into this repo as needed. I'm not sure I have the time or interest to modularize the project, and not sure @ozh would accept such a grand architecture PR anyway.

For reference, here's a link to the diff between my fork (rebased to 1.7.4) and upstream:

https://github.com/YOURLS/YOURLS/compare/master...doronbehar:master

I think it shouldn't be that hard to modularize it but I'm not experienced enough with the PHP ecosystem / development tools to dive in.

**Comment by whalehub** [comment]
@ozh Any update on this?

**Comment by ozh** [comment]
Superseded by linked issue and PR

**Comment by ozh** [comment]
https://github.com/ozh/yourls-postgresql
