### ISSUE TITLE
Share box not showing, missing?  Turn off Ad Blocker!

### ISSUE THREAD

**Issue by vrepub** [YOURLS/YOURLS#2489]
This is not a question, obviously.  I just want to help others who have this problem that I spent hours trying to troubleshoot on a new YOURLS install.  

The only other thread on this issue was imported over from Google code then closed, with no solution shown /issues/238

Anyhow, if that Share box isn't showing on both admin and front end, it's because you have an ad blocker turned on for your YOURLS site.  

TURN YOUR AD BLOCKER OFF!  :)

**Comment by ozh** [comment]
Well, yes, indeed, when you're expecting a popup, sounds sane to turn of pop up blockers :)

**Comment by vrepub** [comment]
Popup?  I'm not talking about the FB and twitter popups that popup when you click the icons.  I'm talking about the share box itself (right next to the short link copybox).    The sharebox does not get bocked because is a popup, it get's blocked because something else in the code makes adbloker think the whole box itself is on-page advertisement.  The dumbest little word or part of a word or number in the code will trigger an adbocker to block something erroneously .
