### ISSUE TITLE
I've tried using this on Freehostias free webhosting plan and not sure if im doing something wrong but it only allows for 1 database, could this be why im having issues creating short links?

### ISSUE THREAD

**Issue by npheria** [YOURLS/YOURLS#2490]
I've tried using this on Freehostias free webhosting plan and not sure if im doing something wrong but it only allows for 1 database, could this be why im having issues creating short links?

**Comment by ozh** [comment]
Could be.

**Comment by dgw** [comment]
There's nowhere near enough information in this issue to answer that.
