### ISSUE TITLE
Made Custom CSS and it works!   ...  BUT

### ISSUE THREAD

**Issue by vrepub** [YOURLS/YOURLS#2492]
I made a custom CSS plugin and it works everywhere (as far as I can tell so far), even on public front end, except it does **not** work on **/admin/upgrade.php** page.

I just don't understand because that page uses the same stylesheet file(s) and CSS rules/properties that all the other pages use, yet my custom CSS does not apply to that page.

Can someone give some insight as to why this is happening?

It's not a big, big deal but it makes me feel like my plugin is broke :(

**Comment by ozh** [comment]
It'll be hard to help without seeing actual code... Host your plugin somewhere (hint: a repo on github) and comment on here.

**Comment by vrepub** [comment]
Just created repository.
https://github.com/vrepub/yourls-custom-css-plugin/blob/master/plugin.php

Just a couple of notes you might want to know about...

- I tried putting custom.css file in the plugin's own folder but that creates problems.  For instance, if I customize/override the background color of body, the whole YOURLS interface disappears and all you see is a screen with your custom color :).  Just an side note, nothing too important, I don't think.

- Other than in the plugin's own folder,  it doesn't matter where I place the custom.css file, it works except upgrade.php still shows original styles.

Thanks

**Comment by ozh** [comment]
In your plugin, line 24: $url isn't defined anywhere within function `vrepub_custom_css()`

**Comment by vrepub** [comment]
Yes, I caught that late last night an moved it into the function, but upgrade.php is still unaffected by the CSS changes.  very strange.
