### ISSUE TITLE
Copy to clipboard function on stats page not working on v1.7.3

### ISSUE THREAD

**Issue by vrepub** [YOURLS/YOURLS#2493]
**Describe the bug**

YOURLS 1.7.3  - on the stats page under the share tab the copy function on the copy box to copy the short link to the clipboard does not work.  

It works fine on the public interface and in the admin index.php page.  It just doesn't work on the stats page >> share tab.

Tried Firefox and Chrome browsers with same results.

I uninstalled all plugins one-by-one to see if it was a plugin conflict, checking the function every time after each deactivation.  Now my YOURLS install is down to vanilla with no plugins activated and the problem still persists so it's not a plugin conflict.  

I also temporarily renamed my plugin folder and the problem still persists.

**I have a v1.7.2 install on another domain and it works fine there so I think this may be a bug in v1.7.3.**

**To Reproduce**
1. Go to stats page of any shortened link
2. Click on the share tab
3. Click on the shortened link in the copy box
4. See if it works

**Expected behavior**
Short link should be copied to clipboard with a message indicating so.

**Environment (please complete the following information):**
- YOURLS version: 1.7.3
- Plugins enabled: **none**
- PHP version: 7.1.26
- Other relevant details depending on the context (server OS & version, MySQL version, browser version, …)
Firefox 64.0.2
Chrome 70.0.3538.110
MySQL 5.7.23

**Additional context**
**I have a v1.7.2 install and it works fine there.**

**Comment by vrepub** [comment]
Was hoping someone might confirm this is a bug or if it's just my install.  Thanks

**Comment by ozh** [comment]
Can confirm. Works fine for me in the admin area, not on stats

**Comment by ewwink** [comment]
> As of jQuery 1.8, the .error() method is deprecated. Use .on( "error", handler ) to attach event handlers to the error event instead.

to fix, in file `js/infos.js` replace 

```
$(img).error(function(){
```

with
```
$(img).on('error', function(){
```

**Comment by LeoColomb** [comment]
@ewwink Oh, thanks a lot for sharing this! Would you aim opening a pull request with this change?

**Comment by ewwink** [comment]
@LeoColomb I have created pull request and you're welcome.

**Comment by LeoColomb** [comment]
Closed by #2508

**Comment by LeoColomb** [comment]
Thanks a lot, @ewwink! 👍
