### ISSUE TITLE
installation issue 

### ISSUE THREAD

**Issue by oahufatcat** [YOURLS/YOURLS#2497]
default installation 
following https://code.tutsplus.com/tutorials/build-your-own-url-shortener-with-yourls--cms-22638

ubuntu 18
no issue to hit the admin page
http://2028.io/admin
takes to http://2028.io/admin/install.php

when click install YOURLS
getting This page isn't working unable to handle this request HTTP error 500

Thank you in adv.

**Comment by dgw** [comment]
HTTP 500 is a generic error code, and doesn't tell us anything.

Check your Apache/PHP error logs: https://askubuntu.com/a/14767/1277

**Comment by oahufatcat** [comment]
looking at error.log 
PHP fatal error uncaught PDOException SQLState[42000] syntax error acccess vi$ess violation 1071 specified key was too long max key length is 767 bytes in /var/www/yourls/includes/vendor/aura/sql/src/ExtendedPdo.php:748\nstack trace

not sure if this helps? 


Thanks.

**Comment by dgw** [comment]
See #2115 and related discussions. You'll find workaround instructions there.

@ozh We need a nickname for this recurring question… :grin:
