### ISSUE TITLE
Charset problem after update to 1.7.3

### ISSUE THREAD

**Issue by diplatis** [YOURLS/YOURLS#2500]
Hi,

after updating to 1.7.3 the titles of all original links before the update are showing with weired chars as shown in the screenshot. I didn't change anything in the database.
![fireshot capture 44 - yourls your own url shortener i https___e-th es_ - https___e-th es_admin_](https://user-images.githubusercontent.com/19187605/51791968-d5b85200-21b3-11e9-94cf-b9b743a34658.png)

**Comment by arialypse** [comment]
Encounter same problem.

**Comment by LeoColomb** [comment]
@diplatis @arialypse Thanks for your reports!
Could you provide requested additional information? At least:
* PHP version
* MySQL version

**Comment by diplatis** [comment]
Php 7.2.14
MySQL 5.5.62

**Comment by LeoColomb** [comment]
@diplatis @arialypse Thanks.

What if you add the following plugin:

```php
<?php
/*
Plugin Name: Test Charset Change
Plugin URI: https://github.com/YOURLS/YOURLS/issues/2500
Description: Not for stying in production
Version: 1.0
Author: YOURLS
Author URI: https://yourls.org/
*/

// No direct call
if(!defined('YOURLS_ABSPATH')) die();

yourls_add_filter('db_connect_custom_dsn', function (string $dsn): string {
    $dsn_array = explode(';', $dsn);
    array_pop($dsn_array);
    return implode(';', $dsn_array);
}
```

---
To add the plugin:
1. Create a simple directory inside `/user/plugins/`, for example `/user/plugins/charset-test/`
2. Create a empty PHP file inside the new directory
3. Edit and past the above code.

**Comment by diplatis** [comment]
I get HTTP ERROR 500 when trying to enable the plugin and get the following in the logs:
PHP Parse error: syntax error, unexpected end of file, expecting ',' or ')' in /var/www/vhosts/hidden/httpdocs/user/plugins/charset-test/plugin.php on line 18\n', referer: https://hidden/admin/plugins.php

**Comment by LeoColomb** [comment]
Sorry, my fault, I updated the code above to fix this.

**Comment by diplatis** [comment]
Nope, no change, not working.

**Comment by ozh** [comment]
Wild shot in the dark with 0.5% chance of improvement: what if you replace 'utf8' with 'utf8mb4' [here](https://github.com/YOURLS/YOURLS/blob/master/includes/class-mysql.php#L31)?

I'm interested to know what it would cause for your previously existing links (same display?) and new links

(from what I understand about utf8, in your case (greek chars) it shouldn't change anything)

**Comment by diplatis** [comment]
No change.
All new links created after the update to 1.7.3 are displayed correctly, only the old ones before the update are wrong.

**Comment by breti** [comment]
Same here. Server migration. MySQL dumped and imported into new DB on new server. Special (non-ASCII) characters are garbled now.

Old server:
- PHP 5.4.45-0+deb7u14
- mysql  Ver 14.14 Distrib 5.5.60
- yourls 1.7

New Server:
- PHP 7.2.15-0ubuntu0.18.04.1
- mysql  Ver 14.14 Distrib 5.7.25
- yourls 1.7.3

**Comment by breti** [comment]
Quick'n'dirty fix is:

replace
`$charset = yourls_apply_filter( 'db_connect_charset', 'utf8' );`
with
`$charset = yourls_apply_filter( 'db_connect_charset', 'latin1' );`
in /yourls/includes/class-mysql.php:31

**Comment by ozh** [comment]
Anyone still following this discussion and having titles fucked up, and willing to try something?

**Comment by rinoshiyo** [comment]
@ozh Hello.

I had the same issue with an upgrade from 1.7.1.
I wrote the following migration script and it seems to work fine.

```
<?php
$db_host = 'mysql';
$db_name = 'db';
$db_user = 'user';
$db_pass = 'user_pass';

# change me
$table = 'url_migrated';

$dbh_latin1 = new PDO("mysql:host=$db_host;dbname=$db_name;charset=latin1", $db_user, $db_pass);
$dbh_utf8 = new PDO("mysql:host=$db_host;dbname=$db_name;charset=utf8", $db_user, $db_pass);

foreach($dbh_latin1->query("SELECT * from $table") as $row) {
#  print_r($row);
  $stmt = $dbh_utf8->prepare("update $table set title = :title where keyword = :keyword");
  $stmt->execute([
    ':keyword' => $row['keyword'],
    ':title' => $row['title'],
  ]);
}

$dbh_latin1 = null;
$dbh_utf8 = null;
```

Thank you for your wonderful product.
