### ISSUE TITLE
yourls_get_option( 'version' ) not giving current version

### ISSUE THREAD

**Issue by joshp23** [YOURLS/YOURLS#2501]
In latest pull from master branch:

On line 1071 of ./includes/functions.php
`$currentver = yourls_get_option( 'version' );`

Resulting value of $currentver (what is in database)
`1.7.2`

On line 6 of ./includes/version.php
`define( 'YOURLS_VERSION', '1.7.4' );`

Apparently, nothing is triggering
`yourls_update_option( 'version', YOURLS_VERSION )`
when the base code version is updated but the database version is not.

**Comment by ozh** [comment]
Indeed, nice catch. For the record, the stored version in the option table on my test box was still "1.5.1-beta" :) This hasn't caused any conflict so far because there hasn't be any need till now, but it could have been a major PITA to debug this in the future when we need it. Again, nice catch :)
