### ISSUE TITLE
Default Shorten URL

### ISSUE THREAD

**Issue by noob2expert** [YOURLS/YOURLS#2503]
By default links that had been shorten look like this:
(www.example.com/short)

What do I need to change in order for the short URL to look like this?
(www.example.com/redirect.php?id=short)

**Comment by LeoColomb** [comment]
Not sure to understand well: you actually want the short URL looks longer?

**Comment by noob2expert** [comment]
Yes, I'm not really concerned with the length. I'm using it for tracking purposes.

**Comment by LeoColomb** [comment]
Then the original short URL is not enough?
Anyway, depending of your configuration, you may either setup a server rewrite to match your need either building a plugin to catch not found error and retry with this new path.

**Comment by noob2expert** [comment]
Why was this marked as invalid and closed? Can you at least provide a code snippet so that I know where to start? I appreciate your response but I'm a newbie who's still learning.

**Comment by LeoColomb** [comment]
@noob2expert I closed this issue because it is not an issue for YOURLS itself.
As I said, making your request working depends on your configuration. You may prefer request your host to help you rewriting `redirect.php?id=xyz` to `yourls-go?id=xyz`.
