### ISSUE TITLE
Add Deep links Support like bitly

### ISSUE THREAD

**Issue by kodeine** [YOURLS/YOURLS#2504]
Adding deep links support would be a great feature.
[more details](https://bitly.com/blog/ap-mobile/)

**Comment by ozh** [comment]
This is definitely plugin territory. Should be rather easy to do, checking user agent and serving `http:` URL or `app:` URL. See https://github.com/YOURLS/YOURLS/wiki/Possible-With-A-Plugin

**Comment by mrlufus** [comment]
There is still no plugin, which helps with this issue. 
Can we get a native support in YOURLS? 

:)
