### ISSUE TITLE
bug, admin login valid, bad web redirect

### ISSUE THREAD

**Issue by jferran95** [YOURLS/YOURLS#2506]
There is an error in file: functions-auth.php; Line: 83;
The content needed in $_SERVER['HTTP_HOST'] is not equal to used $_SERVER['SERVER_NAME'].
See before fix:
`//$url = yourls_match_current_protocol(yourls_sanitize_url(sprintf("%s%s", $_SERVER['SERVER_NAME'], $_SERVER['REQUEST_URI'])));`
See after fix:
`$url = yourls_match_current_protocol(yourls_sanitize_url(sprintf("%s%s",YOURLS_SITE, $_SERVER['REQUEST_URI'] )));`

**Explain perceived error:**
Configure [protocol]://www.domain.name. After login web redirects to: [protocol]://domain.name. This fails to recognized already logged in. I speculate: maybe the cookie (keeps session) is linked to the host-name (with: www.) instead of the domain-name.

**Specifics to my installation:**
I enabled the program with a domain name for testing, another for pre-production, then another for production. Having enabled server to listen to all three domains. But the program is configured once in defined constant: YOURLS_SITE. And the value defined in there is not being used in web redirect after login success.
In my scenario I changed to enable a dynamic site:
`define( 'YOURLS_SITE', 'https://'.$_SERVER['HTTP_HOST'] );`
So I can better handle security. I can hide "/admin/" dir from the public hostname in HTTP. And have it only visible in another hostname -or- domain using HTTPS.

**Comment by ozh** [comment]
YOURLS_SITE is the install root, eg "http://sho.rt" or "http://mysite.com/shorturl" : in _your specific_ case you can define it as above, but this isn't going to work for everybody, especially people installing YOURLS in a subdir
