### ISSUE TITLE
How to segregate admin and non-admin users and have a different URL for both of them.

### ISSUE THREAD

**Issue by CloudDevOps-Engineer** [YOURLS/YOURLS#2509]
Hi All,

Can anyone please brief me about how to create new non admin users and have a seperate URL other than /admin.

Any help is highly appreciated. TIA

**Comment by CloudDevOps-Engineer** [comment]
Hi All,

Can anyone please brief me about how to create new non admin users and have a seperate URL other than /admin.

Any help is highly appreciated. TIA

**Comment by CloudDevOps-Engineer** [comment]
Hi @LeoColomb ,

Can you please help me with this..?

**Comment by LeoColomb** [comment]
@CloudDevOps-Engineer 
It's up to you to add a new PHP page with exactly what you want.
You may take a look at the [`examplepage.php`](https://github.com/YOURLS/YOURLS/blob/1f2af77bb85cbc9caf4abcd1cae219381698646a/pages/examplepage.php) to get started.
