### ISSUE TITLE
Can't Create Short URL

### ISSUE THREAD

**Issue by stone212** [YOURLS/YOURLS#2511]
- [x] Check you are using the [**LATEST** release](https://github.com/YOURLS/YOURLS/releases/latest) or the development branch.
- [x] Make sure you have [**SEARCHED** existing issues](https://github.com/YOURLS/YOURLS/issues?utf8=%E2%9C%93&q=is%3Aissue) first. 
- [ ] Read the [**GUIDELINES**](https://github.com/YOURLS/YOURLS/blob/master/.github/CONTRIBUTING.md) linked in the yellow notice box above.
- [x] **COMPLETE** this issue template.

**Describe the bug**
Using 1.7.3 when I type a valid HTTPS URL into the URL field and click `Shorten the URL` that button turns green and does nothing more.

**To Reproduce**
1. Go to `mysite.com/admin`
2. Enter a URL.  Then Click on `Shorten the URL` button
3. Notice how the button is green with a swirling icon.
4. And nothing more.
5. Enable debug.
6. See on re-freshed page:

```
Connected to database yourls on localhost 
SQL: SELECT option_name, option_value FROM yourls_options WHERE 1=1 (0.00106 s)
Check for new version: no
SQL: SELECT COUNT(keyword) as count, SUM(clicks) as sum FROM `yourls_url` WHERE 1=1  (0.00020 s)
SQL: SELECT * FROM `yourls_url` WHERE 1=1  ORDER BY `timestamp` desc LIMIT 0, 15; (0.00015 s)
```
6. Click button again.
7. See that the debug message didn't change.

**Expected behavior**
I thought it would give me a shortened URL.

**Environment (please complete the following information):**
- YOURLS version: 1.7.3
  - Plugins enabled: What is this?
- PHP version: 7
- Other relevant details depending on the context (server OS & version, MySQL version, browser version, …)  Ubuntu 16.04

**Comment by hemor** [comment]
I just experienced the same issue. I checked chrome dev tools and I saw that the problem was due to CORS error. I reopened the page using https and it worked fine. I checked again without https and problem persists. I don't know if this is the intended behavior or this is a bug.

Try opening the page using https and see if it works for you.

**Comment by ozh** [comment]
https://github.com/YOURLS/YOURLS/wiki/Endless-Spinning-Icon ?

**Comment by hemor** [comment]
Thank you but the problem is when I open https://short.com/admin, after login yourls redirects to non-https url http://short.com/admin. It'd be helpful if yourls automatically redirect to the https version after login.

**Comment by stone212** [comment]
@hemor the https version solved the problem.  Thank you.
