### ISSUE TITLE
Fresh install Not connecting to MariaDB10

### ISSUE THREAD

**Issue by dtswcan** [YOURLS/YOURLS#2514]
error message
Incorrect DB config, or could not connect to DB
PDOException: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)

Yourls version 1.7.3
Apache 2.2
php 5.6 with mysql  driver active

Maria10 DB Server
/** MySQL database username */
define( 'YOURLS_DB_USER', 'root' );

/** MySQL database password */
define( 'YOURLS_DB_PASS', 'XXXX' );

/** The name of the database for YOURLS */
define( 'YOURLS_DB_NAME', 'yourls' );

/** MySQL hostname.
 ** If using a non standard port, specify it like 'hostname:port', eg. 'localhost:9999' or '127.0.0.1:666' */
define( 'YOURLS_DB_HOST', 'localhost:3307' );

/** MySQL tables prefix */
define( 'YOURLS_DB_PREFIX', 'yourls_' );
define( 'YOURLS_DB_DRIVER', 'mysql' );

Any help to track down this error would be much appreciated

**Comment by ozh** [comment]
Your user 'root' doesn't have access: either it's denied to be used by server config, or it's an incorrect password. Good practice: create a user, grant needed privileges (ie all) on `yourls_` tables or `yourls` DB, and don't use root.

**Comment by dtswcan** [comment]
ozh thank you for the reply,  I started with a user and when to the root hoping to troubleshoot the problem
Either user or root I am still getting the same error.  I set up about 7 application all Accessing the same Maria DB server no problems until installing Yourls, and this is my 3rd install of Yourls with not problems to date, but this my first Maria 10 DB.  Could it be a the sql driver I have selected in PHP ?
'

**Comment by dtswcan** [comment]
OK Found the problem

The Server has Maria10 and Maria5 they are set to different ports. however it seems setting the port in the server address like localhost:9999 does not help Yourls find the right server in this case Maria10.. I know this as Yourls did connect to Maria5 once I set up a user
