### ISSUE TITLE
URLs with encoded characters get decoded

### ISSUE THREAD

**Issue by 7AC** [YOURLS/YOURLS#2522]
I've noticed that a URL like

```
http://foo.com/bar%3Dbaz
```

ends up being stored as:

```
http://foo.com/bar=baz
```

So basically looks like the characters get decoded while storing the URL instead of keeping them as they are.

**Comment by dgw** [comment]
Duplicate of #1651 I think

**Comment by 7AC** [comment]
Looks like it thanks
