### ISSUE TITLE
Plugin conflic

### ISSUE THREAD

**Issue by zhoumin** [YOURLS/YOURLS#2524]
Hi,
   I found that the two plugins "Allow Forward Slashes in Short URLs" and "IQRCodes" have conflicts..When this Allow Forward Slashes in Short URLs is activated, this IQRCodes will cause the QR code to display broken images. Can you solve the problem? Thank you!
![aa](https://user-images.githubusercontent.com/2437974/58033856-d8222b80-7b57-11e9-8d8b-9a6d2b4b694c.png)

**Comment by ozh** [comment]
Please contact plugin authors. There may, or may not, something to fix.
