### ISSUE TITLE
Passwords not auto-encrypting

### ISSUE THREAD

**Issue by justkristin** [YOURLS/YOURLS#2525]
Lovely people, I have somehow screwed up and can no longer change any user passwords :(

Our original installation and setup of YOURLS went swimmingly, but a user recently forgot her password, and any attempts to reset it, or to add a new user and encrypt their password, are failing. Even MD5-encrypted passwords are not allowing login - the only way I can now successfully log in is using known, previously entered and encrypted user password pairs. I have turned on debug, but nothing useful shows (and, to be honest, if the debug messages show at the bottom of the page, they were already showing with debug set to "FALSE", and this is all they show:
> Connected to database databasename on dbserver 
> Check for new version: no

I have tried changing the user's entry in the password section, simply replacing the phpass with plaintext:
> 'tuser' => 'theplaintextpassword',

and also moved their entry line above and below the current, working entries, making sure that commas are in place. I also tried creating an md5 version (using the YOURLS salted hash generator) and adding it like this:

> 'tuser' => 'md5:71688:0ce43474167f743b7b92d046ae970801',

but that didn't work either. Logins fail when attempting either, and in the case of the initially unencrypted string, the string never becomes encrypted.

I have:
* set the config.php file to 666 temporarily
* made sure the ownership is set correctly
* restarted Apache
* logged out and in repeatedly as the users currently able to log in and out
All to no avail. The only message I get when trying to log in, either in the case of a non-encrypted user or an MD5-encrypted user, is
> Invalid username or password

I am running on:
* Ubuntu 18.04.2 LTS
* PHP 7.2.17-0ubuntu0.18.04.1
* Apache/2.4.29 (Ubuntu)
* YOURLS 1.7.2

Like I said, I am sure I have simply pooched something, as I only know enough to be dangerous, but any help would be greatly appreciated!

**Comment by justkristin** [comment]
Please consider this closed. I am an idiot. I was looking at the wrong server because of an old hosts file entry. *shameface*

**Comment by ozh** [comment]
Happens even to the best sometimes :)
