### ISSUE TITLE
Clear Stats

### ISSUE THREAD

**Issue by BenJackGill** [YOURLS/YOURLS#2527]
Is it possible to manually clear the stats?

I was testing some links by clicking on each one, and now I want to leave my links up but I need to clear the link stats so that they start counting again from zero.

**Comment by dagee3** [comment]
Hello @bennygill ,
There is a plugin that you can install that hides stats from any logged in user which is what you may be wanting.  The plugin can be found [here](https://github.com/dgw/yourls-dont-track-admins).  If you don't want to use this the only other option would be going into the database and manually changing these values.  I highly recommend using the plugin.

**Comment by LeoColomb** [comment]
X-Ref: #354 

Thanks @dagee3 for this relevant suggestion!
