### ISSUE TITLE
error in the api, when I short an "&" character

### ISSUE THREAD

**Issue by edwincastel** [YOURLS/YOURLS#2528]
Hi,
When the api shortens a url with the character "&" example www.miweb.com/index.php?name=xx&city=yy&age=zz, it only shortens to the first character "&", example: www.miweb.com/index .php? name = xx

Could you help me please

Thank you

**Comment by dgw** [comment]
When passing URLs to the API, you **must** encode special characters, such as `&`, that have special meaning in URLs. In this case, replacing `&` with `%26` should fix the problem, but I'd recommend finding a function in the programming language you're using to call the API that will just handle encoding specials for you.
