### ISSUE TITLE
URLs that use %2B are converted to +

### ISSUE THREAD

**Issue by RadGH** [YOURLS/YOURLS#2530]
* [x] I've read the [guidelines for Contributing to YOURLS Projects](https://github.com/YOURLS/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://yourls.org/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [YOURLS Discourse](https://discourse.yourls.org/) community

**Describe the bug**
I am using ShareX to take screenshots, which upload to Amazon S3, and then a short link is created with YOURLs. This works fine most of the time.

When I take a screenshot of Notepad++, the filename that is generated looks like:
`notepad++_2019-06-19_18-29-56.png`

On Amazon S3, the URL encodes the plus signs as %2B:
`https://xxx.amazonaws.com/xxx/ShareX/2019/06/notepad%2B%2B_2019-06-19_18-29-56.png`

When that URL is sent to YOURLs, the plus signs are converted back:
`https://xxx.amazonaws.com/xxx/ShareX/2019/06/notepad++_2019-06-19_18-29-56.png`

You can also test this quickly by adding your own short URL in the admin area. It doesn't have to be a real URL, for example: `https://radleysustaire.com/testing%2B` gets converted to `https://radleysustaire.com/testing+`

I created a small plugin to fix the problem, although this would break any URLs which **DO** use a literal plus sign:

```
yourls_add_filter( 'sanitize_url', 'rs_escape_plus_signs' );
function rs_escape_plus_signs( $in ) {
	return str_replace('+', '%2B', $in);
}
```

**To Reproduce**
1. Create a shorturl for "https://radleysustaire.com/testing%2B"
2. Notice it changes to "https://radleysustaire.com/testing+"
3. For some hosts this is probably not an issue, but for amazon s3 it results in an error.

**Expected behavior**
Keep the original url with %2B

**Actual behavior**
The url changes to +

**Screenshots**
Example of the problem: https://s3-us-west-2.amazonaws.com/elasticbeanstalk-us-west-2-868470985522/ShareX/2019/06/notepad++_2019-06-19_18-29-56.png

What it should be: https://s3-us-west-2.amazonaws.com/elasticbeanstalk-us-west-2-868470985522/ShareX/2019/06/notepad%2B%2B_2019-06-19_18-29-56.png

**Versions**
1.7.3 - I just updated to test, problem still exists

**Comment by LeoColomb** [comment]
> When that URL is sent to YOURLs

The URL should be sent encoded. I mean `%2B` should be encoded, that value is `%252B`.
How do you send the URL to YOURLS?
