### ISSUE TITLE
Ability to add different shorts for the same url

### ISSUE THREAD

**Issue by gerroon** [YOURLS/YOURLS#2531]
Hi,

I was trying to add a  second  shortened url (with a different name) for a url that already exists. And YOURLS complaint about it and did let me to add it. 

It would be nice if YOURLS has the ability to add urls for duplicate entries. This is useful when one wants to share the same url in different places to track visits.

thanks

**Comment by dgw** [comment]
This is already possible with the `YOURLS_UNIQUE_URLS` constant.

See #1901, #2028, #2186, and probably others (I'm on mobile).

**Comment by gerroon** [comment]
Ashamed :( thanks
