### ISSUE TITLE
Problem on shorten a Google Drive link

### ISSUE THREAD

**Issue by marcosaljr** [YOURLS/YOURLS#2532]
I'm trying to shorten a Google Drive link. Every day I shorten this link style. Now it is not loading and concluding. What can it be?

![image](https://user-images.githubusercontent.com/52473362/60552962-649f3c80-9d07-11e9-900b-f2c93d9487d6.png)

**Comment by LeoColomb** [comment]
Thanks for this report @marcosaljr.

What is your YOURLS version?
Did you do a upgrade recently?
Is this behavior is visible for this specific link only?
