### ISSUE TITLE
Windows server URL submission error

### ISSUE THREAD

**Issue by wyfang** [YOURLS/YOURLS#2534]
![TIM截图20190720004014](https://user-images.githubusercontent.com/17900420/61551206-23d55080-aa87-11e9-8e3d-abc3746d3e67.png)

**Comment by dgw** [comment]
There's an issue with the server configuration, most probably. However, the screenshot doesn't include any information that might help find it. Any number of issues could cause error 500 with YOURLS Ajax requests.

**Comment by jetfueled** [comment]
I have the exact same issue. I've worked out that it seems to be with my host & lack of access to certain things.
@wyfang would you happen to be on shared hosting?

**Comment by wyfang** [comment]
> I have the exact same issue. I've worked out that it seems to be with my host & lack of access to certain things.
> @wyfang would you happen to be on shared hosting?

No, I'm a standalone server. I found that this occurs because the address entered is also a short link or a jump link. If it is a normal web page link, there is no problem. This problem occurs on my Windows server, and my Linux server does not have this problem.

**Comment by LeoColomb** [comment]
Thanks for opening this @wyfang.
As explained by @dgw, it's hard to understand what's going on with a single screenshot. 
Is it possible to provide a log when errors are reported with details?
