### ISSUE TITLE
Javascript Redirect

### ISSUE THREAD

**Issue by 01fenix** [YOURLS/YOURLS#2535]
Hi, I used Yourls long ago and a friend had modified it for doing a javascript redirect. The version been updated a lot since then. Can someone tell me how to modify the script to use javascript for redirecting?

Thanks

**Comment by dgw** [comment]
Why do you want to use JavaScript for redirecting? The way YOURLS does it out of the box (with HTTP headers) is much more efficient, better for SEO, and compatible no matter what browser your visitors use or whether they disable JS.

If you really want to do it, I'm sure it's still possible. I just think you'd probably be better off choosing a different application at that point.

**Comment by 01fenix** [comment]
I need it for social media like snapchat links to prevent the bots from following the URL. I know Yourls can do it, as I did this about 10 years back for Twitter as well.

I don't need it for SEO.

**Comment by dgw** [comment]
My guess is that whatever your friend did in the old version should still work. The code hasn't changed all that much, really. It _might_ need minor tweaks, if anything at all.

**Comment by 01fenix** [comment]
Yea the problem is I don't know what file he modified. I thought it would be functions.php but both files I scanned and they're the same code.

**Comment by dgw** [comment]
All I can suggest (from my phone here) is that you use your favorite recursive diff tool to compare the old and new folders, and search for addition or removal of relevant strings like "javascript". Also check the plugins on your old install, since it should be possible to implement this without hacking core (our mantra when it comes to customization).

**Comment by 01fenix** [comment]
I had found this also: https://stackoverflow.com/questions/2308727/yourls-redirect-with-javascript

But the code looks the same like it's not modified from the original so I'm not sure how it would be using javascript.

**Comment by ozh** [comment]
1) update YOURLS. Delete all the custom code that has been modified here and there because [this is stupid](https://github.com/YOURLS/YOURLS/wiki/Dont-Hack-Core)

2) the following plugin should do:

```php
<?php
/*
Plugin Name: Javascript Redirect
Plugin URI: http://yourls.org/
Description: Javascript redirect
*/

// No direct call
if( !defined( 'YOURLS_ABSPATH' ) ) die();

// When a redirection to a shorturl is about to happen, write some content to force js
yourls_add_action( 'redirect_shorturl', 'ozh_print_shit' );

function ozh_print_shit() {
    yourls_status_header(200);
    echo "<p>You are redirected, wait</p>"
}
```
