### ISSUE TITLE
1.7.3 vendor error/warnings

### ISSUE THREAD

**Issue by master3395** [YOURLS/YOURLS#2537]
I get the errors below, without knowing why.
YOURLS v 1.7.3

PHP 7.2.17.

```
Stack trace:
#0 /home/username/public_html/yourls/includes/vendor/aura/sql/src/ExtendedPdo.php(748): PDOStatement->execute()
#1 /home/username/public_html/yourls/includes/vendor/aura/sql/src/ExtendedPdo.php(306): Aura\Sql\ExtendedPdo->perform('INSERT INTO `n1...', Array)
#2 /home/username/public_html/yourls/includes/functions.php(897): Aura\Sql\ExtendedPdo->fetchAffected('INSERT INTO `n1...', Array)
#3 /home/username/public_html/yourls/includes/functions.php(740): yourls_log_redirect('simplesuperfors...')
#4 /home/username/public_html/yourls/yourls-go.php(21): yourls_redirect_shorturl('https://simples...', 'simplesuperfors...')
#5 /home/username/public_html/yourls/yourls-loader.php(37): require_once('/home/username...')
#6 {main}
  thrown in /home/username/public_html/yourls/includes/vendor/aura/sql/src/ExtendedPdo.php on line 748
```

-----------------------------------------------------------------------------------------------------------
```
Active plugins:

302 Instead + 301 for YOURLS URLs
--
404-Redirect
API Action - Delete
Ad Redirect
Admin reCaptcha
Advanced Reserved URLs
Allow Hyphens in   Short URLs
Allow aliases
Anti spam
Authorization Manager
BlackListIP
Bulk Import and Shorten
Cache stat pages
Change error messages
Check URL
CloudFlare
Fallback URL
Fix Long URL
Force Lowercase
GA
GA-Measurement-Protocol
Geo API plugin
Git Version
Google Analytics
Google Safe Browsing
HTTP Proxy
JappixMini chat on admin pages
Keywords, Charset & Length
List Links
Mailto: quickshare
Mass Remove Links
Mass Updater
Piwik
Popular Clicks
Popular Clicks Extended
QR Code Short URLS
Random Backgrounds
Random Keywords
Redirect with GET
Return   To Main Website
Share G+
Share on Tumbler
Shortshort
Sleeky Backend
Time limited Links   with Fallback
YOURLS Import Export
YourlsBlackListDomains
dnsbl
yourls-virustotal
```

**Comment by LeoColomb** [comment]
Thanks for opening this issue, @master3395.

The error you provided doesn't actually include an error output but just the stack trace. Then we can't know what is the error neither help you.

**Comment by master3395** [comment]
The stack trace is what i keep getting when moving to a new php.
(php 7.3)
It was happening on php 7.2 as well.
I have no other things in the log.
But this keeps happening many times.

> Thanks for opening this issue, @master3395.
> 
> The error you provided doesn't actually include an error output but just the stack trace. Then we can't know what is the error neither help you.

**Comment by LeoColomb** [comment]
I'm sorry but without any error description _we can't help you_, except that there is an issue with PDO (did you check if the PHP extension is enabled?).
The error description is usually the line before the stack trace.

I'm closing for now as incomplete, but please continue the discussion below if you have any more information.
