### ISSUE TITLE
Spam links still being created with reCAPTCHA v2

### ISSUE THREAD

**Issue by jaykepeters** [YOURLS/YOURLS#2540]
Greetings everyone,

I am having issues with spam links being created at **shrinky.link**/**http://ws.jpits.us/yourls/**, even with reCAPTCHA v2 enabled at the highest setting. Here's what my public front page looks like: 
```php
<?php
// Start YOURLS engine
require_once( dirname(__FILE__).'/includes/load-yourls.php' );



// Change this to match the URL of your public interface. Something like: http://your-own-domain-here.com/index.php
$page = YOURLS_SITE . '/index.php' ;

// Part to be executed if FORM has been submitted
if ( isset( $_REQUEST['url'] ) && $_REQUEST['url'] != 'http://' ) {
	include('captcha.php'); if ($resp != null && $resp->success) {

	// Get parameters -- they will all be sanitized in yourls_add_new_link()
	$url     = $_REQUEST['url'];
	// $keyword = isset( $_REQUEST['keyword'] ) ? $_REQUEST['keyword'] : '' ;
	// $title   = isset( $_REQUEST['title'] ) ?  $_REQUEST['title'] : '' ;
	$text    = isset( $_REQUEST['text'] ) ?  $_REQUEST['text'] : '' ;

	// Create short URL, receive array $return with various information
	$return  = yourls_add_new_link( $url, $keyword, $title );
	
	$shorturl = isset( $return['shorturl'] ) ? $return['shorturl'] : '';
	$message  = isset( $return['message'] ) ? $return['message'] : '';
	$title    = isset( $return['title'] ) ? $return['title'] : '';
	$status   = isset( $return['status'] ) ? $return['status'] : '';
	} else {
	 // die("Error: INVALID CAPTCHA");
         yourls_die( $message = 'You must solve captcha', $title = '', $header_code = 200 );
}
}

// Insert <head> markup and all CSS & JS files
yourls_html_head();

// Display title
// echo "<h1>YOURLS - Your Own URL Shortener</h1>\n";
   echo "<h1>Shrinky.Link – Shrink your links</h1>";

// Display left hand menu
// yourls_html_menu() ;

// Part to be executed if FORM has been submitted
if ( isset( $_REQUEST['url'] ) && $_REQUEST['url'] != 'http://' ) {

	// Display result message of short link creation
	if( isset( $message ) ) {
		echo "<h2>$message</h2>";
	}
	
	if( $status == 'success' ) {
		// Include the Copy box and the Quick Share box
		yourls_share_box( $url, $shorturl, $title, $text );
		
		// Initialize clipboard -- requires js/share.js and js/clipboard.min.js to be properly loaded in the <head>
		echo "<script>init_clipboard();</script>\n";
	}

// Part to be executed when no form has been submitted
} else {

		$site = YOURLS_SITE;
		
		// Display the form
		echo <<<HTML
		<h2>Enter a new URL to shorten</h2>
		<form method="post" action="">
		<p><label>URL: <input type="text" class="text" name="url" value="http://" /></label></p>
		<div class="g-recaptcha" data-sitekey="6LfDBZgUAAAAAAzrqDz3gIiaXAokTXpsWMIfjKBx"></div>
		<p><input type="submit" class="button primary" value="Shorten" /></p>
		</form>	
HTML;

}

?>

<p>Thank you for using Shrinky.Link</p>
<p>This project is maintained By: <a href="http://jayke.me">Jayke Peters</a></p>
<h2>Want to customize your links?</h2>
<p>Register for an account at the <a href="https://support.jpits.us/open.php?topicId=15">Help Desk</a></p>
<h2>Abuse</h2>
<p>Clicked on a bad link? Report abuse <a href="mailto:abuse@shrinky.link">here</a>
<p>If you can't click on the link, email us at <strong>support at jpits dot us</strong></p>

<script data-cfbadgetype="f" data-cfbadgeskin="logo" type="text/javascript">
//<![CDATA[
try{window.CloudFlare||function(){var a=window.document,b=a.createElement("script"),a=a.getElementsByTagName("script")[0];window.CloudFlare=[];b.type="text/javascript";b.async=!0;b.src="//ajax.cloudflare.com/cdn-cgi/nexp/cloudflare.js";a.parentNode.insertBefore(b,a)}(),CloudFlare.push(function(a){a(["cloudflare/badge"])})}catch(e$$5){try{console.error("CloudFlare badge code could not be loaded. "+e$$5.message)}catch(e$$6){}};
//]]>
</script>

<?php

// Display page footer
yourls_html_footer();
```

Some additional information that may or may not help resolve the issue:
- Captcha Tutorial Followed by Jared Stark (blog.yourls.org)
- Cloudflare CDN is being used
- Ubuntu 16.04
- PHP 7.2.17-1+ubuntu16.04.1+deb.sury.org+3 (cli) (built: Apr 10 2019 10:50:19) ( NTS )
- mysql  Ver 14.14 Distrib 5.7.26, for Linux (x86_64) using  EditLine wrapper
- YOURLS version 1.7.3
- Apache 2.4

DB DUMP: [yourls_url.pdf](https://github.com/YOURLS/YOURLS/files/3459627/yourls_url.pdf)

Any help would be much appreciated! 

Thanks,

Jayke

**Comment by dgw** [comment]
I wonder what reCAPTCHA does if your domain and API key do not match?

![image](https://user-images.githubusercontent.com/164140/62345094-6c90fe80-b4b6-11e9-9c5b-c403fd634b1e.png)

Try giving the alternate domain a valid reCAPTCHA key.

Also see if you can find the actual requests creating the spam links in your web server logs. I can't shake the thought that they might not be coming in through your public UI at all…

**Comment by jaykepeters** [comment]
> I wonder what reCAPTCHA does if your domain and API key do not match?
> 
> ![image](https://user-images.githubusercontent.com/164140/62345094-6c90fe80-b4b6-11e9-9c5b-c403fd634b1e.png)
> 
> Try giving the alternate domain a valid reCAPTCHA key.
> 
> Also see if you can find the actual requests creating the spam links in your web server logs. I can't shake the thought that they might not be coming in through your public UI at all…

Try it again

**Comment by jaykepeters** [comment]
![image](https://user-images.githubusercontent.com/37952082/62345426-0016ff00-b4b8-11e9-9642-662057130bd8.png)

**Comment by dgw** [comment]
Yeah, aside from putting a valid reCAPTCHA API key for your alternate domain(s) and checking the request logs to see how the spam links are getting submitted… I'm out of ideas for the moment.

I verified that disabling JavaScript or failing to solve the reCAPTCHA fails to submit a link, as does manually POSTing to the form endpoint. I very much doubt that your front page is the weak link. I encourage you to look into your request logs. Pick a recent spam link, and look for the request that created it in Apache's logs for all domains that point to this YOURLS database.

**Comment by jaykepeters** [comment]
> Yeah, aside from putting a valid reCAPTCHA API key for your alternate domain(s) and checking the request logs to see how the spam links are getting submitted… I'm out of ideas for the moment.
> 
> I verified that disabling JavaScript or failing to solve the reCAPTCHA fails to submit a link, as does manually POSTing to the form endpoint. I very much doubt that your front page is the weak link. I encourage you to look into your request logs. Pick a recent spam link, and look for the request that created it in Apache's logs for all domains that point to this YOURLS database.

Thanks, I will see what I can do. Cloudflare has some other WAF features that I can utilize in the meantime, or I can just restrict it to US IP addresses only to rule out any bad guys.

Do you know off the top of your head any other secondary methods that will fool bots, but is easy for humans? I've heard of an invisible form or something like that...

Thanks,

Jayke Peters
Sartell, MN
jayke@jayke.net
+1 (612) 219-2778

**Comment by dgw** [comment]
_Please_ just check your logs. That's why you _have_ server logs. Cloudflare shouldn't matter, because we aren't interested in the source IP, but the requested URL and HTTP verb used.

reCAPTCHA is so popular, I'd say you would have heard about a flaw like this before. Or more likely, it would have been fixed long ago. I'm more inclined to believe it's a server misconfiguration, a bug in the frontend, or _maybe_ (but not likely) a security hole in YOURLS' API. (If you've set YOURLS' cookie key constant, and defined non-default username(s) in the config, it's highly improbable that anyone could attack your authenticated API by spoofing the signature.)

**Comment by jaykepeters** [comment]
> _Please_ just check your logs. That's why you _have_ server logs. Cloudflare shouldn't matter, because we aren't interested in the source IP, but the requested URL and HTTP verb used.
> 
> reCAPTCHA is so popular, I'd say you would have heard about a flaw like this before. Or more likely, it would have been fixed long ago. I'm more inclined to believe it's a server misconfiguration, a bug in the frontend, or _maybe_ (but not likely) a security hole in YOURLS' API. (If you've set YOURLS' cookie key constant, and defined non-default username(s) in the config, it's highly improbable that anyone could attack your authenticated API by spoofing the signature.)

Thanks again. I will be investigating. I think I am going to make a dummy YOURLS installation, just for bots to abuse, so I can further gain insight. I will do many tests, and maybe I can help make YOURLS better. 
- With reCAPTCHA
- Without reCAPTCHA
- User Agents
- IP Blocks
- URLS
- HTTP METHODS, PUT, GET, POST, etc. 
And other parameters that I may want to monitor...

**Comment by Happyfeet01** [comment]
Hello, i get also spam links and i use recaptcha v3.   How can i make it harder to create links for SPAM?   Maybe a word Blacklist?
