### ISSUE TITLE
`yourls_plugin_url()` breaks on symlinks

### ISSUE THREAD

**Issue by dgw** [YOURLS/YOURLS#2541]
* [x] I've read the [guidelines for Contributing to YOURLS Projects](https://github.com/YOURLS/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://yourls.org/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [YOURLS Discourse](https://discourse.yourls.org/) community

**Describe the bug**
If a plugin directory is symlinked into YOURLS' plugins directory, calls to `yourls_plugin_url()` for that plugin's directory return nonexistent, incorrect URLs.

**To Reproduce**
1. Symlink a plugin directory into `YOURLS_ROOT/user/plugins/`
2. Load a page that the plugin affects, e.g. by injecting a script or stylesheet

A plugin that uses `yourls_plugin_url()` is needed, of course. I discovered this issue while installing the [Sleeky](https://github.com/Flynntes/Sleeky) backend.

So, let's say I have a plugin living in `/home/dgw/repos/Sleeky/sleeky-backend`, with symlink `/home/dgw/yourls/user/plugins/sleeky-backend` pointing to it, for the purpose of explanation.

**Expected behavior**
The injected asset loads correctly. `yourls_plugin_url('file.ext')` generates the URL `https://yourls_site/user/plugins/sleeky-backend/file.ext`

**Actual behavior**
The injected asset fails to load, because the URL generated is incorrect. `yourls_plugin_url('file.ext')` generates `https://yourls_site/home/dgw/repos/Sleeky/sleeky-backend/file.ext`.

**Versions**
YOURLS 1.7.x (the code for this function has not changed since 1.6) on Ubuntu Linux under nginx with php-fpm.

**Additional context**
I made the examples above with a specific file for clarity. However, Sleeky itself uses `yourls_plugin_url( __DIR__ )` and then stores that value for later. Either way, the method used in `yourls_plugin_basename()` to remove the leading absolute path is likely the root cause here.

There's an easy workaround to this, of course: Don't symlink plugin directories. But this approach to adding plugins works in many, many different software packages—I use it a ton. Low priority this bug may be, I do think it really _is_ a bug.

**Comment by paulgoodchild** [comment]
I decided to take a look at this for you.

As you know, the Sleeky plugin uses `__DIR__` and passes it through to `yourls_plugin_url()`. Unfortunately `__DIR__` will always resolve the symlink to the full and correct path of the file, so the YOURLS function `yourls_plugin_url()` will be unable to do anything besides what it's already doing - it wont know the path was originally a symlink as it's just sent the string to handle.

The path that you want to use (via symlink) will need to resolved _before_ the URL is built (which is impossible, as Sleeky uses `__DIR__`), or you adjust the URL _afterwards_ using the yourls' URL filter.

Afterwards is much easier. Here is some code you could add (perhaps create your own quick YOURLS plugin to keep your code snippets if you're not doing that already):

```php
yourls_add_filter( 'plugin_url',
    function ( $sUrl ) {
        return str_replace( '/home/dgw/repos/Sleeky/sleeky-backend/', '/user/plugins/sleeky-backend/', $sUrl );
    },
    10, 1
);
```

The precise paths you select and replace will depend on the plugin's real path and the symlink path. You'll know what they are - I've just used the paths you provided in your bug report.

Note: the longer and more precise the paths you use in the `str_replace()` function, the less likely you'll interfere with any other generated URLs.

So I'd say that this isn't a _bug_, at least not one that YOURLS can fix.

**Comment by ozh** [comment]
dirname and filename in PHP don't follow symlink. A workaround could to check if a path is a link and use readlink in such a case, see https://stackoverflow.com/a/12580390/36850
But I fail at seeing how the system can guess a correct URL of a plugin if we're starting to mix paths and symlinked paths

**Comment by ozh** [comment]
Closing this, I think @paulgoodchild is right.
