### ISSUE TITLE
Support for optional 302 redirect instead of 301

### ISSUE THREAD

**Issue by iBug** [YOURLS/YOURLS#2544]
* [x] I've read the [guidelines for Contributing to YOURLS Projects](https://github.com/YOURLS/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing request
* [x] This is not a personal support request that should be posted on the [YOURLS Discourse](https://discourse.yourls.org/) community

**Summary**
Make it configurable in `config.php` to select whether redirects should be permanent (301) or ephemeral (302) by default.

**Motivation**
I'm using YOURLS as more a redirect site than a URL shortener, to better handle permalinks whose targets may change in the future (think it like `go.microsoft.com/fwLink` that pops up everywhere in Microsoft products). I noticed that browsers cache 301 redirects indefinitely, which could potentially make it pointless to change redirect targets, especially when I hand out "shortened" links to customers where I have absolutely no control of their browsers.

**Is your feature request related to a problem? Please describe.**
See the above paragraph.

**Describe the solution you'd like**
An option configurable in `config.php` whether redirects are 301 or 302, preferrably from environment variables as I'm deploying YOURLS in Docker containers.

**Describe alternatives you've considered**
I've patched my local deployment of YOURLS to make it generate 302 redirects all the time, but as is the intention of opening this FR, I'd like to see this feature actually implemented in the mainstream version of YOURLS so I don't have to patch the code again whenever I deploy a new Docker container.

**Additional context**
Nope.

**Comment by dgw** [comment]
Note that this is [Possible With A Plugin](https://github.com/YOURLS/YOURLS/wiki/Possible-With-A-Plugin), which someone else [already wrote](https://github.com/EpicPilgrim/302-instead/blob/master/plugin.php) (per https://github.com/YOURLS/YOURLS/issues/2188#issuecomment-274572157).

A prior PR implementing an environment variable as you described was declined: #2038

Our project still would rather leave features like this to the extensive plugin API, and keep the core code as basic as possible.

**Comment by philomory** [comment]
I know this issue has been closed, but I'd honestly argue that 302 redirects should be the default behavior, and 301 redirects relegated to a plugin. 301 redirects are inherently unsafe, because if you ever make a mistake it can never be corrected. They have their use cases, but 302 redirects are a better choice in most situations, especially for something like a URL shortener, I'd say.

**Comment by ozh** [comment]
[Opinions differ](https://searchengineland.com/analysis-which-url-shortening-service-should-you-use-17204). Hence the possibility to change default behavior with a plugin.
