### ISSUE TITLE
How to use with Composer?

### ISSUE THREAD

**Issue by Andrewsuares** [YOURLS/YOURLS#2547]
Hello,

How do I use this with composer? I've installed this in the vendor/ directory. How do I invoke the script in my framework? I'm using Codeigniter.

Thanks

**Comment by LeoColomb** [comment]
Thanks for your question. 
YOURLS is a full fledged application, thus a [composer project](https://getcomposer.org/doc/04-schema.md#type), not a library. It cannot be used as a dependency.
