### ISSUE TITLE
Borken link in http://yourls.org/#FAQ page (./readme.html)

### ISSUE THREAD

**Issue by christian-momon** [YOURLS/YOURLS#2550]
In page http://yourls.org/#FAQ: 
> Feedback, feature requests and bug reporting
> […]
>     Eventually raise a new issue. To do so, please read the **contribute guidelines**. Thanks!

The words **contribute guidelines** is a link to https://yourls.org/contribute which returns a "404 page not found" error message.

Fix required :smile:

**Comment by ozh** [comment]
Thanks, I've fixed it (you won't see a change using a browser that has cached the link redirection before, though)
