### ISSUE TITLE
Create Database - BEGINNER

### ISSUE THREAD

**Issue by sbbmaster** [YOURLS/YOURLS#2551]
Hi,

Would like to seek help. I am using Cloudways and I use Filezilla to upload the files.

I think I am missing is the database part.

I can't find any instructions to install or create the database.  Here are the following steps I have done.

1. Download the source zip file
2. edit the config.php file based from the database created in cloudways
3. upload the files to cloudways via filezilla

When I visited my domain.tips/admin, error us ERR_EMPTY_RESPONSE

I don't know what to do next. please help me. Thank you.

**Comment by ozh** [comment]
Hello
Steps 1, 2, 3 are fine. Now contact your host service and ask them how to create a database.
Also, you cannot out of the box install WP and YOURLS in the same directory, see http://yourls.org/#FAQ
