### ISSUE TITLE
Running tests locally

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#2553]
Hey there

Now that tests are all in the main repo, we should make sure someone running tests locally will not lose data. I mean, I for one just lost all data on my dev box just because I wanted to test tests :)

YOURLS-unit-tests used to mention:
- Create an empty MySQL database and user. **Do not use an exisiting database** or you will lose data, guaranteed.  
- Copy `yourls-tests-config-sample.php` to `yourls-tests-config.php`, edit it and include your database name, user and password.  

I think we should provide such a config file for tests, *and* some sort of checks to make sure the average ~~Ozh~~ Joe won't erase all their data. Thoughts?

**Comment by vitalyzhakov** [comment]
Hello!

May be we must use https://codeception.com/docs/modules/Db and docker-compose for this purpose?

**Comment by ozh** [comment]
Fixed with 5bc684a
