### ISSUE TITLE
https:// support in Social Sharing

### ISSUE THREAD

**Issue by Domainer** [YOURLS/YOURLS#2555]
* [x] I've read the [guidelines for Contributing to YOURLS Projects](https://github.com/YOURLS/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing request
* [x] This is not a personal support request that should be posted on the [YOURLS Discourse](https://discourse.yourls.org/) community

**Summary**
Please add https:// address support in the social sharing section.

**Motivation**
Nowadays no one will take a short URL seriously if encryption is not available.  If the address starts with http:// (without the s in following http), they will likely not try it because of all the craziness on the net.  When the connection is secured with encryption the user will feel more at ease as long as the padlock is green (or at least, not red). 

**Is your feature request related to a problem? Please describe.**
This is just a convenience issue, but I spend a lot of time promoting links through a number of means, including social media (but not Facebook, I have left that corporate spying fiasco) and use that facility for Twitter and Pinterest a lot.

**Describe the solution you'd like**
When visiting the admin panel in YOURLS, if I am on an https connection, change the http in the social sharing to https because obviously a TLS/SSL security certificate is available and functioning.

**Describe alternatives you've considered**
Otherwise I have to change it every single time, and I do enough editing as it is.  Every little thing helps.

**Additional context**
If short URL utilities are going to be taken seriously, they need to use encrypted connections.  Free security certificates are available through LetsEncrypt.com and Cloud Flare.  We do not want to be seen as spammers or worse, scammers, and having a working encrypted connection is a comfort to the user because there is a record of registration when the cert is up-to-date and functional.  Many web hosts (https://HDWebHosting.com) provide free encryption security certificates for each hosted domain and automate the whole thing right in the control panel (hosted domains).

And btw, THANK YOU for such an awesome tool!
![YOURLS-ShortURL](https://user-images.githubusercontent.com/403871/65861945-d0a73600-e332-11e9-97f7-f542cbedc98b.jpg)

**Comment by dgw** [comment]
I get `https://` links when I shorten in my own YOURLS instance, without having to edit them. Fixing this might be as simple as defining your `YOURLS_SITE` config value with `https://`.
