### ISSUE TITLE
Ability to remove "YOURLS -- Your own URL Shortener" Title.

### ISSUE THREAD

**Issue by Spacella** [YOURLS/YOURLS#2556]
* [x] I've read the [guidelines for Contributing to YOURLS Projects](https://github.com/YOURLS/.github/blob/master/CONTRIBUTING.md)
* [X] This request isn't a duplicate of an existing request
* [X] This is not a personal support request that should be posted on the [YOURLS Discourse](https://discourse.yourls.org/) community

**Summary**
In the <title> of every page, "YOURLS -- Your own URL Shortener" shows.

**Motivation**
You should be able to change this to anything you want so your page can be personalized.

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
A field in config.php to do this.

**Describe alternatives you've considered**
A setting in a config page.

**Comment by ozh** [comment]
YOURLS ships with a sample plugin that does exactly this. See the sample plugin and how it is made, and expand from there.

**Comment by Spacella** [comment]
But it does not take out the "YOURLS -- Your own URL Shortener." It only adds onto the end of the title.

**Comment by dgw** [comment]
> and expand from there.

This is the key phrase. @ozh isn't saying the sample plugin _already_ does exactly what you want, but it can be _adapted_ to do so.

**Comment by Spacella** [comment]
> > and expand from there.
> 
> This is the key phrase. @ozh isn't saying the sample plugin _already_ does exactly what you want, but it can be _adapted_ to do so.

But it doesn't show me how? I am very confused.

**Comment by dgw** [comment]
Here's the [relevant sample code](https://github.com/YOURLS/YOURLS/blob/fbba93d25a7e8a6364881f3c57dcaba37fbc9566/user/plugins/sample-plugin/plugin.php#L38-L60).

Line 40 says: ` * We're going to modify the <title> of pages in the admin area`

`yourls_add_filter( 'html_title', 'ozh_sample_change_title' );` tells YOURLS to run a function named `ozh_sample_change_title` when it's generating the `html_title`.

And this is the actual title-modifying logic:

```php
function ozh_sample_change_title( $value ) {
	$value = $value . ' -- the sample plugin is activated';
	return $value; // a filter *always* has to return a value
}
```

PHP has [string replace](https://www.php.net/manual/en/function.str-replace.php). Your title-changing function doesn't _have_ to _add_ text into the `$value`…

**Comment by Juliaria08** [comment]
> Here's the [relevant sample code](https://github.com/YOURLS/YOURLS/blob/fbba93d25a7e8a6364881f3c57dcaba37fbc9566/user/plugins/sample-plugin/plugin.php#L38-L60).
> 
> Line 40 says: ` * We're going to modify the <title> of pages in the admin area`
> 
> `yourls_add_filter( 'html_title', 'ozh_sample_change_title' );` tells YOURLS to run a function named `ozh_sample_change_title` when it's generating the `html_title`.
> 
> And this is the actual title-modifying logic:
> 
> ```
> function ozh_sample_change_title( $value ) {
> 	$value = $value . ' -- the sample plugin is activated';
> 	return $value; // a filter *always* has to return a value
> }
> ```
> 
> PHP has [string replace](https://www.php.net/manual/en/function.str-replace.php). Your title-changing function doesn't _have_ to _add_ text into the `$value`…

Setting `$value`, will just work...
I am preparing a plugin for that.
