### ISSUE TITLE
Multiple short URLs in one original URL

### ISSUE THREAD

**Issue by beloniki** [YOURLS/YOURLS#2560]
* [x] I've read the [guidelines for Contributing to YOURLS Projects](https://github.com/YOURLS/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing request
* [x] This is not a personal support request that should be posted on the [YOURLS Discourse](https://discourse.yourls.org/) community

**Summary**
Why there is no possibility to create more than one short URL in one original URL?

**Motivation**
The YOURLS helps to make some links shorter, for example, some URLs of Microsoft o365. But sometimes I forget, which short URL I've created: someurl or some-url, url-some, urlsome, and I have to go to admin panel to watch which URL is right. Possibility of making multiple short URLs in one original URL can prevent this problem and can get the flexibility of choice of short URL by the context in one original URL.

**Is your feature request related to a problem? Please describe.**
I think, that there will be no comfort to create different rows to one original URL to cover multiple short URLs.

**Describe the solution you'd like**
I'd like to get the possibility to add a short URL in a single original URL.

**Comment by dgw** [comment]
This already exists. See `YOURLS_UNIQUE_URLS` config constant. http://yourls.org/#Config

**Comment by beloniki** [comment]
I am afraid it's not working in a docker container.

root@95c2e85c92a4:/var/www/html# export
declare -x APACHE_CONFDIR="/etc/apache2"
declare -x APACHE_ENVVARS="/etc/apache2/envvars"
declare -x GPG_KEYS="1729F83938DA44E27BA0F4D3DBDB397470D12172 B1B44D8F021E4E2D6021E995DC9FF8D3EE5AF27F"
declare -x HOME="/root"
declare -x HOSTNAME="95c2e85c92a4"
declare -x OLDPWD
declare -x PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
declare -x PHPIZE_DEPS="autoconf                dpkg-dev                file            g++             gcc             libc-dev                make            pkg-config              re2c"
declare -x PHP_ASC_URL="https://www.php.net/get/php-7.2.23.tar.xz.asc/from/this/mirror"
declare -x PHP_CFLAGS="-fstack-protector-strong -fpic -fpie -O2"
declare -x PHP_CPPFLAGS="-fstack-protector-strong -fpic -fpie -O2"
declare -x PHP_EXTRA_BUILD_DEPS="apache2-dev"
declare -x PHP_EXTRA_CONFIGURE_ARGS="--with-apxs2 --disable-cgi"
declare -x PHP_INI_DIR="/usr/local/etc/php"
declare -x PHP_LDFLAGS="-Wl,-O1 -Wl,--hash-style=both -pie"
declare -x PHP_MD5=""
declare -x PHP_SHA256="74e045ec8ff26290db6a3688826dcdf43b87bc509e508e9cb76dab742804ca14"
declare -x PHP_URL="https://www.php.net/get/php-7.2.23.tar.xz/from/this/mirror"
declare -x PHP_VERSION="7.2.23"
declare -x PWD="/var/www/html"
declare -x SHLVL="1"
declare -x TERM="xterm"
declare -x YOURLS_DB_PASS="example"
declare -x YOURLS_PASS="admin"
declare -x YOURLS_SHA256="ffdf0f94b66cdbeaaa62bed3fde14d4eeb2bb1669c3c342eef369ce6165a0276"
declare -x YOURLS_SITE="http://yourls"
declare -x YOURLS_UNIQUE_URLS="false"
declare -x YOURLS_USER="admin"
declare -x YOURLS_VERSION="1.7.4"
root@95c2e85c92a4:/var/www/html#

**Comment by LeoColomb** [comment]
When running a docker container, you should (if not must) declare env variables at the docker level.

See the YOURLS guide for docker on the official image page: https://hub.docker.com/_/yourls

**Comment by beloniki** [comment]
This is my compose-file

```
version: '3.1'

networks:
  default:
    external:
      name: npm

services:

  yourls:
    image: yourls
    restart: always
    environment:
      YOURLS_DB_PASS: example
      YOURLS_SITE: http://yourls
      YOURLS_USER: admin
      YOURLS_PASS: admin
      YOURLS_UNIQUE_URLS: "false"

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

```
and this is an environment inside the container

```
...
declare -x YOURLS_DB_PASS="example"
declare -x YOURLS_PASS="admin"
...
declare -x YOURLS_SITE="http://yourls"
declare -x YOURLS_UNIQUE_URLS="false"
declare -x YOURLS_USER="admin"
declare -x YOURLS_VERSION="1.7.4"
```
And this feature does not work.

**Comment by LeoColomb** [comment]
Well, it works for me...

![image](https://user-images.githubusercontent.com/846943/66317675-43f40d80-e91a-11e9-846a-782043560008.png)

> and this is an environment inside the container

This will not work.

> This is my compose-file

Change the following

>     environment:
>       YOURLS_DB_PASS: example
>       YOURLS_SITE: http://yourls
>       YOURLS_USER: admin
>       YOURLS_PASS: admin
>       YOURLS_UNIQUE_URLS: "false"

to

    environment:
      YOURLS_DB_PASS: example
      YOURLS_SITE: http://yourls
      YOURLS_USER: admin
      YOURLS_PASS: admin
      YOURLS_UNIQUE_URLS: false

**Comment by beloniki** [comment]
If I change `"false"` to `false`, the reason is an error:
```
# docker-compose up -d
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.yourls.environment.YOURLS_UNIQUE_URLS contains false, which is an invalid type, it should be a string, number, or a null

```
So, it starts working. I found that "some_url" and "someurl" are the same. I think it was my mistake because I've tried to add them first.

Thanks for the quick responses! You are the best :)
