### ISSUE TITLE
Random ShortURLs error

### ISSUE THREAD

**Issue by garanda21** [YOURLS/YOURLS#2561]
Plugin Random ShortURLs has an error on its code, after activate it not working properly.

After review `plugin.php` code the filter assignation seems to be wrong, it says:

`yourls_add_filter( 'random_shorturl', 'ozh_random_shorturl' );`

After replacing to:

`yourls_add_filter( 'random_keyword', 'ozh_random_shorturl' ); `

Plugins works as expected.

**Comment by LeoColomb** [comment]
Thanks for opening this issue, @garanda21!

You're right. Could you open a pull request with this change?
Thanks! 👍

**Comment by ozh** [comment]
Thanks @garanda21

**Comment by dgw** [comment]
Lol, I must have messed up a global find-and-replace long ago when first migrating that plugin to core. Thanks!

**Comment by garanda21** [comment]
Glad to help!
