### ISSUE TITLE
Unable to edit or delete shortened URL's

### ISSUE THREAD

**Issue by seznie** [YOURLS/YOURLS#2563]
* [ ] I've read the [guidelines for Contributing to YOURLS Projects](https://github.com/YOURLS/.github/blob/master/CONTRIBUTING.md)
* [ ] This request isn't a duplicate of an existing issue
* [ ] I've read the [docs](https://yourls.org/) and followed them (if applicable)
* [ ] This is not a personal support request that should be posted on the [YOURLS Discourse](https://discourse.yourls.org/) community

**Describe the bug**
**Unable to edit or delete a link. After creating a shortened URL: when I click the "edit" icon next to it, nothing happens and when I click the "delete" icon, a pop-up window asks if I'm sure I want to delete it, I click OK, but then nothing happens and it doesn't get deleted.**

**To Reproduce**

**Expected behavior**

**Actual behavior**
What actually happens.

**Screenshots**

**Versions**
You can get this information from referencing `CHANGELOG.md` or the releases page.
Also, please include:
* The OS and what version of the OS you're running.
* Plugins or extensions activated if applicable.

**Additional context**
Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by dgw** [comment]
I'd bet this is a browser and/or server configuration problem. IF editing and deleting URLs was actually broken in YOURLS itself, we'd have a LOT more issues about it. Those are basic core features.

**Comment by seznie** [comment]
Hi,

I’ve tried it on Chrome, Firefox and Internet Explorer with the same result. Do you have any suggestions of what I could change re server configuration?

Thanks,
Sez

**Comment by dgw** [comment]
Gotta check server and/or browser console logs for errors. Basically, [start troubleshooting](https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps).

**Comment by particthistle** [comment]
I've been having a possibly related problem, but only with Firefox. When I go to add a new URL the button starts spinning, but nothing happens. Similarly when I go to edit a URL the icons just start spinning and there's no action.

Following @dgw tip of checking browser console, this error appears:
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://<yourls domain>/admin/admin-ajax.php?action=add&url=<url>&keyword=<keyword>&nonce=<nonce id>. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).`

Reading: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin

I added this to the .htaccess file for my site:
`Header set Access-Control-Allow-Origin '*'`

That's then gotten rid of the CORS error message, but not the problem in firefox.

_Posting also in Discourse_

**Comment by ozh** [comment]
@particthistle do you have something funky in your setup, like YOURLS installed on yourdomain.com and used from sho.rt or something? What you're describing never happens on a "normal" install (otherwise there would have been thousands of issues filed over the years)

**Comment by orm-it-oreillymedia** [comment]
I run two Yourls servers behind haproxy load balancers, and I saw this same behavior until I configured stickiness on the load balancers. Might this be your issue?

**Comment by cjstone** [comment]
I run two Yourls servers behind a pair of Haproxy load balancers. I saw this same behavior until I configured stickiness on the LBs. Could this be your issue?

**Comment by particthistle** [comment]
Thanks for the ideas on things to look at @ozh and @seznie 

Closer inspection was that I'd been accessing admin from www.sho.rt instead of sho.rt in Firefox, which then broke admin.

Added some redirection into htaccess to make www go to non-www to fix it permanently going forward. All good now.

(see https://www.siteground.com/kb/how_to_redirect_www_urls_to_nonwww/ for an example of the htaccess code)
