### ISSUE TITLE
HTTP ERROR 500 when clicking on install.

### ISSUE THREAD

**Issue by mnjg123** [YOURLS/YOURLS#2564]
I have installed yourls on my Ubuntu Server with LEMP Stack, and configured the config file. When i go on the webpage and click the "install button" i get a HTTP ERROR 500.

1. Configure yourls on Ubuntu 18.04 with LEMP Stack
2. Try to install yourls on domain/admin/install.php

**Expected behavior**
It should start some kind of setup.

**Actual behavior**
I get a HTTP ERROR 500

**Screenshots**

 [Video](https://youtu.be/FgkpetUIAlI)

**Versions**
yourls 1.7.4
ubuntu 18.04
mariadb 15.4
nginx 1.14.0 (ubuntu)
php7.2

output in error.log:

`PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes in /srv/YOURLS/includes/vendor/aura/s$
Stack trace:
#0 /srv/YOURLS/includes/vendor/aura/sql/src/ExtendedPdo.php(748): PDOStatement->execute()
#1 /srv/YOURLS/includes/functions-install.php(252): Aura\Sql\ExtendedPdo->perform('CREATE TABLE IF...')
#2 /srv/YOURLS/admin/install.php(46): yourls_create_sql_tables()
#3 {main}
  thrown in /srv/YOURLS/includes/vendor/aura/sql/src/ExtendedPdo.php on line 748" while reading response header from upstream, client: IP, server: DOMAIN, request: "POST /admin/install.php? HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "DOMAIN", referrer: "http://DOMAIN/admin/install.php"

`

**Comment by dgw** [comment]
[Duplicate](https://github.com/YOURLS/YOURLS/search?q=Syntax+error+or+access+violation%3A+1071+Specified+key+was+too+long%3B+max+key+length+is+767+bytes+is%3Aissue&type=Issues) of #767, #1071, #2350, #2394, #2431. Workaround details in #2115.
