### ISSUE TITLE
Evernote internal Link

### ISSUE THREAD

**Issue by mike14-2** [YOURLS/YOURLS#2565]
Hey,

i want to short a Evernote Programm Link (Internal Link) like this:
"evernote:///view/98148125/s554/7687431d-5440-40fe-a1f6-0a4d6a4fd42b/7687431d-5440-40fe-a1f6-0asd6a473d42b/"

But it is not possible. In other url-Shortener like tiny... it works.

what do i have to do, that it works on my own plattform of yourls?

thanks

**Comment by dgw** [comment]
Start here and customize: https://github.com/YOURLS/custom-protocol

**Comment by mike14-2** [comment]
thanks a lot. works great
