### ISSUE TITLE
White Blank page on Login Success

### ISSUE THREAD

**Issue by pandeyarun022** [YOURLS/YOURLS#2568]
I am encountering white blank on successful login, instead of seeing the admin page. On refresh, the admin page is visible.

**Comment by ozh** [comment]
Enable debug mode, see https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps

**Comment by pandeyarun022** [comment]
Custom Protocols plugin resulted in such a situation. Any further corrections.

**Comment by ozh** [comment]
Not enough info, dude
