### ISSUE TITLE
Will random-keywords still supported?

### ISSUE THREAD

**Issue by pgi-jsanchez** [YOURLS/YOURLS#2569]
Greetings.

Right now, my doubt it's about this project that I currently use and right now it's archived.
https://github.com/YOURLS/random-keywords

Will stil get some support by the community or there is another project that solves this feature?

Thanks.

**Comment by dgw** [comment]
Random keywords became a core plugin (see #1877), which will be included with YOURLS itself in the future.

**Comment by pgi-jsanchez** [comment]
I did a fresh install using a docker container and even run it manually using 

docker run -it yourls:1.7.4 bash

It's a current bug?

**Comment by dgw** [comment]
No. A version of YOURLS with the core version of the plugin hasn't been released yet. The relevant changes (c5a65b79742a9e24c140b9834120ea447d5135dd) exist only in the `master` branch for now.
