### ISSUE TITLE
Redirect 404

### ISSUE THREAD

**Issue by MrTiptop** [YOURLS/YOURLS#2571]
Hello, Is there a way to automatically redirect you to "admin page" or a page where you create short links if the short link does not exist?

**Comment by LeoColomb** [comment]
Please have a look at the plugin list: https://github.com/YOURLS/awesome-yourls
For example you can use https://github.com/8thwall/keyword-not-found-set-field-yourls

**Comment by MrTiptop** [comment]
Perfect! works like a charm!
