### ISSUE TITLE
Unable to delete shortened URL's

### ISSUE THREAD

**Issue by sudo00** [YOURLS/YOURLS#2572]
* [ ] I've read the [guidelines for Contributing to YOURLS Projects](https://github.com/YOURLS/.github/blob/master/CONTRIBUTING.md)
* [ ] This request isn't a duplicate of an existing issue
* [ ] I've read the [docs](https://yourls.org/) and followed them (if applicable)
* [ ] This is not a personal support request that should be posted on the [YOURLS Discourse](https://discourse.yourls.org/) community

**Describe the bug**
We have cron executing https://domain.com/yourls-api.php?signature=&format=simple&action=prune&scope=expired that cannot be executed until an error occurs.
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 4096 bytes) in /var/www/html/includes/vendor/aura/sql/src/ExtendedPdo.php on line 748
The cause for this may be a large number of records.

**To Reproduce**
1. Go to https://domain.com/yourls-api.php?signature=&format=simple&action=prune&scope=expired
2. See error

**Expected behavior**
It will remove old links and execute without errors

**Actual behavior**
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 4096 bytes) in /var/www/html/includes/vendor/aura/sql/src/ExtendedPdo.php on line 748

**Comment by dgw** [comment]
YOURLS doesn't define any "prune" action, nor does it support expiring links. [This plugin](https://github.com/joshp23/YOURLS-Expiry) does, though. Please take this issue to the [YOURLS Discourse forum](https://discourse.yourls.org/) for help and advice from other users, or take it to the plugin's issue tracker if you think it's a bug with the plugin and not your server setup.
