### ISSUE TITLE
Remove includes/vendor form the repository

### ISSUE THREAD

**Issue by Jelle-S** [YOURLS/YOURLS#2573]
* [x] I've read the [guidelines for Contributing to YOURLS Projects](https://github.com/YOURLS/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing request
* [x] This is not a personal support request that should be posted on the [YOURLS Discourse](https://discourse.yourls.org/) community

**Summary**
Convention for composer projects is to not commit the `vendor` directory to your repository.

**Motivation**
Dependency versions are locked in place by `composer.lock`, removing the `includes/vendor` directory from the repository and adding it to `.gitignore` prevents massive diffs when updating dependencies.

**Is your feature request related to a problem? Please describe.**
Not really a problem, just a convention.

**Describe the solution you'd like**
As described above, remove `includes/vendor` from the repository and add it to `.gitignore`.

**Describe alternatives you've considered**
Keep it in the repository =)

**Additional context**
https://getcomposer.org/doc/faqs/should-i-commit-the-dependencies-in-my-vendor-directory.md

**Comment by ozh** [comment]
"The best practice is to then have all the developers use Composer to install the dependencies"

The thing is, YOURLS isn't used by developers, mostly. Most people download the zip, upload to their server the thing via FTP and expect it to run. YOURLS isn't a library for devs, it's a standalone app for users.

**Comment by Jelle-S** [comment]
Yes, but non-developers aren't going to clone the repository either. They're going to download the attachments added to the releases, they can still contain the vendor directory.

**Comment by LeoColomb** [comment]
@Jelle-S You're totally right.  
But our current way to release YOURLS require we keep vendor directory. This is non standard, right, neither most efficient usage of composer, right again. We may remove it in the future, probably at the next major release.

**Comment by Jelle-S** [comment]
Alright, thanks for the update
