### ISSUE TITLE
Display already generated shorturl if the long url is shortened recently

### ISSUE THREAD

**Issue by Sidgut** [YOURLS/YOURLS#2577]
This feature should be included in the default version of Yourls, I had tried searching for the plugin as well but could not find any plugin in regards to the same.

Will appreciate if someone can comment it this feature makes sense.

This feature will help avoiding spam and minimize the database, infact bit.ly is also using the same implementation, let me know if anyone finds any plugin around this feature.

**Comment by ozh** [comment]
I think that's just how it has worked out of the box since the very beginning (or I don't understand the question)
