### ISSUE TITLE
Redirect the old http urls traffic to https?

### ISSUE THREAD

**Issue by IMExperts** [YOURLS/YOURLS#2578]
Hi, I’ve created the cert in my cPanel, and in config changed the site_value to https and it has converted all the old http shortened links to HTTPS in yourls admin panel. But how can I redirect the old http links traffic to HTTPS? I think this option should be included in the default release.

Thanks

**Comment by dgw** [comment]
[Make your webserver do it](https://www.poftut.com/how-to-redirect-http-to-https-in-apache-nginx/). (Plenty of similar tutorials available for whatever HTTP server you're using if you do a quick web search.)

**Comment by IMExperts** [comment]
> 
> 
> [Make your webserver do it](https://www.poftut.com/how-to-redirect-http-to-https-in-apache-nginx/). (Plenty of similar tutorials available for whatever HTTP server you're using if you do a quick web search.)

This is what .htaccess looks like
```
# BEGIN YOURLS
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^.*$ /yourls-loader.php [L]
</IfModule>
# END YOURLS


<Files 403.shtml>
order allow,deny
allow from all
</Files>
```

I've tried adding this line but it doesn't work.
RewriteRule ^.*$ https://domain.net/yourls-loader.php [L]

**Comment by IMExperts** [comment]
RESOLVED:

# BEGIN YOURLS
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteCond %{HTTPS}  !=on              **//Added this line**
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^.*$ /yourls-loader.php [L]
</IfModule>
# END YOURLS


<Files 403.shtml>
order allow,deny
allow from all
</Files>

**Comment by IMExperts** [comment]
No man, I'm getting 404 No Found error on https links. Could you send the solid solution for this?

**Comment by mgilank** [comment]
we have this issue too
https access got not found
http access working fine

**Comment by ozh** [comment]
@IMExperts @mgilank : server conf issue, not YOURLS ...

**Comment by ichandler** [comment]
This works for us:
`# BEGIN YOURLS
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteRule \.htpasswd$ - [F,L]
RewriteCond %{HTTPS} off
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^.*$ /yourls-loader.php [L]
</IfModule>
# END YOURLS`

**Comment by andrewgl504** [comment]
> This works for us:
> ![image](https://user-images.githubusercontent.com/7467951/71560685-275c0300-2a3b-11ea-8e33-266586709f96.png)
> (stupid PASTE CODE does not work right, sorry)

This fixed the same issue for me. Thank you!

**Comment by ichandler** [comment]
```
<Files ".htaccess">
Order Allow,Deny
Deny from all
</Files>

##AuthUserFile "/home/cur6co/public_html/.htpasswd"
##AuthName "Restricted"
##AuthType Basic
##require valid-user

# BEGIN YOURLS
<IfModule mod_rewrite.c>
RewriteEngine On
##RewriteRule \.htpasswd$ - [F,L]

RewriteCond %{HTTPS} off
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^.*$ /yourls-loader.php [L]
</IfModule>
# END YOURLS
```
Pastable now...

**Comment by theMelMills** [comment]
Hi all, I've searched all over for this and I really need help. I've tried this above and similar solutions to no avail. My https links are forwarding correctly but my HTTP ones are not and just default to the catch all address. http://melm.co/scholars/?nocache=1 (doesn't work) https://melm.co/scholars/?nocache=1 (works). Any ideas?

**Comment by ichandler** [comment]
theMelMills, why is this commented out?
`# RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]`
Without testing it myself, I think it needs to be there...

**Comment by theMelMills** [comment]
> theMelMills, why is this commented out?
> `# RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]`
> Without testing it myself, I think it needs to be there...

It was commented out for troubleshooting as it had no effect. It's back in now and still same result.

`# BEGIN YOURLS
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_URI} !^/\.well-known/acme-challenge/[0-9a-zA-Z_-]+$
RewriteCond %{REQUEST_URI} !^/\.well-known/cpanel-dcv/[0-9a-zA-Z_-]+$
RewriteCond %{REQUEST_URI} !^/\.well-known/pki-validation/[A-F0-9]{32}\.txt(?:\ Comodo\ DCV)?$
RewriteCond %{REQUEST_URI} !^/\.well-known/pki-validation/(?:\ Ballot169)?
RewriteRule ^.*$ /yourls-loader.php [L]
RewriteCond %{HTTPS} off
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
</IfModule>
# END YOURLS
<IfModule mod_rewrite.c>
RewriteCond %{HTTP_HOST} ^melm.co$
RewriteCond %{REQUEST_URI} !^/\.well-known/acme-challenge/[0-9a-zA-Z_-]+$
RewriteCond %{REQUEST_URI} !^/\.well-known/cpanel-dcv/[0-9a-zA-Z_-]+$
RewriteCond %{REQUEST_URI} !^/\.well-known/pki-validation/[A-F0-9]{32}\.txt(?:\ Comodo\ DCV)?$
RewriteCond %{REQUEST_URI} !^/\.well-known/pki-validation/(?:\ Ballot169)?
RewriteRule ^/?$ https://themelmills.com [R=301,L]
</IfModule>`

**Comment by joshp23** [comment]
[YOURLS-doTLS](https://github.com/joshp23/YOURLS-doTLS)

**Comment by palijn** [comment]
I know this thread is old, but **for reference, here is the only solution that finally worked** for me.
It uses, verbatim, the code from [https://cwiki.apache.org/confluence/display/httpd/RewriteHTTPToHTTPS](https://cwiki.apache.org/confluence/display/httpd/RewriteHTTPToHTTPS) 
Which means :

```
# BEGIN YOURLS
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /

# Redirect HTTP to HTTPS - code from https://cwiki.apache.org/confluence/display/httpd/RewriteHTTPToHTTPS
RewriteCond %{HTTPS} !=on
# This checks to make sure the connection is not already HTTPS
RewriteRule ^/?(.*) https://%{SERVER_NAME}/$1 [R,L]
# This rule will redirect users from their original location, to the same location but using HTTPS.
# i.e.  http://www.example.com/foo/ to https://www.example.com/foo/
# The leading slash is made optional so that this will work either in httpd.conf
# or .htaccess context

# YOURLS rewrites
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^.*$ /yourls-loader.php [L]
RewriteRule "(^|/)\.(?!well-known\/)" - [F]
</IfModule>
# END YOURLS

```

I guess the trick resides in "The leading slash is made optional".

**Comment by LukasMueller187** [comment]
The line `RewriteCond %{HTTPS} !=on` as stated in the doc https://yourls.org/docs/guide/server-configuration#redirect-everything-from-http-to-https broke my config (for subdirectory usage of yourls).

I wasted a couple of hours until I figured out it was due to this line. Quite frustrating, you can't expect everyone to be an apache expert, maybe disclaim the line.

**Comment by davidgs** [comment]
I have tried every permutation of the `.htaccess` file listed here and none of them work.  I am still getting the 404 whenever I try to go to any shortened link.

**Comment by RichieviIlainj** [comment]
Capitolism, Controlism
