### ISSUE TITLE
composer 1.9.1 failed installation (it should not contain uppercase characters)

### ISSUE THREAD

**Issue by gwijayas** [YOURLS/YOURLS#2579]
php: 7.3
composer: 1.9.1

This is new installation. When running command `composer install`, got these messages:
```
Deprecation warning: require.rmccue/Requests is invalid, it should not contain uppercase characters
Please use rmccue/requests instead. Make sure you fix this as Composer 2.0 will error
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
```

Changing `rmccue/Requests` to `rmccue/requests` will make composer.phar successfully install the depedency software

**Comment by LeoColomb** [comment]
Thanks for opening this issue @gwijayas.

That said, where is the failure? I see a warning, but the installation is a success.
Regarding the warning, #2557 fixed it.

**Comment by gwijayas** [comment]
The installation will not success. The `rmccue/requests`, `pomo/pomo` etc, will not downloaded. But after I changing the rmccue/requests, there wull be batch processing, downloading the requirement
