### ISSUE TITLE
YOURLS: 404 and directory issues

### ISSUE THREAD

**Issue by bigsmile01** [YOURLS/YOURLS#2580]
My main domain is ***smile.ws***
I have installed yourls in ***smile.ws/yourls***.

As a result, all my shortened urls are ***smile.ws/yourls/link*** instead of ***smile.ws/link***

I followed the [wiki instructions](https://github.com/YOURLS/YOURLS/wiki/.htaccess?PHPSESSID=a7d7b62fceaae22a2d9b908fdaaf9b5d) but that didn’t help.

I looked around and found a plugin called "[Swap Short Url][1]" which is supposed to help in these situations. It has slightly different .htaccess recommendation. I followed the instructions correctly and it works, because now the urls are ***smile.ws/link***. But when you click on them, you get a 404 error.

How can I fix this? Thanks!

<hr>
<hr>
PS I know that I should post this on [Yourls discouse](https://discourse.yourls.org/), but that website doesn't let me sign up for an account or post any messages. Everyone else seems to be posing issues here, so I guess this must be the place to post? 

  [1]: https://github.com/gerbz/Yourls-Swap-Short-Url
  [2]: https://stackoverflow.com/questions/tagged/yourls

**Comment by ozh** [comment]
Hello,

"I have installed yourls in smile.ws/yourls. As a result, all my shortened urls are smile.ws/yourls/link" : normal behavior.

Problem with specific plugin: please see with plugin author

**Comment by bigsmile01** [comment]
> Problem with specific plugin: please see with plugin author

Is there anyway to get this set up working without a plugin? Thanks!

**Comment by ozh** [comment]
YOURLS out of the box works from the directory it's installed in.

There are multiple ways to achieve what you want: server config tweak (for instance on apache with rewrite rules), a plugin (there may be several) or other tricks. 

So, without a plugin: yes, possibly, but it depends on your config and is very specific with your setup, so we cannot provide a generic trick. Hence the plugins.

**Comment by bigsmile01** [comment]
@ozh Thanks for your help. Do you know of any plugins that can do this other than "Swap Short Url". I've searched around but not found anything. The problem with "Swap Short Url" is that it's not very well supported. There are people who have raised issues similar to mine from June and have not had any replies. Thanks in advance for any help you can offer.

**Comment by ozh** [comment]
@bigsmile01 all I know is either from [YOURLS/awesome-yourls](https://github.com/YOURLS/awesome-yourls) or Google :)
