### ISSUE TITLE
Multiple admin accounts

### ISSUE THREAD

**Issue by Githog** [YOURLS/YOURLS#2582]
It'll be nice if YOURLS could support multiple admin accounts, especially for orgs with different departments. Or if there's a plugin for this, or a way to develop one, please kindly help point me in the right direction. 

Thank you

* [x] I've read the [guidelines for Contributing to YOURLS Projects](https://github.com/YOURLS/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing request
* [x] This is not a personal support request that should be posted on the [YOURLS Discourse](https://discourse.yourls.org/) community

**Summary**
One paragraph explanation of the feature.

**Motivation**
Why are we doing this? What use cases does it support? What is the expected outcome?

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dgw** [comment]
I don't understand what you're requesting. The config file already supports multiple username/password pairs.

**Comment by Githog** [comment]
Could you please point me to a documentation on how to pull that off?

**Comment by Githog** [comment]
Thank you

**Comment by dgw** [comment]
Sounds like you found the solution, but in case not:

https://github.com/YOURLS/YOURLS/blob/792f2e56916a5d089bf89228f9914ae741faa26c/user/config-sample.php#L59-L66

**Comment by ozh** [comment]
Also the wiki : https://github.com/YOURLS/YOURLS/wiki/Username-Passwords

**Comment by Githog** [comment]
Got it sorted...thanks again :)
