### ISSUE TITLE
Valid credentials but index loop

### ISSUE THREAD

**Issue by ikyamoet** [YOURLS/YOURLS#2583]
Hi, I use Yourls all the time but since yesterday my backend is impossible to reach..

I was in 1.7.3 so I've updated to 1.7.4, reset the admin password, changed to MD5 hash, but nothing worked.

Credentials are good since I don't have the "Invalid username or password" alert but each attempt to login acts like a refresh.

Best regards
simon

**Comment by ozh** [comment]
We'll need more info to might be able to help, like browser console or server logs. Check https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps

**Comment by ikyamoet** [comment]
Hi everyone,
 
For those who may have that issue someday, it was due to the activation of varnish..
When I removed extreme cache (cpanel), everything worked as it should :)

Regards
