### ISSUE TITLE
404 on Fresh Install

### ISSUE THREAD

**Issue by Torngate** [YOURLS/YOURLS#2586]
* [X] I've read the [guidelines for Contributing to YOURLS Projects](https://github.com/YOURLS/.github/blob/master/CONTRIBUTING.md)
* [] This request isn't a duplicate of an existing issue
* [X] I've read the [docs](https://yourls.org/) and followed them (if applicable)
* [X] This is not a personal support request that should be posted on the [YOURLS Discourse](https://discourse.yourls.org/) community

**Describe the bug**
Upon installing YOURLs, all created shortlinks fail with a 404.

**To Reproduce**
1. Install YOURLs, with complete successful install (No Debug errors or install errors)
2. Open Admin toolbar
3. Select one of the three preloaded shortlinks, or a new created shortlink
4. Open URL in new tab
5. URL 404s.

**Expected behavior**
URL links to the indicated link.

**Actual behavior**
URL Link fails with a 404 Not Found error.

**Screenshots**
Admin Dashboard with Links: https://i.imgur.com/6hB1xSL.png
404 Error Given: https://i.imgur.com/i47mwM0.png

**Versions**
* OS: Ubuntu 18.04.3 LTS
* Browser: FireFox 70.0.1
* Web Server: Apache2
* PHP Version: 7.2.24
* MySQL Version: 14.14
* YOURLs version: 1.7.4

**Additional context**
I know this error has been discussed before, however, I'm almost certain that I've tried everything suggested. Read through open and closed issues on the topic.

Attached files:
.htaccess: [htaccess.txt](https://github.com/YOURLS/YOURLS/files/3929268/htaccess.txt)
Web Conf File: [default-ssl.txt](https://github.com/YOURLS/YOURLS/files/3929275/default-ssl.txt)
Relevant access.log entires: [access.log](https://github.com/YOURLS/YOURLS/files/3929264/access.log)
Relevant error.log entries: None.
Config.php: [config.txt](https://github.com/YOURLS/YOURLS/files/3929280/config.txt)

Also of note, the site is enabled on CloudFlare. I don't think this should do anything but, hey. Info is Info. All files in the /var/www/hsshort directory is owned by www-data, recursively. The YOURLs instance is hosted on the same machine as two other sites, but the YOURLs directory/area is in it's own section.

**Comment by dgw** [comment]
This most certainly _is_ a personal support question that should have been posted on the YOURLS Discourse community, but I'll have a go anyway.

I assume you've copied [the `.htaccess` from our wiki](https://github.com/YOURLS/YOURLS/wiki/.htaccess).

  * Did you use the correct example? (root vs. sub-directory installation)
  * Are you sure your server has mod_rewrite available?

At the moment I can't think of other possible causes, but I know that this can't be a YOURLS bug. There would be thousands of reports by now if it really didn't work.

**Comment by Torngate** [comment]
Apologies for the wrong place, I simply went off of the previous types of questions posted here and there. I'll close and move this to there, then. 

A) Yes, correct example used.
B) mod_rewrite is enabled.

Must not be a YOURLs bug, so closing and moving to personal support.

**Comment by dgw** [comment]
The Discourse site is pretty new, and it's going to be a long effort getting the more support-type questions that used to get lumped in here to be asked there instead. Not really your fault, as the history of this issue tracker is quite misleading. 😸

It's true, though, that just about every instance I've seen of a problem like this turns out to be a server configuration issue somewhere. I wish you a swift troubleshooting & resolution process!
