### ISSUE TITLE
AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught PDOException

### ISSUE THREAD

**Issue by juniorionut** [YOURLS/YOURLS#2587]
Hello,

When trying to insert into database some links that contain "special chars" we will receive the following error:

`[Mon Dec 09 10:46:53.766245 2019] [proxy_fcgi:error] [pid 10978:tid 140644810946304] [client 1.2.3.4:5555] [vhost xxx.yyyy] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\\xF0\\x9F\\x98\\x9A \\xC2...' for column 'title' at row 1 in /var/www/my_instance/includes/vendor/aura/sql/src/ExtendedPdo.php:748\nStack trace:\n#0 /var/www/my_instance/includes/vendor/aura/sql/src/ExtendedPdo.php(748): PDOStatement->execute()\n#1 /var/www/my_instance/includes/vendor/aura/sql/src/ExtendedPdo.php(306): Aura\\Sql\\ExtendedPdo->perform('INSERT INTO `yo...', Array)\n#2 /var/www/my/includes/functions.php(161): Aura\\Sql\\ExtendedPdo->fetchAffected('INSERT INTO `yo...', Array)\n#3 /var/www/my_instance/includes/functions.php(278): my_instance_insert_link_in_db('https://www.xxx...', 'xkb', '\\xF0\\x9F\\x98\\x9A \\xC2\\xB7 gorgeou...')\n#4 /var/www/my_instance/includes/functions-api.php(21): my_instance_add_new_link('https://www.xxx...', 'xkb', '\\xF0\\x9F\\x98\\x9A \\xC2\\xB7 gorgeou...')\n#5 /var/www/my_instance/includes/functions-plugins.php(150): my_instance_api_action_shorturl(false)\n#6 /var/www/...\n'
`

**Comment by juniorionut** [comment]
The problematic title: 
`.... Here’s my weekend undertaking 🥰 · first ... `

**Comment by ozh** [comment]
No specifics or details. Basic posting guidelines not followed. Cannot help.

**Comment by juniorionut** [comment]
@ozh i can' imagine what specifixs do yoy want - i have given the error from fpm plus the problematix title.

**Comment by ozh** [comment]
That's why there's a template to fill when you create an issue

**Comment by dgw** [comment]
With the small amount of information I've seen, my best speculation is some database encoding/settings issue that makes extended Unicode stuff like emoji not work.

**Comment by ozh** [comment]
Also depends on how link was inserted (API? interface? bookmarklet?) hence the "steps to reproduce it" in the template

**Comment by juniorionut** [comment]
@ozh i've seen now the template, I have no idea why that hasn't appeared when I first created the issue.
@dgw i don't think it's the charset, i've set the charset in database to `utf8`

And the insert is done through api calls.

**Comment by ozh** [comment]
Through API calls after the data has been properly encoded, right?

**Comment by juniorionut** [comment]
@ozh will verify, i am not sure about encoding, will verify my scripts but not all users might be able to do what you are telling me, maybe something should be done in core to prevent this "accidents".

**Comment by juniorionut** [comment]
Hello,

Sorry for the late reply. The problem is in fact "emoji" characters such as 🔥 - that thorough the error above.
