### ISSUE TITLE
Sending unsubscribe link with yourls

### ISSUE THREAD

**Issue by hosnas** [YOURLS/YOURLS#2588]
I wanted to add an unsubscribe link to my emails. And to make them short, I am using yourls. However I saw a strange thing. When I make the unsubscribe link short via api, yourls do a get request on that link, and  so the user would be unsubscribed by yourls. 
Is this intended behaviour?

**Comment by dgw** [comment]
> Is this intended behaviour?

Yes. https://github.com/YOURLS/YOURLS/blob/16db6245207b38d53e45927bb7f6ce1c736122ea/includes/functions.php#L236-L240

If you specify a title yourself when shortening the link, YOURLS won't request the page.
