### ISSUE TITLE
Support SQLite database

### ISSUE THREAD

**Issue by fxzxmicah** [YOURLS/YOURLS#2589]
In some low-intensity environments, SQLite is more suitable than mysql. I hope SQLite can be supported in the future, thank you.

**Comment by ozh** [comment]
Hello

For previous versions (till 1.7.2) you have https://github.com/ozh/yourls-sqlite

I think SQLite might be supported out of the box now, see https://github.com/YOURLS/YOURLS/blob/6228a2874e532002286e99ecb364efb4eaa573fb/includes/class-mysql.php#L33-L40
