### ISSUE TITLE
change /admin to /somethingelse

### ISSUE THREAD

**Issue by jmergy** [YOURLS/YOURLS#2592]
Getting more and more bot attacks on my private YOURLs and will test trying to change this directory and inhibit bot attacks against this. But, just wondering if the old 2013 and 2014 notes on this to add the config variable and change the functions.php setting works. I will test. If there is anyone else that has moved the admin location, please let me know any pitfalls on this. Thanks.

**Comment by jmergy** [comment]
Specifically #1137 - I'll try that but if there are better/newer ways to accomplish this, please let me know. Love YOURLs and have used it forever.

**Comment by LeoColomb** [comment]
Hello @jmergy, thanks for opening this ticket.

As you reported, #1611 is the perfect ticket to answer your question. This situation is left unchanged for now but will be enhanced in the future. 

Closing as duplicate.
