### ISSUE TITLE
Loop! I cannot do anything

### ISSUE THREAD

**Issue by francescogosce** [YOURLS/YOURLS#2594]
* [x] I've read the [guidelines for Contributing to YOURLS Projects](https://github.com/YOURLS/.github/blob/master/CONTRIBUTING.md)
* [X] This request isn't a duplicate of an existing issue
* [X] I've read the [docs](https://yourls.org/) and followed them (if applicable)
* [X] This is not a personal support request that should be posted on the [YOURLS Discourse](https://discourse.yourls.org/) community

**Describe the bug**
I changed my host provider from [NETSONS](https://www.netsons.com) to [Tophost](https://www.tophost.it). First I made a backup of all files, then I copied all file to the new host (including database). The problem is that I cannot shorten shorten any link o modify an existing one o try to delete an old shorten link, anything happens. Just a loop.

**Screenshots**
I've also tryed to install Yours on a new database, but the behavior is the same!

Screenshot » https://snipboard.io/rEqdXH.jpg

**Versions**
You can get this information from referencing `CHANGELOG.md` or the releases page.
Also, please include:
* I tryed on macOS Catalina with Safari and on my Google Pixel with Chrome.
* No plugins, just the 1.7.4 version installed on my host provider.

**Additional context**
I chanced host provider from Netsons to Tophost. I used a backup of all file (also database).

**Comment by ozh** [comment]
From the [wiki](https://github.com/YOURLS/YOURLS/wiki) :

* Troubleshooting first steps — Something broken? This is your first aid kit.
* Endless Spinning Icon — Cannot add or edit links? Read this.
