### ISSUE TITLE
You forgot to change /includes/version.php in the latest release!

### ISSUE THREAD

**Issue by FanyangMengDev** [YOURLS/YOURLS#2596]
Hi there,

First thank you for this perfect project.

After you released the 1.7.5, I upgrade immediately and I found that yourls still keeps alerting me that I am using 1.7.4 and need to upgrade.

Then I use VSCode to found that in the /includes/version.php, you forgot to change the version.

Please do not forgot to change that.

Thanks.

**Comment by dgw** [comment]
There's already a pull request that fixes it (#2595), so all that's left is for @ozh to decide whether to update the existing release or publish a new one with a different version number.

**Comment by ozh** [comment]
Argh ffs, I knew it's never good to do things in a rush, even trivial things sometimes ...

**Comment by ozh** [comment]
New release .... :-/

**Comment by FanyangMengDev** [comment]
@ozh LOL, just chill not a big problem : )
