### ISSUE TITLE
sitemap.xml

### ISSUE THREAD

**Issue by urlindexer** [YOURLS/YOURLS#2598]
**Summary**
Sitemap for Google Webmaster Tools

**Motivation**
to create a sitemap.xml to submit to google webmaster tools to index external urls

**Comment by dgw** [comment]
I don't understand the point of submitting short URLs to the Google index. It'll just follow the redirects and index the destination pages.

**Comment by urlindexer** [comment]
> I don't understand the point of submitting short URLs to the Google index. It'll just follow the redirects and index the destination pages.

yes, i want to google index the destination pages.. :)
it will work as url "backlink" indexer

**Comment by ozh** [comment]
This won't be an enhancement to YOURLS, that's a very specific need you want and mostly no one else wants.

You'll have to write a script similar to this : https://github.com/YOURLS/YOURLS/wiki/RSS.php

**Comment by rickvalladares** [comment]
I want to

**Comment by ozh** [comment]
https://github.com/YOURLS/YOURLS/wiki/Possible-With-A-Plugin
