### ISSUE TITLE
Plugins Deactivates at random

### ISSUE THREAD

**Issue by 3dgrafiker** [YOURLS/YOURLS#2599]
I've got an issue with plugins deactivating at random, without any user interferance. ( Can be hours, minutes or days before it gets disabled ) 
It seems to happen to any plugin that is installed by me (Right now I'm trying Sleeky Backend | 2.4.0) 
Random Backgrounds-plugin can however stay on forever. 

I therefore added the code from one plugin to the Random Background-plugin, wich worked for some time but later got deactivated just like the rest. 

Now on v 1.7.7 but also same on earlier versions. 
PHP 7.3 / Apache 2.4

I see issues reported 2013, but they seem to be closed without comments.

**Comment by ozh** [comment]
"I therefore added the code from one plugin to the Random Background-plugin"

What code? Where? How?

**Comment by 3dgrafiker** [comment]
Sorry I might have trouble explaining it. I'll give you an example:

Plugin that works "forever":
Random Background

Plugin that got disabled:
Joel’s Interstitial Plugin for YOURLs

So I tried adding all code from "Joel's Plugin" to the "Random Background" (so now it's 2 plugins in one, still called "Random Background") this causes the new  "Random Background" to get disabled after a while. 

And I can't understand what causes it. Seems to happen with almost any plugin that's not in the Yourls-master.

**Comment by LeoColomb** [comment]
Thanks for this report @3dgrafiker.
Did you report the issue on the plugin repo?
It mostly seems to be specific to this plugin, if the same code at other place has the same behavior.

**Comment by sathish1981** [comment]
> "I therefore added the code from one plugin to the Random Background-plugin"
> 
> What code? Where? How?

Hello @ozh ,
 The same issue happening for me. Any plugin outside of yourls master is getting deactivate after some time. I have opened a new issue for this though #2609

**Comment by 3dgrafiker** [comment]
> Thanks for this report @3dgrafiker.
> Did you report the issue on the plugin repo?
> It mostly seems to be specific to this plugin, if the same code at other place has the same behavior.

Hi, no it seems to be any plugin, or at least the ones I tried. I also see @sathish1981 have the same issue. And other users added the issue 2013. It is a weird one.

I don't know if there's any logging I can do to see what is happening?

**Comment by sathish1981** [comment]
> > Thanks for this report @3dgrafiker.
> > Did you report the issue on the plugin repo?
> > It mostly seems to be specific to this plugin, if the same code at other place has the same behavior.
> 
> Hi, no it seems to be any plugin, or at least the ones I tried. I also see @sathish1981 have the same issue. And other users added the issue 2013. It is a weird one.
> 
> I don't know if there's any logging I can do to see what is happening?

Hello @3dgrafiker - I see we both are using the same versions of yourls, apache and PHP. which platform OS version you are using?

**Comment by 3dgrafiker** [comment]
Now i'm a bit unsure on the exact OS for the webserver (nginx) but its some UNIX-version.
( It should be FreeBSD / OpenBSD if my provider has updated their information ) 

// Peter

**Comment by ozh** [comment]
Closing to keep discussion in one place. See 2609

**Comment by sathish1981** [comment]
@3dgrafiker - I threw a hint at #2609  may be it could help you.
