### ISSUE TITLE
nginx short url redirection

### ISSUE THREAD

**Issue by Tealk** [YOURLS/YOURLS#2601]
**Describe the bug**
When calling a short URL I only get a 404
https://anzah.co/yourlsblog

**Versions**
nginx/1.14.2
PHP 7.4.2

I use Froxlor and this is the vhost:

```
server {
	listen 185.170.112.156:443 ssl http2;
	server_name anzah.co www.anzah.co;
	ssl_protocols TLSv1.2 TLSv1.3;
	ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
	ssl_prefer_server_ciphers off;
	ssl_session_tickets on;
	ssl_session_cache shared:SSL:10m;
	ssl_certificate /etc/ssl/froxlor-custom/anzah.co.crt;
	ssl_certificate_key /etc/ssl/froxlor-custom/anzah.co.key;
	add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload";
	ssl_stapling on;
	ssl_stapling_verify on;
	ssl_trusted_certificate /etc/ssl/froxlor-custom/anzah.co.crt;
	include /etc/nginx/vhost.d/acme.conf;
	access_log /dev/null combined;
	error_log /var/customers/logs/Anzah-anzah.co-error.log error;
	root /var/customers/webs/Anzah/anzah.co/;
	location / {
		index index.php index.html index.htm;
		try_files $uri $uri/ @rewrites;
	}

	location @rewrites {
		rewrite ^ /index.php last;
	}

	location ~ ^(.+?\.php)(/.*)?$ {
		try_files /d7dae490272ef73cd62b77297c9eb429.htm @php;
	}

	location @php {
		try_files $1 =404;
		include /etc/nginx/fastcgi_params;
		fastcgi_split_path_info ^(.+?\.php)(/.*)$;
		fastcgi_param SCRIPT_FILENAME $request_filename;
		fastcgi_param PATH_INFO $2;
		fastcgi_param HTTPS on;
		fastcgi_pass unix:/var/lib/fastcgi/1-anzah-anzah.co-php-fpm.socket;
		fastcgi_index index.php;
	}

	include vhost.d/secure-header.conf;
	include vhost.d/security_file_access.conf;
	include bots.d/ddos.conf;
	include bots.d/blockbots.conf;
}
```

**Comment by Tealk** [comment]
Fixed with this code:
```
if (!-e $request_filename){ rewrite ^(.+)$ /yourls-loader.php?q=$1 last; }
```
https://github.com/YOURLS/YOURLS/issues/1715#issuecomment-326797015

**Comment by soldiweb** [comment]
Hi Tealk, how do you put this code? I have the same problem on Nginx, thanks!

**Comment by Tealk** [comment]
simply into the location / block

```
	location / {
		index index.php index.html index.htm;
		try_files $uri $uri/ @rewrites;
		if (!-e $request_filename) {
			rewrite ^(.+)$ /yourls-loader.php?q=$1 last;
		}
```

**Comment by LeoColomb** [comment]
Thanks for opening this issue, @Tealk.
Please have a look at the official documentation regarding Nginx config for YOURLS: https://github.com/YOURLS/YOURLS/wiki/Nginx-configuration

Also be very careful with `if` usage on Nginx config files, it is not really recommended: https://www.nginx.com/resources/wiki/start/topics/depth/ifisevil/

**Comment by Tealk** [comment]
Hallo @LeoColomb 
Unfortunately the official nginx configuration did not work for me.
`try_files $uri $uri/ /yourls-loader.php$is_args$args;` had no effect at all.

**Comment by LeoColomb** [comment]
What do you mean by "no effect"?
Is something logged?
Are you sure you are targeting the right PHP-FPM server upstream?
Is the YOURLS part in a good position in the configuration so that it is not overwritten?

**Comment by Tealk** [comment]
> What do you mean by "no effect"?

If I call a short url then I only get 404 and i find nohting in the log
>  Are you sure you are targeting the right PHP-FPM server upstream?

yes because the admin side just doesn't do the forwarding.
>  Is the YOURLS part in a good position in the configuration so that it is not overwritten?

i edited the config by hand so that it matches the template, this had no effect.

**Comment by LeoColomb** [comment]
Try removing these lines:

> ```php
> 	location ~ ^(.+?\.php)(/.*)?$ {
> 		try_files /d7dae490272ef73cd62b77297c9eb429.htm @php;
> 	}
> ```

**Comment by Tealk** [comment]
but the whole php-fpm is based on this
and i cant remove this, because it will be replaced by froxlor

**Comment by LeoColomb** [comment]
Then the only advice we can give is to check with your Froxlor provider.
Our configuration example is very common (same as the recommended one for WordPress behind Nginx, Laravel app behind Nginx, etc.), so it _should_ work.
Let me know if you get a better solution! 🙂

**Comment by Tealk** [comment]
> Then the only advice we can give is to check with your Froxlor provider.

This is myself, I use it as administration interface.
