### ISSUE TITLE
Very Slow Search with lots of data

### ISSUE THREAD

**Issue by stefan-kamsker** [YOURLS/YOURLS#2602]
Hi,

we have yourls (v 1.7.4) running with 3.2 million entries in the url table.
We are experiencing a very slow search.

for example the following query is running around 25-30 seconds.

`SELECT * FROM `url` WHERE 1=1  AND CONCAT_WS("",`keyword`,`url`,`title`,`ip`) LIKE ('%asdfasdfasdf%') ORDER BY `timestamp` desc LIMIT 0, 15; (26.32784 s)`

Has anyone an idea / tipps to get this faster? 
fe. better indexing or maybe a rewrite of the search logic is necessary.

Databases:
Mysql 8.0 or mariaDB 5.5.60

Thank you!

Best regards!

**Comment by LeoColomb** [comment]
Thanks for opening this issue, @stefan-kamsker.

> with 3.2 million entries in the url table

I'm sure you know that represent **a lot* of data.
My first advice would be to review entirely your MySQL configuration to tweak it as much as possible and improve data handling. 

Another suggestion would come with a profiling. Is it possible to generate PHP profiling report on your side?

**Comment by stefan-kamsker** [comment]
Thanks @LeoColomb 

it's clearly a mysql problem, not a php one. 

found out that increasing **innodb_buffer_pool_size**  is helping

also the text columns (url, title) seem to be slower than varchar
https://github.com/YOURLS/YOURLS/pull/2585
also changing this, helps a lot

BR

**Comment by ozh** [comment]
For the record : on my totally unoptimized test box (stock XAMPP mysql.ini completely untweaked) I don't notice anything slow after inserting 4.5 millions of records (running latest release, which wasn't the release you were using as of writing)

- Inserting a new link is not noticeable slower
- Displaying the admin page is as fast as usual
- Searching for a particular term takes a couple seconds longer, which I guess is expected (around 3.6 seconds)

```
Connected to database yourls_ozh on localhost 
SQL perform: SELECT option_name, option_value FROM yourls_options WHERE 1=1 (0.00040 s)
Check for new version: no
SQL perform: SELECT COUNT(keyword) as count, SUM(clicks) as sum FROM `yourls_url` WHERE 1=1  (1.01134 s)
SQL perform: SELECT COUNT(keyword) as count, SUM(clicks) as sum FROM `yourls_url` WHERE 1=1  AND CONCAT_WS('',`keyword`,`url`,`title`,`ip`) LIKE ('%dr%') (3.60477 s)
SQL perform: SELECT * FROM `yourls_url` WHERE 1=1  AND CONCAT_WS('',`keyword`,`url`,`title`,`ip`) LIKE ('%dr%') ORDER BY `timestamp` desc LIMIT 0, 15; (0.01439 s)
```

**Comment by badihi** [comment]
I currently have 16M records, and the following query takes more than 3 mins. So the admin page times out and it is not usable.
```SELECT COUNT(keyword) as count, SUM(clicks) as sum FROM `yourls_url` WHERE 1=1```

**Comment by badihi** [comment]
I have to change `WHERE 1=1` to `WHERE 1=0` as a workaround. but this is stupid. This issue must be addressed.
