### ISSUE TITLE
Redirect after authentication doesn't always work correctly

### ISSUE THREAD

**Issue by pcolmer** [YOURLS/YOURLS#2603]
* [X] I've read the [guidelines for Contributing to YOURLS Projects](https://github.com/YOURLS/.github/blob/master/CONTRIBUTING.md)
* [X] This request isn't a duplicate of an existing issue
* [X] I've read the [docs](https://yourls.org/) and followed them (if applicable)
* [X] This is not a personal support request that should be posted on the [YOURLS Discourse](https://discourse.yourls.org/) community

**Describe the bug**
When running yourls in a Docker container, the redirect that takes place after authentication doesn't always work. Sometimes (and I haven't been able to pin this down *precisely*), the redirect is to http://localhost/admin instead of the correct site URL.

As far as I can tell, this is the only place where the yourls code references `$_SERVER[SERVER_NAME]` rather than `YOURLS_SITE`. Making that code change fixes the problem.

**To Reproduce**
1. Configure docker-yourls to run with `YOURLS_SITE` set to "http://wibble:8002" and port mapping of `8002:80`.

2. Configure Apache to listen on port 8000 and reverse-proxy to http://localhost:8002. This is deliberate because:

    a) we need Apache to be proxying here and

    b) we need Apache to listen on a non-standard port to cause the reply redirection to show as incorrect.

3. Navigate to http://localhost:8000/admin/. Enter valid credentials.

**Expected behavior**
What should happen is that yourls should return a redirection header of http://wibble:8002/admin/.

**Actual behavior**
The redirection header is to http://localhost/admin/ instead. Note that there is no port number.

**Versions**
1.7.6 running inside the yourls Docker container. No extensions or plugins.

**Comment by LeoColomb** [comment]
Thanks for this report @pcolmer.
Very nice description, appreciated.

> where the yourls code references `$_SERVER[SERVER_NAME]` rather than `YOURLS_SITE`.

Indeed, but current situation solves many issues regarding domain management.
It's not ideal at all, but by using `$_SERVER[SERVER_NAME]` YOURLS is able to switch between different domain smothly.

@ozh Thoughts?

**Comment by pcolmer** [comment]
There is an alternative approach at https://github.com/YOURLS/YOURLS/pull/2545 but, for some reason, testing resulted in the browser loading a blank page until I re-requested the admin page. Reverting the change back to the one I'm suggesting didn't have that problem.

I can provide more insight/clarity around why using `YOURLS_SITE` can work if you want me to expand on that.

**Comment by ozh** [comment]
It seems anyway that using SERVER_NAME can cause some inconsistencies, judging by issues opened. I'm not sure why we're not simply using YOURLS_SITE instead of this complex $_SERVER['SERVER_NAME'] juggling that #2545 proposes

The only place it is used seems to be in functions-auth.php (if search is accurate here on Github)
The reason it is used here is to trigger a redirection to requested page
Maybe we're overthinking this and there is a simpler way to redirect to current page ?

**Comment by ozh** [comment]
In what case simply using `the server part of YOURLS_SITE` + $_SERVER['REQUEST_URI'] would not work?

YOURLS_SITE : `http://sho.rt/` or `https://sho.rt:1337/yourls/`
REQUEST_URI : `omg`, `admin/something.php`, `yourls/admin/` or `yourls/omg`

Must think about non basic standard cases (IIS, nging, docker, virtual hosting with multiple hosts on same server....)

**Comment by ozh** [comment]
@pcolmer could you test this please :

functions-auth.php, line 93, simply : 
yourls_redirect( yourls_sanitize_url_safe($_SERVER['REQUEST_URI']) );

Not sure why we hardcode the server root after all...

**Comment by ozh** [comment]
@pcolmer could you test with code in https://github.com/YOURLS/YOURLS/pull/2625 ?

**Comment by pcolmer** [comment]
Hi

The redirection after authentication works. Thank you.
