### ISSUE TITLE
nonce URLs are relative, not absolute - this affects proxying with a non-root path

### ISSUE THREAD

**Issue by pcolmer** [YOURLS/YOURLS#2605]
* [X] I've read the [guidelines for Contributing to YOURLS Projects](https://github.com/YOURLS/.github/blob/master/CONTRIBUTING.md)
* [X] This request isn't a duplicate of an existing issue
* [X] I've read the [docs](https://yourls.org/) and followed them (if applicable)
* [X] This is not a personal support request that should be posted on the [YOURLS Discourse](https://discourse.yourls.org/) community

**Describe the bug**
The URLs created by yourls_nonce_url are relative. They do not include the YOURLS_SITE value at the start. Normally, this would not be a problem but, if you are trying to proxy YOURLS with a non-root path, it is close to impossible to define the proxy rules correctly.

Changing the code to use absolute URLs greatly simplifies the proxy rules and does not affect normal usage.

**To Reproduce**
Configure Apache so that it proxies to docker-yourls with a non-root path, e.g.

```
ProxyPass /yourls/ http://localhost:8000/
ProxyPassReverse /yourls/ http://localhost:8000/
```

Now load admin/plugins.php and inspect the page source. The URLs for the actions are relative and so look like `/admin/plugins.php`. These will not work because all of the YOURLS URLs need to be proxied under /yourls/ in this example configuration.

**Expected behavior**
If YOURLS returned absolute URLs, `ProxyPass` and `ProxyPassReverse` would be to successfully rewrite the action URLs.

**Actual behavior**
The URLs are relative so the Apache path cannot get prepended. This breaks the interface.

**Versions**
1.7.6 in the Docker container.

**Comment by ozh** [comment]
Closing to keep discussion going in the PR
