### ISSUE TITLE
Use of HTTP_HOST prevents path proxying against Docker container

### ISSUE THREAD

**Issue by pcolmer** [YOURLS/YOURLS#2607]
* [X] I've read the [guidelines for Contributing to YOURLS Projects](https://github.com/YOURLS/.github/blob/master/CONTRIBUTING.md)
* [X] This request isn't a duplicate of an existing issue
* [X] I've read the [docs](https://yourls.org/) and followed them (if applicable)
* [X] This is not a personal support request that should be posted on the [YOURLS Discourse](https://discourse.yourls.org/) community

**Describe the bug**
`yours_get_request` uses `HTTP_HOST` to divine the full URL of the shortlink request but, if yourls is running in a Docker container **and** it is being proxied from a non-root path, that logic is faulty.

**To Reproduce**
1. Set up a yourls Docker container with YOURLS_SITE set to the "external" FQDN URL **including** the "/app" path (see step 2).
2. Configure Apache to proxy "/app" to the underlying YOURLS instance.
3. Try to retrieve a short link.

**Expected behavior**
The underlying full link associated with the short link is returned.

**Actual behavior**
YOURLS fails to return the link because the use of the Apache variables causes the path to be left in the request field, thereby failing to match the shortlink.

**Versions**
1.7.6 in a Docker container.

**Comment by ozh** [comment]
Closing to keep conversation in the referenced PR
