### ISSUE TITLE
Displaying blank page only in chrome

### ISSUE THREAD

**Issue by sathish1981** [YOURLS/YOURLS#2614]
* [ ] I've read the [guidelines for Contributing to YOURLS Projects](https://github.com/YOURLS/.github/blob/master/CONTRIBUTING.md)
* [ ] This request isn't a duplicate of an existing issue
* [ ] I've read the [docs](https://yourls.org/) and followed them (if applicable)
* [ ] This is not a personal support request that should be posted on the [YOURLS Discourse](https://discourse.yourls.org/) community

**Describe the bug**
After authentication in Yourls using chrome browser, a blank page is displayed. Even after many logouts and login, I an facing the same

**To Reproduce**
Use chrome to access Yourls site
Login with credentials
Displayed Blank screen. 
Even using the incognito browser facing the same issue.

**Expected behavior**
After authenticating users, admin interface should load.

**Actual behavior**
After authentication, blank page displayed. You have edit the address bar and remove the /admin to display the admin interface

**Versions**
Yourls 1.7.7, Apache 2.4, PHP 7

Plugins activated:
1. Allow Hyphens in Short URLs
2. Authorization Manager Plus 
3. Bulk Import and Shorten
4. Random ShortURLs
5. Sleeky UI
6. Share LinkedIn
7. Share on Tumbler

**Comment by ozh** [comment]
See https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps

Feel free to report further info here
