### ISSUE TITLE
Allow webcal URLs to add

### ISSUE THREAD

**Issue by theknigge** [YOURLS/YOURLS#2615]
Can you please add protocol support for webcal/webcals URLs?
Like: webcals://link-to-my-calendar.com
Currently it appears "Missing or malformed URL"

That would be greate. Thank you in advance!

**Comment by LeoColomb** [comment]
Thanks for opening this issue @theknigge.
You can use the related filter with a tiny plugin to add any protocol.

https://github.com/YOURLS/YOURLS/blob/6228a2874e532002286e99ecb364efb4eaa573fb/includes/functions-kses.php#L62

**Comment by ozh** [comment]
Specifically, see https://github.com/YOURLS/custom-protocol
