### ISSUE TITLE
Wrong redirection url with GET parameter containing encoded string

### ISSUE THREAD

**Issue by giaur500** [YOURLS/YOURLS#2618]
For example, souce url:
http://domain.com?url=encodedUrl

Yourls makes redirection to invalid url, not properly encoded. So it's useless, because it redirects to wrong url actually

**Comment by ozh** [comment]
Duplicate of a zillion issues.

**Comment by giaur500** [comment]
Ok, but I am unable to get rid of that issue. Any advice please?

**Comment by ozh** [comment]
For starters, a proper issue description.

**Comment by giaur500** [comment]
What's not clear in description?
