### ISSUE TITLE
Can you tell me how to get the OG to work?

### ISSUE THREAD

**Issue by clicksmartmedia** [YOURLS/YOURLS#2619]
Id like to have an image load when someone clicks on the YOURLS. Like you get on an iPhone when you use this - 

https://developer.apple.com/library/archive/technotes/tn2444/_index.html#//apple_ref/doc/uid/DTS40017677-CH1-TNTAG1

![image](https://user-images.githubusercontent.com/53594482/76568368-f56d1100-646d-11ea-824f-cc6a2c8d10f8.png)

I found thing plugin - https://github.com/matchett808/Yourls-OG-everywhere

But it does not work. 

Anyone have any idea on how to do this?

Thanks!

**Comment by dgw** [comment]
I think I know why that plugin doesn't work: It uses invalid characters in PHP identifiers.

Try with my tweaked fork, referenced in this pull request (that I have little hope will ever be merged): matchett808/Yourls-OG-everywhere#1

**Comment by dgw** [comment]
PHP identifiers aside, I realized upon looking at this again that it's basically the same question as #2203—and the answer is probably "This isn't possible". As stated in that discussion, YOURLS redirects don't output HTML, so there's nowhere for Open Graph tags to appear in the output.
