### ISSUE TITLE
Count click of shared links

### ISSUE THREAD

**Issue by juliocmartins** [YOURLS/YOURLS#2622]
In my test with, the links were shared by WhatsApp and SMS, and it was counted as click, even though it was only the preview render of the shared link.

How can this be avoided? I can see no difference in $_SERVER['HTTP_USER_AGENT'] from normal click and the preview render.

Tks

**Comment by ozh** [comment]
It depends on the client. Some apps follow the URL to generate the thumbnail, hence it's the same behavior from YOURLS point of view as a "click"

**Comment by juliocmartins** [comment]
No way to avoid this? The check statistics is wrong, and need the right count of clicks.

**Comment by ozh** [comment]
It depends on your use case. For instance if you share all links via Whatsapp and SMS, you could make a plugin that simply doesn't count the first 2 hits.
