### ISSUE TITLE
Doc Suggestion: Simplify Upgrade

### ISSUE THREAD

**Issue by johnaweiss** [YOURLS/YOURLS#2630]
Hi, just a suggestion for the upgrade instructions here:
https://yourls.org/#Install

As far as i can tell, Steps 4 and 5 are unnecessary. 

Step 4) Overwriting the exiting install doesn't touch the config.php (in my FTP client, at least, WinSCP), so it doesn't need to be restored. Also, you don't give a step to back it up, so if restoring the config is required, then you should add a step to back it up before upgrading. 

Step 5) This isn't part of the upgrade, it is just a "make sure it worked" step, and could be labelled as such, or just eliminated. 

thx!

**Comment by ozh** [comment]
Indeed, these instruction refer to ancient versions when user config was initially found in `includes/`. I'll simplify.

**Comment by stevecohenfr** [comment]
To upgrade I just connected the git and type 
```
git fetch --all --tags
git checkout tags/<version>
```
And I'm up to date :)

**Comment by ozh** [comment]
```shell
$ git describe --tags
1.7.6-18-gba459cb5
$ git describe --abbrev=0 --tags
1.7.6
```

So, I think it's more `git checkout $(git describe --abbrev=0 --tags)` to checkout the latest tag.
