### ISSUE TITLE
index.html (or Redirect Index plugins) directly

### ISSUE THREAD

**Issue by Allread** [YOURLS/YOURLS#2631]
Hi :) 

It would be good to make an index.html with redirection (or to add the Redirect Index plugin) directly in the basic package.
In fact, badly configured, visitors arrive on the public folder with all the readable files.

Just index.html => <head> <META HTTP-EQUIV="Refresh" CONTENT="0; URL=your_site"> </head>

**Comment by LeoColomb** [comment]
Thanks for this issue @Allread!

> In fact, badly configured, visitors arrive on the public folder with all the readable files.

Well, YOURLS target is not to fix badly configured servers, I'm afraid.  
To be fair, I don't understand the goal on this, the default configuration provided by YOURLS already address directory listing issue.

**Comment by Allread** [comment]
Sorry, im french 🥺

I mean by "misconfigured", if you install yourl without a home page at the root of / www / for example, visitors who visit "mydomain.com" see all the files as well as the DB configuration files.

**Comment by ozh** [comment]
Indeed. See the FAQ: http://yourls.org/#FAQ#noindex
