### ISSUE TITLE
After enable HTTPS, table of short url don´t refresh.

### ISSUE THREAD

**Issue by danilorassis** [YOURLS/YOURLS#2636]
Hello
I'm using Yourls in version 1.7. I recently enabled HTTPS for the admin page and url redirects.
After that, when I try to create a new short link, it is created within the database but the administration page (Table) is not updated. The link creation button has a loading status. Only when I press F5 the table is updated.

Can you help me?

**Comment by dgw** [comment]
Start here: https://github.com/YOURLS/YOURLS/wiki/Endless-Spinning-Icon

This kind of problem is usually server config related.

**Comment by ozh** [comment]
Closing because no feedback
