### ISSUE TITLE
About uppercase letters 

### ISSUE THREAD

**Issue by Motsik** [YOURLS/YOURLS#2637]
Hello, i am using 
Random ShortURLs Plugin
is possible to generate also uppercase letters in url link?
Thanks!

**Comment by dgw** [comment]
The available characters are determined by the value of `YOURLS_URL_CONVERT` in the config file. You can find details about it in the config documentation: https://yourls.org/#Config

(@ozh There's a `#urlsettings` fragment that would go directly there, but the JavaScript tabbing makes it not work. Maybe we should rethink that part of the website?)

**Comment by Motsik** [comment]
Thank you! is there any nice theme option available?

**Comment by dgw** [comment]
Theming isn't officially supported yet (#1234).

**Comment by ozh** [comment]
@dgw https://yourls.org/#Config#urlsettings works for me, not you? (Win, FF or Chrome)

**Comment by dgw** [comment]
@ozh No, at least not on Android Chrome.

![Screenshot_20200403-111846](https://user-images.githubusercontent.com/164140/78382795-00aeea80-759d-11ea-9edc-56ce433a3f78.png)

I'd seen you post a link like that before, so I tried it when adding my link in this thread above, but bailed when my test on PC (Chrome, Win10) didn't work.
