### ISSUE TITLE
Twitter Account @yourls blocked?

### ISSUE THREAD

**Issue by ArnaudFeld** [YOURLS/YOURLS#2639]
![189DEDDE-73F0-4C30-91FC-6E59EB183ACC](https://user-images.githubusercontent.com/1561416/78505713-9ac98b00-7775-11ea-9465-b1e6b42ec42c.png)

Has your Account on Twitter has been blocked?

I ask because it is in the Readme.md 😁

**Comment by LeoColomb** [comment]
Thanks for opening this ticket @ArnaudFeld.

You seems to be right, I get the same error on my side. @ozh? 🙂

**Comment by ozh** [comment]
Yeah, I know. Both @yourls and @yourls_dev are suspended. I've been trying to open a ticket for this on Twitter, but got no answer so far :-/

**Comment by dgw** [comment]
@ozh Best of luck. My own attempts to get support from Twitter (issues resetting an old account's password) were less than successful, so I hope you're more fortunate.

**Comment by ozh** [comment]
Final ruling from these fuckers:
> Hello,
> We’re writing to let you know that we’ve permanently suspended your account due to multiple or repeat violations of our rules.
> This account will not be restored.
> Please do not reply to this email or send us new appeals for this account as we won’t monitor them.
> Thanks,
> Twitter

**Comment by dgw** [comment]
Twitter bans YOURLS, but when I report actual abusive users they do nothing. Makes _perfect_ sense… /s
