### ISSUE TITLE
 Uncaught PDOException:  duplicate entry

### ISSUE THREAD

**Issue by stoneric** [YOURLS/YOURLS#2640]
We are getting 500 errors and very low levels of this bug:

PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1TM' for key 'PRIMARY' in /var/www/html/includes/vendor/aura/sql/src/ExtendedPdo.php:748

**Versions**
We are running PHP 7.3 / nginx and the latest Yourls release

**Comment by dgw** [comment]
What triggers it? I don't understand "very low levels of this bug"—does that mean it happens infrequently? My gut feeling is a race condition between two clients trying to shorten a URL with an automatically generated keyword (the default sequential mode). But there's not enough information about the configuration to know for sure.

**Comment by ozh** [comment]
![image](https://user-images.githubusercontent.com/223647/78651413-9a89d680-78c0-11ea-8043-0d50936e13bd.png)

**Comment by ozh** [comment]
Feel free to keep commenting with relevant details

**Comment by stoneric** [comment]
We get 1 out of about every 10,000 requests.

**Comment by dgw** [comment]
Is it the _same_ keyword in the error each time, or a different one? Can you see from the server logs what type of request usually triggers the error (GET/POST, endpoint/path)?

We can't even begin to _speculate_ without any clue what part of the application is causing the problem.
