### ISSUE TITLE
How to install this?

### ISSUE THREAD

**Issue by phcu-badbox** [YOURLS/YOURLS#2642]
* [x] I've read the [guidelines for Contributing to YOURLS Projects](https://github.com/YOURLS/.github/blob/master/CONTRIBUTING.md)
* [ ] This request isn't a duplicate of an existing issue
* [ ] I've read the [docs](https://yourls.org/) and followed them (if applicable)
* [ ] This is not a personal support request that should be posted on the [YOURLS Discourse](https://discourse.yourls.org/) community

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behavior**
What actually happens.

**Screenshots**

**Versions**
You can get this information from referencing `CHANGELOG.md` or the releases page.
Also, please include:
* The OS and what version of the OS you're running.
* Plugins or extensions activated if applicable.

**Additional context**
Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by phcu-badbox** [comment]
Can you add information on how to install this?

**Comment by dgw** [comment]
If you'd read the docs, you would have seen these installation instructions: https://yourls.org/#Install
