### ISSUE TITLE
https Fails to work from Cloudflare

### ISSUE THREAD

**Issue by mtsmayad** [YOURLS/YOURLS#2643]
Hello,

I installed yourls 1.7.6 on a free web host and it works fine with http, but, when i allowed https from cloudflare it won't create new short links, can  u suggest a way.

http://urlz.ga/go/

THANK U.

**Comment by ozh** [comment]
There's an issue template and it's not for nothing. Feel free to add details in this issue.

**Comment by mtsmayad** [comment]
I did not understand your point sir.

**Comment by ozh** [comment]
When you open an issue, it's pre-filled with a template. This template is here to collect informations that are the bare minimum to expect assistance. "when i allowed https from cloudflare" doesn't give the slightest information on what you exactly did and what might be the "bug" on the YOURLS part.

**Comment by mtsmayad** [comment]
so i need to close this one and re-open or explain again

**Comment by ozh** [comment]
As I said above : Feel free to add details in this issue.

**Comment by mtsmayad** [comment]
ok,
I installed yourls 1.7.6 on 0hi.me free web host.
And it works fine, but when i changed server names to point to cloudflare to get https, the script does not create new urls, it keeps pending without result.
http://urlz.ga/go/

**Comment by dgw** [comment]
@mtsmayad Your hosting service specifically bans URL shorteners, btw. And you still haven't provided the details required by the issue template.
