### ISSUE TITLE
nginx: 403 on brand new install

### ISSUE THREAD

**Issue by Robbbbbbbbb** [YOURLS/YOURLS#2645]
Hey all,

Spun up a new Ubuntu 18.04 VM and installed YOURLS today following the [install guide here](https://computingforgeeks.com/how-to-install-yourls-your-own-url-shortener-on-ubuntu-18-04-bionic-beaver-linux/), but I'm not able to get it working properly.

Any visit to the actual homepage of the site results in a 403, nginx `error.log` reports the following:

`[error] 2161#2161: *14 directory index of "/srv/YOURLS/" is forbidden`

I can visit /admin/ just fine, but if I attempt to visit a redirected URL or the non-admin portion of the site, I get the 403 paired with the log entry above

NGINX is running as www-data
Permissions to /srv/YOURLS and directories within is 755, files are 644

NGINX conf is as follows:

```nginx
server {
  listen 80;
  server_name site.com www.site.com;
  root /srv/YOURLS;
  index index.php index.html index.htm;
  listen [::]:80;
  location / {
    try_files $uri $uri/ /yourls-loader.php$is_args$args;
  }

  location ~ \.php$ {
    try_files $uri =404;
    fastcgi_split_path_info ^(.+\.php)(/.+)$;
    fastcgi_index index.php;
    fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
    fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;
    include fastcgi_params;
  }
}
```

Can anyone give any ideas what's going on?

**Comment by ozh** [comment]
Not an nginx user so I shouldn't be of much help, but I appreciate the quality and details of the issue submission :)

Maybe you have directory indexing off ? Does [autoindex](http://nginx.org/en/docs/http/ngx_http_autoindex_module.html) help?

**Comment by LeoColomb** [comment]
> Not an nginx user so I shouldn't be of much help

@ozh Don't hesitate to ping me on Nginx question 🙂 

> `[error] 2161#2161: *14 directory index of "/srv/YOURLS/" is forbidden`

What is your homepage filename?

Can you access the following exact addresses?
* `site.com/admin/[homepage filename]`
* `site.com/admin/`
* `site.com/admin/index.php`

**Comment by LeoColomb** [comment]
Closing as misconfiguration. 
Don't hesitate to continue the discussion if get more details.
