### ISSUE TITLE
URLs created with a previous charset should be forever valid/editable

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#2646]
Scenario:
- activate a plugin that modifies charset
- create short URLs
- deactivate the plugin
- you're f*cked.

See #2280 for example.

Solution: creating a short URL should check and sanitize things against the accepted charset. Displaying or following short URLs should just deliver what is stored in the DB

**Comment by jmcollado** [comment]
We dont fix this bug with a plugin, because the function yourls_edit_link not include an action where i bind

**Comment by ozh** [comment]
@jmcollado this issue is opened precisely as a reminder (to me) to fix this in core
