### ISSUE TITLE
stats not working 

### ISSUE THREAD

**Issue by aksksujit** [YOURLS/YOURLS#2647]
Stats: http://short.mycreditpolicy.com/4+
 
on opening this link it says This page isn’t working http error 500

**Comment by ozh** [comment]
https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps
Also: issue template.

**Comment by aksksujit** [comment]
checked everything web.config, .htaccess nothing work

**Comment by LeoColomb** [comment]
> web.config, .htaccess nothing work

Probably better to ask your host provider then...
Check your logs, check your plugins, check your version, as @ozh said, please take a look at https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps
and the issue template.
