### ISSUE TITLE
Double slash (/) in urls

### ISSUE THREAD

**Issue by sketchub-official** [YOURLS/YOURLS#2651]
I tried YOURLS, and everylink which is produced is like http://example.com//123 while it should be http://example.com/123 .

**Comment by sketchub-official** [comment]
Sorry, it is solved, in 'YOURLS_SITE' i placed https://example.com/ instead https://example.com

**Comment by ozh** [comment]
I thought this was fixed anyway. What version of YOURLS are you using?

**Comment by sketchub-official** [comment]
Im using latest one. Yes it is fixed, in YOURLS_SITE i accidentally placed "example.com/"instead "example.com".

**Comment by ozh** [comment]
No, I mean, I thought entering "yoursite.com/" instead of "yoursite.com" wasn't a problem any longer
