### ISSUE TITLE
Short links giving 404

### ISSUE THREAD

**Issue by TheProgramSrc** [YOURLS/YOURLS#2652]
When I try to access to a short url (For example: sh.rt/test) I got a 404 Error page

I already saw the Wiki and nothing works, In my apache2 config I have AllowOverride All and my htaccess its like the one in the wiki, I'm running yourls on https://theprogramsrc.xyz/go/

**Comment by ozh** [comment]
I really wonder why everybody thinks they're just going to ignore the fucking issue template we provide.

Either your .htaccess or your server config overrides something. My not knowing about any of both, you're on your own.
