### ISSUE TITLE
`functions.php` is messy. Ideas for splitting?

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#2654]
The file has 2500 lines and more than 100 functions.

I'd like to split it in a couple other files (`functions-something.php`) but cannot think of a proper, relevant and illustrative `-something` ... Any ideas?

(similarly, any ideas to split other large files into relevant tinier pieces welcome)

**Comment by paulgoodchild** [comment]
I guess you could gather related functions into categories, like:

- filters (e.g. `yourls_return_true`, `yourls_return_false`)
- keywords (e.g. `yourls_keyword_is_reserved`, `yourls_keyword_is_free`)
- request state (e.g. `yourls_is_infos`,`yourls_is_admin`,`yourls_is_API`)

**Comment by paulgoodchild** [comment]
Would you like me to make a start on cleaning some of this with the suggestions above and offer a pull request?

**Comment by ozh** [comment]
Maybe the most practical thing first would be to simply have a document with file names and function names, rather than a whole codebase to mess with ? Something like http://collabedit.com/prpbd ? Thoughts?

**Comment by paulgoodchild** [comment]
Sure... you mean to just plan it out this way?
I've updated that doc and moved a few functions with:
# functions-debug.php
# functions-filters.php
# functions-options.php
# functions-state.php

Of course, names can be adjusted, it's just to start some sort of grouping.

**Comment by ozh** [comment]
Not looking bad. I'll need to have this running a couple days in my head eventually but it's starting to look nicer :)

Maybe another grouping could be "stuff relative to short URL" (yourls_add_new_link, yourls_*_keyword_*...) and "stuff relative to how we mangle links or URL" (yourls_admin_url, yourls_site...) but my brain crashed at the naming problem (the whole app is about links, so for instance having functions-links.php or functions-urls.php sounded dumb to me)

**Comment by paulgoodchild** [comment]
My view on that is it does no harm to rearrange and organise it, and if you change your mind later on for the naming the convention, it's a simple to adjust it. Best to start with something small and build from there, or you'll never move it.

Separately, another place to clean a few things up which we can do in this reorg, is to use things like shorthand array notation and adjust simple functions like this to be cleaner and less verbose:

```php
function yourls_is_API() {
    $return = defined( 'YOURLS_API' ) && YOURLS_API == true;
    return yourls_apply_filter( 'is_API', $return );
}
```
to
```php
function yourls_is_API() {
    return yourls_apply_filter( 'is_API', defined( 'YOURLS_API' ) && YOURLS_API );
}
```

Just a few thoughts.

**Comment by paulgoodchild** [comment]
Sounds good - if you reference this issue in your pull request, I'll get a notification sure when it's done and then I'll have a go at cleaning in the way I suggested.  As you say, far easier to do it post-merge than before or during.
Cheers!

**Comment by ozh** [comment]
@paulgoodchild reorder done, feel free to clean up some code where suitable.

Types of stuff I'm totally for: unused vars, too complex function paths (ie intricated if/else stuff for example). Stricter casting is neat too, maybe this will highlight a few areas of sloppy coding (the 10 years ago me was very fond of "@return mixed" functions that would return bools, strings or array depending on context :)

Types of stuff I'm not totally for: when brevity makes readability harder.

For instance the examples you mention above are very fine.

If unsure please make modifications in single commits so it's easy to cherry unpick rather than huge commits with dozens of changes :)

**Comment by paulgoodchild** [comment]
Sounds good - I agree with all you say.  Brevity that makes things unreadable wrecks my head! :)
