### ISSUE TITLE
Upgrading to 1.7.9 broke my install

### ISSUE THREAD

**Issue by MastaBaba** [YOURLS/YOURLS#2658]
* [x] I've read the [guidelines for Contributing to YOURLS Projects](https://github.com/YOURLS/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://yourls.org/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [YOURLS Discourse](https://discourse.yourls.org/) community

**Describe the bug**
Upgrading to 1.7.9 from 1.7.4 broke my install.

**To Reproduce**
I'm not going to try to do this again to see if it is reproducible, but I got to the point of failure easily:

1. Replace install with 1.7.9 files.
2. go to root of site.

**Expected behavior**
A fine working site.

**Actual behavior**
An empty screen. I turned PHP's error reporting on and got this:

Fatal error: Uncaught Error: Call to undefined function yourls_get_yourls_site() in /mysite/includes/functions-http.php:295 Stack trace: #0 /mysite/includes/functions-http.php(418): yourls_check_core_version() #1 /mysite/includes/functions.php(2452): yourls_maybe_check_core_version() #2 /mysite/includes/Config/Init.php(112): yourls_tell_if_new_version() #3 /mysite/includes/load-yourls.php(26): YOURLS\Config\Init->__construct(Object(YOURLS\Config\InitDefaults)) #4 /mysite/admin/index.php(8): require_once('/mysite...') #5 {main} thrown in /mysite/includes/functions-http.php on line 295

**Versions**
Running Apache on PHP 7.3.
Two plugins installed: the background changer and this QR code plugin: 

https://github.com/YOURLS/YOURLS/wiki/Plugin-=-QRCode-ShortURL

**Comment by ozh** [comment]
You simply didn't update correctly and didn't overwrite all existing files. The function `yourls_get_yourls_site()` **is** [defined in 1.7.9](https://github.com/YOURLS/YOURLS/blob/1.7.9/includes/functions.php#L2456-L2458)

**Comment by MastaBaba** [comment]
Perhaps, indeed. But, I confirmed the existence of the function, on the server, in functions.php.

**Comment by ozh** [comment]
Then you simply don't update the right files. (ie you update files in `/home/mysite/yourls` but your webserver reads files from some other place). Simple as that.
