### ISSUE TITLE
YOURLS on Cloudron

### ISSUE THREAD

**Issue by nebulade** [YOURLS/YOURLS#2659]
Hi there,

we have packaged YOURLS for [Cloudron](https://cloudron.io) to allow easy installation. We also keep the app updated with the upstream releases for our users. We did package it based on popular user demand :-)

I saw that http://yourls.org/#Install lists a couple of ways to get the app installed. Would it be possible to also list the Cloudron package there? The link would be https://cloudron.io/store/org.yourls.cloudronapp.html and the actual app package repository can be found in our GitLab instance at https://git.cloudron.io/cloudron/yourls-app

Best,
Johannes

**Comment by dgw** [comment]
I don't think we'd want to feature a paid/commercial service. @YOURLS/admins, dissenting opinions?

**Comment by gramakri** [comment]
FWIW, the app package itself is MIT licensed and we also have automatic selenium tests to verify the updates go smoothly (in the tests/ subdirectory). At the end of the day, Cloudron is just an installation tool, our goal is not to rebrand or sell commercial YOURLS services (it's similar to the already listed softaculous in this regard). But I will understand whatever decision is made.

**Comment by dgw** [comment]
Perhaps we've found an opportunity to improve Cloudron's documentation, then? Clicking around (well, tapping/swiping; I was on my smartphone) earlier gave me the impression that a subscription is required to use Cloudron.

If that's not the case, maybe e.g. the "Pricing" page could be updated to clarify that. 😸

**Comment by nebulade** [comment]
Indeed, we don't mention that there is a free tier everyone starts in. The subscription is required when installing more than two apps.

**Comment by ozh** [comment]
I think that's neat, at least at this point, I'm fine with promoting a tool that promotes YOURLS. Eventually, if more paid services reach to us to get listed and YOURLS is just used as an advertisement for them, we sure may just remove everything, but at this point I think it's fine. I mean, we do already give exposure to some commercial services, such as the hosting websites having install guides for instances.

This said, I think all these unofficial guides, sites and tools mentioned in the readme might be better in [yourls-awesome](https://github.com/YOURLS/awesome-yourls)? This way we could keep the readme light with only "official" stuff

**Comment by nebulade** [comment]
Wow I wasn't aware of that awesome list, quite impressive!

**Comment by ozh** [comment]
Closing here, will be resolved with https://github.com/YOURLS/awesome-yourls/issues/59

**Comment by ozh** [comment]
@nebulade for the record, the Cloudron link is on the the Awesome list
