### ISSUE TITLE
Error finding url

### ISSUE THREAD

**Issue by rawira** [YOURLS/YOURLS#2665]
Problems finding urls of this kind:

"https://domain.com/8w3X3M?utm_source=FB&utm_campaign=G3&utm_creative=C1&ulp=https%3A%2F%2Fbomond.com.ua%2Fadvanced-genifique-yeux-light-pearl-aktivator-molodosti-dljakozhzhzhkozh-glaz-150108.html"

**Comment by dgw** [comment]
Rest in peace, issue template. You are sorely missed. 🙄
