### ISSUE TITLE
Dropping characters from custom short URL

### ISSUE THREAD

**Issue by aantonop** [YOURLS/YOURLS#2666]
* [X] I've read the [guidelines for Contributing to YOURLS Projects](https://github.com/YOURLS/.github/blob/master/CONTRIBUTING.md)
* [X] This request isn't a duplicate of an existing issue
* [X] I've read the [docs](https://yourls.org/) and followed them (if applicable)
* [X] This is not a personal support request that should be posted on the [YOURLS Discourse](https://discourse.yourls.org/) community

**Describe the bug**
When entering a custom short URL (eg. bonuslivestreamhalvingtimes), the URL is stored but with missing characters (bonuslivestreamalvingtimes - dropped the "h"). After editing the short URL it can be corrected. This bug started occurring intermittently yesterday, for 3 different users. No new plugins or other changes to the software since installation. 

**To Reproduce**

Enter a custom short URL. Sometimes it drops letters from the beginning, or the middle.

**Versions**
YOURLS 1.7.4
Also, please include:
* Ubuntu 18.04LTS

11 plugins installed:

Plugin Name | Version | Description | Author | Action
-- | -- | -- | -- | --
Allow Hyphens in Short URLs | 1.0 | Allow hyphens in short URLs (like http://sho.rt/hello-world) | Ozh |  
Amazon Affiliate | 1.2 | Add your Amazon Affiliate-Tag to all Amazon URLs before redirection | Florian Schliep |  
Do TLS | 0.0.1 | Always use TLS for destination url if available | Josh Panter |  
Don't Log Crawlers | 1.3 | Prevents  YOURLS from counting clicks of crawlers & bots with specific User  Agent strings or CIDRs/IP addresses (hardcoded or obtained from a  `whois` lookup on an ASN). | Suguru Hirahara, Rich Christiansen |  
GA-Measurement-Protocol | 1.1 | Tracks clicks using Google Analytics Measurement Protocol. License: Creative Commons Attribution 3.0 Unported: https://creativecommons.org/licenses/by/3.0/ | Powerthazan |  
Google Analytics | 1.1 | Easily add Google Analytics tracking tags to your generated links. Settings: Configure settings | Katz Web Services, Inc. |  
Google Authentication | 1.0 | This plugin enables authentation against Google | Tony Tomarchio (atomarch) |  
QR Code Google Charts | 1.0 | Inline Qr codes using Google Charts API URI: http://yourls.org/ | Aiaraldea |  
Random ShortURLs | 1.2 | Assign random keywords to shorturls, like bitly (sho.rt/hJudjK) | Ozh |  
Redirect Index | 1.0 | Redirect the base directory of YOURLS to a user selected link | Tom Slominski |  
SSL for SSL | 0.1 | Create SSL short links for SSL urls | Chris Hastie |  

**Additional context**
Started happening yesterday, no changes to software since installation. Used every day. 411 links stored at this time.

**Comment by ozh** [comment]
Thanks for this detailed issue, but at this point 2 things prevent us from doing something helpful:
- way too many plugins. To make sure a defect is a YOURLS bug (which I doubt it is here) and not a plugin side effect, [plugins must be deactivated](https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps#disable-plugins).
- this is not reproducible : "enter a custom URL and sometimes it fucks up" isn't a way to pinpoint the problem. I understand that it may be hard if you don't see a consistent unexpected behavior, but without a detailed "this is exactly how the bug happens" there is absolutely nothing we can do. If there was a bug in YOURLS that was dropping random letters, I'm sure the tens of thousands of YOURLS users and their millions of shortened URLs would have raised the issue years ago.

Are you sure it's not dropping **capital** letters ?

**Comment by ozh** [comment]
Also, YOURLS 1.7.4 (I think that wouldn't change anything, but we wouldn't "fix" anything on an old version)

**Comment by loano** [comment]
Hi, I noticed the same yesterday with YOURLS-1.7.9.
Characters did disappear from Custom Short URL and I had to edit it several times to match my Custom URL. But since I installed YOURLS yesterday for the first time and I'm still in the process of setting it up, I thought this is someting I missed on setup.

**Comment by ozh** [comment]
Same comment: see http://yourls.org/#FAQ#lowercase
