### ISSUE TITLE
How can I remove the http:// part from the short domain?

### ISSUE THREAD

**Issue by jack2go** [YOURLS/YOURLS#2669]
Hello.
How can I remove the “http://” part from the generated short domain?
I want it to show “yourls.org/cookie” and not “http://yourls.org/cookie”

Similar to bitly.com links.

Thank you?

**Comment by ozh** [comment]
I don't understand the question. *Where* do you want to show the URL without the HTTP part?

**Comment by jack2go** [comment]
> I don't understand the question. _Where_ do you want to show the URL without the HTTP part?

as the final short URL that the user can see and copy

**Comment by LeoColomb** [comment]
Please don't ask your question at many places in the same time, that useless.
https://discourse.yourls.org/t/how-can-remove-the-http-part-from-the-short-domain/222

**Comment by jack2go** [comment]
Sorry about that,

**Comment by LeoColomb** [comment]
> Similar to bitly.com links

bitly.com links include `https` like every other link on Earth.
Removing that part is like removing a wheel on a car, you can't go anywhere after that.

**Comment by jack2go** [comment]
> > Similar to bitly.com links
> 
> bitly.com links include `https` like every other link on Earth.
> Removing that part is like removing a wheel on a car, you can't go anywhere after that.

When I generate a link on bitly.com id doesn't include the "http://"

**Comment by LeoColomb** [comment]
![image](https://user-images.githubusercontent.com/846943/80794437-334b0380-8b9a-11ea-9a96-c2afbd793f97.png)

**Comment by jack2go** [comment]
Exactly :)
I want this without the "http://"

How can I do it ?
