### ISSUE TITLE
Aggregate traffic referrers for same URL (remove protocol and ending /)

### ISSUE THREAD

**Issue by stevecohenfr** [YOURLS/YOURLS#2674]
* [x] I've read the [guidelines for Contributing to YOURLS Projects](https://github.com/YOURLS/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing request
* [x] This is not a personal support request that should be posted on the [YOURLS Discourse](https://discourse.yourls.org/) community

**Summary**
It would be better if referrers url that differs on http/https and ending/not-ending with '/' were aggregated in the trafic source tab.
Because in my case I have this :

    http://m.facebook.com: 27
    http://m.facebook.com/: 73
    https://m.facebook.com/: 2

This is the same referrer but one with http, the other with https and other with ending /

**Motivation**
With this aggregation it easier to read the trafic source tab.
In my case it should be :

    m.facebook.com: 102

**Describe the solution you'd like**
Trailing the protocol and ending /

**Describe alternatives you've considered**
Counting with my hands 😅

**Comment by ozh** [comment]
I guess we should have stored referrers that way from the beginning :)

Option 1: continue storing that way, and fix the query or, if not possible, the displaying
Option 2: change the way we store. This would imply having an update function, but I'm not sure we can easily update large databases with a online script

**Comment by ozh** [comment]
I've given this some thoughts and after trying to come up with all possible scenarios in the unit test I was writing, I came to the following conclusion. 

Regarding the scheme : https://something/ and http://something/ can be 2 different things. It's rare, but it's totally valid that these 2 URLs be 2 different sites. Just like http://www.site.com/ and http://site.com/ could, again, be 2 different things.

Regarding trailing slash : the referrer will most likely be a website, ie `http(s)://something`. But it can totally be something else than `http(s)`. An easy example would be `ftp://`, but it could be something entirely different. The thing is : depending on the scheme, I don't think it's always harmless to add a trailing slash to the domain.

So for now (and most likely for ever) I'll leave this as is, being aggregated on the stat page by domain but not by URL. 
![image](https://user-images.githubusercontent.com/223647/132250236-314843ce-703e-48c2-a704-7e19fb57c757.png)
