### ISSUE TITLE
limiting request to yourls-api.php

### ISSUE THREAD

**Issue by RandiStone** [YOURLS/YOURLS#2677]
Hello;

This isn't a bug, more a request for help. We've search about for both information on this and a YourLS support forum and found nothing.  If this is the wrong place to ask for help please let me know where to go.  If what we need to do is documented some place please point me in that direction.

I'm working with someone who is getting messages from his hosting company that yourls-api.php is getting too much traffic.

Is there a way to limit the calls made to YourLS from the YourLS Link Creator v2.1.1?

We think that's the source as turning off that plugin in his WordPress installation has resulted in the traffic dropping.

Here is the data presented by the hosting company:

-Hourly hits (30/Apr/2020)--------------------------------------------------------------------------
05: 26     06: 27     07: 5735   08: 11917  09: 12130  10: 1139   11: 1136   12: 1138   13: 279
14: 396    15: 741    16: 481    17: 1134   18: 1134   19: 1135   20: 1133   21: 1133   22: 1133
23: 1141

-Duplicate requests + response codes----------------------------------------------------------------
42737   200   POST /yourls-api.php
188     200   HEAD /
40      404   POST /yourls-api.php

-Requests for non-static content--------------------------------------------------------------------
42737   200   POST /yourls-api.php
188     200   HEAD /
40      404   POST /yourls-api.php

After turning off the WordPress plugin the requests for /yourls-api.php dropped off the top 10 list.

Details on YourLS

## Technical details regarding my environment
- YOURLS version: 1.7.9
- Plugins enabled:
    1. hyphens-in-urls/plugin.php
    1. fallback-url/plugin.php
    1. popular-links/plugin.php
    1. GautamGupta-YOURLS-Import-Export-00f50ef/plugin.php
    1. admin_issue_diagnostic-master/plugin.php
- YOURLS DB Ver: 482
- PHP version: 7.3.11
- Server OS Build: Linux
- Server & version: Apache
- Browser information: Mozilla/5.0 (X11; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0

- Generated by the AID Plugin ver 1.0 

WordPress is the current version 5.4.1.

Thank you, Randi

**Comment by dgw** [comment]
This WordPress plugin? https://github.com/norcross/yourls-link-creator

It defines an hourly cron job (in WP, which has its own cron system) that loops through all saved shortlinks and updates their click stats.

If that's the right plugin, ask the developer to add controls for switching off and/or modifying how often click stats are updated. You could also switch to a different short URL management plugin; there are many.

@ozh Comments in the code over there make me ask: Does YOURLS' API have a bulk query function? Can an API app update the long URL of a shortlink? (Are these possible with a plugin, just not in core? 😁)

**Comment by ozh** [comment]
@dgw out of the box the API cannot update/edit a link. It can just add links, or fetch stats, which seems to be what this plugin is doing (checks every hour how many clicks each shortlink has received)

Regarding @RandiStone issue: easier than adding a way to limit requests to yourls-api.php, you should check on the plugin side. Apparently there's a [filter to disable cron jobs](https://github.com/norcross/yourls-link-creator/blob/master/yourls-link-creator.php#L132), so either you use that filter if you need fine tuning based on some criteria, or you just bypass the whole stuff: edit the plugin so [these lines](https://github.com/norcross/yourls-link-creator/blob/master/yourls-link-creator.php#L124-L145) simply become:
```php
public function schedule_crons() {
    return;
}
```

@RandiStone you should also (if not already existing) open an issue on @norcross plugin and explain the situation so maybe he would add an option in the settings to disable the cron checking :) (not sure if the plugin is still actively maintained)

**Comment by ozh** [comment]
(top notch first analysis by @dgw who really pin pointed the problem and culprit. I would not have dug this far, I admit :)
