### ISSUE TITLE
Redirect only via Javascript

### ISSUE THREAD

**Issue by uniextra** [YOURLS/YOURLS#2678]
Hi i like to implement a pluging to redirect only via javascript instead of headers, i was able to do it on 1.7.6 via changing functions.php yourls_redirect to this:
function yourls_redirect( $location, $code = 301 ) {
	yourls_do_action( 'pre_redirect', $location, $code );
	$location = yourls_apply_filter( 'redirect_location', $location, $code );
	$code     = yourls_apply_filter( 'redirect_code', $code, $location );
	// Redirect, either properly if possible, or via Javascript otherwise

	yourls_redirect_javascript( $location );

	die();

but now updagrade to 1.7.9 and funtion is diferents and anyhow i like not to mess with core files and implement this via pluging.. 

any way to make this work?

**Comment by ozh** [comment]
To redirect only with javascript, something like the following in a plugin:
```php
yourls_add_action('pre_redirect', 'uniextra_redir');
function uniextra_redir($args) {
    $url = $args[0];
    yourls_redirect_javascript( $url );
    exit;
}
```

There are numerous plugin dealing with redirection that can serve as examples to build on
