### ISSUE TITLE
Not redirecting http

### ISSUE THREAD

**Issue by theMelMills** [YOURLS/YOURLS#2680]
Hi all, I've searched all over for this and tried several threads to no avail. I *think* this may be a bug as none of these solutions from the forum or other threads here have worked. My apologies if I am mistaken.

My https links are forwarding correctly but my HTTP ones are not and just default to the catch-all address. http://melm.co/scholars/?nocache=1 (doesn't work) https://melm.co/scholars/?nocache=1 (works).

It's like YOURLS is processing them as an error and not looking them up. I even updated to the latest release as well. Prior to this, I had an SSL cert installed on my server too.

Just for reference, my htaccess code is below and I have also updated my config file.

````
# BEGIN YOURLS
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_URI} !^/\.well-known/acme-challenge/[0-9a-zA-Z_-]+$
RewriteCond %{REQUEST_URI} !^/\.well-known/cpanel-dcv/[0-9a-zA-Z_-]+$
RewriteCond %{REQUEST_URI} !^/\.well-known/pki-validation/[A-F0-9]{32}\.txt(?:\ Comodo\ DCV)?$
RewriteCond %{REQUEST_URI} !^/\.well-known/pki-validation/(?:\ Ballot169)?
RewriteRule ^.*$ /yourls-loader.php [L]
RewriteCond %{HTTPS} off
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
</IfModule>
# END YOURLS
<IfModule mod_rewrite.c>
RewriteCond %{HTTP_HOST} ^melm.co$
RewriteCond %{REQUEST_URI} !^/\.well-known/acme-challenge/[0-9a-zA-Z_-]+$
RewriteCond %{REQUEST_URI} !^/\.well-known/cpanel-dcv/[0-9a-zA-Z_-]+$
RewriteCond %{REQUEST_URI} !^/\.well-known/pki-validation/[A-F0-9]{32}\.txt(?:\ Comodo\ DCV)?$
RewriteCond %{REQUEST_URI} !^/\.well-known/pki-validation/(?:\ Ballot169)?
RewriteRule ^/?$ https://themelmills.com [R=301,L]
</IfModule>
````

If this is not a true bug, please accept my apologies but I cannot locate any discernable cause. I appreciate any support you can provide.

Thanks,

**Comment by ozh** [comment]
http://melm.co/scholars/?nocache=1 and https://melm.co/scholars/?nocache=1 work the same for me. Tried with the default links http://melm.co/ozh (not https) and it also appears to work fine. Also what's this `?nocache` bit?

**Comment by theMelMills** [comment]
You're right. And I am without explanation, to be honest. I spent about a day and a half on this and to no end. But it's resolved now (I verified as well) and I appreciate the prompt response and checking into it. Apologies for the false alarm.
