### ISSUE TITLE
Delete no longer works in latest version

### ISSUE THREAD

**Issue by jayray-git** [YOURLS/YOURLS#2681]
After upgrade delete button in admin page no longer works. Have tried across multiple browsers. Rolled back, and no issue.

**Comment by jayray-git** [comment]
New code is popping something on modsecurity.. I just bypassed it.

**Comment by ozh** [comment]
@jayray-git what was the message ? I'd be curious to know. We've had troubles with mod_sec in the past but it's been long since we've heard about it
