### ISSUE TITLE
Random ShortURLs plugin doesn't show default value

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#2683]
Upon first activation it should show the default value instead of a blank input:
![image](https://user-images.githubusercontent.com/223647/81315809-0f505c00-908b-11ea-9d43-b435738b5c36.png)

(Also, not sure the HTML control is what we need here, a simple input text would be simpler. Was I the one to come up with this idea in the original plugin? Don't remember)

**Comment by zach2825** [comment]
What should be the default value?

**Comment by zach2825** [comment]
I feel like I might have added what you were asking in this PR https://github.com/YOURLS/YOURLS/pull/2767 I don't know if 5 is a good enough default. But, the workflow works as requested.
