### ISSUE TITLE
This github repo "/contribute" URL

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#2686]
https://github.com/YOURLS/YOURLS/contribute displays a neat summary, except that it's complete BS: 404 to a non existent doc, and issues selected by some random algo :
![image](https://user-images.githubusercontent.com/223647/81613299-7c8f2480-93de-11ea-936a-c598ed1b011f.png)

People get potentially sent there when they first display the issue list:
![image](https://user-images.githubusercontent.com/223647/81613633-1d7ddf80-93df-11ea-8d71-d768937c8320.png)

Anyone knows how to tune this?

**Comment by LeoColomb** [comment]
@ozh For internal/repository configuration, I advise we first talk on a team conversation before opening a public issue, better for reviews.

> 404 to a non existent doc

The link should point to https://github.com/YOURLS/.github/blob/master/CONTRIBUTING.md
This is probably a GitHub issue, this screen is fairly new.

For internal/repository configuration, I advise we first talk on a team conversation before opening a public issue, better to review it.

> issues selected by some random

Yes, this is actually expected, from what I understood during GitHub presentation of the screen.

> Anyone knows how to tune this?

No options. Yet.

**Comment by ozh** [comment]
🍕
