### ISSUE TITLE
Creating a new link is not possible.

### ISSUE THREAD

**Issue by antt0n** [YOURLS/YOURLS#2687]
Good morning,
I have identified a rather problematic bug with the latest version of YOURLS.
I don't have any plugin, and I use NGINX as well as PHP 7.3.
When I try to create a custom shortcut for a URL that doesn't end with an extension (for example: https://discord.gg/YouNameHere), I get a 500 error from the AJAX page that normally registers the link.
In DEBUG mode, I have no additional information.
NGINX error log:
`2020/05/12 01:32:29 [error] 3381#3381: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF0\x9F\x8E\xB2 N...' for column `mydomain`.`mytable`.`title` at row 1 in /var/www/Eh/mydomain/includes/vendor/aura/sql/src/ExtendedPdo.php:748`

**Comment by ozh** [comment]
`\xF0\x9F\x8E\xB2` is the UTF8 sequence for 🎲. I don't get how this ends up in a datetime field.

Also, I don't get how the "doesn't end with an extension" part interferes. YOURLS doesn't care if the link has an extension or not. A link is a link.

**Comment by ozh** [comment]
No feedback, closing. Feel free to comment on with further details

**Comment by flumignan** [comment]
I have this too — and I'm happy to help provide more information. This only started recently after a handful of other URLs where shortened. I'm not a developer and have limited skills debugging, but am willing to try things with guidance or provide more testing results.

[Thu Jul 23 15:32:31.862319 2020] [php7:error] [pid 27033] [client 73.25.60.188:53025] PHP Fatal error:  Uncaught PDOException: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\\xF0\\x9F\\x94\\x97 Y...' for column 'title' at row 1 in /var/www/html/YOURLS/includes/vendor/aura/sql/src/ExtendedPdo.php:748\nStack trace:\n#0 /var/www/html/YOURLS/includes/vendor/aura/sql/src/ExtendedPdo.php(748): PDOStatement->execute()\n#1 /var/www/html/YOURLS/includes/vendor/aura/sql/src/ExtendedPdo.php(306): Aura\\Sql\\ExtendedPdo->perform('INSERT INTO `yo...', Array)\n#2 /var/www/html/YOURLS/includes/functions-shorturls.php(258): Aura\\Sql\\ExtendedPdo->fetchAffected('INSERT INTO `yo...', Array)\n#3 /var/www/html/YOURLS/includes/functions-shorturls.php(89): yourls_insert_link_in_db('https://github....', 'yourls', 'GitHub - YOURLS...')\n#4 /var/www/html/YOURLS/admin/admin-ajax.php(19): yourls_add_new_link('https://github....', 'yourls')\n#5 {main}\n  thrown in /var/www/html/YOURLS/includes/vendor/aura/sql/src/ExtendedPdo.php on line 748, referer: https://stanford.link/admin/?

**Comment by benpro** [comment]
Have the same issue.

```
2020/10/07 03:10:22 [error] 11118#11118: *17 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF0\x9F\x8E\x81 E...' for column `lnk`.`yourls_url`.`title` at row 1 in /home/lnk/www/includes/vendor/aura/sql/src/ExtendedPdo.php:748
Stack trace:
#0 /home/lnk/www/includes/vendor/aura/sql/src/ExtendedPdo.php(748): PDOStatement->execute()
#1 /home/lnk/www/includes/vendor/aura/sql/src/ExtendedPdo.php(306): Aura\Sql\ExtendedPdo->perform()
#2 /home/lnk/www/includes/functions.php(172): Aura\Sql\ExtendedPdo->fetchAffected()
#3 /home/lnk/www/includes/functions.php(268): yourls_insert_link_in_db()
#4 /home/lnk/www/admin/admin-ajax.php(19): yourls_add_new_link()
#5 {main}
  thrown in /home/lnk/www/includes/vendor/aura/sql/src/ExtendedPdo.php on line 748"
```

Seems related to some parsing of URL to shorten...

**Comment by dgw** [comment]
Seems likely a database encoding/collation mismatch. https://stackoverflow.com/a/48310027/5991 (This thread is about Laravel, but PDO is PDO.)
