### ISSUE TITLE
URL encoding/decoding problems

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#2691]
There's a well know issue that has been present since, well, ever: long URLs with non latin characters may be wrongly stored (or correctly stored but wrongly redirected).

I'm closing all historical issues because over the year some have been resolved or the need has changed and this issue here will supersede them. Progress on this issue will happen in #2690.

Anyone is welcome to contribute here, with the following requirements and with the following input:

### Requirement:

Please be using the latest YOURLS [release](https://github.com/YOURLS/YOURLS/releases) or current dev [`master`](https://github.com/YOURLS/YOURLS/archive/master.zip) (ideally it would even be current master on branch `thatfuckingencodingproblem`)

### Input:

Please provide the following information

* ACTUAL url you want to shorten (real URL please, we need real use cases)
* How you have shortened it: the "regular way" (cut and paste the in admin area then click Shorten), or a bookmarklet (and which one), or the "prefix n shorten" (trick eg `http://sho.rt/http://longurlhere`), or an API call (in which case, the code use and how the long URL was passed to the API)
* How it's displayed in YOURLS' admin (URL and title)
* URL that you are redirected to
* any other relevant comment

**Comment by ozh** [comment]
URLs that used to bork and now seems to be OK (with code in the associated pull request): stuff like https://www.google.com/search?q=c%2B%2B%20info, https://twitter.com/search?q=%23omg, with regular, or prefix n' shorten. Stored OK, displayed OK, redirects OK, and editing/saving short URL OK

Partially OK:
https://haraj.com.sa/1148395831/مكينك_حلاقة_هيتاشي/
![image](https://user-images.githubusercontent.com/223647/82236730-d50d7700-9934-11ea-971a-d89a2583d991.png)
https://طارق.net/%d8%a7%d9%83%d8%aa%d8%a8-%d9%85%d9%88%d8%b6%d9%88%d8%b9/ 
![image](https://user-images.githubusercontent.com/223647/82236340-43056e80-9934-11ea-8ceb-71c8b658bf2c.png)
Shorten OK with regular or prefix n shorten, redirect OK, editing short URL /saving OK, but displayed is fucked up, which makes it a bit difficult to check the long URL at a glance

**Comment by justkristin** [comment]
All, sorry to be a bother. Getting a missing post-domain forward slash issue...

ACTUAL url you want to shorten: First example, but true for other URLS... https://sandiegozoo.freshservice.com/support/catalog/items/73
How you have shortened it: the "regular way" (cut and paste the in admin area then click Shorten)
How it's displayed in YOURLS' admin (URL and title): (see attached image)
URL that you are redirected to: https://sandiegozoo.freshservice.comsupport/catalog/items/73
any other relevant comment: The only problem seems to be that it is missing the forward slash after the URL domain - it is losing it somehow.

Ubuntu 18.04.6
PHP 7.2.24
MySQL

YOURLS 1.7.9
Active Plugins: Allow Hyphens in Short URLs and Allow Aliases

Thank you for any help!

**Comment by ozh** [comment]
@justkristin well, if YOURLS was stripping forward slashes from URLs, there would have been a gazillion bug reports and this would have been fixed decades ago. Start here: https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps

**Comment by ozh** [comment]
I believe the long running generic problem is fixed. Closing here.
