### ISSUE TITLE
Accept CIDR format for `YOURLS_FLOOD_IP_WHITELIST` variable

### ISSUE THREAD

**Issue by jfix** [YOURLS/YOURLS#2692]
* [x] I've read the [guidelines for Contributing to YOURLS Projects](https://github.com/YOURLS/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing request
* [x] This is not a personal support request that should be posted on the [YOURLS Discourse](https://discourse.yourls.org/) community

**Summary**
Accept CIDR format for `YOURLS_FLOOD_IP_WHITELIST` variable.

**Motivation**
Currently, `YOURLS_FLOOD_IP_WHITELIST` allows to add individual IP addresses. Adding hundreds or more is not efficient.

**Is your feature request related to a problem? Please describe.**
At this point, I cannot add all the IP addresses that I'd like to whitelist because I have an IP address range of 1024 addresses (`/22`).

**Describe the solution you'd like**
I would like it to be possible to add individual IP addresses as well as IP address ranges in CIDR format.

**Describe alternatives you've considered**
Adding IP addresses to the list one by one; and as they are reported to me because the tool doesn't work. That's what I'm currently doing, unfortunately. ;-)

**Additional context**
Currently, the extraction of the IP addresses happens here:
https://github.com/YOURLS/YOURLS/blob/master/includes/functions.php#L547
Looking at the code it is clear that adding IP address ranges in CIDR format won't work because individual IP addresses are expected, separated by white space.

I'm not sure if a plugin would be possible as I cannot see a hook around this area. If so, I'd appreciate some hints on how to do it.

I don't know what the policy is in using external libraries for this project and I'm not a PHP programmer myself, but obviously there are some that would probably do the job: https://github.com/mlocati/ip-lib or https://github.com/dxw/cidr.

**Comment by ozh** [comment]
> I'm not sure if a plugin would be possible as I cannot see a hook around this area. If so, I'd appreciate some hints on how to do it.

You're right, there are no plugin for this, yet this "feature" really belong to plugin territory. I'll make it so.

Just being curious : what is your use case ?

**Comment by jfix** [comment]
The use case is: allow access to a batch process API endpoint from within the organisation's own IP address range and selected other IP addresses but not from elsewhere, in order to pre-generate short URLs for several dozens of long URLs at a time.

**Comment by ozh** [comment]
Looking back at this issue : there is an hook already there, it's `shunt_check_IP_flood`. I don't see then why a plugin could not manage the described issue ?

**Comment by jfix** [comment]
You're right, I'll look into this. I'll close this issue. Thanks.
