### ISSUE TITLE
Not Mobile Responsive

### ISSUE THREAD

**Issue by punkajpk** [YOURLS/YOURLS#2693]
* [x] I've read the [guidelines for Contributing to YOURLS Projects](https://github.com/YOURLS/.github/blob/master/CONTRIBUTING.md)
* [ ] This request isn't a duplicate of an existing request
* [ ] This is not a personal support request that should be posted on the [YOURLS Discourse](https://discourse.yourls.org/) community

**Summary**
The interface is not mobile responsive. Could you kindly add mobile responsiveness to the interface as it will be very helpful for everyone.

**Motivation**
It would be very beneficial to add mobile responsiveness to the interface. I expect the changes in CSS.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I want the interface of Yourls to be mobile responsive. It should adjust itself depending on the screen size.

**Describe alternatives you've considered**

**Additional context**

**Comment by dgw** [comment]
Issue template exists, and was ignored here.

> I had edited CSS and made it responsive

Maybe you would like to share these modifications?

**Comment by ozh** [comment]
> I want the interface of Yourls to be mobile responsive. It should adjust itself depending on the screen size

We all want :) This is a feature that will definitely come down the road. No ETA though

**Comment by Aternus** [comment]
@ozh heya, I'm using YOURLS on a daily basis from my phone and would like to update the theme, is this still relevant or is somebody is already working on the issue?

**Comment by ozh** [comment]
@Aternus nothing that I'm aware of

**Comment by Aternus** [comment]
@ozh I saw the v2.0 redesign, could you kindly provide the history behind it? Why it didn't end up shipping?
P.S. Perhaps there is a Discord or Slack where we can talk instead of comments? =]

**Comment by ozh** [comment]
@Aternus honestly I don't remember. I think it became too big to handle, started as a style redesign, evolved into adding tons of features, we were basically developing another complete fork while maintaining the original one.

**Comment by Aternus** [comment]
@ozh is there another platform where we can talk (hopefully also including other collaborators)?

I'd be happy to implement a new design and enable the mobile/responsive behavior but want to do a sync to define scope so that the code won't end up dead on arrival :D

**Comment by ozh** [comment]
We're only using Github to communicate :)

We're very open for a redesign. We've had a number of people proposing one before, but all we really got were mostly shiny mockups, very unique, while we need something reasonably implementable, easily hackable.

I'd say the first steps would be -- I'll let @LeoColomb and @dgw add to my list or modify it : 
- Make mockups using an established framework (I'm thinking Bootstrap or Tailwind) because we want something simple for CSS noobs and to make collaboration easy. Mockups would be needed at least for the main admin page and a stats page (eg https://app.yourls.org/fp+). If I had more time I'd certainly look at bootstrap and tailwind dashboard admin themes.
- Keep thing veeeeery simple. The simpler, the better : having to use React, or Vue.js, or stuff like this, is certainly cool for designers, but most people are not designers, and I'm certainly not one and don't have time to learn a new tool just to spit out a couple of CSS lines :)
- When mocking up, it would certainly help to have in mind what kind of code will generate each parts. Obviously changing the layout will require changing the code, but avoiding to modify all core would be cool -- certainly one of the key reasons why the 2.0 attempt went belly up.
- Be ready slow and patient. Before YOURLS we are super busy in our lives, and can take days to respond. Not being ready to be in sync with our natural pace might be a real turn down for some :)

**Comment by Aternus** [comment]
@ozh @LeoColomb @dgw 
Hey guys! 👋
Just to clarify, I'm a dev (not a designer) and can relate to the points mentioned.

# JTBD
The Job To Be Done the way I see it...

## Add a build pipeline
So we can easily develop using the new stuff (Tailwind, TypeScript, etc.) and it will automagically convert the "new" stuff to the "old" stuff old browsers can use (to ensure we don't break backwards compatibility). This will require having a package.json in the root of the project so we can use Node.js tooling for Frontend.

## Preserve the existing
After we have a working build pipeline we can convert the existing code to use the new stuff: JavaScript to TypeScript, "regular" CSS to Tailwind, etc.

## Componentize
Part of what makes good responsive web apps is the ability to use the best component for view (mobile/desktop).
The current "html functions" will need to be converted to "component functions" so we can create components that are flexible. Each "container" will serve as the base that defines available width and the CSS (with Tailwind classes) will take care to adjust the representation.

---

I also agree that we shouldn't push for a Frontend framework as the change will require a total rewrite of the core (forcing to expose everything via API for one) and has little benefit.

Regarding the design itself I think we can keep the current style with the required adjustments to make it responsive.
For example, if there is a line with two fields, they will break on mobile so each field is on a new line.

---

lmk what you think about the plan 🙏

**Comment by ozh** [comment]
Honestly : I have no idea what you're talking about, but I would hate having to use node.js to work on YOURLS

Thoughts, @LeoColomb ?

**Comment by Aternus** [comment]
@ozh I can't help but notice the similarity between WordPress and the way YOURLS is built, nowadays FE tooling is built with Node.js (JavaScript) so it's a natural direction to evolve into.

WP went way deeper on this with their tooling which is great for designers (as you've said it yourself) but I don't think we need to go so far with YOURLS.

**Comment by LeoColomb** [comment]
> Thoughts, [@LeoColomb](https://github.com/LeoColomb) ?

Apologies for the delayed reply.
First of all, thanks for the proposal, @Aternus.

I would recommend opening another issue for the general design discussion; it would help to keep things clean.

> nowadays FE tooling is built with Node.js (JavaScript) so it's a natural direction to evolve into.

Indeed, a JavaScript runtime is quite a requirement. Node.js is one of the options; others exist (Bun, Deno), but the workflow is kind of the same.

> I also agree that we shouldn't push for a Frontend framework as the change will require a total rewrite of the core (forcing to expose everything via API for one) and has little benefit.

The ideal implementation, in my opinion, would go with a fully static frontend filling data with API calls only. 
It doesn't have to be a SPA, but the concept is there: decouple the two parts so they can evolve at their pace. That would even help custom frontend developers.
Last but not least, that would also enable having the frontend in a separate repo, avoiding, for example, mixing Node.js with PHP.

**Comment by ozh** [comment]
As of now : people download the archive or git clone and they have it. How would "front end on another repo" work from a user POV ? Are we talking about "front end _dev_ on another repo" and compiled front end in the main repo ?

**Comment by ehthxC7x9D** [comment]
For what it's worth I would lose a lot of interest as soon as ```npm install ... ``` became involved.  NodeJS is not JavaScript.  One can exist without the other. I am not FE focused as a developer, but if it would influence even installing YOURLS I would just as soon use the API exclusively or find another alternative. 

Additionally Tailwind is neat, but would again have a preference for lowering dependencies.  Their standalone compiler (which is a requirement) can be included without the need to rely on NPM, which again, would be my preference to limit outside and unreliable dependencies.  Otherwise Bootstrap is so simple to version and include but not so new and shiny apparently.

**Comment by Aternus** [comment]
Hey guys, I did some prelimiary research and this looks like a direction we could go to:
https://github.com/Flynntes/Sleeky
@ozh  @LeoColomb 

It can be greatly simplified using modern CSS so the next question is, what kind of browser compatibility should we aim for?

**Comment by ozh** [comment]
Hello @Aternus, depends on what you have in mind. I've starting working on a theme API again, I will probably roll out something in the next few weeks.

If you'd like to propose mockup pages with modern responsive HTML & CSS : Sleeky can be a start indeed, and regarding browser compat, I know nothing in the design area but it seems to me that nowadays everybody updates their browser without even knowing it, so I guess aiming at latest versions of major browsers ? As long as the design is light weight and simple.

If you're having in mind something that requires also some PHP work, then wait a bit

**Comment by Aternus** [comment]
@ozh https://github.com/Aternus/yourls-responsive-ui

I'm not next to the computer right now so It's not the latest version, but will be in a couple of hours

**Comment by Aternus** [comment]
Currently the main pain is the inability to adjust the generated html template. Is this what you want to develop? @ozh

**Comment by ozh** [comment]
Yes, I want things to be completely customizable

**Comment by Aternus** [comment]
@ozh I suggest we go the API route and create endpoints to handle the functionality and a demo theme for people to start from using React/Vue.

Laravel went that route and it paid off big time with community contribution.

**Comment by Aternus** [comment]
@ozh  @LeoColomb I've updated the repo with the latest progress so you can see the direction I'm going with, lmk what you think 🙏

https://github.com/Aternus/yourls-responsive-ui

If you want to try it out you'll need to build the assets by running `npm run build` from the project root (after copying/cloning the project).

**Comment by ozh** [comment]
Node fresh install on my machine, `node --version` is `Node.js v24.12.0`, `npm --version` is `TypeError: Class extends value undefined is not a constructor or null`. This basically sums up my experience with node so I won't investigate further, I hate this tool and JS with passion ¯\\\_(ツ)_/¯

So, I have no opinion on the work right now, but in the end I'm looking for user themes that are simple to use and don't require building stuff with node or other stuff. YOURLS, plugins, and eventually theme, have to work the same way : download a zip or clone a repo, done. A massive share of users are using shared hosting where nodejs is not common.

**Comment by ehthxC7x9D** [comment]
> Node fresh install on my machine, `node --version` is `Node.js v24.12.0`, `npm --version` is `TypeError: Class extends value undefined is not a constructor or null`. This basically sums up my experience with node so I won't investigate further, I hate this tool and JS with passion ¯\_(ツ)_/¯
> 
> So, I have no opinion on the work right now, but in the end I'm looking for user themes that are simple to use and don't require building stuff with node or other stuff. YOURLS, plugins, and eventually theme, have to work the same way : download a zip or clone a repo, done. A massive share of users are using shared hosting where nodejs is not common.

thank god.

**Comment by LeoColomb** [comment]
Please see https://github.com/YOURLS/YOURLS/issues/4045 to continue the discussion on @Aternus contriibution.
