### ISSUE TITLE
After logout there stand: Erfolgreich eingelogt

### ISSUE THREAD

**Issue by Dtrieb** [YOURLS/YOURLS#2697]
If you logout, there stand: "**Erfolgreich eingelogt**" 

But it had to be: "Erfolgreich **aus**gelog**g**t"

![chrome_2020-05-24_12-29-12](https://user-images.githubusercontent.com/3650284/82751841-61e38500-9dba-11ea-8c90-0383e7b9f065.png)

**Comment by ozh** [comment]
If I understand correctly your issue : this is a translation issue. Please refer to the translator(s) : https://github.com/YOURLS/awesome-yourls#translations
