### ISSUE TITLE
Dynamic links/ prefix based link/ group link

### ISSUE THREAD

**Issue by payam124** [YOURLS/YOURLS#2702]
**Summary**
I really can't come up with an exact name for this feature. But assume you would like to have a link shortener with per/user or per/group tracking feature.
Let me share an example in the most simple way I can
Assume you have created a landing page and you have created a link like https://my.shortener/promo
Assume you have a million users and you can share private links with each of them. If you want to track users have clicked the link, an idea could be having links like:
https://my.shortener/promo{CustsomerID}
https://my.shortener/promo{\d+}
https://my.shortener/promo11111
and the system decides based on /^promo/ and redirect the 

I have implemented a simple PHP that is capable of doing that. but it only redirects. I went through all the plugins and did not found anything close to that. 

I wonder to know if by design anything for such capability has been put in the code.
I'm also considering contributing to the project. but I would like to hear first from experienced contributions.

**Comment by ozh** [comment]
Out of the box you cannot achieve this specific need, but for this very reason there is a plugin API which can do [pretty much anything](https://github.com/YOURLS/awesome-yourls) 

Having http://sho.rt/something{\d+} redirect to http://sho.rt/something (and tracking which user clicks, I guess) is something doable with a plugin
 
See https://github.com/YOURLS/YOURLS/wiki/Possible-With-A-Plugin for more
