### ISSUE TITLE
Add sign up and login feature

### ISSUE THREAD

**Issue by injoon5** [YOURLS/YOURLS#2703]
* [x] I've read the [guidelines for Contributing to YOURLS Projects](https://github.com/YOURLS/.github/blob/master/CONTRIBUTING.md)
* [X] This request isn't a duplicate of an existing request
* [x] This is not a personal support request that should be posted on the [YOURLS Discourse](https://discourse.yourls.org/) community

**Summary**
A feature that adds sign up and login feature so that they can manage there links.

**Motivation**
I want to make a bit.ly my self.
**Is your feature request related to a problem? Please describe.**
 I can't make/activate/install a sign up/login feature

**Describe the solution you'd like**
I want a sign up/log in feature and a user dashboard(only editing links that the user made.)

**Describe alternatives you've considered**
Another url shortner(Polr?)
**Additional context**

**Comment by ozh** [comment]
You mean a [multi user plugin](https://github.com/YOURLS/awesome-yourls#m)?
