### ISSUE TITLE
Option to always remove https:// prefix

### ISSUE THREAD

**Issue by Avrantinis** [YOURLS/YOURLS#2704]
Hi there, thanks for sharing this great app.
Didn't find anyone asking this or an option.
Just think, it would be useful to have the option to always remove the prefix "https://" on the administration panel, as the short links are working perfect without it. One click copy.
Regards!

**Comment by ozh** [comment]
I don't understand what you are suggesting or asking

**Comment by Avrantinis** [comment]
Example:
1. Original link:
https://mydomain/instalation/this _is_a_really_very_very_long_link_name
2. Yourls shortened link:
https://mydomain/instalation/name
3. What Im asking for:
mydomain/instalation/name
Thanks

**Comment by ozh** [comment]
If for whatever personal reason, which may be very valid, you need to remove "https://" from the generated short URL, you will need a custom plugin.

This is exactly why there is a plugin API : to allow users to make YOURLS work the way they want. See https://github.com/YOURLS/YOURLS/wiki/Possible-With-A-Plugin
