### ISSUE TITLE
Upgrading to 1.7.9 doesnt show the list

### ISSUE THREAD

**Issue by pixartmx** [YOURLS/YOURLS#2709]
i upgrade from 1.7.6 to 1.7.9 and the system open with the heather but doesn't show the list of shortlinks.

i try uploading the 1.7.9 with the old config.file and also replacing everything and is the same, how can i solve it

**Comment by ozh** [comment]
@dgw  🤣 
You're nicer than me: recent issues with vague questions and no issue template got directly deleted without comment.

@pixartmx without detail we just cannot answer.

**Comment by ozh** [comment]
It just occurred to me that there was right on the README a direct link to create blank issues. Doh.

@pixartmx In case you came from that link, please read this https://github.com/YOURLS/.github/blob/master/CONTRIBUTING.md and submit a new proper issue (using the adequate issue template that will pre-fill your issue)

**Comment by pixartmx** [comment]
Here are screen shot from version 176 that are ok and from 179 that doesn’t show the information

 

Im new with this that is why im asking for help

 

Regards

**Comment by dgw** [comment]
@ozh I figure deleting without telling the user why just invites more of the same.

@pixartmx Screenshots don't tell us anything relevant to troubleshooting. Start here, maybe: https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps

**Comment by pixartmx** [comment]
my php is 7.1.33
Here is the error log
[error_log.txt](https://github.com/YOURLS/YOURLS/files/4756173/error_log.txt)

**Comment by dgw** [comment]
Sounds kinda like #2661; have a look at [the workaround](https://github.com/YOURLS/YOURLS/issues/2661#issuecomment-619044362).
