### ISSUE TITLE
Click count is not same as Stats page

### ISSUE THREAD

**Issue by sathish1981** [YOURLS/YOURLS#2711]
My admin interface click counts is not getting matched with Stats page, 

For example short link keyword as "mylink" which  displayed 25 clicks in Admin interface but when i click on stats page its shows as 19 with all date information.

I checked in the back end DB logs table and found only 19 entries there.  But not sure how it got displayed in the main admin interface as 25?

Do you have any idea, how the extra 6 got added up in the main dashboard?

Note : This is occurring randomly and I couldn't find similarities. Its happens with Random keyword, custom keyword,etc... Also this is NOT happening for all short links and the no of clicks difference is also vary from different keywords

**Comment by ozh** [comment]
This is easy to reproduce: create a link, get some click, rename the link. The DB schema for the stats is dumb. It will improve some day.
