### ISSUE TITLE
Missing function for 2 "share" buttons

### ISSUE THREAD

**Issue by Ralf-AM** [YOURLS/YOURLS#2715]
*Please see the attached screenshot* 

The email and whatsapp button work as intended if you click on the "Share" icon for an entry in the URL list, but not if you click on the "Statistics" icon and try to use these buttons at the "Sharing" tab.

![Screenshot 001#  2020-06-17](https://user-images.githubusercontent.com/1440458/84849678-2bfe8d00-b056-11ea-9adb-b020a67b4746.png)

**Comment by ozh** [comment]
That's not a YOURLS feature, this is probably a plugin
