### ISSUE TITLE
Some suggestions and a wrong line break (admin page)

### ISSUE THREAD

**Issue by Ralf-AM** [YOURLS/YOURLS#2716]
*Please see the attached screenshot*

![Screenshot 002#  2020-06-17](https://user-images.githubusercontent.com/1440458/84851171-d926d480-b059-11ea-8cc2-61a27a2921d5.png)

**Comment by ozh** [comment]
All the "should" are personal preferences. It will be customizable with a future Theming API.
The line break depends on the translation but anyway the search box should indeed be prettier and more consistent. This will happen when the whole interface is revamped.
