### ISSUE TITLE
Use full page width on admin tools page

### ISSUE THREAD

**Issue by Ralf-AM** [YOURLS/YOURLS#2717]
*Please see the attached screenshot*

![Screenshot 003#  2020-06-17](https://user-images.githubusercontent.com/1440458/84853258-0b870080-b05f-11ea-94d5-7922e18f85e1.jpg)

**Comment by ozh** [comment]
Right now YOURLS interface is quite old and needs a complete revamping. Theming is a future feature. See #1234
