### ISSUE TITLE
After clicking "edit" icon only gray boxes instead of colored icons

### ISSUE THREAD

**Issue by Ralf-AM** [YOURLS/YOURLS#2718]
*Please see the attached screenshot*

I tested with chrome (v 83.0.4103.106 /64bit) and also with firefox (v77.0.1 / 64-Bit)

![Screenshot 004#  2020-06-17](https://user-images.githubusercontent.com/1440458/84853336-438e4380-b05f-11ea-8513-0dd0a1ce21a4.png)

**Comment by ozh** [comment]
Intended behavior. If you enter Edit mode, you cannot edit or delete or share or whatever until you've completed the edition.
