### ISSUE TITLE
Table prefix cannot contain all valid characters

### ISSUE THREAD

**Issue by tix0815** [YOURLS/YOURLS#2720]
**Description**
Fresh install fails with:

_Fatal error: Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-jetzt_options WHERE option_name = 'version' LIMIT 1' at line 1 in /homepages/26/d37193617/htdocs/my-site/includes/vendor/aura/sql/src/ExtendedPdo.php:748 Stack trace: #0 /homepages/26/d37193617/htdocs/my-site/includes/vendor/aura/sql/src/ExtendedPdo.php(748): PDOStatement->execute() #1 /homepages/26/d37193617/htdocs/my-site/includes/vendor/aura/sql/src/ExtendedPdo.php(545): Aura\Sql\ExtendedPdo->perform('SELECT option_v...', Array) #2 /homepages/26/d37193617/htdocs/my-site/includes/Database/Options.php(110): Aura\Sql\ExtendedPdo->fetchOne('SELECT option_v...', Array) #3 /homepages/26/d37193617/htdocs/my-site/includes/functions.php(1140): YOURLS\Database\Options->get('version', false) #4 /homepages/26/d37193617/htdocs/my-site/includes/Database/Options.php(150): yourls_get_opt in /homepages/26/d37193617/htdocs/my-site/includes/vendor/aura/sql/src/ExtendedPdo.php on line 748_

The db has been prepared with proper charset and collation (utf8/utf8_unicode_ci) as I have read from other errors regarding length of statements with multibyte character sets.

**To Reproduce**
Go to my-dite/admin and press Install button.

**Expected behavior**
Full install w/o errors

**Actual behavior**
Throws exception as above but has created 3 tables: *_log, *_options and *_url

**Versions**
Running PHP7.4 (also tried 7.3 and 7.2) and mysql5.7 (also tried 5.5) on Linux/Apache.

**Additional context**
Manually added the .htaccess as described but don't think it matters. It seems to bee som sort of compatibility issue or some configuration that is needed by YOURLS is missing without warning?

**Comment by dgw** [comment]
Looks like the query here:
https://github.com/YOURLS/YOURLS/blob/84c48cd58a3e6e43602454c0dad1d8ece420ab9c/includes/Database/Options.php#L105

What's the database prefix? `-jetzt_options` (or anything containing characters other than [A-Za-z0-9_]) is an invalid table name if not quoted, AFAIK.

@ozh Queries using a placeholder like `$table` probably should quote it with backticks though, or document (and validate) that the table prefix must contain only the allowed characters above.

**Comment by tix0815** [comment]
the prefix is "my-site_" - that SHOULD be ok? I will try something else to check whether this could be it...

**Comment by tix0815** [comment]
Ok, good idea: prefixes containing "-" will fail in queries, even though you can create such tables flawlessly. the "_" is no problem, I tested it... Thanx a lot for the idea, frustration level was already slightly increased last night ;)) I think this should b documentedd in the config-sample and/or fixed by escaping such stuff?

**Comment by ozh** [comment]
This is surprising. Will check.

**Comment by ozh** [comment]
So, turns out it's exactly what @dgw said, I didn't know that.
* `[A-Za-z0-9_$]` is allowed (let's take the `$` out for the sake of clarity)
* All chars (except backtick) are allowed if names (tables, columns) are quoted within backtick characters

A fix would then be to add backticks in every query. The thing is, backticks are a MySQL stuff, so this would make it harder for people wanting to work on a pgsql port or to make YOURLS 100% pgsql compatible out of the box. See https://github.com/YOURLS/YOURLS/issues/2239#issuecomment-488309976

So, I'll just add a comment to make this clear in the config sample and docs.

**Comment by tix0815** [comment]
Thanx, brilliant response times!
