### ISSUE TITLE
Service deleted some QueryString on the url

### ISSUE THREAD

**Issue by cgtv** [YOURLS/YOURLS#2722]
For example, if you store this url by **API**
https://www.arvandkala.org/%d9%be%d8%b1%d8%af%d8%a7%d8%ae%d8%aa/order-pay/326089/?pay_for_order=true&key=wc_order_18Sbh4A18GUvJ

The query string "&key=wc_order_18Sbh4A18GUvJ" is removed by service and converted to:
https://www.arvandkala.org/%d9%be%d8%b1%d8%af%d8%a7%d8%ae%d8%aa/order-pay/326089/?pay_for_order=true

And here is the example created with yours api service:
http://arvd.link/o

**Comment by ozh** [comment]
As stated in the doc, you need to properly escape the URL when using the API
