### ISSUE TITLE
Feature Request: Multi Select Editing and/or Find & Replace

### ISSUE THREAD

**Issue by BurtThaMan** [YOURLS/YOURLS#2723]
First off, thank you so much for all the time you've put into this.

I use YOURLS to shorten links obviously, but mostly to insert tracking into the link as well. With video and other content creation on the rise, we need more and more links to track individual posts, videos, etc. Now that YOURLS has built in functionality for randomized keywords it's even easier to create individual URLs with specific tracking for each piece of content. 

What I'm worried about, is that I have a lot of links going to a specific landing page. In the future I may want those links to go to a different landing page. It would be really nice if I could select multiple links and edit just the domain/path and not the url parameters. 

As for coding, the hard way would be to create multiple entries for each part of a URL (like FB Ads and GAds do) so that each piece of the url would have it's own data. What seems easier to me would be a "simple" find and replace of text for the "original url" data. This eliminates the need for multiple entries per URL and eliminates the need to build some sort of multi-selection checkbox editing tool. 

Obviously there is nothing simple or easy about what I'm suggesting, I was just using those terms in relativity to the other option. Again, I thank you for all that you do.

P.S.
The only past item I could find on this was closed in 2013 and it said to read the comments, except there were none and the link to the old post is just a loopback to the current post.

**Comment by ozh** [comment]
This is a very specific need, there won't be such a feature implemented in YOURLS, that's what the plugin API is for (see https://github.com/YOURLS/YOURLS/wiki/Possible-With-A-Plugin)

Without a specific plugin, the easiest way would be to simply edit your URLs in phpmyadmin or similar tool (ie mysql search and replace)

**Comment by BurtThaMan** [comment]
Thank you for your reply and for the tip on using phpmyadmin/mysql. That's very helpful. To me it seemed like a core feature that most software I've used have rather than a plugin addon. However, I do appreciate your response, and I'll check out that link.
