### ISSUE TITLE
Clicks count discrepancy on Stats page vs main screen

### ISSUE THREAD

**Issue by sathish1981** [YOURLS/YOURLS#2725]
@ozh 
The request regrading the discrepancy of click count between Stats page and the main page. 

Is there any easy way to replace the stats count logic to main screen table? 

Say like, can we replace the same sql logic written for stats page click calculation to Main page? 

Please suggest and advice a way to achieve this

**Comment by dgw** [comment]
Ref: https://github.com/YOURLS/YOURLS/issues/2711#issuecomment-642933349

**Comment by ozh** [comment]
Closing as duplicate
