### ISSUE TITLE
branch master with only release commits

### ISSUE THREAD

**Issue by drbeco** [YOURLS/YOURLS#2726]
It is more like a security policy or a bug report, but feature request will do.

Please, consider creating a git branch develop and move the develop to there; 

only commit to `master` when it is going to be a `tag` release.

That way, we can use git to update the software, instead of downloading the last release.
(right now, I'm still doing it, but since it risks to download a "in-between release" `pull`, I need to be extra-care).

Another option is to create a new branch `release` and keep `master` in the workflow as it is now, but it is not the best practice anyway.

Thanks a lot for considering it.

**Comment by dgw** [comment]
Why not check out the most recent tag? https://stackoverflow.com/q/17414104/5991

**Comment by drbeco** [comment]
> Why not check out the most recent tag? https://stackoverflow.com/q/17414104/5991

That is what I'm doing (minus the script, thanks):

>  (right now, I'm still doing it, but since it risks to download a "in-between release" pull, I need to be extra-care).

But when you deal with a lot of repos, it is good when we follow best practices instead of relying on scripts or memory. The master branch should be the production branch -- ready for use by anyone with less knowledge -- not the development branch.

But ok, just a suggestion. If you guys still think it is not worth, I'm ok with that. In this case we close the issue.

Thanks for considering it though.

**Comment by dgw** [comment]
"[A]nyone with less knowledge" should be downloading tagged releases, not pulling master. There's a "latest" alias for the most recent stable release.

Per the readme, the YOURLS project officially supports installing only the released archives and Composer tags. There's no warranty for the contents of any branch, whether it's named "master" or "production", etc. (Well, technically there's no warranty on any of it, but you know what I mean!)

I've personally never worked on a project where "master" wasn't the development branch. You might be able to convince @ozh that we should make a "stable" (or whatever) branch that's always an alias for the last release, but I (speaking as myself) think it's unreasonable to expect all repos you ever interact with to confirm to your idea of how branches should be set up. The diversity of workflows is one of the things I love about open source!

**Comment by LeoColomb** [comment]
@dgw is 100% right. Official releases can be downloaded from the release page https://github.com/yourls/yourls/releases

Other ways are at your own risk! 🙂
