### ISSUE TITLE
Chanigng Yourls URL?

### ISSUE THREAD

**Issue by Freaky2003** [YOURLS/YOURLS#2728]
Hey Guys,
I have a question.
I have to domain names.
Linkcarrot.cc and Lnk.cc
Now I want Lincarrot.cc for the Piblic Interface and lnk.cc for the shorten link (i.e. lnk.cc/12345).

How I want to do this?
I use the sleeky theme which allows itself to set a custom URL for the frontend.

The problem is, I started installing Yourls on linkcarrot.cc and if I change the link in the config.php (for yourls itself), the backend doesent work anymore...

What do I do wrong?

Cheers

**Comment by ozh** [comment]
I would do it the other way. Install YOURLS on lnk.cc, and make a public interface on linkcarrot.cc to submit links to lnk.cc via the API.
This sample file https://github.com/YOURLS/YOURLS/blob/master/sample-remote-api-call.txt would be a good starter

**Comment by ozh** [comment]
See also https://github.com/YOURLS/YOURLS/wiki/PasswordlessAPI

**Comment by Freaky2003** [comment]
@ozh but for the public interface (with sleeky) I need to install another instance of yours on linkcarrot.cc, right?

**Comment by Freaky2003** [comment]
and could you help me doing this? Im kinda new to this xD

Cheers

**Comment by ozh** [comment]
I cannot "help" you, as I cannot help everyone running YOURLS with specific needs. If you have a budget for this, see https://github.com/YOURLS/YOURLS/wiki/Possible-With-A-Plugin#find-a-plugin-coder
