### ISSUE TITLE
Backend for normal users/login for normal users

### ISSUE THREAD

**Issue by Freaky2003** [YOURLS/YOURLS#2730]
Hey,
Is it possible to let people register and login on my site and than having a sort of backend, where they can shorten links view stats and have they link saved (as it is on bitly)?
So something like a backend but without admin rights.

Would it work with the Sleeky theme?

Cheers

**Comment by ozh** [comment]
"Is it possible"? Yes: see https://github.com/YOURLS/YOURLS/wiki/Possible-With-A-Plugin.

See also https://github.com/YOURLS/awesome-yourls regarding user roles or multi users, if anything exists.
