### ISSUE TITLE
Error 500 on install.php (Turnkey LAMP VMWARE compliance)

### ISSUE THREAD

**Issue by RodolfoEBDR** [YOURLS/YOURLS#2734]
Hi! I'm trying to install YOURLS on a clean Turnkey LAMP VM. Everything seems right at first glance, the install splash displays OK, but then, after clicking "Install" button, it goes to nothing. Error 500 on install.php.

.htaccess and sites-available are just like the guides round here (I've tried several combinations), MariaDB is working (I've created the DB manually using defaults settings), and user/config file is OK.

The only traceable log is from Apache2 (error.log):

[Wed Jul 29 19:57:51.843213 2020] [:error] [pid 21779] [client 192.168.100.49:16304] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'yourls179.y_options' doesn't exist in /var/www/yourls/includes/vendor/aura/sql/src/ExtendedPdo.php:748\nStack trace:\n#0 /var/www/yourls/includes/vendor/aura/sql/src/ExtendedPdo.php(748): PDOStatement->execute()\n#1 /var/www/yourls/includes/vendor/aura/sql/src/ExtendedPdo.php(545): Aura\\Sql\\ExtendedPdo->perform('SELECT option_v...', Array)\n#2 /var/www/yourls/includes/Database/Options.php(110): Aura\\Sql\\ExtendedPdo->fetchOne('SELECT option_v...', Array)\n#3 /var/www/yourls/includes/functions.php(1140): YOURLS\\Database\\Options->get('version', false)\n#4 /var/www/yourls/includes/functions.php(1110): yourls_get_option('version')\n#5 /var/www/yourls/includes/functions.php(1094): yourls_get_current_version_from_sql()\n#6 /var/www/yourls/includes/Config/Init.php(94): yourls_upgrade_is_needed()\n#7 /var/www/yourls/includes/load-yourls.php(26): YOURLS\\Config\\Init->__construct(Object(YOURLS\\Config\\InitDefaults))\n#8 /var/www/yourls/admin/index.php in /var/www/yourls/includes/vendor/aura/sql/src/ExtendedPdo.php on line 748

[Wed Jul 29 19:59:01.158764 2020] [:error] [pid 21792] [client 192.168.100.49:16387] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes in /var/www/yourls/includes/vendor/aura/sql/src/ExtendedPdo.php:748\nStack trace:\n#0 /var/www/yourls/includes/vendor/aura/sql/src/ExtendedPdo.php(748): PDOStatement->execute()\n#1 /var/www/yourls/includes/functions-install.php(252): Aura\\Sql\\ExtendedPdo->perform('CREATE TABLE IF...')\n#2 /var/www/yourls/admin/install.php(46): yourls_create_sql_tables()\n#3 {main}\n  thrown in /var/www/yourls/includes/vendor/aura/sql/src/ExtendedPdo.php on line 748, referer: http://192.168.0.154/admin/install.php

Is this a particular issue with TK OVFs? Or there's something I'm missing? I'm sorry if this is in the wrong place. Thank you!

**Comment by dgw** [comment]
You can follow the links from #2307 and #2226 to prior coverage of this issue. It's easily remedied by a MySQL/MariaDB configuration change.
