### ISSUE TITLE
cdn.topsy.com currently does not have DNS set up.

### ISSUE THREAD

**Issue by JoshFialkoff** [YOURLS/YOURLS#2736]
I'm getting this response when I try to access yourls on my server:

I'm seeing that the site is trying to load a resoruce http://cdn.topsy.com/topsy.js.

cdn.topsy.com currently does not have DNS set up.  It looks like this may be a resource your applications needs that is pulling from an external resource. 

Do you want to ask a question? Are you looking for support? YOURLS Discourse is the best place for getting support: https://discourse.yourls.org/

**PLEASE NOTE** : if you file and issue without using this template, and your issue doesn't provide enough information, it will be deleted without notice or question asked.

-->

* [ ] I've read the [Troubleshooting First Steps](https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps)
Yes

* [ ] This request isn't a duplicate of an existing issue, opened or closed

Correct 

* [ ] I've read the [docs](https://yourls.org/) and followed them (if applicable)

Yes

* [ ] This is not a personal support request that should be posted on the [YOURLS Discourse](https://discourse.yourls.org/) community

Yes

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior. This is mandatory if you expect someone to fix the problem. Example:

I'm seeing that the site is trying to load a resoruce http://cdn.topsy.com/topsy.js.

cdn.topsy.com currently does not have DNS set up.  It looks like this may be a resource your applications needs that is pulling from an external resource. 

**Expected behavior**

**Actual behavior**
What actually happens.

**Screenshots**

**Versions**
You can get this information from referencing `CHANGELOG.md` or the releases page.
Also, please include:
* The OS and what version of the OS you're running.
* Plugins or extensions activated if applicable.

**Additional context**
Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by dgw** [comment]
One of the (old) sample plugins does: https://github.com/YOURLS/YOURLS/blob/6228a2874e532002286e99ecb364efb4eaa573fb/user/plugins/sample-toolbar/plugin.php#L118 But no core functionality needs it.

**Comment by ozh** [comment]
Huh, nice catch @dgw. Probably time to update or remove that sample plugin.

By the way this issue barely makes sense. Amazing how people seem unable to follow braindead guidelines.
