### ISSUE TITLE
Install Gives White Screen Due to SQL Error

### ISSUE THREAD

**Issue by Carbon8Jim** [YOURLS/YOURLS#2740]
* [X] I've read the [Troubleshooting First Steps](https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps)
* [X] This request isn't a duplicate of an existing issue, opened or closed
* [X] I've read the [docs](https://yourls.org/) and followed them (if applicable)
* [X] This is not a personal support request that should be posted on the [YOURLS Discourse](https://discourse.yourls.org/) community

**Describe the bug**
While installing the 1.7.9 version from a clean install, I get a white screen (500 Error). It turns out to be a SQL error in the create of the options table

**To Reproduce**
Steps to reproduce the behavior. This is mandatory if you expect someone to fix the problem. Example:
1. Go to '/admin/install.php'
2. Click on 'install'

**Expected behavior**
I expected the db tables to be created and the installation to complete

**Actual behavior**
500 Error. (white screen)

**Versions**
You can get this information from referencing `CHANGELOG.md` or the releases page.
Also, please include:
* Ubuntu 20.0.4 LTS and PHP 7.4.

**Resolution**
File: includes/functions-install.php
Line: 223 (first line of statement)
Error Syntax: '`option_name` varchar(64) NOT NULL default "",'.
Error Reason: SQL does not permit double quotes for strings
Correct Syntax: '`option_name` varchar(64) NOT NULL default \\'\\','.

**Comment by dgw** [comment]
Hmm, that line has been the same since v1.4:
https://github.com/YOURLS/YOURLS/blob/8f6fabba4b17ecf3fda12bef12a879fa459b8cef/includes/functions-install.php#L156

Are you using a database server that enforces the ANSI standard? MySQL and MariaDB both should allow double-quoted strings by default, if my quick google-fu is correct.

**Comment by RiversideRocks** [comment]
I am getting this issue to.

![](https://cloud.riverside.rocks/index.php/s/xyBjng9NMQWCNpm/preview)

**Comment by dgw** [comment]
@RiversideRocks No details makes it impossible to say whether you are truly having the same issue or a different one (even if the symptom is identical).

**Comment by RiversideRocks** [comment]
Hello @dgw,

Very sorry! Here is my server log:

```
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'yourls.yourls_options' doesn't exist in /var/www/url/yourls/includes/vendor/aura/sql/src/ExtendedPdo.php:748\nStack trace:\n#0 /var/www/url/yourls/includes/vendor/aura/sql/src/ExtendedPdo.php(748): PDOStatement->execute()\n#1 /var/www/url/yourls/includes/vendor/aura/sql/src/ExtendedPdo.php(545): Aura\\Sql\\ExtendedPdo->perform('SELECT option_v...', Array)\n#2 /var/www/url/yourls/includes/Database/Options.php(110): Aura\\Sql\\ExtendedPdo->fetchOne('SELECT option_v...', Array)\n#3 /var/www/url/yourls/includes/functions.php(1140): YOURLS\\Database\\Options->get('version', false)\n#4 /var/www/url/yourls/includes/functions.php(1110): yourls_get_option('version')\n#5 /var/www/url/yourls/includes/functions.php(1094): yourls_get_current_version_from_sql()\n#6 /var/www/url/yourls/includes/Config/Init.php(94): yourls_upgrade_is_needed()\n#7 /var/www/url/yourls/includes/load-yourls.php(26): YOURLS\\Config\\Init->__construct(Object(YOURLS\\Config\\InitDefault in /var/www/url/yourls/includes/vendor/aura/sql/src/ExtendedPdo.php on line 748
```

I am running this on Debian 10 and PHP 7.3

**Comment by dgw** [comment]
@RiversideRocks Different error than OP. Can't imagine how the installer would progress to something that needs to access the table without creating it first. Surely this would have been mentioned already hundreds of times in older issues? Anyway, you should make a new issue of your own with more details including your DB server version (MySQL, MariaDB).

**Comment by RiversideRocks** [comment]
Done:
https://github.com/YOURLS/YOURLS/issues/2751

**Comment by ozh** [comment]
If I understand correctly and [according to the doc](https://mariadb.com/kb/en/string-literals/):
> The ANSI SQL-standard does not permit double quotes for enclosing strings, although MariaDB does by default

If config is not default, it seems like the `ANSI_QUOTES_SQL SQL_MODE` is the solution.

So I'd rather leave this untouched. As @dgw said, this SQL line has been around for like 10 year and dozens of thousands of YOURLS setups have been installed successfully with this code.
