### ISSUE TITLE
Cross Site Scripting Vulnerability on results.php page

### ISSUE THREAD

**Issue by tuf08694** [YOURLS/YOURLS#2745]
Hello I just had a security assessment done on a instance of YOURLS v 1.7.9. and the results sow that there are Cross Site Scripting Vulnerabilities on the results.php page.

**Comment by dgw** [comment]
But you're not sharing any details? OK…

**Comment by ozh** [comment]
Hello, two things:
- there is no `result.php` in YOURLS, not sure what you mean
- See https://github.com/YOURLS/YOURLS/security/policy

Thanks
