### ISSUE TITLE
Install Yourls inside wordpress site

### ISSUE THREAD

**Issue by psteam89** [YOURLS/YOURLS#2749]
Hi, please help me to resolve this error: I must install YOURLS inside my wordpress site.
My site: mydomain.com
My yourls site: mydomain.com/p/admin
The shorten link like: mydomain.com/p/test 
But it 's not work because of mod_rewrite of my wordpress site. I tried to add some solution to .htaccess file but not working.
Please help me! Thanks!

**Comment by psteam89** [comment]
I need help. Please help me :(

**Comment by psteam89** [comment]
@ozh why close this thread without solution?

**Comment by ozh** [comment]
Because, as indicated above, the issue template is not a suggestion. What help do you expect when the only input you give is "I tried to add some solution to .htaccess". See https://github.com/YOURLS/.github/blob/master/CONTRIBUTING.md
