### ISSUE TITLE
caps

### ISSUE THREAD

**Issue by fakeologist** [YOURLS/YOURLS#2752]
If I use a custom shortener with CAPS in the url, the shortener can't find it, and gives me a denied error.
If I try and add the same short with CAPS in yourls, it says it's a duplicate.
Please advise.

**Comment by dgw** [comment]
I have no idea what this means.

**Comment by fakeologist** [comment]
yourls/ABC does not equal yourls/abc
if you try and add both to the database it sees them as the same.

**Comment by dgw** [comment]
Default value of `YOURLS_URL_CONVERT` setting (36) uses lowercase letters only, yes. You can change it to allow uppercase too (62), but I cannot guarantee that existing links will behave as expected. They _should_, but changing the setting on a site with links already stored is technically unsupported so you do so at your own risk. I recommend backing up your links before changing that setting.

**Comment by fakeologist** [comment]
I will leave it as is. Just wanted a clarification as most urls I use don't see upper and lowercase or convert them all to lower so they can be found. I'll tell everyone I pass the yourls links to to use lower case. Thanks.
