### ISSUE TITLE
Incorrect DB config, or could not connect to DB / PDOException: SQLSTATE[HY000] [2002] No such file or directory

### ISSUE THREAD

**Issue by user67x** [YOURLS/YOURLS#2753]
Hello,

* [X] I've read the [Troubleshooting First Steps](https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps)
* [X] This request isn't a duplicate of an existing issue, opened or closed
* [X] I've read the [docs](https://yourls.org/) and followed them (if applicable)
* [X] This is not a personal support request that should be posted on the [YOURLS Discourse](https://discourse.yourls.org/) community

**Describe the bug**

When I try to install Yourls (after completed config.php and create manually the DB, and download the fr_FR.mo  and fr_FR.po and put them in languages directory, I have this message when I try to install the script:

> Fatal error
> 
> Incorrect DB config, or could not connect to DB
> PDOException: SQLSTATE[HY000] [2002] No such file or directory
> 

I have switch the debug mode, but the message error is the same
define( 'YOURLS_DEBUG', true );

Thanks

//EDIT : oh, sure I can connect to phpMyAdmin with password and user to this database

**Comment by dgw** [comment]
Needs more logs. https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps#check-server-logs

As a guess, following the instructions [later in that troubleshooting wiki page](https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps#stfw-after-you-have-rtfm) you said you've read, I googled the error. Are you perchance [using `localhost`](https://stackoverflow.com/a/36264929/5991) as the DB server address?

**Comment by user67x** [comment]
Hello,

I have that in logs:

> [Thu Oct 01 10:52:49.908623 2020] [autoindex:error] [pid 15285:tid 140145395140352] [client 10.4.32.2:42356] AH01276: Cannot serve directory /home/clients/8b44057ae55374496743b90224a9/sites/domain.tld/: No matching DirectoryIndex (index.html,index.cgi,index.pl,index.php,index.xhtml,index.htm,index.php,index.php5,index.php4,index.php3,default.php,home.php,welcome.php) found, and server-generated directory index forbidden by Options directive

Yes, I use localhost

**Comment by dgw** [comment]
That log line looks unrelated.

Try other solutions on the question page I linked. This kind of troubleshooting is really outside the scope of YOURLS' issue tracker, so if you really can't figure it out I suggest starting a Discourse thread.

**Comment by user67x** [comment]
Ok, solved. I have use a automatic installation that my hoster gives.
