### ISSUE TITLE
Save in yourls_log the vhost that gets the traffic

### ISSUE THREAD

**Issue by juniorionut** [YOURLS/YOURLS#2757]
Hello,

* [x] I've read the [guidelines for Contributing to YOURLS Projects](https://github.com/YOURLS/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing request
* [x] This is not a personal support request that should be posted on the [YOURLS Discourse](https://discourse.yourls.org/) community

**Summary**
I consider that by adding a column inside the yourls_log table and saving the Apache VHost would allow to many of us to export and create better statistics.

**Motivation**
Better statistics.

**Is your feature request related to a problem? Please describe.**
No problem, just a feature request

**Describe the solution you'd like**
Modify the yourls_log_redirect function inside includes/function.php to save the vhost as well.

**Describe alternatives you've considered**
I can create a small plugin that will use the shunt_log_redirect filter to fix my case but maybe others will benefit from this also.

Thanks!

**Comment by ozh** [comment]
>  I can create a small plugin that will use the shunt_log_redirect filter to fix my case but maybe others will benefit from this also.

That's exactly the way to go :) Please write a plugin and [make it available](https://github.com/YOURLS/awesome-yourls) to others!
