### ISSUE TITLE
Admin Page BUG

### ISSUE THREAD

**Issue by McMelonTV** [YOURLS/YOURLS#2760]
* [x] I've read the [Troubleshooting First Steps](https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps)
* [x] This request isn't a duplicate of an existing issue, opened or closed
* [x] I've read the [docs](https://yourls.org/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [YOURLS Discourse](https://discourse.yourls.org/) community

**Describe the bug**
Chrome shows error on admin page after logging out

**To Reproduce**
1. Go to admin panel
2. Log Out
3. Try to log in or going in the admin panel

**Expected behavior**
I should be able to log in to the admin panel

**Actual behavior**
It actually shows an error

**Screenshots**

**Versions**
Version - 1.7.9
OS - Idk im running it on InfinityFree hosting
Plugins - advanced-reserverd-urls, hyphens-in-urls, public-pns

**Additional context**
Before i logged out of the admin panel, everything worked as intended

**Comment by McMelonTV** [comment]
nvm figured it out, i just set

 // if set to true, force https:// in the admin area
        if (!defined( 'YOURLS_ADMIN_SSL' ))
            define( 'YOURLS_ADMIN_SSL', false );

to false

**Comment by dgw** [comment]
Same as #2759
