### ISSUE TITLE
Time clicked on stat not match with current time

### ISSUE THREAD

**Issue by kyosuke100** [YOURLS/YOURLS#2765]
* [x] I've read the [Troubleshooting First Steps](https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps)
* [x] This request isn't a duplicate of an existing issue, opened or closed
* [ ] I've read the [docs](https://yourls.org/) and followed them (if applicable)
* [ ] This is not a personal support request that should be posted on the [YOURLS Discourse](https://discourse.yourls.org/) community

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior. This is mandatory if you expect someone to fix the problem. Example:

**Expected behavior**

**Actual behavior**
What actually happens.

**Screenshots**

**Versions**
You can get this information from referencing `CHANGELOG.md` or the releases page.
Also, please include:
* The OS and what version of the OS you're running.
* Plugins or extensions activated if applicable.

**Additional context**
Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by dgw** [comment]
I have no idea what this issue is about.

**Comment by kyosuke100** [comment]
> I have no idea what this issue is about.

Thank you for your comment. :)

**Comment by dgw** [comment]
The issue template is still empty…

**Comment by kyosuke100** [comment]
what is template?

ดาวน์โหลด Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by dgw** [comment]
All that text in the top comment that you didn't fill in.

**Comment by kyosuke100** [comment]
> All that text in the top comment that you didn't fill in.
I edited issue by filling information. Are they corrently?

**Comment by dgw** [comment]
Oh, I think I understand now. Sounds like you're seeing the difference between your local time and UTC. 1.7.10 plus a plugin should help; check out #2684. :smile_cat:

**Comment by kyosuke100** [comment]
> Oh, I think I understand now. Sounds like you're seeing the difference between your local time and UTC. 1.7.10 or 1.8 (whichever version number gets used) plus a plugin should help; check out #2684. 😸

Thank you very much, I will try as your suggestion.
