### ISSUE TITLE
DB upgrade to 1.7.10 not working (YOURLS_UNIQUE = true, YOURLS_URL_CONVERT=62)

### ISSUE THREAD

**Issue by ArnaudFeld** [YOURLS/YOURLS#2766]
* [ x] I've read the [Troubleshooting First Steps](https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps)
* [ x] This request isn't a duplicate of an existing issue, opened or closed
* [ x] I've read the [docs](https://yourls.org/) and followed them (if applicable)
* [ x] This is not a personal support request that should be posted on the [YOURLS Discourse](https://discourse.yourls.org/) community

**Describe the bug**
When is try to upgrade my Installation from 1.7.6 to 1.7.9 is get the following message after is need to click for an Database Upgrade:

```
Upgrade YOURLS

Updating DB. Please wait...

Unable to update the DB.

You will have to manually fix things, sorry for the inconvenience :(

The errors were:

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'A' for key 'PRIMARY'
```

**To Reproduce**
Steps to reproduce the behavior. This is mandatory if you expect someone to fix the problem. Example:
1. made via CLI git pull
2. Reload yourls
3. Get Message that DB-Update is need

**Expected behavior**
Normally the Update show work

**Actual behavior**
nothing happens.. yourls does not work anymore

**Screenshots**

**Comment by ozh** [comment]
Seems like you have 2 short URLs with "A" as the key ?

**Comment by ArnaudFeld** [comment]
Do you mean only A? I have A and a in my Database (yourls_url).

**Comment by ArnaudFeld** [comment]
![7EC5C316-D6BD-41DE-8B3D-F3BDAD86ADC4](https://user-images.githubusercontent.com/1561416/96351591-badeed00-10bc-11eb-82c6-398dc2ab97d6.jpeg)

Need I also to change something here?

**Comment by ozh** [comment]
Do you have YOURLS_UNIQUE_URLS set to false ?

**Comment by ArnaudFeld** [comment]
![97D95F8A-E49B-4E3E-89C4-0B0236BE1E60](https://user-images.githubusercontent.com/1561416/96360641-2659a680-111f-11eb-8733-542b3cf69c4b.jpeg)

@ozh it is set to True

**Comment by ozh** [comment]
Ho OK. Indeed now I realize the upgrade process is not considering this case

**Comment by ozh** [comment]
@ArnaudFeld Will work on this issue. In the meantime you should update to 1.7.9 which should be stable.

**Comment by ArnaudFeld** [comment]
hey @ozh,

anything new about this bug?

**Comment by ozh** [comment]
@ArnaudFeld I think I have it fixed, check pull request 2840

**Comment by ArnaudFeld** [comment]
@ozh yes it works.. update works
