### ISSUE TITLE
I CAN'T GET THIS THING TO WORK. HELP PLEASE!!!!!

### ISSUE THREAD

**Issue by mandaharris** [YOURLS/YOURLS#2769]
I've been working on this for hours and I can't figure out why it's not working. I shorten the link and get a 404 error every time, and the short link won't redirect to my website. I'm so lost... :( Can somebody just call me and fix it? PLEASE!

**Comment by dgw** [comment]
Aside from missing issue template, this belongs on [the forums](https://discourse.yourls.org/).

**Comment by ozh** [comment]
And be aware that posting this kind of message will get you absolutely zero help, because there is zero detail. Maybe what you need is to pay someone who can install YOURLS for you.
