### ISSUE TITLE
Simple Bookmarklets and twice "https" trim problem

### ISSUE THREAD

**Issue by jaialai2002** [YOURLS/YOURLS#2773]
The simple Bookmarklets its a great feature but I find a problem when shortening certain URLs that contain twice "https".
A long URL as https://server.knosys.es/_sefarad_wp2/pdfjs/viewer/viewer.vm?src=https://server.knosys.es/sefarad_pdf/1918_Derecho_de_los_judios_de_Castilla.pdf is coded as https://server.knosys.es/_sefarad_wp2/pdfjs/viewer/viewer.vm?src= 

The simple Bookmarklets trims part of the URL to the start of the second "https"
Is there an easy fix?
Thanks,
Jaime

**Comment by ozh** [comment]
Yeah, known issue, see #1672, bookmarklets will fail when encountering multiple "http(s)://" 

The fix would be to use a custom bookmarklet as I describe in 1672

**Comment by ozh** [comment]
Although in your specific case, you can use a relative URL: https://server.knosys.es/_sefarad_wp2/pdfjs/viewer/viewer.vm?src=/sefarad_pdf/1918_Derecho_de_los_judios_de_Castilla.pdf seems to work fine

**Comment by jaialai2002** [comment]
Thank you very much. I imagine it would be a complicated bookmarklt. I will consider your second suggestion
