### ISSUE TITLE
Yourls are not shortening my url

### ISSUE THREAD

**Issue by esqualli** [YOURLS/YOURLS#2774]
Hi, i've installed recently yourls un my domain, all the installation process were fine but now when i want to short a url, the result doesn't work. Even if using the default way that creates the link randomly or using a the manual way to create it. The long url works fine, but the short url is trying to open the short url, it's not redirecting to the long url.

Long url: https://domain.es/servicios/?utm_medium=post&utm_source=linkedin
Short url: https://dom.es/servicios

And this short url shows a not found error.

Thanks in advance

**Comment by ozh** [comment]
https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps
