### ISSUE TITLE
No URLs listed in the Admin console

### ISSUE THREAD

**Issue by CMDZEE** [YOURLS/YOURLS#2775]
Just installed YOURLS. The install inserts 3 sample entries. I added one of my own for a total of four. However, no URLs show up in the Admin console. Confirmed that there are 4 entries in the database (more now, of course, with further testing).

Screenshot: [https://ibb.co/6NGnVdG](https://ibb.co/6NGnVdG)

Also, the "Shorten the URL" button eternally spins after submitting a new entry. A new entry is typically added to the database, but there's no indication in the Admin console and  I have to reload the page to add another entry (since the button is already "activated").

PHP 7.4.11
MySQL 5.6.47

Really excited about the possibilities for YOURLS!

**Comment by dgw** [comment]
[Endlessly spinning icon](https://github.com/YOURLS/YOURLS/wiki/Endless-Spinning-Icon)? [Basic troubleshooting](https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps), like [looking for logs](https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps#check-server-logs)?
