### ISSUE TITLE
Run yourls UI webpage at other than the shorten root

### ISSUE THREAD

**Issue by ifuchs** [YOURLS/YOURLS#2782]
I would like to run the YOURLS webpage at a url other than the base url for the shortened URLs. That is, my domain for shortened URLs is mydomain.tld, and I would like the YOURLS webpage to be accessed at another location (e.g. mydomain.tld/yourls or yourls.mydomain.tld). If this is already possible, could someone say how it is done?

**Comment by ozh** [comment]
It's all in the wiki https://github.com/YOURLS/YOURLS/wiki/Giving-YOURLS-its-own-directory
