### ISSUE TITLE
pdo connection fails before SSL plugin can add MYSQL_ATTR_SSL_CA

### ISSUE THREAD

**Issue by RileyDeLeacy** [YOURLS/YOURLS#2783]
**Describe the bug**
I have just setup a new workspace for yourls and added my database settings to the config.php file. My database requires an SSL connection so I copied the plugin made in issue #2468. I had to temporarily modify core so I could login and enable the plugin. After reverting my core changes, the PDO database connection is failing due to the lack of a certificate. Error: _"PDOException: SQLSTATE[HY000] [9002] SSL connection is required. Please specify SSL options and retry."_ my plugin doesn't seem to be running (I tried throwing an error in my plugin and it wasn't being called). I added some code to print logs when the following is performed:
1. When yourls_add_filter is called which will log the name of the hook
2. When the db_connect_driver_option hook is passed to yourls_apply_filter
3. When my override in class-mysql.php manually adds my cert to the PDO options
4. When yourls_load_plugins determines a hook to be either valid or invalid
 and got the following:
(I prefixed each line with which log call above made it)
```TEXT
1 - plugins_loaded was added to the active filters
2 - db_connect_driver_option was not in $yourls_filters and has been ignored
3 - Core was modified to add SSL cert
1 - get_shorturl_charset was added to the active filters
4 - hyphens-in-urls/plugin.php is a valid plugin
1 - db_connect_driver_option was added to the active filters
4 - secure-ssl/plugin.php is a valid plugin
```
Based on this is looks like my plugin to add the db_connect_driver_option filter is being processed AFTER the class-mysql.php file calls for the db_connect_driver_option filter. Therefore, when yourls_apply_filter looks for db_connect_driver_option in $yourls_filters it's not set and returns the input value which is an empty array.
**To Reproduce**
I did this from a fresh install of yourls. Steps I used the following actions:
1. download verion 1.7.9 [here](https://github.com/YOURLS/YOURLS/releases)
2. follow installation instructions [here](https://yourls.org/#Install) (the database you add through config.php should have enforced SSL)
3. add the plugin from this issue #2468 to add the SSL cert to your PDO connection
4. you'll need to enable the plugin. To do this I added the following:
```PHP
$driver_options [PDO::MYSQL_ATTR_SSL_CA] ="path/to/my/cert";
```
To my includes/class-mysql.php file just before the PDO connect is established to overwrite the previous options. Login and enable the plugin then log out and remove the above line from includes/class-mysql.php.

**Expected behavior**
I expected the plugin to run before the PDO connection is established and add my SSL cert to the PDO options.

**Actual behavior**
The PDO connection runs before my plugin and fails because the plugin has not added the MYSQL_ATTR_SSL_CA option to the PDO connection yet.

**Screenshots**
N/A

**Versions**
yourls V 1.7.9
Debian 10.4
PHP 7.3.19
mysql 5.7.29

**Additional context**
We have been using yourls for over a year now but we're changing the data source over to a new mysql database. I know the data and structure are fine because I restored them from the old database. I have inherited this from another developer so I apologise if the solution is simple but I'm not seeing it.

**Comment by ozh** [comment]
YOURLS has the little known ability* to load a "plugin" before everything is loaded (ie you don't get to activate or deactivate it), if it is named `cache.php` or `db.php` in the `user/` directory (see https://github.com/YOURLS/YOURLS/blob/master/includes/Config/Init.php#L55-L63) 

So, untested, please try & report : change plugin from issue 2468 to the following in `user/db.php`:

```php
<?php
/*
Plugin Name: Secure MySQL
Plugin URI: https://github.com/YOURLS/YOURLS/issues/2783
Description: SSL/TLS PDO Connection
Version: 1.0
Author: YOURLS
Author URI: https://yourls.org/
*/
// No direct call
if( !defined( 'YOURLS_ABSPATH' ) ) die();

// Add custom cert
yourls_add_filter( 'db_connect_driver_option', function ( $options ) {
    // Add your certificate paths
    // https://secure.php.net/manual/ref.pdo-mysql.php
    return array_merge( $options, [
        PDO::MYSQL_ATTR_SSL_CA => '/path/to/ca',
    ] );
} );

// Load DB layer as usual
require_once YOURLS_INC.'/class-mysql.php';

```

**Comment by RileyDeLeacy** [comment]
Thanks mate, just a couple of tweaks and it works like a charm.

I needed to call yourls_db_connect() below the require statement in the plugin otherwise it throws some nasty errors.

Also I had to change the plugin a little. array_merge was returning an array indexed from 0 instead of an associative array. I replaced it with an array union.

The final plugin was:
```PHP
<?php
/*
Plugin Name: Secure MySQL
Plugin URI: https://github.com/YOURLS/YOURLS/issues/2783
Description: SSL/TLS PDO Connection
Version: 1.0
Author: YOURLS
Author URI: https://yourls.org/
*/
// No direct call
if( !defined( 'YOURLS_ABSPATH' ) ) die();

// Add custom cert
yourls_add_filter( 'db_connect_driver_option', function ( $options ) {
    // Add your certificate paths
    // https://secure.php.net/manual/ref.pdo-mysql.php
    return $options + Array(PDO::MYSQL_ATTR_SSL_CA=> __DIR__."/mycert");
} );

// Load DB layer as usual
require_once YOURLS_INC.'/class-mysql.php';
yourls_db_connect();
?>
```
Thanks for the help :)

**Comment by dgw** [comment]
> `*`I really should publicize this somewhere. I thought I did, but cannot find it, so I guess I never did it :)

Please do. I vaguely remembered that such functionality existed to load some "must-use" DB plugin, but couldn't find it and didn't want to comment on this ticket unless I could be sure my suggestion would work :)

**Comment by justinforlenza** [comment]
Hello, I am currently trying to get my YOURLS to connect to SSL secured MYSQL server, and I have tried just about everything that I could think of, and am out of troubleshooting steps. 

It appears the code is at least being executed as I am getting a different error from before, however this one does not provide any additional information:

![image](https://user-images.githubusercontent.com/11709872/104207897-7387a480-53fe-11eb-9683-7f5597342fcf.png)


Here is my user/db.php

```php
<?php
/*
Plugin Name: Secure MySQL
Plugin URI: https://github.com/YOURLS/YOURLS/issues/2468
Description: SSL/TLS Database Connection
Version: 1.0
Author: YOURLS
Author URI: https://yourls.org/
*/
// No direct call
if( !defined( 'YOURLS_ABSPATH' ) ) die();
yourls_add_filter( 'db_connect_driver_option', function ( $options ) {
    // Add your certificate paths
    // https://secure.php.net/manual/ref.pdo-mysql.php
    //   return $options;
   return $options + Array(
        PDO::MYSQL_ATTR_SSL_CA => __DIR__."server-ca.pem",
        PDO::MYSQL_ATTR_SSL_CERT => __DIR__."client-cert.pem",
        PDO::MYSQL_ATTR_SSL_KEY => __DIR__."client-key.pem"
   );
} );
// Load DB layer as usual
require_once YOURLS_INC.'/class-mysql.php';
yourls_db_connect();

?>
```

**Comment by RileyDeLeacy** [comment]
Got tagged so I thought I'd take a stab at it.

@justinforlenza can you try adding a forward slash after the __DIR__ magic constants and within the double quotes so they look like this:
``` php
return $options + Array(
        PDO::MYSQL_ATTR_SSL_CA => __DIR__."/server-ca.pem",
        PDO::MYSQL_ATTR_SSL_CERT => __DIR__."/client-cert.pem",
        PDO::MYSQL_ATTR_SSL_KEY => __DIR__."/client-key.pem"
);
```
And make sure those files are in the same directory as your db.php under user/

**Comment by justinforlenza** [comment]
Yeah added the forward slash, still the same error. 

And yeah they are in the same directory, i originally had them in a seperate folder and setting the vales to their absolute path, but for testing/troubleshooting purposes I moved them into the user/ folder and using DIR as in your php.

**Comment by RileyDeLeacy** [comment]
It looks like the PDO connection has recognised the certs so the plugin should be running. I can point you in a couple directions to look but I think your best bet is to log another issue.

Here are a few places I recommend looking:
1. The PDO options should be added by the time the PDO connection is made. The plugin we made would be run in the includes/class-mysql.php file so I would throw a var_dump right before the PDO connection is made to make sure everything is set right.
``` PHP
var_dump($driver_options);
$ydb = new \YOURLS\Database\YDB( $dsn, $user, $pass, $driver_options, $attributes );
```
2. Check the read permissions on your pem files. Try opening them with php or configure read permissions on whatever OS you're using.
3. That error you included in the screenshot above seems to come from includes/Database/YDB.php in a method called dead_or_error(). You could add a couple more var_dumps in there to get a better idea of what's going on.
4. Try creating a new php file and connect to your database with it through PDO. It could be something simple like using the wrong port number.

If this doesn't help I would make another issue specific to your case. Make sure to use the template and provide plenty of details.
