### ISSUE TITLE
demo url in readme is inaccessible

### ISSUE THREAD

**Issue by jlsjonas** [YOURLS/YOURLS#2784]
* [x] I've read the [Troubleshooting First Steps](https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps)
* [x] This request isn't a duplicate of an existing issue, opened or closed
* [x] I've read the [docs](https://yourls.org/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [YOURLS Discourse](https://discourse.yourls.org/) community

**Describe the bug**
https://yourls.org/cookie+ redirects to a login page

**To Reproduce**
Steps to reproduce the behavior. This is mandatory if you expect someone to fix the problem. Example:
1. Go to the https://yourls.org/ website (or readme.html in this repo)
2. Scroll down to
> See a live example of YOURLS stats on https://yourls.org/cookie+
3. Click on the link
4. Be greeted with a login error

**Expected behavior**
a live example of YOURLS stats

**Actual behavior**
A login page

**Screenshots**
![image](https://user-images.githubusercontent.com/932193/98085702-fe3ba880-1e7d-11eb-87f4-c3c42432573c.png)

**Versions**
N/A
 Powered by YOURLS v 1.7.10

**Comment by ozh** [comment]
Indeed. Fixed! Thanks :)
