### ISSUE TITLE
Vanity URL feature on domain name

### ISSUE THREAD

**Issue by mayank-mundhra-2012** [YOURLS/YOURLS#2787]
* [ X] I've read the [guidelines for Contributing to YOURLS Projects](https://github.com/YOURLS/.github/blob/master/CONTRIBUTING.md)
* [ X] This request isn't a duplicate of an existing request
* [ X] This is not a personal support request that should be posted on the [YOURLS Discourse](https://discourse.yourls.org/) community

**Summary**
I want to implement two vanity URL features for my website.
1. vanity.domain.tld/vanity
2. domain.tld/vanity

**Motivation**
Why are we doing this? 
This is to create vanity urls for my clients. Each vanity URL will produce custom pages from a template and saved data.
Additionally is it possible to not do a permanent redirect but rather a temporary redirect so as to prevent caching and logging at a browser level.
This can be similar to facebook.com/username1 and facebook.com/username2

What use cases does it support? 
What is the expected outcome?

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**
I haven't come across any other alternatives

**Additional context**

**Comment by ozh** [comment]
I don't understand what is a question here. Not properly using the issue template (apparently this is really hard for lots of people....) and leaving default text certainly doesn't help.

You want to have YOURLS installed at vanity.domain.tld/vanity and at domain.tld/vanity ? Then install YOURLS at vanity.domain.tld/vanity and at domain.tld/vanity ...
