### ISSUE TITLE
Events Working on /admin urls not base urls

### ISSUE THREAD

**Issue by ankur0890** [YOURLS/YOURLS#2789]
I installed a plugin in the user/plugins directory. Plugin contains` yourls_add_action( 'pre_redirect', 'someFunction' )` which checks for a certain function before redirecting the link to the main URL. But I noticed my event is getting called on the `abc.com/admin/<shorturlId>` instead of `abc.com\<shorturlId>`. I checked all my plugins events are getting listened to by the `/admin` subroutes instead of main short urls. Can you help me with this? Quite a newbie to the Yourls.

The plugin I installed is [https://github.com/MatthewC/yourls-password-protection/blob/master/plugin.php](https://github.com/MatthewC/yourls-password-protection/blob/master/plugin.php)

**Comment by ankur0890** [comment]
After long R&D , Instead of `pre_redirect` I have used `redirect_shorturl` and it's working fine now. 
But I would still like to know the reason behind it. As per my understanding pre_redirect should also worked. Am I Missing a point here???

**Comment by ozh** [comment]
It's just how YOURLS works out of the box : when a URL that doesn't exist is requested, eg `abc.com/admin/<shorturlId>`, `yourls-loader.php` checks if it's a short URL and if not, redirects with `yourls_redirect()` (hence the `pre_redirect` hook) to the root, see https://github.com/YOURLS/YOURLS/blob/master/yourls-loader.php#L68.

This function is used for any redirect, either internal to the YOURLS setup, or external to a long URL.
