### ISSUE TITLE
Handshake Domain Integration

### ISSUE THREAD

**Issue by D347HxD** [YOURLS/YOURLS#2790]
* [x ] I've read the [guidelines for Contributing to YOURLS Projects](https://github.com/YOURLS/.github/blob/master/CONTRIBUTING.md)
* [x ] This request isn't a duplicate of an existing request
* [x ] This is not a personal support request that should be posted on the [YOURLS Discourse](https://discourse.yourls.org/) community

**Summary**
I would like YOURLs to work with handshake domains, https://handshake.org/

**Motivation**
Handshake looks like it will have a bright future, and to be able to shorten your urls to handshake names which can be shorter than a normal domain you can purchase from ICANN will be amazing.

**Comment by dgw** [comment]
If one points a Handshake name to a webserver running YOURLS, why _wouldn't_ it work? What are you asking YOURLS to add/change?
