### ISSUE TITLE
Is this setup secure?

### ISSUE THREAD

**Issue by techboyg5** [YOURLS/YOURLS#2793]
So I'm running my own URL shortener that uses a *private* YOURLS as the backend. The URL shortener is available [here](https://techboyg5blog.com/url-shortener/).

Look at the source code. My question is, is this setup secure? Does this hide the username, password, and forever lasting signature? Does this allow you to get into the admin console?

**Note: Do not tell me tips to prevent spam. It's okay how it is. I just want to know if this setup is secure.**

**Comment by ozh** [comment]
Depends on what you call "secure".
This doesn't allow to enter the console since it doesn't expose your user and password.
This does expose your "secret API signature", which gives access to whatever is allowed via the [API](http://yourls.org/#API)

**Comment by techboyg5** [comment]
> Depends on what you call "secure".
> This doesn't allow to enter the console since it doesn't expose your user and password.
> This does expose your "secret API signature", which gives access to whatever is allowed via the [API](http://yourls.org/#API)

Thank you for telling me that! I'm fine with public API access; that's exactly what I want.
