### ISSUE TITLE
If page title includes emojis insertion fails

### ISSUE THREAD

**Issue by ahmethakanbesel** [YOURLS/YOURLS#2795]
PHP Fatal error:  Uncaught PDOException: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF0\x9F\x92\x99\xF0\x9F...' for column `DB_NAME`.`yourls_url`.`title` at row 1 in /home/XXX/public_html/includes/vendor/aura/sql/src/ExtendedPdo.php:748

Original page title like this: 💙🥀 🖤🥀

**Comment by dgw** [comment]
Likely related to the same problem and https://github.com/YOURLS/YOURLS/issues/2687#issuecomment-704700731 — though I never found out if that helped.

My link there was wrong, though. I must have meant to point at https://stackoverflow.com/a/53072533/5991 instead. tl;dr is check your database charset & collation, making sure it's not using `latin1` or something silly. You probably want `utf8mb4` or adjacent.

**Comment by ahmethakanbesel** [comment]
> Likely related to the same problem and [#2687 (comment)](https://github.com/YOURLS/YOURLS/issues/2687#issuecomment-704700731) — though I never found out if that helped.
> 
> My link there was wrong, though. I must have meant to point at https://stackoverflow.com/a/53072533/5991 instead. tl;dr is check your database charset & collation, making sure it's not using `latin1` or something silly. You probably want `utf8mb4` or adjacent.

I set "yourls_url.title" and "yourls_url" collation utf8mb4_unicode_ci but the issue still occurs.

**Comment by dgw** [comment]
Charset too?

If you did, or that doesn't help either, I guess wait for the EU contingent to see this. For me it's way past bedtime, and I was hoping this would be a quick fix just by tweaking the DB. 😅

**Comment by ahmethakanbesel** [comment]
> Charset too?
> 
> If you did, or that doesn't help either, I guess wait for the EU contingent to see this. For me it's way past bedtime, and I was hoping this would be a quick fix just by tweaking the DB. 😅

Yes, charset too. I think the issue related to PDO driver.

**Comment by ozh** [comment]
What YOURLS version ? Jesus it would be so much easier if people actually used the issue template.

I'm guessing YOURLS 1.7.9 and I'm guessing this [works on 1.7.10](https://yourls.org/em)

**Comment by ahmethakanbesel** [comment]
> What YOURLS version ? Jesus it would be so much easier if people actually used the issue template.
> 
> I'm guessing YOURLS 1.7.9 and I'm guessing this [works on 1.7.10](https://yourls.org/em)

Yes, 1.7.9 which is the latest release.

**Comment by ahmethakanbesel** [comment]
When will 1.7.10 be released?

**Comment by ahmethakanbesel** [comment]
> What YOURLS version ? Jesus it would be so much easier if people actually used the issue template.
> 
> I'm guessing YOURLS 1.7.9 and I'm guessing this [works on 1.7.10](https://yourls.org/em)

When will 1.7.10 be released?

**Comment by ozh** [comment]
As always: when it's done, no ETA
