### ISSUE TITLE
Easy guide for customizing the HTML and CSS?

### ISSUE THREAD

**Issue by BreadcrumbIsTaken** [YOURLS/YOURLS#2796]
* [x] I've read the [guidelines for Contributing to YOURLS Projects](https://github.com/YOURLS/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing request
* [x] This is not a personal support request that should be posted on the [YOURLS Discourse](https://discourse.yourls.org/) community

**Summary**
I would like to know if there can be a guide that describes how to customize the HTML and CSS for yoURLs. Such as what CSS property changes what, how to add your own HTML, change some existing HTML, etc.

**Motivation**
I think that it would be cool to get to customize the HTML and CSS. If someone wants to become the next bit.ly, they will need to change the HTML to make it like they want. It is hard for me to look through all the code (I do not have any knowledge of PHP) and figure out what changes what, if it works or not, and if it does the thing I want.

**Describe the solution you'd like**
The solution I would like is a guide that is easy to follow, that gives you details on functions do what and how to customize the HTML and CSS.

**Comment by ozh** [comment]
I suggest you have a look at how YOURLS plugins or themes that modify the interface work.
