### ISSUE TITLE
Feature Request  - Config to disable IP tracking. (I can PR this.)

### ISSUE THREAD

**Issue by syntaxseed** [YOURLS/YOURLS#2802]
* [ Y] I've read the [guidelines for Contributing to YOURLS Projects](https://github.com/YOURLS/.github/blob/master/CONTRIBUTING.md)
* [ Y] This request isn't a duplicate of an existing request
* [ Y] This is not a personal support request that should be posted on the [YOURLS Discourse](https://discourse.yourls.org/) community

**Summary**
Add a config value which can enable/disable IP tracking.

**Motivation**
Not all users of YOURLS want the application to track IP addresses when logging redirects. This may be related to regional privacy laws, or users who just want to minimize tracking/data collection.

**Describe the solution you'd like**
I have already implemented this feature, it's just a couple of lines of code.

I can PR this if desired.

**Comment by ozh** [comment]
We'd want less config constants, not more. Can you implement this feature with a plugin?
