### ISSUE TITLE
Feature Request  - Config for Not-Found url or visit of the root domain. (I can PR this.)

### ISSUE THREAD

**Issue by syntaxseed** [YOURLS/YOURLS#2803]
**Summary**
Add a config value which contains a specific URL to redirect to if the short url is not found or if someone visits the root of the yourls install (missing index.php page). This can be different from the YOURLS_SITE value.

**Motivation**
What if I have a shortener installed at a subdomain or another domain entirely, but if an invalid short code is supplied or the user visits / on the yourls install, I might want to redirect to my company domain (not the YOURLs installed domain).

**Describe the solution you'd like**
A config value to store the not-found redirect URL and an index.php file which re-directs here (also works when YOURLs gets to the end of yourls-loader.php and a keyword is not found). I have already implemented this solution.

I can PR this if desired.

**Comment by ozh** [comment]
That's a typical use for a plugin, rather than adding yet another config constant. There are already a couple to handle differently not found short URLs: https://github.com/YOURLS/awesome-yourls
