### ISSUE TITLE
Viber link support

### ISSUE THREAD

**Issue by blokhinaleks** [YOURLS/YOURLS#2805]
* [ Y ] I've read the [guidelines for Contributing to YOURLS Projects](https://github.com/YOURLS/.github/blob/master/CONTRIBUTING.md)
* [ Y ] This request isn't a duplicate of an existing request
* [ Y ] This is not a personal support request that should be posted on the [YOURLS Discourse](https://discourse.yourls.org/) community

**Summary**
Add support shortener viber link.

**Comment by ozh** [comment]
Besides not having the slightest idea of what that means because I don't know what "Add support shortener viber link" means or what "viber link" is, I'm pretty sure this is plugin territory. See https://github.com/YOURLS/YOURLS/wiki/Possible-With-A-Plugin
