### ISSUE TITLE
Can't shorten a specific link from Google

### ISSUE THREAD

**Issue by sshcli** [YOURLS/YOURLS#2806]
Can't shorten a specific link from Google
The problem is with a subdomain hosted in negocio.site 
**Note:** Google is the owner of the domain negocio.site

The link causing problems is:
`https://lcd-web-publicidad.negocio.site` (Please feel free to try to shorten from your own installation)

Any idea if the problem is caused by the double - - ?
Any workaround for this?

**Tested with:**
YOURLS v 1.7.9
PHP 7.4.13
MySQL Version 5.7.32

**Comment by dgw** [comment]
> Please feel free to try to shorten from your own installation

I did. It worked fine.

You'll have to be more specific than "can't shorten" and "causing problems". We need error messages, logs, something to go on to help troubleshoot. It's probably not a YOURLS bug though.

**Comment by sshcli** [comment]
> It's probably not a YOURLS bug though.

Thanks @dgw for your quick response.
You are right, it's not a YOURLS bug.
I found the root cause of the problem.
if you have Adblock enabled in your browser it won't work

**Comment by sshcli** [comment]
I'm closing this issue as solved. 
if you need to create a PR to improve compatibility with Adblock, just reopen this issue.
