### ISSUE TITLE
clicks increasing when browser in admin-view reloads

### ISSUE THREAD

**Issue by epagogmbh** [YOURLS/YOURLS#2812]
Hey,

if we login, and we reload overview page in our browser, the counts of the clicks is increasing, every reload sets a click in the statistics. is that a bug or is it normal? actual version. you camn check if you login and klick reload.

#thanks for this great software!
matthias

**Comment by ozh** [comment]
Definitely cannot reproduce. If log in, refresh, log out, log in, refresh, whatever the order of that sequence, if doesn't increment anything. The code for this is straightforward: it *reads* from the DB, it doesn't write.

**Comment by ozh** [comment]
Possible cause : something client side like a browser plugin that prefetchs every link. But anyway, not a YOURLS issue.

**Comment by epagogmbh** [comment]
it was this plugin: https://github.com/joshp23/YOURLS-doTLS

--

(Interne Referenz: not set)


epago GmbH
Geneststr. 5
10829 Berlin

Web: https://www.epago.de
Telefon: +49 (0)30 / 609 858 770
E-Mail: mh@epago.de

Steuernummer: 204/108/03705
Umsatzsteueridentifikationsnummer: DE 263814786
_________________________________________
epago GmbH Geneststr. 5 10829 Berlin GF Dipl.-Kfm.(FH) - Matthias Hanske
Tel: +49 (0)30 / 609 858 770 - Fax: +49 (0)30 / 609 858 779 - Mail:
info@epago.de

*Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte
Informationen Das unerlaubte Kopieren sowie die unbefugte Weitergabe
dieser Mail sind nicht gestattet. Sind Sie nicht der rechtmäßige
Empfänger, vernichten Sie diese E-Mail umgehend.*



Am Fr., 15. Jan. 2021 um 15:32 Uhr schrieb ྅༻ Ǭɀħ ༄༆ཉ <
notifications@github.com>:

**Comment by ozh** [comment]
Ping @joshp23 to maybe look into this ?
