### ISSUE TITLE
mysql connection problem

### ISSUE THREAD

**Issue by Sarptra** [YOURLS/YOURLS#2813]
Using cpanel 86.0 (build 30)
php version 7.0.33
mysql version 5.6.49-cll-lve
Apache 2.4.46

Yourls fresh install cannot be completed 

yourls cannot find mysql port localhost:3306
I also nmap my server and mysql tcp open on 3306i
error code 

Fatal error

Incorrect DB config, or could not connect to DB
PDOException: SQLSTATE[42000] [1044] Access denied for user 'kmvsbdjweqfjbjda'@'localhost' to database 'mysqlurl'

**Comment by dgw** [comment]
The database user configuration in YOURLS does not match what MySQL has. It tells you that access is denied, not that it can't find the server. Check password, username, DB name, etc.
