### ISSUE TITLE
Filter for replacing keyword + with - in URL not working.

### ISSUE THREAD

**Issue by dragosion** [YOURLS/YOURLS#2815]
Filter for replacing keyword + with - in URL not working.
Saw a filter exists but the sanitize is applied to the keyword before the filter.

What happens:
keyword+1
becomes
keyword1

Even though I set a filter to replace + with -
Desired outcome: 
keyword-1
Actual outcome
keyword1

Fix is easy as far as I see, not sure if this is a good idea but:
in latest version (after 1.79) before it was in functions.php
 \includes\functions-shorturls.php

Swap lines 77 and 78

            $keyword = yourls_sanitize_keyword( $keyword, true );
            $keyword = yourls_apply_filter( 'custom_keyword', $keyword, $url, $title );

becomes - filter before

            $keyword = yourls_apply_filter( 'custom_keyword', $keyword, $url, $title );
            $keyword = yourls_sanitize_keyword( $keyword, true );

Or
move the filter at
\includes\functions-formatting.php line 75
return yourls_apply_filter( 'sanitize_string', $valid, $keyword, $restrict_to_shorturl_charset );

**Comment by ozh** [comment]
I don't understand what you're trying to achieve

**Comment by dragosion** [comment]
I have copy/pasted short url that looks like this:
my+short+url

I try to use a filter to replace the + with - without me having to manually modify the link.

I paste 
my+short+url
in the short link box
result is
myshorturl
by default and the same if I add the 'custom_keyword' filter.
'custom_keyword' filter doesn't work if there are + and other characters present.
I only care about + here but it's the same for all the blocked characters.

Hope it's more clear now.

**Comment by dragosion** [comment]
Figured it out eventually.
Added + as allowed character and then it's available to use.

`yourls_add_filter( 'get_shorturl_charset', 'custom_plus_in_charset' );
function custom_plus_in_charset( $in ) {
	return $in.'+';
}`
