### ISSUE TITLE
YOURLS Program Stopped Working

### ISSUE THREAD

**Issue by luvliness** [YOURLS/YOURLS#2817]
Hello,
I set up the YOURLS on my domain yesterday, and was able to successfully create 8 redirects. Today, when I logged in to create new ones, it won't get passed the "loading" button and it is in a continuous loop. It's been doing this for about 3-5 minutes now (enough time for me to create an account on here, verify my email and take a screenshot. Is there a bug that needs to be fixed? I really like the idea of this service and even bought a new domain name and a hosting package just so I could use this. Please help.
![screenshot](https://user-images.githubusercontent.com/78104249/106036992-12b9c680-60a4-11eb-913f-5c4c9cf73e73.png)

**Comment by dgw** [comment]
We need much more detail to have any chance of suggesting solutions. Since YOURLS worked before, I suspect something changed in your hosting environment.

See if you can find error logs? We have a troubleshooting page on the wiki here that might help.

**Comment by luvliness** [comment]
I actually haven't touched my control panel or uploaded any files since yesterday. The hosting account is strictly for this app. Where would I find error logs?

**Comment by luvliness** [comment]
hmm, it actually works if I do the admin/index.php - but if I just go to /admin it is still loading.

**Comment by dgw** [comment]
I couldn't say. You haven't specified what HTTP server or platform (OS) you use, so they could be almost literally anywhere.

Chances are that your hosting provider shows the log location somewhere in their control panel or documentation, though, unless you're using a VPS or bare-metal server.

**Comment by dgw** [comment]
Based on that last comment about index.php, though, maybe the fix would be as simple as configuring the default page in your server config? It's likely looking for index.htm/index.html by default, not PHP.

**Comment by luvliness** [comment]
thank you

**Comment by dgw** [comment]
Setting the index page properly fixed it?

**Comment by iboettcher** [comment]
I see the same issue here. When I open the browser developer tools, I see that clicking the create button causes a 403 on /admin/admin-ajax.php?action=add&url
I also installed yourls some days before, and it was running for a few days without any changes. I have set index.php as the default page, but this did not help.
Using a VM with Ubuntu 20.04 server and nginx.

**Comment by ozh** [comment]
@iboettcher this issue is garbage (no background, not enough info to provide any actual pointers, no feedback) so it's probably a bad start to say you have the same issue. I advise you to open a new, and properly filled, issue
