### ISSUE TITLE
SVG Icons for YOURLS

### ISSUE THREAD

**Issue by simon-eller** [YOURLS/YOURLS#2821]
**Summary**
The icons are now many years old. In one of the last updates the YOURLS logo has been introduced as SVG file and I think that it's no time to vectorize the icons too.

**Motivation**
YOURLS is great and I've implemented the SVG icons already in my own YOURLS installation and now I want to provide those icons for the crowd too.

**Is your feature request related to a problem? Please describe.**
It's not related to a problem but it would look much better.

**Describe the solution you'd like**
I've already cloned the YOURS repository but I'm new at GitHub and I don't now if I'm allowed to upload it now or not.

**Comment by dgw** [comment]
Icons meaning the Actions buttons in the admin panel, for example? Great candidates for SVG, yes!

What you want is a "fork", the button for which you'll find in the top right of this repository. Once you have [your own fork](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-forks), you can clone it and then add your work [to a branch](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-branches) there, then turn that branch into a [pull request](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests).

**Comment by ozh** [comment]
Superseded by #2822
