### ISSUE TITLE
WordPress and YOURLS on one domain (Nginx)

### ISSUE THREAD

**Issue by ToBulk** [YOURLS/YOURLS#2826]
I want to run both WordPress and YOURLS on one domain.

Since both need to handle URLs differently, they need different try_files directives. WordPress sits on the root of the domain (domain.tld), while YOURLS is being installed to the /go/ directory.

Despite the two location rules, I get 404s on any links generated by YOURLS (e.g. domain.tld/g/linkname, all are redirects to external URLs), though I can access the YOURLS admin backend. 

As far as I read, declaring to location rules (one for /go/, and one for /) should suffice in order to let Nginx handle the direct and the /go/ URLS differently - is there something in wrong in my thinking?

I have added the following to the Nginx config:

`
location / {
try_files  $uri $uri/ /index.php?$args;
}
location /go/ {
try_files $uri $uri/ /go/yourls-loader.php$is_args$args;
}
`

What am I missing?

**Comment by ozh** [comment]
Not an nginx user myself, but does the order of the location directive count ? I guess it could make sense to have first the `location /go/ { ... }` and then, if not matched, the `location / { ... }` would be used

**Comment by ozh** [comment]
Possible solution : http://www.hardeepasrani.com/2017/06/installing-yourls-on-nginx/
