### ISSUE TITLE
DB Upgrade 1.7.4 -> 1.7.10: PDO - No Active Transaction

### ISSUE THREAD

**Issue by Dalethium** [YOURLS/YOURLS#2827]
**Describe the bug**
Upgrading the database from 1.7.4 to 1.7.10 using PHP 8 leads to an HTTP 500 error (though the page is displayed, the status code is 500 and the upgrade never completes)

**To Reproduce**
Install latest using old db
upgrade

**Expected behavior**
Upgrade to complete

**Actual behavior**
Upgrade fails without notice

**Screenshots**
Page upon upgrading (no errors)
![SX-All-pEHeGGFggt-2067](https://user-images.githubusercontent.com/22735418/106649218-8f134480-6591-11eb-9f5a-e51a6cefb3de.png)
Error 500 (page loaded is shown above)
![image](https://user-images.githubusercontent.com/22735418/106649301-a94d2280-6591-11eb-9a18-42302a8a71b3.png)
![image](https://user-images.githubusercontent.com/22735418/106649184-83278280-6591-11eb-86cb-ac9f24788e11.png)

**Versions**
Ubuntu 16
PHP 8.0
YOURLS git rev 7af080e
Apache2
PHP-FPM 8.0
**Additional context**
`
==> /var/log/fpm-php.www.log <==
#2 {main}
  thrown in /var/web/[redacted]/public_html/includes/Config/Config.php on line 92
[02-Feb-2021 18:55:03 UTC] PHP Fatal error:  Uncaught PDOException: There is no active transaction in /var/web/[redacted]/public_html/includes/vendor/aura/sql/src/AbstractExtendedPdo.php:150
Stack trace:
#0 /var/web/[redacted]/public_html/includes/vendor/aura/sql/src/AbstractExtendedPdo.php(150): PDO->commit()
#1 /var/web/[redacted]/public_html/includes/functions-upgrade.php(76): Aura\Sql\AbstractExtendedPdo->commit()
#2 /var/web/[redacted]/public_html/includes/functions-upgrade.php(34): yourls_upgrade_to_18()
#3 /var/web/[redacted]/public_html/admin/upgrade.php(72): yourls_upgrade()
#4 {main}
  thrown in /var/web/[redacted]/public_html/includes/vendor/aura/sql/src/AbstractExtendedPdo.php on line 150
`

Please let me know if you need anything else! I am a big fan of this project so I am hoping to get this back and running soon!

**Comment by ozh** [comment]
@Dalethium should work correctly now
