### ISSUE TITLE
Concurency problem with click count function

### ISSUE THREAD

**Issue by vipwangtian** [YOURLS/YOURLS#2829]
There's a problem while a large number of people click the same short url at the same time. 
Last week our establishment push an activity online which use yourls as an entry point, I noticed that the qps is only 30 and a lot of 504 response on nginx log. So I did a performance test on different environments, but the QPS always about 30. Then I query the mysql lock state and find that there are so many locks on yourls_url table executing `UPDATE `yourls_url` SET `clicks` = clicks + 1 WHERE `keyword` = '3vz7wj'` statement. After that, I removed `yourls_update_clicks` function in functions.php file and did the test again. QPS had a surprising advance more than 400.
Is there a solution to solve this problem?

**Comment by ozh** [comment]
A few easy pointers : 
- turn off detail logging (the country, referrer etc...), see http://yourls.org/#Config;optional
- turn off click count entirely. A one liner plugin to bypass [the function](https://github.com/YOURLS/YOURLS/blob/master/includes/functions.php#L80-L101)
- There's a concurrency plugin in the [plugin list](https://github.com/YOURLS/awesome-yourls), coded long ago by someone with high traffic like you report

**Comment by vipwangtian** [comment]
> A few easy pointers :
> 
> * turn off detail logging (the country, referrer etc...), see http://yourls.org/#Config;optional
> * turn off click count entirely. A one liner plugin to bypass [the function](https://github.com/YOURLS/YOURLS/blob/master/includes/functions.php#L80-L101)
> * There's a concurrency plugin in the [plugin list](https://github.com/YOURLS/awesome-yourls), coded long ago by someone with high traffic like you report

Thank U for your help, I write a one line plugin in my repository and it works
https://github.com/vipwangtian/yourls-skip-click-count

**Comment by ozh** [comment]
I've added the plugin to https://github.com/YOURLS/awesome-yourls
