### ISSUE TITLE
No YOURLS logo on IE 11

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#2830]
Probably not too critical because otherwise people would have complained, but the YOURLS logo doesn't show on IE 11

![image](https://user-images.githubusercontent.com/223647/107289384-3b0ed100-6a65-11eb-8311-3d50c1bbac5a.png)

(It's not just a problem of SVG not showing since other SVG icons are fine)

**Comment by master3395** [comment]
IE 11 is on it's way out, don't worry.

**Comment by ozh** [comment]
Closed via #2864
