### ISSUE TITLE
I Need To Know How To Add Something (Total Clicks) - Please Help

### ISSUE THREAD

**Issue by alexwalker0** [YOURLS/YOURLS#2831]
Hi,

I need help with adding a feature which I seem to not have. I am new to coding, and don't understand a word when it comes to coding. I want to add total clicks like the attached photo.

I want to add this in my stats:
![4Fissue](https://user-images.githubusercontent.com/78889778/107597012-20358b80-6c22-11eb-8df8-e0d4ae080a76.png)

**------------------------------------------------------------------------------------------------------------------**

How my stats currently look like:
![dvgfv](https://user-images.githubusercontent.com/78889778/107597253-c71a2780-6c22-11eb-8335-1e7990bc82eb.png)

Thank you,
Alex

**Comment by ozh** [comment]
You'd need a plugin to do so. See wiki page https://github.com/YOURLS/YOURLS/wiki/Possible-With-A-Plugin

**Comment by alexwalker0** [comment]
Hi,

Sorry to bother you. I can't find a plugin for this feature, I might have an idea in hand but I need to know something. Are all the URLs that are shortened stored in a script that I can access?

Thank you,
Alex

**Comment by ozh** [comment]
There are stored in the _database_ you configured when you installed YOURLS ...
