### ISSUE TITLE
Support for PHP8

### ISSUE THREAD

**Issue by lkuza2** [YOURLS/YOURLS#2832]
Using PHP8 results in a 500 server error.  I enabled PHP logging but couldn't get any errors to print out.

Reverting to PHP7 fixes the issue.

**Comment by dgw** [comment]
Duplicate of #2807.

**Comment by lkuza2** [comment]
> Duplicate of #2807.

Sorry, I am stupid and totally missed that while searching.

**Comment by dgw** [comment]
It's OK. Just that you're willing to admit that you missed it is amazing. So is the fact that you even tried to search first! 😸
