### ISSUE TITLE
PHP 8 Compatibility

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#2833]
I'm opening this issue (and pinning it) to make it easier for issue searchers to see that the question is being addressed

* the [latest release](https://github.com/YOURLS/YOURLS/releases) (1.7.9) is **_NOT_** compatible with PHP8. This issue will be closed when the next release support PHP8. No, there's no ETA.
* current master **_IS_** compatible with PHP8.0 (since resolving #2807) 

If PHP8 is an urgent need for you, you'll need to upgrade to current master, currently labelled 1.7.10 - as usual and as for any upgrade, you back up first :)
(For the record my personal shortener or the one hosted at https://yourls.org/admin/ are always running the current master)

**Comment by LeoColomb** [comment]
@ozh Is there anything against releasing 1.7.10?

**Comment by ozh** [comment]
Yeah, two issues I hadn't time yet to dig : 2827 (not 100% sure if important and needing to delay release) and 2766 (may be important)

**Comment by ozh** [comment]
Latest release is PHP 8 compatible. Update now!
