### ISSUE TITLE
When I go to abc.com/admin it redirects changes to abc.com/adminadmin - Please Help

### ISSUE THREAD

**Issue by alexwalker0** [YOURLS/YOURLS#2834]
Hey,

When I go to abc.com/admin it takes me to abc.com/adminadminadminadminadminadminadminadminadminadminadminadminadminadminadminadminadminadminadmin
I'm new to coding, and I'm not sure why this is happening. If anyone could help that would be amazing.

Thank you,
Alex

**Comment by ozh** [comment]
https://github.com/YOURLS/YOURLS#contributing
