### ISSUE TITLE
Not All Clicks Are Counting - Please Help

### ISSUE THREAD

**Issue by alexwalker0** [YOURLS/YOURLS#2836]
Hey,

I don't know if this is a bug, but when I open a shortened URL two times it counts as one hit. Could you please help me make multiple clicks count as multiple clicks?

Thank you,
Alex

**Comment by ozh** [comment]
Browser cache. For more information, feel free to search [existing issues](https://github.com/YOURLS/YOURLS/issues?q=is%3Aissue+is%3Aclosed+click+count). Or the [readme](http://yourls.org/#FAQ;stats).
