### ISSUE TITLE
Yourls 1.8 MySQL 8 broken installer

### ISSUE THREAD

**Issue by jonathandhn** [YOURLS/YOURLS#2843]
Last upgrade can't update MySQL 8 DB scheme with one click updater on admin page.

**To Reproduce**

1. Update code base
2. Go to /admin
3. Click on upgrade DB button

**Expected behavior**

Upgrade DB should works as expected as before ( MySQL 8.0.23 )

**Actual behavior**

Can't upgrade DB after merging code base to a new one.
`SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-cou CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci' at line  1`

**Versions**

1.8

**Additional context**

lsphp 7.4 \ Openlitespeed \ MySQL server 8.0.23 (delivered by MySQL Oracle repos for Ubuntu)

**Comment by ozh** [comment]
Damn the first bug report for 1.8 was fast 🤣

**Comment by ozh** [comment]
The upgrade runs a few SQL queries, see https://github.com/YOURLS/YOURLS/blob/1.8/includes/functions-upgrade.php#L100-L107

Could you manually check (like, using PHPMyAdmin or something similar) which one of the queries doesn't work for you ?

**Comment by jonathandhn** [comment]
My database is named yourls-cou if the SQL statement is called as it, it fails. If the SQL statement is called between escapes characters as this ones `` it works. I did change this code as following `ALTER DATABASE %s → ALTER DATABASE **MyEscapeCharacter**%s**MyEscapeCharacter**` then run the script gain, and it's done. Thanks you.

/**
 * Update to 506
 *
 */
function yourls_upgrade_to_506() {
    $ydb = yourls_get_db();
    $error_msg = [];

    echo "<p>Updating DB. Please wait...</p>";

    $queries = array(
        'database charset'  => sprintf('ALTER DATABASE `%s` CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;', YOURLS_DB_NAME),
        'options charset'   => sprintf('ALTER TABLE `%s` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;', YOURLS_DB_TABLE_OPTIONS),
        'short URL charset' => sprintf('ALTER TABLE `%s` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;', YOURLS_DB_TABLE_URL),
        'short URL varchar' => sprintf("ALTER TABLE `%s` CHANGE `keyword` `keyword` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '';", YOURLS_DB_TABLE_URL),
        'short URL type'    => sprintf("ALTER TABLE `%s` CHANGE `url` `url` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL;", YOURLS_DB_TABLE_URL),
        'short URL type'    => sprintf("ALTER TABLE `%s` CHANGE `title` `title` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci", YOURLS_DB_TABLE_URL),
    );


PS : I'm sorry I don't know of get the ride of Github locking characters as ` to control the output of this sentence.

**Comment by LeoColomb** [comment]
@jonathandhn Thanks! (I've done the formatting for you 😉)

@ozh Oh yes, variable in MySQL statement should always always be escaped.

**Comment by LeoColomb** [comment]
@jonathandhn By the way, would you aim opening a pull request with this change?

**Comment by RezqZiyad** [comment]
I merged the last commit. Still I get:

`Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1142 UPDATE command denied to user 'omitted'@'omitted' for table 'ypreg8_options' in /app/includes/vendor/aura/sql/src/AbstractExtendedPdo.php:558`

Stack trace:
`#0 /app/includes/vendor/aura/sql/src/AbstractExtendedPdo.php(558): PDOStatement->execute()`
`#1 /app/includes/vendor/aura/sql/src/AbstractExtendedPdo.php(232): Aura\Sql\AbstractExtendedPdo->perform()`
`#2 /app/includes/Database/Options.php(166): Aura\Sql\AbstractExtendedPdo->fetchAffected()`
`#3 /app/includes/functions-options.php(70): YOURLS\Database\Options->update()`
`#4 /app/includes/functions-upgrade.php(58): yourls_update_option()`
`#5 /app/admin/upgrade.php(76): yourls_upgrade()`
`#6 {main}`
`thrown in /app/includes/vendor/aura/sql/src/AbstractExtendedPdo.php on line 558 "GET /admin/upgrade.php?step=3 HTTP/1.1" 500 2009 `

**Comment by fnadde42** [comment]
**YOURLS:** Upgrading from 1.7.9 to 1.8.0

**MySQL/phpMyAdmin:**  
Server: 10.209.1.116 via TCP/IP  
Server version: 5.5.42-MariaDB-cll-lve  
Protocol version: 10  
MySQL charset: UTF-8 Unicode (utf8)  
Apache/2.2.22 (Ubuntu)  
MySQL client version: 5.5.37  
PHP extension: mysql Documentation  

I followed the instructions [in this comment](https://github.com/YOURLS/YOURLS/issues/2843#issuecomment-783514606) and all queries went well. It removed one error message but the message `CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci' at line 1` still remains.

I tried to open up the admin interface and got this stack trace (if it helps):
```
Fatal error: Uncaught Error: Call to undefined function yourls_get_db() in /some/path/public_html/includes/functions-html.php:974 Stack trace: 
#0 /some/path/public_html/includes/functions-html.php(67): yourls_set_html_context('index') 
#1 /some/path/public_html/includes/functions-html.php(467): yourls_html_head() 
#2 /some/path/public_html/includes/functions.php(1009): yourls_die('Our service is ...', 'Service tempora...', 503) 
#3 /some/path/public_html/includes/Config/Init.php(42): yourls_check_maintenance_mode() 
#4 /some/path/public_html/includes/load-yourls.php(26): YOURLS\Config\Init->__construct(Object(YOURLS\Config\InitDefaults)) 
#5 /some/path/public_html/admin/index.php(3): require_once('/storage/conten...') 
#6 {main} thrown in /some/path/public_html/includes/functions-html.php on line 974
```

**Comment by ozh** [comment]
@fnadde42 "Call to undefined function yourls_get_db()" seems to indicate you didn't update the sources as expected and needed

**Comment by fnadde42** [comment]
Yeah I thought so too but I have followed upgrade instructions and overwriten the old files with the new:
```
wget https://github.com/YOURLS/YOURLS/archive/refs/tags/1.8.tar.gz
tar -zxvf 1.8.tar.gz
shopt -s dotglob
cp -r YOURLS-1.8/* public_html/
```

**Comment by ozh** [comment]
Why not use latest release ? It includes the query fixes

**Comment by StPiotir** [comment]
I tried that at first but since it didn't work I opted upgrading version by version. I'll try that again.

**Comment by fnadde42** [comment]
It worked! 🎉 Thank you. I don't know what the problem was. I started the upgrade form 1.7.1 -> 1.8.1 and that failed so I opted to upgrade version by version but got stuck on 1.7.9 -> 1.8.0. Now when I followed your advice I could upgrade directly 1.7.9 -> 1.8.1.
