### ISSUE TITLE
Wrong Date

### ISSUE THREAD

**Issue by Dtrieb** [YOURLS/YOURLS#2848]
On the Admin page I see this wrong Date:
![chrome_2021-02-24_17-30-12](https://user-images.githubusercontent.com/3650284/109032545-0be39b00-76c6-11eb-9796-5fac7da0f0f6.png)

I use german language.

**Comment by ozh** [comment]
Then the problem is with the german translation ?

**Comment by Dtrieb** [comment]
No you see Feb_Februar_Abkürzung that's not okay.
Were did I find this in the code?

**Comment by ozh** [comment]
https://github.com/YOURLS/YOURLS/wiki/YOURLS-in-your-language
