### ISSUE TITLE
commit c1517f1 changed the behavior of `redirect_keyword_not_found`

### ISSUE THREAD

**Issue by tessus** [YOURLS/YOURLS#2849]
* [x] I've read the [Troubleshooting First Steps](https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps)
* [x] This request isn't a duplicate of an existing issue, opened or closed
* [x] I've read the [docs](https://yourls.org/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [YOURLS Discourse](https://discourse.yourls.org/) community

**Describe the bug**
I've updated from 1.7.9 (632cc3c) to 1.8.0 (7f27f47) and all of a sudden the behavior of `redirect_keyword_not_found` changed.
Even though a plugin has a loader_failed hook and a proper trigger, yourls invokes `redirect_keyword_not_found`.

I did a `git bisect` and the problem is with c1517f1. After that change the behavior changed. I've read the documentation and the release notes, but nothing would explain the change in the behavior. There is also no mention that we have to change or use hooks differently.

As soon as I deactivate the 404 plugin, everything works. It also works when the 404 plugin is activated and checkout 1.7.9 632cc3c.

**To Reproduce**
Steps to reproduce the behavior. This is mandatory if you expect someone to fix the problem. Example:
1. activate plugin: https://github.com/YOURLS/404-if-not-found
2. activate plugin: https://github.com/tessus/yourls-json-response
3. make sure you have a valid keyword `x`
4. enter in your browser `http://yourls.example.com/x.json`
5. a 404 is received

**Expected behavior**
I should see the json response in my browser.

**Actual behavior**
I'm getting a 404.

**Screenshots**
n/a

**Versions**
working: 1.7.9 (632cc3c)
not working: 1.8.0 (7f27f47)

OS: doesn't matter. I tried on Linux and macOS.
There are no errors/data in the log file, even with DEBUG ON.

Tried PHP 7.2 and 7.3. It's not a PHP issue.

Commit c1517f1 is the culprit. I did a `git bisect`.

**Additional context**
I hope I filed the bug correctly.

**Comment by ozh** [comment]
(Very very neat bug report, we should create a "Now THAT is how you fill an issue" badge and stick it here 😄)
Will look into this.

**Comment by tessus** [comment]
Great, thanks.

**Comment by ozh** [comment]
So: 

commit c1517f1 didn't _change_ the behavior of `redirect_keyword_not_found`, it precisely **introduced** this hook, on which plugin 404-if-not-found relies :)

This hook fires [just before](https://github.com/YOURLS/YOURLS/blob/1.8/yourls-loader.php#L66-L67) `loader_failed`, which is used by the JSON response plugin, so this plugin never actually runs.

I've filed a pull request on the JSON plugin to update it, so it uses the newer hook -- see https://github.com/tessus/yourls-json-response/pull/1

**Comment by tessus** [comment]
Great, thanks.
