### ISSUE TITLE
One file procedural remake of YOURLS :)

### ISSUE THREAD

**Issue by panreyes** [YOURLS/YOURLS#2850]
Hello! I had some issues configuring YOURLS and ended up doing a 1 PHP file remake of its basic features:
[index.php.txt](https://github.com/YOURLS/YOURLS/files/6043465/index.php.txt)

I hope you find it interesting :)

PS: I took too much time to understand that Google Chrome was caching the 302 redirections and that I had to introduce http:// or https:// in the full URL. That's why I remade it 😅

**Comment by ozh** [comment]
Heh, to each his own :) I'm sure you can make it even shorter !
