### ISSUE TITLE
SQL Bug 1.7.9 to 1.8

### ISSUE THREAD

**Issue by pediehl** [YOURLS/YOURLS#2855]
* [x ] I've read the [Troubleshooting First Steps](https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps)
* [ x] This request isn't a duplicate of an existing issue, opened or closed
* [ x] I've read the [docs](https://yourls.org/) and followed them (if applicable)
* [x ] This is not a personal support request that should be posted on the [YOURLS Discourse](https://discourse.yourls.org/) community

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior. This is mandatory if you expect someone to fix the problem. Example:
First you get an Upgrade Button to SQL. OK was not before OK...
The an SQL-Error Key ist too long.
The System ist not working anymore!
Per Snap back to the working 1.7.9.

**Expected behavior**

**Actual behavior**
The an SQL-Error Key ist too long.
The System ist not working anymore!
Per Snap back to the working 1.7.9.

**Screenshots**

**Versions**
You can get this information from referencing `CHANGELOG.md` or the releases page.
Also, please include:
* The OS and what version of the OS you're running. PHP 7.4 SQL 5
* Plugins or extensions activated if applicable. 

Allow Forward Slashes in Short URLs 
Appends a query string to the URL
Allow hyphens in short URLs (like http://sho.rt/hello-world)
Assign random keywords to shorturls, like bitly (sho.rt/hJudjK)

**Additional context**
Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by ozh** [comment]
So basically the same _very vague_ issue than the one you open just before, but with all the default issue template around. I mean, reading "Any additional information, configuration or data that might be necessary to reproduce the issue." really helps here. 😭 At least now we know what PHP version you're on.

So. The most useful info you're providing is that "The an SQL-Error Key ist too long.". Letting aside that this doesn't make sense, what is the **actual**, real, error message ? A screenshot would be more valuable.

**Comment by pediehl** [comment]
i worte it above PHP Version 7.4 (7.4-latest FPM)
thats a manged thing more details.
All modulues beloging to the Version will be there.
MySQL-Client 5.7 und 8
cURL 7.59
MySQL 5.5
SQL Error:
Upgrade YOURLS
Updating DB. Please wait...

Unable to update the DB.

You will have to manually fix things, sorry for the inconvenience :(

The errors were:

SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

**Comment by ozh** [comment]
Duplicate. Search issues.
