### ISSUE TITLE
Overruling is_private not possible anymore

### ISSUE THREAD

**Issue by Virinum** [YOURLS/YOURLS#2858]
* [x] I've read the [Troubleshooting First Steps](https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps)
* [x] This request isn't a duplicate of an existing issue, opened or closed
* [x] I've read the [docs](https://yourls.org/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [YOURLS Discourse](https://discourse.yourls.org/) community

**Describe the bug**
Overruling `yourls_is_private()` is not possible anymore

**To Reproduce**
1. Set `define( 'YOURLS_PRIVATE', true )` and `define( 'YOURLS_PRIVATE_INFOS', false )`
2. Open info page of a short url
3. See that it's still private

**Expected behavior**
`YOURLS_PRIVATE_INFOS` and `YOURLS_PRIVATE_API` should have any effect.

**Actual behavior**
They don't have any effect.

**Versions**
`1.8`

**Additional context**
The problem is in here:
https://github.com/YOURLS/YOURLS/blob/510851c91866063f3e3bc1ac40c8c4c2caf16293/includes/functions.php#L496-L517
`$private` will always be true.

I will provide a pull request.

**Comment by ozh** [comment]
Hooo, indeed, nice catch, was wondering why I couldn't see http://yourls.org/gandi+ the other day :)
