### ISSUE TITLE
SQL Error on upgrade from 1.7.9 to 1.8.0

### ISSUE THREAD

**Issue by matthiasexl** [YOURLS/YOURLS#2861]
**Describe the bug**
Database Error on Upgrade: "SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-yourlsdb CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci' at line 1"

Server Info:
Ubuntu 18.04.5 LTS
Plesk Obsidian Version 18.0.33
Maria DB 10.3.27
Upgrade Yourls 1.7.9 to 1.8.0

Active Plugins:
Popular Links
GWall Change Logo Plugin Config
Admin NoCaptcha Settings

Any advice is highly appreciated,
thank you,
Matt

**Comment by ozh** [comment]
Duplicate. 2843.
