### ISSUE TITLE
Backtick database name in yourls_upgrade_to_506()

### ISSUE THREAD

**Issue by CDinc** [YOURLS/YOURLS#2863]
My database name has a hyphen in it. MySQL 8 is unhappy with this query from yourls_upgrade_to_506()

'database charset'  => sprintf('ALTER DATABASE %s CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;', YOURLS_DB_NAME)

I just fixed my database and tables manually since that was faster than editing and testing code, but might be a good idea to backtick the database name for cases like this.

**Comment by ozh** [comment]
Fixed in current master since #2844 and will be included in 1.8.1 (probably today)
