### ISSUE TITLE
YOURLS installed in Subdomain

### ISSUE THREAD

**Issue by master3395** [YOURLS/YOURLS#2868]
Hello, i am trying to have yourls installed in a sub domain, not domain.com/subdomain but subdomain.domain.com
And I get weird redirects and errors.

I tried the tutorial here: [https://github.com/YOURLS/YOURLS/wiki/.htaccess#case-yourls-installed-in-subdirectory](https://github.com/YOURLS/YOURLS/wiki/.htaccess#case-yourls-installed-in-subdirectory)
But I get the same result.

I have tried to change the role and permission for the whole folder.
chmod -R 777 /home/domain.com/yourls.domain.com/

I am running yourls on my own vps that has cyberpanel installed. (CyberPanel installs OpenLiteSpeed)
It is running Centos 8 with Webmin and Lamp installed.

Core Php is 7.4.14

The front end is fine, but the admin page shows the error below.

403
Forbidden
Access to this resource on the server is denied!

**Comment by ozh** [comment]
Actual .htaccess ? Actual config.php ? Actual URL of your setup ? There is not one useful info here.

Running YOURLS off domain.com or sub.dom.ain.com is exactly the same.

**Comment by dgw** [comment]
@ozh Can we start directing troubleshooting questions like this to Discussions?
