### ISSUE TITLE
Where I can download the script

### ISSUE THREAD

**Issue by ykbenlee** [YOURLS/YOURLS#2870]
* [ ] I've read the [guidelines for Contributing to YOURLS Projects](https://github.com/YOURLS/.github/blob/master/CONTRIBUTING.md)
* [ ] This request isn't a duplicate of an existing request
* [ ] This is not a personal support request that should be posted on the [YOURLS Discourse](https://discourse.yourls.org/) community

**Summary**
One paragraph explanation of the feature.

**Motivation**
Why are we doing this? What use cases does it support? What is the expected outcome?

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dgw** [comment]
[Seriously?](https://github.com/YOURLS/YOURLS#quick-start)

This is the most RTFM issue I've seen in _years_.
