### ISSUE TITLE
Postgress code supplied, PR?

### ISSUE THREAD

**Issue by iWantToKeepAnon** [YOURLS/YOURLS#2874]
A couple/few years ago I forked YOURLS and converted it to postgress (but in right inline breaking mysql functionality).  I was too green in php then to think it was good code (still am :p) and that I could merge it.  I just pulled in an updated YOURLS codebase and applied my changes in a modular fashion.  If you want, I can file a PR; look it over here:
   *    https://github.com/iWantToKeepAnon/YOURLS/tree/yourls-master

I pulled as much database specific code as I found into "includes/class-<mysql|pgsql>.php".  I removed the mysql specific backtick syntax everywhere I could (mysql will work w/o it and psql won't work with it).  I hacked "docker-entrypoint.sh" over on the docker project:
   * https://github.com/iWantToKeepAnon/docker-yourls
to install pgsql and create the database if pgsql is selected (see "stack.yml" and "stack-pgsql.yml" and "start.bash").

There needs to be a good database selector mechanism, for now I run:
   * cd users && ln -s ../includes/class-pgsql.php ./db.php
and that selects postgress.

Let me know what you think.

**Comment by dgw** [comment]
I know we've been talking about keeping stuff out of the config file, but a new constant is kind of the only reasonable way to select the database type. I propose `YOURLS_DB_TYPE`.

**Comment by iWantToKeepAnon** [comment]
"YOURLS_DB_TYPE" would make sense.  The entry point script triggers off "mysql" and "pgsql" as the docker database network names; which wouldn't work for non-docker setups of course.

**Comment by dgw** [comment]
> if you grant write permissions to YOURLS and docker-yourls

Make a pull request.

**Comment by dgw** [comment]
Long replaced by the linked PR.
