### ISSUE TITLE
I need help with adding the amount of clicks on another site

### ISSUE THREAD

**Issue by alexwalker0** [YOURLS/YOURLS#2880]
I wrote this in the discussions area, and no one answered.

I want to add the number of clicks on another website, so I can display a live / real-time click amount. Could anyone please help me with that? 

Thank you, 
Alex

**Comment by dgw** [comment]
Please don't open an issue if no one answers a discussion question, especially after only such a short time.

**Comment by alexwalker0** [comment]
Ok, I'm sorry
