### ISSUE TITLE
Upgrade YOURLS  ERROR

### ISSUE THREAD

**Issue by master3395** [YOURLS/YOURLS#2891]
Hello, when i tried to update my Yourls install from v 1.7.9
up to 1.8.1
But I stumbled upon this error.
And I can't find the row in order to fix it.
As the rows are not listed as numbers.
What can I do?
And what is the warning even for?

Upgrade YOURLS
Updating DB. Please wait...

Unable to update the DB.

You will have to manually fix things, sorry for the inconvenience :(

The errors were:

SQLSTATE[01000]: Warning: 1265 Data truncated for column 'keyword' at row 1685

**Comment by bmercernccer** [comment]
It looks like there was a value in your previous database that was too long to fit in the new version. It says that the data was truncated for a keyword. That implies that one of your entries had a really long value and in the new version it's been chopped off to make it fit. The keyword is the short string that gets added to your base URL, and it has a maximum length of 100 characters I believe. Look in your old database for an entry with a really long keyword and remove it or shorten it, then try the update again.

**Comment by master3395** [comment]
> It looks like there was a value in your previous database that was too long to fit in the new version. It says that the data was truncated for a keyword. That implies that one of your entries had a really long value and in the new version it's been chopped off to make it fit. The keyword is the short string that gets added to your base URL, and it has a maximum length of 100 characters I believe. Look in your old database for an entry with a really long keyword and remove it or shorten it, then try the update again.

How can I force all keywords at a length?
I don't want to go over all and check one by one when I got thousands.

**Comment by bmercernccer** [comment]
Pull  up the list of URLs in the admin UI and show all of them at once by entering a big number in the Show Rows box, then scroll through the list looking for any extremely long values or any values that look strange compared to others. 

This is just one possibility. The problem might also be something else, such as invalid characters in a field causing data to be parsed incorrectly.

**Comment by ozh** [comment]
Use a tool like phpmyadmin to inspect table `yourls_url` and try this : 

```sql
SET @row_number = 0; 
SELECT 
    (@row_number:=@row_number + 1) AS num, 
    keyword, 
    url
FROM
    yourls_url
```

This will number the rows
