### ISSUE TITLE
ezSQL

### ISSUE THREAD

**Issue by techarchsoftwares** [YOURLS/YOURLS#2892]
Hey Guys,

We were using the MS SQL database with version [1.7.2] but now we are updating it with latest version and MS SQL connection not working.

I have noticed that after [1.7.2] eqSQL library has been removed from the included folder. Can anybody help with this?

**Comment by ozh** [comment]
I think your best shot is too have a look at #2875

**Comment by techarchsoftwares** [comment]
Hi, I tried the same https://github.com/YOURLS/YOURLS/pull/2875 but it still show the same error with MSSQL database.

Screenshot: https://prnt.sc/111fr01

Can you please guide me in details.

**Comment by ozh** [comment]
Sorry for the misunderstanding, unfortunately I didn't mean "just take the code from 2875 and it'll work" :)
I meant : from this code, *modify what you need to enable MS SQL support*. 

The goal wouldn't be to ship YOURLS with MS SQL support, but to allow it with a plugin. If something in core is to be modified to allow such plugin support, I'll happily merge pull requests!

**Comment by techarchsoftwares** [comment]
okay, So is there any pull request where any one is able to enable MS SQL support.

**Comment by ozh** [comment]
Errr, no. I'm afraid we're not understanding each other here :)
There will be a pull request to (if needed) modify core files to allow MS SQL support when someone interested in MS SQL support will open one :)
