### ISSUE TITLE
APC Cache Plugins no longer valid with PHP 8

### ISSUE THREAD

**Issue by Swampcritter** [YOURLS/YOURLS#2895]
* [X ] I've read the [Troubleshooting First Steps](https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps)
* [ X] This request isn't a duplicate of an existing issue, opened or closed
* [ X] I've read the [docs](https://yourls.org/) and followed them (if applicable)
* [ X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions)

**Describe the bug**
Upon installing PHP 8.x on CentOS 7 platform, the PHP APC module is considered depreciated so the newer APCu PHP module is required now. I downloaded and installed the APCu PHP8 module installed on the server. When I attempted to enable either the APC Cache plugin or YAPCache, a APC extension error message appears and prevents the plugin page from appearing.

This error message appears:
This plugin requires the APC extension: http://pecl.php.net/package/APC

**Additional context**
https://computingforgeeks.com/how-to-install-php-8-on-centos-linux/
https://shouts.dev/install-apcu-on-centos-7

**Comment by ozh** [comment]
Then open an issue on the plugins' repos ?
