### ISSUE TITLE
Custom URLs returning 403 in NGINX configuration

### ISSUE THREAD

**Issue by Selnewehy** [YOURLS/YOURLS#2898]
`server {

  # HTTP over IPv4 & IPv6
  listen 80;
  listen [::]:80;

  # Server names
  # MUST BE EDITED TO REFLECT YOUR CONFIGURATION
  server_name s.aiesec.org.eg;

  # Root directory
  # MUST BE EDITED TO REFLECT YOUR CONFIGURATION
  root /var/www/link;

  # Rewrites
  location / {
    try_files $uri $uri/ /yourls-loader.php$is_args$args;
  }

  # PHP engine
  location ~ \.php$ {
    include fastcgi.conf;
    # OR
    include fastcgi_params;
    include snippets/fastcgi-php.conf;
    fastcgi_index index.php;
    
    # MUST BE EDITED TO REFLECT YOUR CONFIGURATION
    fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
  }

}`

**Comment by ozh** [comment]
https://github.com/YOURLS/YOURLS/wiki/Nginx-configuration
