### ISSUE TITLE
urlencoded parameters not handled correctly (percent-encoding)

### ISSUE THREAD

**Issue by tapionx** [YOURLS/YOURLS#2903]
**Describe the bug**

I'm not able to use the service (via API) to shorten an URL containing an email address with a `+`.
an URL containing ... `?email=test+123@example.com`
and sent to API correctly urlencoded: `%3Femail%3Dtest%2B123%40example.com`
after being shortened is returned incorrectly: `?email=test+123@example.com`

The software should return instead: `?email=test%2B123%40example.com`

**To Reproduce**

1. Install YOURLS version 1.8.1
2. send an API request to shorten the URL `http://example.com?email=test+123@example.com`:
`$ http "http://localhost:8080/yourls-api.php?signature=CHANGEME&action=shorturl&format=json&url=https%3A%2F%2Fexample.com%3Femail%3Dtest%2B123%40example.com"`
3. Retrieve the shortened URL and expand it
4. Check that return URL is `https://example.com?email=test+123@example.com`
but instead it should be: `https://example.com?email=test%2B123%40example.com`

**Expected behavior**

**Actual behavior**

**Screenshots**

![2021-04-15_14-58](https://user-images.githubusercontent.com/1826929/114873043-32d36900-9dfb-11eb-979c-b291460b2129.png)

**Versions**
1.8.1 (last release)

**Comment by tapionx** [comment]
Partially correct.
In the web interface the input would be: `https://example.com/?email=test%2B123%40example.com`
And it correctly gives back the same: `https://example.com/?email=test%2B123%40example.com`

You are right about the encoding in the API *but*, is there a way to achieve the desired behavior?

**Comment by ozh** [comment]
Well, per your example the input in the web interface would be `https://example.com/?email=test+123@example.com` and this is [correctly stored](https://yourls.org/ex)

If you want the result to be `?email=test%2B123%40example.com` then it has to be your input... (as is in the web interface, or URL encoded if using the API)

**Comment by tapionx** [comment]
@ozh you are right, the input was not correct. 

If i input `urlencode("?email=test%2B123%40example.com")` I get the same as output! :+1:
