### ISSUE TITLE
German Translation broke at Date

### ISSUE THREAD

**Issue by philw95** [YOURLS/YOURLS#2904]
* [X] I've read the [Troubleshooting First Steps](https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps)
* [X] This request isn't a duplicate of an existing issue, opened or closed
* [X] I've read the [docs](https://yourls.org/) and followed them (if applicable)
* [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions)

**Describe the bug**

I have upgraded from version 1.7.9 to 1.8.1.

Since then the date column breaks.

This is how it should look like: (1.7.9)
<img width="729" alt="h4XgiHdl1I" src="https://user-images.githubusercontent.com/27635979/114922990-97f38280-9e2c-11eb-82bd-ebebdd496cbc.png">

this is what it looks like: (1.8.1)
<img width="717" alt="DHXYiPfPVs" src="https://user-images.githubusercontent.com/27635979/114923028-a2ae1780-9e2c-11eb-9a92-49203c5ca36f.png">

**To Reproduce**

1. Change the Language to "de_DE" in the config.
2. See error

it is only in the German Translate.

**Expected behavior**

Looks like:
Apr 10, 2021 22:45

If it is possible this would be even better:
10 Apr 2021 22:45
But only if it is not so much trouble.

**Actual behavior**

**Screenshots**

See above

**Versions**
You can get this information from referencing `CHANGELOG.md` or the releases page.
Also, please include:
* The OS and what version of the OS you're running.
* Plugins or extensions activated if applicable.

**Additional context**

**Comment by ozh** [comment]
Regarding the date formatting (ie dd/mm/yyyy or mm/dd/yy or whatever), see this plugin : https://github.com/YOURLS/timezones

Regarding the date translation, the problem must be in the translation file itself (I've checked the French translation for instance and everything looks OK) -- see #2848. Please contact the translation author.

**Comment by philw95** [comment]
Oh Thanks.
I have loaded the New file and Now it works Thanks.

And thanks for the Date formatting Plugin 👍
