### ISSUE TITLE
[poll] If YOURLS had support for custom themes

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#2915]
[crossposting from [Twitter](https://twitter.com/ozh/status/1387810235377664002)]

People who code stuff for YOURLS : if YOURLS had support for custom themes, would you prefer it with:
1) templates, a la Twig (left) 
2) PHP+HTML, a la WordPress (right)
Or maybe
3) whichever, would be neat anyway

![image](https://user-images.githubusercontent.com/223647/116611140-512a8000-a936-11eb-97d1-df34b9c81f1e.png)

**Please respond with a "reaction"** (upper right corner of this issue) in order to limit the number of emails sent to everybody watching this repo :)

* Option 1, Twig style : 🚀 
* Option 2, PHP+HTML : 👀 
* Option 3, whichever : 👍

**Comment by mwllgr** [comment]
Just my personal opinion: "Twig style" looks cleaner. I just can't look at a PHP + HTML mixed-mess.

**Comment by clmcavaney** [comment]
I like the Twig template model it provides a cleaner model view control implementation.
