### ISSUE TITLE
Overview action buttons disabled after editing short URL & saving & editing again

### ISSUE THREAD

**Issue by stewil87** [YOURLS/YOURLS#2925]
* [x ] I've read the [Troubleshooting First Steps](https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps)
* [x ] This request isn't a duplicate of an existing issue, opened or closed
* [x ] I've read the [docs](https://yourls.org/) and followed them (if applicable)
* [x ] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions)

**Describe the bug**

After some editing, the action buttons stay disabled.

**To Reproduce**

0. Install a fresh YOURLS version from Github. Setup. Login
1. Click on action 'edit' from one of the example links
2. Change for example 'short URL' and hit 'save'
3. Click on action 'edit' again
4. Now just click on cancel
5. the actions buttons for that link are still disabled

**Expected behavior**
After 4: the Action buttons should be usable again

**Actual behavior**
After 2: the new hidden editform has a wrong ID.

**Versions**
1.8.1

**Additional context**
This might be connected to https://github.com/YOURLS/YOURLS/pull/2065
The difference is that, they dont change any content before the buttons appear disabled.

**Comment by ozh** [comment]
I definitely cannot reproduce, latest YOURLS & latest Firefox

**Comment by zapperpro** [comment]
Ok. Thats strange. I also can reproduce in Chrome stable (90) and Firefox stable (88). I also extra downloaded and installed a fresh version without any plugins.

I can see this behavior on local machine with windows php inbuild server, also online on linux based apache server

**Comment by zapperpro** [comment]
Hey. I also created a video. Maybe this helps, if I was unable to explain correctly:
https://www.youtube.com/watch?v=00c0wjmpcX4

**Comment by ozh** [comment]
OK. I couldn't reproduce editing the title but indeed I can reproduce editing the short URL.

Each HTML element in a row is given an ID that is computed from its shortURL ([here](https://github.com/YOURLS/YOURLS/blob/master/includes/functions-html.php#L524)) but when the short URL is changed, we're not updating that ID. I think. Hence the bug.

So, confirmed and low priority as far as I'm concern. Current fix is "Hit F5" 😛
