### ISSUE TITLE
Hyphens in Yourls URLs

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#294]
This is a **COPY** of **Issue 294: [Hyphens in Yourls URLs](http://code.google.com/p/yourls/issues/detail?id=294)**, filed on Google Code before the project was [moved on Github](https://github.com/ozh/google-issues-to-github).
- Submitted on 2010-04-05T18:08:42.000Z by [jfle...@gmail.com](http://code.google.com/u/106520194408134252939/)
- Status: Duplicate

Please **review** the original issue and especially its comments. **Comments here on closed issues will be ignored**. Thanks.
## Original description

```
Can we please have hypens/dashes in Yourls URLs? They would be useful to break up words within 
descriptive URLs.
```

**Comment by jcubic** [comment]
Why this is closed. Why dashes are not supported?

**Comment by dgw** [comment]
It's [Possible with a Plugin](https://docs.yourls.org/guide/extend/possible-with-a-plugin.html), and in fact [a plugin to do exactly this](https://github.com/YOURLS/YOURLS/tree/1.9.1/user/plugins/hyphens-in-urls) is included with the default YOURLS installation package.
