### ISSUE TITLE
Short Link Keeps adding long link

### ISSUE THREAD

**Issue by CrazyGoose** [YOURLS/YOURLS#2960]
I have changed nothing. So I am unsure why this just started.

For example: I shorten the URL -  Fast.com
The long link becomes https://urls.xxxxx.com/admin/fast.com
The long link does not say https://urls.xxxx.com/admin/fast.com but when I hover over the link that is what I get.

The admin interface shows a yellow star next to the long link.
'I click on the link and it takes me to https://urls.xxxxx.com and I get a 404 error

What is going on?

**Comment by CrazyGoose** [comment]
if the link does not already have http:// at the beginning then I get the issue above.  I just make sure to always append http is it isn't present.

**Comment by ozh** [comment]
Expected behavior : not all links to be shortened are "http://"
