### ISSUE TITLE
Log Creating User and Add Show Owned Links Only Option

### ISSUE THREAD

**Issue by joepitt91** [YOURLS/YOURLS#2963]
* [x] I've read the [guidelines for Contributing to YOURLS Projects](https://github.com/YOURLS/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing request
* [x] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions)

**Summary**
It would be good if the database logged which user created each URL.

It would also be good to have the option to limit URL listing to only the links created by the current user.

**Motivation**
In most environments there is a requirement for some level of accountability of actions, logging who created a link would provide a starting point.

In many use cases, you may want to allow many authorised users to create new links, and see the statistics for their links, without this functionality being public; but, not want to grant everyone visibility and control over other users links. 

If many users are creating many links, the admin interface can get full up with many links which are not of interest to the logged in admin, limiting to the logged in user would make it easier to manage the links they created.

While a determined user would be able to enumerate existing links to work out what short codes go where, this would likely be noisy and could be spotted in logs, and having the option to only show users their own links would provide a level of privacy and make it easier for users on systems with lots of links to manage just their own links.

**Is your feature request related to a problem? Please describe.**
Lack of accountability of actions, large list of irrelevant URLs on busy deployments, and lack of privacy for links users create for personal use.

**Describe the solution you'd like**
* A `creator` column in the `url` database table containing the logged in username.
* A Creator column in the admin URL table
* An Orphaned tab showing any URLs created by users that are no longer in `$yourls_user_passwords` in `config.php`.
* A `YOURLS_OWNED_ONLY` boolean option in  `config.php` to restrict users to only see URLs where `creator` matches their username, default `False` for backwards compatibility.
* A second user list `$yourls_admin_passwords` that gets an additional tab on admin page, to see **all** URLs, from all users, when `YOURLS_OWNED` is enabled.

**Describe alternatives you've considered**
No obvious alternative solution that delivers all of the above.

**Additional context**
I did my best to search for similar requests, so hope this isn't a duplicate. 

Keen to hear thoughts on the idea

**Comment by dgw** [comment]
This is most certainly already possible with a plugin, for example https://github.com/ianbarber/Yourls-Separate-Users or https://github.com/keslar/yourls-multi-user

I've no idea how up-to-date these are, but it's clearly not something that has to be part of YOURLS' core.

**Comment by ozh** [comment]
Yeah, user management has always been more or less on the roadmapish, see #1255. Probably something that would be best implementable as a plugin, as @dgw said (most users just don't need it). See the issue I linked for thoughts on implementation (which would definitely not be via another constant or global variable)
