### ISSUE TITLE
yourls-api.php generates error on private install

### ISSUE THREAD

**Issue by s22-tech** [YOURLS/YOURLS#2973]
**Describe the bug**
I have a private install of Yourls.  I decided to go directly to www.my-domain.com/yourls-api.php to see what was displayed.  I was hoping for a blank page, or something else that didn’t give away that I was running Yourls, but instead I get this:

```

XML Parsing Error: junk after document element
Location: https://my-domain.com/yourls-api.php
Line Number 1, Column 70:
		<style>ul#admin_menu li:not(.frontend_link) {display: none}</style><?xml version="1.0"?>
-----------------------------------------------------------------------------------^
```

The source code for the above is:

```
<style>ul#admin_menu li:not(.frontend_link) {display: none}</style><?xml version="1.0"?>
<root><message>Please log in</message><errorCode>403</errorCode><callback></callback></root>
```

It looks like a 403 is being generated by Yourls (maybe there's an error in the XML?).

**To Reproduce**
In a browser, go directly to www.my-domain.com/yourls-api.php

**Expected behavior**
Blank screen or customizable information displayed.  At the very least, no error.

**Versions**
Yourls 1.8.1
CentOS

**Additional context**
I tried adding this to yourls-api.php:

```
if (empty($_GET)) {
   yourls_redirect( YOURLS_SITE, 302 );
}
```

but it’s ignored and the message is still displayed.

**Comment by dgw** [comment]
What happens if you visit https://yourls.org/yourls-api.php?

A 403 error is exactly what's expected here. The client hasn't logged in, and so access to the resource is Forbidden. The XML describes the error condition.

**Comment by s22-tech** [comment]
I found the problem.  It turned out to be Sleeky.  I'm surprised by that, as I don't have it's frontend installed.  I'll contact Flynn.

---

Since I'm not using the API at all, I don't want even a 403 shown, so I made the following change in /includes/auth.php

```
if ( $auth !== true ) {

	// API mode,
	if ( yourls_is_API() ) {
// 		$format = ( isset($_REQUEST['format']) ? $_REQUEST['format'] : 'xml' );
// 		$callback = ( isset($_REQUEST['callback']) ? $_REQUEST['callback'] : '' );
// 		yourls_api_output( $format, array(
// 			'simple' => $auth,
// 			'message' => $auth,
// 			'errorCode' => 403,
// 			'callback' => $callback,
// 		) );

		header('Location: index.php');
```

Perhaps a setting could be added to Yourls so those of us not using the API can block it completely?

Thanks.

**Comment by roslantangah** [comment]
any complete solution for this?

**Comment by matthewpkemp** [comment]
If you aren't using the API I would suggest a block on your webserver or web application firewall.
