### ISSUE TITLE
Remove the literal usage of hateful words in your readme

### ISSUE THREAD

**Issue by ObedAmpah** [YOURLS/YOURLS#2983]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Summary

In your docs:

```yourls_reserved_URL
A list of reserved keywords that won't be used as short URLs. Define here negative, unwanted or potentially misleading keywords
Example: 'porn', 'faggot', 'sex', 'nigger', 'fuck', 'cunt', 'dick'
```

There's no reason to explicitly write out these words that you want to reserve (limit) usage of, in your examples. I don't think I need to see the N-word to know that it can be considered a reserve word example. 

''Example: 'porn',  'sex', 'fuck', 'cunt', 'dick', and any other negative terms"

### Motivation

Because words like that don't need to be a part of your documentation.

### Describe the solution

Remove it and detail that such words can be reserved.

**Comment by dgw** [comment]
This is like #2459 but for the documentation instead.

Since the sample configuration [already includes](https://github.com/YOURLS/YOURLS/blob/976b18e1c827b77c5fd2930184fe17a083021476/user/config-sample.php#L81-L87) this set of examples, I agree that the actual words needn't be in the docs too.

**Comment by ozh** [comment]
I was going to write "_I cannot accurately describe how profoundly uninterested I am, to be honest :)_", but in all honesty I'm also quite amused that every 4 or 5 years someone comes to express that they are offended by reading a word :)

**Comment by wgicio** [comment]
The word "sex" could be considered too offensive to read for incels

**Comment by cetcondor** [comment]
Please allow me to disagree with the suggested deletion. Of course I support the functionality of restricting certain words, but some of the concrete examples are actually helpful. Documentation should be helpful and not obscuring things. Three examples: 

- "dick" also restricts "Dick Cheney" or "Dick Tracy".
- "porn" is a very common part of names in Thai language. 
- And the filter would also restrict any scientific or societal article about porn, which is also a bit strange.

**Comment by dertuxmalwieder** [comment]
I agree with ozh here.
