### ISSUE TITLE
Plugin Updater

### ISSUE THREAD

**Issue by master3395** [YOURLS/YOURLS#2985]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Summary

When plugins get updates, it is hard to keep up to speed on all the updates.

### Motivation

Keeping every update "up to date" will help with security and issue fixes.
The expected outcome would be that every plugin can be faster updated to the latest plugin.php version.
Making sure every Yourls installer safer and plugin support issues might be minimal if updates can be done from a plugin or from the yourls installation itself.

### Describe the solution

Over the years I've seen many installations of Yourls, that have failed because of outdated plugins.
Because of that, a lot of people stop using plugins that might benefit them.

If they were to have an easier way of updating their plugins, then they might start using plugins again, if they run into problems, they could simply try and update their plugins (if they have updates).

PS: I know that you can download plugins using https://github.com/krissss/yourls-download-plugin.
But it won't really be a supplement to an updater.

**Comment by joshp23** [comment]
Very possible with a plugin. 

https://github.com/joshp23/YOURLS-PUNS

**Comment by ozh** [comment]
As Josh says, it's definitely plugin territory.

For the record, as of writing, 67% of YOURLS install have 0 active plugins, and 11.5% have only 1.
