### ISSUE TITLE
Privacy link in footer

### ISSUE THREAD

**Issue by cetcondor** [YOURLS/YOURLS#2989]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Summary

The footer (e.g. visible at the login page) should have a "privacy" link. The target should be configurable.

### Motivation

The European Privacy Law ("General Data Protection Regulation" or short "GDPR") makes it mandatory for site owners to inform their users about processing of any personal data. IP addresses are considered personal data. In order to make a YOURLS deployment GDPR-compliant, at least somewhere such information should be made available.
Being able to add a simple link in the YOURLS footer, to an already existing privacy information (e.g. at one's regular website), would be the easiest solution.

### Describe the solution

see above.
Thank you for your great work!

**Comment by matthewpkemp** [comment]
@cetcondor would it make sense for this to be a plugin for those complying w/ GDPR vs embedded into the code base?  While having it embedded in the admin page for some folks may solve the issue, if it's a non-public admin interface many folks may not see this information.

**Comment by cetcondor** [comment]
@matthewpkemp Yes, your proposal sounds very reasonable to me (and my technical knowledge is anyway too limited to understand which way of implementation is good for the code base).

**Comment by ozh** [comment]
For what it's worth, see my answer on https://github.com/YOURLS/YOURLS/issues/2395 regarding GDPR.

I think it's plugin territory and would happily merge a pull request if needed to make such plugin possible
