### ISSUE TITLE
Metadata not displayed in httpd (apache) on Facebook/WhatsApp/IG

### ISSUE THREAD

**Issue by pohjoon** [YOURLS/YOURLS#3001]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps) guide.

### Version

1.8.1

### Description

Hi there,

I'm running Yourls on AWS EC2 httpd (Apache) under a subdirectory named "link" after the root, the main domain is pointing to the root.
Sample link -> www[dot]abc[dot]com/link/cEDs2

I am able to run the admin portal, shorten URLs and redirect etc, when I paste the shorten URL on Facebook and IG, the meta image shows up but not in WhatsApp. Also, the QR plugin does not work for me, it shows "The requested URL was not found on this server."
 
Below is the .htaccess file content:

_# BEGIN YOURLS
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /link/
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^.*$ /link/yourls-loader.php [L]
</IfModule>
# END YOURLS_

Appreciate your help on this. Thanks

**Comment by ozh** [comment]
Hello,

> when I paste the shorten URL on Facebook and IG, the meta image shows up but not in WhatsApp

So, YOURLS is working. I'm not familiar with how WA works.

> Also, the QR plugin does not work for me

There are like 7 QR code plugins in https://github.com/YOURLS/awesome-yourls
