### ISSUE TITLE
security vulnerability on expiry plugin

### ISSUE THREAD

**Issue by samira-karimi-elfiman** [YOURLS/YOURLS#3006]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps) guide.

### Version

2.4.1

### Description

hi

I found a security vulnerability on expiry plugin
How can I report this?

Good Luck

### Expectation

-

### Reproduction steps

-

### Context

-

**Comment by dgw** [comment]
Not here. It's up to @joshp23 to respond at joshp23/YOURLS-Expiry#37
