### ISSUE TITLE
Prevent YOURLS from displaying encryption warning when password is provided via environment variables

### ISSUE THREAD

**Issue by bryanpedini** [YOURLS/YOURLS#3038]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Summary

Since YOURLS 1.7 as per documentation, the software automatically encrypts passwords.
This is not true (of course) for the user provided by environment variables (e.g. Docker).

### Motivation

Just an annoying little error that does not cause any harm but still, it's an error which is actually not true.

### Describe the solution

Check if the array contains only one element (the usual case when providing YOURLS_USER via environment variable) and if true check if the YOURLS_USER and YOURLS_PASS variables are set from environment, in case both checks are true do not even bother to call the function that tries to encrypt the password.

Maybe, just a quick, dirty solution (first that came in my mind, feel free to propose / do something else).
Thanks!

**Comment by ozh** [comment]
A valid point, thanks for raising. Will look into this.

**Comment by bryanpedini** [comment]
Maybe I can refresh some PHP memories and take a look into creating a PR for this if it's welcome (I don't code PHP from quite a while, since my PHP 8.0 framework that I built).....

**Comment by ozh** [comment]
If you can look into this that would be great, indeed!

How I see things after quick toughts : 
- function [`yourls_hash_passwords_now()`](https://github.com/YOURLS/YOURLS/blob/7e06aa1068fb6481834ca95017b4f206d39c2c30/includes/functions-auth.php#L170) is best left unmodified. Its goal is to hash, not to decide if it should hash.
- the test for an env var would be then introduced at [includes/auth.php#L44](https://github.com/YOURLS/YOURLS/blob/7e06aa1068fb6481834ca95017b4f206d39c2c30/includes/auth.php#L44) with a new function like `yourls_user_is_from_env()` or something like this
- a unit test for this new function would be neat

Thoughts ?

**Comment by bryanpedini** [comment]
> Thoughts ?

Nothing concrete yet, I still haven't touched the codebase nor have I looked at how things are structured so that I can formulate a serious proposal about how to implement this.
