### ISSUE TITLE
YOURLS api access always return HTTP 406 error 

### ISSUE THREAD

**Issue by revenger98** [YOURLS/YOURLS#3039]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps) guide.

### Version

1.8.1

### Description

To any API request (expand, shorten), I only get  : 

yourls.YourlsOperationError: "Error with url 'https://sergayenelperu.com/short/11q' - HTTP Error 406: Not Acceptable"

------
And my python code is so simple and was working until two weeks ago:

import yourls.client

shurl = yourls.client.YourlsClient('http://serxxx.com/short/yourls-api.php',username='xxx',password='xxxxx')

#qurl = 'https://serxxx.com/1323-dog-2008'
#url = shurl.shorten(qurl)

xurl = "https://serxxx.com/short/11q"
url = shurl.expand(xurl)

print  url

---------
Web-based YOURLS Admin runs ok using it to get it shorten, problem comes from API works

### Expectation

Check API error triggers 

### Reproduction steps

1. Copy my python code with your data
2. Try it 
3. I always get : 
4. Traceback (most recent call last):
  File "acortar.py", line 13, in <module>
    url = shurl.expand(xurl)
  File "/usr/local/lib/python2.7/dist-packages/yourls/client.py", line 151, in expand
    raw_data = self._base_request(args, shorturl)
  File "/usr/local/lib/python2.7/dist-packages/yourls/client.py", line 99, in _base_request
    raise YourlsOperationError(url, str(error))
yourls.YourlsOperationError: "Error with url 'https://sergayenelperu.com/short/11q' - HTTP Error 406: Not Acceptable"

### Context

My YOURLS service was installed by SOFTACULOUS in my HTTP host paid-service

**Comment by ozh** [comment]
This isn't a YOURLS problem. I don't think I've even implemented that error code somewhere. Most likely the python lib you're using.
