### ISSUE TITLE
Default interface width

### ISSUE THREAD

**Issue by ookris** [YOURLS/YOURLS#3059]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Summary

Consider increasing the interface width from the default 950px to a slightly larger value.

### Motivation

Increasing the width will allow you to navigate the interface more efficiently and improve its readability, especially if the Random Keyword Length is greater than 5 characters.

**Comment by ozh** [comment]
This is more a personal need than an issue per se, especially the problem described and the solution proposed don't cover much.

FYI there are custom themes that may suit your needs. See https://github.com/YOURLS/awesome-yourls
