### ISSUE TITLE
Internal Server Error with URL over 8k

### ISSUE THREAD

**Issue by d-danger** [YOURLS/YOURLS#3065]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps) guide.

### Version

1.8.2

### Description

I realise this is probably something that needs to be done on my server and not by YOURLS but please help if you can. 

Everything is working fine until the long URL goes over 8k in characters, at which point when it tries to redirect from the short URL to the long URL I get an **Internal Server Error** page and when I check the server logs all I get is: **Premature end of script headers: yourls-loader.php**

I've done:
**LimitRequestLine 1000000**
**LimitRequestFieldSize 1000000**
in Apache directives which have resolved a **414 URI Too Long** error when I loaded the long URL manually (both short and long URLs are on the same server) but the redirect must need some other fix that I can't find.

**Comment by ozh** [comment]
YOURLS shouldn't be traumatized with this. Internally, it can store URL up to 64K.

How does your server itself handle it ? Simple test file : 
```php
<?php
$url = 'http://somethingveryveryveeeeerrryyyyyylong';
header("Location: $url");
?>
```

**Comment by d-danger** [comment]
This is an Apache thing: https://bz.apache.org/bugzilla/show_bug.cgi?id=64919

I'll close this now.

**Comment by DimaKalbfleysh** [comment]
Hi I am using **YOURLS** in **docker**. I have the same problem. Please tell me how to solve this problem in **docker**

**Comment by DimaKalbfleysh** [comment]
> Hi I am using **YOURLS** in **docker**. I have the same problem. Please tell me how to solve this problem in **docker**

I fix it used POST API request
