### ISSUE TITLE
Auto-redirect to /admin if accessing / - setting

### ISSUE THREAD

**Issue by szitnik** [YOURLS/YOURLS#3077]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Summary

I do not like to add trailing /admin to url for the admin page. Therefore I propose to update .htaccess as proposed. There an also be a setting that would enable redirect to admin page from /.

### Motivation

I do not like to add trailing /admin to url for the admin page.

### Describe the solution

I propose to generate .htaccess as follows:

```


# BEGIN YOURLS
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /

# for /
RewriteCond %{HTTP_HOST} ^YOUR_DOMAIN$ [NC]
RewriteCond %{QUERY_STRING} ![a-zA-Z0-9]
RewriteRule ^$ https://YOUR_DOMAIN/admin [L,R=301]

# for links
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^.*$ /yourls-loader.php [L]
</IfModule>
# END YOURLS

```

**Comment by ozh** [comment]
That's personal preference. Some people actually use the root page to display informations, or stats. Some people redirect their short domain root to their main domain. To each their own.
