### ISSUE TITLE
Yourls eats Google Cloud proxy hostname

### ISSUE THREAD

**Issue by webb-ben** [YOURLS/YOURLS#3101]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps) guide.

### Version

1.8.2

### Description

Google Cloud SQL Proxy allows for easier connections between a Cloud SQL instance and a Cloud Run container. The YOURLS_HOST that I have been using as per, #1589 and #1743 has been `127.0.0.1;unix_socket=/cloudsql/geoconnex-us:us-central1:yourls-mysql`, but the connection continues to be refused on GCP despite proper credentials. 

### Expectation

Yourls would be able to connect to the MySQL cloud database using the proper socket and host.

### Reproduction steps

1. Go to http://sandbox.onlinephpfunctions.com/code/fe0f6aa084a533ce300add9d82b0bd13806854c8
2. Output $dbhost is incorrectly mutated to `127.0.0.1;unix_socket=/cloudsql/geoconnex-us;port=0`

### Context

I believe the issue lies here:
https://github.com/YOURLS/YOURLS/blob/118c7e6627c5d6c127da37cf3838f2c0636bf80d/includes/class-mysql.php#L27-L31

While the port in `$dbhost` is always going to be number, the splitting of `$dbhost` happens without checking that the latter element of the string split is a number/port, thus mutating the socket address.

I tried a (measly) attempt to write a [plugin workaround](https://github.com/webb-ben/pids.geoconnex.us/tree/dev/yourls/plugins/gcloudsql) using URL encoding/decoding and the dsn-hook. I stopped when I realized that even on a preconfigured mysql server, the initial connection should always fail because `yourls` cannot retrieve the plugin data from `yourls.options` in the first place needed to amend how to connect to the database. 

PHP isn't my forte so maybe I missed something entirely. Thanks for all you do!

**Comment by dgw** [comment]
@webb-ben If you have a working `db.php` and you're willing to share it, this is a great place to do so. Anyone in the future searching for "Google Cloud" will find this issue, and then your solution. 😸

**Comment by mli-gal** [comment]
@webb-ben Could you please share your db.php file with details of what you've implemented to fix this issue ?
Thx

**Comment by webb-ben** [comment]
@dgw That is a good idea. Heh :) @mli-gal Look at [/pids.geoconnex.us/yourls](https://github.com/internetofwater/pids.geoconnex.us/blob/f18a553a2e63a591eb2342d5675d9e269945a5b4/yourls/db.php) and then I move it to the appropriate spot in this [Dockerfile](https://github.com/internetofwater/pids.geoconnex.us/blob/f18a553a2e63a591eb2342d5675d9e269945a5b4/yourls/Dockerfile). Good Luck! and let me know if there is anything I can do to help out.

**Comment by ozh** [comment]
Neat if this works. It may help other users.

FYI your whole db.php could be replaced with a one liner plugin, since all you need if I'm correct is to hook into `db_connect_custom_dsn` to add the `$socketDir`

**Comment by webb-ben** [comment]
@ozh I am a big fan of yours (and yourls) and I want to commend you on how cool the plugin architecture is. I tried to implement a plugin like that [here](https://github.com/internetofwater/pids.geoconnex.us/tree/main/yourls/plugins/gcloudsql). Instead of harvesting environment variables for the socket using url decoding. That being said, I am not sure how to auto-enable the plugin. I understand how to do it insofar as using backups of the MySQL database for CI/CD of 400K+ redirects. I get stuck when I need to enable the plugin before the initial connection to the database (i.e. before `yourls.yourls_options.active_plugins` is read). I actually have a couple of other plugins I have worked on for this geoconnex.us that might also be added to awesome yourls, but I have been too intimidated! heh! Definitely something to think about. Thank you again for your work!

**Comment by ozh** [comment]
YOURLS has the little known ability to load a "plugin" before everything is loaded (ie you don't get to activate or deactivate it), if it is named `cache.php` or `db.php` in the user/ directory (see https://github.com/YOURLS/YOURLS/blob/master/includes/Config/Init.php#L55-L63)
