### ISSUE TITLE
520 Error on Trying to Shorten data:image URL

### ISSUE THREAD

**Issue by SirOMGitsYOU** [YOURLS/YOURLS#3109]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps) guide.

### Version

1.8.2

### Description

When submitting the following url 
`https://img.shields.io/static/v1?label=&message=Website&color=119DA4&labelColor=FFC857&style=for-the-badge&logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASAAAAEgCAYAAAAUg66AAAAACXBIWXMAAAsTAAALEwEAmpwYAAAF52lUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS42LWMxNDUgNzkuMTYzNDk5LCAyMDE4LzA4LzEzLTE2OjQwOjIyICAgICAgICAiPiA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPiA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtbG5zOmRjPSJodHRwOi8vcHVybC5vcmcvZGMvZWxlbWVudHMvMS4xLyIgeG1sbnM6cGhvdG9zaG9wPSJodHRwOi8vbnMuYWRvYmUuY29tL3Bob3Rvc2hvcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21tLyIgeG1sbnM6c3RFdnQ9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZUV2ZW50IyIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ0MgMjAxOSAoTWFjaW50b3NoKSIgeG1wOkNyZWF0ZURhdGU9IjIwMjEtMTEtMDRUMTQ6MjQ6MTBaIiB4bXA6TW9kaWZ5RGF0ZT0iMjAyMS0xMS0wNFQxNDoyNDozOVoiIHhtcDpNZXRhZGF0YURhdGU9IjIwMjEtMTEtMDRUMTQ6MjQ6MzlaIiBkYzpmb3JtYXQ9ImltYWdlL3BuZyIgcGhvdG9zaG9wOkNvbG9yTW9kZT0iMyIgcGhvdG9zaG9wOklDQ1Byb2ZpbGU9InNSR0IgSUVDNjE5NjYtMi4xIiB4bXBNTTpJbnN0YW5jZUlEPSJ4bXAuaWlkOjc0YTJiN2IyLWJiYjYtNDAxMC1iOTExLWQ1N2YyNGNhOGY3MCIgeG1wTU06RG9jdW1lbnRJRD0iYWRvYmU6ZG9jaWQ6cGhvdG9zaG9wOjI0MzQ5YWE3LTkzZDAtYWI0OS1iOWJhLTQzMWU5MjgyMmMxNyIgeG1wTU06T3JpZ2luYWxEb2N1bWVudElEPSJ4bXAuZGlkOmZkNDcxNDI3LTk3ZDItNDRlOC04MjNhLTFiZTA4YzkyODY3MiI+IDx4bXBNTTpIaXN0b3J5PiA8cmRmOlNlcT4gPHJkZjpsaSBzdEV2dDphY3Rpb249ImNyZWF0ZWQiIHN0RXZ0Omluc3RhbmNlSUQ9InhtcC5paWQ6ZmQ0NzE0MjctOTdkMi00NGU4LTgyM2EtMWJlMDhjOTI4NjcyIiBzdEV2dDp3aGVuPSIyMDIxLTExLTA0VDE0OjI0OjEwWiIgc3RFdnQ6c29mdHdhcmVBZ2VudD0iQWRvYmUgUGhvdG9zaG9wIENDIDIwMTkgKE1hY2ludG9zaCkiLz4gPHJkZjpsaSBzdEV2dDphY3Rpb249InNhdmVkIiBzdEV2dDppbnN0YW5jZUlEPSJ4bXAuaWlkOjc0YTJiN2IyLWJiYjYtNDAxMC1iOTExLWQ1N2YyNGNhOGY3MCIgc3RFdnQ6d2hlbj0iMjAyMS0xMS0wNFQxNDoyNDozOVoiIHN0RXZ0OnNvZnR3YXJlQWdlbnQ9IkFkb2JlIFBob3Rvc2hvcCBDQyAyMDE5IChNYWNpbnRvc2gpIiBzdEV2dDpjaGFuZ2VkPSIvIi8+IDwvcmRmOlNlcT4gPC94bXBNTTpIaXN0b3J5PiA8L3JkZjpEZXNjcmlwdGlvbj4gPC9yZGY6UkRGPiA8L3g6eG1wbWV0YT4gPD94cGFja2V0IGVuZD0iciI/Ply2tzwAAAzoSURBVHic7d1fjls3EsXh0sC9h5kdJCuI9/8Ur8Degb2Hfuh56Jat/y1dkXVOFX8fECAIghYvWTyXpK6k3dvbWwCAwn/UDQCwLgIIgAwBBECGAAIgQwABkCGAAMgQQABkCCAAMgQQABkCCIAMAQRAhgACIEMAAZAhgADIEEAAZAggADIEEAAZAgiADAEEQIYAAiBDAAGQIYAAyBBAAGQIIAAyBBAAmS9ZL7Tb7bJeCuNt/flcBr2orF9MTgsgWJpdZff+fYJqUQTQGnJuZ9tdax/B1BxnQP38jPcJffhPVUfX8RLxj7g9GGyXtdfjDGiOl4h/XiP+VbdDhKKahDMg3PK7Ol6VrdA7nSUEUjEEUB2Vt1JZDvuIMCqAAPJG6GxHGBXAIbSn6ofHbjjENsUhtA8CJxcFeQOH0OsgeDT2/U4QCbEF02Gb5YHtmRABlOijyAkeQx/PUhFEyTgDykPoFPIS8fU14pu6HSppuUAATUfw1LZk4XIIXR/B0wOH1RMRQOMRPD0RRBNwCD3O9yB8VvAW7984gAE4AxqD4FlT26LmDKgGgmdtbMuexBZsO8IHe9TCRqyAHkex4RJWQxuwAnoM4YPPUCMPIIDuR2HhXtTKndiCfY5iuux0q0E/HWNLdgdWQLcxqc7t4vKkuvbfV0cN3UAAXUfhHLs3YAiic9TSFQTQiYOvzMAfWwKFEDrGV31cwJPQxwiec88OHH16zn4yZOUCK6A/mCjnRkwU+8kmQK19IIDeURDnRgYHIXSOmgsCKIJCuGRGYBBC55avvdUDaPkCuGBmUBBC55auwZUDqMLAM2GfV6EPK9TiFKsGkPuAq56lyXhN1XW5B5F7TU6xYgA5D/TpRMlsa+YEzXyt09+Idw4i59qcYrUAch5g54nRjXNfO9focCsFkOvAXrsrd139KF7zUl86r4Zca3W4VQLIcUBdJoCyDS7X79COU441O9wKAeQ4kJ8VvGObq/usTwkhge4B5DaAbndbh7Y4tGHPbXwi/Gp4qM4B5DZwdxU2n5ie6vud/x8hlKRlAJlN4ofuqq8R/05syyGnSZbVlr8e+H+tVkNmNT1M16/jcLljbLnorLbbTK4PztdduZ424es4tqtcLM6TcLasNm3pY5f+cqntYboFkMsAuRQsxtm9RHxVNyJ8anyITgHkMDBW5wZXOLcvpW1bz1NeI76FR/851PoQnc6A1INS5atLHSbQLVX6oXq93cQZ0GNaF8NAFdpZoY0R+naqa36IDgGkHogRhXjv8ykYZ0TdEEJPqr4FUw/AqIvKuA71ZHlUpT7pUoe/sQXzV21CYx5qYaPKAaS864wsOPXdc2Uj+14ZQmVrqGoAdQmfLLQ5ByH0oKoBpFJxUiAXNfKAigGkSvqqhfVD3YAnZLT954S/qaqVcqugau+C/YyI/474Qw+aVVCV3ulRqdxHikD4ERF/P/tH0nKhWAApBnTmBK48ubJU76OSNcvb8OdUd5PKqodPRPFrEH2AtcxWrNIKqOSd5Ibqd/ZM1fuqXO2yAjpWbgCBA4paKrEKqhJA2cqHj8l314zyS92AAcrX1AwVtmDZSe78zXyP6FbwU/vrJeLrx/f9zFainnkX7I8SA/ag6mcaCl36rEQ9cwb0rsRgAQ/IrjHrsyDbABL8DEmn8Ol0LXudrin1Wpx/0sd5C9Z59cP5zzad+s26vtmC5epceLhf5th0vUk8xDWAKITtOrxlfU31J9NPLX/jc92CdQ6gTtsIhW79Z1nrK2/BLAcEmGTpVZBjAGVRLOf59Qt/6ZO02VPrD3HbgnVf/cy+viHfBWOuywOJp6xqf9Unoav8KuZW3c4vVLr2o039r3wGBGAipwcTnVZANuk/Udc7d7bO/WgxD7Jy4UvKq3ixeydgoM7Xlol+TOKyBWPAgVwWc84lgAAsiAACIOMQQBZLQWBB8rnnEEAAFkUAAZBRB5B8CQgsTjoH1QEEYGEEEAAZWQA5fR4FgIbys2Cc/wA+jiYon4YH0B4BBEBGEkCc/wBeVHNSdQbE+Q/g5/ck5QwIQHsEEAAZAgiAjCKAOP8BPKXPTVZAAGQIIAAyBBAAGQIIgEzH3wVz+3G+mQd7bteqslIft3oTJ3sF1PkXLc/wkZMW3Cb87BpPvd7sj2IsFUCx3vWqrNbP06+Xj2IAaI8AAiBDAAGQIYAAyBBAAGQ6BZDbOxXALG1qvVMAASiGAAIgkxlAbk+UArgsba6yAgIgQwABkCGAAMgQQCjvJeKrug3YJvPT8Kt9YjlivU9pK630nUARk2vr7e0t5ZpZAdXlOCmAhxBAAGQIoLp4rgrlEUAAZAggADIEEMrjy//r4m34uVa8ZoUV+5m34QHgGZkB5HgXAXAuba6yAgIgQwABkOkUQDyYh1W0qfVOAQSgGAIIgAwBBECGAAIgQwABkCGAAMhkB9DsJyzd3p7k6e/iDL9vutXn3jI/jLr/V7eQAPDHLiIiKxfYggGQIYAAyBBAAGQIIAAyigDinSHAU/rcZAUEQIYAAiBDAAGQkQSQ4dOlwNJUc1LxJPQeT0QDPo4mKE9CA2iPAAIgowwgngcCPMjmIisgADIEEAAZAgiAjDqAOAcCtKRzUB1AABZGAAGQcQggtmGAhnzuOQQQgEURQABkXAJIvhQEFmMx576oGyCg7PhWPyon1Lkfl/qWCJcVUETeoC81wCglqzZtblROAQRgMasGUNdV0Hd1AxJ0Hbuu13WTWwClLQ1fIv7Jeq1Ef6kbgE0ybxw2268I7VeyXpN5J1AMRucD1Awd+8+u5lf+StbMAlhy2QsrduGTyTGA8Jyf6gZMtMIZ11Ict2B7Xe8MGddld6cbpFvf2db4ylswBdtCQKqu4WPLNoD48UJgGNubnvMWLCL/LtHpaWzbotuoU5/Z1zVbsHfZk4hlMWazD59M7gHUEttLS9YTtasKAdRuFfQa8W32a0Svt+O7vP3O6ueE+xnQnmJrNHvwOp1pzNahr0rVMGdAx7o/Ho/eSoVPpioBpDJzGzO9QDp84DbpGmaORaet8HBVtmB73e4kHbYWs1Xvo5I1yxbssl+C12Qrhq0UtaOYI5tVC6D/iV53ViFlFEvld5CmT+CJj0SoblyqObJJtS3YnmpwZyzVq28xZqraN+Xrky2YJ7Zj+Aw18oCqAcTPpjyGNudQtrnkKrdqAEX0CaGShdPEyL4nfDaoHEBqFe/QJRR8fola2KjqIfQh9eCPuLDlfpDuExn98SMi/h7wdzrU35m0XGgQQBE9iqDqOz4zVOmLDnV3Ee+CPUY9sdSFeK8K7azQxgh9O9U1P0SXAHLwVEHyHUGpnp286vBpo1MAOdwR3mLjk8dJ3xEU4T15nNsW8T62Dm10qPUhupwBHXIokIhtRbL6YbTz9Veuq4dxBrSdy+TaMoJdvxT9HoTP51xqe5iOAeR0nuJSuNjOYgyNanqojluwPYvCOXBvB3yPiL9mNuSAyx01a6x+xf2fFq9aP0PwHNAYVYvIeTsyg9v1Vq2bYTgDGsNlgu29hVdxO7TFoQ17buMT4VfDQ3UPoAjPAfysyB3bXN1nfeoWPBEL1MEKARThOZAud1tlG1yu36EdpxxrdrhVAijCd0CvTYDM9iomYOZrXupL1+CJ8K3V4VYKoAjvgXWdDB0597VzjQ63WgBFeA/w6V256ypItfpxXvVEeNfmFCsGUIT/QKsmSsZrqq7LOXgi/GtyilUDKKLGgLtPmoeIvumwQh9WqMUpuj+IeI8KBZpt1mDR1+csJwYPIuaxLACxGdVH+JxbvvYIoHfLF8IFIwOD8DlHzQUBdIiCODciOAifc9TaBwLo2K7r1x484ZkAIXwOfNQW4XOAQ+jrmDzHHh1A+u9YqQnAIbReqYJJcO+zNBWeuclGLV1BAN1G4Zy7FjAEz2XU0A1f1A0oYF9ATK5j9MdtBM8dWAHdj4LCvaiVOxFAj6Gw8Blq5AFswR7HlgyXEDwbsALajoLDHrWwESug57AaWhvB8yRWQGPs4v03p7CGX0H4DMGT0OOxGuptiULOygW2YOOxLetpieDJRgDNQxD1QPBMRADNRxDVRPAkIIDyEEQ1EDyJCKB8BJEngkeAANIhiDwQPEIEkB5BpEHwGOBBRB+7g38wwcFXotLHJlgBeWJVNNYuIuJV3QqcIYC8nf6uOe7HKqcAAqgOwuhzhE4xBFBNpxNt1UAicIrjELqH3wfYzX/XbBcc1rfCp+HXUHWFRNGI8Gl4jHRtIrsEE0GzKAJobfdO/K1BRbDgprQtGACc4hAagAwBBECGAAIgQwABkCGAAMgQQABkCCAAMgQQABkCCIAMAQRAhgACIEMAAZAhgADIEEAAZAggADIEEAAZAgiADAEEQIYAAiBDAAGQIYAAyBBAAGQIIAAyBBAAGQIIgMz/AT8uv0Xakt/+AAAAAElFTkSuQmCC`

YOURLS submits the request but gets a 520 server error and doesn't do anything else

### Expectation

Create the Short URL

### Reproduction steps

1. Put in the long url listed above
2. Error
3. profit?

**Comment by dgw** [comment]
I can't reproduce this. Next steps for figuring out what's wrong depends on whether you _really_ get HTTP 520 (a non-standard error code Cloudflare returns sometimes) or if that's a typo and you're really seeing HTTP 502 (usually seen in PHP-FPM configurations if the service isn't running correctly).

**Comment by SirOMGitsYOU** [comment]
> I can't reproduce this. Next steps for figuring out what's wrong depends on whether you _really_ get HTTP 520 (a non-standard error code Cloudflare returns sometimes) or if that's a typo and you're really seeing HTTP 502 (usually seen in PHP-FPM configurations if the service isn't running correctly).

How can I determine if it is a 502 or if my PHP FPM is buggered

**Comment by SirOMGitsYOU** [comment]
Update: I have fixed the issue by re-encoding the data:image in base64 for a smaller string but surely this isn't the best way around this?

**Comment by dgw** [comment]
Screenshot clearly shows 520, which could still be caused by an error on the server side if said error causes the server to just _not respond_ instead of returning any code/message.

Re-encoding the data URI fixing it points to some software issue, certainly. Note that [the allowed length of a URL varies wildly](https://www.sistrix.com/ask-sistrix/technical-seo/site-structure/url-length-how-long-can-a-url-be) depending on what pieces exist in your stack (from your browser to the server and everything in between).

If the error is on _your server_, following the "Troubleshooting first steps" guide that you acknowledged following in the initial message will help you find the error logs.

**Comment by SirOMGitsYOU** [comment]
> Screenshot clearly shows 520, which could still be caused by an error on the server side if said error causes the server to just _not respond_ instead of returning any code/message.
> 
> Re-encoding the data URI fixing it points to some software issue, certainly. Note that [the allowed length of a URL varies wildly](https://www.sistrix.com/ask-sistrix/technical-seo/site-structure/url-length-how-long-can-a-url-be) depending on what pieces exist in your stack (from your browser to the server and everything in between).
> 
> If the error is on _your server_, following the "Troubleshooting first steps" guide that you acknowledged following in the initial message will help you find the error logs.

This is the debug log posted in the page footer 

`Connected to database yourlsdb on localhost 
SQL perform: SELECT option_name, option_value FROM yourls_options WHERE 1=1 (0.00027 s)
Check for new version: no
SQL perform: SELECT COUNT(keyword) as count, SUM(clicks) as sum FROM `yourls_url` WHERE 1=1  (0.00019 s)
SQL perform: SELECT * FROM `yourls_url` WHERE 1=1  ORDER BY `timestamp` desc LIMIT 0, 15; (0.00041 s)`

**Comment by dgw** [comment]
That's debug output, not an error log. Errors will be logged wherever PHP or the HTTP server is configured to do so, and those logs should already contain details of the failures you saw earlier **if** it was a server-side problem.

**Comment by LukeLR** [comment]
I also tried to reproduce this, but no luck. Shorting the URL supplied in your original posting works in my YOURLS 1.8.2 / php-74-fpm / Apache 2.4.51 setup. So maybe it would help to know more about your stack :)
