### ISSUE TITLE
is it possible to create multiple short urls  for one long URL?

### ISSUE THREAD

**Issue by gitxxxa** [YOURLS/YOURLS#3134]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Summary

I want to generate more than 1 short URL for each original URL, but now the system allows me to create only one short URL for one link. can anyone help on this?

### Motivation

to create more short URLs for each link.

**Comment by dgw** [comment]
> I checked current issues and this request isn't a duplicate of an existing issue, opened or closed.

It _is_ a duplicate, of #2560.
