### ISSUE TITLE
Add nonce to the logout link

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#3170]
The logout link doesn't check for a nonce, see:

https://github.com/YOURLS/YOURLS/blob/42fd3b85c2d49120f3328c7f77ce4d5c100fcc61/admin/admin-ajax.php#L43-L46

A mean hax0r can trick a naive user into logging out themselves if they're redirected to `http://their-your.ls/admin/index.php?action=logout`.

Definitely not a big deal, but also trivial to fix.

**Comment by lenny-lam** [comment]
Looks interesting. I would like to have a look at it.

**Comment by ozh** [comment]
(I'll add that, of course, this should be covered with a proper unit test)
