### ISSUE TITLE
Date created UTC instead of current local time (winter time)

### ISSUE THREAD

**Issue by un99known99** [YOURLS/YOURLS#3172]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps) guide.

### Version

v 1.8.3-dev 

### Description

If I create a new short URL (Enter the URL - Shorten the URL) the date (created) is shown as 'current time -1' (UTC, as my current time zone is 'Berlin')

### Expectation

Current local time is choosen

### Reproduction steps

admin interface
enter the URL
press "Shorten the URL"
Short URL in overview is shown "Date: => current -1"

**Comment by dgw** [comment]
YOURLS uses UTC. Timezone support is meant to come from  plugin, if you desire it.

https://github.com/YOURLS/YOURLS/blob/23d21fd996e771c4015f5d8b4ec1b06af122d60b/includes/Config/Init.php#L30-L33

**Comment by un99known99** [comment]
Hi,
thx for info, downloaded files
![grafik](https://user-images.githubusercontent.com/1615207/147851203-07652f32-0c62-4ab4-b5ba-fc8cf3cfd67b.png)
but giving:

![grafik](https://user-images.githubusercontent.com/1615207/147851222-77439117-31fe-47d8-a292-54e893571ff6.png)

am I doing something wrong?

**Comment by un99known99** [comment]
ok, seems to work when downloading zip file ... :)
