### ISSUE TITLE
Traffic location - "No country data"

### ISSUE THREAD

**Issue by un99known99** [YOURLS/YOURLS#3173]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps) guide.

### Version

v 1.8.3-dev

### Description

Statistic details of a setup short URL, tab "Trafic location" is giving => "No country data"

### Expectation

Traffic location by country is shown

### Reproduction steps

Admin interface
Enter the URL, short the url
choose setup short url, stats, traffic location => no data

### Context

Country data shown

**Comment by dgw** [comment]
This is almost certainly because of the GeoIP2 database's age. You can provide a more recent one [via a simple plugin](https://github.com/YOURLS/YOURLS/blob/23d21fd996e771c4015f5d8b4ec1b06af122d60b/includes/functions-geo.php#L32).

@ozh Why is YOURLS still shipping with a database from 2017? Did the license change to disallow redistribution?

**Comment by ozh** [comment]
This is definitely because I don't pay attention to geo data in my own YOURLS instance and never think about updating the DB.

There should be a core plugin updating that DB every couple months, that would be neat.

I'll fix in next release :)

**Comment by un99known99** [comment]
geoip lite service is discontinued

**Comment by un99known99** [comment]
https://blog.maxmind.com/2018/01/02/discontinuation-of-the-geolite-legacy-databases/

**Comment by ozh** [comment]
> geoip lite service is discontinued, only a paid one exists

You're referring to an obsolete version of GeoIP. We've been using [GeoIP2](https://dev.maxmind.com/geoip/geolite2-free-geolocation-data) for 5 years.
