### ISSUE TITLE
High DB cpu load 

### ISSUE THREAD

**Issue by Airex** [YOURLS/YOURLS#3181]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps) guide.

### Version

1.8.1

### Description

High DB cpu load (up to 100%) and slow response time (>10 sec) during high system load activity. 
My investigation pointed to query `select * from yours_url where url = 'some url'` over non indexed field 'url' in table with >1 mil entries.
Manual addition of index with some field truncation decreased db cpu load to avg (3%) for same high system load.

### Reproduction steps

High system activity with high amout of new urls shotened.

### Context

Nothing to add

**Comment by ozh** [comment]
What column should be indexed might be debatable.

Having indexes makes writing and updating longer, so if you're shortening lots of URLs, your custom index will certainly improve your URL searches (ie `select * from yours_url where url = 'some url'`) but would also degrade your regular shortening.

So in the end it depends on your use case and where you need performance (ie having lots of people shortening thousands of URL in a blink, or making searches faster)

Also, be aware that field truncation might not work for everyone.
