### ISSUE TITLE
Tests broken

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#3186]
Just found out that tests have been broken for a while, I think since I added a nonce the the login screen ([commit](https://github.com/YOURLS/YOURLS/pull/3034/commits/08cdb3296f7d777db6f515614eea3181ac20355d)) which breaks the test 'Auth_Login_Normal_Tests::test_login'

it's quite surprising btw that Github reports all tests as passing as none are actually completing.

To be fixed.

(Do we need a nonce in the login form ?)

**Comment by LeoColomb** [comment]
Good catch!

> it's quite surprising btw that Github

GitHub Actions status follows command exit status, my guess is PHPUnit does not handle the output (and the `die()`) thus generate a false positive exit.

**Comment by ozh** [comment]
(Culprit is actually #3090)

**Comment by LeoColomb** [comment]
Closing via https://github.com/YOURLS/YOURLS/pull/3188
