### ISSUE TITLE
When a time is displayed, it should be done so uniformly across the app

### ISSUE THREAD

**Issue by oliverneedham** [YOURLS/YOURLS#3199]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Summary

When a time and date is displayed in YOURLS's admin pages, it isn't done so uniformly.

E.g. within index.php's list of URLs, it displays `Nov 19, 2021 16:33` (24 hour)
Where as on the graph displaying the time of visitors it uses the format `HH AM/PM`, e.g. `13 PM`. (mixing 24 hour & 12 hour formats)
Under 'Historical click count' for a specific URL's stats, there is `Short URL created on November 19, 2021 @ 4:33 pm`. (12 hour)

The display of the date appears to be consistent, as with the examples above.

Example of where two times are displayed different on a single page:
![An example of the times displayed on the stats graph](https://oliverneedham.co.uk/files/yourstimedisplay-jan2021.png)

### Motivation

Making the display of the time uniform across the system assists with being able to compare times quickly and more easily.

Whilst there may be a myriad of different ways to display the time (especially in different cultures), the attention to detail to display time in a single fashion helps the user know that time and care has been taken to create the product.

This should also help users whose first language isn't English to read the times more consistently.

### Describe the solution

Choose a single format to display times across the system.
I believe the main options should be:
`HH:MM` (24 hours)
`HH:MM AM/PM` (12 hours)

These two formats are more universally accepted than `HH:MM a/p` (12 hours), which is sometimes favoured in the USA.

I don't believe the first solution is allowing the user to choose the format they would like the time/date to be displayed in, as this would require significant work. The WordPress system does allow a [custom time/date format](https://wordpress.org/support/article/formatting-date-and-time/) displayed.

**Comment by oliverneedham** [comment]
This may be merged/related to improving the stats page, #2675.

**Comment by ozh** [comment]
The reasoning (not stating that it was a good idea, just explaining why I did this :) of various time/date formatting was primarily a matter of "where do I need a compact display" and "where can I afford to be more verbose". I think. Also maybe a complete lack of consistency.

Did you give https://github.com/YOURLS/timezones a try ? I think this is what you're looking for.

**Comment by oliverneedham** [comment]
Thanks @ozh for response. I really appreciate it.

I was not aware of the plugin, so I've added that in and it has certainly helped.

It's still inconsistent on the graph, but I suspect it's got a library of its own and decides to display the time however it wishes.

The whole thing was a recommendation/thought rather than a demand, so hopefully it came across that way.

Again, thank you for the response and more broadly for contributing YOURLS to the open source community!
