### ISSUE TITLE
Add startpage

### ISSUE THREAD

**Issue by strarsis** [YOURLS/YOURLS#3207]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Summary

Currently, when visiting the `/` URI of `yourls` I get a HTTP 500 Forbidden by the underlying Apache server.
This is surely a valid and secure response in these cases (no shortened or backend URL was given).

But it would be nice to be able to show a logo or a text and/or a link to the login (`/admin`) page of `yourls`.

### Motivation

Convenience: I set up a `go.mydomain.com` URL for `yourl` which is short and looks great and familiar.

Familiarity: A visitor may look at the domain (e.g. `go.mydomain.com`) and it would be nice to have some cool/professional logo/page there.

Consistency: When I visit that URL it would be nice to have some HTTP 200 OK page that ensures that everything works and a site logo. The same goes for very simple+cheap HTTP(S) checkers that can be then pointed directly to the root URL.

### Describe the solution

Show a nice and simple landing page, e.g. with the `yourls` logo as the default and a link to the backend login.

**Comment by dgw** [comment]
http://yourls.org/#FAQ;noindex
