### ISSUE TITLE
Error in installation

### ISSUE THREAD

**Issue by licen150** [YOURLS/YOURLS#3217]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps) guide.

### Version

1.8.3-dev

### Description

Error in installation

### Expectation

When i click install yourls in install page yourls installs and works but an error appears in the logs 

```
2022/02/06 15:25:42 [error] 10855#10855: *144 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'url.yourls_options' doesn't exist in /var/www/url/includes/vendor/aura/sql/src/AbstractExtendedPdo.php:558
Stack trace:
#0 /var/www/url/includes/vendor/aura/sql/src/AbstractExtendedPdo.php(558): PDOStatement->execute()
#1 /var/www/url/includes/vendor/aura/sql/src/AbstractExtendedPdo.php(412): Aura\Sql\AbstractExtendedPdo->perform('SELECT option_v...', Array)
#2 /var/www/url/includes/Database/Options.php(110): Aura\Sql\AbstractExtendedPdo->fetchOne('SELECT option_v...', Array)
#3 /var/www/url/includes/functions-options.php(25): YOURLS\Database\Options->get('version', false)
#4 /var/www/url/includes/functions.php(504): yourls_get_option('version')
#5 /var/www/url/includes/functions.php(486): yourls_get_current_version_from_sql()
#6 /var/www/url/includes/Config/Init.php(95): yourls_upgrade_is_needed()
#7 /var/www/url/includes/load-yourls.php(26): YOURLS\Config\Init->__construct(Object(YOUR" while reading response header from upstream, client: x.x.x.x, server: cc.licen777.ru, request: "GET /admin/ HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.3-fpm.sock:", host: "cc.licen777.ru"
```

### Reproduction steps

1. Download and unzip or git clone YOURLS to site directory
2. Connect to database
3. Go to www.example.com/admin/ and click Install YOURLS
4. Check nginx/apache2 logs

### Context

Debian 10 (Buster)
nginx 1.14.2 web server
php-fpm 7.3, php-mysql and php-curl installed
MySQL Version 5.5.5-10.3.31-MariaDB-0+deb10u1

**Comment by ozh** [comment]
Ok, it seems function `yourls_is_installed()` isn't behaving as expected. I'll have a look.

Thanks for reporting !
