### ISSUE TITLE
Update default links to HTTPS

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#3228]
Default links are created upon install: they should point to their HTTPS URL instead of HTTP (ie `https://yourls.org/` et al)

https://github.com/YOURLS/YOURLS/blob/d5f373f54a1706f048bba68dd4e8ce3a7f5b7d44/includes/functions-install.php#L308-L310

**Comment by jaas666** [comment]
Change is easy enough. I'm still trying to figure out GitHub. Can I give this a try?
