### ISSUE TITLE
Remove lib ozh/phpass

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#3231]
We've been using [ozh/phpass](https://github.com/ozh/phpass) for a super long time because back then when dealing with PHP prior to 5.5 we didn't have builtin functions [password_hash()](https://www.php.net/manual/en/function.password-hash.php) and [password_verify()](https://www.php.net/manual/en/function.password-verify.php).

We can, so we should, remove this dependency and use `password_hash()`, which should be a straightforward replacement in `includes/functions-auth.php` and in the unit tests.

Things to ponder : 
- we could use `PASSWORD_BCRYPT` by default and allow another hashing algorithm with a filter
- do we really need that `$` <-> `!` replacement ?

Note : the bcrypt hash is limited to 72 chars, see https://stackoverflow.com/questions/16594613/how-to-hash-long-passwords-72-characters-with-blowfish (note that ozh/phpass behaves the same, see https://3v4l.org/F6NvW).
Now, passwords longer than 72 chars _shouldn't be an issue_ I guess, but it may be worth documenting it somewhere (there's got to be some zealot one day with a password manager who will use a 128 char long password, obviously) (Other hashing algorithm don't have that limitation)

**Comment by My1** [comment]
couldnt we even make argon the default considering the minimum PHP is 7.4

**Comment by ozh** [comment]
I think it depends on how PHP was compiled, ie could be totally unavailable on some distros or web hosts, while Blowfish is always avail

**Comment by My1** [comment]
Now that's dumb. Windows php at least always had argon in as long as it existed.

Then I'd at the very least say that the algo should definitely be able to be customized, params as well as the default bcrypt cost wasn't high either last time i checked.)

The entire $ to ! swap is imo entirely unneeded and likely just a thing to keep phpass happy and not accidentally clash with other had handlers maybe.

**Comment by My1** [comment]
might it be possible to long term rewrite phpass hashes into normal password_hash() hashes without any substitution? one could even do this in combo with [`password_needs_rehash()`](https://www.php.net/manual/de/function.password-needs-rehash.php) to re-hash if the parameters have changed

**Comment by ozh** [comment]
I think the substitution is needed because of the way we `include()` the `config.php`. At least, I removed it and it failed, so I added it back :^P

**Comment by My1** [comment]
does the password hash happen to be enclosed in double quotes, e.g. `"$2y$10$.vGA1O9wmRjrwAVXD98HNOgsNpDczlqm3Jq7KnEd1rVAGv3Fykk1a"`
if yes make sure to use single quotes:
`'$2y$10$.vGA1O9wmRjrwAVXD98HNOgsNpDczlqm3Jq7KnEd1rVAGv3Fykk1a'`
double quotes mean you can $variable names are being resolved or at least tried to.
