### ISSUE TITLE
persistent links

### ISSUE THREAD

**Issue by garrison63** [YOURLS/YOURLS#3234]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps) guide.

### Version

1.82

### Description

why does the YOURLS shortened links are correct in the console but redirects to the main page of the link using the api

for example this Persistent Link   https://search.ebscohost.com/login.aspx?direct=true&db=geh&AN=2022-004514&site=ehost-live     works get in the console and stores it correctly but when you use the api off our website it stores the the root of the URL 
https://search.ebscohost.com/

this is a university library and using persistent links are important....I did install and activate the plugin Fix links but still does this using the api.....works great using the console....

**Comment by garrison63** [comment]
another example    https://search.ebscohost.com/login.aspx?direct=true&db=hch&AN=155217424&site=ehost-live      this link works in the console but puts this in when using the api     https://search.ebscohost.com/login.aspx?direct=true

Here's a link that worked using api       https://misinforeview.hks.harvard.edu/

**Comment by ozh** [comment]
Because, as per stated in the readme -- http://yourls.org/#API;apiusage -- you didn't URL-encode the long URL.

**Comment by garrison63** [comment]
this command    $data = json_decode( $data );     I don't see anything else on the page

**Comment by garrison63** [comment]
I see a get ..... do you have to encode using Post command

**Comment by garrison63** [comment]
ok Thanks for your help
