### ISSUE TITLE
Treat www & non www the same ?

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#3242]
I have not completely thought this through but we should probably treat WWW and non WWW urls the same.

Two places : 
- http://sho.rt/blah and http://www.sho.rt/blah should be both detected true by yourls_is_shorturl()
- if willing to shorten http://longurl.com/blah and there's already a short URL to http://www.longurl.com/blah, it should be treated as duplicate

Doesn't make sense I think for other schemes than `http(s)`

Possible problems : might not be completely easy to add or remove www from a URL and make sure it's the same
Examples:
- http://www.127.0.0.1/ makes no sense. http://www.localhost/ or http://www.local.dev/ might or might not work
- Some domains use `www1` (or 2, 3 etc...) and it's sometimes the same, sometimes different than `www`

(Maybe this is overthinking and an endless rabbit hole? I mean, if `http://this.com/` and `http://www.this.com/`, why not `http://this.com/?` and `http://this.com/#?` ?)

**Comment by dgw** [comment]
As Léo said, they're not necessarily the same. About the only sane way to detect if they really are is to see if one redirects to the other.

**Comment by ozh** [comment]
OK :)
