### ISSUE TITLE
Hooks for adding a search item

### ISSUE THREAD

**Issue by carsten-wilhelm** [YOURLS/YOURLS#3262]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Summary

As part of a special multi-user plugin, we wanted to add a search filter for a username.

There are some issues with that, currently this is not possible without changing the core:

* The filter "html_select" can be used to add an option, but this needs to be done in the generated HTML for the select box
=> it would be better to add a hook to include a new option before creating the HTML
* The "search_in" parameter can be changed in the filter "admin_view_search_in", which seems to be OK
* But then you get an error, because the new filter has no translation in "params_translations" in AdminParams..php
=> there is no filter or hook to add newe translations, so this would require core changes for now

### Motivation

We want to filter for a specific username in our multi-user plugin

### Describe the solution

Add a new filter before "html_select" where plugins can change the list of options
Add a new filter to add a new translation for the search filter.

**Comment by ozh** [comment]
@carsten-wilhelm please have a look at the linked PR - if I understood correctly this should cover your case

**Comment by carsten-wilhelm** [comment]
@ozh looks great, I think plugins should now be able to add (or remove) sort options more easily.
I will try this out and open a new issue if we encounter problems using that.
Thanks a lot for the quick update!

**Comment by carsten-wilhelm** [comment]
Sorry - just saw two remaining issues - should I try to create a new pull request for that?

1) In index.php, line 37 - this should use the values from $possible_search_params from AdminParams.php (which need to be exported then)
2) Since I need to search in a separate table (I haven't added a column to the core "url" table), I need to have a slightly different SQL statement. Maybe add a new hook here as well: index.php, line 43

**Comment by carsten-wilhelm** [comment]
Forget it fow now - since I needed to include a JOIN into the generated SQL, this would mean that I would need to change the way the SQL is concatenated in yourls_get_db_stats and maybe other parts of the code as well.
