### ISSUE TITLE
What file permissions should be used for Yourls

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#329]
This is a **COPY** of **Issue 329: [What file permissions should be used for Yourls](http://code.google.com/p/yourls/issues/detail?id=329)**, filed on Google Code before the project was [moved on Github](https://github.com/ozh/google-issues-to-github).
- Submitted on 2010-05-15T13:00:40.000Z by [ryan.fit...@gmail.com](http://code.google.com/u/112605141581487832446/)
- Status: Done

Please **review** the original issue and especially its comments. **Comments here on closed issues will be ignored**. Thanks.
## Original description

```
Hi, this is an error in code, but i am worried about the security, and i
want to know what CHMOD for the File Permissions i should use for the
folders and files.

Many thanks, Ryan
twitter.com/ryanfitton
```

**Comment by dylanh724** [comment]
Well, what was the answer? O_o
