### ISSUE TITLE
Performance significantly decreased with 1.9

### ISSUE THREAD

**Issue by merdely** [YOURLS/YOURLS#3307]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://docs.yourls.org/guide/troubleshooting/first-steps.html) and [frequent issues](https://docs.yourls.org/guide/troubleshooting/frequent-issues.html) guides.

### Version

1.9

### Description

Immediately after upgrading to 1.9, performance took a hit.
I use Nagios to monitor my server with a simple check_http using SSL looking for a string (the <meta name content> tag).

It now times out after 10 seconds after upgrading to 1.9.  No other changes on my server were made.
Additionally, loading the page in my browser feels significantly slower.

### Expectation

Page should load in about 0.5 seconds

### Reproduction steps

1. Upgrade from 1.8.2 on OpenBSD 7.0 with a mariadb back-end
2. Connect to YOURLS URI and experience slow connection

### Context

OpenBSD 7.0
nginx 1.20.1p1
php-8.0.17
mariadb-server-10.6.7v1

**Comment by LeoColomb** [comment]
Thanks for opening this issue @merdely.
Right now, two ideas in my mind:
* A potential cache issue on php server; if a service restart is possible it's worth a try.
* A plugin validation delay
  * @ozh there isn't db change indeed, but significant plugin load changes
    https://github.com/YOURLS/YOURLS/blame/27375bc813f2ddc38030800e466babb72d7a5a66/includes/functions-plugins.php#L604
  * @merdely You didn't specify if any plugin is installed on your deployment. Any?

**Comment by ozh** [comment]
This plugin load changes shouldn't have any performance side effect, it's merely the previous code wrapped into a try catch block

**Comment by merdely** [comment]
I have 3 plugins:

- Change Password
- Random ShortURLs
- A custom plugin I wrote

My plugin simply has:
````
<?php
/*
Plugin Name: REDACTED Plugin
Plugin URI: REDACTED
Description: Simple overrides for REDACTED
Version: 0.1
Author: Mike Erdely
Author URI: REDACTED
*/

// No direct call
if( !defined( 'YOURLS_ABSPATH' ) ) die();

/* Override the Title
 *
 * We're going to modify the <title> of pages in the admin area
 *
 * The <title> tag is generated by function yourls_html_head() in includes/functions-html.php
 * Notice the following function call:
 * $title = yourls_apply_filter( 'html_title', 'YOURLS: Your Own URL Shortener' );
 * This function means: give $title the value "YOURLS: Your Own URL Shortener", unless a
 * filter modifies this value.
 *
 * We're going to hook into this filter and modify this value.
 */

yourls_add_filter( 'html_title', 'erdely_change_title' );
function erdely_change_title( $value ) {
        $value = 'REDACTED URL Shortener';
        return $value; // a filter *always* has to return a value
}

yourls_add_filter( 'admin_url', 'erdely_change_admin_url' );
// return yourls_apply_filter( 'admin_url', $admin, $page );
function erdely_change_admin_url( $value ) {
        $value = preg_replace('#/admin/#', '/REDACTED/', $value);
        return $value;
}
```

**Comment by merdely** [comment]
I just rebooted my server and with the Plugins page loaded in my browser, I hit refresh.  It took 10 seconds to load, so likely not a cache issue.

**Comment by merdely** [comment]
I just disabled all plugins: same issue.

**Comment by ozh** [comment]
https://docs.yourls.org/guide/troubleshooting/first-steps.html : YOURLS_DEBUG
