### ISSUE TITLE
Shortmenu App no longer works with YOURLS

### ISSUE THREAD

**Issue by pftnhr** [YOURLS/YOURLS#3308]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://docs.yourls.org/guide/troubleshooting/first-steps.html) and [frequent issues](https://docs.yourls.org/guide/troubleshooting/frequent-issues.html) guides.

### Version

1.9

### Description

Yesterday I did the update for YOURSL and today I'm not able to short my URLs with the Shortmenu app. It says "Error! Parsen der Antwort nicht möglich" (maybe "Parsing of the answer not possible." in english). Before the update, everything worked without any problems.

I double checked the secret signature token and all other settings within the App.

**Comment by matthewpkemp** [comment]
Haven't had a chance to dig in fully, but on my Short Menu/iC-YOURS it looks like I'm getting a 403 on 1.9 as well:

{"message":"Please log in","errorCode":403,"callback":""}

**Comment by ozh** [comment]
Well, that's not a YOURLS issue, that's a Shortmenu App issue then.

YOURLS 1.9 doesn't change anything to how the log in works. In 1.8.2 we did introduce a nonce to the login form.

**Comment by matthewpkemp** [comment]
Just an FYI, it appears the secret signature token changed on my system (just realized this).  That is why the two apps didn't work.
