### ISSUE TITLE
Workflow updating the certificates creates two `etag*.txt` files that are not part of the lib

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#3312]
**Situation**: [.github/workflows/update-certificates.yml](https://github.com/YOURLS/YOURLS/tree/master/.github/workflows/update-certificates.yml) creates 2 files, `etag-cert.txt` and `etag-sha.txt` in `includes/vendor/rmccue/requests/certificates`

**Problem**: when updating the lib, those 2 files are deleted, thus a PR to update the certificates is automatically created

**Solution**: do something else.

**Comment by ozh** [comment]
> Is there a reason these two files are committed in the repository?
> Are they used when running the app?

Not at all, there are created only when checking for an update. This was dumb

**Comment by LeoColomb** [comment]
Not dumb, but maybe unnecessary, and definitely something that could have been discussed in a review 😜

More seriously, I think this issue can be closed now #3313 is merged.
One option is to use GHA cache as you've tried in #3313, but I'm not sure it brings a significant value here.

**Comment by ozh** [comment]
> Not dumb, but maybe unnecessary, and definitely something that could have been discussed in a review 😜

;-)
No, that was dumb in retrospect, I overlooked (didn't know, tbh) the fact that when a lib is updated its content is first completely erased

Closed via #3313
