### ISSUE TITLE
Use sandbox to include every user defined PHP files

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#3321]
Since YOURLS 1.9 we have a foolproof sandbox to safely include PHP files, used for plugins : https://github.com/YOURLS/YOURLS/blob/27375bc813f2ddc38030800e466babb72d7a5a66/includes/functions-plugins.php#L682-L696

Rename this function to make it more generic, update tests accordingly, and reuse it for : 

Pages:
https://github.com/YOURLS/YOURLS/blob/27375bc813f2ddc38030800e466babb72d7a5a66/includes/functions-html.php#L865

Custom DB error:
https://github.com/YOURLS/YOURLS/blob/27375bc813f2ddc38030800e466babb72d7a5a66/includes/Database/YDB.php#L161

Custom maintenance page:
https://github.com/YOURLS/YOURLS/blob/27375bc813f2ddc38030800e466babb72d7a5a66/includes/functions.php#L1052

Custom DB or cache layer: 
https://github.com/YOURLS/YOURLS/blob/27375bc813f2ddc38030800e466babb72d7a5a66/includes/Config/Init.php#L143-L165
(by the way, rename that "cache.php" to something understandable -- `must-use-plugin.php`? `unconditional-use-plugin.php`?)

**Comment by ozh** [comment]
And document those "special files" damnit -- #3045

**Comment by e-ht** [comment]
Keen to PR this if there is no current WIP.

**Comment by e-ht** [comment]
Added PR https://github.com/YOURLS/YOURLS/pull/3478 with changes but did not rename cache.php.   The entire verbiage around 'cache' is confusing to me.  Could this be its own issue with a more apt description of what it is?  Is it a cache layer or an always on plugin, or...? 

eg
"// Allow early inclusion of a cache layer"
vs
"// Allow early inclusion of always on plugin layer"

**Comment by ozh** [comment]
Yeah the wording used for this file is especially poor :-) I think it's more "always-on plugins or custom files"

**Comment by ozh** [comment]
The case is settled. It's named "cache.php" because it stands for "Custom Additional Code for Hazardous Extensions" :)
