### ISSUE TITLE
Auto encrypting password does not work if username contains a square bracket

### ISSUE THREAD

**Issue by SXN31** [YOURLS/YOURLS#3364]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://docs.yourls.org/guide/troubleshooting/first-steps.html) and [frequent issues](https://docs.yourls.org/guide/troubleshooting/frequent-issues.html) guides.

### Version

1.9.1

### Description

If a user's name includes square brackets, the password will not be encrypted and a preg_replace error is reported.

### Expectation

The password to be encrypted without any issue.

### Reproduction steps

Add

```php
$yourls_user_passwords = array(
    'testuser[2]' => 'password',
);
```

### Context

Seems like the bracket might be breaking something for the `preg_replace` pattern.

https://github.com/YOURLS/YOURLS/blob/3b69f2be52fdfa08c54eccdcb7b3cfc55560a851/includes/functions-auth.php#L216

I only tried curly braces as an additional test, which did work, but even just 1 square bracket breaks the encryption.

**Comment by SXN31** [comment]
Changing line 216 to 
`$pattern = "/[$quotes]". preg_quote($user, '/'). "[$quotes]\s*=>\s*[$quotes]" . preg_quote( $password, '/' ) . "[$quotes]/";`

Appears to have worked for my test user with square brackets.

**Comment by ozh** [comment]
Closed via linked PR
