### ISSUE TITLE
A cookie pair named `username` and `password` will prevent logging in

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#3383]
YOURLS stores credentials (hashed login / password) in a uniquely named cookie, something like `yourls_75715761fe7da[...]199e566c53f27eeb`, see [`yourls_store_cookie()`](https://github.com/YOURLS/YOURLS/blob/16be4c392cb07e345521c5cbe9e0ff0ae2eb6cd4/includes/functions-auth.php#L454).

Yet, if two cookies named `username` and `password` are present, it makes logging in impossible

![image](https://user-images.githubusercontent.com/223647/178319033-63438a2d-c3cc-440e-9ecc-84674062f460.png)

Most likely this is because we're loosely checking `$_REQUEST` ([here](https://github.com/YOURLS/YOURLS/blob/16be4c392cb07e345521c5cbe9e0ff0ae2eb6cd4/includes/functions-auth.php#L75-L77) for instance) which can contain `$_GET`, `$_POST`... and `$_COOKIE`.

`$_REQUEST` is thoroughly used across YOURLS, maybe we should introduce a function to fetch `$_GET` or `$_POST` but not those darn cookies.

Possible references: #3382, #3087, #3351

**Comment by ozh** [comment]
Note that this is server dependent : this depends on `variables_order` or `request_order`. Default is `EGPCS` (Environment, Get, Post, Cookie, and Server) but many host restrict this to only `GP`.

**Comment by LeoColomb** [comment]
The less it relies on host env and the more it relies on http requests parameters, the better it's going to be for Docker usage.
So far I can't see how your suggestion can degrade anything for Docker usage. 😊

**Comment by dgw** [comment]
Is there a reason to use `$_REQUEST` instead of the more specific arrays? If the code is always looking for a GET var, for example, why not have it look in `$_GET`?

**Comment by ozh** [comment]
@dgw sometimes the same code can be used under GET or POST, so I took the lazy way

**Comment by dgw** [comment]
To me, that makes a case for tightening up which request methods are allowed for each function/endpoint, but… yeah, I get it. Overriding `$_REQUEST` at least prevents unintentional crossover _now_ and it's still possible to decide to make accesses more specific in a later refactor. Or maybe v2 will just make it _all_ go away. (@LeoColomb? 😹)

**Comment by LeoColomb** [comment]
> Or maybe v2 will just make it _all_ go away. (@LeoColomb? 😹)

It certainly will! 😄 
Did you give it a try?

---
I agree with the rest. 🙂

**Comment by NoxInmortus** [comment]
Hello! Any estimation on this ? 
Thanks
