### ISSUE TITLE
Query strings cannot be passed with short URL

### ISSUE THREAD

**Issue by dpalic** [YOURLS/YOURLS#3396]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://docs.yourls.org/guide/troubleshooting/first-steps.html) and [frequent issues](https://docs.yourls.org/guide/troubleshooting/frequent-issues.html) guides.

### Version

1.7.9

### Description

I am not sure if a bug or a feature.
IMHO it is a bug

if you use your short domain with yourls
sho.rt/ertzhjmk   => https://www.google.com/search

everything is fine

But I require to pass query params to the final URL
sho.rt/ertzhjmk?q=best+open+source+link+shortener
resulting into
https://www.google.com/search?q=best+open+source+link+shortener

this is not possible

and also passing multiple query params would be required too

### Expectation

that I can somehow pass query parameters to my final URL

### Reproduction steps

create a shortend url
use the shortend URL and add a query parameter
click on it

### Context

many different cases are considered here

**Comment by dgw** [comment]
This is plugin territory. See multiple entries on [the Awesome list](https://awesome.yourls.org/) that already do this, e.g. the last two (currently) [under Q](https://github.com/YOURLS/awesome-yourls#q).
