### ISSUE TITLE
Ignore My Own Clicks

### ISSUE THREAD

**Issue by johnaweiss** [YOURLS/YOURLS#3448]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Summary

i love YOURLS. But it counts my own clicks, which is very unhelpful. Please add a feature to ignore my own clicks. 

Could be IP, but i'm always changing location, so that would add excessive maintenance. Every time i go to a new coffeshop, i'd have to add the new IP. 

### Motivation

Improve stats. 

### Describe the solution

Alternate suggestion, which would be much easier: allow a "nocount" parameter at the end of the url. Your counter would ignore any clicks with that parameter. 
https://mydomain/myshorturl?nocount

thanks!

**Comment by dgw** [comment]
This is plugin territory. Such plugins already exist, e.g. https://github.com/dgw/yourls-don't-track-admins or https://github.com/joshp23/YOURLS-No-Tracking-Admins

They do not use the method you suggested, but being based on whether the clicker is logged in should be easier in the long run.

**Comment by johnaweiss** [comment]
Ok, thanks for that! 

I think the parameter method would be significantly fewer steps. 

But i'll take what i can get. 

Thx!

**Comment by dgw** [comment]
> I think the parameter method would be significantly fewer steps (ie no steps).
> 
> I click the link many times every day. My browser typically logs me out of YOURLS. So with this plugin i'll have to repeatedly browse to YOURLS admin and login.

The idea behind just excluding logged-in users is that _that_ should be ~zero steps. If your YOURLS login session doesn't even last through a day, that's non-default behavior:

https://github.com/YOURLS/YOURLS/blob/6da30dfab08700888d4403a8ce2abaaf47ec11c7/includes/Config/Config.php#L188-L190

Your config file and/or a plugin can modify that value to set cookies with longer or shorter expiration time.

> Btw, one of your links is broke, gives 404 error
https://github.com/dgw/yourls-don't-track-admins

Mobile keyboard pretending it's smart… Fixed.

**Comment by ozh** [comment]
(https://github.com/dgw/yourls-dont-track-admins with no `'`)
