### ISSUE TITLE
Bio link feature

### ISSUE THREAD

**Issue by AnhDOS** [YOURLS/YOURLS#3451]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Summary

I'd like to suggest the bio link feature, similar to Linktree

### Motivation

A big additional feature to URL shorten and can replace Linktree

**Comment by dgw** [comment]
This is out of scope. It might be possible with a plugin, but it's definitely not going to become part of the base package.

**Comment by ozh** [comment]
You can very easily replace Linktree out of the box. Just make a custom index page with all your links. I have never understood the value of linktree :)
