### ISSUE TITLE
group it!

### ISSUE THREAD

**Issue by dexzhou** [YOURLS/YOURLS#3459]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Summary

is that possible to add a category, so that makes management easy, I tried to add a category with / or -, and it works, but the problem is the filter function is not friendly, it will ignore / and -, thanks!

### Motivation

makes management easy, sorry I do not know coding

### Describe the solution

add a new column named category.

**Comment by ozh** [comment]
Every now and then, people request "tags" or "categories". See issue # 2610, 1922, 1763, 675, 13, and more.

Short answer : yes, some day.
