### ISSUE TITLE
set filter more than 0 clicks, still shows links with 0 clicks

### ISSUE THREAD

**Issue by dexzhou** [YOURLS/YOURLS#3460]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://docs.yourls.org/guide/troubleshooting/first-steps.html) and [frequent issues](https://docs.yourls.org/guide/troubleshooting/frequent-issues.html) guides.

### Version

1.9.1

### Description

set filter more than 0 clicks, it still show links with 0 clicks,
set more than 1, shows with 2 and more clicks, that is right.

**Comment by dgw** [comment]
Seems similar to a bug I just fixed in another project, where `0` was interpreted as a Boolean false.

https://github.com/YOURLS/YOURLS/blob/6da30dfab08700888d4403a8ce2abaaf47ec11c7/includes/Views/AdminParams.php#L225-L226
