### ISSUE TITLE
Helm chart domain broken

### ISSUE THREAD

**Issue by markshawtoronto** [YOURLS/YOURLS#3461]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [ ] I've read the [troubleshooting first steps](https://docs.yourls.org/guide/troubleshooting/first-steps.html) and [frequent issues](https://docs.yourls.org/guide/troubleshooting/frequent-issues.html) guides.

### Version

1.9.1

### Description

I've noticed that these URLs aren't working today:
http://blog.yourls.org/
https://docs.yourls.org/
https://charts.yourls.org/

The effect is I'm not sure how to download / update the helm chart right now.

**Comment by LeoColomb** [comment]
Thanks for the report @markshawtoronto.
Indeed, good catch.
