### ISSUE TITLE
User A can see all the links of User B

### ISSUE THREAD

**Issue by dirtycoder0124** [YOURLS/YOURLS#3464]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://docs.yourls.org/guide/troubleshooting/first-steps.html) and [frequent issues](https://docs.yourls.org/guide/troubleshooting/frequent-issues.html) guides.

### Version

v 1.9.1

### Description

-User A can see all the URLs, created by User B and vice-versa.
-I did not find yourls. conf to make changes. I do not want 403 forbidden on my base URL. 

### Expectation

User A should not be able to see the data of User B.

**Comment by ozh** [comment]
Expected behavior. At the moment this feature is plugin territory.
