### ISSUE TITLE
API response code when a link already exists in DB changed from HTTP 200 to HTTP 400

### ISSUE THREAD

**Issue by ashleykleynhans** [YOURLS/YOURLS#3493]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://docs.yourls.org/guide/troubleshooting/first-steps.html) and [frequent issues](https://docs.yourls.org/guide/troubleshooting/frequent-issues.html) guides.

### Version

1.9.1

### Description

After upgrading YOURLS from version 1.7.4 to 1.9.1 and creating a plugin to solve the hashing issue where the `yourls_salt` function changed the hash from md5 to sha256, I am now experiencing issues where my API calls are all broken, because the API used to previously return an HTTP 200 status code when an entry already existed in the DB, but now it returns an HTTP 400 status code.

This kind of thing is why API versioning is important,  if you want to change something as fundamental as an HTTP response code in an API call, then a new version of the API should be created so that no breaking changes are introduced for people who are already using the API.

### Expectation

After upgrading YOURS from version 1.7.4 to version 1.9.1, the HTTP response codes that are returned by the YOURLS API should be the same.  The API should be versioned, and the version bumped if a breaking change such as changing an HTTP status code is introduced into the API.

### Reproduction steps

1. Install YOURLS version 1.7.4.
2. Create a script to consume the API and expect an HTTP status code of 200 when the link already exists in the DB.
3. Run the script and observe success.
4. Upgrade to YOURS version 1.9.1.
5. Run the script created in point (2) and observe failure.

**Comment by dgw** [comment]
IMO, at some point it becomes easier and faster to just update your scripts rather than trying to force the current release of YOURLS to behave exactly the same as one from 2019.

**Comment by dgw** [comment]
However, there are filters like `add_new_link_already_stored_filter` and `add_new_link_keyword_exists` that allow a plugin to modify the `$return` array, including the `statusCode`, for a given error type.

**Comment by ozh** [comment]
> The API should be versioned, and the version bumped if a breaking change such as changing an HTTP status code is introduced into the API.

You're absolutely right, we should have done this from the start, and I didn't. We paid close attention not to break things when updating YOURLS, there are probably one or two cases of broken stuff along YOURLS' history and this is one of them. Sorry! :)
