### ISSUE TITLE
Logs are not deleted after URL deletion

### ISSUE THREAD

**Issue by quicoto** [YOURLS/YOURLS#3496]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://docs.yourls.org/guide/troubleshooting/first-steps.html) and [frequent issues](https://docs.yourls.org/guide/troubleshooting/frequent-issues.html) guides.

### Version

1.9.1

### Description

When you delete a URL entry the existing log entries in the _log table are not deleted.

### Expectation

Deleting a URL should clean out the log table.

### Reproduction steps

1. Create a short link
2. Click it to, so it adds an entry to the log table
3. Delete the short link
4. log table entry is not deleted

### Context

I expected to clean the logs if the URL is deleted. Why are they kept?

**Comment by ozh** [comment]
> Why are they kept?

Because we just never implemented this. I also could see a number of reason why to _not_ delete logs.

What you're asking for is not planned for the moment, and can be relatively easily done with a plugin. See https://yourls.org/docs/guide/extend/possible-with-a-plugin/
