### ISSUE TITLE
Issue about ${var} one PHP 8.2

### ISSUE THREAD

**Issue by garryde** [YOURLS/YOURLS#3498]
### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Summary

Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /www/wwwroot/sus.show/admin/index.php on line 295

<img width="1095" alt="image" src="https://user-images.githubusercontent.com/14953698/213463324-ebe1745a-57b6-4ad3-864f-dab7a2c5da77.png">

### Motivation

PHP 8.2: ${var} string interpolation deprecated

**Comment by LeoColomb** [comment]
Fixed by https://github.com/YOURLS/YOURLS/pull/3474

Will be part of next YOURLS release, 1.9.2.
