### ISSUE TITLE
requesting add gives error on php8.2 but works fine with php7.4

### ISSUE THREAD

**Issue by rjwmtgevolution** [YOURLS/YOURLS#3506]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://docs.yourls.org/guide/troubleshooting/first-steps.html) and [frequent issues](https://docs.yourls.org/guide/troubleshooting/frequent-issues.html) guides.

### Version

1.9.1

### Description

php8.2 on ubuntu 22.04, 
url to be shortened
https://securian.events/index.php/63DD7B2294B92.html?eventId=63DD7B2294B92&page=5384

url call to add
https://securian.events/y/admin/admin-ajax.php?action=add&url=https%3A%2F%2Fsecurian.events%2Findex.php%2F63DD7B2294B92.html%3FeventId%3D63DD7B2294B92%26page%3D5384&keyword=&nonce=3f9e362fa2

error 500

If I do the exact same process on php7.4, the request goes through the short url is created.

### Expectation

a short url in return

### Reproduction steps

php8.2 on ubuntu 22.04, 
url to be shortened
https://securian.events/index.php/63DD7B2294B92.html?eventId=63DD7B2294B92&page=5384

url call to add
https://securian.events/y/admin/admin-ajax.php?action=add&url=https%3A%2F%2Fsecurian.events%2Findex.php%2F63DD7B2294B92.html%3FeventId%3D63DD7B2294B92%26page%3D5384&keyword=&nonce=3f9e362fa2

error 500

If I do the exact same process on php7.4, the request goes through the short url is created.

### Context

shortened url in return

**Comment by dgw** [comment]
#3474 should fix this for the next release, 1.9.2

**Comment by rjwmtgevolution** [comment]
Ok, any idea when 1.9.2 will be available?

**Comment by dgw** [comment]
When @ozh is ready to release it, I'd guess.

**Comment by ozh** [comment]
https://github.com/YOURLS/YOURLS/releases/tag/1.9.2 🍕
