### ISSUE TITLE
Wrong Date/Time Display

### ISSUE THREAD

**Issue by NordFreak** [YOURLS/YOURLS#3524]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://docs.yourls.org/guide/troubleshooting/first-steps.html) and [frequent issues](https://docs.yourls.org/guide/troubleshooting/frequent-issues.html) guides.

### Version

1.9.1

### Description

After Upgrade to the newest version, i have a wrong date/time output. 

![grafik](https://user-images.githubusercontent.com/125671870/219679160-50f3548b-8b7a-4a0d-8f3d-a898773c3b32.png)

**Comment by ozh** [comment]
Seems like an error in the translation file you're using, check with the translator
