### ISSUE TITLE
WORDPRESS WEBSITES (Multiple) -> Single Security Token is Unfair and Unresponsive

### ISSUE THREAD

**Issue by bhonsle-chand** [YOURLS/YOURLS#3532]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://docs.yourls.org/guide/troubleshooting/first-steps.html) and [frequent issues](https://docs.yourls.org/guide/troubleshooting/frequent-issues.html) guides.

### Version

1.9.1

### Description

I have a multiple (as of now 4-5) websites having wordpress plugin to publish short urls to twitter handle, 4-5 sometimes in a day it is done autoposting but considering 4-5 website all use same security token. My self hosted YOURLS doesn't respond to all websites at a time and the posts the content without shortening the url.

### Expectation

There should have been different API / security token for each websites using the same short url website.

### Reproduction steps

1. self hosted server for YOURLS and Wordpress Websites (Multiples)
2. use of security token for each website would help in address the problem

### Context

use of security token for each website would help in address the problem

**Comment by ozh** [comment]
If I understand correctly (and I'm not sure I'm doing) : sometimes your YOURLS install shortens, sometimes it doesn't.

I don't understand how having multiple tokens would address the issue.

**Comment by ozh** [comment]
> @ozh yes dear, sometimes it does but sometimes doesn't

Then there's probably something wrong with your install or setup or networking or anything . To qualify it as a bug, it needs to be replicable so we know what to inspect.

Anyway, you already have multiple tokens : tokens are unique to a user. Simply create one user for every WP blog you have.
