### ISSUE TITLE
Short Link get 404 Error.

### ISSUE THREAD

**Issue by XHyperDEVX** [YOURLS/YOURLS#3538]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://docs.yourls.org/guide/troubleshooting/first-steps.html) and [frequent issues](https://docs.yourls.org/guide/troubleshooting/frequent-issues.html) guides.

### Version

1.9.2

### Description

I have reinstalled Yourls today and yesterday a total of probably 4 times. Since they have released about 1 hour ago V1.9.2 I just tried this. Same problem.
Again and again I had the problem that shortened pages show me a 404 error. I have worked through the docs [https://yourls.org/docs/guide/troubleshooting/frequent-issues] several times, no changes.
The .htaccess file is exactly as it should be.

The funny thing is, when reinstalling the default shortlinks [like domain.tld/ozh] work. But when I delete them and link e.g. youtube.com with ozh I get a 404 error again.
As if when I save the links they are not transferred to the database. I have also set up the database again several times. MariaDB.

I did 1:1 exactly the steps I did from the installation guide [https://yourls.org/docs/guide/install] on an older system about 1 week ago and everything went smoothly.

I am running on Debian with Apache2 and PHP 8.1.

### Expectation

That I am redirected and do not get a 404 error 

### Reproduction steps

1. Install Yourls like https://yourls.org/docs/guide/install
2. Make a Shortlink
3. Get a 404 Error on the Link

### Context

All infos above

**Comment by ozh** [comment]
https://yourls.org/docs/category/troubleshooting

**Comment by XHyperDEVX** [comment]
Did they even read my message? I have read https://yourls.org/docs/category/troubleshooting or https://yourls.org/docs/guide/troubleshooting/frequent-issues and the steps given have **NOT HELPED**.

**Comment by ozh** [comment]
"They" read your message, stating that 
1) you've done everything correctly and that your config is like it should be (but you provide no actual info, url, config, htaccess, whatever
2) you've read all the pages yet you don't provide feedback on what is mentioned on these pages (for instance: server logs?)
3) you've installed YOURLS on another instance and it works perfectly.

Based on that, I fail at seeing how I can help.

**Comment by XHyperDEVX** [comment]
I have found the error. It was due to my Apache configuration. Now everything works.

Yes, the error was not with the program, but except for a "Make sure your server configuration is correct." there was nothing in their doc that could indicate an SSL problem.
I told you that everything is as described in their docs. I.e. the way it should be installed. Which was the case, the error was outside of Yourls, it was in Apache.

I'm glad to use Yourls now, because it's really good, but more than just sending a simple link where it was communicated before that it was already read and marking the problem as closed I find very user unfriendly, even if they don't necessarily do that as their main job.

I am happy to be able to use Yourls now and would like to thank them for offering it for free and open source. 

Have a nice evening :)

**Comment by dgw** [comment]
Sometimes, as you said yourself, the error lies outside of the software we maintain. As maintainers of YOURLS, we can't be expected to think of every possible upstream problem in Apache—especially when you shared none of your configuration or logs.

It's impossible to put too much stress on the fact that open-source maintainers, like all other humans on this planet, _are not telepaths_ and have _zero_ knowledge of your environment beyond what is included in the discussion or issue submitted. If it's not provided in the ticket, we don't know it.

Should you wish to help future users who might run into a similar problem, I encourage you to briefly summarize 1) what caused the problem, 2) how you found the cause, and 3) how you fixed it.

We are, of course, glad you solved the problem, and happy that you find the project useful. 🙂

**Comment by XHyperDEVX** [comment]
I had to add the following in the Apache Virtual Host configuration to make it work.

```
    <Directory "/path/to/your/yourls/root">
        Header set Access-Control-Allow-Origin "*"
        Require all granted
        Options Indexes FollowSymLinks
        AllowOverride All
        Order allow,deny
        Allow from all
    </Directory>
```

I already had this in my virtual host, but only in the HTTP config. This made the link shortener work even if I called the link via http. I added the above to my SSL config and immediately it worked over HTTPS.

This is how the HTTP config should look like.

```
<VirtualHost *:80>
    ServerName domain.tld

    DocumentRoot "/path/to/your/yourls/root"

    <Directory "/var/www/html/yourls">
        Header set Access-Control-Allow-Origin "*"
        Require all granted
        Options Indexes FollowSymLinks
        AllowOverride All
        Order allow,deny
        Allow from all
    </Directory>
</VirtualHost>
```

HTTPS looks different for everyone, so there is a clear picture there. There are differences if you do it manually or with bots like certbot.

**Comment by tcreek** [comment]
I tried those and got errors on nearly every single one of them
 
` Header set Access-Control-Allow-Origin "*"` = Invalid command 'Header'

All the other ones except for "Options" I got: `XXX  not allowed in <VirtualHost> context`
