### ISSUE TITLE
Reset(Clear)-Button for statistics

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#354]
This is a **COPY** of **Issue 354: [Reset(Clear)-Button for statistics](http://code.google.com/p/yourls/issues/detail?id=354)**, filed on Google Code before the project was [moved on Github](https://github.com/ozh/google-issues-to-github).
- Submitted on 2010-06-03T09:41:20.000Z by [aff...@da-gaming.de](http://code.google.com/u/101556234808510172062/)
- Status: WontFix

Please **review** the original issue and especially its comments. **Comments here on closed issues will be ignored**. Thanks.
## Original description

```
Without manually 
erasing of the log my database increases every month to 4-6 GB.

So it would be nice if there was a way to clear/reset the statistics of the 
rows with clearing the db.

I would put a button to "actions" to do this with a question what the user 
wants to clear (log, clicks) or totally reset the statistics of the row to 
"0"
```

**Comment by bennygill** [comment]
Was there any progress on this? Or a perhaps a plugin that was made?

I would also like to clear the stats for some of my links.
