### ISSUE TITLE
wish: Integration into [next|own]cloud

### ISSUE THREAD

**Issue by sotel** [YOURLS/YOURLS#3555]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Summary

YOURLS is nice and useful also in a **cloud environment** like **Nextcloud** or **ownCloud**. I would appreciate it if YOURLS is integrated into *cloud as a loadable app.

### Motivation

If YOURLS is an app in a *cloud environment it will enhance the cloud for the users of this cloud and simplifies a lot for the user who gave access to parts of the cloud, e.g d teacher for his pupils during online training.

### Describe the solution

Please analyze how to create a Nextcloud or ownCloud app.

**Comment by dgw** [comment]
A Nextcloud app that connects to the YOURLS API could indeed be useful, but implementing one is not within the scope of our work on YOURLS itself. I would invite you to request this integration within the Nextcloud community.
