### ISSUE TITLE
spanish language please to 1.9.2 v.

### ISSUE THREAD

**Issue by julbroa** [YOURLS/YOURLS#3559]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Summary

I install spanish language to 1.7 ver. but dont translate

### Motivation

spanish speakers need your app in your language

### Describe the solution

please translate your great app to spanish language

**Comment by dgw** [comment]
Out of scope; we do not maintain the translations. See kralizeck/YOURLS-es_ES#1
