### ISSUE TITLE
Uppercase letters in mobile

### ISSUE THREAD

**Issue by TEBandCo** [YOURLS/YOURLS#3588]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://docs.yourls.org/guide/troubleshooting/first-steps.html) and [frequent issues](https://docs.yourls.org/guide/troubleshooting/frequent-issues.html) guides.

### Version

1.9.2

### Description

When creating a short link on mobile, the font is all uppercase. When this is copied, it leads to a bad links that send the user back to the homepage.

### Expectation

Create a lowercase link.

### Reproduction steps

Go to https://b.fail on mobile
Create and copy link.
Paste link, it'll as all capitals and will redirect to homepage when used.

**Comment by LeoColomb** [comment]
Thanks for opening this issue @TEBandCo.
That being said, the behavior reported has nothing to do with YOURLS itself.
The "uppercase-font" is part of custom pages/theme, which is not developed by the YOURLS team.
Please reach out theme author.
