### ISSUE TITLE
PHP Warning:  Constant YOURLS_DEBUG already defined in /var/www/YOURLS/user/config.php on line 95

### ISSUE THREAD

**Issue by jason-weiser** [YOURLS/YOURLS#3591]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://docs.yourls.org/guide/troubleshooting/first-steps.html) and [frequent issues](https://docs.yourls.org/guide/troubleshooting/frequent-issues.html) guides.

### Version

1.9.2

### Description

YOURLS is flooding my Apache error.log with the following line:

`PHP Warning:  Constant YOURLS_DEBUG already defined in /var/www/YOURLS/user/config.php on line 95`

I found it when I was looking for the root of a separate issue, but it appears to be logging that warning several times a minute.

### Expectation

Probably not doing that. 

### Reproduction steps

1. Normal install of YOURLS
2. Look at /var/log/apache/error.log

### Context

Normal use. No other errors or issues. Very minor issue, but it would be nice to have the logs a little cleaner.

**Comment by LeoColomb** [comment]
Thanks for reporting @jason-weiser.
That being said, just drop the line 95 on your `user/config.php`, [it is not shipped per default with YOURLS](https://github.com/YOURLS/YOURLS/blob/65655a5c7ba031be611045bb04c9b3a99bbdf170/user/config-sample.php).

**Comment by jason-weiser** [comment]
Wow. Yeah, sorry, I should have checked about that before posting this. This is a very old install I've carried with me across servers for years and must have enabled that some time ago and forgotten about it.

Thanks so much for all the work on this. YOURLS is fantastic.
