### ISSUE TITLE
Make/Integromat integration stopped working

### ISSUE THREAD

**Issue by outbound** [YOURLS/YOURLS#3618]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://docs.yourls.org/guide/troubleshooting/first-steps.html) and [frequent issues](https://docs.yourls.org/guide/troubleshooting/frequent-issues.html) guides.

### Version

1.9.1

### Description

I used the YOURLS module in Make/Integromat and it worked well - v 1.7.2

At some point, I updated to 1.9.1 
- after a month or so, when I ran this module - the integration fails with this error

"Invalid module output. Expected Object, but found String."

Steps I have taken
1. Checked manual link shortening works - via the admin
2. Setup a new connection in Make to Yourls and tested it's working
3. Simplified the integration to contain just an Airtable and YOURLS module

![image](https://github.com/YOURLS/YOURLS/assets/824269/5ea9e785-f8d2-4edc-a14c-c9f116d176e5)

![image](https://github.com/YOURLS/YOURLS/assets/824269/3d1241e9-2db0-425e-8623-e05c004886ed)

![image](https://github.com/YOURLS/YOURLS/assets/824269/68e2b5af-95ed-4f34-95cf-6473abedd176)

4. Ran a test with just the YOURLS module and hard-coded link sand keyword

5. Checked the YOURLS admin
I see the URL being sent there - (https://cnn.com) but not being converted to the short URL, like the ones below it 
The two links below it were converted via the same Make modulle

![image](https://github.com/YOURLS/YOURLS/assets/824269/ef3ba9c0-a5fb-409f-9a4b-306ddda47482)

### Expectation

I expect Yourls to return a short URL

### Reproduction steps

1. Run the scenario
2. Remove all other items and create a standalone scenario
3. Same error received

![image](https://github.com/YOURLS/YOURLS/assets/824269/824e4c9f-00d2-4ccd-87c8-563a10381b9a)

![image](https://github.com/YOURLS/YOURLS/assets/824269/55fbfedc-2edb-47a6-a5ac-9a2dac63b36c)

### Context

Running on a self-hosted wordpress website. Nothing has changed  on the website - PHP v8

**Comment by dgw** [comment]
I don't see how this could be considered a YOURLS problem. Any automation template provided by Make is their responsibility to maintain, and we (the YOURLS maintainers) have nothing to do with it.

Especially if the failure began happening at a different time than your upgrade to YOURLS 1.9.x, the problem almost certainly lies on the Make end.

**Comment by outbound** [comment]
The failure did not begin happening at a different time. 
I simply stated that I didn't check right after upgrading to 1.9.1 if that caused the failure. There was a month or so long gap between my upgrading YOURLS and running  the automation and seeing it not work. 
I run the automation occasionally. 

I've posted this in the Make forum as well, and they're looking into it - rather than simply pointing the finger at YOURLS. 

I'm asking for even a cursory attempt to look at the issue rather than dismissing it out of hand. 

Respectfully yours.

**Comment by dgw** [comment]
> The failure did not begin happening at a different time. I simply stated that I didn't check right after upgrading to 1.9.1 if that caused the failure.

> I'm asking for even a cursory attempt to look at the issue rather than dismissing it out of hand.

First of all, by upgrading two minor versions at once, you run a greater risk of changes that could break a third-party integration like this. [Even bug fixes can "break" things.](https://xkcd.com/1172/)

Second, having taken 10 minutes to create a Make account just now and clicked YOURLS in the list of available modules, I can't find any way for me to actually see what the integration is doing. It asks me for an instance URL, username, and password—and that's it. I can't see the script or other backend code that actually talks to YOURLS, how it's assembling the API request…

Third & finally:

> 2. Setup a new connection in Make to Yourls and tested it's working

If a fresh connection does work, that really seems more likely to be a platform issue on Make's end. Which would be ideal, because even if we could debug Make's integration we couldn't actually modify it with a fix.
