### ISSUE TITLE
AbstractExtendedPdo.php's Error

### ISSUE THREAD

**Issue by jiespring** [YOURLS/YOURLS#3625]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://docs.yourls.org/guide/troubleshooting/first-steps.html) and [frequent issues](https://docs.yourls.org/guide/troubleshooting/frequent-issues.html) guides.

### Version

1.9.1

### Description

When I click install on the admin/install.php page, the following error pops up
` Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 3 Error writing file './example_com/yourls_url.frm' (Errcode: 28) in /www/wwwroot/example.com/includes/vendor/aura/sql/src/AbstractExtendedPdo.php:565 Stack trace: #0 /www/wwwroot/example.com/includes/vendor/aura/sql/src/AbstractExtendedPdo.php(565): PDOStatement->execute() #1 /www/wwwroot/example.com/includes/functions-install.php(259): Aura\Sql\AbstractExtendedPdo->perform() #2 /www/wwwroot/example.com/admin/install.php(45): yourls_create_sql_tables() #3 {main} thrown in /www/wwwroot/example.com/includes/vendor/aura/sql/src/AbstractExtendedPdo.php on line 565`

### Reproduction steps

1、Download the file, unzip it, and copy it to the site root

2、Modify the file name of config.php to modify the content

3、Added in the nginx configuration file and restart nginx
`location / {
try_files $uri $uri/ /yourls-loader.php?$args;
}`
4. open example.com/admin/install.php
5.  When I click the install link, an error page pops up
6. version：nginx1.17.10   ，MySQL 5.5.62，  PHP-7.4.25 

### Context

How is normal installation complete and can be used

**Comment by dgw** [comment]
The directory where MySQL is trying to write files has either insufficient space or insufficient inodes. https://stackoverflow.com/a/7415732/5991

*Note: This _is_ a personal support request and should have been opened as a discussion.*
