### ISSUE TITLE
Hide url feature

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#363]
This is a **COPY** of **Issue 363: [Hide url feature](http://code.google.com/p/yourls/issues/detail?id=363)**, filed on Google Code before the project was [moved on Github](https://github.com/ozh/google-issues-to-github).
- Submitted on 2010-06-11T02:42:25.000Z by [Harvey2...@gmail.com](http://code.google.com/u/113097417576952546260/)
- Status: WontFix

Please **review** the original issue and especially its comments. **Comments here on closed issues will be ignored**. Thanks.
## Original description

```
**What feature do you suggest ?**

Would you link to add Hide url to Yourls? That means the short url will show in the address bar instead of jump to the original url.

Hide url feature may be welcomed by the blogger.  
```

**Comment by sameh-yasuo** [comment]
Hi bro I have yourls and I want to redirect to the short url in the browser bar what can I do please update me

**Comment by dgw** [comment]
@sameh-yasuo It sounds like you want the opposite of #2988/#3320. If the described plugin does not do what you want, please [open your own _discussion_](https://github.com/YOURLS/YOURLS/discussions/new?category=plugins) about it.
