### ISSUE TITLE
Error 403 Forbidden + solution (v1.9.2)

### ISSUE THREAD

**Issue by Padandish** [YOURLS/YOURLS#3631]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://docs.yourls.org/guide/troubleshooting/first-steps.html) and [frequent issues](https://docs.yourls.org/guide/troubleshooting/frequent-issues.html) guides.

### Version

1.9.2

### Description

When I first installed version 1.9.2, I got a 403 error when requesting a link instead of a redirect.
After checking the yourls-loader.php file, I realized that after the exit; In line 53, the program goes to line 63 and leads to this error.

Therefore, I rewrote this file as follows and the problem was solved:

Webserver: Nginx  nginx/1.18.0 (Ubuntu)
PHP: 8.1-fpm

Nginx server block:
```
server {

	listen 80;
	listen [::]:80;

	server_name xxxxx.xxx;
	root /var/www/xxxxx.xxx;

	location / {
		try_files $uri $uri/ /yourls-loader.php$is_args$args;
	}

	location ~ \.php$ {
		include fastcgi.conf;
		fastcgi_index index.php;
		fastcgi_pass unix:/var/run/php/php8.1-fpm.sock;
	}
}
```

### Expectation

Rewrote yourls-loader.php

### Reproduction steps

yourls-loader.php rewritten:
```
<?php
if ( '/favicon.ico' == $_SERVER['REQUEST_URI'] ) {
	header( 'Content-Type: image/gif' );
	echo base64_decode( "R0lGODlhEAAQAJECAAAAzFZWzP///wAAACH5BAEAAAIALAAAAAAQABAAAAIplI+py+0PUQAgSGoNQFt0LWTVOE6GuX1H6onTVHaW2tEHnJ1YxPc+UwAAOw==" );
	exit;
}

// Handle inexistent root robots.txt requests and exit
else if ( '/robots.txt' == $_SERVER['REQUEST_URI'] ) {
	header( 'Content-Type: text/plain; charset=utf-8' );
	echo "User-agent: *\n";
	echo "Disallow:\n";
	exit;
}

else {	
	// Load YOURLS
	require_once __DIR__ . '/includes/load-yourls.php';

	// Get request in YOURLS base (eg in 'http://sho.rt/yourls/abcd' get 'abdc')
	// At this point, $request is NOT sanitized.
	$request = yourls_get_request();

	// Now load required template and exit
	yourls_do_action( 'pre_load_template', $request );

	// Let's look at the request : what we want to catch here is "anything", or "anything+" / "anything+all" (stat page)
	preg_match( "@^(.+?)(\+(all)?)?/?$@", $request, $matches );
	$keyword   = isset($matches[1]) ? $matches[1] : null; // 'anything' whatever the request is (keyword, bookmarklet URL...)
	$stats     = isset($matches[2]) ? $matches[2] : null; // null, or '+' if request is 'anything+', '+all' if request is 'anything+all'
	$stats_all = isset($matches[3]) ? $matches[3] : null; // null, or 'all' if request is 'anything+all'

	// if request has a scheme (eg scheme://uri) : "Prefix-n-Shorten" sends to bookmarklet (doesn't work on Windows)
	if ( yourls_get_protocol($keyword) ) {
		$url = yourls_sanitize_url_safe($keyword);
		$parse = yourls_get_protocol_slashes_and_rest( $url, [ 'up', 'us', 'ur' ] );
		yourls_do_action( 'load_template_redirect_admin', $url );
		yourls_do_action( 'pre_redirect_bookmarklet', $url );

		// Redirect to /admin/index.php?up=<url protocol>&us=<url slashes>&ur=<url rest>
		yourls_redirect( yourls_add_query_arg( $parse , yourls_admin_url( 'index.php' ) ), 302 );
		exit;
	}

	// if request is an existing short URL keyword ('abc') or stat page ('abc+') or an existing page :
	else if ( yourls_keyword_is_taken($keyword) or yourls_is_page($keyword) ) {

		// we have a short URL or a page
		if( $keyword && !$stats ) {
			yourls_do_action( 'load_template_go', $keyword );
			require_once( YOURLS_ABSPATH.'/yourls-go.php' );
			exit;
		}

		// we have a stat page
		else if( $keyword && $stats ) {
			$aggregate = $stats_all && yourls_allow_duplicate_longurls();
			yourls_do_action( 'load_template_infos', $keyword );
			require_once( YOURLS_ABSPATH.'/yourls-infos.php' );
			exit;
		}
		
		else {
			yourls_do_action( 'redirect_keyword_not_found', $keyword );
			yourls_do_action( 'loader_failed', $request );
			yourls_redirect( YOURLS_SITE, 302 );
			exit;
		}
	}

	else {		
		// Past this point this is a request the loader could not understand : not a valid shorturl, not a bookmarklet
		yourls_do_action( 'redirect_keyword_not_found', $keyword );
		yourls_do_action( 'loader_failed', $request );
		yourls_redirect( YOURLS_SITE, 302 );
		exit;
	}
}
```

**Comment by dgw** [comment]
> After checking the yourls-loader.php file, I realized that after the exit; In line 53, the program goes to line 63 and leads to this error.

Simply put, not possible. `exit;` exits the program. It does not continue to another line.

Something else you changed fixed the problem. 4xx errors instead of redirection for shortlinks is a very common issue in incorrectly configured instances.

**Comment by Padandish** [comment]
> > After checking the yourls-loader.php file, I realized that after the exit; In line 53, the program goes to line 63 and leads to this error.
> 
> Simply put, not possible. `exit;` exits the program. It does not continue to another line.
> 
> Something else you changed fixed the problem. 4xx errors instead of redirection for shortlinks is a very common issue in incorrectly configured instances.

in php-8.1:
You are sending a Location header before calling exit(), which redirects the page to another URL. This may cause the exit() function to be ignored or delayed.

**Comment by dgw** [comment]
What? PHP's example usage of [`header()`](https://www.php.net/manual/en/function.header.php) shows sending a `Location` header followed immediately by `exit;`:

```php
<?php
header("Location: http://www.example.com/"); /* Redirect browser */

/* Make sure that code below does not get executed when we redirect. */
exit;
?>
```

Exiting prevents any further code execution, and therefore prevents PHP from sending any further content to the client after the new URL has been sent.

That won't hold true if some plugin code has already sent non-header content by the time `yourls_redirect()` gets called, but at that point it isn't YOURLS' fault and should not be fixed by [hacking core](https://yourls.org/docs/development/dont-hack-core).
