### ISSUE TITLE
Uppercase letters are removed and not converted if used in custom short URL if yourls is configured to use only lowercase letters

### ISSUE THREAD

**Issue by joshuabeny1999** [YOURLS/YOURLS#3632]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://docs.yourls.org/guide/troubleshooting/first-steps.html) and [frequent issues](https://docs.yourls.org/guide/troubleshooting/frequent-issues.html) guides.

### Version

1.9.2

### Description

If only lowercase is allowed in Yourls (`YOURLS_URL_CONVERT=32`) then any uppercase letters are removed from the short URL. So for example _Test4DK_ results to _est4k_

### Expectation

Correct conversion to lowercase and not removing uppercase letters. So String "Test4DK" would result to "test4dk". Alternatley the Input Field should be configured to not allow uppercase at all. But i think the conversion would be a better approach so it works too on API. 

### Reproduction steps

1. Make sure that in Config.php the Varible `YOURLS_URL_CONVERT``is set to 32.
2. Open Admin Center
3. Enter any URL not already shortened
4. Enter following string for example "Test4DK" in Custom short URL
5. URL will be shorted to "est4"

I tested it on multiple instances and could always reproduce it. 

### Context

Set following in config.php
```php
YOURLS_URL_CONVERT=32;
```

**Comment by dgw** [comment]
This is why plugins exist. https://github.com/YOURLS/force-lowercase
