### ISSUE TITLE
'inis' error

### ISSUE THREAD

**Issue by jiespring** [YOURLS/YOURLS#3633]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://docs.yourls.org/guide/troubleshooting/first-steps.html) and [frequent issues](https://docs.yourls.org/guide/troubleshooting/frequent-issues.html) guides.

### Version

1.9.1

### Description

It seems impossible to set the short link character to 'inis'

**Comment by dgw** [comment]
Cannot reproduce on 1.9.2:

```
$ curl --head https://my.short.domain/inis
HTTP/2 302
date: Mon, 25 Sep 2023 10:09:03 GMT
server: Apache
x-robots-tag: noindex
location: https://www.example.com/
cache-control: max-age=600
expires: Mon, 25 Sep 2023 10:19:03 GMT
vary: User-Agent
content-type: text/html; charset=UTF-8
```

**Comment by dgw** [comment]
Also works in Firefox, for me.

I think it's safe to say this is not a YOURLS problem.

**Comment by jarebear6expepjozn6rakjq5iczi3irqwphcvb** [comment]
Just to add @jiespring: if you are creating a short URL without adding a protocol to the original URL (http:// or https://, et al.) it will cause the behavior you are experiencing when loading that short URL. Worth double checking, anyway.
