### ISSUE TITLE
Statistics isn't shown

### ISSUE THREAD

**Issue by amiliaev** [YOURLS/YOURLS#3661]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://docs.yourls.org/guide/troubleshooting/first-steps.html) and [frequent issues](https://docs.yourls.org/guide/troubleshooting/frequent-issues.html) guides.

### Version

1.9.2

### Description

After clicking Statistics the error message appears, that there is no such page found on the server
![Снимок экрана 2023-11-06 в 22 22 40](https://github.com/YOURLS/YOURLS/assets/45568854/2c2ffa81-cd3a-4df2-b80e-9a36def2a7c1)

### Expectation

statistics is shown below the link

### Reproduction steps

1. go to admin panel
2. click on Statistics right to the URL, I wanted to see statistics
3. I'm redirected to the error message page, that this page wasn't found

**Comment by dgw** [comment]
This is almost certainly a server configuration issue, or possibly a plugin conflict.

At the risk of sounding like "_that_ project maintainer", statistics work just fine for me on 1.9.2.

**Comment by amiliaev** [comment]
Thanks!

And sorry, will try to reinstall completely - I tried to install themes, may be they caused the problem.

BTW, no theme is working.. :(
Is there some actual theme, supporting 1.9.2?

**Comment by dgw** [comment]
We don't maintain third-party themes ourselves, obviously. (That's what makes them third-party.)

Knowing what you tried to do could help make YOURLS more robust, if you figure out a definite cause. :)

**Comment by amiliaev** [comment]
> We don't maintain third-party themes ourselves, obviously. (That's what makes them third-party.)
> 
> Knowing what you tried to do could help make YOURLS more robust, if you figure out a definite cause. :)

Just tried to unstall sleeky theme and statistics stopped working

**Comment by dgw** [comment]
Ah, not the first I've heard of problems caused by Sleeky. Seems to be not-really-maintained these days, which is too bad. I used it on an older YOURLS instance that no longer exists; it was neat.

**Comment by amiliaev** [comment]
> We don't maintain third-party themes ourselves, obviously. (That's what makes them third-party.)

of course, I understand. that was a question - may be there are some new and actual themes for YOURLS - it's very cool and useful, but not for mobile use.  :(

**Comment by dgw** [comment]
There's a small list of themes (including Sleeky, hmm) [on the Awesome list](https://github.com/YOURLS/awesome#themes), but YOURLS 1.x isn't really designed to support theming. The WIP 2.0 branch is a lot better at it, but I couldn't tell you when that's coming.

**Comment by amiliaev** [comment]
Actually, I tried all three themes and all of them are not working properly... Air 66 doesn't show the menu at all, Sleeky breaks statistics, Infinity squared is only frontend actually, but the it's Bookmarklet doesn't work at all. And for the last, I don't need to have the public shortener, just the private one. So it's useless for me at all.

**Comment by amiliaev** [comment]
> There's a small list of themes (including Sleeky, hmm) [on the Awesome list](https://github.com/YOURLS/awesome#themes), but YOURLS 1.x isn't really designed to support theming and it looks like none of the entries are particularly maintained any more (based on commit activity). The WIP 2.0 branch is a lot better at it, but I couldn't tell you when that's coming.

I see, thanks. So I better will use the pure YOURLS and waiting for the new release. thanks again!

**Comment by amiliaev** [comment]
Ah, Is that planned to make the folders for the URLs inside the admin panel?

**Comment by dgw** [comment]
I encourage you to make use of issue search for further feature questions. (And remember to include closed issues.) https://github.com/YOURLS/YOURLS/issues/3459#issuecomment-1312603515
