### ISSUE TITLE
Problem in shortening links from a given website

### ISSUE THREAD

**Issue by mohammadshg84** [YOURLS/YOURLS#3667]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://docs.yourls.org/guide/troubleshooting/first-steps.html) and [frequent issues](https://docs.yourls.org/guide/troubleshooting/frequent-issues.html) guides.

### Version

1.9.2

### Description

None of the [rentry.co](https://rentry.co) site links are shortened and get stuck in the loading phase of shortening. Also I don't see any _error_log_ and I can't figure out what the problem is.
For example, you can write a text on [this site](http://rentry.co), or try [this link](https://rentry.co/rhip2/raw).

**Comment by ozh** [comment]
https://ozh.in/zw -- works fine. YOURLS doesn't care what you shorten, if the site exists or even if it's a website at all.

See https://yourls.org/docs/guide/troubleshooting/frequent-issues#endless-spinning-icon
