### ISSUE TITLE
Instead of comma/point, the thousands separator is written-out

### ISSUE THREAD

**Issue by Der-K-2000** [YOURLS/YOURLS#3668]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://docs.yourls.org/guide/troubleshooting/first-steps.html) and [frequent issues](https://docs.yourls.org/guide/troubleshooting/frequent-issues.html) guides.

### Version

1.9.2

### Description

In the stats you can find in the table (see screenshot) the **thousands separator** is written-out, so it's (for the german version) not `1.915`, but `1Zahlenformat Tausender-Trennzeichen915`.

![thousand](https://github.com/YOURLS/YOURLS/assets/7254827/fc633167-2cfb-4646-ae08-d4e86b8108ad)

### Expectation

**Point** as a separator (in German)

### Reproduction steps

Open the admin page with the list

**Comment by ozh** [comment]
This is a bug with the German translation then, not YOURLS ?
