### ISSUE TITLE
Allow special characters in custom short URLs

### ISSUE THREAD

**Issue by ericswpark** [YOURLS/YOURLS#3675]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Summary

Currently there is no way to have short URLs with special characters (i.e. yourls.example.com/example/test-a, assuming YOURLS is hosted at yourls.example.com). When I attempt to add a short URL with special characters, it just excludes them and creates yourls.example.com/exampletesta

### Motivation

This would allow categorizing short URLs. For example, yourls.example.com/2023/year-in-review would be different from yourls.example.com/2024/year-in-review

### Describe the solution

Allow custom short URLs to have special characters

**Comment by dgw** [comment]
This falls squarely under https://yourls.org/docs/guide/extend/possible-with-a-plugin

In fact, you'll find [a plugin that adds the `/` character](https://github.com/williambargent/YOURLS-Forward-Slash-In-Urls) listed on [the Awesome list](https://github.com/YOURLS/awesome#a). YOURLS [ships with an "Allow Hyphens in Short URLs" plugin](https://github.com/YOURLS/YOURLS/blob/f7fbeacf8bba2d7459262ffdc9c2ff8dfb35f3ef/user/plugins/hyphens-in-urls/plugin.php#L1) that can be copied and modified to add all the characters you'd like into the accepted charset.
