### ISSUE TITLE
Req: It is recommended that webmasters be allowed to set up separate domain names for administrative pages

### ISSUE THREAD

**Issue by 8MiYile** [YOURLS/YOURLS#3680]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Summary

https://github.com/YOURLS/YOURLS/blob/master/includes/functions-links.php#L166

### Motivation

Admin page requires a separate domain name
Allow webmasters to transfer https://exam.ple/admin
Replace with https://admin.exam.ple
By checking this constant
defind ('YOURLS_ADMIN_PAGE_DOMAIN','admin.exam.ple')

**Comment by ozh** [comment]
We're not introducing more constants, by design choice.

Having a separate domain admin page is a typical example of a very specific use that does not interest 99.5% of the people, therefore we won't bloat core with such a feature. This is plugin territory.
