### ISSUE TITLE
Can not use my.domain/yourls as my shorturl

### ISSUE THREAD

**Issue by Doublefire-Chen** [YOURLS/YOURLS#3685]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://docs.yourls.org/guide/troubleshooting/first-steps.html) and [frequent issues](https://docs.yourls.org/guide/troubleshooting/frequent-issues.html) guides.

### Version

1.9.2

### Description

I deleted the built-in shorturl of yourls and add a new shorturl the same name with the old built-in one. But it does not take effect. When I visit https://nj.mk/yourls , it should redirect me to https://aka.cy/2023/12/13/How-to-install-YOURLS-with-caddy/, however, it redirects me to its old address https://yourls.org/
<img width="981" alt="Screenshot 2023-12-13 at 12 38 39" src="https://github.com/YOURLS/YOURLS/assets/72138342/e709566b-fd87-4a9f-87bc-a9ebd96636a1">

### Expectation

When I visit https://my.domain/yourls , it should redirect me to my set website instead of https://yourls.org/

### Reproduction steps

1. delete the built-in shorturl of yourls
2. add a new shorturl the name yourls
3. visit the new shorturl my.domain/yourls

**Comment by dgw** [comment]
301 Moved Permanently (the default redirection type used by YOURLS) is aggressively cached by many browsers and CDNs. Clear your browser cache.

**Comment by Doublefire-Chen** [comment]
Thank you, it works for me.
