### ISSUE TITLE
Long URLs without https:// (or another protocol) are not being redirected.

### ISSUE THREAD

**Issue by ruhsBB** [YOURLS/YOURLS#3692]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://docs.yourls.org/guide/troubleshooting/first-steps.html) and [frequent issues](https://docs.yourls.org/guide/troubleshooting/frequent-issues.html) guides.

### Version

1.9.2

### Description

Whenever I create a new short URL without https:// or another protocol (such as example.com) and then use the short url of it (eg sho.rt/xyz redirecting to example.com), it just brings me back to sho.rt. Is there a way I could force people to input links with a protocol to combat this? Thanks!

### Context

I expected that the shortened link would not redirect me to my home page.

**Comment by ozh** [comment]
Excepted behaviour. YOURLS shortens anything : http links, ftp links, mailto, anything... or even relative links without scheme.

This is plugin territory : make one that, when a submitted link misses a scheme, adds one ? See https://yourls.org/docs/guide/extend/possible-with-a-plugin
