### ISSUE TITLE
Can't connect with a valide password

### ISSUE THREAD

**Issue by ChukapiTCG** [YOURLS/YOURLS#3718]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://docs.yourls.org/guide/troubleshooting/first-steps.html) and [frequent issues](https://docs.yourls.org/guide/troubleshooting/frequent-issues.html) guides.

### Version

1.9.2

### Description

On the login page, when trying to connect myself i got the message "Please log in"

First i was thinking my password was wrong : i created a new user with an easy password like "azerty" but it doesn't work. I tried to connect thru the api with this new credential : i could connect myself and generate a new link and the new password has been hashed like it was explain in th documentation.

### Expectation

Connection to the YOURLS' dashboard.

### Reproduction steps

1. Enter your username
2. Enter you password
3. Click on login
4. You still have the "Please log in"

### Context

I'm on mozilla firefox : i try it on edge, chrome and on private navigation for all of them.

**Comment by 2ndK16** [comment]
It does say so explicitly in `user/config.php`:
```php
/** YOURLS installation URL
 ** All lowercase, no trailing slash at the end.
 ** If you define it to "http://sho.rt", don't use "http://www.sho.rt" in your browser (and vice versa)
 **/
```
However, there is [a workaround](https://stackoverflow.com/questions/26394367/use-one-instance-of-yourls-url-shortner-with-multiple-domains): use the domain that Apache provides:
```php
define('YOURLS_SITE', 'http://' . $_SERVER['HTTP_HOST'] . '');
```
