### ISSUE TITLE
MariaDB issue

### ISSUE THREAD

**Issue by EDIflyer** [YOURLS/YOURLS#3727]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://docs.yourls.org/guide/troubleshooting/first-steps.html) and [frequent issues](https://docs.yourls.org/guide/troubleshooting/frequent-issues.html) guides.

### Version

1.9.2

### Description

Unable to access admin after update to MariaDB last night:
```
Incorrect DB config, or could not connect to DB PDOException: SQLSTATE[HY000] [2054] Server sent charset (0) unknown to the client. Please, report to the developers
```

### Expectation

Connect OK to database

### Reproduction steps

1. Update to MariaDB 11.3.2

### Context

I'm more just listing this for information in case anyone else runs into similar issues - I presume the fix will have to come from the MariaDB team - https://github.com/MariaDB/mariadb-docker/issues/566

As a temporary workaround I've fixed to the 11.2.3 docker image and it is working again.

**Comment by LeoColomb** [comment]
Thanks for opening this issue and the reference, @EDIflyer.
Thus, I'm closing in favor of upstream ticket https://github.com/MariaDB/mariadb-docker/issues/566.
