### ISSUE TITLE
short url + .qr = 404 Not Found

### ISSUE THREAD

**Issue by Slobug** [YOURLS/YOURLS#3749]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://docs.yourls.org/guide/troubleshooting/first-steps.html) and [frequent issues](https://docs.yourls.org/guide/troubleshooting/frequent-issues.html) guides.

### Version

1.7.2

### Description

Hi Everyone,

My application don't display QRcode, the result display : 40 Not Found.

**Url :** https://_mydomaine_/yourls/xv25z9.qr -> https://chart.apis.google.com/chart?chs=200x200&cht=qr&chld=M&chl=https://_mydomaine_/yourls/xv25z9

Someone can help me ?

Thanks

### Expectation

Display of image of qrcode

### Context

my application insert the QRcode in PDF.

**Comment by dgw** [comment]
Google seems to have turned off that endpoint. It was deprecated for quite some time. See YOURLS/website#204
