### ISSUE TITLE
geoip update broken

### ISSUE THREAD

**Issue by un99known99** [YOURLS/YOURLS#3754]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://docs.yourls.org/guide/troubleshooting/first-steps.html) and [frequent issues](https://docs.yourls.org/guide/troubleshooting/frequent-issues.html) guides.

### Version

v 1.9.2

### Description

gz geofile file empty error:

```console
sudo php /var/www/yourls/user/plugins/geoip-update/cron.php
```

```
PHP Fatal error:  Uncaught UnexpectedValueException: internal corruption of phar "/var/www/yourls/user/plugins/geoip-update/GeoLite2-Country.tar.gz" (truncated entry) in /var/www/yourls/user/plugins/geoip-update/vendor/tronovav/geoip2-update/src/Client.php:315
Stack trace:
#0 /var/www/yourls/user/plugins/geoip-update/vendor/tronovav/geoip2-update/src/Client.php(315): PharData->__construct()
#1 /var/www/yourls/user/plugins/geoip-update/vendor/tronovav/geoip2-update/src/Client.php(186): tronovav\GeoIP2Update\Client->extract()
#2 /var/www/yourls/user/plugins/geoip-update/vendor/tronovav/geoip2-update/src/Client.php(113): tronovav\GeoIP2Update\Client->updateEdition()
#3 /var/www/yourls/user/plugins/geoip-update/run.php(26): tronovav\GeoIP2Update\Client->run()
#4 /var/www/yourls/user/plugins/geoip-update/cron.php(6): ozh_yourls_geoip2_update_client_run()
#5 {main}
  thrown in /var/www/yourls/user/plugins/geoip-update/vendor/tronovav/geoip2-update/src/Client.php on line 315
```

```console
/var/www/yourls/user/plugins/geoip-update] #
-rw-r--r--  1 www-data www-data    0 May  2 07:47 GeoLite2-Country.tar.gz
```

Also updating via admin interface not working

**Comment by un99known99** [comment]
cat cron.php
// https://github.com/ozh/yourls-geoip-update/issues/2
<?php
$key = 'maxmid-KEY';
include_once __DIR__ . '/run.php';
$results = ozh_yourls_geoip2_update_client_run($key);
var_dump($results);
?>

**Comment by un99known99** [comment]
-rw-r--r-- 1 www-data www-data 6455950 Apr 25 04:47 GeoLite2-Country.mmdb
-rw-r--r-- 1 www-data www-data      10 Apr 25 04:47 last-modified.txt

stopped working Apr 25

**Comment by LeoColomb** [comment]
@un99known99 April 25 is almost exactly 2 years after your issue https://github.com/ozh/yourls-geoip-update/issues/2.
Are you sure your Maxmid private key is not just expired?

**Comment by un99known99** [comment]
@LeoColomb  already tried that, requested new one - same ....

**Comment by LeoColomb** [comment]
Did you also try to delete the file `/var/www/yourls/user/plugins/geoip-update/GeoLite2-Country.tar.gz` after you rotated the key?

**Comment by un99known99** [comment]
@LeoColomb  yes, it is not there

root@pi[/var/www/yourls/user/plugins/geoip-update] # ll GeoLite2-Country.tar.gz
ls: cannot access 'GeoLite2-Country.tar.gz': No such file or directory

**Comment by LeoColomb** [comment]
Ref https://github.com/tronovav/geoip2-update/issues/14

**Comment by LeoColomb** [comment]
Closing in favor of:
* https://github.com/tronovav/geoip2-update/issues/14
* https://github.com/ozh/yourls-geoip-update/pull/8
