### ISSUE TITLE
Inconsistent data type of statusCode in API response

### ISSUE THREAD

**Issue by ms4sman** [YOURLS/YOURLS#3755]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://docs.yourls.org/guide/troubleshooting/first-steps.html) and [frequent issues](https://docs.yourls.org/guide/troubleshooting/frequent-issues.html) guides.

### Version

1.9.2

### Description

In the API response for shortening a URL, if the request is successful, the statusCode in the JSON response is an integer. But in the case of an error, like the URL already having been shortened, the statusCode is returned as a string in the JSON. 

### Expectation

I would think it should be consistently one data type or the other.

### Reproduction steps

Make a shorten API call for a new URL. The statusCode will be an integer in the response JSON. Now try to shorten the same URL again. In the error response the statusCode is now a string.

### Context

I'd expect that both should be either an integer OR a string.

**Comment by dgw** [comment]
> I would think it should be consistently one data type or the other.

As would I, and there are comments in the code supporting this:

https://github.com/YOURLS/YOURLS/blob/aed6bb9a5ad5ea79ff419cae103188ea8ac8a0a3/includes/functions-shorturls.php#L15-L16

Since it seems like strings are expected, I have made those changes and opened #3756 for the other maintainers to review.
