### ISSUE TITLE
Login directly at the domain root, not under `/admin/`

### ISSUE THREAD

**Issue by cclove845** [YOURLS/YOURLS#3759]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Summary

建议可设置在二级域名下直接打开后台登陆页面，不需要在 [域名/admin下登陆。
![QQ截图20240516122651](https://github.com/YOURLS/YOURLS/assets/67997283/7d82eeff-5daf-4569-b64a-524bb60039d6)

### Motivation

更方便登陆后台，缩短网址。

**Comment by dgw** [comment]
_Please note, our team cannot generally process issues in languages other than English (or for some of us, French)._

You can easily redirect `/` to `/admin/` through your web server configuration or with a few lines of PHP at `/index.php`. YOURLS leaves the domain root free on purpose so each user can put whatever they would like there.
