### ISSUE TITLE
It is recommended to open the background login page directly under the domain name, without logging in under [domain name/admin].

### ISSUE THREAD

**Issue by cclove845** [YOURLS/YOURLS#3760]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Summary

It is recommended to open the background login page directly under the domain name, without logging in under [domain name/admin].
![331048401-7d82eeff-5daf-4569-b64a-524bb60039d6](https://github.com/YOURLS/YOURLS/assets/67997283/17677863-999b-41c9-b817-8cd17435c7bc)

### Motivation

Accessing the website is more convenient.

**Comment by dgw** [comment]
Thank you for re-filing this issue in English. However, the answer is the same as in #3759: This is trivial to set up for users who want it, and YOURLS can continue to leave the domain root free for this and/or any other desired customizations.
