### ISSUE TITLE
Multiple short links redirect to the same site.

### ISSUE THREAD

**Issue by williamcanon1** [YOURLS/YOURLS#3775]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Summary

I hope to change this mechanism.

### Motivation

I use YOURLS and Nextcloud simultaneously. When some Nextcloud links become invalid, I change the YOURLS short links to redirect to my main site. However, it notifies me that the content already exists in the database, causing the change to fail.

**Comment by dgw** [comment]
See #2411 and several other threads. This is asked at least once every month or two.
