### ISSUE TITLE
Can we have a middle page with timer?

### ISSUE THREAD

**Issue by tasinone** [YOURLS/YOURLS#3790]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Summary

Add a middle page with a countdown timer.

### Motivation

This will give us a chance to use ads on our link-shorter website. 

### Describe the solution

Suppose I click the short link, then it will take me to another page. This page has a countdown timer. Once the countdown finished a GO button appeared. I clicked the GO button and it will take me to the destination page. 

1. We should be able to turn this feature on and off in the settings. Because not everyone needs this feature.
2. We should be able to set the time for the timer in the settings.
3. We should be able to use ads on this page. Like banner ads, and pop-unders.

**Comment by dgw** [comment]
This is plugin territory. [The "Safe Redirect" plugin](https://github.com/imydou/yourls-safe-redirect) listed on [Awesome YOURLS](https://awesome.yourls.org/) already implements something similar.
