### ISSUE TITLE
Could we have plugin or feature to customize footer?

### ISSUE THREAD

**Issue by ivancarlosti** [YOURLS/YOURLS#3792]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Summary

I am looking to customize the footer of standard layout, but I do not found anything like this

### Motivation

Customize footer, in my case, I am looking to add a privacy policy text

### Describe the solution

A plugin or a feature on YOURL would be awesome

**Comment by dgw** [comment]
This is already [possible with a plugin](https://yourls.org/docs/guide/extend/possible-with-a-plugin) using [the `html_footer_text` filter](https://github.com/YOURLS/YOURLS/blob/41ff6adf5404e762fc1700e3e7091595b6069501/includes/functions-html.php#L158) or [the `html_footer` action](https://github.com/YOURLS/YOURLS/blob/41ff6adf5404e762fc1700e3e7091595b6069501/includes/functions-html.php#L166).

Adding text to the footer using the `html_footer_text` filter would be very similar to [the practical example of adding text to the title](https://yourls.org/docs/development/hooks#practical-example-of-use) as shown in YOURLS' documentation.

**Comment by ivancarlosti** [comment]
Oh my, works perfectly <3
