### ISSUE TITLE
Put it into a Docker 

### ISSUE THREAD

**Issue by ally9335** [YOURLS/YOURLS#3794]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Summary

How come that no one has created a Docker container for it thus far? Over the course of 7 years

### Motivation

...

**Comment by ozh** [comment]
https://www.google.com/search?q=yourls+docker

**Comment by ally9335** [comment]
But should a dockerfile or composer be in this repository?

**Comment by LeoColomb** [comment]
Dockerfile in the main repository is as standard as requesting an existing feature with a passive-aggressive tone is a good idea.

**Comment by ally9335** [comment]
Good idea? I knew it! You owe me money then.
