### ISSUE TITLE
API Call with & in the long URL

### ISSUE THREAD

**Issue by BPJustReboot** [YOURLS/YOURLS#3798]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://docs.yourls.org/guide/troubleshooting/first-steps.html) and [frequent issues](https://docs.yourls.org/guide/troubleshooting/frequent-issues.html) guides.

### Version

1.9.2

### Description

I've got everything working correctly and its awesome, thank you, however when I'm posting URLS forms from MS as pre-filled URL links they have the & sign in the url to split the request. Do you guys know if there is a way round this as the API call code uses the & sign to split the different functions. 

### Expectation

Ideally could the API be changed or a quick fix to allow the URL to contain & signs

### Reproduction steps

Through the web page, the URL works, but using the API call it doesn't. Any URL that is posted with the & inside doesn't get completed correctly.

**Comment by BPJustReboot** [comment]
Just in case anyone else has this issue, I replaced the & sign with %26 as per the URL escape codes.

[URL Escape Codes](https://docs.microfocus.com/OMi/10.62/Content/OMi/ExtGuide/ExtApps/URL_encoding.htm#:~:text=URL%20escape%20codes%20for%20characters,%27%3CMy%20title%3E%27%20.)

**Comment by ThanhPhongPhan** [comment]
***@***.***
***@***.***

Vào 18:17, Th 5, 22 thg 8, 2024 BPJustReboot ***@***.***> đã
viết:

**Comment by ThanhPhongPhan** [comment]
0939368520

***@***.***

Vào 23:56, Th 5, 22 thg 8, 2024 Phong Phan ***@***.***>
đã viết:
