### ISSUE TITLE
Bulk addition of short URLs

### ISSUE THREAD

**Issue by cdaters** [YOURLS/YOURLS#3808]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Summary

Allow for the bulk creation of short URLs for target original URLs .

### Motivation

The motivation for this is to facilitate the rapid deployement of a quantity of short URLs to target original URLs at once.

### Describe the solution

In the administrative side of the web app, there would be a "Bulk Operations" area that would take a CSV (or similar) file, and upon clicking submit, would parse through the file and create the relative short URL to target original URL mapping appropriately.

This feature might also facilitate the creation of segregating short URLs into groupings such that you may utilize to keep (lets call them projects) separate from one another...

**Comment by dgw** [comment]
This is an existing plugin: https://github.com/vaughany/yourls-bulk-import-and-shorten

You can find it and more on the Awesome List: https://awesome.yourls.org.

**Comment by cdaters** [comment]
Nevermind...I see this functionality is provided via a plugin.
