### ISSUE TITLE
cannot post new URL when http:// used in the address

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#392]
This is a **COPY** of **Issue 392: [cannot post new URL when http:// used in the address](http://code.google.com/p/yourls/issues/detail?id=392)**, filed on Google Code before the project was [moved on Github](https://github.com/ozh/google-issues-to-github).
- Submitted on 2010-07-05T14:07:46.000Z by [andrewrg...@gmail.com](http://code.google.com/u/117708152110588912657/)
- Status: Invalid

Please **review** the original issue and especially its comments. **Comments here on closed issues will be ignored**. Thanks.
## Original description

```
Follow on from issues 20 and 23 from some time ago

in 1.4.3 AND 1.5 when posting a new URL, the "shorten the URL" graphic keep spinning and does nothing if the address has a leading http:// in it

ie if the default http:// is deleted and the address is entered WITHOUT http:// it does post

**What steps will reproduce the problem?**
1. as per above - have http:// in the long URL
2. change browser to IE8, Firefox, or Chrome - same happens
3. Fresh install on new server of 1.5 beta - release 454 or 1.4.3 - same issue

What is the expected output? 

URL being shortened and added to the list

What do you see instead?
spinning AJAX graphic 

**Please write in your current versions of YOURLS, Web server, PHP, OS,**
**Browser if applicable, etc...**

Happens with YOURLS: 1.5 beta - release 454 or 1.4.3
Apache version  2.2.15
PHP version 5.2.13
MySQL version   5.1.47
website http://lc.tl


**Please provide any additional information below.**
see also screen shots
```

**Comment by dylanh724** [comment]
http://www.davewooding.com/yourls-not-working/ this is still a known issue as of today with the latest version. Also the link the original post is broken. Adding `newurl = newurl.replace(“http://”, “”);` allowed me to finally DELETE a url, but not add.
