### ISSUE TITLE
Allow separate accounts to only show that user's links

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#419]
This is a **COPY** of **Issue 419: [Allow separate accounts to only show that user's links](http://code.google.com/p/yourls/issues/detail?id=419)**, filed on Google Code before the project was [moved on Github](https://github.com/ozh/google-issues-to-github).
- Submitted on 2010-08-02T08:51:48.000Z by [ytlev...@gmail.com](http://code.google.com/u/114592818866855309941/)
- Status: Invalid

Please **review** the original issue and especially its comments. **Comments here on closed issues will be ignored**. Thanks.
## Original description

```
It would be pretty cool if we could make separate accounts for different people with YOURLS, and each account would only show links shortened with that user/account.
Thanks for all the good work!
```

**Comment by DJHeartFeelings** [comment]
I would like to add more Users to my Page so they can use Yourls

**Comment by ozh** [comment]
This may be a feature at some point. In the meantime check the plugins, there's something related
