### ISSUE TITLE
Plugins disabled on their own (1.5-beta)

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#427]
This is a **COPY** of **Issue 427: [Plugins disabled on their own (1.5-beta)](http://code.google.com/p/yourls/issues/detail?id=427)**, filed on Google Code before the project was [moved on Github](https://github.com/ozh/google-issues-to-github).
- Submitted on 2010-08-03T23:04:01.000Z by [dannydin...@gmail.com](http://code.google.com/u/105652231092628030005/)
- Status: Invalid

Please **review** the original issue and especially its comments. **Comments here on closed issues will be ignored**. Thanks.
## Original description

```
**What steps will reproduce the problem?**
1. Enable plugins
2. Wait and return later
3. Plugins are disabled

**What is the expected output? What do you see instead?**
Plugins are disabled when I return later

**Please write in your current versions of YOURLS, Web server, PHP, OS,**
**Browser if applicable, etc...**
Using 1.5-beta 
Centos5 VPS, Firefox 3.6.8


**Please provide any additional information below.**
This issue may have occurred when restarting httpd and mysql (IE rebooting the VPS), but it has happened when they were running the whole time, and they have stayed enabled when rebooting aswell.

The entry for active_plugins under yourls_options in the mysql database is 
a:4:{i:0;s:26:"hyphens-in-urls/plugin.php";i:1;s:25:"sample-toolbar/plugin.php";i:2;s:25:"random-keyword/plugin.php";i:3;s:31:"quickshare-on-tumblr/plugin.php";}
```

**Comment by liruqi** [comment]
Occurred on my server for *Random Keywords* plugin.

**Comment by dgw** [comment]
@liruqi please open a new issue with your setup's details. This one is almost six years old.
