### ISSUE TITLE
MIGRATION FROM MYSQL TO POSTGRESQL 

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#448]
This is a **COPY** of **Issue 448: [MIGRATION FROM MYSQL TO POSTGRESQL ](http://code.google.com/p/yourls/issues/detail?id=448)**, filed on Google Code before the project was [moved on Github](https://github.com/ozh/google-issues-to-github).
- Submitted on 2010-08-16T13:52:05.000Z by [spirito...@gmail.com](http://code.google.com/u/110628238711643556045/)
- Status: WontFix

Please **review** the original issue and especially its comments. **Comments here on closed issues will be ignored**. Thanks.
## Original description

```
hello,

i work on the 1.4.3.
i have some trouble to migrate the DB .

Do you plan a Postgresql or Oracle Migration ?
If yes for witch version ?

Best regards,

SOGF
```

**Comment by noplanman** [comment]
Hope you don't mind me reopening this, as opposed to creating a new issue.

Is this on the roadmap at all?

Or is it up to the user to change all SQL queries and some other code to make it work? 😁

**Comment by ozh** [comment]
It should be rather easy to make as a plugin, similar to the one I did for SQLite https://github.com/ozh/yourls-sqlite

**Comment by noplanman** [comment]
@ozh Ok, will have a look into that, thanks! 😊

**Comment by doronbehar** [comment]
Is there a chance an article could be added to the wiki with full instructions showing what to do in order to use `postgresql` instead of `mysql` for this?

**Comment by ozh** [comment]
https://github.com/ozh/yourls-postgresql
