### ISSUE TITLE
Generate random short url instead of incrementing from 1

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#513]
This is a **COPY** of **Issue 513: [Generate random short url instead of incrementing from 1](http://code.google.com/p/yourls/issues/detail?id=513)**, filed on Google Code before the project was [moved on Github](https://github.com/ozh/google-issues-to-github).
- Submitted on 2010-10-08T06:30:50.000Z by [srhn...@gmail.com](http://code.google.com/u/103273643791762893580/)
- Status: Invalid

Please **review** the original issue and especially its comments. **Comments here on closed issues will be ignored**. Thanks.
## Original description

```
So for example, when you shorten a URL from a fresh installation, have the ability to set a minimum length (for example 3) and have it create a totally random url like so http://nims.me/x4s instead of starting at http://nims.me/1 and incrementing.

This would prevent people from just incrementing and finding out all the shortened URL's that are generated.
```

**Comment by zhilevan** [comment]
Any Proceed? 
I haven't found any configuration for this and by default  `/1` is applied,

**Comment by dgw** [comment]
This is not only [possible with a plugin](https://github.com/YOURLS/YOURLS/wiki/Possible-With-A-Plugin), but it's [an existing plugin](https://github.com/YOURLS/random-keywords) listed on the official [plugin list](https://github.com/YOURLS/awesome-yourls).

Random keywords have come up many times in the issue history of this project, so please don't hesitate to search as hard as you can. Chances are whatever you want to do next has already been done, too. :)
