### ISSUE TITLE
Allow localization (translation) of the interface

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#52]
This is a **COPY** of **Issue 52: [Allow localization (translation) of the interface](http://code.google.com/p/yourls/issues/detail?id=52)**, filed on Google Code before the project was [moved on Github](https://github.com/ozh/google-issues-to-github).
- Submitted on 2009-09-01T15:25:56.000Z by [ozh...@gmail.com](http://code.google.com/u/113077239472542905682/)
- Status: Done

Please **review** the original issue and especially its comments. **Comments here on closed issues will be ignored**. Thanks.
## Original description

```
Not high priority but will do this at some point
```

**Comment by lupa18** [comment]
hello ! can we translate it right now ?

**Comment by LeoColomb** [comment]
@lupa18 See https://github.com/YOURLS/YOURLS/wiki/YOURLS-in-your-language#translate-yourls

**Comment by lupa18** [comment]
perfect ! it works.. thanks !!
