### ISSUE TITLE
Multi Domain Support

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#560]
This is a **COPY** of **Issue 560: [Multi Domain Support](http://code.google.com/p/yourls/issues/detail?id=560)**, filed on Google Code before the project was [moved on Github](https://github.com/ozh/google-issues-to-github).
- Submitted on 2010-11-09T07:16:51.000Z by [bkere...@gmail.com](http://code.google.com/u/115750270177636397262/)
- Status: Invalid

Please **review** the original issue and especially its comments. **Comments here on closed issues will be ignored**. Thanks.
## Original description

```
I think it would be amazing if Yourls offered support for multiple domains for instance a user who signs up could use a default short url like   my.ly or they could use their own domain like them.ly this is one of the most amazing features that bit.ly currently offers is support for using your own domain instead of bit.ly and if people could simply come to my site and signup and use their own domain god that would rock because open source YOURLS would rock bit.ly and I would stop using bit.ly all together.




**Any idea on how it could be implemented? (interface, code, whatever)**
I imagine that it could be setup so that a user creates a cname record to the main Yourls default short name and then it begins working.... im sure it would require a lot of backend work.... :)
```

**Comment by toleabivol** [comment]
Hi , thanks for great tool.
Is this feature still in the roadmap ?
Keeping one install/docroot per domain only with a change in config seems not good practice.

**Comment by leech24** [comment]
good idea
and thanks
i will wait it,multi domain

**Comment by mauwiks** [comment]
Is there a way to use multiple domains within a single installation but the other domains are in different servers? Thanks for the feedback soon

**Comment by dgw** [comment]
@mauwiks If the domain is pointed to a different server, how do you propose YOURLS should receive the requests?

**Comment by alexander7567** [comment]
Instead of having two sets of files and two different config files, I just did this in my single config file.. 

` if ($_SERVER['HTTP_HOST'] == 'nice.name') {
     define( 'YOURLS_SITE', 'http://nice.name' );
 } else {
    define( 'YOURLS_SITE', 'http://also-nice-but-long.nice.name' );
}`

Not sure if there are any other implications to take into consideration, but this seems to work for me wihtout having to maintain two copies of the site.

**Comment by rinogo** [comment]
I was wondering why my CNAME wasn't working. @alexander7567, your solution did the trick! Thanks!

In case it helps others, I adapted @alexander7567's approach to be a little less verbose if you're adding a bunch of domains:

```
if(in_array(strtolower($_SERVER["HTTP_HOST"]), array("also-nice-but-long.nice.name", "also-nice-but-long-2.nice.name", "also-nice-but-long-3.nice.name"))) {
	define("YOURLS_SITE", "https://" . strtolower($_SERVER["HTTP_HOST"]));
} else {
	define("YOURLS_SITE", "https://nice.name");
}
```

**Comment by denisskuzickins** [comment]
This one will work

$allowed_hosts = ['domain1.com, 'domain2.com', 'domain3.com'];

$host = $_SERVER['HTTP_HOST'] ?? 'dkho.st';
$host = strtolower(preg_replace('/:\d+$/', '', $host));

if (!in_array($host, $allowed_hosts, true)) {
    $host = 'domain1.com';
}

define('YOURLS_SITE', 'https://' . $host);
