### ISSUE TITLE
inputting url such as http://google.com yields http://http%3A%2F%2Fgoogle.com/

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#601]
This is a **COPY** of **Issue 601: [inputting url such as http://google.com yields http://http%3A%2F%2Fgoogle.com/](http://code.google.com/p/yourls/issues/detail?id=601)**, filed on Google Code before the project was [moved on Github](https://github.com/ozh/google-issues-to-github).
- Submitted on 2010-12-05T23:44:55.000Z by [jschwa...@gmail.com](http://code.google.com/u/106862481482946799941/)
- Status: Invalid

Please **review** the original issue and especially its comments. **Comments here on closed issues will be ignored**. Thanks.
## Original description

```
I have two instances of yourls 1.5 running with separate databases.  One works perfectly as expected, the other not.

**What steps will reproduce the problem?**
1. Navigate to admin page.
2. Input http://google.com as URL
3. Push shorten URL

**What is the expected output? What do you see instead?**
It should say that the long URL is http://google.com, instead it shows http://http%3A%2F%2Fgoogle.com/ which certainly doesn't work.  Visiting previously created links still works as expected, though.

**Please write in your current versions of YOURLS, Web server, PHP, OS,**
**Browser if applicable, etc...**
YOURLS 1.5.  The odd thing is that another install works.

**Please provide any additional information below.**
The install that is no longer working was at one point running the Hyphens plugin.
```

**Comment by sunilnbhavsar24-lgtm** [comment]
Hi
