### ISSUE TITLE
Lost Admin Password No Forgot Password option

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#620]
This is a **COPY** of **Issue 620: [Lost Admin Password No Forgot Password option](http://code.google.com/p/yourls/issues/detail?id=620)**, filed on Google Code before the project was [moved on Github](https://github.com/ozh/google-issues-to-github).
- Submitted on 2010-12-23T07:44:47.000Z by [alan@searchmarketingwisdom.com](http://code.google.com/u/alan@searchmarketingwisdom.com/)
- Status: Invalid

Please **review** the original issue and especially its comments. **Comments here on closed issues will be ignored**. Thanks.
## Original description

```
I have v. 1.4.3 installed under my own domain.  I had to get a new laptop today and lost all my retained Firefox logins - and can't remember the password I used when I installed Yourls for my own shortener. And there's no "forgot password" option to get into admin! OMG how am I supposed to get into my own shortener now? 
```

**Comment by JayHoltslander** [comment]
Arrived here while Googling the answer to this dilemma. This was no help.

**Comment by dgw** [comment]
Changing the user password stored in YOURLS' configuration file will always be the way to solve this: https://yourls.org/docs/guide/essentials/credentials#i-dont-remember-my-password--i-want-to-change-it
