### ISSUE TITLE
Plugin Not Working - Allow Hyphens in Short URLs

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#687]
This is a **COPY** of **Issue 687: [Plugin Not Working - Allow Hyphens in Short URLs](http://code.google.com/p/yourls/issues/detail?id=687)**, filed on Google Code before the project was [moved on Github](https://github.com/ozh/google-issues-to-github).
- Submitted on 2011-02-11T19:24:34.000Z by [yournextoffice@gmail.com](http://code.google.com/u/yournextoffice@gmail.com/)
- Status: Invalid

Please **review** the original issue and especially its comments. **Comments here on closed issues will be ignored**. Thanks.
## Original description

```
**What steps will reproduce the problem?**
1.Visit ucflink.me
2.Paste in your URL
3.Create custom URL with hyphen (ucflink.me/test-this)

**What is the expected output? What do you see instead?**
Expected: Link to work
Actual Result: Not Found Error Page

**Please write in your current versions of YOURLS, Web server, PHP, OS,**
**Browser if applicable, etc...**
YOURLS v1.5
PHP 5.2.14
OS X
Firefox


**Please provide any additional information below.**
I have activated the plugin, yet it doesn't seem to accept custom urls with Hyphens in them. I have not been able to find a solution to this problem. Please assist me.
```

**Comment by seventhsite** [comment]
There is another problem with hyphen's at the end of the link. For example http://ali.onl/2-0 is worked, but http://ali.onl/2z- is work like http://ali.onl/2z, but http://ali.onl/2z- have another long link.
