### ISSUE TITLE
Admin Page Does Not Ask For Username/Password To Access

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#776]
This is a **COPY** of **Issue 776: [Admin Page Does Not Ask For Username/Password To Access](http://code.google.com/p/yourls/issues/detail?id=776)**, filed on Google Code before the project was [moved on Github](https://github.com/ozh/google-issues-to-github).
- Submitted on 2011-04-20T23:40:14.000Z by [agcool...@hotmail.com](http://code.google.com/u/103672662775831444807/)
- Status: Invalid

Please **review** the original issue and especially its comments. **Comments here on closed issues will be ignored**. Thanks.
## Original description

```
**What steps will reproduce the problem?**
1.Going to www.subdomain.site.com/admin/
**2.**
**3.**

**What is the expected output? What do you see instead?**
EXPECTED: Request for admin username and password
INSTEAD: Straight to admin panel thing

**Please write in your current versions of YOURLS, Web server, PHP, OS,**
**Browser if applicable, etc...**
YOURLS 1.5

**Please provide any additional information below.**
Pretty much, the title explains everything... everybody has access to the Admin features! How can i make it so that they cannot go onto it without a username and password?
```

**Comment by ameralzarouni** [comment]
I have the same problem, how do I fix it?

**Comment by LeoColomb** [comment]
Recheck your `config.php` and be sure a user is well defined, and try reinstalling YOURLS.
