### ISSUE TITLE
Using YOURLS with a master slave database

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#800]
This is a **COPY** of **Issue 800: [Using YOURLS with a master slave database](http://code.google.com/p/yourls/issues/detail?id=800)**, filed on Google Code before the project was [moved on Github](https://github.com/ozh/google-issues-to-github).
- Submitted on 2011-05-13T05:42:12.000Z by [p...@google.com](http://code.google.com/u/110383835040117885055/)
- Status: Done

Please **review** the original issue and especially its comments. **Comments here on closed issues will be ignored**. Thanks.
## Original description

```
I am trying to use YOURLS with a master and slave database system, so that incase the master fails the slave database will take over. This requires the YOURLS code to shift to querying the slave once the master fails. Is there already some code aimed at this?



I am using the latest version of YOURLS and mysql 5.0 apache 2.2
```

**Comment by vikasbatra** [comment]
Use https://github.com/vikasbatra/YOURLS for master slave config.

**Comment by ozh** [comment]
@vikasbatra looks interesting! but that's a shame you need to fork the whole project to do so :) You should look into packaging this as a plugin, that would be much more beneficial to all!

**Comment by vikasbatra** [comment]
I was in hurry, if you've proper documentation on how to create a plugin. I shall create a plugin for same and publish that.

I've fixed this for my project in no time and shared here....

**Comment by ozh** [comment]
It's all in the wiki https://github.com/YOURLS/YOURLS/wiki
