### ISSUE TITLE
cannot create or delete shortened urls

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#806]
This is a **COPY** of **Issue 806: [cannot create or delete shortened urls](http://code.google.com/p/yourls/issues/detail?id=806)**, filed on Google Code before the project was [moved on Github](https://github.com/ozh/google-issues-to-github).
- Submitted on 2011-05-17T19:24:33.000Z by [mark.b...@lbi.com](http://code.google.com/u/112810644959432506511/)
- Status: Invalid

Please **review** the original issue and especially its comments. **Comments here on closed issues will be ignored**. Thanks.
## Original description

```
i have just installed yourls 1.5.

there are 3 urls there as default, when i click on delete, it asks me to confirm, i press ok and nothing happens.

also, when i try and shorten a url nothing happens.

any help is much appreciated!
```

**Comment by rizalarisona** [comment]
nobody can help for this issue?
