### ISSUE TITLE
passing arguments to a shortened link

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#815]
This is a **COPY** of **Issue 815: [passing arguments to a shortened link](http://code.google.com/p/yourls/issues/detail?id=815)**, filed on Google Code before the project was [moved on Github](https://github.com/ozh/google-issues-to-github).
- Submitted on 2011-05-24T11:42:40.000Z by [marshcon...@googlemail.com](http://code.google.com/u/107595164053570906657/)
- Status: WontFix

Please **review** the original issue and especially its comments. **Comments here on closed issues will be ignored**. Thanks.
## Original description

```
I would like to be able to add some arguments to a shortened link, for example without arguments

    http://abc.yz/sl redirects to http://abc.yz/info.php?id=<blah>

But with arguments

    http://abc.yz/sl?o=1234 redirects to http://abc.yz/info.php?id=<blah>&amp;o=1234

But it seems my arguments after the short link are not being rewritten. Is this possible?
```

**Comment by tayax** [comment]
I'd love to have the answer to this

**Comment by ozh** [comment]
plugin.

**Comment by tayax** [comment]
@ozh Any specific ones? I've tried the 2 I found in the official plugin pages and it doesn't work if the long url already have arguments. I'm trying to add more.
