### ISSUE TITLE
Passing parameters in short urls

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#879]
This is a **COPY** of **Issue 879: [Passing parameters in short urls](http://code.google.com/p/yourls/issues/detail?id=879)**, filed on Google Code before the project was [moved on Github](https://github.com/ozh/google-issues-to-github).
- Submitted on 2011-07-19T07:33:30.000Z by [samuel...@gmail.com](http://code.google.com/u/100901050000746077457/)
- Status: WontFix

Please **review** the original issue and especially its comments. **Comments here on closed issues will be ignored**. Thanks.
## Original description

```
Hi!

I suggest, it is possible add the posibility to pass parameters in short urls?

example:

http://u.com/a4dx?Myparameter=59

real url:

www.hix.com/?Myparameter=59

=) it is ? thx
```

**Comment by projectje** [comment]
I don't read any reasons for why this would not be supported?

I wanted to make a shortlink to https://github.com/yourls/yourls/issues/{parameter} 

Where parameter is a variable. 

So this would i guess require ... a plugin ?

**Comment by ozh** [comment]
Exactly. There are probably plugins doing this already, see https://github.com/YOURLS/awesome-yourls and https://github.com/YOURLS/YOURLS/wiki/Possible-With-A-Plugin

**Comment by projectje** [comment]
Thanks! Understood. (Also helpful for others because THIS page is the #1 when searching for "yourls parameters in url" in Google)
