### ISSUE TITLE
Can I shorten my email address?

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#881]
This is a **COPY** of **Issue 881: [Can I shorten my email address?](http://code.google.com/p/yourls/issues/detail?id=881)**, filed on Google Code before the project was [moved on Github](https://github.com/ozh/google-issues-to-github).
- Submitted on 2011-07-21T20:53:59.000Z by [tex...@gmail.com](http://code.google.com/u/110801048224912402701/)
- Status: Done

Please **review** the original issue and especially its comments. **Comments here on closed issues will be ignored**. Thanks.
## Original description

```
I'd like to have a link that says texs.org/email, but it appears that YOURLS forces an http:// in front of everything.

If the answer is "No way we'll ever do that", then I'd love to hear some suggestions, I tried this: http://scr.im/texjer, but I didn't like it because it doesn't take you directly to the email.

Thanks,

Tex



Keywords:
Email Address shortener, Mailto:, HELP, Awesome Service
```

**Comment by vrepub** [comment]
1. Enter the email address just like you would a URL EXCEPT LIKE THIS:   mailto:emample@example.com
2. Enter custom short URL:  email (or whatever you want)
3. Click shorten URL button
4.  Voila!

**Comment by ozh** [comment]
See https://github.com/YOURLS/YOURLS/wiki/Custom-protocols
