### ISSUE TITLE
Time is not offsetting from GMT?

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#918]
This is a **COPY** of **Issue 918: [Time is not offsetting from GMT?](http://code.google.com/p/yourls/issues/detail?id=918)**, filed on Google Code before the project was [moved on Github](https://github.com/ozh/google-issues-to-github).
- Submitted on 2011-08-26T22:21:33.000Z by [weightlo...@gmail.com](http://code.google.com/u/108864242428334601254/)
- Status: Invalid

Please **review** the original issue and especially its comments. **Comments here on closed issues will be ignored**. Thanks.
## Original description

```
This is my configuration?

/** Timezone GMT offset */
define( 'YOURLS_HOURS_OFFSET', +1 ); 

I live in UK so offset is +1 but not working .....time is still 6hours behind with above config????? 
```

**Comment by ckrebs** [comment]
This I think is not a GMT offset, but a server time offset.  When set to -5 for USA/New York, I get 5 hours behind now (my server's clock is set to gmt - 5).  When setting it to 0, I get the correct time.

**Comment by ozh** [comment]
Indeed.
